### ISSUE TITLE
BidAskSpreadFilter feature! Also FAST Bid Ask values (computed from ohlcv!)

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#10049]
I have found this fantastic paper https://ssrn.com/abstract=3892335 and python code https://github.com/eguidotti/bidask . 

It calculates the Bid Ask values from OHLCV alone, and in the paper the performance usually meets or exceeds the accuracy of the exchanges! Plus its 10-1000x faster since you DONT needs to query server each time!

We should use this to create a BidAskSpreadFilter. I will probably do this!

**Comment by keithorange** [comment]
```
SpreadFilter[¶](https://www.freqtrade.io/en/stable/plugins/#spreadfilter)

Removes pairs that have a difference between asks and bids above the specified ratio, max_spread_ratio (defaults to 0.005).

Example:

If DOGE/BTC maximum bid is 0.00000026 and minimum ask is 0.00000027, the ratio is calculated as: 1 - bid/ask ~= 0.037 which is > 0.005 and this pair will be filtered out.
```

This one uses the exchange bid ask spreads right? So if this works well then it may be unnecessary (Unless the current implementation DOESNT work in backtesting, the estimation would!)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

We do have [spreadFilter](https://www.freqtrade.io/en/stable/plugins/#spreadfilter) - which uses real data.
It doesn't work in backtesting since exchanges don't provide this data.

Calculating spread from (historic!) ohlcv data doesn't really make sense - and the paper even mentions that it neglects useful information (e.g. actual trades):

>  Moreover, they consider only a subset of open, high, low, and close prices and neglect potentially useful information to improve the spread estimate.
