### ISSUE TITLE
Difference in adjustment return values

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#10068]
## Describe your environment

Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.7
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2024.03

## Your question

1) Question Summary : 
- The 24.03 update notes state that partial exits can be fully sold using -trade.stake_amount.
- However, there is a difference between selling ⓐ-trade.stake_amount and ⓑfilled stake_amount in backtesting logs.
- For instance, ⓐ results in a "win" in the regular stoploss of the backtesting results log.
- In addition, there are differences in profit, MDD, UnderWater, etc.
2) Code

ⓐ-trade.stake_amount

dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)

if trade.is_short:
    if (count_of_exits == 0) & (np.sum(np.array(long_conditions), axis=0) >= 4):
        return - stake_amount

ⓑ Using fill

count_of_exits = trade.nr_of_successful_exits
dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
last_candle = dataframe.iloc[-1].squeeze()

filled_entries = trade.select_filled_orders(trade.entry_side)
count_of_entries = len(filled_entries)
stake_amount = filled_entries[0].cost

if trade.is_short:
    if (count_of_exits == 0) & (np.sum(np.array(long_conditions), axis=0) >= 4):
        return - stake_amount

Could you tell me about the expected problems?
Or, please tell me what the difference is between ⓐ and ⓑ.

**Comment by stash86** [comment]
either way, the logic for backtest was missed during the last change. Wait for #10067 to be merged

**Comment by xmatthias** [comment]
The backtest logic was (re-)aligned in df2432bc18cb364869ebd7cdbf6893166a3e2e5b.

For the difference between a and b ... in spot markets, there's most likely no difference.
for futures markets - it'll depend. 
"cost" is interpreted differently by exchange - so it's not 100% reliable what it actually contains.
Usually though - it's "amount * average" - which is also how dry-run implements this.

It's however "controlled" by the exchange / ccxt - not something freqtrade sets / calculates itself (at least not in live modes). 

For a leveraged trade, this means that you can have a trade with a stake_amount of 100$ at 5x leverage,
`order[0].cost` would contain 500$ ... as the trade is 5x leveraged, and the actual amount you got is a trade valued at 500$.
Stake-amount is however still 100$ - as that's what the accounts collateral is - and it's also what's expected for a "full" exit (`-500` would be ignored, as it's bigger than the stake and therefore assumed to be a calculation error).

"most" supported futures exchanges apply it this way - which is why we aligned dry-run to this behavior - though this is not something we actively check for as "cost" is not relevant for operational purposes - and just kept for informational purposes in the order object (the exchange returns it - no reason not to keep it).
