### ISSUE TITLE
include "api_server" in command line option

### ISSUE THREAD

**Issue by efirvida** [freqtrade/freqtrade#10091]
Hi I'm using frequtrade in virtual environment not in docker container and I think it wold be very handly if `api_server.listen_ip_address` and `api_server.listen_port` can be passed as command line argument. With this option I can create multiple bots then included in FreqUI without having to add several config files only to change the `listen_port`

Rigth now I'm using it like this:

```
EXCHANGE="binance"
freqtrade trade -c user_data/configs/${EXCHANGE}_80.json -c user_data/configs/trading_mode-futures.json --logfile logs/${EXCHANGE}_futures_MyStrategy.log   -s MyStrategy   --db-url postgresql:///futures_MyStrategy              

```

then the ` user_data/configs/${EXCHANGE}_80.json` looks like this:

```
{
  "dry_run_wallet": 100,
  "bot_name": "Freqtrade Binance",
  "dry_run": true,
  "add_config_files": [
    "config.json",
    "exchange-binance.json",
    "private.json"
  ],
  "api_server": {
    "listen_port": 8080
  }
}
```

But If I want to run another strategy I have to copy/paste this config only to change the `listen_port`, maybe that option exsit and I don´t know how to use it.

**Comment by xmatthias** [comment]
Freqtrade offers several solutions to this problem already. 
Exposing a selected number of a complex object will not be one of these - not least because this is not the full list of things that need to be changed. For example, if you're using telegram, that **must** be changed as well, otherwise the "later" port will not be properly started.

You can either use the [environment variable](https://www.freqtrade.io/en/stable/configuration/#environment-variables) approach - where the key would look like `FREQTRADE__API_SERVER__LISTEN_PORT`.

Alternatively (probably the approach i'd personally follow)  is to use a minimal, additional [configuration file](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files) - which can only include the section of the config that you'd like changed - and then simply provide this as 2nd configuration (e.g. `--config user_data/config.json --config user_data/config_port_1234.json`).

that 2nd file would look something around the following:

``` json
{
  "api_server": {
    "listen_port": 8080
  }
}
```
