### ISSUE TITLE
How to avoid connection to exchange

### ISSUE THREAD

**Issue by Brvcket** [freqtrade/freqtrade#10100]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.12 (`python -V`)
  * CCXT version: 4.2.91 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, I am interested in creating a project to study the effectiveness of a genetic algorithm for optimizing strategy parameters.

I met the following problem: it is not clear how to make the logic similar to the built-in HyperOpt. 
The main problem is that if you just run backtesting for each candidate (where the candidate is a class with some parameter values), then you have to wait each time to connect to the exchange, which slows everything down hundreds of times. What can I do? Is there any way to avoid connecting to the exchange? (In fact, it is not needed more than once, and in general, it is possible to do without connection to the exchange by specifying default values.)
Alternatively, it would help me if you could suggest that maybe I should override some part of the source code for my purposes.

**Comment by xmatthias** [comment]
The connection to the exchange is necessary to fetch some uptodate market data (more specifically, markets, the limits that apply to these markets - and eventually fees).

Freqtrade will only do this once for each hyperopt run - and it's non-optional.

For regular backtesting - you can use `backtesting --strategy-list StratA stratB stratC <...>` to have both the startup - as well as loading the data executed only once.

There's however no plans to apply any form of caching to this - not least because this is changing both per exchange - and over time - and is not fully under our control (what exactly is fetched and needed is controlled by ccxt).
