### ISSUE TITLE
Add new pairlists.method: PromotionRatePairList

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#10127]
There are many pairs with promotion rate on https://www.binance.com/en/fee/tradingPromote.
It would be nice if you could add a new method like this.
I can help by writing python code to get these pairs, but it's quite complicated to implement to your source code.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I don't think this data is available through the binance API, which will make it rather difficult to implement (we'll not add dependencies to libraries like selenium to facilitate parsing from websites - simply because these websites change all the time, and would require constant adjustments).

If it is available through the API, please link to the API documentation for this data here. Otherwise i'll be closing this soon.

For writing pairlists themselfs - it's not that difficult, and has [documentation](https://www.freqtrade.io/en/latest/developer/#pairlists) available.

It'll obviously assume that the data is available through the api / through ccxt.

**Comment by ghost** [comment]
https://www.binance.com/bapi/accounts/v1/public/commission/symbol-activity-list?currentPage=1&pageSize=100
Here is the API

**Comment by xmatthias** [comment]
I think you misunderstood.
I'm sure there's api endpoints for it "someplace" - but as long as they're not documented - they're not api's intended for public use. 
This also means they can break (or be disabled) at any time - and are therefore not suitable, as it's not reliable.

What i mean is a [documented api on the binance APi documentation page](https://binance-docs.github.io/apidocs/spot/en/#introduction) (i couldn't find this here ... but maybe you can find it).

While there is a "commission" endpoint - it requires 1 symbol - and a logged in user - making it unsuitable (it'd be tons of weight - and unavailable in dry-run).

**Comment by xmatthias** [comment]
Going to close this as there doesn't seem to be an official api endpoint for this - and we can't reliably use internal endpoints.

Happy to look at this again should such an endpoint be added - but for the moment, i don't see this as feasible - simply from a support / maintenance perspective (non-documented endpoints can break without warning - as they should only be used by binance internally).
