### ISSUE TITLE
How to get Taker buy volume

### ISSUE THREAD

**Issue by jiangxch** [freqtrade/freqtrade#10120]
how to get Taker buy volume 

<img width="1435" alt="image" src="https://github.com/freqtrade/freqtrade/assets/61080164/6478d996-03b1-4131-9b66-9304876aa7e3">

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade will provide the volumes that are in the default [fetch-ohlcv](https://docs.ccxt.com/#/README?id=ohlcv-structure) response.
This includes standard OHLCV columns - but no further / additional data the exchange MAY include in their  esponse.
For freqtrade, that's simply because ccxt does not provide this info to us (aside from the fact that this is not standardized, and would not be available for most exchanges).
