### ISSUE TITLE
Share exit signal from one pair to another

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#10141]
## Describe your environment

  * Operating system: __Docker__
  * Python Version: ___Python 3.12.2
  * CCXT version: ____ccxt==4.2.87
  * Freqtrade Version: _docker-2024.4-dev-15cbca51
  
## Your question

Could you please advise the best method to evaluate conditions for exit and share exist signal from one pair to use it with different pair as exit condition.

**Comment by stash86** [comment]
Use one or more global variable(s)

**Comment by darioneto** [comment]
thanks, do you think I could find any relevant doc which describes this process in more details?

**Comment by xmatthias** [comment]
Not really - and i don't think it's something we should be adding to the documentation, either.

You'll usually want to treat pairs independently (why would a good running pair be sold because a random other pair is doing badly?).

What you might be looking for is informative pairs - which can get you signals from a specific, key pair (btc / eth) into every dataframe - signaling a potential longer-term trend reversal.
Selling pairA based on how PairB's trade is performing will not be a good strategy i'd think.

**Comment by darioneto** [comment]
yeah pretty much, the reason is to utilize already evaluated and generated signal from a key pair and then "forward/reuse" it on SOL for instance. So you'd recommend using  informative pairs method moving forward?

**Comment by xmatthias** [comment]
i'd say so, yes

while you could use [`get_analyzed_dataframe()`](https://www.freqtrade.io/en/stable/strategy-customization/#get_analyzed_dataframepair-timeframe) - you can't rely on what you get within populate_* methods due to the evaluation order.
Pairs with an open trade usually evaluate first - pairs without later - so when it's turn for PairA - you can't be sure if SOL already evaluated or not, so you might get the current info - or past info - depending on the evaluation sequence.

**Comment by darioneto** [comment]
withough example chances are very low to figure it out, anyways thanks for suggestions , maybe next year I could get it to work lol

**Comment by xmatthias** [comment]
well there's plenty of examples in the documentation about informative pairs (which is the approach i'd strongly recommend to go with this to avoid problems).
It's however up to you to [read these](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) (make sure to expand the "colored boxes" - which do include several examples) :laughing: 

Please understand that we'll not provide tailor-suited examples for individual usecases - it's a process of learning and adapting the examples for your needs...
