### ISSUE TITLE
How to enable sandbox mode on OKX exchange

### ISSUE THREAD

**Issue by notgood0937** [freqtrade/freqtrade#10191]
How to enable sandbox mode on OKX exchange

**Comment by xmatthias** [comment]
There's little point in using exchange sandboxes, which is why we removed official support for them.

Sandboxes usually have very little / no volume - so whatever strategy you're trying to run there, results are not going to hold true.

Instead, freqtrade provides the [dry-run](https://www.freqtrade.io/en/stable/configuration/#using-dry-run-mode) - which will simulate all orders within freqtrade without requiring API keys - which is the recommended way to test strategies without risking your own money.

**Comment by notgood0937** [comment]
Thank you
