### ISSUE TITLE
Mutually exclusive execution of populate_entry_trend and populate_exit_trend

### ISSUE THREAD

**Issue by bsshor** [freqtrade/freqtrade#10231]
Hello, as shown in the pseudo-code below, there are 2 condition groups set up when exit is allowed, and I want to use the one in exit to be executed first and then the one in entry to be executed when condition groups 1 or 2 are met at the same time, is there any freqtrade that has a corresponding scheme in it?
```
def populate_entry_trend():
    dataframe.loc[
            (
                # Condition group 1
            ),
            'enter_long'] = 1
    dataframe.loc[
            (
                # Condition group 2
            ),
            'enter_short'] = 1    
def populate_exit_trend():
    dataframe.loc[
            (
                # Condition group 2
            ),
            'exit_long'] = 1
    dataframe.loc[
            (
                # Condition group 1
            ),
            'exit_short'] = 1
```

**Comment by xmatthias** [comment]
Please fill out the issue template. Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

This is your second violation in this regard within the same day after being reminded about the same thing in https://github.com/freqtrade/freqtrade/issues/10230#issuecomment-2120940823 - less than 2 hours before opening this issue.

Therefore, please treat this as a warning.

---

Please read the [documentation](https://www.freqtrade.io/).
I'd recommend to read it once from top to bottom to get an understanding of the features freqtrade offers - and how it actually works.

The [bot execution logic](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) is explained in these docs, too.
The execution logic will not change just because you'd like it to.

That said - the `populte_*` methods should be treated as what they are - mental helpers for the most part (except for hyperopt - refer to the docs as to why).

What actually counts is which columns (and their content) come out at the end of the 3 calls. How you reach that goal (all in one method, split as in the documentation) is essentially up to you, and your knowledge about pandas.
