### ISSUE TITLE
Re-asigning values to populate indicators dataframe from custom exit

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#10238]
## Describe your environment

  * Operating system: Linux mint
  * Python Version: 3.10.4
  * CCXT version: 4.2.82
  * Freqtrade Version: 2024.3
  
## Your question
Would freqtrade allow returning values from last canlde or analyzed dataframe in the custom exit callback to populate indicators dataframe? I would like to do something like this:
```
if last_candle['rsi-05'] > last_candle['rsi-07']:
    dataframe.loc[
                 ['enter_long', 'enter_tag']] = (1, 'first_buy')
```

**Comment by xmatthias** [comment]
"allow" is relative.
It's a dataframe - so that's not read only - so your code will not fail per se.

What you get in callbacks is however a copy - so while you can write / change it / delete it - your changes will be thrown away once the callback exits, and the next callback will get a new, fresh copy.

This is intentional - as modification from within a callback would cause repainting, ghost signals, and a heapload of other, non-nice issues.
