### ISSUE TITLE
FreqAI installation issue

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10244]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.4 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I get the error on the image with and without the Microsoft Visual Studio Build Tools, using the command:
pip install -r requirements-freqai.txt

TA Lib is installed:
Requirement already satisfied: TA-Lib in c:\users\a1\.conda\envs\freqtrade\lib\site-packages (0.4.19)
Requirement already satisfied: numpy in c:\users\a1\.conda\envs\freqtrade\lib\site-packages (from TA-Lib) (1.26.0)

I continue to evaluate, and I post any news asap.

(Running bots in the usual way works fine)

![FAI](https://github.com/freqtrade/freqtrade/assets/34372534/a7caaac8-b3c1-4e5a-bc4e-f8ccd738f1df)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
This is not really related to freqAI - but simply to the fact that windows requires special treatment.

Please use the [documented way](https://www.freqtrade.io/en/latest/windows_installation/#2-install-ta-lib) to install ta-lib (from pre-built sources) - and it'll work fine.

The alternative is to have ta-lib (the C library) installed. 
please refer to the ta-lib repository for assistance with that - as so far, i always failed when installing that on windows.

**Comment by myNextCoder** [comment]
Ok, I understand.
I usually install Freqtrade, by using 2023.2 (with environment.yml), and then I upgrade. With this method I never needed to use the above link. Does the installation of FreqAI go deeper into the system, then?

**Comment by xmatthias** [comment]
Neither.
There's a good reason we no longer support environment.yml - and it's not because it used to work "that great".


FreqAI dependencies can be harder to install on some systems (it's what i'd consider heavy dependencies - some comming in at 500MB downloads, most with C level dependencies, which would probably fail if no wheel were provided).

The error you get has nothing to do with freqAI though - it's ta-lib which needs installing and is missing it's system-level dependencies (since it's not installed via the wheels we provide - and ta-lib itself doesn't provide windows wheels at this point)

**Comment by myNextCoder** [comment]
I thank you, giving you my news, as I am a step further.
