### ISSUE TITLE
freqtrade reports wrong time on telegram

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#10241]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.3.27
  * Freqtrade Version: freqtrade 2024.5-dev-2c740059d
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:
date is reported correctly on the OS
```
root@freqtrade:~# date
Sat 25 May 11:44:05 EEST 2024
```

But it's wrong on telegram, by 3 hours.

<img width="314" alt="Greenshot 2024-05-25 11 45 17" src="https://github.com/freqtrade/freqtrade/assets/528302/b5c28f04-c7d2-47ca-ba0e-3c964c796a82">

I guess it must be a setting somewhere.
How can I fix this?

**Comment by xmatthias** [comment]
Times are in UTC, usually.
That's because also exchanges operate mainly with UTC timezone - so having the time "switch around" would only be confusing as to when things actually happened.


Now your offset looks completely off (it's like - 3 hours 15 minutes) - so it's probably a "device clock is imprecise" problem more than anything else.
