### ISSUE TITLE
Bot stopped trading.

### ISSUE THREAD

**Issue by slowdive42** [freqtrade/freqtrade#10266]
## Describe your environment

  * Operating system: wsl2 ubuntu 22.04
  * Python Version: 3.10.14 (`python -V`)
  * CCXT version: 4.3.27 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.5-dev-acae6e75f (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I run the bot in the bash terminal. After 2024-05-29 00:03:02,629, it stopped outputting and trading. Then, at 2024-05-29 05:48:38,440, I pressed enter in the terminal, and the bot started working again. During this time period, the bot did not execute my trading signals.

2024-05-29 00:01:02,514 - freqtrade.worker - INFO - Bot heartbeat. PID=1281695, version='2024.5-dev-acae6e75f', state='RUNNING'
2024-05-29 00:01:04,281 - freqtrade.wallets - INFO - Wallets synced.
2024-05-29 00:02:02,569 - freqtrade.worker - INFO - Bot heartbeat. PID=1281695, version='2024.5-dev-acae6e75f', state='RUNNING'
2024-05-29 00:03:02,629 - freqtrade.worker - INFO - Bot heartbeat. PID=1281695, version='2024.5-dev-acae6e75f', state='RUNNING'

2024-05-29 05:48:38,440 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ReadError: 
2024-05-29 05:56:30,926 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.

**Comment by xmatthias** [comment]
I've never really seen this happening (and i do run quite some bots).

That said - i run no bot on WSL - and I wouldn't trust it to run a "long-running"  process without interaction, where "keep it running" is key.
WSL is good for development / backtesting / ...  - but i'd consider running a live (or dry) trading bot on it is clearly not recommended.

If you think about it from an infrastructure perspective, you can have 3 components messing with your process in one way or another

* windows (energy settings?)
* hyper-v (thinks it ain't used / saves resources?)
* wsl2 (the linux part)

the  `httpx.ReadError` does (kindof) support this, too - as it's a "Failed to receive data from the network." message.
This part is however running on a separate thread, so wouldn't stop "actual" bot operations from happening.

---

Apart from that - i'd not know where to even start looking - mostly, because i've  never had it happen - but also because there's no information whatsoever (exchange, mode, ...).

If you have some way to reproduce this (in little to no time short time) - or if you got verbose logs (which might point to WHERE it's stuck) - it'd be something to go on - but i doubt looking down that route does make much sense as long as we can't exclude a simple "microsoft did it's thing" problem, causing a freeze in that stack (which i DID have happen in the past, though not with freqtrade).

**Comment by slowdive42** [comment]
> I've never really seen this happening (and i do run quite some bots).
> 
> That said - i run no bot on WSL - and I wouldn't trust it to run a "long-running" process without interaction, where "keep it running" is key. WSL is good for development / backtesting / ... - but i'd consider running a live (or dry) trading bot on it is clearly not recommended.
> 
> If you think about it from an infrastructure perspective, you can have 3 components messing with your process in one way or another
> 
> * windows (energy settings?)
> * hyper-v (thinks it ain't used / saves resources?)
> * wsl2 (the linux part)
> 
> the `httpx.ReadError` does (kindof) support this, too - as it's a "Failed to receive data from the network." message. This part is however running on a separate thread, so wouldn't stop "actual" bot operations from happening.
> 
> Apart from that - i'd not know where to even start looking - mostly, because i've never had it happen - but also because there's no information whatsoever (exchange, mode, ...).
> 
> If you have some way to reproduce this (in little to no time short time) - or if you got verbose logs (which might point to WHERE it's stuck) - it'd be something to go on - but i doubt looking down that route does make much sense as long as we can't exclude a simple "microsoft did it's thing" problem, causing a freeze in that stack (which i DID have happen in the past, though not with freqtrade).

Thank you so much. Do you think using Docker Compose on the Windows platform is a better choice?

**Comment by slowdive42** [comment]
> I've never really seen this happening (and i do run quite some bots).
> 
> That said - i run no bot on WSL - and I wouldn't trust it to run a "long-running" process without interaction, where "keep it running" is key. WSL is good for development / backtesting / ... - but i'd consider running a live (or dry) trading bot on it is clearly not recommended.
> 
> If you think about it from an infrastructure perspective, you can have 3 components messing with your process in one way or another
> 
> * windows (energy settings?)
> * hyper-v (thinks it ain't used / saves resources?)
> * wsl2 (the linux part)
> 
> the `httpx.ReadError` does (kindof) support this, too - as it's a "Failed to receive data from the network." message. This part is however running on a separate thread, so wouldn't stop "actual" bot operations from happening.
> 
> Apart from that - i'd not know where to even start looking - mostly, because i've never had it happen - but also because there's no information whatsoever (exchange, mode, ...).
> 
> If you have some way to reproduce this (in little to no time short time) - or if you got verbose logs (which might point to WHERE it's stuck) - it'd be something to go on - but i doubt looking down that route does make much sense as long as we can't exclude a simple "microsoft did it's thing" problem, causing a freeze in that stack (which i DID have happen in the past, though not with freqtrade).

Thank you so much. I am running multiple bots simultaneously on dry run mode, and only this one got stuck.Do you think using Docker Compose on the Windows platform is a better choice?

**Comment by xmatthias** [comment]
same problem - different thing that controls it, really (still windows with hyper-v).

Best get yourself a VPS - if you can get an oracle free account - their free tier is pretty generous, offering 24G of ram on ARM for nothing.

**Comment by slowdive42** [comment]
> same problem - different thing that controls it, really (still windows with hyper-v).
> 
> Best get yourself a VPS - if you can get an oracle free account - their free tier is pretty generous, offering 24G of ram on ARM for nothing.

Thank you. Is running directly in bash on a VPS stable, or would it be better to use Docker?

**Comment by xmatthias** [comment]
I do both, both work  just fine - as such, it comes up to personal preference.
I find docker easier to install - as it keeps the underlying system clean - but as said, it's personal preference.
