### ISSUE TITLE
why does backtesting not work as live mode does?

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10294]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

When you do paper or live trading via dryMode=True, the results can be significantly worse than in backtesting mode.
This is due to lookahead bias that appears when indicators are calculated for whole tested period and thus the strategy gets to know "the future" of a given pair.

But in live mode the candles are iteratively fed to the strategy as time passes.
So why not do the same in backtesting mode? Like feed iteratively each candle in the backtesting period and allow the strategy to run as if it cannot have any access to "the future" candles?

Is there a pitfall in applying this I'm not aware about? Because this is what live-mode essentially does, is it not? Like feeding each new candle to the algorithm as it appears.
Or is there any limitation in freqtrade library that would prevent one to write such backtesting algorithm?

Thank you!

**Comment by xmatthias** [comment]
the limitation is speed / execution performance - making it no longer useful as you'd wait forever.

To "properly" simulate live (which you can't, really) - you'll have to use a sliding window of ~1000 candles, and move that over the whole testing period - each time calculating all indicators for all pairs for 1000 candles - use the very last signal, throw the rest away, and move to the next candle.

for a 5m backtest of 1month(~8640 candles) - you'd therefore do 8640 x "populate_indicators" - per pair - instead of one time for all 8640 candles (again, per pair).
Performance wise - this has 2 problems - it's slicing a dataframe 1000nds of times (which is slow) - but it's also calculating all indicators again and again (a great waste) for the same candles - though it's really only needing one (but a framework can't know how many back you need - hence it'd need to calculate all).

I did a test with such an algorithm once - a backtest normally taking ~3m turned out to take about 4 hours (iirc) - but the only real "benefit" is to avoid having to think "is this now a lookahead bias" - which is pretty easy if you follow a few very simple rules.

We do have a [list of things to avoid](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) - as well as [several](https://www.freqtrade.io/en/stable/recursive-analysis/) [commands](https://www.freqtrade.io/en/stable/lookahead-analysis/) which can help you avoid lookahead bias. Following these is not hard - neither is running these commands.

**Comment by uplight-dev** [comment]
Thank you for the detailed explanation, however I digress from it.

There are a few reasons:
- one might only want to work with high timeframes like 4h or 1d and a short timerange like 1 month
- the recursive analysis is prone to interpretation(i.e. the EMA indicator being a false-positive). Even if lookahead didn't report any biased indicators, I've recently tried a strategy online with 0% losses in backtest only to later find people calling it as "reading the future"
- if it were easy to spot, why does the recursive analysis leave interpreting to the user? why it doesn't just say if bias exists and perhaps which indicators are at fault?
- one might  prefer instead to be 100% sure strategy results are accurate and has a strong workstation at hand
- it might be better to leave it to the users to decide whether they want to subject thieir workstation to the "burn" of a real backtest
- users could compare for same period the results between the classic backtest and this "live-mode backtest"
 
Hoping still you'd reconsider and allow this kind of backtest or at least provide some instructions on needed steps to setup it.
Thank you!

**Comment by xmatthias** [comment]
> recursive analysis is prone to interpretation

recursie analysis helps you determine the best startup candles - which is one gotcha (hence i mentioned it above).
it's not really helping with lookahead bias.

> one might prefer instead to be 100% sure strategy results are accurate and has a strong workstation at hand

you don't. "strong workstation" usually assumes it's got a lot of cores - though python is in reality single-threaded unless you use processes (hyperopt) - which would also apply to backtesting (including this mode). You can't have 1 core "that strong" - it's a false believe of "strong workstation" :laughing: 

---


it's yet another "mode" to support - which quite honestly - we currently lack the bandwith.
it's not just the code to maintain - but more severely, the support, explanation (why is it so slow?) - which i really don't see as reasonable or making sense.


If you look deep enough - i shared a decorator for such a mode some time ago (which you can apply to your strategy - so it becomes slow automatically) 
~I'm too lazy to search for it now - but it's in some issue.~ here: https://github.com/freqtrade/freqtrade/issues/6586#issuecomment-1077933526

you'll find it to be very slow - so have fun waiting.

**Comment by uplight-dev** [comment]
ok, I see your point. Thank you for being upfront and exposing your view on it honestly.

I'll try the decorator, it certainly look interesting. 
Still, it feels this might be a half-baked solution, since it requires to move all code into populate_indicators. I'd prefer to feed the data as if it was in live-mode. 

Would making a mock API for binance work better?
Or is there no way to actually call the heartbeat myself in an iterative manner and exposing the candles one-by-one to the engine?
In any case, you know better the internals of the framework. So I can only assume anything else than decorator is actually the case for which you don't have bandwidth to do.

And now I'm thinking how is it possible to have lookahead analysis detect 0 indicators as biased for the strategy I tested? Since you say recursive analysis is not related to the bias, I guess this result should indicate a clean strategy, right?
It had 0% losses on all backtests done and only profitable trades - around 60-100% profit, no matter the year/period. And this should be impossible to achieve in live-trading if I'm not mistaken?
I'm still really puzzled on it.

So again thank you, it's great to have your insight on it.

**Comment by xmatthias** [comment]
> Would making a mock API for binance work better?

that'd be a "full" forward-testing framework - which you can't get the data for unless you collect it in real time (orderbook data has no historic endpoints on any of the exchanges i've looked at so far).


---

Well backtesting is a pre-determined, stable environment - which (has to) take certain [assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) - which you can game pretty easily to get "great" results - which actually wouldn't be that.

common problems are either a very tight trailing stoploss (it'll start trailing and trigger on the same candle, simulating an exit at "high-trailing value" - which is possible - but assumes price goes from open straight to high without ANY wick) - or pricing problems (your backtest works with 0.1% profits - which slippage / order filling dynamics can eat away pretty quickly).

"most" problems (aside from slippage) can be identified by usign [`--timeframe-detail`](https://www.freqtrade.io/en/stable/backtesting/#improved-backtest-accuracy) - which will give you a better picture of what happens within a candle.

**Comment by froggleston** [comment]
Supplying candles "one by one" is limited by the data resolution provided by the exchange. In this case, usually 1m candles is the best resolution you can get. As backtesting already gives you 1m timeframe-detail as an option, as xmatthias has said, pretending that you can see all movement intracandle at a better resolution than 1m is misguided. You won't see any benefit over that because the underlying data is the same resolution either way.
