### ISSUE TITLE
Epoch time only on order_date column

### ISSUE THREAD

**Issue by Jorman** [freqtrade/freqtrade#10316]
## Describe your environment

  * Operating system: Debian Sandworm
  * Python Version: Python 3.12.3 (`python -V`)
  * CCXT version: ccxt==4.3.35 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

*Hi, I have a little problem with the order date creation, I just discovered that from 06/11/2024 all the trades have Epoch data.
Ok I just played a little with the database, I switched from one coin to another, so I edited the database, but I only touch the pairs, I don't even touch the dates. Honestly I don't remember when I did this switch and I don't think this can make this problem, but I'm not the person that can say that!
*
![image (1)](https://github.com/freqtrade/freqtrade/assets/5203988/713fabad-ec45-4889-a61f-8a9ac613a97b)
![image](https://github.com/freqtrade/freqtrade/assets/5203988/c80a26f5-03cd-4ce3-8eb9-b28ec1696e13)

### Steps to reproduce:

when the bot open or close one order or when I manually force entry or exit...
  
### Observed Results:

Wrong data/time in records, even in database

### Relevant code exceptions or logs

no strange message on the log

I stopped and edited again the database, I modified all the wrong order_date with the order_filled_date, and I lowered it by 1 sec, then I started the bot again, and I increased one position, but not working
![image (2)](https://github.com/freqtrade/freqtrade/assets/5203988/f50255cf-658e-42ed-a847-bef7a74a93a9)

Any idea?

**Comment by stash86** [comment]
Pro tips: never mess with the database. We never encourage user to change the database manually.

Honestly, not sure if we can help you. It's not a normal FT bot issue. It happened because you were messing with the database.

If I can give suggestion of a fix, sold all open trades, delete the broken database, and start fresh

**Comment by Jorman** [comment]
Yep, I know and agree, I only try to understand what is happening.
I already modified the database in the past, same way, but never some kind of issue.
I check the database and is not corrupted, I'm looking at every data inside the database, but I can't see anything wrong, apparently!
Do you think or have any extra tips to try to understand or fix the situation, now I can't close all trades, maybe in the future, but I can try to make some test on it.

**Comment by xmatthias** [comment]
Best bet - revert to the backup you made before the manual messing (you did make a backup, didn't you?).

It's not "epoch time" - times like this is what happens if the epoch precision is off - which i assume "might" happen if you're using some odd tool to edit the database which is ignoring the actual precision and save it with that.
Essentially, you can probably take the date you have now - convert it to epoch, multiply it by a few million to make it "ms" precision again - and get the "correct" date back.

https://www.epochconverter.com/ can be of great help for this.

you'll however struggle to do this automatically i'd think - as most (decent) database tools will know it's type is date.

**Comment by Jorman** [comment]
Yep, I've the backup, like always, but many trades happened meanwhile, I don't want to make a bigger mess if I recover the "old" database.
Normally I use https://sqlitebrowser.org/ when I've to edit the sql, I just check, and I've the latest version 3.12.2, if we don't consider the rc1.
I think your guess can be good, I also noticed a progressive increment on "epoch time"
Is too bad sqlitebrower as tool? I always use it, even when I've to modify some database for other programs and never had this problem, if I remember corretcly I don't even touched any data and time, but maybe during the save the program made some conversion on cell format?

Any good tools to use instead?
Thanks for the link, usefull.

**Comment by xmatthias** [comment]
While i'm using sqlitebrowser myself - i'm not really editing my databases much - but i've never really experienced something similar - which doesn't mean that newer / older / other versions might have this problem - maybe even in specific circumstances.

i'll also not be giving tool recommendations in this regards aside from "don't manually edit your database".

Whatever you've been trying to accomplish - if editing the database is the way to accomplish this, it's neither supported nor recommended - and **clearly** at your own risk.

i don't really see why you'd "switch from one coin to another". If one coin got delisted (the only reason i can think of doing this), it's a 100% loss anyway - why modify the database? you'll only be fooling yourself that you didn't loose it all - while in reality, you did as your strategy got hold (and held on to?) a failing coin.

**Comment by Jorman** [comment]
The question about the tool is a general question, you put the doubt in my mind that my program was not "eligible" and so I became alarmed. Obviously database modification, any database, is discouraged for the end user, in fact I am not saying it is a bug or anything like that, I would just like to understand if and how to "fix" this database, I think the problem is precisely in the table, I see no other explanation.
To an untrained eye like mine though, the table looks identical to that of a "healthy" database

Yes the reason for the change was a coin that was going to be removed from the exchange, actually I didn't lose the whole bet but that depends on the strategy itself, I am therefore slowly recovering the situation, but that is not the topic of this post.

The strange thing I don't understand, is why it only does it on order_date, as said I am not an expert in SQL, that's why I only use programs and don't run queries, but if I had made a mistake or something, I would have compromised the other fields that use a date as well, so why only order_date and not the other fields as well?
Could a hypothetical database compaction have created this damage?

**Comment by froggleston** [comment]
SQLite browser is completely able and recommended to edit databases. The issue is that you're editing a database that contains information about data happening *in another system*.

So, you haven't "made a mistake" with the way you're editing the database. You've made a mistake editing a database that *shouldn't be modified* to try and avoid the situation you've found yourself in, i.e. the strategy grasping on to a losing/delisted coin and trying to "fix" the situation by faking the data underneath. The strategy you're choosing to use is at fault, not freqtrade, sqlite, or sqlite browser.

`Ok I just played a little with the database, I switched from one coin to another` this is fundamentally wrong, utterly unsupported, and whoever suggested to edit the database to try and fix poor trades is the real problem.

**Comment by Jorman** [comment]
Ok, this is not a post to encourage manual editing of the database and I would also like to make it clear that I am not blaming anyone, not freqtrade or any other people, I did the editing myself, so the fault is mine, honestly this is not the first time I have edited the database, but it is the first time I am getting this error.
I am aware that it is not a freqtrade problem, but what better place to understand why this is happening?
I could have omitted the whole story and maybe now you would be here trying to understand why such a thing happened, however, I preferred honesty, hoping for advice on how to find and correct the problem, because you never stop learning. Instead, I find myself with only words of admonition, okay I think a reprimand is normal, one though. I hypothesize that as programmers you have made mistakes too, and the next step was always to find a solution/fix

I think I understand the admonition, I would like, if possible, also a sharing of experiences, to understand what is not working in the database, an explanation, which in part seems logical to me has been given, but it does not explain the behavior only on one part of the table.

If you have other constructive ideas on how to identify the error, welcome, I am willing to test, one more one less makes no difference at this point.

**Comment by stash86** [comment]
Last response before I'm locking this issue.

We have no interest in debugging this issue, because this isn't caused by freqtrade bot.

You are free to do whatever you want with the bot, but we won't help you with issues that isn't caused by the bot/code itself

**Comment by xmatthias** [comment]
> If you have other constructive ideas on how to identify the error, welcome, I am willing to test, one more one less makes no difference at this point.

The error -> the user doing the edits (don't blame the tool (sqlitebrowser, or any other, really) - with 99.9% certainty, it's the user that modified the fields - most likely accidentally. If that were not the case - it's an issue to raise with the tool - but you'll need proof of it malfunctioning, which i doubt there is)
The fix: either restore from backup, or fix the values manually.

I'm also in on the locking - but not because of the topic per se (which is a discussion probably better suited in other channels than github issues) - but because this diverted into "let's blame the strategy".
