### ISSUE TITLE
store persistent values in strategy outside of trades

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10346]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

In a strategy, I'd like to store a custom value in freqtrade that should be database persisted.
Having a Trade this is possible via set_custom_data(...). However, outside of a trade, how can I do it?

I've been trying to use KeyValueStore and forcefully extend the KeyStoreKeys enum. But I keep getting _KeyValueStoreModel.session undefined when running in backtesting mode.

Are there any better alternatives? Or should I store these into a custom external database?

Thank you!

**Comment by stash86** [comment]
You can always store it in external file

**Comment by uplight-dev** [comment]
Yes, what I started doing, but felt best if FreqTrade would provide a way to use it's own DB.

**Comment by stash86** [comment]
If not the best if we allow users to store any random data into database. It's possible they somehow break the database, then the bot stop working. It's better to save it in separate file. You can do whatever you want, but the bot will still run even if your custom file got corrupted or anything else

**Comment by xmatthias** [comment]
KeyValue Store is not meant to be used by the strategy - but for freqtrade internals (otherwise it would be mentioned in the documentation how to use it).
While you can do everything in python / freqtrade - i'd strongly advise against this - as we cannot and will not make sure that your modifications are not breaking in case of updates from our side.
Should that be the case, please don't expect us to help you sort out the mess you made.

---

Backtesting doesn't initialize database access (database access is automatically slow, so not suited for backtesting). 

As freqtrade is not using keyValue store - there's no compatibility layer to prevent database accesses - as it would be pointless effort at this point.

---

Independent of the approach - you'll probably want to exactly not store data during backtesting. It's pretty easy to have lookahead bias through that (one run saves "BTC price 2024" - the other reads it while the backtesting logic is still in 2023).
While this sounds like a simple example - you'll need to put a ton of thought into how to do this without risking lookahead bias - so most likely the best approach will be to not store during backetsting.

---

As mentioned above however - nothing prevents you from using your own file for this (in any format you think suits your data best).
Depending on the type of data, you'll always be restricted by a database (must be serializable, can't be too big, can cause performance issues if the database file grows large due to it, ...).
