### ISSUE TITLE
Add a plot-dataframe Command Line Option to Rename Plot File

### ISSUE THREAD

**Issue by cookster9** [freqtrade/freqtrade#10341]
## Describe your environment
(if applicable)

  * Operating system: Mac
  * Python Version: Python 3.11.8 (`python -V`)
  * CCXT version: ccxt==4.2.82 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I don't see a way to rename the plot html file that is generated by freqtrade plot-dataframe. I'd like something similar to the export-filename argument in "freqtrade backtesting" so that I can programmatically retrieve plot files after generating them.

The export-filename argument is reused when plotting as a way to retrieve a backtest result when plotting. So there needs to be a new argument. 

More likely than "renaming", it would probably make sense add a prefix or something to the filename since it generates a plot for each pair.

I vote adding a --prefix argument to freqtrade plot-dataframe.

I was messing around with it, and it would require changes in:
arguments.py, configuration.py, cli_options.py, plotting.py

Maybe other files if other behavior depends on the generated file name for some reason

**Comment by xmatthias** [comment]
the 2 plot commands (`plot-dataframe`, `plot-profit`) should be considered deprecated - and are in maintenance mode.
This is mostly for the performance problems even medium sized plots can cause - but also because the way it feels from a user perspective (store a file, open in browser) is rather clumsy and non-interactive (there's no way to add an indicator later...).

While there's currently no plans to remove these commands in the near future - there will also be no new features added, and we won't spend time on them beyond keeping them functioning roughly the same as they are (they'll be removed should there be major updates required to them).

Instead, please use [frequi](https://www.freqtrade.io/en/stable/freq-ui/) for plotting needs.

**Comment by cookster9** [comment]
cool thanks - didn't know about [freqtrade webserver](https://www.freqtrade.io/en/stable/utils/#webserver-mode)
