### ISSUE TITLE
Lookahead analysis get_open_trades misjudgment

### ISSUE THREAD

**Issue by Saber2pr** [freqtrade/freqtrade#10380]
## Describe your environment

  * Operating system: mac
  * Python Version: 3.12.3 (`python -V`)
  * CCXT version: 4.3.35 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I added the following code to my strategy code, and the analysis showed that there was a look-ahead bias. When the code was removed, the analysis result showed that there was no look-ahead bias. However, I do not think that this code can cause look-ahead bias. Its role is only to prevent all slots from being used in a single direction. Could help me analyze the reason?

The code:

```py
# ...
          dataframe.loc[cond_long, 'enter_long'] = 1
          dataframe.loc[cond_long, 'enter_tag'] = 'long'
          dataframe.loc[cond_short, 'enter_short'] = 1
          dataframe.loc[cond_short, 'enter_tag'] = 'short'

    def confirm_trade_entry(
        self,
        pair: str,
        order_type: str,
        amount: float,
        rate: float,
        time_in_force: str,
        current_time: datetime,
        entry_tag: Optional[str],
        side: str,
        **kwargs
    ) -> bool:
        open_trades = Trade.get_open_trades()

        num_shorts, num_longs = 0, 0
        for trade in open_trades:
            if "short" in trade.enter_tag:
                num_shorts += 1
            elif "long" in trade.enter_tag:
                num_longs += 1

        if side == "long" and num_longs >= 5:
            return False

        if side == "short" and num_shorts >= 5:
            return False

        return True
```

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by froggleston** [comment]
What was the output of the lookahead-analysis command? And we'd likely need to see more code.

**Comment by xmatthias** [comment]
The code itself will not cause lookahead bias - however, it can "delay" entries - causing the test-period to change (so instead of testing 1 week - you'll be testing 2 months - as there's far fewer entries).

With that, it can encounter more (or rather, different) scenarios - which might not even occur in the "shorter" timeperiod.

You should play with the parameters a bit (more specifically, with `--targeted-trade-amount` and `--minimum-trade-amount`) -  which can help you get more details.

---

As we've had no further feedback on the questions we've asked, i'm going to close this for now.

Feel free to comment below so we can reopen this issue if you're still encountering problems - and are willing to share more code and the output of the commands for your runs.
