### ISSUE TITLE
Support startup_candle_count beyond Exchange limit (Kraken) for backtesting / hyperopt

### ISSUE THREAD

**Issue by grainz** [freqtrade/freqtrade#10407]
## Describe your environment
(if applicable)

  * Operating system: Debian 12
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.3.54
  * Freqtrade Version: freqtrade 2024.7-dev-7a67771e4

## Describe the enhancement

Can we get an option to ignore the Exchange candle limit such as Kraken's 720 during Backtesting / Hyperopt?

```
2024-07-07 11:35:45,211 - freqtrade - ERROR - Configuration error: This strategy requires 800 candles to start, which is more than the amount of candles Kraken provides for 15m.
```

**Comment by stash86** [comment]
What's the point in ignoring such limit if you are still limited by it on dry/live run? Don't you want your backtest process to get as close as possible to dry/live? Or do I miss anything here?

**Comment by grainz** [comment]
> What's the point in ignoring such limit if you are still limited by it on dry/live run? Don't you want your backtest process to get as close as possible to dry/live? Or do I miss anything here?

I run a strategy / TA outside of FT live and send API calls to FT to enter trades. From there, I use FT to monitor the entry for profit / stoploss. This doesn't require 720 candles.

**Comment by stash86** [comment]
Well, there are a lot of other softwares to run backtest, if that's what you need. Maybe they have no such restriction.

We won't add a feature to cater for such special usecase that can be misleading to most of the general users.

**Comment by grainz** [comment]
I happen to think FT's BT/HO utilities are amazing and extremely useful. One of the best. It's just silly that an artificial limitation gets in the way of being able to utilize it completely. If the docs go out of the way to explain the limitation and there are additional tools to import trade data from Kraken's own CSV archive, I don't think there would be anything misleading. Especially if the default is to keep the candle check on.

**Comment by stash86** [comment]
There's nothing stopping you from forking FT and remove the limitation on your fork repo. As said above, we won't do this on the main repo.

**Comment by xmatthias** [comment]
>  It's just silly that an artificial limitation gets in the way of being able to utilize it completely. 

It'd be even sillier to allow users to backtest a situation they can't get to in live due to limitations with the exchange api.


---

As mentioned above - there's really no point in allowing users to backtest with a condition that they can't reach in live.

Just imagine this scenario: a user find a great strategy with 1500 candles making them rich on kraken.
They try to put it live, only to find out that they have no way of using it, as the exchange is only providing 720 candles to them.

Sure, it would be mentioned in the docs that this is something the user needs to pay attention to ...  - but be honest, did **you** read the **full docs** (from top to bottom) so you'd be aware of this oddity (you can backtest it - but live will screw you and not allow this) before increasing startup_candle_count to 1500 - which only applies to kraken and a few other exchanges you probably never heared off?

Everyone being in this case would feel utterly disappointed and would feel screwed by the tool - which showed great profits - telling you "yeah, but the exchange limits you in this - sorry, can't get rich in reality".

From experience i can say - almost nobody even looks at the documentation in case of problems or questions.

A better approach (that would serve everyone) would be to bug kraken support to add historic endpoints - though from experience i can tell you - they simply don't care - which had me move to an exchange with improved user focus.

---

That said - it can probably even be disabled via parameters (`exchange._ft_has_params` - setting `ohlcv_has_history` to true) - but i'd strongly advise against this - and changes via this must be considered not supported - and if you keep it when running live, it'll probably break and provide you with invalid history.
