### ISSUE TITLE
ImportError: cannot import name 'NAN' from 'numpy'

### ISSUE THREAD

**Issue by haxwell** [freqtrade/freqtrade#10401]
## Describe your environment

  * Operating system: Linux Mint
  * Python Version: 3.10.12
  * CCXT version: 4.3.56 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop branch, commit cd8bd
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

After forking the repository, then running `python -m freqtrade`, I get the error (top lines omitted)

  File "/home/jjames/src/freqtrade/freqtrade/freqtrade/rpc/__init__.py", line 1, in <module>
    from .rpc import RPC, RPCException, RPCHandler  # noqa: F401
  File "/home/jjames/src/freqtrade/freqtrade/freqtrade/rpc/rpc.py", line 14, in <module>
    from numpy import NAN, inf, int64, mean
ImportError: cannot import name 'NAN' from 'numpy' (/home/jjames/.local/lib/python3.10/site-packages/numpy/__init__.py)

### Steps to reproduce:

  1. Fork the freqtrade repo
  2. execute the command `python -m freqtrade`
  3. notice the error
  
### Observed Results:

  * What happened? I got the above error
  * What did you expect to happen? I expected freqtrade to run without error.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  File "/home/jjames/src/freqtrade/freqtrade/freqtrade/rpc/__init__.py", line 1, in <module>
    from .rpc import RPC, RPCException, RPCHandler  # noqa: F401
  File "/home/jjames/src/freqtrade/freqtrade/freqtrade/rpc/rpc.py", line 14, in <module>
    from numpy import NAN, inf, int64, mean
ImportError: cannot import name 'NAN' from 'numpy' (/home/jjames/.local/lib/python3.10/site-packages/numpy/__init__.py)

**Comment by xmatthias** [comment]
This sounds like you're having a wrong verison of numpy installed (most likely 2.0).

Also for direct clones - please follow the [installation guideline](https://www.freqtrade.io/en/latest/installation/) to have the proper dependencies installed.

With the version pinned by the repository (the only version we support) - importing `from numpy import NAN` works  perfectly fine.

Numpy 2.0 has not been tested, and is not supported to be used with freqtrade at this point.

We'll make the necessary adjustments as needed (i doubt this is the only one) before bumping that version - until then, please use the pinned versions of dependencies.
(as a side note: you'll run into further issues - as you can't install ta-lib with numpy 2.0 at the moment).

**Comment by KingMikeX** [comment]
### I have the same Issue with **Solution**

The problem is that Numpy changed _NaN_ to _**nan**_ in the new 2.0.0 version

I use for myself the pandas_ta Library, due to, that pandas_ta is using the TA-Lib Library as well. It may be a problem for
those user's which install all their packages from scratch.

The reason, why the problem does occur is the if you install **numpy** with "`_pip install numpy_`", pip installs the latest version, while the version in the library _pandas_ta_ for numpy is **_1.22.4_**  

### **How to fix the Error:**
( Remember, this was a quickfix for me. It's important to say that if the Library pandas_ta updates there version to be compatible to numpy 2.0. This won't work anymore and you should upgrade to the newest version. )

bash
```
pip uninstall numpy
pip install numpy==1.22.4
```

.. restart you project if you didn't already and you are good to go.

**OR**

You choose a deeper change in the base of pandas_ta.

Therefore you have to open die File "_/.local/lib/python3.10/site-packages/pandas_ta/momentum/squeeze_pro.py_"  in your user Directory

and change the line 2 from:

`from numpy import NaN as npNaN`

to 

`from numpy import nan as npNaN`

**Comment by xmatthias** [comment]
freqtrade has numpy <2.0 pinned at the moment - so i don't really see how this comment is relevant.

We're however looking to update to 2.0 in the near term - at which point we'll no longer support numpy 1.x versions (as some dependencies made a hard cut, and support either this, OR The other version).

**Comment by KingMikeX** [comment]
The reason is my last installation I did with pip of the panda_ts the is the mistake in the squeeze_pro.py of the momentum folder, that NaN was imported instead of nan. Therefor you would have two options. Fix it by hand or downgrade. While I fix it myself and use numpy 2.2

**Comment by xmatthias** [comment]
well i'm not ... sure how this relates to freqtrade.
Instead, you should submit a fix to pandas_ta - or ask **there** to fix it.
