### ISSUE TITLE
Install local freq UI build

### ISSUE THREAD

**Issue by haxwell** [freqtrade/freqtrade#10455]
## Describe your environment
(if applicable)

  * Operating system: Linux Mint
  * Python Version:  3.10.12 (`python -V`)
  * CCXT version:  4.3.54 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop branch (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I would like to be able to install a local build of freq-ui, as easily as I can install an officially released version. I would do this by passing a parameter to the `install_ui` command referring to a locally built zip file containing the output of the `dist` directory created after building the `freq-ui` with the `pnpm run build` command. The zip would be built with the command `cd dist && zip -r dist.zip .`.

**Comment by xmatthias** [comment]
I don't really see a reason for that if i'm honest (and all reasons i can think of are misguided by "i need to build it to test it").

if you're building it locally - that's usually because you're developing a new feature for it, where you'll also want to run the dev version - so changes for it are reflected immediately - which you can do with `pnpn run dev`.

If you "really" want it in the freqtrade directory - you can probably get the install directory through something like `pip show freqtrade` - and use that to copy the files to the correct location. 
I don't see this as something we'll be building in though.
