### ISSUE TITLE
Is Binance supported in "Credit Trading Mode" for Perpetual Futures ? The only way for EU users to use Perpetual Futures on Binance.

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#10503]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Is Binance supported in "Credit Trading Mode" for Perpetual Futures ? Since MICA regulation, the only way for EU users to use Perpetual Futures on Binance.
Asking because in documentation it's specified: "Cross margin mode (currently unavailable)".
Under "Credit Trading Mode" only "cross" margin mode is supported currently on Binance. "isolated" not available.
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
I don't see any mention that isolated isn't supported.
https://www.binance.com/en/support/faq/how-to-use-binance-futures-credits-trading-mode-0e857c392a2d47cebde0af762d9255ae

All it says is the default mode would be cross margin. You should be able to change it to isolated.
In theory, yes it should work. But whether it really works flawlessly or not, you have to run live with it and see yourself.

**Comment by dobremha** [comment]
> I don't see any mention that isolated isn't supported. https://www.binance.com/en/support/faq/how-to-use-binance-futures-credits-trading-mode-0e857c392a2d47cebde0af762d9255ae
> 
> All it says is the default mode would be cross margin. You should be able to change it to isolated.

I can't change it to isolated (see picture).

I will make a test with "margin_mode": "cross", but last time it didn't work.

![Screenshot_20240807_000227_Binance](https://github.com/user-attachments/assets/ddb51aa0-0b72-4100-a97e-7faa8e42e8e4)

**Comment by dobremha** [comment]
'2024-08-06 21:23:35,603 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.68
2024-08-06 21:23:35,603 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-08-06 21:23:35,613 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-08-06 21:23:35,623 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-08-06 21:23:38,432 - freqtrade - ERROR - Freqtrade does not support cross futures on Binance

**Comment by dobremha** [comment]
I try now with "margin_mode": "isolated" ....

'2024-08-06 21:25:44,522 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.68
2024-08-06 21:25:44,523 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-08-06 21:25:44,532 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-08-06 21:25:44,543 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-08-06 21:25:50,608 - freqtrade - ERROR - 
Multi-Asset Mode is not supported by freqtrade. Please change 'Asset Mode' on your binance futures account.

**Comment by dobremha** [comment]
![Screenshot_20240807_002827_Binance](https://github.com/user-attachments/assets/2b420742-0702-4d36-ae55-a1fa890ed78a)

Houston, we have a problem ...

**Comment by stash86** [comment]
A solution I can think of is you need to do a dirty hack.

Run FT on dry mode. On confirm_trade_entry and confirm_trade_exit functions, send API call to binance for order placements.

It's gonna be a little bit complicated, but is doable. The only issue is the entry and exit rates stored by the dry bot might be different than the actual rates if you are using market orders

**Comment by dobremha** [comment]
Thanks Stefano, I use limit orders. It's not complicated, I already use this trick, but on Bybit: a dry-run bot with an extreme bad strategy and results, and a live one that only takes entry and exit signal's (but in opposite direction) from the dry-run bot.
But on Bybit the live bot is running normally (until they will also stop it for EU users...).

This "Credit Trading Mode" shit on Binance has some advantages, one is that I can use BTC as underlaying asset for my credit points. And as BTC is rising in time, my "Credit Trading Mode" account will also rise in value only for holding BTC, not USDT/USDC. Even let's say my strategy don't run as expected and I get a -2% drawdown from my trades... if BTC go from 55k to 80k, I will still win.

Now ... how do I send API call's to Binance for order placements ?
Do you have an link to such an example ?

**Comment by xmatthias** [comment]
> Now ... how do I send API call's to Binance for order placements ?
Do you have an link to such an example ?

You can't - and we won't provide any examples for this (if these are provided here, i'll be deleting these) - as it's a hacky way we cannot and will not support.


If you're interested in this - feel free to put in the work to submit a proper pull request adding support for it.
We'll however neither provide guides, nor hints on how to accomplish this in any other way.

I won't be able to support in this too much - as my country doesn't get this trading mode - so i'm unable to update my account to this (or rather, one of the subaccounts).

Thanks for your understanding.

**Comment by dobremha** [comment]
Hi Matthias, I am willing to work on this task, do tests and what it takes to solve it. I will start to do some research on how to "submit a proper pull request" for it, because I am a beginner in github stuff.

**Comment by xmatthias** [comment]
That's the easy part ;) 
A guide for the github PR workflow can be found [here](https://guides.github.com/introduction/flow/).


essentially it's 
* you setup freqtrade for dev
* you create a feature branch
* you make changes necessary for things to work - once it works - you look at why so many tests broke 😆

**Comment by Su-Well** [comment]
I modified freqtrade to make it work for USDⓈ-M Futures, by a simple change that overrides the get_free (stake) check to use BNFCR instead of the stake currency based on the pair (usually USDT). It is a hack, since it is only correct insofar that 1 BNFCR = 1 USDT. It also requires that the binance futures account keeps its margin in the BNFCR "currency". Binance offers conversion between these at close to 1:1, but with maybe 0.01% difference sometimes.

My changes have been successful in both backtesting and live trading, although in a long position with 4 position adjustment, freqtrade says total profit was -30.746, while Binance says -29.13. Funding fee calculation works.

I don't have time for doing this properly, but since I essentially have a working setup, I wanted to share my changes in case it helps someone get started. **removed**

**Comment by xmatthias** [comment]
@Su-Well Please understand that I've hidden your comment to protect occasional readers from potentially non-working code (there's no better reason, sorry) and removed the link to not tempt inexperienced users to reproduce your modification.

The code is _clearly_ hacky, will break regular modes- and not something we'd approve (not in this way, anyway) - and won't be able to support (also because we don't have access to BNFCR at this moment due to location restrictions).

From your comment, i do understand that you'll not have time to support this either, which means it'll be outdated very soon - and users will be left in the dust (we'll clearly not support your fork).

While I'm happy to get _proper_ PR contributions (in case of BNFCR, tied to the condition to support it going forward), links to hacky, potentially non-working workarounds will not be allowed.

**Comment by yperfanov** [comment]
Hello @xmatthias 

Would you please try to summarize the steps for implementing binance pepr futures cross margin that would work for the european users? What part of the code should be changed and/or newly developed in order to support this feature?

**Comment by xmatthias** [comment]
@yperfanov best contact your EU Politician and convince them to have BNFCR allowed in all of europe, not excluding most bigger countries (it's not available in at least the following countries: germany, italy, netherlands, france, UK).
So it's not a "european" mode - it's "smaller european countries mode" - which is the fault of regulators, really.


Since i don't have access to this feature, i can't comment on the precise steps - as i am unable to perform such a trade manually and look at what exactly is involed.
If i'd have such steps, it'd be pretty easy to implement this - but figuring out these steps is essentially part of the task involved in this issue.

**Comment by xmatthias** [comment]
@yperfanov i've deleted your previous comment as i think it's something you'd rather not have in an issue publicly - though thanks for the offer 👍  (don't take this as censoring plz).

can you get in touch on discord?

**Comment by yperfanov** [comment]
Yes, I've just contacted you.

**Comment by dobremha** [comment]
Hi. I'm also in this thing. I trade actively on Binance in this environment and understand how it's working. Can support with tests or other needed INFO. Running FQ only with Docker (Linux).

and I desperately need this to work....

**Comment by dobremha** [comment]
GREAT ! Best best possible christmas/new year gift.
Already running live 2 bot's : BTC/USDT:USDT for longs and BTC/USDC:USDC for shorts.
And it's working fine.
With BTC, ETH, USDC as collateral for BNFCR.

**Comment by xmatthias** [comment]
the collateral used is actually mostly irrelevant - as binance converts it all to BNFCR anyway.

let me know if you're encountering issues related to this mode - in my testing, it seemed to work fine - but i obviously only did a few test trades - not running a full strategy over weeks.
