### ISSUE TITLE
Leverage example

### ISSUE THREAD

**Issue by kleanth11** [freqtrade/freqtrade#10539]
## Describe your environment

  * Operating system: ubuntu 22.04.4
  * Python Version: Python 3.10.12 (`python -V`)
  * CCXT version: cant seem to find this (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.7.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
So i was going through the callback section on freqtrade documentation and i saw that almost every other callback like boot_start() but the leverage() one does not have an example it only has this part :     
```
def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,
                 **kwargs) -> float:
        """
        Customize leverage for each new trade. This method is only called in futures mode.

        :param pair: Pair that's currently analyzed
        :param current_time: datetime object, containing the current datetime
        :param current_rate: Rate, calculated based on pricing settings in exit_pricing.
        :param proposed_leverage: A leverage proposed by the bot.
        :param max_leverage: Max leverage allowed on this pair
        :param entry_tag: Optional entry_tag (buy_tag) if provided with the buy signal.
        :param side: 'long' or 'short' - indicating the direction of the proposed trade
        :return: A leverage amount, which is between 1.0 and max_leverage.
        """
        return min(5.0, max_leverage)  
```
        so i did change only the leverage number but it does not work and i get Optional as non imported, is there any library i should add as well
        Thanks in advance

**Comment by froggleston** [comment]
You need to add `from typing import Optional` in your strategy imports.

**Comment by xmatthias** [comment]
Quite honestly - you should get some basic understanding of how python works - so such issues are obvious when seen - otherwise i think you'll struggle greatly with freqtrade strategies (not just because of imports - but because of the whole syntax per se).

Imports are a general thing usually - and samples in the documentation are almost always intended as demonstration - not fully runnable code.

The assumption for these is that imports are maintained by the user (importing Optional is something very generic in python) - the "class" reference in this particular example is just to show you where the method goes (from an indentation / layout perspective). This example will not run on it's own - as there's several mandatory methods which are missing - but it's the section to show "how to add leverage" - there's little point in having a 100 line sample for just this.
