### ISSUE TITLE
Freqtrade no longer working with Mexc due to recent API changes

### ISSUE THREAD

**Issue by rmtucker** [freqtrade/freqtrade#10558]
OS Ubuntu 22.04.4
CCXT 4.3.79
Freqtrade docker-2024.8-dev-4ca6e617

Freqtrade has not been working with Mexc for a number of days now due to changes to their API
[<https://mexcdevelop.github.io/apidocs/spot_v3_en/#change-log>](url)
The change on 16/08/2024 is what seems to have broken it.

**Comment by froggleston** [comment]
MEXC isn't a supported freqtrade exchange, and given the incredibly shady API access, it's unlikely to be officially supported.

**Comment by xmatthias** [comment]
Essentially - it's not a problem freqtrade will address - but which needs to be addressed in ccxt.

As it's not a supported exchange - we strongly suggest to use one of the supported exchanges instead.

Alternatively - please do the legwork yourself- which essentially means
* create a reproduction with ccxt code directly
* open an issue against ccxt
* (alternatively, create a Pull Request fixing the issue yourself in ccxt).

For supported exchanges - we're willing and able to take up these points with ccxt.
There's however a reason we have a limited number of supported exchanges - simply because we don't have the capacity to do this for a greater number of exchanges without sacrificing our ability to actually inovate.

Thanks for your understanding.

**Comment by kennylbj** [comment]
For those encountering this issue: just upgrade the ccxt to 4.3.85 or pull the develop branch if you are using docker.
