### ISSUE TITLE
Help Needed: Error When Testing Freqtrade Strategy in Dry Run Mode

### ISSUE THREAD

**Issue by mdelhaous** [freqtrade/freqtrade#10567]
Hello everyone,

I’m currently setting up a Freqtrade bot using the config_examples/config_kraken.example.json file from the official repository. I’m running the bot in dry run mode to test my strategy, but I keep encountering the following error:

`ImportError: Short strategies cannot run in spot markets. Please make sure that this is the correct strategy and that your trading mode configuration is correct. You can run this strategy in spot markets by setting `can_short=False` in your strategy. Please note that short signals will be ignored in that case.
`

**What I Need Help With:**

**Strategy Configuration:** What’s the correct way to configure my strategy for spot markets? Should I be disabling short signals entirely?
**Error Resolution:** How can I resolve this error and successfully run the strategy in dry run mode?
Any advice or pointers would be greatly appreciated!

Thank you!

**Comment by froggleston** [comment]
Yes, spot is long only. You can't use futures pairs, or futures configurations with spot markets. In the strategy you've set `can_short = True` and your trading mode is set to spot. These are not compatible, so do as the error suggests and set `can_short` to False, or remove it entirely from the strategy.

**Comment by mdelhaous** [comment]
@froggleston , thank you for your response! Unfortunately, I'm still encountering an issue. I'm using Freqtrade with Kraken and attempting to run the FreqaiExampleStrategy.py strategy. However, I'm getting the following error when executing the bot:

`freqtrade.exceptions.OperationalException: freqAI is not enabled. Please enable it in your config to use this strategy.
`

Just to clarify, I'm using the **config_kraken.example.json** configuration file and the **FreqaiExampleStrategy.py** strategy file from official repo.

**CMD: freqtrade trade --config config_kraken.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor**

Any further guidance would be greatly appreciated!

**Comment by stash86** [comment]
Read the docs on how to set freqai in the config, or look at the example config for freqai.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Well you can't use random strategies without understanding how they work and what other prerequisites are required.
The [documentation](https://www.freqtrade.io/en/stable/) will be your first step - and i'd recommend to read it from top to bottom at least once to get an overall understanding of the features freqtrade offers without having to ask and wait for answers every time.
it'll also help keep our limited time focused on improving things, instead of reading the documentation to people.

---

Now for your particular combination (kraken, freqAI) - It won't work due to technical limitations of the kraken API.
Kraken does not offer historic ohlcv data (it must be converted from trades data - where downloading is a very slow process). 
Exactly this data (in a timely manner) is however key for freqAI - so it's technically not possible to run a freqAI enabled strategy on kraken.

You're obviously free to open an issue with kraken support pressing them to provide an endpoint for more than 720 candles of historic data (which is effectively the only solution to get freqAI working against kraken) - me (and others) have done so in the past with no success - hence don't bet on it.

**Comment by mdelhaous** [comment]
@xmatthias Thanks for the clarification on Kraken and freqAI.

- I’ll review the documentation more thoroughly.
- Appreciate the heads-up on Kraken’s limitations with historic data.

**Do you have any suggestions for a strategy that works well? I’m testing several templates and would appreciate any recommendations.**

Best,

**Comment by xmatthias** [comment]
we don't recommend strategies. 

https://github.com/freqtrade/freqtrade-strategies/ contains some samples - but they should be seen as is - examples to get you started.
Experience or "trader fit" to individuals can best be found by backtesting. Maybe one of these does align with you - but most likely, it'll be a combination of several.

Freqtrade is however not (and doesn't aim to be) a "click, start and get rich" tool. 
Users are expected to put in the time and work to both understand how freqtrade works (reading the documentation) - as well as to invest the time to try and find a strategy that works for you (with your risk appetite, exchange, pairs, ...).

**Comment by mdelhaous** [comment]
Could you please specify which issue template you're referring to? The template helps us address issues more effectively. Without it, we may need to close issues as duplicates.

Thanks for your understanding.

@xmatthias

**Comment by xmatthias** [comment]
@mdelhaous the template you get when you open a new issue - the one you've so far always deleted as part of opening a new issue and replaced with your own  content.

**Comment by mdelhaous** [comment]
I didn't pay attention, sorry.
