### ISSUE TITLE
FreqAI execution logic + methods explanatios

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#10568]
* Operating system: ubuntu 22
  * Python Version: 3.10
  * CCXT version: 4.3.65
  * Freqtrade Version: stable
  
Hello!

I am using FreqAI, it is amazing, thanks for the product!

What I would like to ask - Is the main logic of FreqAI. I think I understand some points, but it is better to ask and have feedback if I am wrong somewhere.

So:
1. _feature_engineering_expand_all_ and _feature_engineering_expand_basic_ - difference is not pretty clear for me, I appreciate If you can give a simple example where methods difference can be helpful. ( I know about config and periods). Does FreqAI computs all _feature_engineering_expand_all_  before _feature_engineering_expand_basic_ or it calls _feature_engineering_expand_all_ and _feature_engineering_expand_basic_ , lets say, as "duet" than goes to the next core_pair/tf?

2. What is the way to get informative tf/pair to use as the data column to compute new feature based on it? This is the continue of previous question. If I need BTC/USDT 15m tf to compute the feature for */USDT 1m tf, and BTC/USDT 15m is in config as core, how to get this feature to comput another?

3. There is no possibility to plot features (is there?). But at the same moment in hybrid populate_indicators can be plotted? The same as possibility to use @informative_pair? I've not tried, but if fetures are isolated from df used for populate_indicators(IF!!!) - it is not a problem to make copy of features df and pass where it is needed (with cutting data by the timerange) to use for plotting.

I believe some questions may seem not pretty smart, but if you(me at the moment) missing a part of puzzle - it is not seems so stupid=).

Thanks for any help.

**Comment by robcaulk** [comment]
Hello,

1. I don't remember the order, except that feature_engineering_standard is last (as described to you in the doc). If you'd like to find exact ordering of events, the code is open-source, so you can go have a look at the for loop. Just ctrl-f `feature_engineering_expand_all` in the code base. Or type `feature_engineering_expand_all` into the github search bar of the freqtrade repo.

Regarding "what is the difference" I can't write it any clearer than I wrote in the doc:

https://www.freqtrade.io/en/stable/freqai-feature-engineering/#defining-the-features

Please ask your question relative to what is shown at the top of that page - otherwise we've entered a circular holding pattern.


3. Do whatever you want with earlier engineered features in `feature_engineering_standard`. See comment above.

4. Use `%%` for features you want returned back to your strategy, which includes the ability to plot them.

Cheers,

Rob

**Comment by xmatthias** [comment]
well the sequence will be `feature_engineering_expand_all` `feature_engineering_expand_basic`, then `feature_engineering_standard`.

Not sure the actual sequence is important though - it's how they work - which is explained pretty well in the above linked docs. if you carefully read that until the very end - you'll notice this:

> In total, the number of features the user of the presented example strategy has created is: length of `include_timeframes` * `no. features in feature_engineering_expand_*()` * `length of include_corr_pairlist` * `no. include_shifted_candles` * `length of indicator_periods_candles` .

The docstring of each of the methods (also in that documentation part) also contains more details with "what" each feature will be multiplied with.
