### ISSUE TITLE
Inconsistent signal generation during backtesting 

### ISSUE THREAD

**Issue by xenon1001** [freqtrade/freqtrade#10571]
## Describe your environment

Operating system: ubuntu 24
Python Version: 3.10
CCXT version: 4.3.70
Freqtrade Version: 2024.7
  
## Your question

I have a question that I'm uncertain about whether it’s a bug or not. I'm developing a pair trading strategy using Freqtrade. The strategy functions as expected with real-time data, but I'm facing issues during backtesting and hyperopt. Specifically, when I backtest each symbol individually, everything works correctly, and the signals generated are accurate. However, when I run a backtest with both symbols together, the signals become inaccurate. Upon reviewing the backtest JSON files, I noticed that while one symbol's signals are correct, the other symbol's signals are not. In a pair trading strategy, if the first symbol generates a long signal, the second symbol should generate a short signal, but this isn’t happening when both symbols are tested together, regardless of whether I configure it via the config file or use the -p command. The same issue occurs with hyperopt. When tested separately, the signals are generated as expected. Could this be a bug, and do you have any advice on how to resolve it?

**Comment by stash86** [comment]
SOL only
```
┏━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃          Pair ┃ Trades ┃ Avg Profit % ┃ Tot Profit USDT ┃ Tot Profit % ┃ Avg Duration ┃  Win  Draw  Loss  Win% ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ SOL/USDT:USDT │     11 │         0.95 │           4.065 │         2.03 │      0:14:00 │   11     0     0   100 │
│         TOTAL │     11 │         0.95 │           4.065 │         2.03 │      0:14:00 │   11     0     0   100 │
└───────────────┴────────┴──────────────┴─────────────────┴──────────────┴──────────────┴────────────────────────┘
```

XRP only
```
┏━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃          Pair ┃ Trades ┃ Avg Profit % ┃ Tot Profit USDT ┃ Tot Profit % ┃ Avg Duration ┃  Win  Draw  Loss  Win% ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ XRP/USDT:USDT │     10 │         0.74 │           3.354 │         1.68 │      2:48:00 │    9     0     1  90.0 │
│         TOTAL │     10 │         0.74 │           3.354 │         1.68 │      2:48:00 │    9     0     1  90.0 │
└───────────────┴────────┴──────────────┴─────────────────┴──────────────┴──────────────┴────────────────────────┘
```

Both backtested at the same time
```
┏━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃          Pair ┃ Trades ┃ Avg Profit % ┃ Tot Profit USDT ┃ Tot Profit % ┃ Avg Duration ┃  Win  Draw  Loss  Win% ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ SOL/USDT:USDT │     11 │         0.95 │           4.065 │         2.03 │      0:14:00 │   11     0     0   100 │
│ XRP/USDT:USDT │     10 │         0.74 │           3.354 │         1.68 │      2:48:00 │    9     0     1  90.0 │
│         TOTAL │     21 │         0.85 │           7.419 │         3.71 │      1:27:00 │   20     0     1  95.2 │
└───────────────┴────────┴──────────────┴─────────────────┴──────────────┴──────────────┴────────────────────────┘
```

All three tests shows same exact result. So unless you can provide us with a strategy and config that we can use to reproduce your issue, I will say the issue is on your side, whatever it is

**Comment by xenon1001** [comment]
@stash86 No problem! I'd be happy to share the strategy with you. I'll clean up the code a bit, and then I'll send it over for you to check.

**Comment by xenon1001** [comment]
@stash86 [Pairtrading.zip](https://github.com/user-attachments/files/16738511/Pairtrading.zip)
To ensure the strategy works properly, add a .json file named Target_pairs_1.json in the strategy directory with the following content example: {
  "Target_pairs": ["BTC/USDT:USDT", "ETH/USDT:USDT"]
}

**Comment by xenon1001** [comment]
@stash86 I reviewed the code several times and identified that the issue likely stems from defining the function statically. Refactoring it to an instance method seems to have resolved the problem. The remaining errors might be due to how a symbol loss affects the trade entry amounts in single-symbol versus pair trading. While I'm not entirely certain this is the root cause, it's my best guess.

**Comment by stash86** [comment]
Just checked your file, and indeed the issue is you are defining different inf pairs. My advice to just set them both as informative pairs, so for example if you are trading BTC and ETH, just set them both as informative. Then in populate_indicators, you can call specific column name based of current processed pair. So if the bot is processing BTC, they should call "ETH_close", and vice versa

**Comment by xenon1001** [comment]
@stash86 Thanks! After refactoring the method, most of the problems have been resolved. I appreciate your advice and will implement it. Thanks again for your time.

**Comment by xmatthias** [comment]
not entirely sure what method you're refering to - as the only static method in the file above is `plot_config` - which is not relevant for backtesting.

---

the use of `self.current_pair` is for sure problematic / wrong - as we don't guarantee (or aim to guarantee) execution sequence of the populate_* methods to be identical between dry and backtesting.

you're only setting `self.current_pair` once - in `populate_indicators` - in `populate_entry_trend` and `populate_exit_trend` - you don't set it - hence the pair last analyzed will be set.
This will probably work for dry-run - but must fail in backtesting whenever more than one pair is used.

If you carefully look at the [backtesting/hyperopt execution logic](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic) (compare it with the dry-logic above this link)

![image](https://github.com/user-attachments/assets/0f9b9d55-b773-41e9-ace7-60de30c43eb9)

These methods are not called "per pair" - so freqtrade will first do a `populate_indicators()` call for every pair - and **then** run the same for all pairs on `populate_*_trend()`.
As such - setting the pair to the strategy instance (`self.current_pair = metadata['pair']`) is wrong.

Instead, you should use `metadata['pair']` whenever provided (and not rely on the pairs otherwise) - or `pair` or `trade.pair` in callbacks if needed.
