### ISSUE TITLE
Stop-loss for big trade that's value is over the volume of a single candle

### ISSUE THREAD

**Issue by marc-pawlos** [freqtrade/freqtrade#10591]
## Describe your environment

  * Operating system: UBUNTU 22.04
  * Python Version: Python 3.10.13
  * CCXT version: ccxt==4.3.68
  * Freqtrade Version: freqtrade 2024.7

  
## Your question
Hello,
This is my first post (question), and I would like to thank you for the development of this software!
I have a question regarding backtesting, and I have reviewed the information available at:

https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting

However, I have the following question:
I am using Freqtrade for backtesting on 15-minute candles. I need to understand the behavior of the stop-loss.

Specifically, what happens if the stop-loss is triggered, but the value of my pair in the portfolio is greater than the volume of the candle?

For example, let's say I have a pair in my portfolio worth 1M USDT, and the historical 15m candle has a volume of 10,000 USDT.

What happen in that scenario, during back-testing:

- Does it sell the 1M trade within this candle?
- Does it do nothing?
- Does it sell 1M over the next consecutive 15-minute candles, ensuring that in each candle, it does not sell more than the historical volume of that candle?

**Comment by stash86** [comment]
Backtest don't take volume into consideration when it's entering and exiting any trades. So you can put unrealistic stake amount, and it will considered it was fully filled. So it's recommended to use "sane" number for the stake amount

**Comment by xmatthias** [comment]
I'd say the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting)  outline this quite nicely: 

> All orders are filled at the requested price (no slippage) as long as the price is within the candle's high/low range

---

At any rate - validating volume during backtesting doesn't make sense if you think about it carefully.
While technically, filling an order could be postponed based on candle volume - it'd not emulate actual behavior - as the actual orderbook state would not be known - and the impact of your order wouldn't, either (that's something dry-run can't simulate, either).

ust because volume in a candle is low doesn't mean there were not 10M on both bid and ask spots - just they never moved one pip.
So having your order added to the other side of the orderbook might've very well filled your order (even though candle volume was 10k - and your position was 1M - you could've been the catalyst for a 10M candle) - but since you were not there at the time - nobody knows.
Also, the pure presence of an 1M order in the orderbook on a small market will make price move.

**Comment by marc-pawlos** [comment]
Many thanks for your responses !!!  :-)
