### ISSUE TITLE
WebSockets for binance

### ISSUE THREAD

**Issue by GabrielBertoli** [freqtrade/freqtrade#10596]
## Describe your environment

Operating system: mac os
Python Version: Python 3.11.9
CCXT version: ccxt==4.3.21
Freqtrade Version: freqtrade 2024.4
  
## Your question

Hello, Is there a proven and validated method for using WebSockets with Freqtrade when trading on Binance?

**Comment by xmatthias** [comment]
Freqtrade is using websockets for selected exchanges (including binance) since [2024.7](https://github.com/freqtrade/freqtrade/releases/tag/2024.7).

It's currently only being used for ohlcv data - however that's usually the most traffic-prone data.
There's currently no active plans to extend this to more data - but it's not excluded that we'll be adding more data-types in the future.

**Comment by GabrielBertoli** [comment]
Thank you for your prompt response. This is already great news!

I read in the update that ccxt.pro uses WebSockets to get up-to-date OHLCV data, which is currently available for Binance Spot and Bybit. Could you please clarify if there's anything specific I need to do in my Freqtrade setup to benefit from this feature?

Additionally, I understand that WebSockets support does not currently extend to order book data. Are there any plans to implement this in the future? If not, would it be possible to write custom code to enable order book data retrieval via WebSockets for Freqtrade?

Thank you for your assistance!

**Comment by xmatthias** [comment]
> Additionally, I understand that WebSockets support does not currently extend to order book data. Are there any plans to implement this in the future? If not, would it be possible to write custom code to enable order book data retrieval via WebSockets for Freqtrade?

not in the near term. 
While it's something I've investigated in the past and have a rough prototype (non-public, and currently no intend to share this)- the data amount accumulating through this (also because ccxt doesn't allow unsubscribing from a websocket) doesn't make this feasible - and will clog your line as soon as you've got a few open trades.

you're obviously free to write whatever code you'd like - but we'll not be supporting you in this.

**Comment by GabrielBertoli** [comment]
that is very clear for Order book

Now, Is there anything specific I need to do to enable WebSockets once we have the new 2024.7 version of Freqtrade, or is it already configured to work out-of-the-box?

**Comment by xmatthias** [comment]
Websockets are enabled out of the box for supported exchanges / configuration.

there's a [documentation page](https://www.freqtrade.io/en/stable/configuration/#consuming-exchange-websockets) explaining how to eventually disable it.
Freqtrade will automatically fall back to rest calls if the websocket connection fails or doesn't deliver data (it's stuck and about to fail).
