### ISSUE TITLE
Add BitMart Futures Market

### ISSUE THREAD

**Issue by Jasper7619** [freqtrade/freqtrade#10593]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*
Currently only BitMart spot trading is available, but BitMart also provide futures trading

**Comment by xmatthias** [comment]
That's correct - bitmart is only supported for spot markets at this point.

Unfortunately, it's a time-consuming process (some more, some less) - at any rate a lot more complex than getting spot markets running.

A quick look at the ccxt side also reveals that bitmart is missing key methods (fetchFundingRateHistory, fetching mark candles).
It's most likely not ccxt's fault, either - as according to the API docs - this data doesn't seem available.

https://github.com/ccxt/ccxt/blob/8d6bff547e0d33e79317e4d71b8dbf73f1079858/ts/src/bitmart.ts#L69

Both informations are needed for proper functioning of futures in dry run (so it's also interesting to users - as they can simulate if their strategy actually works) - as it's required by the calculations (again, according to the docs).

While it's possible to fetch the **current** funding rate - that's not sufficient for backtesting / dry-runs - and we've seen that adoption of exchanges with missing data is almost zero - as it makes all simulations pointless - and our time spend on testing an exchange wasted, too.

Without this, it won't make sense to implement an exchange.

I'm however happy to look at this if i've missed something, and this information is available - just not yet implemented in ccxt (which would be your next stop) - obviously - that assuems that it's available through the API - otherwise it'd be pointless to ask ccxt to implement anything :laughing:
