### ISSUE TITLE
Strategy backtesting with good Condition, but no Trades in Dry Mode

### ISSUE THREAD

**Issue by danxathome** [freqtrade/freqtrade#10638]
Hello Guys,

I have a question. I backtesting and optimzed my strategy and it looks for me good. I try the strategy a few days, but the bot didn ´t find any good trades. 

Can anyone help me?

Sorry for my bad english.

**Comment by froggleston** [comment]
Use the `lookahead-analysis` and `recursive-analysis` commands to verify that your strategy doesn't have fundamental issues with the logic. Check the docs for their usage.

Also, check you have a large enough stake amount, usually >$20 per trade.

**Comment by xmatthias** [comment]
you might also wanna double-check your actual backtest results in detail
just because you've had 30 trades a month doesn't necessarily mean it's spread out evenly with 1 trade per day - so i think aligning the expectations between backtest and dry-run is important.
There's bots that go weeks without a trade - but that's intended - as they simply don't identify a good entry opportunity.
