### ISSUE TITLE
why does adjust_trade_position on order sell needs to be above minimum stake?

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10649]
## Describe your environment

  * Operating system: linux
  * Python Version: __Python 3.12.5___ (`python -V`)
  * CCXT version: __ccxt==4.3.93___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade docker-2024.9-dev-704e32b0__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I have a trade with only one order that is opened by custom_stake_amount. 
Can freqtrade sell this order completely via the adjust_trade_position? 

This is what I tried to do but the backtesting.py::_get_adjust_trade_entry_for_candle expects that the stake returned by adjust_trade_position to be above min_stake.
I would expect this to be tested when buying but why is is this test done also when selling an order?
Is Binance for example enforcing that when you sell ETH to USDT to also respect a minimum stake? I saw it's fixed at 5 USDT when buying but not sure for selling.

Thank you!

**Comment by stash86** [comment]
You can test it on binance directly, whether the sell order needs to obey minimum stake or not.

Also, please read the docs regarding whether you can fully exit a trade via adjust trade callback.

**Comment by xmatthias** [comment]
well stake-amount for position decreases must be

* The adjustment amount must be higher than the minimum order amount (all exchanges have minimum order amounts, usually around 10-20$ - but i've seen them way higher after pairs do significant moves).
* Remaining stake must remain above the minimum order amount (otherwise you'll be unable to sell the "the rest")
* equal to stake_amount (this is a special case to fully exit a position) - and can be done via `return -trade.stake_amount` - as stated [in the documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#decrease-position).


Freqtrade aims to respect the exchange limitations in this regards. For dry-run, it wouldn't technically matter if you sell 1$ or 10$ ... but an exchange would simply reject an order for 1$ - as they enforce minimum amounts.
