### ISSUE TITLE
Implementing Unified Trading Account (UTA) Feature (Bybit & Binance)

### ISSUE THREAD

**Issue by aliengofx** [freqtrade/freqtrade#10648]
## Describe your environment
 
  * Operating system: ubuntu 24.04
  * Freqtrade Version: 2024.8
  
## Your question

Hi! You probably have noticed than Binance stopped offering crypto futures and derivatives trading in EU, you can only trade them through a Unified Trading Account (UTA).

https://www.reddit.com/r/3Commas_io/comments/1dndnng/important_notice_for_binance_futures_traders_in/
https://en.cryptonomist.ch/2024/06/19/crypto-regulation-mica-arriving-on-june-30-what-does-it-mean-for-stablecoin-in-europe/
https://announcements.bybit.com/en/article/migration-of-usdc-derivatives-trading-to-unified-trading-accounts-uta--bltfa0f4defd805a6d3/
https://www.binance.com/en/square/post/9012660554761

Recently, Bybit is also rushing users to switch from Standard to Unified Trading Account (UTA) due to the need to comply with new EU regulations. They also stopped allowing user to create Standard Trading Accounts in EU area. They are now supporting inverse derivatives trading through UTA as well and unfortunately none of these futures can be used with freqtrade atm.

https://announcements.bybit.com/en/article/product-updates-introducing-inverse-derivatives-trading-to-unified-trading-account-uta--blte3dc1e58c8aefd04/

![photo_2024-09-12_11-43-42](https://github.com/user-attachments/assets/dd200f57-d275-4257-9452-31d21e3e580d)
![photo_2024-09-12_10-08-35](https://github.com/user-attachments/assets/980ffb54-d1cd-4727-b332-432e2a58d81e)

A lot of users may be affected, so I would kindly like to ask you when this Unified Trading Account (UTA) feature will be available with freqtrade for Binance and Bybit.

Thank you.

**Comment by xmatthias** [comment]
For Bybit, i disagree with it at least in part (about the reason for the change).
It's been clear since they introduced UTA accounts that they'll sooner or later push users in that direction.

I don't see a relation to EU regulation in this regards though - and it also won't change which futures you can trade - a UTA account can still trade the same futures - you just can't create a standard account anymore (which i think will simplify their internal handling more than it has anything to do with compliance reasons).
It's hence understandable that they push in this direction - and i am even a little surprised that it took them this long.


UTA accounts can be used in the develop version - it'll however be regular, isolated perpetual futures that you can trade - it's just that the account type is slighlty different.

Please make sure to carefully read the [bybit section](https://www.freqtrade.io/en/develop/exchanges/#bybit) related to this.

---

For binance - i do think that the EU will tell them sooner or later that their "regulation workaround" is also not really allowed - it's just a matter of time. It's then a question of "do they want to follow the rules - or follow what most other exchanges do and ignore the EU ...

Personally - i don't have access to Binance futures anymore (not regular futures, not the "new workaround"  futures) - so this is unlikely to be implemented anytime soon. At any rate - for this topic - best follow #10503 - which revolves around this topic.
