### ISSUE TITLE
UI Backtesting - Visualise Result - Profit reasoning

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10651]
## Describe your environment

  * Operating system: linux
  * Python Version: __Python 3.12.5___ (`python -V`)
  * CCXT version: __ccxt==4.3.93___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade docker-2024.9-dev-704e32b0__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
In the tab Visualise Result, the currency percentage gain seems to be misleading. It is calculated as the sum of profits of all trades.
The Run Backtest and Analyze Result tabs calculate correctly the real profit. I expected to have the same value in Visualise Result. 
Or maybe there is an added value to this? 

Thank you!

**Comment by xmatthias** [comment]
I'm not entirely sure what you mean to be honest - so maybe you can be a bit clearer on what you mean specifically.

Run Backtest doesn't show any profit (nowhere, never) - so not sure what you mean with this.
Analyze Result on the other hand has several profit displays - from total profit, to profit per trade, per tag, or by exit reason, and a few others.

Now the Profit shown in the "per trade" column does align with what's shown in Visualize Result (once you've selected a pair the trades will show on the right).

So it's either a confusion on your side - or you'll need to be clearer so that i see what you mean, too.

**Comment by uplight-dev** [comment]
Hello, the profit is displayed in Run Backtest  in the upper left side, after expanding there is Available Results, showing Trade Count and Profit (0.911% in the screenshot )

In In the tab Visualise Result, also on the upper left side can be expanded the "Pair Navigation" and there is the profit as the sum of all profits (58.53%)
In the table from below, indeed the values are correctly aligned with the Analyze Result.

Please ignore the values, I'm doing some tests, so it's for the sake of the example.

![Screenshot_2024-09-16_09-53-35](https://github.com/user-attachments/assets/5265c607-72e5-4002-abd6-ac3d02fb8f7b)
![Screenshot_2024-09-16_09-54-20](https://github.com/user-attachments/assets/26ee6bbc-8776-428e-80f0-8ac2ef8a338e)

**Comment by xmatthias** [comment]
the "available results" pane aligns with the "total Profit" metric in analyze results. 
Don't see where / how that's wrong - as it shows the total profit for this backtest.

Result comparison (if you have more than one backtest loaded) shows the same.

The only value that may need improvement is the "per pair" one in the chart - as that's not aligned with the "per pair" metric - but uses a different calculation method, which won't work well for unbalanced trades (where stake-amount is not identical across trades).

**Comment by uplight-dev** [comment]
Thank you for the feedback.
Should I open a bug for the per-pair metric on unbalanced trades?

**Comment by xmatthias** [comment]
no? 
for the per-pair metric, it's fine - and the chart "pair selection" has been updated (see linked commit).
