### ISSUE TITLE
Liquidation price calculation question

### ISSUE THREAD

**Issue by viper7882** [freqtrade/freqtrade#10668]
Hi admin,

## Describe your environment
  * Operating system: Ubuntu running on top of WSL2 Windows 11 
  * Python Version: 3.10
  * CCXT version: 4.3.61
  * Freqtrade Version: 2024.6
  
## Your question
In both `freqtradebot.py` and `backtesting.py` files, wallet_balance instead of taken from trade.stake_amount:
```python
                    trade.set_liquidation_price(
                        self.exchange.get_liquidation_price(
                            pair=trade.pair,
                            open_rate=trade.open_rate,
                            is_short=trade.is_short,
                            amount=trade.amount,
                            stake_amount=trade.stake_amount,
                            leverage=trade.leverage,
                            wallet_balance=trade.stake_amount,
                        )
                    )
```

Isn't it more logical for wallet_balance value to be taken from wallets? The rationale is to reflect the realistic calculation from exchange especially during backtesting.
```python
                    trade.set_liquidation_price(
                        self.exchange.get_liquidation_price(
                            pair=trade.pair,
                            open_rate=trade.open_rate,
                            is_short=trade.is_short,
                            amount=trade.amount,
                            stake_amount=trade.stake_amount,
                            leverage=trade.leverage,
                            wallet_balance=self.wallets.get_free(self.config["stake_currency"]),
                        )
```

I'm seeing DCA is able to perform better with the above adjustment.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well if you need to change the basis for a calculation to have the bot "perform better" - that's a sign on it's own, no? :laughing: 


It's clear that it'll perform better - as you can simulate a 100k wallet, while taking 100$ positions - and completely change the basis for the calculation, so you'll never be liquidated.
it'll perform better - but once you're live - it won't matter - as the exchange will not adhere to your calculation change.

---

Maybe the parameter name is slighlty missleading (it's thought to support cross futures, too) - but it's intentional this way - as that's how the exchange formula's actually work _for isolated mode_.

Keep in mind that we're talking isolated futures mode only - so "wallet" is actually the isolated wallet for this position (essentially - (roughly, without fees) `entry price * amount / leverage` - not the whole USDT amount you've got in your wallet) - at least in my understanding (and based on my research through the different liquidation price documentations across supported exchanges).


Now i'm happy to be proven wrong if you have compelling evidence that this understanding is wrong (essentially, a link to a documentation, which clearly explains that this calculation works differently).


In cross mode, this would need to be different - but then this whole calculation will need to be quite different - but that's a different topic.

**Comment by viper7882** [comment]
I believe the changes that I was looking into is for cross margin mode instead of isolated mode. You've made a good point here. I think we are done with the earlier question.

Looking back at our discussion, looks like that could be the one of the key line changes to differentiate between isolated and cross margins.

Just for my curiosity, the reason for FreqTrade not to support cross margin is it due to you would like to prevent traders to risk liquidating more than isolated balance in their their account I.e. wouldn't blow up their account?

I have a different goal here where my job is to find out how to stress the strategy and liquidate the account so that I know where the limit of each variable is of a given strategy.

**Comment by xmatthias** [comment]
> Looking back at our discussion, looks like that could be the one of the key line changes to differentiate between isolated and cross margins.

no it's not (at least not alone) - and even there - it's probably not correct this way. 

the whole logic for cross margin changes - where changes to one position must update all other trade's liquidation prices - as it changes the account risk.
It's not terribly difficult to do in theory - but i don't really see the benefits other than increased complexity overall, with little actual benefits.
 
People do over-leverage already - cross-margin will make it worse for essentially no good reason other than greed - which usually is followed by tears.
In my understanding - if you run into liquidation in cross margin - you'll run into liquidation on all pairs at the same time, as the whole account is then liquidated. 
It's however neither a situation i've been in, have observed actively - nor am i trying to get to that point :laughing:

**Comment by viper7882** [comment]
I have no further question. It is a pleasure talking to you, @xmatthias.
