### ISSUE TITLE
Immediately exit after enter

### ISSUE THREAD

**Issue by zhaohui-yang** [freqtrade/freqtrade#10706]
## Describe your environment

  * Operating system: _linux ubuntu 24.04___
  * Python Version: __3.12.3___ (`python -V`)
  * CCXT version: __4.4.3___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ___2024.8_ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

```
{
    "user_data_dir": "PATH",
    "datadir": "DATAPATH",
    "timeframe": "1m",
    "strategy": "SampleStrategy",
    "exchange": {
        "name": "binance",
        "pair_blacklist": [],
        "pair_whitelist": [
            "ADA/USDT:USDT"
        ]
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": true,
        "emergency_exit": "market"
    },
    "unfilledtimeout": {
        "entry": 20,
        "exit": 20,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "fee": 0.0004,
    "dataformat_ohlcv": "parquet",
    "dry_run_wallet": 1000000.0,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "position_adjustment_enable": true,
    "global_leverage": 1.0,
    "stoploss": -1.0,
    "trailing_stop": false,
    "use_custom_stoploss": true,
    "hyperopt_loss": "SharpeHyperOptLoss",
    "hyperopt_jobs": 48,
    "hyperopt_min_trades": 33,
    "print_all": true,
    "epochs": 576,
    "spaces": [
        "stoploss",
        "buy",
        "sell"
    ],
    "max_open_trades": 10,
    "close_position": false,
}

```
Hello, I used the 2023 version of the code for backtesting before, and later changed to 2024.8. However, I found that when backtesting, the trade was exited directly after entering. I investigated and found that the function _get_exit_for_signal directly placed an exit order, and the stoploss price was the high or low of the bar, so the trade was directly completed within the bar, resulting in the duration being 0, and then the trading fee was lost. I would like to ask if there is any configuration that I need to pay attention to? Thanks

The result is as below,
```
┏━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃          Pair ┃ Trades ┃ Avg Profit % ┃ Tot Profit USDT ┃ Tot Profit % ┃ Avg Duration ┃  Win  Draw  Loss  Win% ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ ADA/USDT:USDT │    260 │        -0.18 │         -88.593 │        -0.01 │      0:00:00 │    0     0   260     0 │
│         TOTAL │    260 │        -0.18 │         -88.593 │        -0.01 │      0:00:00 │    0     0   260     0 │
└───────────────┴────────┴──────────────┴─────────────────┴──────────────┴──────────────┴────────────────────────┘
```

**Comment by hippocritical** [comment]
duration 0 means that you close in the same candle as you opened, freqtrade "wanders" through the candle from open to low to high to close. If you (for example) use a tight trailing stoploss, then you "instantly" close.

Assuming you are on a 1d timeframe and trail hard and the trailing hits after 1 hour, then freqtrade will not know that it hit after an hour since it only can go through the candles it actually sees via the 
OHLCV data (open high low close volume).

Open
High
Low
Close
Volume

these  5 values are only there once per candle width. so assuming you are on a 1d timeframe then it s only 5 numbers for the whole day.

A solution usually would be that you trail less tight,f or example.

**Comment by zhaohui-yang** [comment]
> duration 0 means that you close in the same candle as you opened, freqtrade "wanders" through the candle from open to low to high to close. If you (for example) use a tight trailing stoploss, then you "instantly" close.
> 
> Assuming you are on a 1d timeframe and trail hard and the trailing hits after 1 hour, then freqtrade will not know that it hit after an hour since it only can go through the candles it actually sees via the OHLCV data (open high low close volume).
> 
> Open High Low Close Volume
> 
> these 5 values are only there once per candle width. so assuming you are on a 1d timeframe then it s only 5 numbers for the whole day.
> 
> A solution usually would be that you trail less tight,f or example.

I guessed that this might be the reason, so I set trailing_stop to false, and then stoploss to -1 so that it would not exit directly. As shown in the config.

**Comment by hippocritical** [comment]
there is an exit and entry reason to see what happened and why, what is the exit reason?

**Comment by zhaohui-yang** [comment]
> there is an exit and entry reason to see what happened and why, what is the exit reason?

The problem is in the should_exit function of strategy/interface.py. The function returns stop_loss, and then automatically sets close_price to the high or low of bar, and then triggers close directly after entry. So exit_reason is 'stop_loss'.

**Comment by xmatthias** [comment]
if your exit reason is `stop_loss` - then the problem is that your stoploss is too tight.

It's surely possible that behavior in this changed between 2023 and now - but it improved towards accuracy - if you've got a stoploss that's smaller than average candle movements (otherwise it wouldn't trigger as stoploss) - then your strategy is simply missconfigured - and live / dry will almost certainly have similar behavior.


I'd also advise to not use GPT generated configurations. You've got at least one key in there which doesn't exist / never existed on freqtrade configurations - so it's clearly being ignored.
(i didn't check all keys - but it's more than one after a very quick spot-check).
