### ISSUE TITLE
create_userdata_dir doesn't handle linux symlinks

### ISSUE THREAD

**Issue by kamil6x** [freqtrade/freqtrade#10720]
The create_userdata_dir function doesn't recognize directory links created with ln -s and tries to create the direcotory.  When creating several bots on a single system the exchange data directory is several gigabytes and having an individual copy for each bot is not feasible. Therefore a single data directory with links to it, from each user_data directory is space efficient.  

create_usedata_directory should handle directory links properly.

## Describe your environment

  * Operating system: __Ubuntu 24.04.1 LTS__
  * Executed in Jupyter Notebook strategy_analysis_example.ipynb
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.8
  
## Describe the problem:
---------------------------------------------------------------------------
Create_userdata_dir should recognize sym links as directories instead of trying to create a directory when the symlink already exists and directory creation fails.

Moved the user_data/data directory to another drive and created a soft link to it in user_data directory; with ln -s.  All freqtrade function seem to work correctly except with executing the following code in Jupyter lab (freqtrade docker jupyter):
config = Configuration.from_files(["user_data/configs/config.json"])

### Steps to reproduce:

  1. Move the user_data/data directory to another drive.
  2. Create a link to the directory with ln -s /new_drive/data user_data/data
  3. execute the code config = Configuration.from_files(["user_data/configs/config.json"]) from Jupyter notebook.

  
### Observed Results:

  * What happened? - FileExistsError
  * What did you expect to happen? The code to recognize the file link to a directory and not try to create one.

### Fix suggested by ChatGPT 4o

def create_userdata_dir(directory: Union[Path, str], create_dir: bool = True) -> Path:
    folder = Path(directory).expanduser().resolve()
    subfolders = ["data", "logs", "strategies", "configs"]

    for f in subfolders:
        subfolder = folder / f
        if subfolder.exists():
            if subfolder.is_dir():
                continue
            elif subfolder.is_symlink() and subfolder.is_dir():
                continue  # Skip if it's a symlink to a directory
            else:
                raise FileExistsError(f"File exists and is not a directory: {subfolder}")
        else:
            subfolder.mkdir(parents=False)
    return folder

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
FileExistsError                           Traceback (most recent call last)
Cell In[2], line 27
     18     print(f"Directory '{user_data_dir}' does not exist.")
     21 # Customize these according to your needs.
     22 
     23 # Initialize empty configuration object
     24 #config = Configuration.from_files([])
     25 # Optionally (recommended), use existing configuration file
     26 #config = Configuration.from_files(["user_data[/config.json](http://xxxxxx8/config.json)"])
---> 27 config = Configuration.from_files(["user_data[/configs/config.json]"])
     29 # Define some constants
     30 config["timeframe"] = "5m"

File [/freqtrade/freqtrade/configuration/configuration.py:69](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/configuration.py#line=68), in Configuration.from_files(files)
     67 # Keep this method as staticmethod, so it can be used from interactive environments
     68 c = Configuration({"config": files}, RunMode.OTHER)
---> 69 return c.get_config()

File [/freqtrade/freqtrade/configuration/configuration.py:51](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/configuration.py#line=50), in Configuration.get_config(self)
     46 """
     47 Return the config. Use this method to get the bot config
     48 :return: Dict: Bot config
     49 """
     50 if self.config is None:
---> 51     self.config = self.load_config()
     53 return self.config

File [/freqtrade/freqtrade/configuration/configuration.py:104](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/configuration.py#line=103), in Configuration.load_config(self)
    100 self._process_common_options(config)
    102 self._process_trading_options(config)
--> 104 self._process_optimize_options(config)
    106 self._process_plot_options(config)
    108 self._process_data_options(config)

File [/freqtrade/freqtrade/configuration/configuration.py:287](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/configuration.py#line=286), in Configuration._process_optimize_options(self, config)
    267 configurations = [
    268     (
    269         "timeframe_detail",
   (...)
    282     ("timerange", "Parameter --timerange detected: {} ..."),
    283 ]
    285 self._args_to_config_loop(config, configurations)
--> 287 self._process_datadir_options(config)
    289 self._args_to_config(
    290     config,
    291     argname="strategy_list",
    292     logstring="Using strategy list of {} strategies",
    293     logfun=len,
    294 )
    296 configurations = [
    297     (
    298         "recursive_strategy_search",
   (...)
    306     ("freqai_backtest_live_models", "Parameter --freqai-backtest-live-models detected ..."),
    307 ]

File [/freqtrade/freqtrade/configuration/configuration.py:203](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/configuration.py#line=202), in Configuration._process_datadir_options(self, config)
    200     config.update({"user_data_dir": str(Path.cwd() [/](http://xxx/) "user_data")})
    202 # reset to user_data_dir so this contains the absolute path.
--> 203 config["user_data_dir"] = create_userdata_dir(config["user_data_dir"], create_dir=False)
    204 logger.info("Using user-data directory: %s ...", config["user_data_dir"])
    206 config.update({"datadir": create_datadir(config, self.args.get("datadir"))})

File [/freqtrade/freqtrade/configuration/directory_operations.py:85](http://xxx/lab/tree/user_data/notebooks/freqtrade/configuration/directory_operations.py#line=84), in create_userdata_dir(directory, create_dir)
     83     subfolder = folder [/](http://xxx/) f
     84     if not subfolder.is_dir():
---> 85         subfolder.mkdir(parents=False)
     86 return folder

File [/usr/local/lib/python3.12/pathlib.py:1311](http://xxx/usr/local/lib/python3.12/pathlib.py#line=1310), in Path.mkdir(self, mode, parents, exist_ok)
   1307 """
   1308 Create a new directory at this given path.
   1309 """
   1310 try:
-> 1311     os.mkdir(self, mode)
   1312 except FileNotFoundError:
   1313     if not parents or self.parent == self:

FileExistsError: [Errno 17] File exists: '[/freqtrade/user_data/data](http://xxx/lab/tree/user_data/notebooks/user_data/data)'  ```

**Comment by froggleston** [comment]
You shouldn't need to call `create_userdata_dir` more than once. You also don't need to use a symlink.

Use the `userdir` configuration property, and set it to the same directory for each bot. You can do the same with `datadir` for large historical data directories.

Furthermore, please don't paste GPT code in as suggestions to issues. GPT doesn't understand code, creates bogus code, and shouldn't be a replacement for reading and understanding the actual code.

**Comment by xmatthias** [comment]
Well the point is (if you look at the trace carefully) - `create_user_dir()` is called implicitly when loading the config - so it's not an explicit `freqtrade create-userdir` call.
the userdir exists (so there's technically nothing to do for the method) - and the data-dir has been linked "someplace" else.

---

Now i'm not sure why you don't just point user_data someplace else (that's how i do it).

I'd also want to point out that shared data-dirs are not really supported for some scenarios (more than one running bot with either freqAI or orderflow using the same user_data/data directory) - as they both write to that same directory - but don't know from each other, so with unfortunate timing, one of the 2 (or both) can have errors or become locked.

For analysis / backtesting, this shouldn't be a problem (no writes to that directory).

---

Now the thing is - `.is_dir()` is a sufficient check **if** the symlink is valid and points to an actual directory (the only case i see us supporting)
it returns false if it's an invalid symlink (see below - red is invalid links)

![image](https://github.com/user-attachments/assets/7bb61170-538c-44b0-848f-094f875f48a6)
![image](https://github.com/user-attachments/assets/9dbfc3ca-5150-4114-b802-097884d6d403)

_(this same also applies if the symlink is created without trailing slash)_

This suggests that the failure actually happens because your symlink is invalid and points to a non-existing location (or to a file).

I'm not sure that's a scenario we should support - at least not in the way you propose.

While it shouldn't crash in this form - i think failing is correct (but with a clearer errormessage).
If we'd skip the (in your case apparently invalid) symlink - you'd simply postpone the problem to where freqtrade tries to use the directory and would  encounter failures once you try to use that directory.
while it's a symlink - it's not a **valid** symlink - so using it as if it were a directory would fail.

![image](https://github.com/user-attachments/assets/6e556c47-ef6b-48ef-bdd1-77d7a11d6ecb)
