### ISSUE TITLE
Kucoin futures integration

### ISSUE THREAD

**Issue by TheyCallMeSticky** [freqtrade/freqtrade#10750]
## Describe your environment
(if applicable)

  * Operating system: Windows 11 / WSL Ubuntu 22
  * Python Version: 3.10.12 (`python -V`)
  * CCXT version: 4.4.9 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.10-dev-e2adfe9ea (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Hello ! 

I want to integrate Kucoin Futures support into freqtrade. On CCXT, it's a separated exchange and it's supported. 

As a developer, i can participate.

**Comment by xmatthias** [comment]
Kucoin is an exchange that's not officially supported because it's API is known to be flaky / unreliable. Trying to Supporting that actively is a nightmare.

From what i understood, their Futures API is worse from a stability / reliability point of view - so i think this will be time wasted (especially in the maintenance/support phase).

---

While in theory - it could be added in a "community tested" approach (similar to spot) - that's a bit more difficult for futures, as that requires quite additional code and logic, which will need both maintenance (also going forward), and also eventual help in case people have problems.


While i appreciate the incentive to try and contribute - I don't think it's a good idea at this point.

It's not personal against you - however you'd be a new contributor - who never interacted with this repo before.
So it's becomes a question of trust to some degree.
It's unknown if you'll stick around (for how long? how much time a week / month can you dedicate to eventually support users), how responsive you'd be in case of questions, ... 

Assuming you'd lost interest in X months time there'd be 2 options
it'd either fall back to existing contributors / maintainers to try and support an exchange we know is flaky before even trying to implement it - which quite honestly, I've got no will to do for an exchange i know doesn't work well.
The alternative is to simply remove that support again (remove the code contributed, ...) - but then it'd be even more time wasted, both on your side trying to add it - and on our side reviewing code, merging, ...

**Comment by TheyCallMeSticky** [comment]
Ok, i understand why it's not a good idea to open it as an official release. I'll do it on my side. Too much problems

**Comment by xmatthias** [comment]
what you can always do is let us 
* know how well it works (or doesn't)
* how easy / difficult it was

We can then still determine if it makes sense to include it or not ;)

**Comment by TheyCallMeSticky** [comment]
As European laws tends to complicate futures trading for their inhabitants. They should ban kucoin also one day. 

I'll move to hyperliquid. It's supported by CCXT. No kyc, DEX. 

Did you already try to implement it ? Any information about stability / security ?

**Comment by xmatthias** [comment]
> They should ban kucoin also one day.

That's not how it works - technically, futures trading is banned on a country by country basis.
It's the exchanges that decide to either follow or ignore these regulations (obviously countries going after specific exchanges can change their mind - but it's not a "the country said, exchange X is banned from using futures" topic). :laughing: 

for hyperliquid - best follow #10377. There's some work done on that - and it seems to work mostly fine with very recent versions of ccxt - but so far, testing for spot is ongoing, with issues being found "weekly" (more or less) :laughing:

**Comment by weyerma** [comment]
Is there now any possibility to enable KuCoin Futures? I understood the API is not really reliable, but even then it would be a great feature because there are many other pairs available on this exchange and for shorting i need the futures option.

**Comment by stash86** [comment]
As said above, unless someone willing to commit their time for long-term supporting Kucoin, then no possibility in near future
