### ISSUE TITLE
The exchange and freqtrade sync not correct

### ISSUE THREAD

**Issue by zeco07** [freqtrade/freqtrade#10837]
## Describe your environment

  * Operating system: debian
  * Python Version: 3.11.2 (`python -V`)
  * CCXT version: 4.4.6 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

The exchange and freqtrade sync don't fit so well that bot keep missing out on selling, any suggestions?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by froggleston** [comment]
Please provide more information. What does "missing out on selling" mean? Please provide logs and evidence.

**Comment by zeco07** [comment]
I'm sorry that I'm using a translator.

When the bot has to sell, the price has already dropped and it can't be sold.

**Comment by xmatthias** [comment]
Well that sounds like it's simply caused by misaligned / bad pricing decisions [docs](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).

That whole section of the docs will contain information on how to approach pricing - but it assumes some basic understanding on how orderbooks / order filling works (it's not related to bot trading, really - but to how exchanges behave with different prices).

This information is based on suspicions about the very little information we got.
Without further information on what you're actually experiencing, there's little else we can suggest.
