### ISSUE TITLE
Telegram: "custom_exit": "off"

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10895]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Turning off Telegram posts for custom exits works partially: 

if the condition is simply:
if current_profit >= self.min_profit: return 'custom_exit'
. . ."custom_exit": "off" indeed turns off all custom exit messages.

but with this kind of exit conditions:
if current_profit >= self.min_profit_1: return 'min_profit_1'
if current_profit >= self.min_profit_2: return 'min_profit_2'
if current_profit >= self.min_profit_3: return 'min_profit_3'
if current_profit >= self.min_profit_4: return 'min_profit_4'

. . .Telegram still posts the messages "Exiting XXX/YYY. . .", the messages "Exited XXX/YYY. . ." aren't posted as expected.

I have turned off Telegram messages like this (partial config of the Bot):

`"telegram": {
    "allow_custom_messages": false,
    "notification_settings": {
      "entry": "off",
      "entry_fill": "off",
      "exit": {
        "roi": "off",
        "emergency_exit": "off",
        "exit_signal": "off",
        "trailing_stop_loss": "off",
        "stop_loss": "off",
        "custom_exit": "off"
      },
      "exit_fill": "off",
      "entry_cancel": "off",
      "exit_cancel": "off"
    }`

(entry and exit signal posts are entirely turned off with this configuration)

Probably, there is an additional switch, I need to edit for no more having any custom exit posts, no matter how the def looks, have you got an idea?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
For exits - there's 2 levels of "precision" if you will

The way you've configured it (as object) - each exit signal can be controlled separately, allowing you to hide ROI messages, while still seeing certain types of messages (e.g. stoploss) within the "exit" structure.

you could hence add `"min_profit_2": "off"` - and disable this particular exit - while still keeping "min_profit_1" turned on.
On the other hand, this also means that all exit reasons that are not defined explicitly are on.


If that's not what you're after, but instead you'd like to disable "all" completely - you can simply use `"exit": "off"` (instead of the whole object that now is your exit structure).
I'll enhance the docs a bit in this regards - as reading them again for this issue - i don't think this behavior is immediately clear.

**Comment by myNextCoder** [comment]
I thank you. I choose "exit": "off" for my specific case, but it is good to know, that I can granularly mute custom exits, if needed.
