### ISSUE TITLE
`brew install libomp` is not documented

### ISSUE THREAD

**Issue by xzmeng** [freqtrade/freqtrade#10900]
And `brew install hdf5` `brew install c-blosc`, they're expected to appear in the manual installation part of the docs.

**Comment by xmatthias** [comment]
I'm honestly not sure if they're actually necessary in this day and age.

we add them in CI - sure - but they come from a time where hdf5 didn't provide proper wheels.
Now i lack a mac to test this out for sure - but i may get the time to let this play in CI ... with the assumption that if CI passes there, wheels will be fine and the system-level installs won't be necessary (i can't confirm that due to lack of mac).
