### ISSUE TITLE
Impossible to load Strategy . This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by P-PPPP** [freqtrade/freqtrade#10927]
## Describe your environment

  * Operating system: Windows 
  * Python Version: 3.12.7 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*I Create a new strategie and did not found a file with error:*
`Impossible to load Strategy 'SuperTrendTPSLLong'. This class does not exist or contains Python code errors.`

then i use `freqtrade list-strategies` to list all my strategies but my strategie was not in there. However, an old one (which i had deleted in windows before) appeared.
then i delete the container and rerun `docker compose up`, my strategie came up again.

**Comment by gleim** [comment]
Seeing also on Linux, with and without Docker.

**Comment by stash86** [comment]
Please open your own issue with detailed informations

**Comment by xmatthias** [comment]
For future readers - maybe https://www.freqtrade.io/en/latest/faq/#im-getting-impossible-to-load-strategy-when-starting-the-bot is of help.
otherwise, please open a new issue with detailed information. 
Attaching to a random other issue won't work - as this particular problem can have many reasons - and it's quite unlikely that you're actually encountering the same exact problem.
