### ISSUE TITLE
Rounding, Overflows and Security Issue

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#10938]
* Operating system: Linux
  * Python Version: Python 3.12.3
  * CCXT version: 4.4.6
  * Freqtrade Version: 2024.10

I am not 100% sure if this is a bug.

An example rounding for a trade:  0.000013088899928 and another 1.52279274512304 

Amount 22010917 
Open Rate 0.000018167960369
Close Rate 0.00001898

Could these kinds of number lead to overflows?
Should the rounding be to 8 decimals or even 10 decimal places maximum
and should the Amount be maxed out to some value less than overflow value
Sometimes I see trades opened with 0 as the amount, should the amount always be checked greater than 0

Like I said, I do not know if it's a bug, potential security issue.![Image](https://github.com/user-attachments/assets/0506b9fd-b249-418b-883b-936be8fb1e01)

**Comment by xmatthias** [comment]
It's neither.

At max, it's floating imprecision - which in reality, is not a problem, as the value is truncated before being sent to the exchange.
Rate rounding happens to the precision the exchange defines.

This can be 2 decimals (BTC) - or anything up to 12 decimals for other pairs, usually depending on the price.

Now some exchanges (e.g. kucoin) don't specify an actual precision, and return data with 16 digits precision - so we'll be using that.
Funnily, on exchange, they do then round the values - so it's a rounding problem in their API, really 😆

Open rate displays in this way because we show the one that's been given in the UI (because of kucoin, really) - not the one that's been rounded to precision - which is somewhat intentional.
One can argue that this maybe should be changed (before sending to the exchange, the value will have been truncated anyway).
