### ISSUE TITLE
Using Trade.get_open_trade_count() in custom_exit() probably leads to excessive memory usage

### ISSUE THREAD

**Issue by Debeet** [freqtrade/freqtrade#10940]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: 3.12.1 (`python -V`)
  * CCXT version: 4.4.24 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

When using Trade.get_open_trade_count() in custom_exit() callback in live memory slowly increases over time until it crashes. Freqtrade did not free up this memory. To reproduce this issue I had 2 active trades for one day although it hogged the memory much sooner.

```
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float, current_profit: float, **kwargs):
        # Sell any positions at a loss if they are held for more than 7 days.
        if current_profit < 0.0 and (current_time - trade.open_date_utc).days >= 2 and Trade.get_open_trade_count() >= self.config['max_open_trades']:
            return 'unclog'
```

While looking at get_open_trade_count() I can see that it looks up data in the database:
https://github.com/freqtrade/freqtrade/blob/3276dd6b94adcb6df4f2362fabb22216b9a37317/freqtrade/persistence/trade_model.py#L1491

Perhaps there's a problem with SQLAlchemy and/or the way it's being used. Maybe periodically closing and reopening database connection could help with this?

**Comment by xmatthias** [comment]
quite honestly, i'm pretty tempted to simply close this issue as "you can't reproduce".

it sounds like pure guesswork - yesterday, you had a memory leak due to an outdated python version - which we know where it came from - and you confirmed is fixed by updating python.
Is it leaking that much that you can be sure exactly this is causing it?  how much does it leak per hour? how much per minute? 

How long did you run that same strategy, with the same python version and code - but without this function call to have a comparison and be sure you can point the finger at one particular method?
i doubt there's even been enough time to do such a test ... ?

**Comment by Debeet** [comment]
> How long did you run that same strategy, with the same python version and code - but without this function call to have a comparison and be sure you can point the finger at one particular method?

I tried to do the same amount of time with and without the get_open_trade_count() although the version with the call didn't last long (from about 500 MB of memory to 1,7 GB in a matter of 2h). Version without get_open_trade_count() wasn't killed and was up to 1,35 GB until I closed it myself. Nothing else was changed in the code or the environment, I even rebooted the system before both tests to have a clear situation.

I'll try to figure this out on my own.

**Comment by xmatthias** [comment]
Quite honestly - the code in that function does nothing other than return an integer.

Having tried it now from within `bot_loop_start()` (called every 5 seconds - independent of open trades) - it doesn't seem to leak. Within half an hour - there was absolutely no increase in memory after the initial memory loading.

Also - as you say yourself - also without this - it increased - not as much - but from the wording, i'd think that's because you closed it yourself, leaving it there for longer would've probably caused the same amount of memory.
