### ISSUE TITLE
Is possible to make an indicator using the order book?

### ISSUE THREAD

**Issue by luchobarretootc** [freqtrade/freqtrade#10963]
Hi, I'm new to algorithmic trading and I'm learning how to use Freqtrade. I'm trying to render simple indicators using the order book in freqUI like this:
```
timeframe = "1m"

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    if self.dp and self.dp.runmode.value in ('live', 'dry_run'):
        order_book = self.dp.orderbook(metadata['pair'], 10)
        best_bid = order_book['bids'][0][0]
        best_ask = order_book['asks'][0][0]
        spread_relative = (best_ask - best_bid) / best_ask

        dataframe['best_bid'] = best_bid
        dataframe['best_ask'] = best_ask
        dataframe['spread_relative'] = spread_relative

    return dataframe
```
However, I’m only getting a constant line on my chart. Is this expected behavior, or am I doing something wrong?
![Image](https://github.com/user-attachments/assets/544f50c5-4d43-4f10-ac46-6d842520185d)

**Comment by Axel-CH** [comment]
Order book data is not available for backtesting, only for live.
For backtesting, you have ohlcv data.
You also have the experimental feature of orderflow data https://www.freqtrade.io/en/stable/advanced-orderflow/

**Comment by luchobarretootc** [comment]
Hi @Axel-CH , thanks for answering. I'm aware that the order book data is only available for live environments, which is why I’m testing this in live mode. The issue I’m facing is that while I can see the values from the order book updating correctly in the logs, the chart for the indicator on the dataframe shows a constant value or doesn’t update dynamically as expected. Is there a specific approach or workaround within Freqtrade to visualize such real-time data effectively?

**Comment by stash86** [comment]
that's because you are entering a single value into the column, which means every rows' value will be the latest best_bid and best_ask.

Every new candles arrive, old dataframe will be replaced by new one, which means old values will be lost

**Comment by Axel-CH** [comment]
The UI plot is optimized to display series data stored in columns and not single point numerical ones. Also, displaying such value on one candle would not be accurate as it implie that the "best_bid" is calculated from all orderbook datas available during the candle.

That won't be the case as you only get a sample of the order book in an instentaneous manner and not over the candle period.

I don't see a practical work around for this that won't include UI code modifications.
I will let other contributors more familiar with Ui related subjects contradict me if they see something I don't.

**Comment by stash86** [comment]
you will need to store the values into a dict object containing the candle datestamp and best_ask and bid. Then on populate_indicators, you will loop through the dict and apply the best ask and bids' values to the appropriate rows based of the datestamp.

No example for that, so you need to play around to get it right

**Comment by xmatthias** [comment]
it's a line because you assign a scalar to a series - thinking in excel terms - every row gets assigned the latest value.
A quick workaround to this is probably something around `dataframe.iloc[-1]['best_bid'] = best_bid` (not suited for backtesting!) - so the data will need to build up over time. It'll still remain one snapshot per candle though - and i don't think a more granular level makes sense, as any level freqtrade can support will still be missing 90% of the actual orderbook movements.

---

Now the problem is with the data granularity.
Sure - you get access to orderbook data (which can also build up history if done correctly) - but is it really useful to you?

it's a snapshot in time - depending on the configuration, either once per candle, or once every ~5s - on a value that changes _multiple times per second_ in real time (just look at an orderbook chart on exchange).

Independent of settings - you won't be able to capture all orderbook moves - letalone trying to store this data in a historic manner so you can attempt to backtest this.
If that "single snapshot per candle" is fine for what you need - sure - go for it, i think the building blocks are in this issue.

If you want to capture orderbook movements - don't.

This is absolutely not  a "simple indicator" (your words) - but a _very_ advanced concept - one where professional HFT firms with millions of budget are often still struggling to keep the amount of data in check.

**Comment by luchobarretootc** [comment]
Hi everyone,

Thanks so much for the detailed explanations and suggestions. I now understand why the issue occurs and the limitations when working with order book data in Freqtrade. I’ll experiment with these ideas and share any progress. Thanks again for the insights!
