### ISSUE TITLE
FreqUI wrong open profit values on comparison page

### ISSUE THREAD

**Issue by andrasmining** [freqtrade/freqtrade#10969]
## Describe your environment

  * Operating system: Bot running on Ubuntu 22 LTS, UI issue comes up in every browser (tested Chrome, Safari)
  * Python Version: 3,12,3
  * CCXT version: N/A
  * Freqtrade Version: 2024.10
  
## Describe the problem:

Check the screenshot: ![Image](https://github.com/user-attachments/assets/c3c712fd-0bff-406c-9407-ea86329b22e7)

On the bot comparison page, the sum of open profit does not match the sum of the single values in the table below. The correct values are the single ones. The sum is wrong.
Closed profit is correct.

### Steps to reproduce:

N/A
  
### Observed Results:

See problem description

### Relevant code exceptions or logs

Nothing relevant. Bot is running for a year now with same setup. I started to see this issue after upgrading to 2024.08 or 09 I think.
As you can see I have multiple bots on the ss, all of the "sum of open profit" show wrong values. Either in minus or plus.

Any idea what could be the issue?

Thank you for your help guys, great tool btw, absolutely loving it! 👍

**Comment by andrasmining** [comment]
As you can see I have multiple bots, all of the "sum of open profit" show wrong values. Either in minus or plus.

**Comment by xmatthias** [comment]
The values are not wrong - but represent different things - which is actually intentional.

The individual trades profit shows you the currently open (unrealized) profit for open trades - excluding already realized gains or losses.
The bot summary shows a total - which is both open (unrealized) and closed (realized) profit for open trades.

For individual trades, the "trade detail" page does have both profits (total profit, as well as unrealized profit) - and you'll see that the trades may be **currently** i profit - but the total realized value will be negative (at least on one / some of them).

If anything is wrong / misleading - then the individual trades display, where in reality, both current and total profit should be displayed - but is not due to space constraints.


(as an aside, i'd encourage you to copy/paste images to the github issue directly. That avoids them going away leaving the issue way less useful in the future, and doesn't have us go off-platform)

**Comment by andrasmining** [comment]
screenshot added

checked again. All good. Thanks Matthias for clarification! 
For clarification for others: I already had losses on those trades (eg. SLERF) but did not close the trade, only the position partly and was "grinding" it further. This means currently I am in profit on SLEFR, but already closed some positions with losses.
