### ISSUE TITLE
Short signal for futures

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#11029]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: 2.7
  * CCXT version:  ccxt 4.4  * 
  * Freqtrade Version: latest release at post time (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

As there are entry signals to be configured in strategy, are there shorts signals for people who use exchanges with futures ? If so, how you configure that ? 

for instance you have that basis 

```
minimal_roi = {
        "60":  0.01,
        "30":  0.03,
        "20":  0.04,
        "0":  0.05
    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -0.10

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # trailing stoploss
    trailing_stop = False
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02

    # run "populate_indicators" only for new candle
    process_only_new_candles = True

    # Experimental settings (configuration will overide these if set)
    use_exit_signal = True
    exit_profit_only = True
    ignore_roi_if_entry_signal = False

    # Optional order type mapping
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }
```

and you had some like 

```
minimal_roi = {
        "60":  -0.01,
        "30":  -0.03,
        "20":  -0.04,
        "0":  -0.05
    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = 0.10

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # trailing stoploss
    trailing_stop = False
    trailing_stop_positive = -0.01
    trailing_stop_positive_offset = -0.02

    # run "populate_indicators" only for new candle
    process_only_new_candles = True

    # Experimental settings (configuration will overide these if set)
    use_exit_signal = True
    exit_profit_only = True
    ignore_roi_if_entry_signal = False

    # Optional order type mapping
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

```

some like that ? WHich would make me understand why buy was replaced buy entry and sell by exit

**Comment by elestranobaron** [comment]
i saw the can_short = true there https://www.freqtrade.io/en/latest/leverage/ but could'nt find more details

**Comment by elestranobaron** [comment]
and can the strategy used be the same ?

**Comment by elestranobaron** [comment]
the values i gave are just example the question is more about the structure of the configuration

**Comment by Axel-CH** [comment]
To enable short trading, you must add: `can_short = True` in your strategy

**Comment by xmatthias** [comment]
> latest release at post time

Let me repeat this a last time for you - this is not a valid release - and people will not care to look "what was the release on the date this was published".
There's a clear command that is to be executed - what's so difficult in adding this _if you got the ccxt version_ - which is WAY harder to get.
For this issue - it's mostly irrelevant - next issue - i'll however close without further comment.


Also - please use the edit functionality if you think you've missed something.
Adding 1 line comments in 1 minute intervals makes this issue near unreadable.

---

I think you're misreading how values are to be interpreted.

things like `minimal_roi` and `stoploss` relate to profit - not "price increase".
As such - they include fees - but they're also direction independent ( ` "60":  0.01,` is still 1% profit - no matter if that trade is long or short).

There's not much reason about this as quite honestly - in the 2 years since having futures as features - this is not a question anyone asked - not least because  the documentation for the individual features mentions this

> The `stoploss` configuration parameter is _loss as ratio_ that should trigger a sale.

[source](https://www.freqtrade.io/en/stable/stoploss/)
(highlight added for clarity)

**Comment by elestranobaron** [comment]
SO that mean the strategy is the same for Long or Short ? You can keep the same strategy with the same signals right ?

**Comment by elestranobaron** [comment]
and las t question when i add can_short = true buy or sell the bot 'll choose accordingly right ?

**Comment by Axel-CH** [comment]
Please take a look at the strategy exemple, you will have a better understanding: [Strategies exemple](https://github.com/freqtrade/freqtrade-strategies/tree/main/user_data/strategies/futures)

**Comment by elestranobaron** [comment]
ok thanks

**Comment by Axel-CH** [comment]
A git issue is not a chat, please take time to make sure to include all knowed questions in your new message.

**Comment by elestranobaron** [comment]
ok thanks
