### ISSUE TITLE
handling stoploss from absolute based on an indicator

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#11047]
## Describe your environment

  * Operating system: Linux mint
  * Python Version: 3.10.4
  * CCXT version: 4.4.24
  * Freqtrade Version: 2024.10
  
## Your question

I am trying to set custom stop loss based on an indicator like so:
```
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime,
                        current_rate: float, current_profit: float, after_fill: bool,
                        **kwargs) -> Optional[float]:
dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)

last_candle = dataframe.iloc[-1].squeeze()  
if trade.is_short:
      if last_candle['indicatorX'] == 1 and last_candle['indicatorY'] != 1:
          short_stop_price = current_rate * 1.002
          diff = 100 * (self.sell_short_loss_factor_two.value - 1)
      
          if current_rate >= short_stop_price: # My issue is here
                  logging.info(f'Trigger price is lower than current rate for {pair}, setting stop loss will be skipped')
                  return None
          logging.info(f'Long signal on: Setting stoploss for {pair} at {short_stop_price} {diff}% higher than {current_rate} (short)')
          return stoploss_from_absolute(short_stop_price, current_rate, is_short=trade.is_short)
```
The current problem is that if the bot stops for a while then turned on. It might find that it needs to exit a trade with the custom stop loss for the (short) trade. However, the current rate is already above the necessary stop price. So bybit throws this error:
```
ccxt.base.errors.ExchangeError: bybit {"retCode":110093,"retMsg":"expect Falling, but trigger_price[78170000] \u003e= current[75760000]??LastPrice","result":{},"retExtInfo":{},"time":1733500535002}
```
So I have had to forceexit the trade manually and everything runs normally again. My question is, would I be summoning the devil if I cancel the stoploss on exchange for that trade like so:

```
from freqtrade.freqtradebot.FreqtradeBot import cancel_stoploss_on_exchange
    try:
        cancel_stoploss_on_exchange(trade)
        logging.info(f'Trigger price is lower than current rate for {pair}, setting stop loss will be skipped')
        return None
    except Exception as e:
        logging.info(e)
```
Does it even make sense? All help appreciated.

**Comment by xmatthias** [comment]
well no it doesn't make sense.

If placing a stoploss fails - then the expected behavior is an emergency exit.
If that doesn't happen, then normally, the error code mapping in ccxt is wrong, not an  `InvalidOrder` exception (your very truncated sample makes it look like a generic `ExchangeException` - but that's difficult to tell without the full stacktrace).

If you want to handle this situation differently yourself - you can rely / compare with current_rate - so you can handle the case of "crossed already" differently.

You should however evaluate if it makes sense to have a (production) bot down for a longer period of time - that's a risk in it's own - one which backtesting cannot even try to cover or simulate.
