### ISSUE TITLE
How to Configure Freqtrade for Stop-Limit Entry, Progressive Take Profits, and a Single Stop Loss ?

### ISSUE THREAD

**Issue by marcfcrypto** [freqtrade/freqtrade#11045]
Hi everyone,

I’m trying to set up a complex trading strategy using Freqtrade on Binance, and I could use some guidance. Here’s what I’m aiming to achieve:
	1.	Stop-Limit Order for Entry: I want to enter a long position only when the price hits a specific level (stop) and then executes at a predefined limit price.
	2.	Multiple Take Profits: I would like to set progressive take profit levels (e.g., 25% at a X price, 50% at a X price...).
	3.	Single Stop Loss: A unified stop-loss level for the entire position that triggers if the price moves against me beyond a certain threshold.

I’ve been exploring the documentation and understand that custom_stoploss and custom_exit_price might help. However, I’m unsure how to properly configure these for my use case. Specifically:
	•	How can I define the stop-limit entry condition in the strategy?
	•	What’s the best way to implement progressive take profits without creating conflicts in the logic?
	•	How can I ensure the stop-loss applies consistently across all portions of the trade?

Any example configurations, scripts, or insights would be greatly appreciated! If anyone has tackled a similar setup, your experience would be invaluable.

Thank you in advance for your help!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.

We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.


Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Stoploss is in "risk" - so if you configure it as 20% - that'll assume 20% risk (not 20% price move - which can be important in leveraged strategies). It always applies to the full position.

in theory, you can probably use the default static stop - which acts as a hard stop for the position.
If you need something a little more flexible (different values per pair or entry price) - go for [custom stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss).
Carefully read the documentation to understand what to return - and that it behaves as trailing if you return x% all the time).


i don't see where `custom_exit_price` fits in - to take partial profits, you'll need to use [`adjust_trade_position`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) - otherwise exits will use the full position size.


> Stop-Limit Order for Entry

Stop orders are only supported for exits, not for entries - though you can get similar behavior by combining a regular signal with [trade confirmations](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation).

---

for examples - there's the [strategy repo](https://github.com/freqtrade/freqtrade-strategies/) which has some examples to give ideas - though i doubt you'll find exactly your trading idea - but that's not the point of that repository, anyway.
