### ISSUE TITLE
Quick Telegram visual request

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#11040]
Hi,
```

cat /etc/debian_version
docker exec freqtrade bash -c "python -V"
docker exec freqtrade bash -c "pip freeze | grep ccxt"
docker exec freqtrade bash -c "freqtrade -V"

# cat /etc/debian_version
12.8
docker exec freqtrade bash -c "freqtrade -V"
Python 3.12.7
# docker exec freqtrade bash -c "pip freeze | grep ccxt"
ccxt==4.4.35
# docker exec freqtrade bash -c "freqtrade -V"
freqtrade 2024.11
```

Would it be possible to improve some commands results views to something like this , here an example of status table

![Image](https://github.com/user-attachments/assets/f8466ce3-c45e-4e19-acea-ca4629abd0b5)

Instead of this , status

![Image](https://github.com/user-attachments/assets/ce3bdd5e-a865-46b7-948a-b905f74e9eec)

Which is really hard to read in comparison.

Now that i'm used to read the first it's really hard for me to read the second. In fact, i don't read it.

Especially commands, status, performance, balance, profit status is the worst

Thanks

**Comment by xmatthias** [comment]
I quite honestly don't understand what you're asking. 

One command outputs a table - while the other outputs detail information - which will obviously have a completely different content.
One is for a quick overview - the other for a more detailed list. Obviously it's more difficult to find individual information in a more detailed list - but that's the nature of it.

If you don't need the detail level of information (i don't read it) - then just don't call `/status` ?

**Comment by elestranobaron** [comment]
i talk about the aspect, the grey background and small characters of the first is way better than the second. Presentation is more visual

I talk in terms of css i dont know what you use

**Comment by elestranobaron** [comment]
plus the fact that you can copy in one click in the first and not in the second

**Comment by xmatthias** [comment]
Ah - the first is using a code-block - the 2nd isn't.
we'd lose all formatting options though - so it'll become black and white only.


That's not a "quick" change - but essentially a rewrite of how the output is supposed to look.
That's neither planned, nor do i think that it makes sense for a non-table representation - as it makes the whole thing look like code (monospace font, no highlighting possible, ...).

For tables - we'll stick to the current view (which you seem to like better - i don't) though - as otherwise rendering becomes odd.

**Comment by elestranobaron** [comment]
I think thats separators, font size smaller, and highlighted background, all that makes it more readable

**Comment by elestranobaron** [comment]
You should put these into code blocks honestly

**Comment by xmatthias** [comment]
As mentioned above - that's not  something we plan to spend our time on.
Spam-commenting trying to raise attention will get the issue locked, but won't change how we see this topic.


if you think it's that important - Feel free to invest the time, make a PR. 
Please note: there's no guarantee we'll accept it - and it'll not just need to put it in code blocks, but it'll also have to look better than it does now - which will prove quite difficult as you'll find.


otherwise - please accept that this issue has been closed as "not planned"
