### ISSUE TITLE
 Enable Cross Margin Support for BFUSD as a Dedicated Single Asset in Binance Futures

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#11072]
## Describe your environment
(if applicable)

  * Operating system: __windows__
  * Python Version: __Python 3.12.7___ (`python -V`)
  * CCXT version: ___4.4.35__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.12-dev-6082bf7ee8__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I understand that Cross Margin and Multi-Assets Mode are currently not supported in Freqtrade because the risks and complexities of supporting Cross Margin and multiple assets are significant.
However, I would like to propose a specific scenario that could be an exception: using BFUSD as the sole margin asset in Cross Margin Mode for Binance Futures, because BFUSD offers an annualized yield (around 10–15%) when used as collateral in Binance's ecosystem. This makes it a more appealing choice compared to other stablecoins like USDT. Introduction: https://www.binance.com/en/futures/bfusd .
I also understand that, due to regulations in the EEA, you might face challenges in using BFUSD. That is completely understandable, and I greatly appreciate all the effort and hard work you put into maintaining and improving Freqtrade.

**Comment by xmatthias** [comment]
I don't really see how a single asset class will change the complexities involved in the implementation and support of that.

If using cross futures (to any degree, really) - i don't see why one asset should be favored over another asset - so the support is not a "we don't want to" - but a "we don't care enough to invest the time into". 
I don't really see how BFUSD would change that (and your issue also doesn't really describe that, either) - and support IS a topic - as supporting futures overall has become quite difficult lately due to regulatory hurdles.

in the end, it think this is really a duplicate of #10503 - while the coin there is named "slightly differently" - the underlying requirements are the same, really.

**Comment by 14790897** [comment]
Thanks for explaining. I agree it's not worth prioritizing.
Thanks for your hard work and response!

**Comment by xmatthias** [comment]
Please give #11120 a try - in my testing, it seems to support BFUSD mode just fine.
