### ISSUE TITLE
Change per trade positions with current rate

### ISSUE THREAD

**Issue by Zzzyc0528** [freqtrade/freqtrade#11073]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.12.7 (`python -V`)
  * CCXT version: 4.4.31 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.11-dev-b637e7dd (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

HI,
I want to sell half or a quarter of the initial trade amount for each trade when the current price meets certain conditions. But once I change the initial wallet amount, I get different backtest results. I thought there must be something wrong with the code. The code is wrote based on the documentation's example. But I cannot find more information in the documentation.
I would be really grateful for your help!

``` python
def adjust_trade_position(self, trade: Trade, current_time: datetime,
                            current_rate: float, current_profit: float,
                            min_stake: float | None, max_stake: float,
                            current_entry_rate: float, current_exit_rate: float,
                            current_entry_profit: float, current_exit_profit: float,
                            **kwargs
                            ) -> float | None | tuple[float | None, str | None]:

        dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        width_candle=last_candle["resistance"]-last_candle["support"]
        filled_entries = trade.select_filled_orders(trade.entry_side)
        stake_amount = filled_entries[0].stake_amount_filled 
        trailing_stop = last_candle["resistance"]
        if current_rate >= 1*width_candle+last_candle["resistance"]:
            trailing_stop = 1*width_candle+last_candle["resistance"]

        if current_rate >= 1*width_candle+last_candle["resistance"]:
            return  -0.5* stake_amount
        if  current_rate <0.98*last_candle["resistance"]:
            return  -0.25* stake_amount
```

**Comment by xmatthias** [comment]
> But once I change the initial wallet amount, I get different backtest results. 

well - but why not?
assuming a standard configuration of - say - `max_open_trades=3` and `stake_amount="unlimited"` (which is a pretty standard configuration) - each trade would get 1/3rd of the full balance.

This essentially means - with an dry_run_wallet of 1000$ - your trades will be for 333$ each.
If you increase this to 1500$ - each trade will be 1500/3 - or 500$ each.
With that - your results will also change - simply because you've got more in each trade.

**Comment by MJayden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Freqtrade Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by Zzzyc0528** [comment]
Yes. But the total profit % also changes from 19% to 29%. I thought if I only change the wallet number, the profit rate would not change. Really confuse about that.

**Comment by stash86** [comment]
What was the initial config (stake amount, max open trades, dry run wallet) and what is the new config?

**Comment by Zzzyc0528** [comment]
old:
stake amount: unlimited, 
max open trades: 3,
dry run wallet: 1000

new:
stake amount: unlimited, 
max open trades: 3,
dry run wallet: 10000 or 1000000

every time I change the dry run wallet to a new level, the  total profit % would be different.

**Comment by xmatthias** [comment]
I don't think the information given in this suffice to give you any more information than what we did above.

It's a theoretical discussion up to this point.
I don't see how this function (alone) will cause different results - but this function is not a complete strategy - and other things can influence the values this function gets - which is information that's lacking.

we can have a look at this - but we'll need
* the commands used for backtesting
* actual results / backtesting output
* strategy that causes this - or a minimal reproduction of the same behavior.

Without that - i don't think there's much to add here - mainly because we don't have anything to actually work with and look at ourselfs.
Bugs  / problems in methods like your above can always happen - but it's often difficult to see if you're not able to actually work with it.

**Comment by stash86** [comment]
And please fill in the info asked in the template above.

**Comment by Zzzyc0528** [comment]
After several times practice, I found that when I comment the [adjust_trade_position] function, the result still would be different if I choose different wallet number. 
Below is the whole strategy. I wanna find a way to realize selling some positions when the current price meet some conditions. For example, I set every candle with a resistance price and a support price. When I first go into a trade, like buy one ETH with 3000 USDT(So [stake_amount] defined in the [adjust_trade_position] function=3000 and will not be changed if I don't misunderstand it). Then the price reaches 4000(if 4000 is the resistance price) , then I would like to sell half of the stake_amount(1500) USDT's ETH. In the strategy it will be a little bit complicated but under the same idea.

```python
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these imports ---
import numpy as np
import pandas as pd
from datetime import datetime, timedelta, timezone
from pandas import DataFrame
from typing import Dict, Optional, Union, Tuple

from freqtrade.strategy import (
    IStrategy,
    Trade,
    Order,
    PairLocks,
    informative,  # @informative decorator
    # Hyperopt Parameters
    BooleanParameter,
    CategoricalParameter,
    DecimalParameter,
    IntParameter,
    RealParameter,
    # timeframe helpers
    timeframe_to_minutes,
    timeframe_to_next_date,
    timeframe_to_prev_date,
    # Strategy helper functions
    merge_informative_pair,
    stoploss_from_absolute,
    stoploss_from_open,
)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import pandas_ta as pta
from technical import qtpylib


class AwesomeStrategy_test(IStrategy):
    position_adjustment_enable = True

    INTERFACE_VERSION = 3

    timeframe = "4h" 

    can_short: bool = False


    minimal_roi = {
        "60": 100,
        "30": 100,
        "0": 100
    }


    stoploss = -0.10

    trailing_stop = False
    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    startup_candle_count: int = 40

    # Strategy parameters
    buy_rsi = IntParameter(10, 30, default=20, space="buy")
    sell_rsi = IntParameter(70, 90, default=80, space="sell")# Optional order type mapping.
    order_types = {
        "entry": "limit",
        "exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": False
    }

    # Optional order time in force.
    order_time_in_force = {
        "entry": "GTC",
        "exit": "GTC"
    }
    @property
    def plot_config(self):
        return {
            # Main plot indicators (Moving averages, ...)
            "main_plot": {
                "tema": {},
                "sar": {"color": "white"},
            },
            "subplots": {
                # Subplots - each dict defines one additional plot
                "MACD": {
                    "macd": {"color": "blue"},
                    "macdsignal": {"color": "orange"},
                },
                "RSI": {
                    "rsi": {"color": "red"},
                }
            }
        }

    def informative_pairs(self):

        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
   
        touch_threshold = 0.02  
        n = 40  
        dataframe['resistance'] = 0
        dataframe['support'] = 0
       
        for i in range(n,len(dataframe)):
            window = dataframe['close'][i-n:i]  
            categorized_prices = {}  

            for price in window:
                found = False
                for key in list(categorized_prices.keys()):
                    if abs(price - key) / key <= 0.02:
                        categorized_prices[key] += 1
                        found = True
                if not found:
                    categorized_prices[price] = 1

            frequent_prices = {k: v for k, v in categorized_prices.items() if v > 2}

            if frequent_prices:
                dataframe.loc[i, 'resistance'] = max(frequent_prices.keys())
                dataframe.loc[i, 'support'] = min(frequent_prices.keys())



        dataframe["ema30"] = ta.EMA(dataframe, timeperiod=30)
        dataframe["ema60"] = ta.EMA(dataframe, timeperiod=60)
        dataframe["ema120"] = ta.EMA(dataframe, timeperiod=120)


        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            ( 
              (dataframe['close'] >= dataframe["resistance"]) &
              ((dataframe['ema30'] > dataframe['ema60']) |(dataframe['ema30'] > dataframe['ema120'])) 


            ),
            "enter_long"] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
     
        return dataframe

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                                current_rate: float, current_profit: float,
                                min_stake: float | None, max_stake: float,
                                current_entry_rate: float, current_exit_rate: float,
                                current_entry_profit: float, current_exit_profit: float,
                                **kwargs
                                ) -> float | None | tuple[float | None, str | None]:

            # Obtain pair dataframe (just to show how to access it)
            dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
            last_candle = dataframe.iloc[-1].squeeze()
            width_candle=last_candle["resistance"]-last_candle["support"]
            filled_entries = trade.select_filled_orders(trade.entry_side)
            stake_amount = filled_entries[0].stake_amount_filled 
            trailing_stop = last_candle["resistance"]*0.98
            if current_rate >= 1*width_candle+last_candle["resistance"]:
                trailing_stop = (1*width_candle+last_candle["resistance"])*0.98

            if current_rate >= 1*width_candle+last_candle["resistance"] :
                return  -0.5* stake_amount
            if current_rate <= trailing_stop or current_rate <0.98*last_candle["resistance"]:
                return  -1* stake_amount
        
            
```

the commands used for backtesting:
`docker compose run --rm freqtrade backtesting --strategy AwesomeStrategy_test --timeframe 4h --timerange 20210101-`

First time I set dry_run_wallet= 1000000 I got this:
![Image](https://github.com/user-attachments/assets/b1d26f60-b165-4dbb-9f90-4e035ff5b46a)




Then I set  dry_run_wallet= 1000
![Image](https://github.com/user-attachments/assets/82380af2-95a1-47cd-9739-ad99120ef4bf)



After tried several times, when I comment the [adjust_trade_position] function, the result still would be different. So I guess there is something wrong with the config file.

```

{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "HKD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": { 
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{ 
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "ETH/USDT",
            "SOL/USDT",
            "FTM/USDT"
            // "FIL/USDT",
            // "LTC/USDT"


        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [ 
        {
            "method": "StaticPairList"
            // "method": "VolumePairList",
            // "number_assets": 10,
            // "sort_key": "quoteVolume",
            // "min_value": 0,
            // "refresh_period": 300
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "1",
        "chat_id": "1"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8085,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "**", #you may change here
        "ws_token": "**", ##you may change here
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "****"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}


```

**Comment by Zzzyc0528** [comment]
> And please fill in the info asked in the template above.

Updated. By the way, This is my first time use the "issue" function, I accidentally closed and restarted this issue. I'm sorry if I caused any confusion.

**Comment by xmatthias** [comment]
it's a calculation oddity / rounding error in `order.stake_amount_filled`.
I did 2 tests, one with a 2k balance, one with 100_000 - and the results were indeed different.
Looking at the results, one got a result of the function of `-637.1743999999999` - while `trade.stake_amount is actually `637.1744`.

As this value is used in calculations - this leads to the value beeing slightly too low -once it's trimmed to the actual tradable limits - i got to a trade.amount of 23.99 - and an amount to sell of 23.98 - which means the bot automatically refused the exit as the remaining coin amount of 0.01 LINK (my example trade) would not be sellable.

With a different dry-run balance, the whole calculation changed (as amount is different) - where it didn't run into the floating point error.


if you use `trade.stake_amount` as stake_amount (instead of `filled_entries[0[.stake_amount_filled`) it works without problems. 
Considering the intend of the remaining function, this would even be more correct as you expand your strategy - as only `trade.stake_amount` is actually a full exit - the other is not if you did additional entries.

Now we'll surely improve how `order.stake_amount_filled` is calculated - as it has other usages (even though i still your usage of this is not correct based on the function's intend).


> I found that when I comment the [adjust_trade_position] function, the result still would be different if I choose different wallet number.

this on the other hand - i couldn't reproduce - and results were identical across different balances.
