### ISSUE TITLE
Order Book Data Integration for Advanced Indicators (e.g., Open Interest, CVD)

### ISSUE THREAD

**Issue by dinikon** [freqtrade/freqtrade#11082]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.12
  * CCXT version: 4.4.35
  * Freqtrade Version: freqtrade 2024.12-dev-b1d7d7304
  
## Your question

Dear Freqtrade Developers,

First of all, I would like to express my gratitude for the excellent work you’ve done with Freqtrade. It is a fantastic platform for algorithmic trading, and I deeply appreciate the effort put into its development and maintenance.

I’m reaching out to inquire about a potential feature enhancement: the inclusion of order book data. Many advanced trading strategies rely on analyzing the order book to derive indicators such as Open Interest, Cumulative Volume Delta (CVD), and other metrics that can provide valuable insights into market dynamics.

Currently, it seems Freqtrade primarily focuses on candlestick data. Do you have any plans to integrate order book data into the framework? If not, could you provide some guidance or best practices for implementing this feature independently?

Some specific questions include:

Are there any existing modules or hooks in Freqtrade that could facilitate the integration of real-time order book data?
What would be the best approach to process and store such data for use in strategies without significantly impacting performance?
I believe this addition could open new horizons for strategy development and attract a broader user base interested in advanced trading analytics.

Looking forward to hearing your thoughts!

**Comment by xmatthias** [comment]
>  the inclusion of order book data. Many advanced trading strategies rely on analyzing the order book to derive indicators such as Open Interest, Cumulative Volume Delta (CVD), and other metrics that can provide valuable insights into market dynamics.

I think you're messing up terminology here. Orderbook data will not give you open interest data. an orderbook itself may give you a hint at a price wall (support / resistence) - but it's got essentially nothing to do with actual trades - as it contains no information if any order was actually filled (if a buyer found a seller, ...).
It's a limit order - a (potential) intend to buy - but also with the possibility to be manipulated VERY easily.


You can technically get real time orderbook data via [`dp.orderbook()`](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum).
It's an active network call - and will only get you that particular snapshot in time - and it's not backtestable, either (also because orderbook data is not historically available).


The "actual" things you're talking about sound a bit more like [orderflow data](https://www.freqtrade.io/en/stable/advanced-orderflow/) - which has very little to do with orderbook data - and is based on closed trades.
It's a feature that is available (as experimental feature) - and will probably be closer to what you're actually asking.

> What would be the best approach to process and store such data for use in strategies without significantly impacting performance?

There is none - and we have no plans to work in the direction of real time orderbook integration (see above for an alternative with orderflow).

To get an even remotely accurate picture of orderbook data (movements), you'll need to take snapshots of the orderbook several times a second.
Purely the data infrastructure for this will probably require a team to operate on (we're talking GB's of data per day per pair for this).
The setup requirements for such a thing are not something I'd feel we'll be able to support as part of an open source project aimed at individual traders (often ones that dip their toes into trading for the first time).

As such, you cannot do this without severly impacting performance, and not without having a pretty complex environment to support such things - one that's not supportable in an open source project run by volunteers.

**Comment by dinikon** [comment]
Thank you so much for your detailed response regarding order book and order flow data. The explanation was extremely helpful, and I appreciate the effort you put into clarifying the distinctions between order book data and order flow. It’s clear how powerful the experimental order flow feature is, and it’s already a significant tool for the community to leverage advanced analytics in trading strategies.

I wanted to confirm if I’ve understood correctly: is it possible to calculate indicators like Open Interest (OI) and Cumulative Volume Delta (CVD) using the order flow data? For example:

OI could potentially be derived from total_trades or the sum of bid and ask volumes.
CVD could be calculated using the cumulative sum of delta.
I’d like to ensure I’m interpreting the available data and its usage accurately.

Thank you once again for your dedication to improving Freqtrade, and for providing such invaluable tools for the community.

**Comment by xmatthias** [comment]
I'm not using these tools / indicators - so that's not something i can comment on.
At a glance, it seems likely that for CVD, you can use that.

For Open Interest - i doubt it - as the data doesn't include leverage information - and with that - also no interest data.

I'm however pretty confident that orderbook data (the thing you asked above) is **not** suitable to calculate either of the two - as that represents at max. trade intends - not actually executed trades.

**Comment by lythanh24** [comment]
you can get open interest by call exchange api and merge to dataframe and calculate indicator in your strategy
