### ISSUE TITLE
`No module named 'xdist'` is raised when I try to test the codebase

### ISSUE THREAD

**Issue by daseindev1** [freqtrade/freqtrade#11092]
## Describe your environment

  * Operating system: Debian12 and MacOS Sonoma 14.5
  * Python Version: 3.12.4
  * CCXT version: 4.3.50
  * Freqtrade Version: 2024.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I want to test the codebase with pytest. However an error is raised, and I 

### Steps to reproduce:

(Just following the manual installation steps in the doc)
```shell
# Install ta-lib
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar xvzf ta-lib-0.4.0-src.tar.gz
cd ta-lib
sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
./configure --prefix=/usr/local
make
sudo make install
# On debian based systems (debian, ubuntu, ...) - updating ldconfig might be necessary.
sudo ldconfig  
cd ..
rm -rf ./ta-lib*

# Init python env
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r ./freqtrade/requirements.txt
python3 -m pip install -e ./freqtrade
```

### Observed Results:
![Image](https://github.com/user-attachments/assets/eefbe0bb-e024-48c3-9f3d-99f320542b0e)

### Solutions I tried

`pip install xdist` and `pip install pytest-xdist` doesn't work for me.

Can anyone give me a hint about how to resolve it?

**Comment by xmatthias** [comment]
To run tests - please install the full dependencies via `python3 -m pip install -r ./freqtrade/requirements-dev.txt`.

Otherwise, test-dependencies will not be installed - so i'm already surprised that you've got pytest installed (it's probably not from the virtual environment) - as that's not part of the default dependencies.
xdist is probably the first error - but not the last - as you'll be missing about 10 dependencies if the code above is really the only thing you've installed
