### ISSUE TITLE
Rework DB Table structure

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1109]
When making a trade most of the data added to the trade table is assumed to be correct, pre-populated ,and not what is in the order_id, and some instances does not align with trading reality

Ive done some digging and the unified returns are as depicted. 
Some of these can be directly mapped in the existing trade table fields, others are missing and "fees" drifts from actual. I've  provided an example of fields that can be directly mapped. 

To explain further:
We handle fee's in a odd manner, we add an open_fee and a close_free when an order is made -  its not possible for an order to have an open fee and close fee - an order has only a "fee".  
We cannot know a fee until an order has filled - for a later sale as example we do not know what the  token price will be or how many will be sold:

If imagine a token doubles in price, selling it will inur double fees. 
Or if a user selling only 1/10th their holding the fee will be significantly less. 

- I recommend we drop open fee and close fee and simply use "fee" per order id as comes back from CCXT

Also we're missing fields that can be critical to types of reporting or managing trades later. 
- Recommend recording `side` of the order, to record if the order was buy or sell 
- Recommend recording `type` of the order to report back what type of order was executed. 

We should probably record all the unified fields, `status`, `filled`, `remaining` as they're useful for managing trades. 

<img width="499" alt="screen shot 2018-08-01 at 4 46 42 pm" src="https://user-images.githubusercontent.com/34645187/43535878-9e28fdde-95aa-11e8-86ab-a2a269aec355.png">

Example of mapping existing fields to return values from CCXT
```
            trade = Trade(
                pair=order_id['symbol'],
                stake_amount=order_id['cost'],
                amount=order_id['amount'],
                fee_open=order_id['fee']['cost'],
                fee_close=,
                open_rate=order_id['price'],
                open_rate_requested=order_id['price'],
                open_date=order_id['datetime'],
                exchange=self.exchange.id,
                open_order_id=order_id['id'],
                strategy=self.strategy.get_strategy_name(),
                ticker_interval=constants.TICKER_INTERVAL_MINUTES[self.config['ticker_interval']]
            )
            Trade.session.add(trade)
            Trade.session.flush()
```

**Comment by creslinux** [comment]
Return may be different across many exchanges, ill close this and reopen later once unified fields are better understood

**Comment by creslinux** [comment]
Ive done some research and the unified returns are as depicted. 
Some of these can be directly mapped in the trade table. 

as shown below. 
We have fee's in a odd manner, its not possible for an order to have an open fee and close fee - indeed an order has only a "fee".  We cannot know a fee until an order has filled - as the token price is unknown and the amount unknown. 

If imagine a token doubles in price, selling it will inur double fees. 
Or if a user selling only 1/10th their holding the fee will be significantly less. 

- I recommend we drop open fee and close fee and simply use "fee" per order id as comes back from CCXT
- Also recommend recording "side" of the order, to know if the order was buy or sell 
- Also recommend recording "type" of the order to report back what type of order was executed. 

We should probably record all the unified fields, `status`, `filled`, `remaining` as they're useful for managing trades. 

<img width="499" alt="screen shot 2018-08-01 at 4 46 42 pm" src="https://user-images.githubusercontent.com/34645187/43535878-9e28fdde-95aa-11e8-86ab-a2a269aec355.png">

I 

```
            trade = Trade(
                pair=order_id['symbol'],
                stake_amount=order_id['cost'],
                amount=order_id['amount'],
                fee_open=order_id['fee']['cost'],
                fee_close=,
                open_rate=order_id['price'],
                open_rate_requested=order_id['price'],
                open_date=order_id['datetime'],
                exchange=self.exchange.id,
                open_order_id=order_id['id'],
                strategy=self.strategy.get_strategy_name(),
                ticker_interval=constants.TICKER_INTERVAL_MINUTES[self.config['ticker_interval']]
            )
            Trade.session.add(trade)
            Trade.session.flush()
```

**Comment by xmatthias** [comment]
the database structure is currently based around a "position" (one row is one position) - which is opened (open_fee) - held - and closed (close_fee).

This is mainly due to how the bot was initially designed. i feel it moving further and further away from it, and i think a major overhaul of the persistance layer will be comming, probably following proposed approach.

open_fee is estimated based on default exchange fees when creating the trade.
However, once the buy-order is fullfilled, open_fee (and amount if necessary) is updated to the real value, as this can differ by account on binance.

https://github.com/freqtrade/freqtrade/blob/cfcc2e61e5779dffb9f7d5d49dc1eaa43415cbda/freqtrade/freqtradebot.py#L462-L475


One thing i would like to see here (which would really help speed up this process as we then have a clear design guideline) is the following:

Assume no persistence currently exists, ignore the whole persistence class for now - how would you layout your table(s).

Based on that new DB design, have some query-ideas (not sql or something just "check if this and that" ... ) how to:
* get currently open (which are to check if "should sell")
* get current open position count (a total, not to go over "total-stake")
* get unfilled orders (to check/update once filled)

* get total profit
* get percentage profit 
* get current profit (or loss) - to decide for eventual sell

it's just a concept / design approach - but i think this will lead to a proper design, while currently we are patching / modifying the table with each new feature to somehow fit our needs.


To explain where i'm going with this: 
we see the current table as limiting.
Trying to migrate to a new table trying to keep compatibility somehow for some odd reason may (and probably will) lead to very bad design decisions.
it's a mind-game for now - will however be discussed, maybe improved (maybe the first is ideal already), and probably implemented once agreed unless we have good reasons not to (can't think of one now... but you never know)
