### ISSUE TITLE
Missed Exit Signals (Binance)

### ISSUE THREAD

**Issue by APiercey** [freqtrade/freqtrade#11140]
## Describe your environment

  * Operating system: OS X, M1 Max, Sequoia 15.0
  * Python Version: Python 3.12.7
  * CCXT version: 4.4.42
  * Freqtrade Version: freqtrade 2024.12-dev-5ac95a050
  
## Your question

I noticed a few missed exit signals (which produced considered loses ;)). After inspection, the only "issue" I could find was excessive errors in regards to websockets:

```
ccxt.base.errors.NetworkError: Connection closed by remote server, closing code 1008
2024-12-24 11:00:16,857 - freqtrade.exchange.exchange_ws - ERROR - Exception in continuously_async_watch_ohlcv for <SOME_COIN>/USDT, 5m
```

So my qestion: **Could this cause exit signals to be missed?** If so, I'll be on my merry way! It's hard to diagnose as not _all_ exit signals are missed. If not, I'd love to know how to investigate this better

Some extra info:
- As per docs, I have added `"enable_ws": false` to my `config.json`. I'm observing if this resolves this issue (at least in the logs ;)).
-   FYI, running in Dry-Run mode :)

Merry Christmas and Happy Holidays to you wonderful folks! 🎄🎁 🎅

**Comment by xmatthias** [comment]
1008 is a rate limit error when it comes from the websocket.
This only really happens if you start the bot with tons of pairs/timeframe combinations (including informative pairs)  - in my observation, more than 100, but ratelimits may differ for other IP ranges.

If that error happens, freqtrade will fall back to rest calls, so i don't really see how it can cause problems with missed exits (not if this is the only error, anyway).

The usual, most common cause for missed exit signals is lookahead bias, which can also be happening on only a subset of (exit)signals.
Essentially that means that the signal appears only once a few subsequent candles have been completed.

You can also have too long processing times, but that would show as warning in the logs.
