### ISSUE TITLE
Feature Request: Enhanced Debug Logging with Better Navigation and Styling

### ISSUE THREAD

**Issue by mcpolo99** [freqtrade/freqtrade#11147]
## Describe your environment
(if applicable)

  * Operating system: ____ debain
  * Python Version: _____ Python 3.12.7
  * CCXT version: _____ ccxt==4.4.40
  * Freqtrade Version: ____ 2024.12-dev-0625e1933

## Describe the enhancement

*Explain the enhancement you would like*
I propose improvements to the logging system, primarily to make debugging more efficient and log messages easier to navigate and read. Below are the specific suggestions:

# 1. Enhanced Log Formatting for Navigation

**Current Issue:**
When debugging, it can be challenging to locate the exact source of a log message.

**Proposed Solution:**
Introduce an enhanced log formatter that allows easier navigation in development environments. For example, we could use a format like this:

```
#freqtrade/loggers/__init__.py 

LOGFORMAT = "%(asctime)s | %(filename)s:%(lineno)d:%(funcName)s | %(levelname)s | %(message)s"

```

This format includes:
- **Timestamp (asctime):**  for log traceability. (already present)
- **File name and line number (filename, lineno):**  for direct reference to the source code.
- **Function name (funcName):**  to identify the context of the log message.
- **Log level and message (levelname, message) :** to provide clarity on the log's importance. (already present)

**Benefit:**
In many IDEs or text editors, users can Ctrl+Click on the log line (or equivalent action) and jump directly to the corresponding line in the file, significantly speeding up debugging. (in my opinion)

# 2. Colored Logging for Better CLI Experience

**Current Issue:** (not really a issue but cumbersome)
Log outputs in the CLI can be monotonous and harder to scan quickly.

**Proposed Solution:**
Implement a ColoredFormatter to add color-coded log levels and other components, making logs visually appealing and easier to interpret at a glance. Here is my implementation:
```
#freqtrade/loggers/coloredformatter.py
import logging

from colorama import Fore, Style  # , Back


class ColoredFormatter(logging.Formatter):
    """Custom formatter to add colors to log levels and other parts of the log record."""

    COLOR_MAP = {
        logging.DEBUG: Fore.CYAN,
        logging.INFO: Fore.GREEN,
        logging.WARNING: Fore.RED,
        logging.ERROR: Fore.RED,
        logging.CRITICAL: Fore.MAGENTA + Style.BRIGHT,
    }

    RESET = Style.RESET_ALL

    def format(self, record):
        # Apply color to the log level
        color = self.COLOR_MAP.get(record.levelno, self.RESET)
        record.levelname = f"{color}{record.levelname}{self.RESET}"

        # Apply yellow color to the function name
        if record.funcName:
            record.funcName = f"{Fore.LIGHTYELLOW_EX}{record.funcName}{self.RESET}"
        if record.filename:
            record.filename = f"{Fore.GREEN}{record.filename}{self.RESET}"
        # if record.filename: #does not work for some reason
        #     record.filename = f"{Fore.GREEN}{record.filename}{self.RESET}"
        # if record.asctime: #does not work for some reason
        #     record.asctime = f"{Fore.RED}{record.asctime}{self.RESET}"

        # Apply color to the message itself (optional)
        record.message = f"{Fore.WHITE}{record.getMessage()}{self.RESET}"

        # Apply color to other log fields if desired (e.g., time, filename)
        formatted_log = super().format(record)

        return formatted_log
```
**Benefit:**

Log levels are clearly distinguished using colors (e.g., DEBUG in cyan, INFO in green, WARNING in red).

Critical information such as function names, file names, and messages are visually emphasized.

# 3. Separate Formatters for Handlers when using ColoredFormatter

Current Issue:
Using a single formatter for both file-based logs (e.g., RotatingFileHandler) and console logs (StreamHandler) will lead to the logfiles looking bad and harder to read. (since we have added color formatting to the StreamHandler and a text file cannot interpret color)

Proposed Solution:
Allow configuration of separate formatters for different handlers. For example:

```
#freqtrade/loggers/__init__.py

from freqtrade.loggers.coloredformatter import ColoredFormatter

#using logging.Formatter for RotatingFileHandler
LOG_FILE_FORMAT = logging.Formatter(
    "%(asctime)s | %(filename)s:%(lineno)d:%(funcName)s | %(levelname)s | %(message)s"
)

#using ColoredFormatter for StreamHandler
LOG_STREAM_FORMAT = ColoredFormatter(
    "%(asctime)s | %(filename)s:%(lineno)d:%(funcName)s | %(levelname)s | %(message)s"
)

```

Additional Context:
though i don't know how this would be implemented in a good way for it to work in all cases and with verbosity etc. maybe only activated separately when a debug param is provided when launching freqtrade similar to the verbosity parameter ??

**Comment by mcpolo99** [comment]
this is how i set it up at the moment to isolate my code if it is of any interests, but could be nice to have implemented a more proper solution :D

```
config.json:
    "logfile":"custom:./Logs/",
```




``` python
#freqtrade/loggers/__init__.py
def setup_logging(config: Config) -> None:
if logfile:
        s = logfile.split(":")
...........
elif s[0] == "custom":
            """"""
            import datetime

            from freqtrade.loggers.colorformatter import ColoredFormatter

            LOG_FILE_FORMAT = Formatter(
                "%(asctime)s | %(filename)s:%(lineno)d:%(funcName)s | %(levelname)s | %(message)s"
            )
            LOG_STREAM_FORMAT = ColoredFormatter(
                "%(asctime)s | %(filename)s:%(lineno)d:%(funcName)s | %(levelname)s | %(message)s"
            )

            LOG_DIR = s[1]
            LOG_FILE = LOG_DIR + datetime.datetime.today().strftime("%Y-%m-%d") + ".log"
            # File logger setup
            handler_rf = get_existing_handlers(RotatingFileHandler)
            if handler_rf:
                logging.root.removeHandler(handler_rf)

            try:
                logfile_path = Path(LOG_FILE)
                logfile_path.parent.mkdir(parents=True, exist_ok=True)
                handler_rf = RotatingFileHandler(
                    filename=logfile_path, maxBytes=1024 * 1024 * 10, backupCount=10
                )
            except PermissionError as e:
                logging.error(f"PermissionError: Unable to create log file. {e}")
                return  # Exit gracefully if file can't be created

            handler_rf.setFormatter(LOG_FILE_FORMAT)
            logging.root.addHandler(handler_rf)
            # Console logger setup
            handler_sr = get_existing_handlers(FTStdErrStreamHandler)
            if handler_sr:
                logging.root.removeHandler(handler_sr)

            handler_sr = FTStdErrStreamHandler()
            handler_sr.setFormatter(LOG_STREAM_FORMAT)
            logging.root.addHandler(handler_sr)

            set_loggers(verbosity=0, api_verbosity="info")

```

![Image](https://github.com/user-attachments/assets/3848bc15-7a46-4eb3-87aa-ea21bba984df)
![Image](https://github.com/user-attachments/assets/4bfb7755-0d8a-4232-a33e-c94a17046a12)

**Comment by xmatthias** [comment]
if we look at colored formatting - then the only viable solution in my opinion is rich.

Anything beyond that - you'll struggle with terminal compatibility across platforms - where it's rendering fine on one platform, and will then fail on windows - either when you're using powershell - or when you're not doing that.
We've struggled with this for a long time with colored output - which rich kindof solved.
I'm not going back to doing "colored" formatting manually.

The Rich loghandler however has a hardcoded format - which is (in my opinion) not suitable for freqtrade, and will hide a lot of necessary information.

If you find a solution to this - great - please make a PR (please include screenshots of the logs rendering properly on all platforms we support - which includes linux, mac, windows and docker).

The format you propose is way too noisy however - especially the first one (different color for different levels - sure - but not different color per column!).


---


Adding the line-no seems great at first (if you're debugging it yourself) - but is pointless in 99% of the cases i'm looking at - as most people 
* fail to provide their version - so you have a line number that doesn't actually match the code
* don't use the latest version (not their fault - using stable is fine)

---

Using the file name instead of the actual source is not something we'll be looking for i'd think - as i see it as downside rather than a benefit.
we use `%(name)s` intentionally to have the full path in the logs. We neither look for (nor should we look for) having unique filenames across packages. that's a pointless goal, really - already broken up by python forcing `__init__.py` for each package.

i'd rather see `freqtrade.resolvers.strategy_resolver` rather than `strategy_resolver.py` - especially as it could in reality also be issued by `__init__.py` - in which case your log would show `__init__.py:25` - a file which we have about 100 times in the repository.


Also keep in mint what / who the first reader of the log is - which is the end-user.
Knowing the function name won't really help a user - but will confuse them by having way too much information (this is based on experience). For us looking at the logs afterwards, the log location is either irrelevant (the content counts) - or clear (there's very few places where the same log message is issued in multiple places).
