### ISSUE TITLE
different values open profit freqUI and Telegram

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#11145]
Operating system: Debian GNU/Linux 12 (bookworm)
Python Version: Python 3.11.2
CCXT version: ccxt==4.4.35
Freqtrade Version: freqtrade 2024.11

FreqUI shows a different open profit than Telegram. The values are correct from Telegram.

![Image](https://github.com/user-attachments/assets/425cff71-729c-4d21-80e7-f082880fe24e)
![Image](https://github.com/user-attachments/assets/0278bdf9-fb49-4eea-8eb1-125a78ea2e18)

**Comment by xmatthias** [comment]
well values are slightly offset if that's what you mean (if not, please explain).
but in reality - prices move all the time - so they might use slightly different values as base for their current profit calculation.

**Comment by VerDoe** [comment]
Pleas calculate the individual values in the freqUI screenshot, then you will see that the value is wrong.

**Comment by xmatthias** [comment]
which value? 
there's about 20 values - and i looked at every single trade - each of which aligns within a .05% or so.

**Comment by VerDoe** [comment]
Add up the values in the Current profit column in brackets and you should get the summary of open profit. Telegram shows the correct value, freqUI does not.

**Comment by xmatthias** [comment]
as you seem to not be able to articulate what you're talking about, i'll take some assumption.

there's a difference in what the "open trades" pane shows (current profit)  vs. what bot comparison shows (open Profit).
current profit is the profit that's currently open in each trade. this excludes already realized profits for the open trades.
You can get the "realized" profit in the detail pane for each trade.

open profit (in the bot comparison view) is `current profit + realized profit` - showing the total profit that's still in open trades.
This is intentional - and it's not intended to show the same thing.

It's not wrong - just showing something else.

**Comment by VerDoe** [comment]
Sorry for my English, I would prefer German, but I want everyone to benefit ;-)
Ok, got it. In the freqUI dashboard the open total profit is displayed under open profit and in Telegram the open profit without realized is displayed under total. :)
Merry Christmas and thanks for your explanation!

**Comment by xmatthias** [comment]
I'll probably be adding the "total" (open + realized) profit to the telegram message as well to make this clearer.
