### ISSUE TITLE
Configure SQLAlchemy engine options

### ISSUE THREAD

**Issue by erickaby** [freqtrade/freqtrade#11151]
## Describe the enhancement

While running an instance with a managed postgres service I was getting pooling issues due to how they offer their managed db #11148. I would assume other database providers would also have similar cases to this one. To give more flexibility in db connections, exposing an environment variable/config.json file to configure sqlalchemy options would solve these edge cases for people who have specific db requirements.

example:
```python
engine_options_json = os.environ.get('FREQTRADE__SQLALCHEMY_ENGINE_OPTIONS', '{}')
engine_options = json.loads(engine_options_json)

engine = create_engine('your_database_url_here', **engine_options)
```

```sh
export FREQTRADE__SQLALCHEMY_ENGINE_OPTIONS='{"pool_pre_ping": true, "echo": false}'
```

```json
# config.json
{
  "sqlalchemy_engine_options": {
       "pool_pre_ping": true
   }
}
```

Additionally, not quite in scope of this but is roughly related. It would be great to have a docker build tagged (`freqtrade-pg`?) with the postgres lib `psycopg2-binary` pushed with the `develop` branch ci step to a registry.

**Comment by xmatthias** [comment]
For the moment, i don't really see a need to allow generic, random parameters to sqlalchemy if i'm honest.
Just because a random cloud database thinks they need it - why not use a different provider without such odd limitations?


you can cause tons of bugs by using wrong sqlalchemy engine options (can tell from experience) - and we can't guarantee or test which ones work flawlessly or not - but we'll have to deal with the "fallout" - unexplicable issues due to random, stupidly set parameters.

Often, the code needs to be structured / used in a specific way for specific options (had this before, very painful analysis).

for the 2 options that docs mention - it's unknown / not really explained what the side-effects are (yes, sqlalchemy documentation is lacking in MANY areas - it explains what it does, but not what side-effects it can cause). 
Adding a "ping" before using a pool sounds like it'll add latency - how much, what the timeouts for this are, etc - is howevr not mentioned anywhere (not in the docs, anyway)- so i don't think it's safe to just say "use that and everything will work".


**edit** on a funny side note about neon:
i assume that "compute" counts whenever a query runs ... 
based on their "basic" tier (19$/month) - you'll get 300 compute hours.

Freqtrade will by default query the database every 5 seconds (if a trade is open) - so if you have a strategy is in trades more than 50% of a month - you'll fall out of this tier immediately, making this a rather expensive database.
If you're looking for free cloud databases, there's pretty certainly better options (e.g. supabase - where the free tier should get you a long way with freqtrade - and where i have some experience with - though not in a freqtrade context).



> It would be great to have a docker build tagged (freqtrade-pg?) with the postgres lib psycopg2-binary pushed with the develop branch ci step to a registry.

I don't really see why. It's pretty simple to use a custom docker image.
It'd add even more time to our build time - for very little use (we'd essentially need the same thing for all images - develop-pg, develop-pg-plot, develop-pg-freqai, develop-pg-freqai_rl).
Also - it would favor postgres - so to treat all supported databases equally - where would it stop? mysql? mssql? oracle even? the effort for this for an effectively very small userbase will not be worth it.

**Comment by erickaby** [comment]
Thanks for the feedback, you have raised some great points that I had not considered.

> For the moment, i don't really see a need to allow generic, random parameters to sqlalchemy if i'm honest.
Just because a random cloud database thinks they need it - why not use a different provider without such odd limitations?

>you can cause tons of bugs by using wrong sqlalchemy engine options (can tell from experience) - and we can't guarantee or test which ones work flawlessly or not - but we'll have to deal with the "fallout" - unexplicable issues due to random, stupidly set parameters.

>Often, the code needs to be structured / used in a specific way for specific options (had this before, very painful analysis).

>for the 2 options that docs mention - it's unknown / not really explained what the side-effects are (yes, sqlalchemy documentation is lacking in MANY areas - it explains what it does, but not what side-effects it can cause).
Adding a "ping" before using a pool sounds like it'll add latency - how much, what the timeouts for this are, etc - is howevr not mentioned anywhere (not in the docs, anyway)- so i don't think it's safe to just say "use that and everything will work".

Gotcha, I've had zero experience with sqlalchemy but that doesn't sound fun and had the same question with latency.

> edit on a funny side note about neon:
i assume that "compute" counts whenever a query runs ...
based on their "basic" tier (19$/month) - you'll get 300 compute hours.

> Freqtrade` will by default query the database every 5 seconds (if a trade is open) - so if you have a strategy is in trades more than 50% of a month - you'll fall out of this tier immediately, making this a rather expensive database.

> If you're looking for free cloud databases, there's pretty certainly better options (e.g. supabase - where the free tier should get you a long way with freqtrade - and where i have some experience with - though not in a freqtrade context).

that explains how i hit the free tier quota so quick lol, Ive been messing around trying to come up with a cheap prod setup and have used neon in the past so will most likely be trying out supabase now, cheers

> I don't really see why. It's pretty simple to use a custom docker image.
It'd add even more time to our build time - for very little use (we'd essentially need the same thing for all images - develop-pg, develop-pg-plot, develop-pg-freqai, develop-pg-freqai_rl).
Also - it would favor postgres - so to treat all supported databases equally - where would it stop? mysql? mssql? oracle even? the effort for this for an effectively very small userbase will not be worth it.

no worries, I thought that was the case. I'll just create my own little job to build for develop daily
