### ISSUE TITLE
freqtrade download-data not working correctly on CoinEx

### ISSUE THREAD

**Issue by cinorid** [freqtrade/freqtrade#11168]
## Describe your environment

  * Operating system: Windows 11 x64 docker desktop
  * Freqtrade Version: freqtrade 2024.10 running in docker
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. run command `docker compose run --rm freqtrade download-data --days 700 -t 5m`
  2. the logs show that downloading a bunch of data started.
  3. after that run `docker compose run --rm freqtrade list-data --show`

  ### Observed Results:

  * When the download started it showed this log:
  > 2024-12-31 13:28:31,952 - freqtrade.data.history.history_utils - INFO - Download history data for "BTC/USDT", 5m, spot and store in /freqtrade/user_data/data/coinex. From 2023-01-31T00:00:00 to now
2024-12-31 13:28:43,198 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 201720.
  * when I run run `list-data` command it displays this:

>
Pair         Timeframe        Type       From          To        Candles
BTC/USDT   5m  spot   2024-12-29 16:10:00  2024-12-31 09:40:00     499

It seems it downloads full data but always saves only 499 candles.
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
If you run freqtrade with `-vvv` - you'll see that all requests use the following query:

```
2024-12-31 11:51:40,221 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT, spot interval 5m...                             
2024-12-31 11:51:40,223 - ccxt.base.exchange - DEBUG - GET https://api.coinex.com/v2/spot/kline?market=BTCUSDT&period=5min&limit=500,
```

Implicitly, this means that pagination won't work - as no "since" or whatever other parameter is passed in.

Freqtrade is using ccxt for this - with the following parameters:
```
fetch_ohlcv(
                    pair, timeframe=timeframe, since=since_ms, limit=candle_limit, params=params
                )
```

Quite apparently, ccxt is ignoring the "since" parameter.

Unfortunately, we don't have the bandwidth to support all exchanges and try to have them fixed / workable.
As this is an unsupported exchange - it's up to you to reproduce this indepenent of freqtrade - and then report it to ccxt.

it's obviously welcome to report back here once it's been fixed.


As you're probably the first to use this exchange, expect future problems down the road (if this is already wrong) - so if you're not familiar / comfortable with debugging issues in python - i'd strongly advise to not use coinex.

In that case, please use one of the supported exchanges, which are the ones we know are working..
