### ISSUE TITLE
huobipro backtesting WARNING

### ISSUE THREAD

**Issue by ynzheng** [freqtrade/freqtrade#1223]
## Step 1: Have you search for this issue before posting it?
yes

## Step 2: Describe your environment

  * Python Version: Python 3.7.0
  * CCXT version: ccxt==1.17.311
  * Branch:  Develop
  * Last Commit ID: eaa657aa3b9f9074dba6a57e2b698ff6ea11a344
  
## Step 3: Describe the problem:

when i run the following command on debian 9:
(.env) yn@host:~/freqtrade/bot$ python3 freqtrade/main.py --verbose backtesting

I got these:
2018-09-19 17:54:59,900 - freqtrade.exchange - INFO - downloaded ETH/USDT with length 360314.
2018-09-19 17:54:59,907 - freqtrade.optimize - DEBUG - New Start: 2018-09-16T06:25:00
2018-09-19 17:54:59,907 - freqtrade.optimize - DEBUG - New End: 2018-09-19T17:50:00
2018-09-19 17:55:02,671 - freqtrade.optimize - DEBUG - Loading ticker data from file user_data/data/huobipro/ETH_USDT-5m.json
2018-09-19 17:55:03,297 - freqtrade.optimize - WARNING - No data for pair: "ETH/USDT", Interval: 5m. Use --refresh-pairs-cached to download the data
2018-09-19 17:55:03,298 - freqtrade.optimize.backtesting - CRITICAL - No data found. Terminating.
2018-09-19 17:55:03,298 - freqtrade.exchange - DEBUG - Exchange object destroyed, closing async loop

### Steps to reproduce:

  1. change the config.json to :
-----------
       "dry_run": true,
        "pair_whitelist": [
            "ETH/USDT"
        ],
       "refresh_pairs": true,
-----------
  2. run the latest freqtrade code
  3. 23M huobipro data downloaded  @
  user_data/data/huobipro/ETH_USDT-5m.json

but no backtesting process

binance works

**Comment by ynzheng** [comment]
thanks first of all

it seems that 

1.Backtesting huobipro does work only with "./bin/freqtrade"

2.not work with " ./freqtrade/main.py“ :

python3 ./freqtrade/main.py  --verbose  backtesting

just let you know these.

closed

**Comment by xmatthias** [comment]
Let me followup on this as on slack others saw a similar issue:

This is nothing to do with freqtrade - but with how long the exchange gives you data for a specific period of time.

most exchanges hold short-term data only for a relatively short amount of time (mostly counted in ticks). this means, 5m data may be awailable for the last 3 days - while hourly or daily data may go back a while.

Some exchanges form an exception to this (e.g. binance - which has minutely data since january - i didn't go back further...). 
CCXT outlines this nicely in their [docs](https://ccxt.readthedocs.io/en/latest/manual.html#ohlcv-candlestick-charts)
> There’s a limit on how far back in time your requests can go. Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka REST polling) latest OHLCVs and storing them in a CSV file or in a database.

Below is a very simple code sample demonstrating the things above.
For huobpro, only ~3 days of data is awailable.


``` python
import ccxt
import arrow
ct = ccxt.huobipro()
mark = ct.loadMarkets()

pair = "ETH/USDT"
date = arrow.now().shift(days=-10)

print(f'submitted start-date: \t{date.datetime}')

ohlcv = ct.fetch_ohlcv(pair, timeframe='5m', limit=1000, since=int(date.datetime.timestamp()) * 1000)


print(f'From: \t\t\t{arrow.get(ohlcv[0][0] / 1000)}')
print(f'From: \t\t\t{arrow.get(ohlcv[-1][0] / 1000)}')


```
### Output:
``` 
submitted start-date: 	2018-09-10 19:38:56.685284+02:00
From: 			2018-09-17T06:20:00+00:00
From: 			2018-09-20T17:35:00+00:00
```

nothing freqtrade can do about this - sorry - best try to contact the exchanges - but chances are slim to none to get them to change their endpoint strategy
