### ISSUE TITLE
Plotting: Indicators should be defined in Strategy

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#1531]
I think we should have plot indicators details defined directly in Strategy file. That way the user can define more specific plot configuration for each strategy.

Features:

- Dynamic Row / Subplot number
- User defined indicators color
- Possibility to show Strategy related indicators on upcoming plotting web ui #1505 

Below the variable proposition:

    # Optional plot informations
    plot_rows = [
        'main_plot':[
            {'name': 'ema10', 'color': 'red'}
        ],
        'sub_plots':[
            [
                {'name': 'macd', 'color': 'blue'},
                {'name': 'macdsignal', 'color': 'red'}
            ],
            [
                {'name': 'rsi', 'color': 'orange'}
            ],
        ]
    ]

**Comment by xmatthias** [comment]
as long as it's kept optional (so strategies not defining this will still work also for the UI) I guess that's fine, even though it'll clutter the strategy quite a bit for huge strategies.

I would keep color optional since the color is not that important.
maybe consider a "type" section - defaulting to Line but allowing to specify histograms or so ... ? (not sure if that makes sense, but i'm thinking about MACD histogram ...)

you could also use `dataframe.columns` coming out of `populate_indicators` to create a list of possible indicators users can select in the UI if this is not defined?

And once selected it generates this list ... so users can copy/paste it to the Strategy? (i know, i'm lazy) ...

**Comment by Axel-CH** [comment]
I'm agree with you about:
- This parameter should be optionnal
- Color is optional
- Add type, default to line

However for the automatic generetion of those parameter from the UI, I don't see a suffisent gain versus time allowed to develop that feature.

The added value of being able to choose indicators in the UI is to make a quick visual observation. 
I see two limitations factor here:
- the availables indicators should be already present in dataframe, defined in Stategy
- It's really difficult to use dash for theese kind of dynamic plot edition (should reload entire plot at each indicators modification). More details here: https://dash.plot.ly/faqs

**Comment by xmatthias** [comment]
i said "you could" - this makes it a "would be nice to have ..." 
one can dream ... no?
