### ISSUE TITLE
unexpose exchange api key

### ISSUE THREAD

**Issue by TheRinger** [freqtrade/freqtrade#1556]
There needs to be a method for importing exchange api & secret that is separate from the config.json or any other config-example.json file. 
A method that separates the config.json and the trusted exchange api would be helpful for security purposes especially when sharing strategies and having multiple configurations.
It would be useful if the method allowed for the use of environmental variables to pull the api & secret allowing the api keys to be environment specific. 
example in linux ~/.profile or ~/.bashrc 
binance_api_key='<exampleapikeyher>'
binance_api_secret='<exampleapisecret>'
kraken_api_secret='' 
etc
the config could pull $binance_api & $binance_secret and a copy of the api would never exist in the freqtrade directory.
If there is already a method that exists to do this, I apologize for submitting this issue.

**Comment by xmatthias** [comment]
This is currently not possible, but implementing should be fairly simple.
However, I would not make the variables exchange-specific, but rather use `ftexchangekey` / `ftexchangesecret` or something like that.

You can then store them in "some" arbitrary, exchange specific file and use `. binancekeys` or `source binancekeys.whatever` to load them to your environment.

I would STRONGLY recommend against setting them in `~/.bashrc` or `~/.profile` since that makes the keys available to all processes running under your user, including chrome, firefox, and whatever else is running.

**Comment by hroff-1902** [comment]
@TheRinger, #1571

**Comment by xmatthias** [comment]
@TheRinger would #1571 fix your issue?

the idea is that you have your configurations in one file - and the keys in another configuration file. you can specify an absolute path so the file can reside wherever you'd like it to be.

**Comment by hroff-1902** [comment]
@TheRinger, I added some description for this new feature, see at https://github.com/freqtrade/freqtrade/blob/develop/docs/bot-usage.md#how-to-use-multiple-configuration-files

**Comment by xmatthias** [comment]
I think #1571 should address this sufficently. 
Feel free to reopen if you think differently.

**Comment by TheRinger** [comment]
Apologize I haven't had much time , I will look at it as soon as I can.

**Comment by hroff-1902** [comment]
> Apologize I haven't had much time , I will look at it as soon as I can.

I have not added yet to the configuration.md examples of 2 configuration files with the exchange keys in a separate conf. file...

bot-usage.md contains description of the command line option and its usage.

**Comment by TheRinger** [comment]
I really like this new way of parsing the config for an api , I did
discover how to pull them in easily with a bath script, but doing it like
this does seems more much cleaner.
  Does multiple configs allow for separate currencies pairs in the same
runtime? What about separate exchanges running parallel? Your changes to
the descriptions really make a big difference in getting over the learning
curve, there isn't a ton of depth to current the documentation. I spent a
lot of time building scripts to shorten most of the command line arguments.

**Comment by xmatthias** [comment]
most command line arguments can be specified in the config as well.

the multiple configurations are combined into one - so after loading the config, nothing changes beyond that point.

it is however easy to run multiple bots with different stake-currencies ... that's currently the only way - and I'm not keen on supporting more since the complexity raises a LOT with that, while it can be accomplished easily by running 2 bots side by side.
