### ISSUE TITLE
Problems in backtest with trailing_stop

### ISSUE THREAD

**Issue by gianlup** [freqtrade/freqtrade#1575]
## Step 1: Have you search for this issue before posting it?
Yes
  
## Step 3: Describe the problem:

While using the bot I've noted some differences from backtest and dry run. I think there are 2 problems in backtest with `trailing_stop:true`:

- at this line https://github.com/freqtrade/freqtrade/blob/788cbb67767cfe7bc8b7166d17ef59e4a94cd85a/freqtrade/strategy/interface.py#L334 should be used the **high** of candle instead of low
- in the same function the trailing stop loss should be adjusted **before** checking if it was reached

Maybe related to #746.

### Steps to reproduce:

  1. backtest with trailing stop active
  
### Observed Results:

  * trades count and timestamp in backtest are not comparable to dry_run
  * trades count and timestamp in backtest should be comparable to dry_run

**Comment by xmatthias** [comment]
you are right, kind of ...

The problem with this function is that it's *primary* function is to deal / update stoploss.
This requires low to be passed in, since we assume low is before high -> protect capital first - which is correct in case of stoploss.

For trailing stoploss it's different, since that assumes "current price" and evaluates if that was higher than the `previous measured maximum - trailing stoploss`.

simply passing in high to the above function will not work, as that would break stoploss.
It's best explained in pictures (not good ones but i think they show what i mean)
Assume the following scenario - you buy on the open of the first green candle.

![open_candles](https://user-images.githubusercontent.com/5024695/53115122-aba14800-3545-11e9-93f3-3d373a50a9ac.png)

The long low would shake you out on your stoploss - but by using high in that function that would never be cought during backtest, since `trade.stoploss` is never lower than the open or close.

we may need to pass both high/low into that function and handle that there - or split the function up somehow ... 
however it's unfortunately not as simple as using high instead of low.

Currently stoploss / trailing stoploss remains lower in backtest than in dry-run ... which is kind of intentional - since it protects value over profit in lack of more information.

**Comment by gianlup** [comment]
Yes you are right, but my intent wasn't to replace entirely low with high. Like you said we should find a smart way to pass also the high value in order to handle both cases.

I really appreciate the detailed response though.

What do you think about the second point?

**Comment by xmatthias** [comment]
While writing the above I ran out of time and forgot about the second point sorry.

I'll however need some time to think about it ...

**Comment by xmatthias** [comment]
Have been thinking about this for a while now (and relooking at the code multiple times).

Since we only move stoploss up (never down) - and "prefer" low over high during backtesting (protect assets first) - I don't think it'll matter.

we have 2 (releevant, 3 in total) cases with trailing stoploss:
* either low is below stoploss
* or high is higher than the previous high
* (high and low is somewhere between stoploss and max_high)

In the first case, we sell no matter what.
in the 2nd case - we adjust stoploss - but it's not relevant until the next iteration (we evaluated low already)
(in the 3rd case, nothing matters since stoploss is not adjusted, and we don't sell.)

Maybe i miss something ... but that's what i came up after looking at this multiple times ...

**Comment by gianlup** [comment]
>In the first case, we sell no matter what.

yes - in backtest _low_ is passed to `stop_loss_reached()` and it sells if `trade.stop_loss >= current_rate`

>in the 2nd case - we adjust stoploss - but it's not relevant until the next iteration (we evaluated low already)

I think the problem is here. After the last candle close stoploss should be adjusted using _high_ because it is the highest price that has reached (in the last candle) and only after that it should check if the stoploss has been hit.

My propose isn't to replace `current_rate` in `stop_loss_reached()` with _high_ everywhere, but only change it in `trade.adjust_stop_loss(current_rate, stop_loss_value)`.

An example - stoploss=10%, every step is a candle close
- buy signal @ 100 -> sl=90
...
- L=95 H=105 -> actually the stop loss is adjusted with L (85.5) - so no change. Instead should be adjusted with H (94.5)
...
- L=93 H=101 -> the trade should be closed because 94.5>=93, but the stop loss is still 90 so nothing happens. **Problem 1**
...
- L=91 H=104 -> the bot should adjust stoploss to H (93.6) and after close the position because 93.6>=91. Instead it does nothing because it checks before the stop loss 90 ! >=91 and only then adjusts it. **Problem 2**

These 2 problems mixed can cause a substantial difference between backtest and dry run/live with trailing stoploss.

**Comment by xmatthias** [comment]
I absolutely agree on problem 1. This should definitely be adjusted using high.

Problem 2 - I'm not certain. Yes, it's potentially a problem. However
We take the assumption that low always happens before high -> close a trade rather than do ROI if both stoploss and ROI would apply.
Your solution (to adjust before checking stoploss) would change this assumption for just this part of the code. 

I'm not 100% clear on the implications of this yet ... 

Anyway thanks for the very detailed description of the problem you see.

**Comment by xmatthias** [comment]
@gianlup when you have time - please have a look at #1673 - it should solve problem1 ... 

not sure about problem 2 (read previous comment).

**Comment by gianlup** [comment]
I've just looked to the PR and it's looks good, that's just what I had in mind. This evening I will try from home PC.

Regarding problem 2:
>after looking at the code, it would have no impact on real mode - since stoploss is only moved up, never down.

Exactly, in fact I think it's only a small logical issue. The execution order (both live and backtest) should be `new candle > adjust SL > check SL > check ROI > check SELL` instead of `new candle > check SL > adjust SL > check ROI > check SELL`.

In live mode it doesn't make any difference (just a few seconds of delay), but in backtest the problem can be bigger as we do not have ticker data (we only rely on candle OHLC) and so we can potentially miss a sell.

**Comment by xmatthias** [comment]
Your proposal - even though it's assuming high was before low - protects assets better than the current approach. 
It'll negatively impact most trailing stop strategies backtests - but align it to real live better (on a more conservative manner).

Great spot! :+1:

**Comment by xmatthias** [comment]
#1673 should address this fully.

feel free to reopen if it does not.
