### ISSUE TITLE
Documentation should include latest / stable versions (older versions should be accessible)

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1619]
As I see, in the meantime, the pages on the freqtrade.io site are generated from (or simply copied/used as is) the develop branch.

The proposal is to use versions of the .md pages from the master branch instead. Because, especially when new features are actively added into develop, the documentation in develop may significantly contradict with features in the 'stable' master branch and releases. Which may be painful for a new user which is not familiar with internals of the project development procedures and simply want to use the current 'stable' release.

**Comment by xmatthias** [comment]
technically there are:
https://www.freqtrade.io/en/master/bot-usage/
https://www.freqtrade.io/en/latest/bot-usage/#how-to-use-multiple-configuration-files

(note the multiple configuration files is different in the "master" version).

I could not find a link to switch between the 2 versions though ... but that could be theme-related... (@mishaker ?)

**Comment by mishaker** [comment]
The default branch on FT is develop (this is explicitly mentioned). So I don't think the documentation should point to the master. 
That being said and maybe off topic: I am with you on pointing to a stable version. I think at some point we have to change the process, releasing stables more often and switching docs to the master. But that is beyond documentation. if we change the process, documentation will follow. 

@xmatthias I think it is possible to add versions on the header ... I am just not sure if it is worth it for now with our current stable release process.

**Comment by xmatthias** [comment]
> with our current stable release process.

there is a documentation for stable releases, and creating a release takes ~5 minutes...

I don't see any benefit of frequent releases, unless we are able to install from pypi (which we currently can't - because of #1384). If users need to clone the repository anyway, most will stick to develop...

Ideally, on a bigger merge, we would have the documentation included before merging to develop - and I've tried to keep that followed (mostly).

No matter how the release-process is - we should also have the documentation for "older" versions available.
If, for whatever reason, I want to stick to version 16.1 (did that version exist?) , I currently have no way to get documentation (apart from within the checked out branch).

**Comment by mishaker** [comment]
Ok, let me find a way to include versions in the theme ...

**Comment by hroff-1902** [comment]
> If, for whatever reason, I want to stick to version 16.1 (did that version exist?) , I currently have no way to get documentation (apart from within the checked out branch).

At least for the latest 'master' stable release. So that an ordinal user could refer to the docs that corresponds to it. Developers will always find last unstable docs from develop. ;-)

Sorry if I initiated big changes to the site structure and the project development process.

**Comment by xmatthias** [comment]
Don't feel sorry to have us question ourselfs - that's a good thing 👍

**Comment by iuvbio** [comment]
I think this makes a lot of sense.. as @mishaker says the default is develop and that is mentioned, but imho it would indeed be better to have master (or whatever stable branch) as default.. the develop branch is frequently changing, which is a good thing, but also increases risk

**Comment by xmatthias** [comment]
As pointed out in the [mkdocs documentation](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/deploying-your-docs.md#read-the-docs):

> To benefit from all of the [features] offered by Read the Docs, you will need
to use the [Read the Docs theme][theme] which ships with MkDocs. The various
themes which may be referenced in Read the Docs' documentation are Sphinx
specific themes and will not work with MkDocs.

I've now been able to allow showing different versions on readthedocs - but it's in the "rtd" style, and changing that style does not seem to be easily possible, since all elements are injected by readthedocs.

Currently, the "latest" version points to that branch, so you can check this out [here](https://www.freqtrade.io/en/latest/) - bottom right.

I can revert this with one click ... if this is OK i'll cleanup that branch and make it "mergable".

**Comment by hroff-1902** [comment]
Great, how did you do this? I've read recently somewhere that this is currently impossible for the Material design used as the theme...

Is it possible to inject the switch in the older versions?

The switch element may be made a bit bigger (or its size scaled better), it's too small in 1280x720 screen, for example...

**Comment by xmatthias** [comment]
well the fix is really a one-liner - it's jquery that is missing in material design, and required by RTD to inject this tag.
Now styling this is a different issue i'm still fighting with...


I don't think we can (or should) inject it into the older versions since these are Tags - and i don't intend to forcepush tags (or something else i know others use) as that can mess up a cloned repository ...
been there - i know how to fix that state now - but i don't intend to explain it to git-beginners ...

**Comment by hroff-1902** [comment]
agree, we should not move old tags, I meant if this can be injected at the site-wide (readthedocs) level -- old versions are tags in git, but they are the dirs at readthedocs, so site-wide change could be applicable at them as well somehow...
If it's impossible, right -- no tags should be changed...

**Comment by xmatthias** [comment]
I know, i was thinking about the same, but it doesn't seem possible.

it's folders once it's built - but we don't have access to these folders directly.

Readthedocs is coupled with the repository - so each tag needs to be "built" - which results in then the folder shown. we cannot ssh into it and change it as we'd like...
