### ISSUE TITLE
Combine exchange.validate_pairs and ipairlist._validate_whitelist

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1622]
As far as I see it, `exchange.validate_pairs` and `ipairlist._validate_whitelist`basically do the same thing, only that the check in the pairlist is more extensive. As the pairlist is validated every round anyways via `refresh_pairlist` this seems unnecessary. Should we scrap `exchange.validate_pairs` or combine the two?

**Comment by hroff-1902** [comment]
I like the approach implemented in `ipairlist._validate_whitelist` since it compares actual data that came from the exchange (the `quote` element comparing to the stake_currency). It much better (more robust) than getting the second part of the pairname like in `exchange.validate_pairs`. However, on some exchanges there may be instruments, where staking is performed in units if base currency. This approach won't work for them, I will try to find examples...

**Comment by iuvbio** [comment]
Hey @hroff-1902 did you find any examples? You mean for instruments such as Futures and the like, right?

You're right, using the quote is more robust, but I think it's fine to use the quote part of the pair name though, because we also check whether the pair is active in markets. If the pair is misspelled or something, it still won't make it to the whitelist, because it cannot be found in markets.

**Comment by hroff-1902** [comment]
Thanks for the reminder, I've almost completely forgotten of this, sorry...

Not only Futures. Look at the ccxt's issue I posted: https://github.com/ccxt/ccxt/issues/4678

I mentioned there the following pairs (on bitmex):

* XBTUSD (BTC/USD), most active: orders are created in USD, price is in USD (so USD is a quote currency while BTC(XBT) is a base currency, staking in USD
* ETHUSD -- price in USD, orders in USD -- same;
* ETHBTC -- price in BTC, orders in ETH, -- staking in the base currency,

More exchanges with similar anomalies can found in the ccxt since it influences the ['limits']['cost'] and ['limits']['amount'] in the market structure returned by ccxt, as you can see from that issue...

**Comment by iuvbio** [comment]
No worries ;) As far as I can see, that's more related to `amount` and `cost` isn't it? You're saying that in the case of ETHBTC from you example `quote` would be ETH not BTC? Then that would indeed be a problem.. In any case, I'll use the 2nd part of pair name then to avoid any issues.

**Comment by hroff-1902** [comment]
Pairs in the ccxt output structures can also be reversed, i.e. with the base currency in the second place in the name (there should be a marker somewhere in the market data structure, do not remember the exact name of a field); staking, as you can see, can be in both quote and base currency...

**Comment by hroff-1902** [comment]
Should be closed since resolved in the merged PR?

**Comment by xmatthias** [comment]
I thought the same - but the PR has the following comment (and both functions are still there):

>  haven't removed exchange.validate_pairs yet, as I'd like to get your input.. As I wrote in #1622, that check is basically unnecessary, since the whitelist gets validated by ipairlist anyways.. However, it's only executed once when the exchange is initialised. So not too much damage and the whitelist gets validated earlier. Could also import _validate_whitelist and call it there, but that seems like overkill.. imo, it's probably fine to take it out. What do you think?

Maybe we can close it anyway as it's true - the function in the exchange class is only called on initialization, never again after that.

**Comment by iuvbio** [comment]
Since there was no clear preference for removing it, I've left it in. I think it doesn't do any harm, we can still remove it at a later point, if wanted. I'll close this one for now.
