### ISSUE TITLE
Telegram command for showing current whitelist (for vol pairlist) and add pair to blacklist

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1625]
As the title says, I think it would be good to have a Telegram command that displays the current whitelist (mainly useful if using the VolumePairList) and one that enables adding a pair to the blacklist.

**Comment by xmatthias** [comment]
we do have such a thing for whitelist: https://github.com/freqtrade/freqtrade/blob/ca64d8a8611d940547d3cff16bb0a98c158cc8c6/freqtrade/rpc/telegram.py#L444-L458

it's visible when you run `/help`.

I just noticed that it's missing from the documentation page ... 

add to blacklist does not exist - but that's more difficult since a restart of the bot would clear that list, unless we write to documentation (which i would not wanna do)...

**Comment by iuvbio** [comment]
Didn't know that, works great, thanks!

For me personally, it would be fine if the blacklist is reset on restart. It's more for a temporary fix while on the road, later it can be added in the config.

**Comment by xmatthias** [comment]
`/blacklist` feature was added in #1697 - `/whitelist` did already exist...
