### ISSUE TITLE
Automatically update database after forcesell

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1628]
Pretty self-explanatory again, I believe. It's really annoying having to update the db manually after a forcesell.

**Comment by xmatthias** [comment]
using `/forcesell` does update the database.
There is a slight bug/race condition which causes the bot to see it one iteration too late eventually ...but the database is definitely updated.

the only thing that's not detected is if you sell it directly on the exchange - but that's difficult to detect tbh, since it's not tied to an order or similar.

**Comment by xmatthias** [comment]
Since i like to back my claims up by code...: 

https://github.com/freqtrade/freqtrade/blob/045de94b49dbf07f51a3272c38f80f52f41f9b93/freqtrade/rpc/rpc.py#L366-L385

**Comment by iuvbio** [comment]
Oh damn, sorry about that.. I might have been too fast. Had to update it before, but not sure whether I also didn't wait back then. Going to close this one then :+1:
