### ISSUE TITLE
Treat sandboxed exchange and its main one separately

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1630]
On many (? at least some) exchanges that have a 'sandboxed' variant, they are implemented as separate exchanges, with their own trades, positions, orders, orderbooks, prices, volumes.

I see two points to resolve;

* Introduce the 'sandbox' field into the trades table. Since the list of trades made on sandboxed version of exchange may (and often does) differ from main exchange.
* Keep loaded historical data for main exchange and sandboxed one separately. Now at least for the Edge module the loaded historical data are stored without distinction if they correspond to sandboxed exchange.

* ?? May be in some more aspects the main exchange and its sandbox should be treated separately.

**Comment by xmatthias** [comment]
The only exchange I know having a sandbox (implemented in ccxt) is gdax ...

However, that has that low volumes that you would never want to backtest on it, since the BTC price jumps around at will, and nothing working there will work on a real exchange (that's my experience with GDAX, anyway).

For database - you can simply use a different database file for this usecase ... and you need to change the configuration for sanbox anyway, so add a "sandbox" to the filename and you're good ;) 

I'm not strictly refusing the idea, but I'm not sure the sandbox-usecase justifies the effort it would require to really, properly seperate the real from the sandbox.

**Comment by hroff-1902** [comment]
> The only exchange I know having a sandbox (implemented in ccxt) is gdax ...

BitMEX (yeah, as always):
Main: https://www.bitmex.com/app/trade/XBTUSD
Sandbox: https://testnet.bitmex.com/app/trade/XBTUSD

Completely different ohlcv data (historical data kept by the Edge betwen runs when running the edge command), orderbooks, different orders (trades in terms used in the bot) if you are logged in...

**Comment by xmatthias** [comment]
yes, I am sure they are different / completely separate - that's how a sandbox exchange should be.

But to me, the above points can be taken care off by using `--datadir user_data/data/sandbox_bitmex/` and `--db-url sqlite:///sandbox.sqlite` ...

(both can be set in the configuration ... and as mentioned above, you'll need to change the configuration anyway to point it to the sandbox ...)

**Comment by hroff-1902** [comment]
> For database - you can simply use a different database file for this usecase ... and you need to change the configuration for sanbox anyway, so add a "sandbox" to the filename and you're good ;)

Well, one could use different database files when changing the exchange name in the config with the same success, why do you have the exchange field in the database?

All this is a source of errorneous trades for an ordinal user... When the bot will simply use data from sandbox thinking they correspond to the current, non-sandbox exchange, instead of loading correct data using actual current configuration...

**Comment by hroff-1902** [comment]
And yes, seems to be quite hard to implement, to select all the points where the sandbox should be separated, indeed,,,

Mark as Enhancement, leave open for the future, for (non-nearest) future refactoring iterations?

**Comment by xmatthias** [comment]
Honestly, I see this more as a documentation issue more than an enhancement ...

using the double configuration (which i come to like more and more!), you could have a config specifying the "sandbox" settings (other datadir, other database, other exchange config) - and load that last  so you have a "simple" way to archive what you request above ;)

**Comment by hroff-1902** [comment]
Yes, but see a simple scenario:

A trader uses config with sandbox exchange, runs edge via command. The historical data are fetched from sandbox and kept by edge module. It then decides to switch to main exchange, runs the bot and after some time decides to verify the stoploss by running the edge command. He will receive receive results either same, based on sandbox data, or strange results based partly on sandbox data, partly on new data from main exchange. And nowhere in the log you'll find any notification about this... What to do in this case? Refresh historical data? And do not forger to do it in the proper moment of time... But what if I work with sandbox and main exchange simultaneously? Refresh data every time I run edge? And receive finally ban from the exchange because of API limits, right? Use different data directories for keeping two sets of historical data? TOO complicated for a simple task like changing the sandbox boolean in the config... TOO complicated for a user...

Another point: you run the bot live on sandbox, then stop it, leaving some trades (positions) open, then switch to the main exchange. Am I right thinking that upon second start the bot will show you those trades and will even tries to sell them if the strategy tell this?

Yes, all this can be described in the documentation, but this is a potential source for strange errors in trades, as I see. And you'll never find it from the log...

Minimal ToDo: enhance documentation, describing how to switch between sandbox, main exchange and vise versa *properly*.
Further ToDo: implement the separation of sandbox and main exchange in the persistence data.

**Comment by xmatthias** [comment]
I agree on the minimal ToDo to enhance documentation.

The 2nd part can be accomplished by using a "sandbox.config" as a last configuration - which reconfigures data-dir and database, without tons of code to support sandbox which is supported by only 2 exchanges.

You can try to pre/postfix the `exchange.name` property - that'll take care of persistence, HOWEVER, switching exchange with the same database is not supported at all (if there are open trades), since no (or almost no) query uses exchange as a filter, and I'm not keen on supporting that as I think it'll lead to tons of problems.
