### ISSUE TITLE
Implement all available Kraken order types

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1687]
I've been running FT on Kraken stably since it was implemented now, so I think it's time to implement some more functionality.

As per the [docs](https://www.kraken.com/features/api#private-user-trading) the following order types are available:

- [x] market
- [x] limit (price = limit price)
- [x] stop-loss (price = stop loss price)
- [ ] take-profit (price = take profit price)
- [ ] stop-loss-profit (price = stop loss price, price2 = take profit price)
- [ ] stop-loss-profit-limit (price = stop loss price, price2 = take profit price)
- [ ] stop-loss-limit (price = stop loss trigger price, price2 = triggered limit price)
- [ ] take-profit-limit (price = take profit trigger price, price2 = triggered limit price)
- [ ] trailing-stop (price = trailing stop offset)
- [ ] trailing-stop-limit (price = trailing stop offset, price2 = triggered limit offset)
- [ ] stop-loss-and-limit (price = stop loss price, price2 = limit price)
- [ ] settle-position

There seem to be a lot of things we could do in one order call like trailing stoploss, roi.. But I'll first concentrate on stop-loss-limit, since that's what we have for Binance and probably the most useful.

*Edit @xmatthias*: 
I'm adding the below here as i think it's important info without scrolling through all comments:

Almost all advanced ordertypes are currently disabled on kraken [source](https://blog.kraken.com/post/1234/announcement-delisting-pairs-and-temporary-suspension-of-advanced-order-types/).
The only ones enabled are "stop-loss" and "take-profit" [source](https://blog.kraken.com/post/1494/kraken-enables-advanced-orders-and-adds-10-currency-pairs/)

**Comment by xmatthias** [comment]
The problem with the take_profit orders is that they prevent you from setting a stoploss at the same time (you'd tie up your balance twice).

I would always prefer a stoploss-on-exchange over a take-profit order on exchange
however trailing-stop looks interresting ...

**Comment by mishaker** [comment]
some exchanges do allow you to put stoploss and take profit at the same time (not binance anyway). it is called OCO (one cancels other) orders if I am not mistaken. 
otherwise another approach can be cancel SL if the spot is higher enough and cancel TP if the price approaches the buy. but it is too risky in case of shake out.

**Comment by mishaker** [comment]
Just realized Kraken allows you to put both (SL and TP) since a while. it is called advanced orders. here is the article: 
https://blog.kraken.com/post/1494/kraken-enables-advanced-orders-and-adds-10-currency-pairs/

**Comment by xmatthias** [comment]
it's been suspended since i'm a member of kraken ...

just saying

**Comment by iuvbio** [comment]
I also thought that SL and TP were possible.. however, that was from the very early days of Kraken, haven't seen it in a while. If only one is possible, I agree SL is more important to implement on exchange. I've already made a prototype for the stop-loss-limit, but still need to test it and I won't have much time this weekend. Probably over the next week. I made this an issue rather than one big PR so that we can implement them one by one in individual PRs. If anyone else wants to have a go at any of these that would be very welcome of course :)

**Comment by hroff-1902** [comment]
> it's been suspended since i'm a member of kraken ...
> 
> just saying

What can this mean? Hmm...

**Comment by xmatthias** [comment]
probably that I registered too late ... or that it's been disabled since a year or so...

**Comment by iuvbio** [comment]
I've contacted Kraken Support over this and this was their answer:

> Thank you for contacting us regarding the Kraken API, specifically the availability of the advanced order types.
>
> As you are already aware, you are receiving the EGeneral:Invalid arguments:ordertype error because the advanced order types (such as stop-loss-profit, stop-loss-limit, etc.) are not presently enabled (via any of our trading platforms).
>
> Our developers are actively working on enabling the advanced order types, and we expect the order types to be available again within days to weeks (my apologies that I cannot be more precise).
>
> An announcement will be made on our official blog when the advanced order types are available again.
Thank you for contacting Kraken.

So, days to weeks... curious about that. This answer is from Wednesday. See also [here](https://github.com/ccxt/ccxt/issues/4972).

**Comment by xmatthias** [comment]
I don't think progressing with this will make sense at the moment.

as discovered in #2225 - kraken does not properly report free balance, and it's not straightforward to get this information from kraken.
Since we base the available calculation on that we cannot currently trade.

it should be possible to override get_balances() and either set `free=total` (which is wrong as it hides the amounts tied up in orders) - or by doing another call to `fetch_open_trades()` and aggregating these values by asset, subtracting the amounts from `total`, and assigning that to `free`.

Pseudo code to straighten my thoughts:

``` python
for trade in fetch_open_trades():
    bal[trade.asset]['free'] = bal[trade.asset]['total'] - trade.value_in_asset

```

I'll therefore block Kraken temporarily (it cannot be used anyway) until we have a solution to the above problem.

**Comment by hroff-1902** [comment]
ccxt 'universal interface' is not quite universal... 😢

**Comment by xmatthias** [comment]
well ... i've had my discussions around that today as well - even though kraken is a certified exchange for ccxt, that does only mean that ccxt implements the methods from the exchange, not that the exchange provides a good API :) 

side note: not even the Kraken webpage has a way to show free / available balance - so probably they don't know themselfs until you open an order ...

source: https://support.kraken.com/hc/en-us/articles/360000670903-How-can-I-see-the-balance-available-for-new-orders-

**Comment by iuvbio** [comment]
interesting.. it seems with all their "improvements" the Kraken API is only getting worse.

> or by doing another call to `fetch_open_trades()` and aggregating these values by asset, subtracting the amounts from `total`, and assigning that to `free`.

good idea, I will have a look at this once I get some time..

**Comment by xmatthias** [comment]
> good idea, I will have a look at this once I get some time..

it's not my idea, really: https://github.com/ccxt/ccxt/issues/5776#issuecomment-528226724

**Comment by xmatthias** [comment]
I'll close this issue now as kraken does not "really" support all the above order-types (it used to, but all appart from take-profit and stop-loss are disabled since over 2 years).

We can reopen this issue should that ever change again, but as it stands now i don't see this happening.


The only remaining and available order-type would be `take-profit`.
While it's not implemented, i doubt we'll ever do as it has very little sense.

This would prevent the creation of stop-loss on exchange - which would increase the risk in case of market crashes.
Having both ordertypes for the same asest is impossible (this would tie the asset twice, which is not possible on kraken).
