### ISSUE TITLE
Discussion/Enhancement: Verification for the names of pairs and staking currency

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1703]
Inspired by #1701 and #1697...

A few points to discuss regarding pair names, their verification and staking currency/staking amount, their firther refactoring and possible enhancements:

* Would it be better to remove all artificial checks for the names of the pairs everywhere in the code and add a simple check that verifies if the pair is in the list of the markets of the exchange? (i.e. one of the instruments, in other terms, known for the exchange) For both pair whitelist and pair blacklist...

* In addition, for the staking currency checking, we should (IMHO) look at the `limits` in the ccxt'market data instead of the name of the pair. The `limits` structure in the ccxt's market structure has the `cost` and `amount` values that together with the `base` and `quote` strings in the ccxt's market structure give complete information about the pair (market) staking currency.

* As for the staking currency amount... We could implement the `stake_amount` option accepting a dict (in addition to a simple value) with currency names as keys and stake amounts as values. That would allow to trade pairs with different staking currencies. May sound complicated and heavy for the code and testing, but just think about this. A list (dict) of amounts instead of a single value, that's it...

So the pseudo-code can be the following:

* If you need to verify names of the pairs in the whitelist or blacklist: Check if the pair name is in the list of the ccxt's markets, compare pair name with the ccxt's market `symbol`. That's it, no more, no less.

* If you need to check if the pair has particular staking currency (as specified in `stake_currency` option): Check if ccxt's market for this pair has `['limits']['cost']`, if so, the staking currency is the ccxt's market `'base'` field. Otherwise, if ccxt's market for this pair has `['limits']['amount']`, the staking currency for the pair is to be one specified in the ccxt's market `'quote'` field. This probably is already implemented in one of the @iuvbio 's last refactoring PRs.

* If `stake_amount` is a dict rather than a value, the `stake_currency` option can be ignored and the pairs staking currency can be checked against the keys of this dict.

**Comment by xmatthias** [comment]
i agree with most of the above - a `is_pair` function would definitely help, and should be simple to implement.

I'm currently not sure what you mean with using limits to determine stake/base currency (maybe / probably i misunderstand your intend)
For binance:
``` python
ct = ccxt.binance()
markets = ct.load_markets()
markets['ETH/BTC']['limits']

>>> {'amount': {'min': 0.001, 'max': 100000.0}, 'price': {'min': 0.0, 'max': 0.0}, 'cost': {'min': 0.001, 'max': None}}
```
The dict, on the other hand, has a field "base" and one "quote" ... i would rather use these ...? 
I'm not sure what's wrong with current base and quote detection - but I've not seen any bug reports that the wrong currency would be used.

> We could implement the stake_amount option accepting a dict

Accepting a dict is easy - yes - however I don't see the benefit. You can run 2 bots, one with BTC, one with ETH, against the same account, without adding a ton of complexity.

Also, it's not just stake-currency - if i specify i want the bot to trade 0.3 ETH, and 1 BTC , we need this as a dict too.
Also, max-open trades should then be "per stake-currency" - since that needs to match the above stake.

The usage of this is too limited to be worth the effort and complexity, and not worth increased maintenance burden and code complexity, not least because since most strategies I've seen so far may work for BTC, but perform badly for ETH or viceversa.

Also think on further consequences - what if the bot buys XRP twice, once from ETH, once from BTC Stake amount? the 2 could conflict, and if the strategy was wrong and XRP drops, it would (probably) drop for both, causing doubled loss, so this cool new feature actually increased your risk on the market.

**Comment by xmatthias** [comment]
This is partially covered by #3396 - but not fully therefore leaving it open for now.

**Comment by xmatthias** [comment]
closing as i can't find what's left in this (we will not support multi-stake for now). the rest is covered by #3396 .
