### ISSUE TITLE
Last candle is removed for all exchanges

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1715]
...even for those of them, that do not provide current incomplete candle in the ohlcv data (BitMEX).

**Comment by hroff-1902** [comment]
It's not a ccxt issue, imho. The last candle is removed in data/converter.py without any checks or verifications if this actually should be done.

**Comment by xmatthias** [comment]
it's not really a bug either since bitmex is not in the list of supported exchanges - and it's related to ccxt (ccxt does not mean it's ccxt, but related to ccxt).

I belive i read somewhere that ccxt has information if the exchange provides half-open candles or not ...

**Comment by hroff-1902** [comment]
I do not remember of this kind of info in the ccxt exchange data.
IMHO, this should better be defined in the exchange/exchangename.py exchange specific file, in ft_has or something...

**Comment by mishaker** [comment]
ft_has is a better approach. ccxt does not provide it for the moment.

**Comment by hroff-1902** [comment]
I've got a better solution -- this point will be resolved along with upcoming (which I started working on) implementation of pagination for ohlcv data,

If we provide to ccxt proper 'since' and proper 'limit', the incomplete candle won't be even taken...

What do you think, guys?

**Comment by xmatthias** [comment]
i am not certain that'll be foolproof - `limit` is in number of candles, if some candles in the middle "miss" different exchanges will behave differently.

I am not sure if ccxt extracts this and bases limit on time (so i always get exactly 500 minutes if i use 500 as limit on 1m candles) or if i get 500 candles - which may span 500 minutes, or 502 minutes (2 missing candles in the middle).

I think it is the latter - in which case it'll not really work the way you expect it to - and it'll be very difficult to debug or even test, since you'd need an outage on each exchange  to see how they all behave...

**Comment by kroitor** [comment]
@xmatthias we're planning to add better unification for pagination aspects that will cover most of the other issues discovered, including the indications of the above aspect (semantics of each argument will be much more precise, and we will have additional indications for empty candles and for the last candle as well).

**Comment by hroff-1902** [comment]
> i am not certain that'll be foolproof - `limit` is in number of candles, if some candles in the middle "miss" different exchanges will behave differently.

Thanks for pointing at this...

There is a simple workaround for this -- yes, in this case the last candle will be fetched, but we can build all missed candles and ignore the tail... I guess...

An ft_has exchange attribute modifying the behaviour of freqtrade/exchange code in the required aspects for certain exchanges is a much simplier solution, right. But it can also be tricky for debugging and testing...
