### ISSUE TITLE
Tests for scripts

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1751]
Tests for programs in the scripts catalog should be added.

At least just in order to run all of them subsequently with some parameters in case a developer made some modifications to them, to be sure that all of them can still be executed and have no syntax errors, for example.

**Comment by xmatthias** [comment]
The idea sounds good - but with the current structure we can't, since scripts is not a module, and freqtrade/tests does not have access to the scripts folder without some trickery, which will make testing a nightmare.

However, as discussed on slack, i would rather go with moving the scripts to freqtrade subcommands (say `freqtrade downloaddata`) - which looks more appealing to me, also from a usability point of view

**Comment by Dante2333** [comment]
freqtrade downloaddata seems really intuitive and natural, nice idea.

**Comment by hroff-1902** [comment]
Closing it since the original idea for this enhancement is not achievable (tests for scripts) and transition of the scripts functionality into main freqtrade subcommands has already been started and is an ongoing activity now.
