### ISSUE TITLE
History of trades

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1753]
How can I fetch the history of trades in my custom strategy?

I mean, fetch last N completed (sold) trades for the given currency pair, with their results (profit value or lost value for each).

Same for all pairs, N last completed trades and their attributes.

Need it for risk management.

**Comment by hroff-1902** [comment]
I mean in the code.

Assume I'll modify somehow interfaces of the strategy so that the whole freqtradebot instance is available, along with its persistense, trades, the Trade module, etc. accessible, How can I get results for, say 10 last completed (already sold) trades for a pair?

**Comment by xmatthias** [comment]
i think you can use something similar to the below (untested, includes probably syntaxerrors ...).

``` python
from freqtrade.persistence import Trade
# Stolen from rpc.py:
trades = Trade.query \
                .filter(Trade.is_open.is_(False)) \
                .filter(Trade.close_date >= profitday)\
                .filter(Trade.close_date < (profitday + timedelta(days=1)))\
                .order_by(Trade.close_date)\
                .all()
curdayprofit = sum(trade.calc_profit() for trade in trades)
```

Strategy is nothing other than a module running within freqtradebot, so persistence should be available.
Note that this will NOT work during backtest/hyperopt, since persistence is not initialized there.

**Comment by hroff-1902** [comment]
I'm not closing this yet since I hope I'll make it less complicated... To not forget about this, as a reminder...

**Comment by xmatthias** [comment]
I'll add documentation here - since we "could" also fix it via documentation.

We could also add static methods to the Trade class for some usecases (`get_trades_for_pair()`, `get_last_x_trades()` ... 
however covering all usecases will not be sufficient, and some users will still require the above. 

It's also not "that" complicated if you remove the filters for profitday ...

**Comment by hroff-1902** [comment]
Okay, fine, thanks! 👍
