### ISSUE TITLE
enableRateLimit should be switched to true by default in the config and defaults

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1764]
In the default config use
```
"ccxt_async_config": {
            "enableRateLimit": true
        },
```
... And probably in the default value.

Reason:
With current config and defaults Bittrex blocks new inexperienced users who just started evaluation of the bot and use default config for that.

**Comment by xmatthias** [comment]
I wouldn't enable ratelimit as you specify - it'll be as slow as with syncronous code, as it'll do exactly one call per second.

As long as you don't exagerate with the pairs in the pairlist, this should not be a problem, since a lot of calls will come as burst, and you'll then back off for 5m or 15min (depending on your interval).

If you need that many pairs (or if bittrex is enforcing a very strickt limit) the following config should work (play with rateLimit - the one below is working well for binance.

```
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
```

**Comment by hroff-1902** [comment]
You might be right.

I experienced this blocking with default config and default whitelist defined in that...

Anyway, this should not appear for newcomers that use default config, options in it should be consistent. If blocking appears frequently on default exchange bittrex with "default" whitelist specified in it, either whitelist should be reduced a bit or additional option like rateLimit you stated above should be added into default config as well.

**Comment by angelo-di-marzio** [comment]
Indeed, i have installed the bot and i'm running it for the first time with the default config and i get The owner of this website (bittrex.com) has banned you temporarily from accessing this website
config :
`"ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
`

**Comment by angelo-di-marzio** [comment]
Any idea on which parameters to tweak ?
