### ISSUE TITLE
Installation/freqtrade not found

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1766]
Whenever the image is being built with docker (docker build -t freqtrade .) following error shows up:

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/nielsschmidtmartinez/.Trash/freqtrade/freqtrade/Dockerfile: no such file or directory

freqtrade is not there as it says in the error message.

the manual installation gets a 'Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-install-rid3_yha/py-find-1st/' several times and then:

Command "/Users/nielsschmidtmartinez/.env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-install-jn385ve4/py-find-1st/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-record-7lx3n__v/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nielsschmidtmartinez/.env/include/site/python3.7/py-find-1st" failed with error code 1 in /private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-install-jn385ve4/py-find-1st/

What could be the problems?

**Comment by xmatthias** [comment]
It somehow looks like it's searching something in the trash? 

lstat /Users/nielsschmidtmartinez/**.Trash**/freqtrade/freqtrade/Dockerfile

is your dockerfile a symlink to something else (in Trash) or is the whole folder in the trash?

Is there a need to build the image yourself (did you modify stuff in the code)? otherwise you may simply run `docker pull freqtradeorg/freqtrade:develop` or `docker pull freqtradeorg/freqtrade:master` to get the latest prebuild image.


The second part could be related to #1675 - since the folders suggest you're on a mac (?)

**Comment by xmatthias** [comment]
Going to close this as the same problem was restatet in #1774.
