### ISSUE TITLE
running two strategies / bots in parallel on one machine?

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1768]
Hello! I like to run two strategies / bots in parallel on one machine? I am on Ubuntu 18.xx

How can I do this?

## Step 2: Describe your environment

  * Python Version: 3.7.1
  * CCXT version: 1.18.430
  * Branch: Develop

**Comment by hroff-1902** [comment]
The easiest way for a novice user is to open two terminal sessions and run one instance of the bot in each of them. With different configs.

So, create two config files, say, configA,json and configB.json (with different whitelists set in them, for example, or using two different accounts on the exchange) and run
```
python3 freqtrade -c configA.json
```
in one terminal session and
```
python3 freqtrade -c configB.json
```
in the second one.

Notice that if you run freqtrade in a terminal session you should better use the `screen` utility or an alternative. Otherwise the bot will be stopped when your terminal connection is lost or when you close the terminal. You should educate yourself with `screen` and how to restore sessions in it.

Other approaches to run two bot instances include multiple docker instances and multiple system service instances.

I'll add the description for system services a bit later...

**Comment by xmatthias** [comment]
to add to the above detailed description, you should also supply different db urls to avoid problems

`--db-url sqlite:///strategyA.sqlite`
`--db-url sqlite:///strategyB.sqlite`

**Comment by Prossi79** [comment]
Thanks guys! Each question for both versions:

1) Using two different configs, how can I start it with the different strategies?

python3 freqtrade -c configA.json  -s StrategyA  ?
python3 freqtrade -c configB.json  -s StrategyB  ?

2) how do I manage the different white lists / pairs if using one config? Can I define the pairs as well in the strategy file? If yes can you post an example pls?

**Comment by xmatthias** [comment]
you should use different configurations.
You can configure strategy in the configuration (`"strategy": "CoolStrat"`)- but you cannot configure pairs in the strategy.
Also, you should not run 2 live bots with the same stake currency on the same account ... that's untested and risky to produce errors.

The below is how i run it ... (in docker - but the command is basically the same).
 
`python3 freqtrade -c configA.json -s StrategyA --db-url sqlite:///strategyA.sqlite`
`python3 freqtrade -c configB.json -s StrategyB --db-url sqlite:///strategyB.sqlite`

**Comment by hroff-1902** [comment]
@xmatthias, 

May it have sense to add support for defining the pairs in the strategy?

**Comment by xmatthias** [comment]
i don't think that makes too much sense - pairs are exchange-specific - while the strategy is ideally not and can be used for many exchanges.
Also pairlist is not really mandatory if used with dynamic-whitelist ...

you will need to define the config anyway (for api keys, ...)- and you can have a "standard" config - and load the pairlist with a 2nd config (so you use `--config config.json --config config_pairsA.json` and `--config config.json --config config_pairsB.json`. (i seem to love this option more and more - thank you @hroff-1902!)

**Comment by hroff-1902** [comment]
> you will need to define the config anyway (for api keys, ...)- and you can have a "standard" config - and load the pairlist with a 2nd config (so you use `--config config.json --config config_pairsA.json` and `--config config.json --config config_pairsB.json`. (i seem to love this option more and more - thank you @hroff-1902!)

BTW, with second config used, one can specify the strategy in it as well.
I.e.,
run first instance as 
```
python3 freqtrade --config config.json --config config_pairsA.json
```
second one as 
```
python3 freqtrade --config config.json --config config_pairsB.json
```
where config_pairsA.json and config_pairsB.json define api keys (if different account on exchange used), exchanges (if different exchanges used), pair (if instances are running on different sets of pairs) AND define corresponding two different strategies. The config.json configuration file here is common and defines common settings, common for both instances,..

**Comment by xmatthias** [comment]
To extend on this - samples for such a configuratio below.

### Combined conf (config.json)

```json
{
    "max_open_trades": 3,
    "stake_currency": "BTC",
    "stake_amount": 0.05,
    "fiat_display_currency": "USD",
    "ticker_interval" : "5m",
    "dry_run": false,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },
    "exchange": {
        "name": "bittrex",
        "key": "your_exchange_key",
        "secret": "your_exchange_secret",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        }
    },
    "experimental": {
        "use_sell_signal": false,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "your_telegram_token",
        "chat_id": "your_telegram_chat_id"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

```
### confA (config_pairsA.json)

``` json
{
    "stake_currency": "ETH",
    "strategy": "strategyA",
    "exchange": {
        "pair_whitelist": [
            "LTC/ETH",
            "ETC/ETH",
            "DASH/ETH",
            "ZEC/ETH",
            "XLM/ETH",
            "NXT/ETH",
            "POWR/ETH",
            "ADA/ETH",
            "XMR/ETH"
        ],
        "pair_blacklist": [
            "BNB/ETH"
        ]
    }
}
```

### ConfB (config_pairsB.json)
``` json
{
    "stake_currency": "BTC",
    "strategy": "strategyB",
    "exchange": {
        "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "NXT/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
        "pair_blacklist": [
            "DOGE/BTC"
        ]
    }
}
```

**Comment by Prossi79** [comment]
Thank you for the very good explanations and example!! highly appreciated

A short recap:

1.) I should use two different stake currencies to avoid any issues, correct? Above it is ETH and BTC

2.) I understood that I should not trade same pairs .. above we got ETH/BTC and all other ETH pairs, we got DASH/ETH and DASH/BTC, ZEC/ETH and ZEC/BTC etc. ... this would not cause any issues?

**Comment by iuvbio** [comment]
You can set the db path either like that or in the configs, then you don't need to include them in every command. If you run the bots on different exchanges, you don't need to set different stake currencies. I wouldn't run two separate bots on one exchange, but it should work if you use different stake currencies and a small timeframe so that you don't get blocked.

**Comment by Prossi79** [comment]
Finally - I think I got the concpet ... in config.json I can define all common parameters and in configA.json I would define all what is just for BotA correct? configA.json would override all what has been defined in config.json, e.g. stake currency in above example?

I would need following parameters differently for each bot (running on binance with same account) -> stake currency, pairs, strategy, database, telegram bot ... anything else which would need to be splitted?


confA (config_pairsA.json)

{
    "stake_currency": "ETH",
    "strategy": "strategyA",
    "db_url": "sqlite:///strategyA.sqlite",
    "exchange": {
        "pair_whitelist": [
            "LTC/ETH",
            "ETC/ETH",
            "DASH/ETH",
            "ZEC/ETH",
            "XLM/ETH",
            "NXT/ETH",
            "POWR/ETH",
            "ADA/ETH",
            "XMR/ETH"
        ],
        "pair_blacklist": [
            "BNB/ETH"
        ]
    }
    "telegram": {
        "enabled": true,
        "token": "your_telegram_token",
        "chat_id": "your_telegram_chat_id"
    }
}


ConfB (config_pairsB.json)

{
    "stake_currency": "BTC",
    "strategy": "strategyB",
    "db_url": "sqlite:///strategyB.sqlite",
    "exchange": {
        "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "NXT/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
        "pair_blacklist": [
            "DOGE/BTC"
        ]
    }
    "telegram": {
        "enabled": true,
        "token": "your_telegram_token",
        "chat_id": "your_telegram_chat_id"
    }
}

**Comment by hroff-1902** [comment]
Correct. When you use two configs, the options set in the second one overwrite settings in the first config. If you additionally use command line parameters, they overwrite values of the corresponding options set in both configuration files. 

You can combine these in any way you want. Command line options are useful for quick temporary changing of the parameters. Assume you create a new variation of you strategyA with name strategyA_experimental. You can run it for testing without changes to the config you use for strategyA as:
```
python3 freqtrade --config config.json --config config_pairsA.json --strategy strategyA_experimental
```

You even should not delete options in the common config that are overwritten by second config -- values in the common (first) config will be overwritten, i.e. ignored. So if in the future you decide that some more options should differ for your strategies -- do not even touch the common config, just specify new values in the second, strategy-specific config. Just keep the proper order of configs in the command line.

Moreover, you can move the exchange key/secret into a separate config for security reasons, to avoid publishing this sensitive information when you paste your config here or somewhere else.

I mean you can run:
```
python3 freqtrade --config config.json --config exchange_keys.json --config config_pairsA.json
```
where exchange_keys.json contains your secretes (notice that no keys should in this case be specified in config_pairsA.json since it follows exchange_keys.json in the command line). Or even more complicated:
```
python3 freqtrade --config config.json --config exchange_keys.json --config telegram_keysA.json --config config_pairsA.json
python3 freqtrade --config config.json --config exchange_keys.json --config telegram_keysB.json --config config_pairsB.json
```
where telegram_keysA.json and telegram_keysB.json contains secrets for telegram that differ for two instances of the bot.

Combine it in any way you wish.


Running bot in the different terminal session, or as background jobs in the terminal sessions, as docker containers or system services is just a way to launch and control the bot app processes. For any approach, just specify the command line settings in proper way to satify your needs.

**Comment by hroff-1902** [comment]
Btw, notice that if you run two instances with diff. stake currency set in the configs, you should also adjust the stake_amount in the strategy config files, because this also differs for currencies.

**Comment by xmatthias** [comment]
I'll close this as i think it has been answered sufficiently

feel free to reopen if it's still unclear.

**Comment by gdominoni** [comment]
> to add to the above detailed description, you should also supply different db urls to avoid problems
> 
> `--db-url sqlite:///strategyA.sqlite` `--db-url sqlite:///strategyB.sqlite`

Hi, I know this thread is old, but ok... Question, what happens if you run them on the same database?

**Comment by xmatthias** [comment]
it'll only create problems, as both bots will try to handle the same trades.

**Comment by gmag11** [comment]
May I run two live bots (one on USDT and one in BTC) using same exchange account then? Make this sense? Thanks!

SOLVED: This is answered in https://github.com/freqtrade/freqtrade/issues/3703#issuecomment-678423599
