### ISSUE TITLE
hyperopts 

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1796]
running in osx mojave, as stated in instructions (venv):

hyperopts  appears to stop analysing at about 1/10 epochs without. If doing 5000 it stops at around 500-700, it achieved around 1000 once. If running 1000 epochs it stops at around 100-120. I have been running different hyperopts simultaneously and the same happens for each test. What is up with the other ~9/10?

**Comment by xmatthias** [comment]
I'm sure it's got nothing to do with your system.

I never noticed this to be honest, and testing it (

If you're on the latest develop, you could try to pass in `--print-all` to see all results (it's been merged yesterday - so you probably need to update first).

By default, hyperopt will only print "better" results - so maybe you reached the best result after 10% of the time.

the counting is odd/off - since it starts with 0 (so when testing with 10 epochs, the first output is 0/10, and the last 9/10 (but there are 10 in total).

I never noticed this to be honest, and testing it with --print-all it prints exactly the number of epochs specified.

**Comment by hroff-1902** [comment]
What do you mean by "stop analysing"? Does it stop responding/crashes or simply prints dots and do not produce new best results?

**Comment by hroff-1902** [comment]
may be related:

https://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux

**Comment by gitgitgat** [comment]
the terminal appears to be doing nothing for a while and then gets back to work, it does crash with several hyperopts running at once. better results are coming out in the end, although it is taking roughly 4hours running about 3-4 hyperopts at once where one crashes, and the remaining two take longer than previous hyperopts that were running two days ago.

**Comment by gitgitgat** [comment]
this could help: 
https://scikit-learn.org/stable/developers/performance.html

**Comment by xmatthias** [comment]
well running multiple hyperopt-processes does not make sense - they'll be eating away each others resources - since by default, each process tries to take everything your machine has.

Please test with 1 hyperopt-process only - this should no crash (unless there are errors in the strategy).
Also try the `--print-all` option, i think that's why you think it does nothing (because it does not improve after some time ...)

**Comment by gitgitgat** [comment]
hyperopt_results.pkl does not exist after running the tests?

**Comment by gitgitgat** [comment]
thanks

**Comment by hroff-1902** [comment]
you can run multiple hyperopts with the new option `-j 1` (update from develop, just merged). That means each hyperopt wil work in one single process. When you run multiple hyperopts without this option, each runs 4 processes and the cpus are overloaded. This adds additional overhead for the system to switch scheduling context etc... (Of course, application should not crash anyway... What's the traceback it shows?)

However, I agree with @xmatthias -- there is no sense to run multiple hyperopts simultaneously, with same success you can run them one by one in a batch script, for instance...

**Comment by xmatthias** [comment]
#1804 limits parallelism to 1 per installation, since the others will eat away the cpu from each other.
