### ISSUE TITLE
Backtesting does not guard against use of future data

### ISSUE THREAD

**Issue by MichealReed** [freqtrade/freqtrade#1839]
* Python Version: 3.6.7
  * CCXT version: 1.18.507
  * Branch: Develop
  * Last Commit ID: 4ae743ecb6e461e8f4febee715f204a7a484eed3
  
The back testing engine allows for shifts to future data and does nothing to prevent a user from utilizing data from the future for current signals.

### Steps to reproduce:

  1. Utilize the chikou span in a signal.
  2. Save the DF as a CSV.
  3. Investigate results. Chikou value always reflects the price + 30 rows.

**Comment by xmatthias** [comment]
Well yes - but there is nothing we can do against that while keeping backtesting performant (which means using mostly vectorized operations).

The only way i know to protect against this is to feed the data to the strategy line by line - which will take HOURS for a few months of 5m data (since the whole analysis needs to be performed once for each line (incl. a reasonable amount of history).

It is known that this can happen during backtesting if one is  not carefull - but a normal flow should be to perform backtesting - then dry-run (you'll notice this in dry-run, since your signals will be empty) - then live.

we should point this out clearer in the documentation - but that's all i can think of we can do against this.

If you have other ideas on how to detect this please let us know.
