### ISSUE TITLE
emergency stop against repetitive "loops" and loss

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1841]
## Step 2: Describe your environment

  * Python Version: Python 3.7.1
  * CCXT version: ccxt==1.18.509
  * Branch: Develop
  * Last Commit ID: c8d75fbd8ac10e2af5502bf8e849061bff1c1bb5

  
## Step 3: Describe the problem:

During live mode my bot bought and sold  7 times in a row the same pair (BTT/BTC), each times running into stop loss (-10%). I suspect that the first trade signals to open the next one. All open and close rates in the 7 trades were exactly the same ... kind of self created loop?

Luckily I was just checking my bot on telegram and stopped the bot manually, otherwise it would have continued until all my BTC balance on Binance would have eaten away!

Please see sqlite database as zip enclosed.
[strategyB.zip](https://github.com/freqtrade/freqtrade/files/3168988/strategyB.zip)

Can a kind of "emergency auto stop" be integrated in the bot? (e.g. after 5 negative trades or stop loss hitted in row it would stop automatically esp. in live mode)

PS: I have backtested the strategy and did a run in dry mode - all vey good

**Comment by xmatthias** [comment]
This is a dangerous pair ... if you check the chart (https://www.binance.com/en/trade/pro/BTT_BTC) - it does "binary" moves of >10 %.

![2019-05-11-141737_1123x402_scrot](https://user-images.githubusercontent.com/5024695/57569597-8a8b1d80-73f7-11e9-8e91-c677c776fc4b.png)

Did you add this manually to the pairlist?

**Comment by Prossi79** [comment]
no, thats the problem .. i worked with the dynamic pairlist  ...  :/

    "pairlist": {
        "method": "VolumePairList",
        "config": {
            "number_assets": 30,
            "sort_key": "quoteVolume",
            "precision_filter": true
        }
    },

**Comment by xmatthias** [comment]
Well technically it is in the top 20ish pairs for today (depending when it's checked) - so dynamic pairlist selecting this is correct. also stoploss is still possible below - which makes this also correct.

I've never been convinced that volume alone is a good indicator for good pairs - however i currently don't have an alternative idea for automatic selections.

**Comment by xmatthias** [comment]
an alternative as "emergency stop" would be `/blacklist BTT/BTC` - which will add this pair to the blacklist.

**Comment by Prossi79** [comment]
Yeah, the problem is that there are some more kind of binary dangerous pairs ... such as HOT/BTC, I was running into that one too. :/

If applying the dynamic pair list it would mean to manually check for such pairs, if there is no other "check" built in the strategy itself.

**Comment by xmatthias** [comment]
Detecting these pairs dynamically is not that simple.

It's happening if the value is very low (0.000001 or so for BTC) - but absolute value changes for HOT/ETH ... and changes again for HOT/USDT.

So far, i've not come across a solution for this ... if you have ideas (which are applicable for different stake-currencies) - please share

**Comment by gaugau3000** [comment]
@Prossi79 Be carefull with precision filter maybe i have to open an issue on this because i noticed that he take some time before blacklist the pairs with low value. I don' t know why he don't due it at bot start for sure code related about. Maybe check the value of the coin on close in your strategy as a filter to prevent buy you don't want with low coin value.

**Comment by hroff-1902** [comment]
> Can a kind of "emergency auto stop" be integrated in the bot? (e.g. after 5 negative trades or stop loss hitted in row it would stop automatically esp. in live mode)

That's exactly why I asked @xmatthias (couple of weeks ago) how to access (or fetch) the history of the trades, so that it would be possible to implement position sizing rules based on the history of trades, with a predefined or even a user-defined custom function...

**Comment by hroff-1902** [comment]
For dangerous shitcoins -- the solution here can be a yet another pair filter based on price, PricePairList: include pair into whitelist only if price >= configured min value. Or even if min <= value <= max.

**Comment by Prossi79** [comment]
What about a the apporach to implement a kind of **"automatic emergency brake"** as general optional feature, independent of this low value pair problem. 

I think it would be in general very good if the bot stops automatically when a fatal / critical error occurs (e.g. same negative tardes in a row), especially in live mode. In backtest some issues apparently do not happen.

**Comment by hroff-1902** [comment]
> I think it would be in general very good if the bot stops automatically when a fatal / critical error occurs (e.g. same negative trades in a row), especially in live mode. In backtest some issues apparently do not happen.

The problem here is that a set of "same negative trades in a row" is not a "fatal / critical error", it's a normal and frequently expected situation...

**Comment by xmatthias** [comment]
i was thinking about the min price too - but it's kinda difficult to calculate since it's very different between different stake currencies (0.000001 for BTC, 0.0001 for ETH - for example).

maybe we can use one of the minimum values per market for that and configure it as a % offset from that ... (different from the stoploss-calculation - which does only check if there's room for stoploss or not).


negative trades are a) market dependent (we may or may not want to stop), and b) can be desired - if we have a VERY tight stoploss where it's acceptable to have 20 stoploss hits - but 1-2 successfull trades make all these losses up.

It'll also depend on personal preference if you wanna stop the bot completely, or stop trading for the day - or stop trading this pair alone.

Not a strategy i would run necessarily - but still a valid trading strategy.

Also - especially with pairs like HOT i had 3 bad trades (-5% each), 1 with 1% gain, and another 5 bads  - and repeating that pattern over and over again (will have to check if i still have that DB file ... prolly not since it was a dry-run test). So even an **emergency stop** would not trigger, since the 1 gain would reset that trigger - however the total loss was substancial.

**Comment by Prossi79** [comment]
oh, okay ... similar accident happens to you @xmatthias  :/ but yeah, my suggestion would have not helped in that case

@hroff-1902 I think it depends on your strategy (stoploss etc.), in my strategy I am running I would consider 5 trades running into a -10% stop loss as a fatal error, eating much much money

What about building a optionally feature in the FT, something like "emergency stop" after x negative trades / stop losses? If you have a very tight stoploss and if it fits in your strategy you may accept 50 times hitting a stoploss in a row , but if this happens something might be wrong too - correct? 

I think this would be an awesome safety feature.

**Comment by hroff-1902** [comment]
> What about building a optionally feature in the FT, something like "emergency stop" after x negative trades / stop losses? If you have a very tight stoploss and if it fits in your strategy you may accept 50 times hitting a stoploss in a row , but if this happens something might be wrong too - correct?

I'm working on position management based on history of trades. It would allow to descrease position size after unsuccessful trades. Should prevent such massive losses you are talking about...

Another possibility, as I said above, could be the PricePairList, which would unselect cheap shitcoins from the whitelist.

Another possibility (a new idea, just found it, to be discussed) can be another PairList filter, based on the history of trades, which would unselect a pair after N unsuccessful trades performed on it. (But your balance could be already empty by that time if you do not follow risk management and if your stake_amount is too high for your small balance...)

**Comment by gaugau3000** [comment]
@hroff-1902 PricePairList could be a good. There is a precision_filter when you use a dynamic pairList but it filter based on stoploss. Maybe something like that not based on stop loss.

**Comment by Prossi79** [comment]
Hi Guys! how is this topic going? Did you implement such a feature? 

I recently had an issue where it would be good if it would be possible to define a max loss in a row or lose trades in a row where the bot automatically stops. During the recent BTC flash crash my test bot was running mad, such a feature would have stopped him.

Currently we can just set a max loss per trade (stop loss) but not for a strategy / bot in total.

**Comment by hroff-1902** [comment]
Don't worry, it's in my personal list of TODOs...

**Comment by dj-crypto-rick** [comment]
Hi guys

hroff-1902, you mentioned "Don't worry, it's in my personal list of TODOs..." re #1841

Did you ever build this functionality?

I'd sleep much better at night knowing that I'm not going to wake up and find my entire crypto balance gone due to a never-ending loop of losing trades.

Thanks very much,

Rich

**Comment by xmatthias** [comment]
@dj-crypto-rick please don't revive old threads - it'll give everyone in this conversation a ping which is clearly not necessary.

This is possible with [protections](https://www.freqtrade.io/en/latest/plugins/#protections) - so please make sure to read the documentation.
i'll also lock this conversation to avoid another "revival".
