### ISSUE TITLE
Hyperopt telling me not to trade as best strategy

### ISSUE THREAD

**Issue by hpdeandrade** [freqtrade/freqtrade#1885]
I'm running hyperopt and whatever timerange or parameters I set, it suggests me not to trade as being the best strategy ;(

![image](https://user-images.githubusercontent.com/46167400/58445523-568c4980-80d3-11e9-9e87-83244f90018e.png)

I'm running freqtrade this way:
`python freqtrade -c config.json hyperopt --customhyperopt OPT_FILE_NAME --timerange=20190101-20190520 -e 100`

When I run like below, optimization gives me something more resonable.
`python -m freqtrade -c config.json hyperopt --customhyperopt OPT_FILE_NAME --timerange=20190101-20190520 -e 100`

Why am I getting different results by running in these two different ways? What is the correct format considering I'm using Python 3.7 on Windows?

Thanks!

**Comment by xmatthias** [comment]
both options are correct/identical if the installation was done correctly.

by default, hyperopt starts with a random point in the hyperopt space, so subsequent runs may / will probably lead to different results. You can override this by using `--random-state 42` (or whatever number) on both.


Note that hyperopt stores state in the user_data directory, so you may need to remove `hyperopt_tickerdata.pkl` and `hyperopt_results.pickle` to be sure it starts from 0.

**Comment by hroff-1902** [comment]
@hpdeandrade try to use the `--min-trades=10` option (was added recently, need to add more docs on it), Try to vary this value as well. (See the description below.)

The reason is that during the optimization process the hyperopt algorithm may find a set of hyperopt parameters (a point in the optimization hyperspace) which fetches one single lucky trade (or a couple, for example) with comparatively big profit. For the DefaultHyperopt there are lots of such points in its hyperspace so it happens frequently. If you perform longer optimization attempts, with 1000 epochs for instance, you'll end to a such hyperspace point almost always for the DefaultHyperopt. The objective function is low at this point (cause profit is comparatively high and profit is one of the components of the objective funxtion), The optimization algorithm decides then that this point is near the local minimum of the objective function and starts optimization around this useless point with only 1 or 2 trades.

The `--min-trades=N` option allows to mark all points in the hyperspace with number of trades < N as "bad" points, assigning them purposefully large value of the objective function, thus excluding them from treating as local minimum of the objective function. In short, if you think that all hyperopt space points with trades < N is not of interest for you, assign the value of N or a bit less to this option...

@xmatthias I know, this should be well documented. I'm going to complete the bunch of changes to the hyperopt in #1775 and document all of them. Such description given to other users will definitely help me at this.

**Comment by hroff-1902** [comment]
> Why am I getting different results by running in these two different ways? What is the correct format considering I'm using Python 3.7 on Windows?

As @xmatthias proposed, try to run both variants of your command with the `--random-state whatever_positive_int` option. You should obtain identical results. With this option, the optimization starts with same initial points in the hyperspace.

Also try to use the `--print-all` option to see all optimization evals, not only the best ones. This can also help compare results.

**Comment by hpdeandrade** [comment]
Many thanks @xmatthias & @hroff-1902 

Before using `--min-trades=N` I tried both ways with `--random-state 42` (also trying 24 😆) and it returns me the same strategy (0 trades though), which makes me believe files are correctly installed.

When using `--min-trades=N`, outcome is a strategy different than 0 trades but still it seems very strange to me. My Objective gets decreasing as soon as hyperopt simulates but end result is not even the best if I look at the simulations.

In the example below I ran the following code and clearly simulation 44/100 was better than 70/100 (the chosen one):
`python freqtrade hyperopt --customhyperopt BBRSIOPT --timerange=20190228-20190520 --min-trades=20`

![image](https://user-images.githubusercontent.com/46167400/58518863-42a21f80-8187-11e9-8fe2-cd986a8d0af6.png)

**Comment by hroff-1902** [comment]
> unless a lower duration weights that much in our Objective target?

You are completely right. If you look at the code, you can find the current objective function (see at freqtrade/optimize/hyperopt.py):

```
    def calculate_loss(self, total_profit: float, trade_count: int, trade_duration: float) -> float:
        """
        Objective function, returns smaller number for more optimal results
        """
        trade_loss = 1 - 0.25 * exp(-(trade_count - self.target_trades) ** 2 / 10 ** 5.8)
        profit_loss = max(0, 1 - total_profit / self.expected_max_profit)
        duration_loss = 0.4 * min(trade_duration / self.max_accepted_trade_duration, 1)
        result = trade_loss + profit_loss + duration_loss
        return result
```

From my point of view, the coefficient of 0.4 is too agressive here, At least for DefaultHyperopts. As I already mentioned somewhere in the issues, I personally have got better optimization results with coefficient set to 0.1 or even to 0.04. Try to modify it locally in the code...

That's why I'm going to make this customizible in the future, so that users could change weights for the objective function or probably even completely override the objective function in their custom hyperopts. This is work in progress for a while...

See also some of my findings on description of the meaning of the hyperopt results here: #1779. It was created by other devs long time ago and without sufficient documentation it <s>is not easy</s> requires some effort to understand the hyperopt results and the optimization path in the hyperspace.

You may obtain some more clear and evident results with the `--print-all` option, as I think, that's why I added this option into hyperspace recently.

You may also take a look at #1775. Feel free to add ideas when you are deep enough in the freqtrade hyperopt and have some thoughts on further usefull enhancements.

**Comment by hpdeandrade** [comment]
Great! I took the opportunity to change the file and work with Sharp Ratio as my Objective, as taught in a Udemy course I took (offered by Montreal Trading Group).

For the sake of interest, see below - it has indeed yielded better optimization results.

`def calculate_loss(self, total_profit: list, trade_count: int) -> float:
        """
        Objective function, returns smaller number for more optimal results
        """
        period = self.max_date - self.min_date
        days_period = period.days

        #adding slippage of 0.1% per trade
        total_profit  = total_profit - 0.0005
        expected_yearly_return = total_profit.sum()/days_period

        if (np.std(total_profit) != 0.):
            sharp_ratio = expected_yearly_return/np.std(total_profit)*np.sqrt(365)
        else:
            sharp_ratio = 1.

        sharp_ratio = -sharp_ratio
        print(expected_yearly_return, np.std(total_profit),sharp_ratio)


        result = sharp_ratio
        self.resultloss = result
        return result`

Again, many thanks for all your kindness and help.

Cheers!

**Comment by hroff-1902** [comment]
Pls return back the function you used.
I'll correct the appearance...

**Comment by xmatthias** [comment]
It's actually there (in the link) ... ;)

**Comment by hpdeandrade** [comment]
You mean the code function in my reply? Couldn't figure out why the code didn't fit between the quotes.

**Comment by hroff-1902** [comment]
in triple backquotes...

**Comment by hpdeandrade** [comment]
Here we go! Thanks again guys!

```
def calculate_loss(self, total_profit: list, trade_count: int) -> float:
        """
        Objective function, returns smaller number for more optimal results
        """
        period = self.max_date - self.min_date
        days_period = period.days

        #adding slippage of 0.1% per trade
        total_profit  = total_profit - 0.0005
        expected_yearly_return = total_profit.sum()/days_period

        if (np.std(total_profit) != 0.):
            sharp_ratio = expected_yearly_return/np.std(total_profit)*np.sqrt(365)
        else:
            sharp_ratio = 1.

        sharp_ratio = -sharp_ratio
        print(expected_yearly_return, np.std(total_profit),sharp_ratio)


        result = sharp_ratio
        self.resultloss = result
        return result

**Comment by hroff-1902** [comment]
```
if (np.std(total_profit) != 0.)
```

Hmm, they compare floats for equality again...
