### ISSUE TITLE
[idea/discussion] new configuration / args system

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1945]
## Problem

Since we've been struggling lately with the arguments / config-options, i've been giving some thought to this problem.

We mostly define an argument in multiple places so it shows up as

1. CLI argument (different overlapping options between the different sub-commands)
1. config option
1. optionally, overridable by the strategy

We define this in multiple places (`arguments.py`, `configuration.py`, `strategy_resolver.py`, and currently some of the scripts).

Ideally, we should have one place to look for these things.

## Idea

Having a simple Class which defines everything required, and arguments, config options (and overrides) and strategy parameters (and overrides) are then created automatically from this.

## Sample mock implementation

*Note* this is mock code, which will not actually work. Also, there is currently no implementation behind "FTConfiguration".

``` python
FTConfiguration(name="strategy",
                cli=["-s", "--strategy"],
                help="Specify strategy class name (default: %(default)s).",
                default="DefaultStrategy",
                type=str,
                usages=["main", "backtesting", "edge-cli", "plot"],
                strategy_argument=False,
                )
FTConfiguration(name="config",
                cli=["-c", "--config"],
                help='Specify configuration file (default: %(default)s). '
                     'Multiple --config options may be used.',,
                default="config.json",
                type=str,
                action="append"
                usages=["main", "backtesting", "edge-cli", "plot"],
                strategy_argument=False,
                )
FTConfiguration(name="stake_amount",
                cli=['--stake_amount'],
                help='Specify stake_amount.',,
                default="DefaultStrategy",
                type=float,
                action="append"
                usages=["main", "backtesting", "hyperopt"],
                strategy_argument=True,
                override_output='Parameter --stake_amount detected, '
                                'overriding stake_amount to: {} ...'
                )
```

Based on this, we could then dynamically generate arguments where they are needed, copy the arguments to the configuration, or load them from the configuration, and move them to the strategy eventually.

An alternative approach to this would be to use a .yaml (or json) configuration file specifying more or less the same things - but i think using it as class (or NamedTuple?) should work for our usecase.

This is just an idea for now, maybe it's terrible, but that's why i created this issue - to discuss.

Let me know.

**EDIT**:
for clarification: 
This would remove most argument-defining code in both `arguments.py` and `configuration.py` - since `parser.add_argument()` is only called once, and do the same to `_args_to_config()` in `configuration.py

**Comment by hroff-1902** [comment]
Maybe. Need to think...

**Comment by xmatthias** [comment]
An alternative to using `usages=["main", "backtesting", "hyperopt"],` is to add this to a dict of arguments, and then have the command "pick and choose".

The file below is quite messy since there are thousands of cli options (and subcommands) - however it's about the concept, not about copying the whole thing.

A sample for this from airflow:
Argument definition (i would add the config-arguments here too)
https://github.com/apache/airflow/blob/8a89175ad938ef1c3200384d1ed48105b61c64de/airflow/bin/cli.py#L2060-L2071

Assignment of arguments to subcommands:
https://github.com/apache/airflow/blob/8a89175ad938ef1c3200384d1ed48105b61c64de/airflow/bin/cli.py#L2197-L2203

Assignment of commands to subcommands:
https://github.com/apache/airflow/blob/8a89175ad938ef1c3200384d1ed48105b61c64de/airflow/bin/cli.py#L2386-L2398

**Comment by hroff-1902** [comment]
Well, I see the following problems with current implementation that have to be resolved in the new concept:

-- some of the options, that are available now for the "main" freqtrade (called without a subcommant) are true common (verbosity level, logging options) while others are only applicable for the running bot -- like sd-notify, dry-run, etc. (I separated them from the "true common" and called them "main" in arguments.py during last cleanup). They should not even appear in the '--help' output for the subcommands. It may not be achievable with parseargs, possible we should consider a subcommand ('run' or 'live', or maybe a couple of subcommands like 'live' and 'dry-run') to run the bot with those 'main' options available for the running bot and really separated from the 'true common' options.

-- of course, all defaults should be collected in one place. Possibly in configuration.py. In principle, this is achievable in the current implementation -- we should simply remove any defaults from arguments.py and move their handling to configuration.py.

-- any implementation should make complete set configuration settings merged with the values from arguments -- so that no code in the codebase required to call config.get('setting', DEFAULT_VAL) just because the setting can be absent in the config. If the option is set in the arguments -- assign its value to the corresponding config setting. If not and if it's set in the config -- use that vaule. Otherwise -- assign the designated default value for this setting. But always fill it with some value. So that the code in the main freqtrade, in the modules and in the custom strategy/hyperopt may simply call config['setting'] without exceptions.

-- settings shared with strategies. Now they are merged with the settings in the config and result is stored in the strategy. It should be stored in the config itself. So that no code in the main freqtrade attempts to fetch the settings from the strategy. The code should always simply call config['setting']. In the same time, the merged settings should be copied to the strategy so that custom code in the strategy may work as in the meantime, using variables from the strategy.

May be all this a bit wider than this issue suppose, but this is here at least to memorize all these points for the future.

Also, in order to memorize and for completeness, I'm keeping the reference to the following PR here: #1947, where some discussion about arguments also took place.

**Comment by xmatthias** [comment]
> -- settings shared with strategies. Now they are merged with the settings in the config and result is stored in the strategy. It should be stored in the config itself. So that no code in the main freqtrade attempts to fetch the settings from the strategy. The code should always simply call config['setting']. In the same time, the merged settings should be copied to the strategy so that custom code in the strategy may work as in the meantime, using variables from the strategy.

I disagree with this for the following reasons:
- accessing `strategy.argument` should be more efficient than config['argument'] - at least when implemented using `__slots__`.
- using `strategy.argument` technically allows the strategy to modify this during runtime  (it's not documented and a bit tricky / untested, but possible - see https://github.com/freqtrade/freqtrade/issues/1929#issuecomment-504148242)

> -- any implementation should make complete set configuration settings merged with the values from arguments 

This does make sense  - but we may also look at #36 - since all options are available at all times (after parsing/startup ...) in the configuration, we could statically define them in a class, which would allow to "fix" typing - which would avoid using `str(config['argument'])` in certain cases just to make mypy happy.
*side note: this must be a 2nd step though - as that will touch all files of the bot - and will require some more thought.*

> some of the options, that are available now for the "main" freqtrade (called without a subcommant) are true common (verbosity level, logging options) while others are only applicable for the running bot

This is a good point, and i think we'll need to fix this seperately (by adding `freqtrade trade` (dry-run is a flag, then ?) ) ... ? but that'll need to be a slow change, since it'll break the startup logic everyone's used to.r

**Comment by hroff-1902** [comment]
> > -- settings shared with strategies. Now they are merged with the settings in the config and result is stored in the strategy. It should be stored in the config itself. So that no code in the main freqtrade attempts to fetch the settings from the strategy. The code should always simply call config['setting']. In the same time, the merged settings should be copied to the strategy so that custom code in the strategy may work as in the meantime, using variables from the strategy.
> 
> I disagree with this for the following reasons:
> 
> * accessing `strategy.argument` should be more efficient than config['argument'] - at least when implemented using `__slots__`.
> * using `strategy.argument` technically allows the strategy to modify this during runtime  (it's not documented and a bit tricky / untested, but possible - see [#1929 (comment)](https://github.com/freqtrade/freqtrade/issues/1929#issuecomment-504148242))

I'm not sure about performance, but accessing config from the main freqtrade codebase looks more solid from the design point of view.

In the same time, yes, changing values in the strategy should also be an option and these changed values should also be used by the main freqtrade codebase, This is acievable if all this stuff are references to the same objects.
 
> > -- any implementation should make complete set configuration settings merged with the values from arguments
> 
> This does make sense - but we may also look at #36 - since all options are available at all times (after parsing/startup ...) in the configuration, we could statically define them in a class, which would allow to "fix" typing - which would avoid using `str(config['argument'])` in certain cases just to make mypy happy.
> _side note: this must be a 2nd step though - as that will touch all files of the bot - and will require some more thought._

Defining options statically in a class (with their corresponding default values) is a nice option, I like it.

> > some of the options, that are available now for the "main" freqtrade (called without a subcommant) are true common (verbosity level, logging options) while others are only applicable for the running bot
> 
> This is a good point, and i think we'll need to fix this seperately (by adding `freqtrade trade` (dry-run is a flag, then ?) ) ... ? 

Well, or a separate commands (for live trade and for dry-run). Just consider this case.

>but that'll need to be a slow change, since it'll break the startup logic everyone's used to.r

Sure, this is a slow change, we are just discussing the design moments for the future...

**Comment by hroff-1902** [comment]
Pls take a look at this: https://stackoverflow.com/a/6130879
(a comment with the class NoneDict).

It allows to use config['setting'] everywhere, including custom strategy code, even if assigning it a value was missed in some conditions. Can be handy to avoid exceptions experienced by the users in the rare cases.

**Comment by xmatthias** [comment]
i would rather keep the `config.get()` for now until we have a class (when it'll not be relevant anymore).

Otherwise we'll need to touch the same things twice ... which would be a waste ;)

**Comment by xmatthias** [comment]
I've been playing witht he above proposal for a bit - the way i proposed it is difficult to implement due to how argparse want's the arguments.
I would rather have a dict with all arguments (as follows) and then allow the commands to "pick and choose".

``` python
OPTIONS = {
    # Common arguments
    "loglevel": Arg('-v', '--verbose',
                    help='Verbose mode (-vv for more, -vvv to get all messages).',
                    action='count',
                    dest='loglevel',
                    default=0,
                    ),
    "logfile": Arg('--logfile',
                   help='Log to the file specified',
                   dest='logfile',
                   metavar='FILE',
                   ),

    "version": Arg('--version',
                   action='version',
                   version=f'%(prog)s {__version__}'
                   ),
    "config": Arg('-c', '--config',
                  help="Specify configuration file (default: %(default)s). "
                  "Multiple --config options may be used. "
                  "Can be set to '-' to read config from stdin.",
                  dest='config',
                  action='append',
                  metavar='PATH',),
    "datadir": Arg('-d', '--datadir',
                   help='Path to backtest data.',
                   dest='datadir',
                   metavar='PATH',)
    # Main options
}

...

def add_args_from_option(self, parser, optionlist):

        for val in optionlist:
            opt = OPTIONS[val]
            parser.add_argument(*opt.cli, **opt.kwargs)

...

self.add_args_from_option(self.parser, ['loglevel', 'version', ...])
```

It'll remove some of the benefits - but i just dislike to call 6(!!) functions to get the command for plot_dataframe.py (as an extrem example). 
THe funny thing is - it adds a lot more options that what really do something in the plotting context.

**Comment by hroff-1902** [comment]
One of the main questions we should address here: how to handle default config in diff. subcommands. Should we keep current behaviour: use config.json for main live/dry run and for other simple subcommands allow them to run without config and use an internal hardcoded one, taking the exchange name from `--exchange` option? This can even be implemented for the main dry-run, for backtesting, hyperopt and edge since they do not require exchange credentials... Anything except main live run can in principle run with internal config if default one config.json is not created yet and a custom config is not specified with `-c`. And even the main live-run could fall back to the dry-run mode if no custom config is specified and the default one cannot be found... This has effect on handling the config argument so should be addressed here...

**Comment by xmatthias** [comment]
I'll close this as i think we're at a good point with the new argument settings.

handling of config -> class may be tracked in #36.

**Comment by hroff-1902** [comment]
> I'll close this as i think we're at a good point with the new argument settings.
> 
> handling of config -> class may be tracked in #36.

👍 
I have an extra enhancement in one of my stashes, but it does not require to keep this one open.
