### ISSUE TITLE
How to use multiple accounts in config files

### ISSUE THREAD

**Issue by sbralin** [freqtrade/freqtrade#1953]
Hi all, I have 3 different accounts in binance, hitbitc, bittrex and I want to use single config file in one terminal session, how to configure config.json file?
python freqtrade -c config_binance.json -c config_hitbtc etc... But freqtrade starts only hitbtc, and not both! Any advise?

**Comment by xmatthias** [comment]
I am not sure what you are trying to do - but one bot instance is limited to one exchange.

To run the bot on 3 exchanges, you need to use 3 terminal sessions (or tmux ...) and start the bot 3 times, once for binance, once for hitbtc, and once for bittrex.

**Comment by hroff-1902** [comment]
> Hi all, I have 3 different accounts in binance, hitbitc, bittrex and I want to use single config file in one terminal session, how to configure config.json file?
> python freqtrade -c config_binance.json -c config_hitbtc etc... But freqtrade starts only hitbtc, and not both! Any advise?

Do you really want to use one config or simply run the bot with multiple exchanges using one terminal session?

First is not achievable and will not be implemented in the nearest future (or maybe will not be ever implemented at all) since the freqtrade bot and its config supports one exchange for one running instance.

Second is possible -- simply run multiple instances of the bot (each with one corresponding exchange configured in a separate config) in the background in one terminal session. Output then can be complete mess, so redurect the output from the bot instances to different logfiles.

Remember that you can pass multiple config files to one instance of the bot, so you can keep the common part of your config in a separate common config file which is passed to all of the instances you run.

**Comment by hroff-1902** [comment]
Closing the issue since the question has been answered.
Feel free to reopen.

**Comment by kimathi99** [comment]
HI is it possible to trade multiple accounts in binance using the same freqtrade bot?

**Comment by xmatthias** [comment]
No, you will need to use different bots for this.

Also - please dont revive issues that are 2 years old. That's bad practice, and will send an alert to everyone who was involved in this issue (but potentially won't care about this any longer).

if this is still unclear, please open a new issue, or better yet, discuss the question in our [discord server](https://discord.gg/p7nuUNVfP7).
