### ISSUE TITLE
Installation failed due to pip dependcy missing in setup.sh

### ISSUE THREAD

**Issue by phe-sto** [freqtrade/freqtrade#1956]
My environment
Ubuntu 18.04.2 LTS
Python 3.6
ccxt 1.18.726
Develop a75f08cf17cd039aaae1e8b980482c63c0b94266
  
The problem:

On a fresh Ubuntu 18.04.2 LTS system, pip3 was not installed, the installation failed as the setup.sh install pip packages.

To reproduce:
Reproduce in a Ubuntu docker in the above mentioned Ubuntu system.
Create the docker:
`chrichri@chrichri-KPL-W0X:~/freqtrade$ sudo docker run -ti ubuntu /bin/bash`
In the docker if installing the packages from setup.sh

```
root@620b800e245d:/# apt
apt 1.6.11 (amd64)

...

root@620b800e245d:/# apt-get update

...

Fetched 16.8 MB in 23s (741 kB/s)                                                                                                                                                                          
Reading package lists... Done
root@620b800e245d:/# apt-get install python3.6 python3.6-venv python3.6-dev build-essential autoconf libtool pkg-config make wget git
Reading package lists... Done

...

done.
```

No pip related command:
```

root@620b800e245d:/# pip
bash: pip: command not found
root@620b800e245d:/# pip3
bash: pip3: command not found
root@620b800e245d:/# python -m pip 
bash: python: command not found
root@620b800e245d:/# python3 -m pip
bash: python3: command not found
```

This cause the installation to fail, to fix the issue I add python3-pip dependency to setup.sh. Confirmed in docker:

  ```
root@620b800e245d:/# apt install python3-pip
Reading package lists... Done

root@620b800e245d:/# pip3

Usage:   
  pip <command> [options]
  ```

**Comment by xmatthias** [comment]
Maybe i miss something, but why is setup.sh relevant when you're using docker?
you could just run `docker pull freqtradeorg/freqtrade:develop` and run the bot within that image?

**Comment by hroff-1902** [comment]
do you install python 3.6 through the jonathonf/python-3.6 ppa?

**Comment by phe-sto** [comment]
Hi @xmatthias , @hroff-1902,
The docker is just to show on a fresh Ubuntu system here docker, the packages `python3.6 python3.6-venv python3.6-dev build-essential autoconf libtool pkg-config make wget git` do not install pip.

Yes, install from  jonathonf/python-3.6 ppa.
```
chrichri@chrichri-KPL-W0X:~$ grep .*jonathonf.* /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list.d/jonathonf-ubuntu-python-3_6-bionic.list:deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu bionic main
/etc/apt/sources.list.d/jonathonf-ubuntu-python-3_6-bionic.list:# deb-src http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu bionic main
```

**Comment by hroff-1902** [comment]
> Yes, install from jonathonf/python-3.6 ppa.

Seems to be similar to your case: https://stackoverflow.com/questions/50157653/python3-pip-broken-since-system-update

**Comment by phe-sto** [comment]
`python3.6` package does not install pip, it is normal not to have pip after installation you have a basic python3.6 interpreter. In the stackoverflow a module is missing raisin an ImportError but in the pip library, as the title says, pip (an already existing one) is broken.

**Comment by xmatthias** [comment]
Honestly, i doubt that a new ubuntu installation will require a PPA to install python3.6 (it should be in the default repositories) (but i'll need to verify since i'm not a ubuntu user).

My plan for the `setup.sh` script is to strip it of usefull parts (config creation, ...) and try to get rid of it (or at least get rid of most of it) - there's too many different systems for this to really work flawlessly (we say it's supporting debian, but debian does not have PPA just to name one of the problems).

**Comment by phe-sto** [comment]
Doubting is reasonable, if you want learn more about ubuntu ppa start a docker like I did. You will see there no need to add this ppa to install python3.6.
But the issue here is about freqtrade not ubuntu, you are trying to use pip without installing it, it failed...

**Comment by xmatthias** [comment]
Well first of all, using a docker-container and comparing that to a "real" installation is dangerous, since docker-containers are usually highly reduced versions of a real installation.
Installing from a official .iso does include python3 (3.6, iirc) - while the docker-image you mention does not - so comparing them directly when it comes to "what is pre-installed" is wrong.

Well, as mentioned above, i will try to remove most of the setup.sh script if possible.

In my opinion, it should not be the task of the bot to install python on every possible system, which will be impossible to maintain or test, and (as we see with each issue with this script) is very error-prone.
It has more problems than are known (e.g. it does install python3 from PPA - but can't even reach that step since it first checks if python3 is installed)...

**Comment by Dante2333** [comment]
I made this for my blog, feel free to use it for the site.. I do use setup.sh

```
Setting up freqtrade on Ubuntu 19.04

Login to your server on the newly created user you set up from the root account then proceed as follows:

$ git clone https://github.com/freqtrade/freqtrade
$ cd freqtrade/build_helpers/ta-lib
$ sudo apt install python3-pip wget gcc python3-dev make build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev
$ sudo pip3 install setuptools
$ sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
$ ./configure –prefix=/usr/local
$ make
$ sudo make install
$ cd ~/freqtrade
$ sudo ./setup.sh –install
Press Ctrl+c in order to cancel the installation of python 3.6
It will then proceed to compile and finish installing whatever is required, make sure to say “y” to all installation questions.
$ pip3 install –upgrade pip
$ pip3 install -r requirements.txt
$ sudo pip3 install -e .
Now freqtrade should be ready to go, you can run it by getting into the freqtrade directory and doing
$ freqtrade
Make sure to properly configure config.json, take a look at config_full.json.example to see all possible parameters, check https://www.freqtrade.io for more information.

```
