### ISSUE TITLE
Difference backtest live results (two consecutive buys)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#1971]
## Step 1: Have you search for this issue before posting it?

Yes

  ## Step 3: Describe the problem:

I compare backtest and live differences (5 minute ticker same pair):

If there is a buy signal at 21:00 and the stop loss in reach before 21:05 and the buy signal still exist on the next candle (at 21:05) then the bot will buy 2 times in live  (that's expected behavior).

But in backtest that is not the case he make only 1 trade at 21:00.

![freqtrade_backtest](https://user-images.githubusercontent.com/2643583/60197629-07574700-9840-11e9-843b-60eb52a19d96.png)
![freq_trade_live](https://user-images.githubusercontent.com/2643583/60197630-07574700-9840-11e9-906c-ca6f6abc3d02.png)

Have a nice day.

**Comment by xmatthias** [comment]
yes - but i doubt there is much we can do about this, since we won't know the exact close-time during backtesting, so we'll use close (actually next candle open i think).

This blocks this pair for for that duration (of two candles, the 21:00 and 21:05 candles in this case) - which will result in the backtest not buying again at 21:05.

There is actually another thing in this backtest which could be interpreted as misalignment, which is that your strategy buys at 21:00:05, and sells at 21:00:18 (seconds later) - but backtest shows a duration of 5m (buy at 21:00, sell at 21:05).

I guess the asumption during backtesting is that you always hold at least one candle. I'll need to think about this since i'm not sure what would need to change to facilitate what you are suggesting.

**Comment by gaugau3000** [comment]
@xmatthias oki the idea was just to show the difference with a limit use case : about the solution i don't know (maybe just explicit backtest rules/usecase in documentation  : for example if i have roi and stop loss possible on the same candle it takes the worst or the better scenario ?)

Many tks.

I hope one day i can help better in this project than just open issues :-)

**Comment by xmatthias** [comment]
Testing (and especially reporting!) is a big part of contributing - everyone has his own ideas - which shows new issues, so please keep going :+1:

**Comment by xmatthias** [comment]
I hope you're happy to help me test this (you seem to have a strategy / case where this is happening).

If the below fix solves the issue i'll try to come up with a testcase covering this (but for now, i think it's easier/quicker to run the above backtest again if you don't mind

please move this line (Line 359 in backtesting.py) to line 385 (careful with intentation, it should not be part of the if/else statement, but come after (see below))

https://github.com/freqtrade/freqtrade/blob/086d690df76e85bb1205a5037e73a9eae96a7fdd/freqtrade/optimize/backtesting.py#L359

https://github.com/freqtrade/freqtrade/blob/086d690df76e85bb1205a5037e73a9eae96a7fdd/freqtrade/optimize/backtesting.py#L379-L387


``` python
                if trade_entry:
                    lock_pair_until[pair] = trade_entry.close_time
                    trades.append(trade_entry)
                else:
                    # Set lock_pair_until to end of testing period if trade could not be closed
                    lock_pair_until[pair] = end_date.datetime

                indexes[pair] += 1
            # Move time one configured time_interval ahead.
            tmp += timedelta(minutes=self.ticker_interval_mins)
```

**Comment by gianlup** [comment]
At a first glance I don't think this is the correct way to fix to the problem. If we move `indexes[pair] += 1` down to line 385 and a pair has `row.buy == 0 or row.sell == 1` condition true it will be stuck at the same index all the time.

From what I understand the problem is in the line (with `process_only_new_candles=1`): https://github.com/freqtrade/freqtrade/blob/175fc8591e1d6619f891b4136c7adae106272125/freqtrade/freqtradebot.py#L290 because we return and the loop over `whitelist` was not completed. This causes all the following pairs to not have set the value for `_last_candle_seen_per_pair`.

Same as #1850

**Comment by xmatthias** [comment]
the line you think the error lies in is not called in backtesting (nothing from that file is) ...

**Comment by gianlup** [comment]
>It's not related to #1850, #1904 in my opinion

Well yes I read too fast the issue and I thought that gaugao3000 was referring to the same candle instead of the next. My bad

Said this, I think there is a problem only in dry run/live (1850, 1904). In backtest we don't know what happens intra-candle.

I try to explain my point of view:

With `process_only_new_candles=1` I expect that **all** buy signals are evaluated only when a new candle come and I don't want a delayed buy. Example:

timeframe: 2h max_open_trades=1, new candle at 12:00 and there are 2 buy signals: ETH/BTC and LTC/BTC. Few seconds and ETH is bought. At 12:45 SL is reached and the bot sells. After few seconds it buys LTC, but this buy is 45 min late (and in my view this shouldn't happen). This is also true with max_open_trades>1.

With `process_only_new_candles=0` I think we have multiple options:

- let the bot re-buy the same pair multiple times during a candle - like now
- exclude from whitelist only pairs already bought in this candle 
- exclude all pairs to avoid delayed buys

**Comment by xmatthias** [comment]
let's be careful here - this issue has **nothing** to do with `process_only_new_candles`, so i would rather not mix this in here since it creates nothing than confusion.

The issue, as you reported it, is as follows:
bot buys at 21:00, sells intracandle of 21:00 in live/dry, can (and did) buy again at 21:05.
bot buys at 21:00, sells at 21:05 in backtesting. This prevents the bot from buying again at 21:05 - and is therefore misaligned.

The problem is because during backtesting, roi/stoploss is not evaluated for the 21:00 candle, but only for the 21:05 candle (always assuming candle-open times). This is because the index is moved +1 before passing the data to the sell-evaluation function. This was my (half-hearted, since i didn't think it through) attempt to have you test this for me.

I still stand by that, so i still think that this would fix it (including the fix to my solution you identified).

**Comment by gianlup** [comment]
At the moment I don't have a situation like this, so I can't test. I'll check in the future if it should happen. Maybe gaugau3000 can test.

Proposal: instead of adding `indexes[pair] += 1` three times after every `continue` change
```
trade_entry = self._get_sell_trade_entry(pair, row, ticker[pair][indexes[pair]:],
                                                         trade_count_lock, args)
to

trade_entry = self._get_sell_trade_entry(pair, row, ticker[pair][indexes[pair]-1:],
                                                         trade_count_lock, args)
```
___

I have updated my previous comment to avoid confusion and commented on the correct issue.

**Comment by xmatthias** [comment]
yes, that should also work (and has the same effect).

**Comment by gaugau3000** [comment]
@xmatthias @gianlup 
Many tks i will test next week and come back to you.

**Comment by gaugau3000** [comment]
Hi,

By moving (with the last develop branch from 357 to 384)

> indexes[pair] += 1 

I don't have any trades in the backtest.

and 

> trade_entry = self._get_sell_trade_entry(pair, row, ticker[pair][indexes[pair]:],
>                                                          trade_count_lock, args)
> to
> 
> trade_entry = self._get_sell_trade_entry(pair, row, ticker[pair][indexes[pair]-1:],
>                                                          trade_count_lock, args)

work.

Have a nive day.

**Comment by xmatthias** [comment]
Thanks for confirming (sorry, forgot about this issue)...

#2096 will implement what we discussed above. I've also added some tests so we are sure we're not regressing in the future.
