### ISSUE TITLE
If Count is X, X-1 forcebuy wont work over telegram

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1985]
## Step 1: Have you search for this issue before posting it?

yes

## Step 2: Describe your environment

  * Python Version: 3.7
  * CCXT version: latest
  * Branch: Master
  * Last Commit ID: 2019.6
  
## Step 3: Describe the problem:

I'm trying to forcebuy the last remaining balance of my account, stake amount = "unlimited"; count is 4 of 5

### Steps to reproduce:

1. Say X is max amount of orders, if you have X-1 counts, you cant forcebuy last remaining, exchange is binance.
  
### Observed Results:

  * What happened?
It didnt buy after forcebuying, had to sell something then forcebuy again
  * What did you expect to happen?
that it worked properly and bought remaining amount.

### Relevant code exceptions or logs:

  ```
2019-06-29 15:48:44,757 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 370, in create_order
    amount, rate, params)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 694, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1193, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/rpc/telegram.py", line 433, in _forcebuy
    self._rpc_forcebuy(pair, price)
  File "/home/dante/freqtrade/freqtrade/rpc/rpc.py", line 432, in _rpc_forcebuy
    if self._freqtrade.execute_buy(pair, stakeamount, price):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 350, in execute_buy
    time_in_force=time_in_force)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 399, in buy
    return self.create_order(pair, ordertype, 'buy', amount, rate, params)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 374, in create_order
    f'Insufficient funds to create {ordertype} {side} order on market {pair}.'
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
  ```

**Comment by xmatthias** [comment]
Honestly this is nothing to do with max_trades - but with your account balance:
`ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action`.

`/forcebuy xxx` will buy one time stake_amount. 
Assuming stake is 1 ETH - but you only have 0.8 left on your balance, it will NOT buy for 0.8, but will try to buy for 1 ETH and fail (as it did in your case).

This could also be the reason why the last slot was open (or the strategy didn't see a buy opportunity - can't determine that.

**Comment by Dante2333** [comment]
i did have a massive amount of balance available, i'm using "unlimited".

**Comment by xmatthias** [comment]
Well ccxt / the exchange said otherwise ...

**Comment by Dante2333** [comment]
Yes, unlimited as stake amount, sadly I do not have those logs anymore.

**Comment by Dante2333** [comment]
I think I know the issue
Stake amount is not dynamic, as balance is used up it wont take the last remaining amount of base left to purchase last position but try to buy with the last stake amount used in the last trade, therefore trade will fail. Is this the expected behavior @xmatthias ?

**Comment by xmatthias** [comment]
i'm not sure i understand what you mean ... 

Unlimited uses `available_amount / (self.config['max_open_trades'] - open_trades)` ...

`available_amount` is calculatd based on the `free` balance returned from the exchange.

So stake-amount is dynamic ... based on what you have available.

This is refreshed in each iteration (output: `Wallets synced.`) - Which should happen quite often (actually each time something happened on the exchange).

**Comment by Dante2333** [comment]
ok, so going from what you say, it means that we should always have balance available; On my errors I had max_open_trades - 1 open, and had a sizable chunk of money available to trade, but it seems that it was not possible for freqtrade to grasp how much was it to then use it; this error should be really easy to reproduce as I put the instructions above.

**Comment by xmatthias** [comment]
> this error should be really easy to reproduce as I put the instructions above.

no it is not... and the instructions are not clear whatsoever.

I'll need a few more answers to try and recreate this - since i cannot reproduce it for now.

* did you run across this again? (if yes, we'll need all available logs...)
* what is the order-type used for buys? limit or market?
* Did you specify a rate at which to buy the asset?  e.g. `/forcebuy <asset> 0.001`
* how long before these errors was the previous trade action (buy or sell) - before this error happened? 
I suspect it could be related to #1986 ... which is a race condition which would appear if a trade action (buy or sell) happened right before /forcebuy - and would list open_trades wrongly.

`available_balance` is updated from the wallet on the exchange before doing the trade - so the available balance should be uptodate.


> i did have a massive amount of balance available, i'm using "unlimited".

"massive" is wrong by definition ... if you're using "unlimited", then the bot will split all available balance into the buckets.
assume you have 1000$ in your account.

Then each of the first 4 trades would open with a stake of 200$ - leaving 200$ left for the last trade.
If 200$ seems "massive" or not is not relevant - the bot will try to buy with these 200$.

Now depending on the pair and rate, it is possible that `symbol_price_prec()` causes this - since it'll round price up to the next "tradeable price" - which is either nothing, or 1 pip.

However since that will greatly depend on the questions above (it's not even called for market orders), we'll need these informations to debug this further.
