### ISSUE TITLE
"No module named 'freqtrade'" error should be addressed in the FAQ

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1990]
This is one of the most asked questions by the novice users. It should be covered in the FAQ docs.

I mean an error similar to:

``` bash
$ python3 freqtrade -c config.json
Traceback (most recent call last):
 File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "freqtrade/__main__.py", line 9, in <module>
   from freqtrade import main
ModuleNotFoundError: No module named 'freqtrade'
```

In my environment (Ubuntu), setting `export PYTHONPATH=.:$PYTHONPATH` helps. In Windows, there is an analog -- just set PYTHONPATH env. var in the System Variables so that it point to the path where Freqtrade is installed.

@xmatthias If you have another recipe, please offer. At least, this should be covered in the FAQ.

**Comment by xmatthias** [comment]
I think we should change the documentation to use the freqtrade "binary" entrypoint, and don't run it as `python3 freqtrade`.

I'm honestly not sure who changed it to `python3 freqtrade -c config.json` (probably me ...) but thinking about that it's wrong, since this syntax is correct to run scripts (but freqtrade is no script, but a module / package / binary).

We can either run it as module (`python3 -m freqtrade -c config.json`) - or as standalone executable (`freqtrade -c config.json`).

Both methods work the same (courtesy of `setup.py` magic / `__main.py`) - but i prefer the standalone version as it does not decide which python3 to use (i may have python3.6 and python3.7 available, so `python3` may point to either one of them).

so instead of using `python3 freqtrade -c config.json` - you use `freqtrade -c config.json`.

This does 2 things:
a) it makes sure freqtrade is installed correctly, since the binary has been generated
b) it looks nicer / shorter

Hope this makes sense

**Comment by hroff-1902** [comment]
#2004 if fine, but it does not contain the "No module named 'freqtrade'" string. People experiencing this problem won't find this in the FAQ.

**Comment by xmatthias** [comment]
No it does not - but the "no module named freqtrade" problem only happens because the documentation shows them the wrong way to start the bot (`python freqtrade` - which runs the folder - not the installed version of the Bot).
