### ISSUE TITLE
backtesting timerange

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2028]
`backtesting --timerange` is not gathering data from that period, (-200 in 15m is using the last 62 days.)

**Comment by xmatthias** [comment]
i suspect you have a problem with your data in that case.
-200 uses the last 200 entries it has - not necessarily now - 200 "timeframes" ...

I would honestly suggest to use "dated" timeranges (20190101-20190201) instead of using just "entry" values - since this will give you "whatever" and is not reproducible since it'll change each time you update your data.

I was thinking about retiring / deprecating the "-100" and "100-" options for this reason...

**Comment by gitgitgat** [comment]
ok, it is working again
