### ISSUE TITLE
using Bittrex - DDoSProtection error

### ISSUE THREAD

**Issue by whatTHEh3ll** [freqtrade/freqtrade#2038]
When I run freqtrade with bittrex I get a bunch of html code as output. Examples include. It's much to large to replicate here. I ran freqtrade with output to a text file. How can I fix these this?

 "Could not load ticker history due to DDoSProtection. Message: bittrex https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=fiveMin&marketName=BTC-VIB GET 429"

2019-07-06 17:23:39,731 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to DDoSProtection. Message: bittrex https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=fiveMin&marketName=BTC-VIB GET 429 <!DOCTYPE html>

 <html class="no-js" lang="en-US">

**Comment by whatTHEh3ll** [comment]
Is this normal?

**Comment by hroff-1902** [comment]
> Is this normal?

Yes, since 

1) 429 means you was temporary banned by exchange for many number of requests. Try to increase rateLimit. 

2) Noisy html messages -- this is the way the ccxt library reports us of the problems. See https://github.com/ccxt/ccxt/pull/5461. I'll leave this open for a while because I'm going to verify if something was changed in ccxt regarding reporting, the https://github.com/ccxt/ccxt/pull/5470 mentioned there was already merged into master ccxt branch...

**Comment by hroff-1902** [comment]
2. (Noisy messages) -- not yet, appropriate enhancement is not ready in the ccxt yet.

**Comment by whatTHEh3ll** [comment]
What do you mean when you say increase rate limit? Most of my knowledge comes from the Udemy course on Freqtrade. They might have covered this but I don't remember. I need to take a more in depth python course

**Comment by hroff-1902** [comment]
> What do you mean when you say increase rate limit? 

See https://www.freqtrade.io/en/latest/configuration/#sample-exchange-configuration. RateLimit.

**Comment by hroff-1902** [comment]
Closing the issue since it was answered.
Feel free to reopen it.
