### ISSUE TITLE
Install with Conda TA-Lib conflict with python 3.6

### ISSUE THREAD

**Issue by jraviotta** [freqtrade/freqtrade#2041]
I'm working on a method to install freqtrade with Conda as that is my preferred environment/package management tool.

TA-Lib is a bottleneck but quantopian supports a package on [conda-forge](https://anaconda.org/Quantopian/ta-lib). Unfortunately it is pinned to python <3.6.
Freqtrade requires python >=3.6 but is able to install TA-lib manually in `setup.sh`. I can do the same in my `Makefile` but the version conflict suggests that there may be some unexpected bugs introduced by end-running the version check.

Can you offer any clarity about the freqtrade version requirements? Is there any way to reduce the dependence to python <3.6?

**Comment by xmatthias** [comment]
freqtrade uses typehints almost everywhere which were introduced in 3.6 - so that is definitely not an option unless you want to manually go through every line and remove them (which you'll need to repeat for every update). 

You should also be carefull with the conda-forge package - it's outdated - 0.4.9, while the current version on pypi is 0.4.17 - so AT LEAST 8 bugs (counting one bug per version number, but probably there were more) were fixed between then and now.

Also, using conda does not mean you cannot use pip - you can install some packages through conda, and others (like ta-lib) with pip (which is also documented for freqtrade as part of the [raspbian](https://www.freqtrade.io/en/latest/installation/#raspberry-pi-raspbian) installation).

installing ta-lib manually (the c dependency) and through pip is definitely your best solution. we cannot offer much support for problems with other install methods.

**Comment by hroff-1902** [comment]
Even just theoretically, it's only possible to downgrade back to python 3.5 (previous versions are not supported already). And the end-of-life for python 3.5 is scheduled for 2019-09. Just an year... I guess it does not worth it.

**Comment by jraviotta** [comment]
Thanks a bunch for the thorough response. It sounds like scripting a solution is my best bet. I'll also look into the raspbian documentation as you suggested. Since freqtrade is on pypi, I can include it in my conda environment.yml file, but the install fails because the TA-Lib c libraries are not installed and all the packaged options have dependency conflicts. Similarly, the TA-Lib wrapper on Pypi is easy to include in environment.yml, but expects the c libraries to be available. I think that if I can work through the TA-lib install, the rest should work. It's just so nice to be able to build everything from a spec list.

**Comment by hroff-1902** [comment]
just to be correct:
end-of-life for python 3.5 is 2020-09, not 2019-09, I mistyped it above...

**Comment by xmatthias** [comment]
> freqtrade is on pypi

don't use that please.
It's outdated (and did never work correctly) if installed from pypi. we still have a few issues to clean out before the pypi install method is ready.

**Comment by hroff-1902** [comment]
Impossible (we have pandas as a dependency):

```
What’s new in 0.25.0 (July 18, 2019)
...
Warning The minimum supported Python version will be bumped to 3.6 in a future release.
```
So, no way to downgrade to python 3.5 even if we would like to do this.

**Comment by jraviotta** [comment]
I successfully installed the bot into a conda environment. :)

All of my installation logic is contained in a Makefile. I would be happy to send a pr for review. But this does add another option for configuration that may or may not be useful to the community. If you think that supporting a conda install is worthwhile, than I can help to integrate the new feature into the existing `setup.sh` or possibly streamline the initial config some. As pointed out by some of the issues I've reviewed, the multiple installation options are useful but can be confusing. I'm sure maintaining the documentation is also a headache. Your thoughts?

**Comment by xmatthias** [comment]
if you can share it (either here (use tripple `) or via PR) we can decide...

i'm no fan of `setup.sh` personally (it seems to fail every other time...) - so having an option to replace it with would be great ...

**Comment by hroff-1902** [comment]
Why in the makefile, not a script?

**Comment by xmatthias** [comment]
personal preference i guess ... everyone uses what he's most comfortable with

**Comment by jraviotta** [comment]
> personal preference i guess ... everyone uses what he's most comfortable with

Two reasons; first because it's what I learned and am more comfortable implementing. Second, because I use a Makefile to capture verbose docker commands. When I was using the Windows before WSL, I had more luck with keeping things compatible staying out of the shell.

For example:
`make docker-app` really executes
```make
## Build App container
docker-app: build-docker-app
build-docker-app: setup-create
	@docker build -t $(APP_CONTAINER) -f $(APP_DOCKERFILE) .

## Start app  
start-docker-app:
ifeq ($(OSFLAG), OSX)
	@docker run --rm -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` \
		-d -it --name $(APP_CONTAINER) \
		$(DOCKER_MOUNTS)\
		$(APP_CONTAINER) $(START_ARGS)
else 
	@docker run -it --rm -d --name $(APP_CONTAINER) \
		--mount type=bind,source=$(DOCKER_MOUNT_CONFIG_PATH)/localtime,target=/etc/localtime,readonly \
		$(DOCKER_MOUNTS)\
		$(APP_CONTAINER) $(START_ARGS)
endif
```

**Comment by hroff-1902** [comment]
> It's outdated (and did never work correctly) if installed from pypi

Ehm, why?

**Comment by xmatthias** [comment]
because we cannot use it from there ATM (see #1384), since most things assume user_data is in cwd(), relative to the installation / code.

I'm working on that issue so i hope we're able to use pypi soonish (i even have that ready - so the pypi version is from myself - it's just not working as it should).

**Comment by xmatthias** [comment]
i guess #2049 does fix this (thanks for contributing! :+1: )

Feel free to reopen if you feel otherwise
