### ISSUE TITLE
Hyperopts and backtesting different results.

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2051]
I'm on the latest version of freqtrade. HyperOpts and Backtesting have different results. The vary widely, results in backtesting are usually 4x less than the proposed strategy by hyperopts for same time period.

**Comment by hroff-1902** [comment]
what `whereis freqtrade` command says?

**Comment by gitgitgat** [comment]
whereis: 
`/home/user/.conda/envs/freqtrade/bin/freqtrade`

--version: 
`freqtrade 2019.6-dev`

**Comment by hroff-1902** [comment]
@xmatthias I see freqtrade lacks the build number in its version.

Is it possible to add? Like `2019.6-dev-38495` (some increasing number) or simply `2019.6-dev-20190727` (the date), `2019.6-dev-20190727T1810` (the datetime), or `2019-6.dev-9d57b` (last commit)...

In this case I suppose @gitgitgat has an older version of freqtrade installed in conda (while in the current dir he has an up-to-date one), also 2019.6-dev, but dated before --eps and --dmmp were adjusted for hyperopt. How can we see it? No way...

**Comment by gitgitgat** [comment]
--eps and --dmmp do give different results in hyperopts.

**Comment by gitgitgat** [comment]
so you suggest making a new environment and installing freqtrade in the new conda env?

**Comment by hroff-1902** [comment]
@gitgitgat As I probably told, I'm not familiar with conda at all. Never used it and do not know anything about its features and internals... That's why I asked you to open this issue, maybe @xmatthias or someone else help us clean up your configuration. I can only see that while freqtrade in your current dir is up-to-date, the installed binary points to another location, which probably contains older version and this is the reason of the deviations in results you experience... Try to call freqtrade as `python3 -m freqtrade <command>`, it should use the up-to-date instance from the current dir.

**Comment by xmatthias** [comment]
well `whereis` (or `which`) will give you the path to the executable, which is normally in the `../bin` path of the virtual environment. (even though i installed mine with `pip install -e .` - it'll show up as 

This is the same with conda environments (assuming you activated it using `conda activate freqtrade`.

The only thing you should make sure is to always have the same venv active when doing something with the bot (run, install, update, ...).

If you're not sure, it may be best to start a new virtual environment (either through venv, or conda environments) and install everything again.

**Comment by xmatthias** [comment]
According to what i read on slack, this issue seems now fixed.

Feel free to reopen if i'm wrong and you still have this issue.
