### ISSUE TITLE
Hyperopts --live backtesting with old data

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2052]
backtesting --live does backtesting from the 30th of April. Isn't meant to be live testing from now until it stops?

**Comment by xmatthias** [comment]
No, the start-date will depend on the ticker-interval used.

`--live` uses the last 500 (ish) candles from the current time. 
Backtesting will never run from "now" until it stops, but always use historic data - that's running the bot regularily and setting "dry_run" to true.


This again, is a option i don't see having much sense (you always want to backtest more than 500 candles). 
@hroff-1902 - comments on removing `--live` (it's misleading by name - and does not make much sense since backtesting 500 candles only will rarely make sense).

**Comment by hroff-1902** [comment]
I think we can actually mark `--live` as deprecated, right.

Say, add a deprecation warning and keep the current behaviour right now, then in, say, 3 months leave deprecation warning and quit, and then after 3 months remove the option.

**Comment by gitgitgat** [comment]
okay, what about something like `freqtrade start dry-run`? Can that be used? If I want to test a strategy with live data for about 5-7 days for example.

**Comment by xmatthias** [comment]
no, you'll need to change it in the configuration - and then run `freqtrade --config config-dry.json` ... Note that this mode does not require exchange keys - (but you can control the bot via telegram if necessary).

**Comment by hroff-1902** [comment]
wait a minute, are we talking about dry run or about backtesting?

**Comment by gitgitgat** [comment]
hmm, a bit of both, it could start with backtesting the 1 week prior to the current date and then leae the bot open for about 1 week in dry run mode, or straight from current date to dry run.
