### ISSUE TITLE
plot_dataframe.py

### ISSUE THREAD

**Issue by blinklabllp** [freqtrade/freqtrade#2081]
## Step 1: Have you search for this issue before posting it?

Couldn't find similar issue, so starting a new issue.

## Step 2: Describe your environment

  * Python Version: Python 3.6.8
  * CCXT version: ccxt==1.18.992
  * Branch: Master 
  * Last Commit ID: b8713a515e960f1ffadcf1c7ee62c4bee80b506c
  
## Step 3: Describe the problem:
Unable to plot my backtest results.

*Explain the problem you have encountered*
Executing the following command results in error.
Error
### Steps to reproduce:

`
        Command: python3 scripts/plot_dataframe.py -s EMACrossHTF1h --export 
        EMACrossHTF1h_results.json -p BTC/USDT --datadir user_data/data/binance/
`
  
### Observed Results:

Error is thrown. 

### Relevant code exceptions or logs:
`
          File "scripts/plot_dataframe.py", line 113, in <module>
            main(sys.argv[1:])
          File "scripts/plot_dataframe.py", line 107, in main
            plot_parse_args(sysargv)
          File "scripts/plot_dataframe.py", line 58, in analyse_and_plot_pairs
            plot_elements = init_plotscript(config)
          File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 57, in init_plotscript
            trades = load_trades(config)
          File "/home/ubuntu/freqtrade/freqtrade/data/btanalysis.py", line 113, in load_trades
            return load_backtest_data(Path(config["exportfilename"]))
          File "/home/ubuntu/freqtrade/freqtrade/data/btanalysis.py", line 33, in load_backtest_data
            raise ValueError("File {filename} does not exist.")
        ValueError: File {filename} does not exist.
`

**Comment by xmatthias** [comment]
it's a syntax error i think ...

you'll need `python3 scripts/plot_dataframe.py -s EMACrossHTF1h --export trades --export-filename EMACrossHTF1h_results.json -p BTC/USDT --datadir user_data/data/binance/`

--export does not take a filename - hence the filename uses the default, which you did apparently not use

**Comment by Kaidokuni** [comment]
Hi I have the same issue, after backtesting a strategy I tried different things to see the data result (to see on a graph when the bot have take a position)  but in the end the same line appear "ValueError: File {filename} does not exist.". I will put the command line and the return below.
Does anyone know how to fix this?

`(base) C:\Users\john\freqtrade>python scripts/plot_dataframe.py --export-filename user_data/backtest_data/backtest-result.json -p LTC/BTC

2019-08-04 12:29:05,136 - freqtrade.loggers - INFO - Verbosity set to 0
2019-08-04 12:29:05,136 - freqtrade.configuration.configuration - INFO - Dry run is enabled
...
...
2019-08-04 12:29:05,152 - freqtrade.data.history - INFO - Using local backtesting data ...
Traceback (most recent call last):
  File "scripts/plot_dataframe.py", line 114, in <module>
    main(sys.argv[1:])
  File "scripts/plot_dataframe.py", line 108, in main
    plot_parse_args(sysargv)
  File "scripts/plot_dataframe.py", line 58, in analyse_and_plot_pairs
    plot_elements = init_plotscript(config)
  File "c:\users\john\freqtrade\freqtrade\plot\plotting.py", line 57, in init_plotscript
    trades = load_trades(config)
  File "c:\users\john\freqtrade\freqtrade\data\btanalysis.py", line 114, in load_trades
    return load_backtest_data(Path(config["exportfilename"]))
  File "c:\users\john\freqtrade\freqtrade\data\btanalysis.py", line 33, in load_backtest_data
    raise ValueError("File {filename} does not exist.")
ValueError: File {filename} does not exist.

(base) C:\Users\john\freqtrade>python scripts/plot_dataframe.py -s FSTRAT -p LTC/BTC --datadir user_data/data/binance
...
...
2019-08-04 12:31:24,704 - freqtrade.data.history - INFO - Using local backtesting data ...
Traceback (most recent call last):
  File "scripts/plot_dataframe.py", line 114, in <module>
    main(sys.argv[1:])
  File "scripts/plot_dataframe.py", line 108, in main
    plot_parse_args(sysargv)
  File "scripts/plot_dataframe.py", line 58, in analyse_and_plot_pairs
    plot_elements = init_plotscript(config)
  File "c:\users\john\freqtrade\freqtrade\plot\plotting.py", line 57, in init_plotscript
    trades = load_trades(config)
  File "c:\users\john\freqtrade\freqtrade\data\btanalysis.py", line 114, in load_trades
    return load_backtest_data(Path(config["exportfilename"]))
  File "c:\users\john\freqtrade\freqtrade\data\btanalysis.py", line 33, in load_backtest_data
    raise ValueError("File {filename} does not exist.")
ValueError: File {filename} does not exist. `

**Comment by xmatthias** [comment]
@Kaidokuni 
The error is that the file you have in the argument, `--export-filename user_data/backtest_data/backtest-result.json`, does not exist.

Did you run backtesting with `--export trades --export-filename user_data/backtest_data/backtest-result.json` ? otherwise this file will not have been written.

**Comment by OtenMoten** [comment]
> @Kaidokuni
> The error is that the file you have in the argument, `--export-filename user_data/backtest_data/backtest-result.json`, does not exist.
> 
> Did you run backtesting with `--export trades --export-filename user_data/backtest_data/backtest-result.json` ? otherwise this file will not have been written.

Hello dear @xmatthias,

I've tried to `(.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json -s BBRSI  backtesting --export trades --export-filename user_data/backtest/backtest-result.json` and the error is still the same:

`FileNotFoundError: [Errno 2] No such file or directory: 'user_data/backtest/backtest-result.json'`

What to do to get the backtest-result.json to be generated?

Refer my issue [here ](https://github.com/MontrealTradingGroup/freqtrade/issues/6)

**Comment by OtenMoten** [comment]
Hell yeah,

I've got a workaround. In the previous post there was a little mistake from me - nvm.

From the beginning:

1. I've struggle with lection [34. Backtesting Strategy & Plotting result](https://www.udemy.com/course/algorithmic-trading-in-python/learn/lecture/13495168#overview) because there is a deviation between the tutorial and reality on Ubuntu machine.

2. Everything else from the tutorial on Udemy was closely perfect.

3. For you all I've gathered all the informations from the video AND the MontrealTradingGroup Github-Repository:

wget https://raw.githubusercontent.com/MontrealTradingGroup/deployPython3VM/master/python-pip3.sh 
sh python-pip3.sh 
pip3 install virtualenv --user 
mkdir .env 
virtualenv .env/freqtrade 
source .env/freqtrade/bin/activate 
(.env) mtg@mtgvb:~/$ deactivate 
sudo apt-get install git 
git clone https://github.com/MontrealTradingGroup/freqtrade.git 
cd freqtrade 
sudo apt-get install make build-essential python3-dev 
git checkout develop 
sh ./install_ta-lib.sh 
./setup.sh --install 
source .env/bin/activate 
(.env) mtg@mtgvb:~/freqtrade$ pip install numpy 
(.env) mtg@mtgvb:~/freqtrade$ pip install -e . 
(.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json
(.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json -s BBRSI  backtesting --export trades --export-filename user_data/backtest_data/backtest-result.json
(.env) mtg@mtgvb:~/freqtrade$ python3 ./scripts/plot_dataframe.py -s BBRSI ADA/BTC

Then it works!

The clue is to get the `backtest-result.json` to be generated. The comment I found here from @xmatthias `python3.6 ./freqtrade/main.py -c config.json -s BBRSI  backtesting --export trades --export-filename user_data/backtest_data/backtest-result.json` is sovling the issue.

Thanks all for helping. 

Maximal profits to you all.

**Comment by xmatthias** [comment]
@OtenMoten Glad that you found a solution, and thanks for sharing since others may find this solution too.

a few Notes: 
None of the developers or contributors to treqtrade were involved in building the Udemy course - and no one from the team did take the course as far as i know.

using `python3 ./scripts/plot_dataframe.py -s BBRSI ADA/BTC` is  no longer working in newer versions of freqtrade, and that the course uses a older (over 1 year old) version of freqtrade which i would not recommend using in production since a TON of things changed.

It's good to grasp the basics, and i fully understand that it cannot be kept uptodate with the project.
Due to this however, the documentation will not be accurate for the version you get from the course.

For the command you're running: 
with an uptodate version of freqtrade, the new syntax is `freqtrade plot-dataframe.py -s BBRSI ADA/BTC`.

**Comment by OtenMoten** [comment]
EDIT:

If somebody got this error:

`ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory`

This is my work around: 

[SOURCE]
1. http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
2. https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz

```
wget [SOURCE]
tar -xzf ta-lib-0.4.0-src.tar.gz
cd ta-lib/
./configure --prefix=/usr
make
sudo make install
pip install numpy
```

If you don't have it installed
`pip install TA-Lib `

If you do have it installed
`pip install --upgrade --force-reinstall TA-Lib`

[Got from here ](https://stackoverflow.com/questions/45406361/importerror-libta-lib-so-0-cannot-open-shared-object-file-no-such-file-or-dir)

**Comment by xmatthias** [comment]
well - or use [the instructions in the [docs](https://www.freqtrade.io/en/latest/installation/#1-install-ta-lib) - which are somewhat similar :smile:

**Comment by nathanrhoda** [comment]
> Hell yeah,
> 
> I've got a workaround. In the previous post there was a little mistake from me - nvm.
> 
> From the beginning:
> 
> 1. I've struggle with lection [34. Backtesting Strategy & Plotting result](https://www.udemy.com/course/algorithmic-trading-in-python/learn/lecture/13495168#overview) because there is a deviation between the tutorial and reality on Ubuntu machine.
> 2. Everything else from the tutorial on Udemy was closely perfect.
> 3. For you all I've gathered all the informations from the video AND the MontrealTradingGroup Github-Repository:
> 
> ```
> wget https://raw.githubusercontent.com/MontrealTradingGroup/deployPython3VM/master/python-pip3.sh 
> sh python-pip3.sh 
> pip3 install virtualenv --user 
> mkdir .env 
> virtualenv .env/freqtrade 
> source .env/freqtrade/bin/activate 
> (.env) mtg@mtgvb:~/$ deactivate 
> sudo apt-get install git 
> git clone https://github.com/MontrealTradingGroup/freqtrade.git 
> cd freqtrade 
> sudo apt-get install make build-essential python3-dev 
> git checkout develop 
> sh ./install_ta-lib.sh 
> ./setup.sh --install 
> source .env/bin/activate 
> (.env) mtg@mtgvb:~/freqtrade$ pip install numpy 
> (.env) mtg@mtgvb:~/freqtrade$ pip install -e . 
> (.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json
> (.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json -s BBRSI  backtesting --export trades --export-filename user_data/backtest_data/backtest-result.json
> (.env) mtg@mtgvb:~/freqtrade$ python3 ./scripts/plot_dataframe.py -s BBRSI ADA/BTC
> ```
> 
> Then it works!
> 
> The clue is to get the `backtest-result.json` to be generated. The comment I found here from @xmatthias `python3.6 ./freqtrade/main.py -c config.json -s BBRSI backtesting --export trades --export-filename user_data/backtest_data/backtest-result.json` is sovling the issue.
> 
> Thanks all for helping.
> 
> Maximal profits to you all.
> 
> EDIT:
> 
> If somebody got this error:
> 
> `ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory`
> 
> This is my work around:
> 
> [SOURCE]
> 
> 1. http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
> 2. https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
> 
> ```
> wget [SOURCE]
> tar -xzf ta-lib-0.4.0-src.tar.gz
> cd ta-lib/
> ./configure --prefix=/usr
> make
> sudo make install
> pip install numpy
> ```
> 
> If you don't have it installed
> `pip install TA-Lib `
> 
> If you do have it installed
> `pip install --upgrade --force-reinstall TA-Lib`
> 
> [Got from here ](https://stackoverflow.com/questions/45406361/importerror-libta-lib-so-0-cannot-open-shared-object-file-no-such-file-or-dir)

Much appreciated guys. @OtenMoten  this saved me from throwing my laptop out the window :) 1 small thing missing on last line the  "(.env) mtg@mtgvb:~/freqtrade$ python3 ./scripts/plot_dataframe.py -s BBRSI ADA/BTC"

Just the -p @ the end. I think you meant to type 
"(.env) mtg@mtgvb:~/freqtrade$ python3 ./scripts/plot_dataframe.py -s BBRSI -p ADA/BTC"
