### ISSUE TITLE
Data processing and analysis feature

### ISSUE THREAD

**Issue by jraviotta** [freqtrade/freqtrade#2088]
### As a freqtrade quant, I want to use freqtrade to develop and test hypotheses about market dynamics so that I can implement more effective strategies.

- [ ] Easily import data from multiple exchanges
- [ ] Collect data into a persistent database without retrieving the same data twice
- [ ] Easily interact with stored data in interactive environment
- [ ] Interact with the project in a jupyter notebook

**Comment by jraviotta** [comment]
What do you think of this feature request? I started working on the new class `DataCLI` to capture the plumbing for this. Feel free to assign to me if you like the idea.

**Comment by hroff-1902** [comment]
I guess all this is already exist in the project (maybe you just do not know of some features -- that's probably the lack of documentation in some aspects):

1. `./scripts/download_backtest_data.py --exchange <yourexchange> -t <yourtimeframe> --days <days>`
That's it. This script will become a subcommand of the main freqtrade pretty soon.

2. Why do you need a DB and the `user_data/data/` dir does not suffice you as a persistent store?

3. Please take a look at an example using `load_pair_history()` interactively in that your Jupyter/notebook at https://www.freqtrade.io/en/latest/data-analysis/#strategy-development-problem-analysis (added this morning)...

4. Same as 3.

**Comment by xmatthias** [comment]
Honestly, i think you should have a look at the [documentation](https://www.freqtrade.io/en/latest/data-analysis/).

Most of what you ask is available 
* download data for multiple exchanges: `scripts/download_backtest_data.py`
* load downloaded data (into a interactive environment):  [documentation for exactly this](https://www.freqtrade.io/en/latest/data-analysis/).

^ actually covers points 2-4.
I don't understand the need for a new class, since all of it is already available.

**Comment by jraviotta** [comment]
> 1. `./scripts/download_backtest_data.py --exchange <yourexchange> -t <yourtimeframe> --days <days>`
>    That's it. This script will become a subcommand of the main freqtrade pretty soon.
>    Iterate through multiple exchanges, timeframes, etc.

Yes I did see this script. Seems like it should be promoted to a freqtrade command which was the reason I thought of a new `DataCli` class rather than running scripts. Glad it is getting promoted. Is there an issue that tracks this effort?

The objective is something like:
```
>>>freqtrade update-data --all

for exchange in EXCHANGE_LIST:
        for all pairs in PAIRS_LIST:
            fetch all new trades

>>>freqtrade aggregate-candles --pairs-list --timeframes 1m

for exchanges in EXCHANGE_LIST:
    do some logic that builds a dataset of combined data across exchanges

>>>freqtrade some-other-useful-common-data-transformation --max-prediction

for all my data:
    generate a new dataset in real time

>>>freqtrade --strategy new-strategy-using-transformed-data --max-profit
```

> Why do you need a DB and the user_data/data/ dir does not suffice you as a persistent store?

Ideally, I want everything I can get from every exchange, not just candles. Collecting this information is more complex than flat files could handle. Also, it seems that pulling data retrieves prior data twice without checking if it has already been retrieved. That means that if exchanges limit the available history, backtests and data can only be performed over the available window and not the full history since listing. At a minimum, there should be logic to merge existing history with new history so data is not lost and so that retrieval time can be minimized.

> 3. Please take a look at an example using load_pair_history() ...

This is perfect and satisfies the last 2 items in the request. As you noted, the information was just added this morning.

You are correct that some of this functionality is already available, but it's not as polished as the backtesting or bot feature. The focus of this request is to make collecting and aggregating data more fluid so that I can generate hypotheses and then develop strategies. Presently, freqtrade is one-dimensional in it's capacity and that does not lead to much edge in strategy development. Every quant can use TA-lib on candles, so there's not much value to be gained in a world where whales have more sophisticated bots than the rest of us.

As with my other request, I'm pushing the boundaries, so if this use is not helpful to the community, I'm happy to work it out on my own locally. But I'm also willing to work on features that move the project forward in line with the maintainers' vision. Feel free to redirect my efforts elsewhere if you already have plans in mind. I took a look on the project boards and didn't see tasks that addressed this use-case. Perhaps I overlooked it, or your plans are embedded in other objectives. Just point me in the right direction.

**Comment by xmatthias** [comment]
> I want everything I can get from every exchange

Exchanges will not give you any other historic information ... :-( 
most even limit ohlcv data to a month or 2 (or 1000 candles) - except binance (and maybe others i did not try yet), which has information back until 2017 for pairs already listed there...

Ideally, we'd have orderbook data (or at least tick data) - but that's not available from any crypto exchange i know, which is very unfortunate.


>   Also, it seems that pulling data retrieves prior data twice without checking if it has already been retrieved. That means that if exchanges limit the available history, backtests and data can only be performed over the available window and not the full history since listing. At a minimum, there should be logic to merge existing history with new history so data is not lost and so that retrieval time can be minimized.

this is not true, it checks the available data and starts at the last candle it has.
example:
you have data for all of february - and want to download data for february-april - so the script will download only data March-April.
The script will however throw away if you download January-April - since it only checks start-date (which however i don't see as a big issue, ~~since my time-machine is currently broken~~ since we normally download newer data, not older ...)

### boards:

To be honest, the boards are not well maintained, most newer issues are missing from there (i added a few this morning - but surely not all).
They were an idea we had about a year ago - but i am tempted to remove them completely, since the gain/cost ratio does not match (it takes a lot of time to maintain them, which is better spent working on the issues).


I think the most problematic point we have is documentation in this regard - most of what you ask is available in some form - but it's not exposed through documentation, so most users won't know unless they read through the sourcecode.

**Comment by jraviotta** [comment]
Ok. I can help with documentation then. I'll figure out how to work that out.

**Comment by hroff-1902** [comment]
Jonathan, you can help reviewing the installation scripts and installation procedure in the whole, for example...

When I installed freqtrade first time (on Ubuntu), I was forced to pull my shamanic tambourine from the shelf and the only configuration I was able to run was freqtrade in the Docker container...

**Comment by jraviotta** [comment]
> Jonathan, you could help reviewing the installation scripts and installation procedure in the whole, for example...
> 
> When I installed freqtrade first time (on Ubuntu), I was forced to pull my shamanic tambourine from the shelf and the only configuration I was able to run was freqtrade in the Docker container...

Will do. I assume edits are done through pull requests? Thanks for the direction.

**Comment by xmatthias** [comment]
> I assume edits are done through pull requests

Yes, both master and develop are locked for pushes for everyone, this way we try to make sure that only code is introduced which at least one person had a look at other than the author.

**Comment by hroff-1902** [comment]
> > Jonathan, you could help reviewing the installation scripts and installation procedure in the whole, for example...
> > When I installed freqtrade first time (on Ubuntu), I was forced to pull my shamanic tambourine from the shelf and the only configuration I was able to run was freqtrade in the Docker container...
> 
> Will do. I assume edits are done through pull requests? Thanks for the direction.

See #2087 as a potential starting points... Other open and closed issues related to installation are marked with the 'install' label.

**Comment by jraviotta** [comment]
Here's another idea.

I want to connect to https://p.nomics.com/cryptocurrency-bitcoin-api as my data feed, so that my bot is not limited to 1min candles from one exchange.

**Comment by xmatthias** [comment]
is it integrated in ccxt? 

if not, then i think it's out of scope for freqtrade - since we cannot maintain the api for multiple exchanges ourselfs (we used to do that in the past, and it did not work out well).
