### ISSUE TITLE
Kraken: Historical data limited to 720 candles 

### ISSUE THREAD

**Issue by Saber1998** [freqtrade/freqtrade#2134]
Attempting to utilize the Kraken exchange and would like to perform backtests but I am unable to pull data going back further than 5 days at 1h candles.

**Comment by xmatthias** [comment]
The issue is best explained here: [kraken-support-trade-data](https://support.kraken.com/hc/en-us/articles/218198197-How-to-pull-all-trade-data-using-the-Kraken-REST-API)

starting with https://github.com/ccxt/ccxt/issues/5677 (for kraken) - we should be able to utilize trade-level data to gather historic candle data.
