### ISSUE TITLE
unable to use /forcesell with stoplimit on exchange

### ISSUE THREAD

**Issue by il-katta** [freqtrade/freqtrade#2193]
* Operating system: docker on linux
  * Python Version: 3.7.3
  * CCXT version: 1.18.992
  * Branch: Master
  * Last Commit ID: 0d9d23a888d1189a6c9b6e6d453d0aee08183724
  
When a stoplimit order is present on exchange /forcesell command cause this errror message:
```
WARNING - Stoploss order was cancelled, but unable to recreate one: Insufficient funds to create stop_loss_limit
```

### Result:

the coin is sold but the order remains unclosed on the database

**Comment by il-katta** [comment]
```
Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
```

**Comment by xmatthias** [comment]
The fixing PR for this is #2177 , so if you upgrade to develop, this issue should be gone.

Note that we'll also do a release shortly, so maybe wait a day or two and it'll be fixed in master.

You can also close the trade manually in the database [helper queries](https://www.freqtrade.io/en/latest/sql_cheatsheet/)

**Comment by xmatthias** [comment]
Please update to version 2019.8 (released just now).

That will fix this issue.
