### ISSUE TITLE
support the configuration of slippage for backtest/hyperopts

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2223]
idea :
As a trader
i want to configure a slippage when i test a strategy that deal with low volume or xxx/btc that have low decimals digits of precision 
so that the backtest look closer to live and the objective function take slippage into account for optimization

i can write test case if needed to exchange the how to.

have a nice day.

**Comment by hroff-1902** [comment]
> i can write test case if needed to exchange the how to.

Yes, please.

It can be as simple as subtracting some slippage percent from the profit of each trade.
Then the slippage percent should simply be added to the config, this is easiest part.

**Comment by xmatthias** [comment]
you call it slippage - but in theory, a simple `--fee` parameter would accomplish the same (i wanted to add this anyway, as it will allow complete offline backtesting / hyperopting) (which i would have needed during my last flight ...).

currently, we use what the exchange gives us (0.0025 IIRC - for binance).

By using 0.0030 instead of 0.0025, you would have added a 5% slippage ... or am i seeing this wrong / too simple?
