### ISSUE TITLE
Remove unfulfilled orders

### ISSUE THREAD

**Issue by shusso** [freqtrade/freqtrade#229]
If an order is not fulfilled remove it 
- manually
- automatically

From issues #66 #144 #153

**Comment by seansan** [comment]
Was this fixed?

**Comment by glonlas** [comment]
This is fixed now, unfulfilled orders will timeout and removed. Use the param `unfilledtimeout` in your config.
**Doc:** https://github.com/gcarq/freqtrade/blob/develop/docs/configuration.md#bot-commands

**Comment by pan-long** [comment]
I don't think this is fixed for partially fulfilled order.

1. For partially unfulfilled buy order, it cancels the order, but it didn't use filled amount, which result in insufficient fund every time it tries to sell it.
2. There is no solution for partially fulfilled sell order yet.

For 1, it's easier to solve, after canceling the order, use the filled amount instead of amount in trading.

For 2, we might need to introduce multiple orders tied to one trade.
