### ISSUE TITLE
"Whitelist is empty" message is misleading

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2295]
Why i have these messages in the log file ?

2019-09-23 18:01:25,681 - freqtrade.freqtradebot - WARNING - Whitelist is empty.
2019-09-23 18:01:25,681 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...

I have running in edge mode. It is running fine with testing but in reality it does not.
I have whitelist defined in the config file. I even created user_data/data/bittrex/pairs.json file.
Also the commands /edge and /whitelist does not show anything at bot chat:

/edge
Edge only validated following pairs: (no pairs listed)
/whitelist
Using whitelist StaticPairList with 0 pairs

Is this normal behaviour or some kind of bug ?
I am using latest git on debian 10 everything up to date.
freqtrade -c config.json edge is running correctly showing the pairs
listed in the file.
but running
freqtrade -c config.json (edge enabled) shows my whitelist empty...

Can someone confirm (test) this ?

**Comment by xmatthias** [comment]
With edge, this can happen and depends heavily on your strategy.

Assuming that your strategy works as expected, then maybe the market in the last X days was not in a way to allow any profitable trades - so edge will empty the whitelist until this situation changes (which will probably take a bit - since it's using `calculate_since_number_of_days` of history, and tries to reach `minimum_expectancy`).

Especially this parameter is important: [minimum_expectancy](https://www.freqtrade.io/en/latest/edge/#minimum_expectancy) - since it's probably the one emptying your whitelist. try lowering it and you should have more pairs (but understand the implications first by reading through the whole edge documentation).

**Comment by sanitariu** [comment]
Ok so we can close this may be. It will work as expected.
Just this message "freqtrade.freqtradebot - WARNING - Whitelist is empty." is misleading me and typing /whitelist in telegram after pairs refreshment is empty. This confused me so i thought it will never trade because it has no whitelist pairs.

**Comment by hroff-1902** [comment]
Let's rename it to '"Whitelist is empty" message is misleading' and leave open?

**Comment by sanitariu** [comment]
Ok :)
Maybe in edge mode
First line is ok
2019-09-23 23:58:29,133 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...

But this one should be ignored and not printed. This should be fixed in telegram bot too.
2019-09-23 23:58:34,132 - freqtrade.freqtradebot - WARNING - Whitelist is empty.

**Comment by hroff-1902** [comment]
Not completely.
This info message is useful, it gives information about the internal state of the bot.
However, the term 'whitelist' used there and in other places is, as you said, a bit misleading for the end-user since it's not that whitelist defined by the user in the config, but the derived out, the list of active pairs.

This should be discussed and agreed, but my opinion is that all appearences of the 'whitelist' term in the code, log messages and the docs should be verified and a better term (probably 'list of active pairs') should then be used instead. While 'whitelist' should only be applicable to the content of the whitelist from the config.

**Comment by xmatthias** [comment]
well what's printed is the "active whitelist" - which is the list the bot is using to trade - and it's technically empty at this point.

Maybe printing "Active whitelist empty" would make more sense - but i wouldn't introduce conditional log messages based on edge or not - that will complicate things unnecessarily...

**Comment by xmatthias** [comment]
Fixed in #2332 - which improves this message.

**Comment by hroff-1902** [comment]
@sanitariu please compare the new logging message, it was adjusted.
