### ISSUE TITLE
Disable negative sells

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#2300]
Is it possible to disable all negative sells (for any possible mode) when  part of trades were open as trailing  ?

**Comment by xmatthias** [comment]
It's not clear what types of sells you're having a problem with, since there are multiple ways the bot can sell in both negative and positive profit-ranges.

for sell-signals - you can use `sell_profit_only`
If you want to apply trailing stoploss only once the positive offset is reached, then use `trailing_only_offset_is_reached` [documentation](https://www.freqtrade.io/en/latest/stoploss/#custom-positive-loss)

You should not deactivate stoploss completely, since that will put 100% of your capital at risk, so in the end, you'll probably still have "some" negative sells at the initial stoploss value (unless you have a perfect buy-signal).

if it's something else, please specify more details ...

**Comment by hroff-1902** [comment]
I did not get it.

**Comment by vpotap** [comment]
I have experimented with multiple config , yes there are multiple ways bot can sell - negative/positive , i will check sell_profit_only flag i suppose it was activated before , the idea was how is possible globally disable all negative sell (overwrite trailing logic sell and other and etc), with one flag overwrite and disable any negative sells..

**Comment by xmatthias** [comment]
in short - you cannot - and it's also really desirable to avoid all negative sells. Assume the current market - you would not want the bot to stay in the position when it's going downhill fast, but you'll accept the (stop)loss and come back another day or time (or probably week - in the current case).

you need to understand the different options you're using (trailing-stop, sell-flag...) and enable or disable them accordingly.

The 2 flags pointed out above will do what you want for trailing stop and sell-signal - but stoploss will ALWAYS sell - and it's good that way (although you can set it to `-1` - and have that disabled, but i'd strongly advise against that).

**Comment by hroff-1902** [comment]
Why not? It's possible: set `use_sell_signal: false` (or `sell_profit_only: true`) and `stoploss=-0.999` and you'l never reach it...

**Comment by xmatthias** [comment]
but there is no 1 flag you can flip to allow this... 
also your settings depend on `trailing_stop` and `trailing_only_offset_is_reached` settings... :)

**Comment by xmatthias** [comment]
Going to close this since i think the question was answered.

Feel free to reopen if you think otherwise.
