### ISSUE TITLE
Proper installation of Freqtrade on vps

### ISSUE THREAD

**Issue by hanswayne23** [freqtrade/freqtrade#2302]
## Step 1: Hav?
Proper instllation of Freqtrade on vps?
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: __LInux__
  * Python Version: _3,6____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
Installation of freqtrade on vps
*Explain the problem you have encountered*
I did a lot of procedure/guide on how to install freqtrade on digitalocean vps but i still encountered a lot of error?
Kindly needed help!!!
### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
you'll need to point out which errors you encountered (ideally with logs / outputs) for us to be able to help you.

**Comment by hanswayne23** [comment]
DigitalOcean Droplets
Linux 18.04 LTS

update and upgrade of python3

sudo apt update
sudo apt -y upgrade

python3 -v

install pip

sudo apt install -y python3-pip

pip3 install numpy

install additional tools

sudo apt install build-essential libssl-dev libffi-dev python3-dev

install venv

sudo apt install -y python3-venv

create virtual environment

python3.6 -m venv .env

activate virtual environment

source my_env/bin/activate

Installation of freqtrade
git clone https://github.com/gcarq/freqtrade && cd freqtrade && ./setup.sh --install

Running setup.py install for pycparser... done
Running setup.py install for idna-ssl... done
Running setup.py install for SQLA1chemy... done
Running setup.py install for future... done
Running setup.py install for tornado... done
Running setup.py install for wrapt... done
Running setup.py install for pyrsistent... done
Running setup.py install for TA-Lib... /

when it comes to running TA-Lib is already freezing.

To be honest i dont know if my procedure is right to install all packages for freqtrade.

My apologies im really a newbie on algorithmic trading and freqtrade

**Comment by hanswayne23** [comment]
By the way version of python3 3.6.8

**Comment by sanitariu** [comment]
Try python 3.7

**Comment by hroff-1902** [comment]
Our documentation (https://www.freqtrade.io/en/latest/installation/#prerequisite) says:
```
Requirements¶
Python >= 3.6.x
pip
git
virtualenv (Recommended)
TA-Lib (install instructions below)
```
-- you installed all but TA-Lib.

Follow instructions here: https://www.freqtrade.io/en/latest/installation/#1-install-ta-lib

**Comment by xmatthias** [comment]
How big is the droplet? 

`/setup.sh --install` does install ta-lib, however it fails if <2G of memory is available - hence the min requirement in the [readme.md](https://github.com/freqtrade/freqtrade#min-hardware-required).
Also, it will probably not freeze, but take a while since it needs to build the ta-lib c component (on single CPU systems this can take an hour or more ...).

you can circumvent that to some extend by using prebuild docker images [documentation](https://www.freqtrade.io/en/latest/docker/).

**Comment by hanswayne23** [comment]
> Try python 3.7. I did install on PI but only way to work for me is with python 3.7. So i upgraded to buster and everything working during the install as your description.

I installed it on my raspberry pi 4 and it was a success. but still on executing?

Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade'.
pi@raspberrypi:~/freqtrade $ nano ./config.json
pi@raspberrypi:~/freqtrade $ nano ./config.json
pi@raspberrypi:~/freqtrade $ nano ./config.json
pi@raspberrypi:~/freqtrade $ ource .env/bin/activate; python3 freqtrade/main.py
bash: ource: command not found
Traceback (most recent call last):
  File "freqtrade/main.py", line 16, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'
pi@raspberrypi:~/freqtrade $ source .env/bin/activate; python3 freqtrade/main.py
Traceback (most recent call last):
  File "freqtrade/main.py", line 16, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

Kindly need help on this one....

**Comment by hroff-1902** [comment]
@xmatthias installation.md still contains instruction to run freqtrade via main.py

**Comment by hroff-1902** [comment]
> You can now use the bot by executing 'source .env/bin/activate; freqtrade'.

@hanswayne23 try to run it with this command

**Comment by sanitariu** [comment]
Hello,
you have a type error "ource .env/bin/activate; python3 freqtrade/main.py"
Just do:
1. source .env/bin/activate;
2. freqtrade -c config.json

**Comment by hanswayne23** [comment]
Thanks for all your reply.

i tried: source .env/bin/activate; freqtrade

and also

source .env/bin/activate;
freqtrade -c config.json

both resulted to: bash: freqtrade: command not found

**Comment by hanswayne23** [comment]
kindly i would like to know if i need to learn programming language from scratch in order for me to succeed on how to use freqtrade? 

so far its been really a struggle. i've been trying to install it properly for almost two months now plus having difficulty to execute it.

thanks in advance... :)

**Comment by xmatthias** [comment]
programming is not necessary, but you'll benefit from some basic skills during the development of your own strategies.

### For installation:
The list of commands you listed above ( https://github.com/freqtrade/freqtrade/issues/2302#issuecomment-535275295) are a mess, and it's surely not documented this way.

If you executed it this way, then you 2 virtual environments - `.env`  and  `my_env`.
Freqtrade should be installed in `my_env` (if you executed all commands like this) - but based on the last comments you're activating .env - which you created but did not install anything to.

Now our documentation does not contain any reference to `my_env` - so if you follow the instructions *correctly*, the installation will be easy.

I would suggest to follow the "simple" instruction [here](https://www.freqtrade.io/en/latest/installation/#easy-installation-linux-script).
 quick summary:

```bash 
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
bash ./setup.sh --install
```

The last step may take a while since it'll download and install all dependencies. 

Follow the instructions within this - it'll install all dependencies and freqtrade itself within the correct virtual environment (`.env`), so all you need to do after this is run

``` bash
source .env/bin/activate
freqtrade --version
```

**Comment by hanswayne23** [comment]
> programming is not necessary, but you'll benefit from some basic skills during the development of your own strategies.
> 
> ### For installation:
> The list of commands you listed above ( [#2302 (comment)](https://github.com/freqtrade/freqtrade/issues/2302#issuecomment-535275295)) are a mess, and it's surely not documented this way.
> 
> If you executed it this way, then you 2 virtual environments - `.env` and `my_env`.
> Freqtrade should be installed in `my_env` (if you executed all commands like this) - but based on the last comments you're activating .env - which you created but did not install anything to.
> 
> Now our documentation does not contain any reference to `my_env` - so if you follow the instructions _correctly_, the installation will be easy.
> 
> I would suggest to follow the "simple" instruction [here](https://www.freqtrade.io/en/latest/installation/#easy-installation-linux-script).
> quick summary:
> 
> ```shell
> git clone https://github.com/freqtrade/freqtrade.git
> cd freqtrade
> bash ./setup.sh --install
> ```
> 
> The last step may take a while since it'll download and install all dependencies.
> 
> Follow the instructions within this - it'll install all dependencies and freqtrade itself within the correct virtual environment (`.env`), so all you need to do after this is run
> 
> ```shell
> source .env/bin/activate
> freqtrade --version
> ```
> 
> Obviously, you'll need to activate the virtual environment each time you run freqtrade, since it's available only within this virtual environment.

Thank you for this simple installation of Freqtrade for raspberry pi.

I followed your guide to install freqtrade:

First - git clone https://github.com/freqtrade/freqtrade.git

Second - cd freqtrade

Third - bash ./setup.sh --install

The installation of freqtrade finished but when is started to run

source .env/bin/activate
freqtrade --version

Still the problem exist specially bash: freqtrade: command not found again

Raspberry Pi raspbian verison
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by xmatthias** [comment]
I'm sorry, are is this now about installing this on a raspberry??

I thought the issue is about installing freqtrade on a digitalocean VPS, and the instruction above is for exactly that.

Please provide the full output of `bash setup.sh --install` - so we can see where it might go wrong... (i've never used the install-script on a raspberry ...).

**Comment by hroff-1902** [comment]
@hanswayne23 we need output from `./setup.sh --install` command you made

**Comment by hanswayne23** [comment]
Vps Droplet: 2Gb 2CPU 3TB transfer

I installed and followed your guide to install freqtrade:

First - git clone https://github.com/freqtrade/freqtrade.git

Second - cd freqtrade

Third - bash ./setup.sh --install

attached is the snapshot of the installion error on digitalocean vps.

![vps error](https://user-images.githubusercontent.com/55561332/66012392-8d4af400-e4f9-11e9-8bb5-efe223c2911b.jpg)

**Comment by xmatthias** [comment]
Are we now back on a VPS? 
I'm sorry, but i am not sure what / where you are trying to install - and errors / experiences may differ between a VPS and a Raspberry, so i think you should decide on one, and keep the issue focused on ONE type of installation. otherwise you'll get conflicting answers, which will not work in the end.

Well the error is "rather" easy, and has nothing to do with freqtrade, but with the environment. A quick google search for "ubuntu 18.04 python3 pip" reveals:

Run the following 2 commands, and then run setup.py again.
```
$ sudo apt update
$ sudo apt install python3-pip
```

**Comment by hanswayne23** [comment]
My apologies to all the confusion. My focus is the problem setting up freqtrade on digitalocean vps.

I already installed freqtrade on digitalocean vps.

![install final](https://user-images.githubusercontent.com/55561332/66186805-d051c680-e6b5-11e9-88fa-2e0ab6e7a5b0.jpg)

should i open new thread for how to setup freqtrade on raspberry pi? or i can do it in this thread?

Also kindly i would like to ask if i can ask helped about running the commands on how to start the bot freqtrade in this same thread?
or i will open a new thread for this one? details link below
https://www.freqtrade.io/en/latest/bot-usage/

again thank you for guiding me on how to install freqtrade in digitalocean vps,

Really appreciate it!!! :)

**Comment by xmatthias** [comment]
we have a current issue about raspberry installation #2328 - however i've verified this week - the installation instruction is uptodate, it simply needs patience since the raspberry is low-powered, and compiling C-dependencies on a single core machine does take time.

> Also kindly i would like to ask if i can ask helped about running the commands on how to start the bot freqtrade in this same thread?

Best first read the documentation, all commands are explained there. If you still have questions, feel free to open issues to ask them, or even better, if it's just some questions, join our [Slack channel](https://join.slack.com/t/highfrequencybot/shared_invite/enQtNjU5ODcwNjI1MDU3LTU1MTgxMjkzNmYxNWE1MDEzYzQ3YmU4N2MwZjUyNjJjODRkMDVkNjg4YTAyZGYzYzlhOTZiMTE4ZjQ4YzM0OGE) and ask there.
