### ISSUE TITLE
backtesting and timeranges - startup timerange

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#2311]
Signals that require X candles don't work as expected when timeranges are specified because the available data is limited to the timerange, both in timeframes and date notations (?)
This can cause wrong signals at the start of the timerange until enough data is available
a workaround is to add a guard to avoid signals if there aren't X ranges (but I think this effectly just prevents backtesting...)
This can skew hyperopt results since subsequent epochs might go the wrong way depending on how much the wrong signals affect the overall strategy

**Comment by xmatthias** [comment]
yes, strategies will require startup time - but it's impossible to determine this automatically, since even if the column is called `ema20`, it could be a typo and contain `ema200` ...
It's an oddity when you try to exactly recreate a trading day - but normally not a problem for backtesting or hyperopt if the exact time of the first trade is not 100% important.

i thought we have something around this in the documentation too, but currently struggle to find it (maybe it was just me repeating it in the slack channel multiple times which makes me think this ...)

### To explain why it's not a problem

most common indicators that have startup time "don't" start up - so they remain empty (`NaN`) for the startup time  - making all comparisons to evaluate to False automatically, preventing buy signals.

very quick example:

``` python
dataframe['ema8'] = ta.EMA(dataframe, timeperiod=8)
dataframe['ema13'] = ta.EMA(dataframe, timeperiod=13)
dataframe['x'] = dataframe['ema8'] < dataframe['ema13']
dataframe['y'] = dataframe['ema8'] > dataframe['ema13']
dataframe['equal'] = dataframe['ema8'] == dataframe['ema13']

dataframe.head(20)
```
We're comparing for >, < and equality. 

![2019-09-27-203617_1116x756_scrot](https://user-images.githubusercontent.com/5024695/65793578-7a859780-e166-11e9-85cc-498e4b5c8cdc.png)

As you can see - until both ema8 and ema13 did "start up", not one element results to True (NaN != NaN). 
This means that you'll also have no buys in this timerange.

I would not know any indicator that works differently (it may depend on the implementation ...), but maybe you have an example of a common indicator that behaves differently?

To prove the NaN point:

``` python
import numpy as np
np.NaN == np.NaN

False
```

**Comment by hroff-1902** [comment]
I'll think of it in more details, but I also thought of similar -- an ability to specify the 'startup' period for indicators, during which they are unstable and may produce false results for backtesting. This period should first be added (prepended) to the backtesting timerange, all indicators calculated, and then the data for this 'startup period' should simply be removed or ignored by backtesting.

Of course "it's impossible to determine this automatically", this should be an attribute for the custom strategy to be set by the user.

**Comment by hroff-1902** [comment]
"This means that you'll also have no buys in this timerange." -- but what if you should?

**Comment by xmatthias** [comment]
adding an attribute is easy, but introduces other problems.

### main problem

I'm curious how you plan on solving the following (i don't know how), since if we cannot solve it, implementing it makes no sense to me.

say you specify `startup=200` - 200 candles. 
Assuming i have data from 20190101 - and i specify `--timeframe 20190101-` - so i would expect data to be loaded from `20190101 - 200 candles` - which depending on the timeframe is sometime in 20181231 (or earlier).

Now i don't have this data, but my data starts at 20190101, making it impossible to fulfill the "startup period". 
Would you then move this startup period to the beginning of the startup time?

### 2nd caveat
I can now specify `--timeframe 20190101-` - but my backtest data starts a month later (20190201). Backtesting will warn about this per pair, and start backtesting from this date, since this is what's available from a data perspective.

Again, same question as above - how would you plan on handling that?

### impossible solution

Failing / exiting is not an option in my opinion, since i could specify `--timeframe 20190101-` and have data for 90% of the pairs starting from this timerange, but one pair only started trading in April. 
Failing if data at the beginning is missing is not possible, since that would force me to either
a) backtest starting from April 
b) force me to remove this new pair
- both options are not acceptable options in my opinion, since it's realistic to have new pairs listed at a later date.

**Comment by orehunt** [comment]
I think the goal is to make sure live run and backtesting behave in the same way. Not to prevent backtesting to run if there aren't enough candles. If you don't have data in backtesting because a pair is not available for a timerange then it wouldn't have data at that time anyway, so both live and backtesting will give same results.
Any pair that doesn't have the number of required candles should simply be temporarily blacklisted until it does. (I think this shouldn't even be a setting, just fixed behaviour)

I haven't looked if the 500 candles number for live is configurable or not, but either way it should be the same for backtesting so the setting should be replicated.

_Comparing against NaN will always give false so it's not an issue fails_...is wrong for negations:
```python
~(X > NaN) == True
``` 
but it can also be:
```python 
~(X > Y) == True
```

Thinking about missing data for pairs, there are already warnings for when data is not available, maybe they could be colored like:
`RED: data is missing because hasn't been downloaded`
`YELLOW: data is missing because pair wasn't available at that time`

**Comment by xmatthias** [comment]
well, also `~(True) == False` ... but why negate if you can invert the sign to `<`?

> I haven't looked if the 500 candles number for live is configurable or not, but either way it should be the same for backtesting so the setting should be replicated.

this is simply wrong, you have 500 candles for live - but the bot may generate correct signals after 20 candles in both live and backtesting.
By requiring 500 candles, you will create the same problem you have, but the other way around, where you specify a start-date, we load 500 candles before that date - so the first possible buy is not at `20190101`, but at 20191231 20:05:00 ...

**Comment by orehunt** [comment]
> well, also `~(True) == False` ... but why negate if you can invert the sign to `<`?

It is easier to reason about a collection of events not happening than to negate many, do you think this is an antipattern?

> By requiring 500 candles, you will create the same problem you have, but the other way around, where you specify a start-date, we load 500 candles before that date - so the first possible buy is not at `20190101`, but at 20191231 20:05:00 ...

This would be a lesser evil imo, because you would have less signals, not bad ones, so at worst the strategy would come out as less profitable. 
Anyway the only solution is to expose the number of used candles (which are mirrored between live and backtesting) to the user.

**Comment by xmatthias** [comment]
> Anyway the only solution is to expose the number of used candles (which are mirrored between live and backtesting) to the user.

i'm not sure what you mean with this ...
when you use sma200, you know that you need 200 startup candles - so this is exposed to the user since the user decided this in the first place.

**Comment by hroff-1902** [comment]
> when you use sma200, you know that you need 200 startup candles

You know. And your customs strategy knows. But freqtrade does not.

First, is live/dry trading. Now we use default length for data, fetched from the exchange. 500 candles is default for both binance and bittrex, right? Assume we add support for an exchange where the default frame is only 100 candles. In this case, a strategy including SMA200 will simply fail. There should be an attribute in the strategy class requesting the needed length of the dataframe for all of the indicators used in the strategy so that all of them will be at the end of the dataframe series 1) calculable (non producing NaNs) 2) stable (out of their instable 'startup' period, which may be longer.

Second, is backtesting. For the same reasons, many indicators at the beginning of the timerange's dataframe are 1) not calculable, producing NaNs, 2) in their period of instability, with incorrect data (though non NaNs). The comparisons and other calculations made for those bars at the beginning of the timerange may produce errorneous signals, with errors of both Type 1 and Type 2. In order to mitigate this instability and errorneous backtesting results, some amount of candles (which can be defined by the same strategy attribute, which is mentioned above) may be added (prepended) to the beginning of the timerange, the extended set of data downloaded and later loaded into backtesting, the calculations of the indicators (and probably buy/sell signals, but this is a TBD point) started from the beginning of that extended timerange, and finally that leading addendum to the backtesting timerange should simply be dropped in order to produce backtesting results for exactly same timerange that was requested by the user.

@orehunt It's a good enhancement, I'll probably try to implement it when the time allows...

**Comment by xmatthias** [comment]
> Assume we add support for an exchange where the default frame is only 100 candles.

Honestly, if an exchange only gives you 100 candles i would exclude it (or at least not actively support it) just because of that - 100 is not enough data for any medium term trend detection ...

> In order to mitigate this instability and errorneous backtesting results, some amount of candles (which can be defined by the same strategy attribute, which is mentioned above) may be added (prepended) to the beginning of the timerange,

How will you handle the problems i pointed out above? That the additional data you're asking for is not available?

Also, data-downloading should be (should remain) strategy independent (normally you'll reuse the same data to test multiple strategies) ...


I did not say it would not be a good enhancement, but i don't think it's as easy as adding an attribute and simply prepending that data.
