### ISSUE TITLE
Can't install freqtrade on raspberry pi 

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#2328]
***# Step 1: Have you searched for this issue before posting it?***

Yes I've been through the installation process multiple times with trying different commands, googling a lot (this defenitely helped) but I'm still stuck at many parts. I have a feeling I'm missing something basic, so I want to start over again, but this time correctly from the beginning.

***# Step 2: Describe your environment***

  **Operating system**: Raspberry Pi model 3 B+ (Raspbian)
  **Python Version:** Python 3.4.3 :: Continuum Analytics, Inc. (`python -V`) (note that I also 
  have python 3.7.3 installed, how do I know? python3.7 -V returns Python 3.7.3)
  **CCXT version:** bash: /home/pi/.local/bin/pip: /home/pi/cryptobot/bin/python3: bad 
  interpreter: No such file or directory
  I googled this one earlier today and got a workaround which worked, it was a temporarily 
  workaround which I would have to do every single time again. I'm not sure why this is 
  because I'm very sure I have pip installed (maybe it can't find the directory or something?).
  (`pip freeze | grep ccxt`)
  
***# Step 3: Describe the problem:***

I'm pretty new to Linux and Raspbian but I've come a long way with installing some very cool projects. However I'm stuck on this project with the installing process on multiple parts.

I'm following this installation guide for the RPI, http://www.freqtrade.io/en/latest/installation/#raspberry-pi-raspbian

Before I can begin the installing process it tells me to install **miniconda3**, I've followed this tutorial on installing it: gist.github.com/simoncos/a7ce35babeaf73f512be24135c0fbafb, I feel like I'm missing some things but the 'conda' command returns me a help-menu so I'm guessing it should be fine. It's version (conda -V): conda 3.16.0 

Now I can start the installing process, first part:
```
conda config --add channels rpi
conda install python=3.6
conda create -n freqtrade python=3.6
conda activate freqtrade
conda install pandas numpy

sudo apt install libffi-dev
python3 -m pip install -r requirements-common.txt
python3 -m pip install -e .
```

Here the errors begin! 
The second command, '**conda install python=3.6**', returns:
Error: Missing write permissions in: /home/pi/miniconda3
```
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/home/pi/miniconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone=/home/pi/miniconda3
```

I've followed what it says and did the command '**conda create -n my_root --clone=/home/pi/miniconda3**', this worked and let me continue the process.

Then the next step where I get an error is, '**conda activate freqtrade**':
Error: 'activate' is not a conda command.
Did you mean "source activate freqtrade" ? 

Which I then did '**source activate freqtrade**' and it worked, I now see (freqtrade) in front of the  pi@raspberry in the command terminal! 

And then the next step where I get an error is the last one, '**python3 -m pip install -e .**':
/home/pi/miniconda3/bin/python3: No module named pip

This is weird again because I sure have installed pip, I've found and tried some workaround and I can remember that it worked for 1 step but gave me multiple errors in the next. So I will just wait until I clear out all the errors in this first part before I continue to common: http://www.freqtrade.io/en/latest/installation/#common in the installation guide.
I actually already tried all these steps but it gets stuck on installing the TA-lib on step 5 (not the step 1 TA-lib). Then step 6 returns that the command 'freqtrade' is not found. I hope anyone can help me out.

**### Steps to reproduce:**

  1. Install miniconda3 using the guide I linked.
  2. Run the first 8 installation commands.
  3. Observe the errors.
  
**### Observed Results:**

  * What happened? I installed all the necessary dependencies before going into the installation process, however it looks like I'm still missing some basic things for this installation to work?
  * What did you expect to happen? I expect to follow the tutorial and run every command without returning an error, or explain me that I have to use something else.

**Comment by xmatthias** [comment]
### miniconda

Based on your miniconda installation error - i think the biggest problme is that the guide you link to (https://gist.github.com/simoncos/a7ce35babeaf73f512be24135c0fbafb) uses sudo to install everything.

This installs miniconda as root - so every command which modifies miniconda will also need to be run as root - which is not default and does not make sense.

Instead, use the following command - by changing the default directory to `/home/pi/miniconda3` - there is no need to run this with sudo / as root.
Make sure to run these commands as user `pi`.
```
wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh
md5sum Miniconda3-latest-Linux-armv7l.sh # (optional) check md5
/bin/bash Miniconda3-latest-Linux-armv7l.sh # -> change default directory to /home/pi/miniconda3
nano /home/pi/.bashrc # -> add: export PATH="/home/pi/miniconda3/bin:$PATH"
# sudo reboot -h now
```


> I actually already tried all these steps but it gets stuck on installing the TA-lib on step 5 (not the step 1 TA-lib). Then step 6 returns that the command 'freqtrade' is not found. I hope anyone can help me out.

It appears like you tried to install freqtrade without conda - which should work as well.
You'll need to make sure that every command is run with python3.7 (not python3.4 - since we use features not supported in anything < python 3.6).

Anyway, since it's running on a raspberry and many packages don't have arm wheels availble, python will need to compile most libraries, which can take a long time.
when i last tried this it took ~24 hours since it needs to compile a ton of C libraries, but this should be improved in the latest develop.

That being said - with the latest develop version it should work in "reasonable" time since it does not install the hyperopt dependencies (scipy and skopt), so maybe it's time to rework the raspberry installation guide.

**Comment by Theagainmen** [comment]
Hey Matthias, thanks for your quick reply!

I did what you said about not running it as sudo and install it on /home/pi/miniconda3, however the installation guide said in the # comment already to do this, so as expected I got returned that it was already installed there! 

> It appears like you tried to install freqtrade without conda - which should work as well.
You'll need to make sure that every command is run with python3.7 (not python3.4 - since we use features not supported in anything < python 3.6).

Ah that's good to know, I might try again making sure to select python 3.7!

> Anyway, since it's running on a raspberry and many packages don't have arm wheels availble, python will need to compile most libraries, which can take a long time.
when i last tried this it took ~24 hours since it needs to compile a ton of C libraries, but this should be improved in the latest develop.

Oh wow, this might explain why my Raspberry Pi gets stuck on installing the TA-lib as I said in my original post, I googled a lot but couldn't find anyone with this issue. I think I have tried this step over 6 times and all the 6 times I unplugged power after an hour/multiple hours because it froze. Maybe it didn't freeze but it was installing the packages?

> so maybe it's time to rework the raspberry installation guide.

I'll keep trying, but with my knowledge an updated version would **really** help me out a lot! For the last few days I've been searching and playing with trading bots and this is the first one that looks really really promising. I love all the open-source configs/strategies and the back-testing options already. Do you think you could fix this in the near feature (1 day - 1 week?). I'd be willing to help you with the testing! You could add me on discord for example if you want.

**Comment by xmatthias** [comment]
>  I think I have tried this step over 6 times and all the 6 times I unplugged power after an hour/multiple hours because it froze. Maybe it didn't freeze but it was installing the packages?

yes it did. 
try using tmux or screen - where you don't have to be connected all the time and you can leave it running / installing. You can also open another session and use "top" or similar to check if it's still processing at 100% (it should since it doesn't really get stuck ...), but simply takes a while...

> You could add me on discord for example if you want.

we use a [slack - click me for invite](https://join.slack.com/t/highfrequencybot/shared_invite/enQtNjU5ODcwNjI1MDU3LTU1MTgxMjkzNmYxNWE1MDEzYzQ3YmU4N2MwZjUyNjJjODRkMDVkNjg4YTAyZGYzYzlhOTZiMTE4ZjQ4YzM0OGE) 

> I'll keep trying, but with my knowledge an updated version would really help me out a lot!

don't get me wrong, the current version is not outdated, and with enough patience it will work. An updated version may be simply to use the "setup.sh" script (or the [common](https://www.freqtrade.io/en/latest/installation/#common) installation section without anything special for raspberry - which however will again require enough patience, since things will need to be compiled.

**Comment by hroff-1902** [comment]
I could take my RPI from the dusty box at the attic to check the installation procedure...

**Comment by Theagainmen** [comment]
I will add you on slack Matthias! What does screen or tmux exactly do? Prevent it from freezing? I tried step 5 one more time this time using python3.7 specifically and it's stuck again, too bad :(.

So with screen or tmux installed this issue should be resolved?

> I could take my RPI from the dusty box at the attic to check the installation procedure...
That'd be amazing @hroff-1902 ! If you know how to install these things and would like to share me how you installed/fixed certain things that are not in the installation process or I might have missed. That would be great.

**Comment by hroff-1902** [comment]
> So with screen or tmux installed this issue should be resolved?

Screen and tmux both keep the terminal session, so if you are doing something which looks 'frozen' remotely, you can close ssh session for the night and next morning open ssh session again, attach to the previous screen/tmux session and look at the results...

**Comment by Theagainmen** [comment]
Thanks hroff, I installed tmux, ran 'tmux' and now I see a green bar in the terminal, is that it? Can't find any documentation or commands online. If so, I will try to run the commands again.

**Comment by Theagainmen** [comment]
Here an image of the terminal with TMUX installed, this is also exactly the point where it gets stuck and I reset it many many times now: https://imgur.com/a/ZeFFRDn

**Comment by sanitariu** [comment]
Its more easy to use screen. Do it like that.
1. apt-get install screen
2. screen
3. source .env/bin/activate;
4. cd freqtrade
5. freqtrade -c config.json
6. press ctrl+a, then press d (to dettach session)
7. later if you want to see whats going on you can check the session with screen -ls command
and use screen -r the_session. You can detach via step 6

I think it will be more easy for you to study screen command or tmux.
The meaning is to leave your session working while you disconnect from the server.

**Comment by sanitariu** [comment]
For PI2 my advice is just to upgrade PI2 to buster so everything works like normal debian.

**Comment by hroff-1902** [comment]
I don't use tmux, I use screen

**Comment by Theagainmen** [comment]
Thanks for all the help and comments! With the TMUX the installation finished in less than 5 minutes, no need for screen I guess? I can run the bot, the command gets recognized finally!
Currently it's just spamming 'no buy signals' but I can't wait to set it all up. When I'm stuck again with something I'll let it know, maybe tomorrow when I try to open the bot I'm stuck again. Also off-topic question, but can I change the telegram bot messages?

**Comment by hroff-1902** [comment]
> Thanks for all the help and comments! With the TMUX the installation finished in less than 5 minutes, no need for screen I guess? I can run the bot, the command gets recognized finally!
> Currently it's just spamming 'no buy signals' but I can't wait to set it all up, very excited :). When I'm stuck again with something I'll let it know, maybe tomorrow when I try to open the bot I'm stuck again. Also off-topic question, but can I change the telegram bot messages?

Actually, there is no magic in screen/tmux -- these are just terminal multiplexers, that do not help installing packages but allow you to quit and then resume terminal sessions... I guess this time it was simply 5 minutes because lot's of installation work was done during your previous attempts (I assume you have not cleaned the system) and the rest took 5 minutes this time.

You may change telegram messages as well as you are allowed to change anything in the code -- it's open source under the GPL license. But be careful with the changes -- we'll won't support your changed repository. Instead, if you have some suggestions, enhancements/improvements -- create an issue for this like this one or directly a pull request with the changes to the Freqtrade repository (if you have programming skills)

**Comment by xmatthias** [comment]
For our understanding, which method of installing worked for you on the raspberry?

did you follow the Raspberry install with conda - or install it with pure python?

**Comment by hroff-1902** [comment]
Cited description from Slack:

"After I installed TMUX I re-ran step 5 on the installation guide ('python3 -m pip install --upgrade pip' and 'python3 -m pip install -e .'). and simply did instead of python3 -> python3.7 and voilà it installed and worked after that."
