### ISSUE TITLE
Is there any possibility to integrate Pyfolio to analyze backtests

### ISSUE THREAD

**Issue by girmax** [freqtrade/freqtrade#2399]
As of now the backtest results analytics is very limited.  Would be great if such a tool as Pyfolio can be integrated to allow for better analysis https://github.com/quantopian/pyfolio

**Comment by xmatthias** [comment]
Best have a look at the [data analysis documentation](https://www.freqtrade.io/en/latest/strategy_analysis_example/).

It includes samples how to load backtesting results into jupyter notebooks. 
From there, it should just be a question of formatting the dataframe the correct way to be able to use pyfolio.

**Comment by xmatthias** [comment]
Now technically this is not a problem... 

``` python
from pathlib import Path
import pyfolio
from freqtrade.data.btanalysis import load_backtest_data

user_data_dir = Path('user_data')
# Load backtest results
trades_bt = load_backtest_data(user_data_dir / "backtest_results/backtest-result.json")

trades = trades_bt.set_index('open_time')

pyfolio.create_full_tear_sheet(trades['profitabs'])

### Alternatively using daily returns
trades_res = trades.resample('1d').agg({'profitabs': sum})
pyfolio.create_full_tear_sheet(trades_res['profitabs'])
```

However i'm not sure about the accuracy ... pyfolio seems to assume daily returns (it reports 26 months instead of 1 without resampling) - the rest of the plots seem okish though, but i'm not sure if the calculations for all the ratios are correct.

While daily returns can be calculated - i'm not sure about the quality of the output since most trades will happen intraday (at least for my strategies)... 

Also, pyfolio uses `empyrical` under the hood, and according to https://github.com/freqtrade/freqtrade/issues/2407#issuecomment-544870743 it does not calculate drawdown below 0.

For these reasons, I would rather not include this into the official documentation...
