### ISSUE TITLE
Unclear behavior of dynamic pair list

### ISSUE THREAD

**Issue by santiagomalter** [freqtrade/freqtrade#2414]
## Step 1: Have you search for this issue before posting it?
Yes.

## Step 2: Describe your environment

  * Operating system: `macOS 10.14.6`
  * Python Version: `3.6.5`
  * CCXT version: `ccxt==1.18.1180`
  * Branch: `2019.9`
  * Last Commit ID: `6bbc0eefed8e45edb5e2ca48f9e8760551b7a395`
  
## Step 3: Describe the problem:

The underlying logic of the dynamic pair list is unclear, and the doc didn't help with this. (but except this, the doc is fantastic, thanks!)

What I would like to achieve is to use market data to create a dynamic pair list, without any hardcoded whitelist. (only the blacklist)

Pairlist config:
```json
    "pairlist": {
        "method": "VolumePairList",
        "config": {
            "number_assets": 100,
            "sort_key": "quoteVolume",
            "precision_filter": true
        }
    },
```

Since the whitelist parameter is required, I've configured an extensive list of pairs (under the `exchange` node), and I expect the `VolumePairList method` + the `precision_filter` to disable the irrelevant ones, but this isn't straightforward.

1. Is it possible to have no whitelist and to fill it dynamically from market data?

2. I've noticed a few **trades on pairs that weren't whitelisted**.
Is it because the pairs were somehow "cherry-picked" by the `VolumePairList` method?
Then probably the `pair_whitelist` parameter shouldn't be mandatory.
If this isn't the normal behavior, there is a bug that trades outside of the white list.

It seems too big to be a bug, I'm probably missing something, help is appreciated.

**Comment by hroff-1902** [comment]
> and I expect the `VolumePairList method` + the `precision_filter` to disable the irrelevant ones, but this isn't straightforward.

It should disable. Does not it work? Pls describe "isn't straightforward"... 

> Is it possible to have no whitelist and to fill it dynamically from market data?

Pls wait for #1861, this should be there.

> I've noticed a few trades on pairs that weren't whitelisted.
When you wrote "I've configured an extensive list of pairs" I read it as if you've included the list of all pairs with stake currency as quote currency into whitelist, so there shall not be any non-whitelisted pairs.

Could you describe your environment more precisely -- which exchange used, white/black list... What strange pairs you obtain (logs)... So that we could reproduce the behavior.

**Comment by santiagomalter** [comment]
> It should disable. Does not it work? Pls describe "isn't straightforward"...

I meant that the dynamic white list should work without any predefined hardcoded whitelist. (only blacklist)

> Could you describe your environment more precisely -- which exchange used, white/blacklist... What strange pairs you obtain (logs)... So that we could reproduce the behavior.

I'm using Binance. The pair was BCPT/BTC, and it's definitely not in my whitelist. And only BNB/BTC is blacklisted.

My point is: I don't understand why the whitelist is mandatory while its content is dynamically filled or changed. (which is the expected behavior)

**Comment by hroff-1902** [comment]
Yes (I took a look at the code), currently VolumePairList ignores the `whitelist` setting set in the config and starts from all pairs on the ecchange with stake currency as the quote currency.

Yes, as for me, this is strange, not quite correct and only causes questions like this your issue. Dynamic pairlist(s) should start from whitelist in the config if it's set.

This will be addressed as a part of the more generic refactoring (ongoing).

**Comment by xmatthias** [comment]
> My point is: I don't understand why the whitelist is mandatory while its content is dynamically filled or changed. (which is the expected behavior using this config)

The whitelist attribute is mandatory to have in the configuration - but you can leave it empty if you use dynamic_whitelist.

```json
"exchange": {
        "pair_whitelist": [],
        "pair_blacklist": [
            "BNB/BTC"
        ]
}
```
*simplified to only include relevant things*

@hroff-1902  and myself disagree on this topic - for me, Dynamic whitelist should fill the whitelist from **all** available pairs with the correct quote currency based on precision filter and volume, with the number of `number_assets` assets.
(which seems to be what you expect, too).

Adding all pairs on the exchange to the whitelist manually to have DynamicWhitelist then filter on it does not make sense to me - as that is work i can have automated by the bot, since most of the time (almost always) - you'll want to select from all available pairs except for a few ones you don't like and therefore put into the blacklist.

**Comment by santiagomalter** [comment]
> The whitelist attribute is currently mandatory to have in the configuration - but you can leave it empty if you use dynamic_whitelist.

Got it. Actually, I've tried before but I was misled by the logs.

Example with empty `pair_whitelist`:
<pre><code>
2019-10-25 10:48:03,862 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Searching for BTC pairs to buy and sell based on VolumePairList - top 100 volume pairs.'}
<b>(... OK)</b>
2019-10-25 10:48:04,457 - freqtrade.pairlist.IPairList - WARNING - Pair BNB/BTC is not compatible with exchange Binance or contained in your blacklist. Removing it from whitelist..
2019-10-25 10:48:04,457 - freqtrade.pairlist.IPairList - INFO - Ignoring WIN/BTC from whitelist. Market is not active.
2019-10-25 10:48:04,465 - freqtrade.pairlist.IPairList - INFO - Ignoring BSV/BTC from whitelist. Market is not active.
<b>(... OK)</b>
2019-10-25 10:48:04,466 - VolumePairList - INFO - Removed CHZ/BTC from whitelist, because stop price 9.9e-07 would be <= stop limit 9.9e-07
2019-10-25 10:48:04,466 - VolumePairList - INFO - Removed WAVES/BTC from whitelist, because stop price 2e-07 would be <= stop limit 2e-07
2019-10-25 10:48:04,478 - VolumePairList - INFO - Removed ONT/BTC from whitelist, because stop price 2e-07 would be <= stop limit 2e-07
<b>(... OK)</b>
2019-10-25 10:48:04,485 - VolumePairList - INFO - Searching pairs: [] <b>-> Super misleading IMHO.</b>
2019-10-25 10:48:27,667 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.001 ...
<b>(... OK it works)</b>
</pre></code>

Probably something for #2417 as well.

**Comment by xmatthias** [comment]
> Searching pairs: [] -> Super misleading IMHO.

will need to look at this message - i'm not so certain that this will go away with #2417 ... Not intentionally, anyway

**Comment by santiagomalter** [comment]
@xmatthias FYI it seems that the "Searching pairs" trace is only empty the first time. After the first pairs refresh, the log message contains all the active pairs. Hope this helps!

**Comment by xmatthias** [comment]
That message is unrelated to this issue or the PR (the wrong variable was printed ...) but i've added this to the fix as well.

**Comment by OtenMoten** [comment]
Hello dear Community,

I use in my config this:

```
"exchange": {
        ...
        },
        "pair_whitelist": [],
        "pair_blacklist": ["DOGE/BTC"]
    },
    "pairlists": [{
        "method": "VolumePairList",
        "number_assets": 200,
        "sort_key": "quoteVolume",
        "refresh_period": 1800,
    },
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01}
    ],
    "edge": { ....
```

and I got the message 
`2019-11-30 11:10:29,435 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Searching for BTC pairs to buy and sell based on StaticPairList: []'}`

Sadly it uses staticPairList

**Comment by hroff-1902** [comment]
You whitelist is empty, the message says you about this.
You are using the master branch, which does not have yet #2417 merged, so the `pairlists` settings are simply ignored. Old StaticPairList from the older `pairlist` is implied thus, it fetches whitelist, which is empty...

C'mon, either switch to the develop branch or verify the issues for the branch they were applied/fixed in...
