### ISSUE TITLE
backtesting and sell signal / stoploss priority

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#2422]
When there is a sell signal, and a stoploss trigger on the same candle, stoploss takes over sell signal. Is this intended?
- It makes sense for timeframes <15m
- not so much for timeframes >30m
There are edge cases where if you use order book, sell is obviously not guaranteed, so it is conservative to prioritize stoploss, but generally market selling with >30m timeframes should always favour sell signal over stoploss.

**Comment by xmatthias** [comment]
as explained [here](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting), backtesting has to make a few assumptions, since it does not see "intra-candle".

One of these assumptions is that stoploss is first, protecting your assets.
in real trading, sell-signal may be first, and stoploss can happen 15 minutes later (assuming 30m candles), but we don't know that for sure, and therefore have to make this assumption.
This obviously becomes worse for longer-time candles - as we have a longer period of "no data".

Now this will have backtesting results lower than what you could archive in live trading - but backtesting aims to be "more conservative" than real trading - so it does not promise profits you cannot reach in real trading.
I'm intentionally saying it aims to be - since this may not always be true, depending on the strategy - but the aim is still there.

hope this makes sense?

**Comment by untoreh** [comment]
The list does not specify that a sell always happen after a loss. Also I agree that backtesting should always try to be conservative, but this also makes sell signals harder to debug because of stoplosses.

**Comment by orehunt** [comment]
The list does not specify that sell signals happen after stoplosses I think. 
Also I agree that backtesting should be conservative. However stoplesses also make sell signals harder to debug.

**Comment by xmatthias** [comment]
well yes ... you're right, that's missing from the list.

Thinking about it - you may have a point ... (will need some further investigation...)

assuming 1h candles:
the sell-signal triggers at the candle 8:00 (goes from 8:00-9:00) - for backtesting, this means it'll sell at 9:00 (open - next candle) it'll mean the same for live trading, btw.

Now when does your stoploss trigger? 
at the 9:00 candle, or at the 8:00 candle?
If it's the 9:00 candle, then in live-trading, sell-signal would probably win (real trading would sell at 9:00:05 or so) - stoploss could occur a lot later.

will need further investigation i think
