### ISSUE TITLE
Refactoring PairLists infrastructure

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2445]
* Let's split existing VolumePairList into Volume part and Precision part. Two accurate different PairLists.
* That one from #2442 then is normally to be implemented also in a separate PairList.
* More PairLists will then easily follow (we have requests for PairLists limiting by max/min price), since they all will be small.
* Edge also looks like a PairList (it implements same interface, returning the list of pairs, but with different names of methods), But I would not like to touch it and convert into pairlist... 😃 Not at this stage.
* Then the `pairlist` section in the config should be a list of pairlists. We can allow a single Pairlist as it is now for compatibility. There are several options here how this particularly can look like, the main idea is to allow specifying any number of PairLists with corresponding parameters.
* Then the pairlists should work in a chain, as filters for the list of pairs, modifying the list of pairs passed from the previous one. As Edge now does, fetching the list of pairs after StaticPairlist, modifying it and returning the modified list of pairs further for use by the consuming code.
* I assumed that the chain of pairlists should start from the StaticPairList (implicitly added into the beginning of the list of pairlist filters). However, I know you don't like this idea, so they can simply start from the list of all pairs ignoring the pairs_whitelist setting. It's okay.

**Comment by xmatthias** [comment]
I'm not sure i agree with this...

It'll make configuration and code too complex ... and the outcome of a pairlist will not be clear, since it'll run through one after the other (and in the end, probably no pair will be left ...).
You can only have one way to sort (Volume - or Price, or ...) - but you can have multiple ways to eliminate pairs.

> More PairLists will then easily follow (we have requests for PairLists limiting by max/min price), since they all will be small.

This is just another "sorting" Pairlist - similar to `VolumePairList`. 

> Edge also looks like a PairList (it implements same interface, returning the list of pairs, but with different names of methods), But I would not like to touch it and convert into pairlist... smiley Not at this stage.

Edge looks like many things we have deidicated modules for and i regret to have it allowed into freqtrade as is ... 

------------

Thinking about the above - how about we split Pairlist into 2 types of PairOperations - `SortingPairlist` - and Elimination stuff.

* Sorting would be the VolumePairList
* elimination would be the PrecisionFilter and MinMaxFilter and ....

Users select a SortingPairlist (`VolumePairList` - you cannot select more than one of these anyway) - and can assign multiple EliminationPairLists.

That way, you can sort by VolumePairList (nonbreaking for current users) ... and add additional "filter" classes...
