### ISSUE TITLE
Strategy analysis -> how many max_open_trades i will use for this strategy ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2449]
As an algo trade
I want to perform statistics like maximum drawdown, profit and find an optimum between stake_amount and max_open_trade so i run and export the backtest with --disable-max-market-positions flag and make simulations in jupyter.
So that i can find a comprise between risk and profit.

To archive that i need to find trades that happens at the same time and flag them (open_trade_number) and then filter then.

I don't know if it can be useful to have this straight in a column of the dataframe of load_backtest_data() ?

Maybe it is a too specific need.

Have a nice day.

**Comment by xmatthias** [comment]
I don't think it should be part of `load_backtest_data()` - since this returns a dataframe with data per pair. Adding the open_trade_number to each line would taint it with non-pair information ... which i don't think is good.

Also, load_backtest_data includes an open and close time per line. What would "open_trade_number" = 20 mean for this? 
at the open? close? maximum? .... it could vary greatly if you assume one pair is open for a few days.

It'll definitely need to be a seperate function, which returns a real timeseries (`load_backtest_data()` does NOT return a timeseries).

There is a `evaluate_result_multi()` in btanalysis, which (almost) does what you ask for, but compares it to the max_open_trades value passed in.

This can easily be refactored to 2 functions, one returning the timeseries contianing open trades per "interval" - and one doing the comparison.

**Comment by xmatthias** [comment]
I've added this now in #2451 .

Let me know if this is what you're looking for ...

**Comment by hroff-1902** [comment]
@gaugau3000 pls report back, if this is okay?

**Comment by hroff-1902** [comment]
@xmatthias is it possible to incorporate it somehow into the backtesting results tables?

**Comment by gaugau3000** [comment]
@hroff-1902 1 week later and still not have a clear mind on this :-) and sure i am late in my todo :-). I have a dilemma in my mind with correlated trades (2 buys at the same time or close and result most of the time in the same direction) -> it is terrible to manage this type of risk. 

I have already tested  the function it work find and for sure the time series granularity is the good direction.

So for me it is ok . As it was close and merge i was thinking it was ok for you.

See you.
