### ISSUE TITLE
Pivots Points function returns dates in front of all data variables

### ISSUE THREAD

**Issue by animehacker** [freqtrade/freqtrade#2469]
```
dataframe_weekly = resample_to_interval(dataframe, self.get_ticker_indicator() * 10080)
pp = pivots_points.pivots_points(dataframe_weekly, 1, 3)
```

This is the code I used in my strategy in the indicators function. Strange behaviour exhibited by pivots_points function. If we put standard dataframe in, it behaves as expected, but when putting in a resampled dataframe, the return will give us dates before every numerical value.

I am accessing the data like this pp['pivot'] or pp['r1'] , so if this is incorrect someone please tell me. But so far I am having to use a regex to 'clean' the output and get the data I need, which is not ideal.

**Comment by xmatthias** [comment]
This code will not work in dry/live operations irrelevant of how `pivot_points` behaves:

since you're using `10080` as multiplicator, i assume you're resampling 1m data to weekly timeframes.

This may work in backtesting / hyperopt, but won't work in dry-run since that only has ~500 candles available.
It may work if you use daily ticker-interval and resample to weekly (you'll have ~500 days of history) ... but not starting from minute.

#### pivot points
> `pp = pivots_points.pivots_points(dataframe_weekly, 1, 3)`

By passing `1` as 2nd argument, you're using a window of 1
From quickly looking at the code, i have my doubts that this code will work with timeperiod=1...

[pivot_points implementation](https://github.com/freqtrade/technical/blob/master/technical/pivots_points.py)


Could you maybe share the output you're getting which you think is wrong?

**Comment by animehacker** [comment]
dataframe_weekly = resample_to_interval(dataframe, self.get_ticker_indicator() * 10080)
       pp = pivots_points.pivots_points(dataframe_weekly, 1, 3)
       print(pp['pivot'])
       temp = re.findall(r'\d+\.\d+', str(pp['pivot']))
       res = list(map(float, temp))
       print("The numbers list is : " + str(res))

You can see what I'm doing here, I'm having to extract the number from each variable
because it's putting a date right at the front of each value
it's sub-optimal and will be easy to break, so I want to fix the issue inside pivot points if possible
rather than having to manually 'clean' the output.

You mentioned not being able to do it like this in a live bot, I agree completely, it's already an issue I am aware of and I will be using daily candles in a livebot then just using the live ticker to perform my entries.

As you probably know.. the backtester doesn't have a live ticker so this is the only way I can get good entries done on it. 

Back to the issue at hand. Here's a print dump of the data I get back:

   
![image](https://user-images.githubusercontent.com/3927087/68085183-510d0980-fe92-11e9-94c3-5d456ed588a5.png)

I'm just a newbie at Python but digging into the code of the pivots points function:

return pd.DataFrame(
        index=dataframe.index,
        data=data
    )

it seems to be returning data in a dataframe format, Pandas style. When I print it, it seems to be an array with date as the first column. But when I try to print an individual column e.g. pp['pivot'] for the pivot column, then it prints the date before my value, and it does that for every column.

Probably it's my inexperience with using Python and Pandas in general, and this might not be a true 'issue' in the sense of it being a bug.

But even if it's just a matter of my lack of understanding I think we need to either return data in a more usable format, or provide some kind of documentation with these functions that explains how to access the data within them, this pivots points function didn't even have a test class for it as far as I could see.

I feel like this might only be happening when resampling a dataframe interval and putting it into the pivots points function.

**Comment by animehacker** [comment]
Thanks to XMatthias who helped me solve this.

The solution is to extract the values from the Pandas index using the .values subfield, as so:

print(str(pp['pivot'].values[9]))

This gets the last index in the array for me, but you can choose any index, or choose to fetch the whole array without the index number on the end. 

I suggested to xmatthius that perhaps the documentation for FreqTrade could be updated to make it more newbie friendly to people with little Python and Pandas experience. 

Let's hope, maybe a section titled 'You Suck' or 'You are really a big newb' can be put at the bottom of the documentation menu and serve with some nice additional tutorial on usage for really below average intelligence people like myself.

**Comment by xmatthias** [comment]
> As you probably know.. the backtester doesn't have a live ticker so this is the only way I can get good entries done on it.

so this basically allows you to simulate "live" data within a longer timeframe ... i can immagine worse :D 

> it seems to be returning data in a dataframe format, Pandas style. When I print it, it seems to be an array with date as the first column.

as you can see from your screenshot, the first column header is slightly lower - indicating that this is the index. 
using `pp['pivot']` will get you one column (series) - including the index (that's how pandas work).
Since you're feeding a resampled dataframe, the index is a date. If you use the "original" dataframe, the index will be a number (0 to length of dataframe) ... however it'll still be shown in front if you convert a row to a string.

> But even if it's just a matter of my lack of understanding I think we need to either return data in a more usable format, or provide some kind of documentation with these functions that explains how to access the data within them, this pivots points function didn't even have a test class for it as far as I could see.

`pivots_points()` has a quite extensive [doc-string](https://github.com/freqtrade/technical/blob/57ee5d001b922b883fb2fea8aa29101faf6cb037/technical/pivots_points.py#L11-L32) which can be accessed via `help(pivots_points)` and tells you it returns a dataframe.
This format is identical to the dataframe passed in (since you pass in the resampled dataframe, you get the date-index back) - with the aim to make it easily mergable to the original dataframe and later reuse in the buy / sell functions.

I think we should link to the [pandas quickstart](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) guide since writing strategies requires some understanding of it - however - teaching users how to use pandas is "out of scope" from freqtrade.

Yes, Technical is not in a good state and we are aware of it (especially considering tests and library structure) - yet most functions have good docstrings explaining both the parameters they need, and basic functioning.

> `print(str(pp['pivot'].values[-1]))`

Yes, this way you can access this - but also `pp['pivot']` will work unless you convert it to string.
Please be aware that you should NEVER use `pp['pivot'].values[-1]`. 
This is point 2 from the [strategy mistakes documentation](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies):

> don't use .iloc[-1] or any other absolute position in the dataframe, this will be different between dry-run and backtesting.

It'll taint your backtest results as you look at data not yet available during trading operations.


> Let's hope, maybe a section titled 'You Suck' or 'You are really a big newb' can be put at the bottom of the documentation menu and serve with some nice additional tutorial on usage for really below average intelligence people like myself.

As mentioned above, i think the best we can do is link to the [pandas quickstart](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) guide - or something similar, since documenting how pandas work is done well on the pandas documentation.

Side note: Definitely **NOT** called  'You suck' - and neither  'You are really a big newb' - but something more positive like "New do python / pandas? Look at the pandas Getting Started guide ... "   - but thanks for the naming suggestions anyway... :smile:

**Comment by animehacker** [comment]
Sorry just my bad attempt at humour. I'll take a look at your suggested changes thanks.

**Comment by xmatthias** [comment]
Going to close this as i think the questions were answered and i think you got it to work in the end.

feel free to reopen if it's still not working.
