### ISSUE TITLE
How do I write buy / sell signals?

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#2470]
1. question)
How to write the cross condition of the price with any moving average? (Sample 1 picture)
I don't know which of these two examples should I choose. What's the difference between them?

(dataframe['close'] < dataframe['EMA10'])
(qtpylib.crossed_above(dataframe['close'], dataframe['EMA10']))

![asagi_kes1](https://user-images.githubusercontent.com/39681665/68093845-0cda3300-feab-11e9-8735-c59d2e3b7ddf.jpg)

----------------------------------------------------------------------------------------------------
2. question)
How to write the condition where the price is above the ichimoku cloud?

(dataframe['close'] < dataframe['ichimoku_cloud_green'])
is it true?

----------------------------------------------------------------------------------------------------
3. question)
dataframe['tema'] > dataframe['tema'].shift(1)

In this example; The last closing candle has the condition of being larger than the previous candle. Closed candles are taken into account when calculating, right?
When performing the calculation, it is necessary to consider the candlestick closure; or I think it would be repaint.

**Comment by xmatthias** [comment]
### 1.
Both ways are technically correct, but do something completely different. 
Using `(qtpylib.crossed_above(dataframe['close'], dataframe['EMA10']))`, you'll get one signal right when the cross happens.

Using `(dataframe['close'] < dataframe['EMA10'])` you'd get a signal at each candle between your graphical "buy" and "sell" signal. The signal will "stick" until the condition is not met anymore. This can lead to "late buys" - assuming you use a limited amount of trade-slots (`max_open_trades`) and one slot frees at the peak of the bull rush.

Both ways are valid to be used, and both can make sense depending on the context. If this is your Signal (buy when it crosses) - use `crossed_*()` functions to avoid "signal sticking".

If you have something different to create a signal (say RSI crosses > 30 [i know, bad example]) - and want to use this as a guard (so it doesn't buy at the wrong moment) - then using `(dataframe['close'] < dataframe['EMA10'])` is perfectly fine.

### 2. 

`dataframe['close'] < dataframe['ichimoku_cloud_green']` will compare when the close price is below the 'ichimoku_cloud_green'. 
Now looking at the code (assuming you use technical) i don't think that'll even  work, since `'cloud_green'` is already a boolean series.

You'd probably need to use one of the 3 below (alll lines work identically) - best prefer the 2nd since it's the shortest to type.

``` python
dataframe.loc[
            (
                (dataframe['cloud_green']==True) & 
                (dataframe['cloud_green']) & 
                (dataframe['senkou_span_a'] > dataframe['senkou_span_b']) # will do the comparison again - least performant.
            ),
            'buy'] = 1
```

https://github.com/freqtrade/technical/blob/57ee5d001b922b883fb2fea8aa29101faf6cb037/technical/indicators.py#L670-L706

### 3. 
By default (for supported exchanges) - freqtrade will only give you closed candles. 
If exchanges are known to give you partial candles (binance, bittrex, ...), this candle is removed before passing the candles to the strategy.

While this can be changed by an (undocumented) setting, it'll complicate your strategy as you'll need to handle "repainting-protection" yourself.

**Comment by xmatthias** [comment]
Going to close this since i think the questions were answered.
Feel free to reopen if you still have questions.
