### ISSUE TITLE
Realistic back-test :  how to deal with spread (backtesting by tick) ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2471]
As a trader
I want spread to be include during back-test simulation
So that i can choose witch pair to include/exclude during live and have a more realistic view on expected profits.

I don't know the feasibility (seems like tks to @xmatthias we can now download tick like data) but is use for now only to create candles (not look inside a candle :-) what happens )

I don't know if the functional gain/develop cost ratio is optimal to go in this direction i am interested in your point of view.

Have a nice day.

**Comment by xmatthias** [comment]
The problem with tick data is it's size (and therewith the problem of handling it) - so i would avoid if it's not necessary (it is for kraken - but the binance ohlcv data is good).

Backtesting with tick-data is probably impossible on any "usual" computer for any period longer than a few days, since we need to load all data into memory to correctly account for "parallel" trades correctly.

yes, eliminating this makes sense in certain analysis (as you've outlined in another issue) - but it's not realistic and not worth the effort of re-coding the complete backtesting, since that's a real edge-case which not too many people will look at.

I'm also not sure what you expect from tick-level data in regards to spread - it won't tell you the spread, just where trades actually executed. 

What you'd need to correctly determine spread is the historic orderbook - but no exchange i know provides this - you'd need to record this yourself all the time to build up a data-history - which will amount to TB's of data very quickly (i guess that's why exchanges don't provide this) - think about it - you'd need to record all orders - no matter if they got executed or not. 

Assuming i place a order, cancel it seconds later, and then place it one pip lower (or higher) ... this are 2 seperate entries you'd need to record - and now assume all users of the exchange doing the same over the span of a year...


Spread is included in the `get_tickers()` / `get_ticker(pair)` result (it includes best bid / ask prices) - but that's a "current" snapshot - not historic - which again, you'd need to record yourself for all pairs all the time.

On the other hand - up to a certain point, you can derrive spread from the pct-change of one pip (#2442 - allowing filtering pairlists by that) ... if an asset is priced "around the precision" limit - one pip (one price-unit) can mean 10% change - so you'll by definition have a high spread, since the price can only vary by 8% (HOT/BTC - as a popular example), but cannot be 1% higher or lower due to precision constraints.

The PR also includes a calculation example if you're interrested in this logic.

**Comment by gaugau3000** [comment]
Many tks very interesting !

> The problem with tick data is it's size (and therewith the problem of handling it) - so i would avoid if it's not necessary (it is for kraken - but the binance ohlcv data is good).

Ok

> Backtesting with tick-data is probably impossible on any "usual" computer for any period longer than a few days, since we need to load all data into memory to correctly account for "parallel" trades correctly.

Ok

> yes, eliminating this makes sense in certain analysis (as you've outlined in another issue) - but it's not realistic and not worth the effort of re-coding the complete backtesting, since that's a real edge-case which not too many people will look at.

Ok

> I'm also not sure what you expect from tick-level data in regards to spread - it won't tell you the spread, just where trades actually executed.

you are true it is not real spread based on order book but the prices gap give you enough information on how your trade will behave with a market buy/sell depending quantity. How many pct i loose to market fulfill this order ?

> What you'd need to correctly determine spread is the historic orderbook - but no exchange i know provides this - you'd need to record this yourself all the time to build up a data-history - which will amount to TB's of data very quickly (i guess that's why exchanges don't provide this) - think about it - you'd need to record all orders - no matter if they got executed or not.

I know not the goal :-) 

> Assuming i place a order, cancel it seconds later, and then place it one pip lower (or higher) ... this are 2 seperate entries you'd need to record - and now assume all users of the exchange doing the same over the span of a year...

spot spoofing the order book ;-)

> Spread is included in the get_tickers() / get_ticker(pair) result (it includes best bid / ask prices) - but that's a "current" snapshot - not historic - which again, you'd need to record yourself for all pairs all the time.

That's true.

> On the other hand - up to a certain point, you can derrive spread from the pct-change of one pip (#2442 - allowing filtering pairlists by that) ... if an asset is priced "around the precision" limit - one pip (one price-unit) can mean 10% change - so you'll by definition have a high spread, since the price can only vary by 8% (HOT/BTC - as a popular example), but cannot be 1% higher or lower due to precision constraints.

Yes tks usefull for BTC pairs.

> The PR also includes a calculation example if you're interrested in this logic.

Yes i will take a look

**Comment by xmatthias** [comment]
> spot spoofing the order book

well - it may be market manipulation, but it does happen and i'm pretty certain about it...

Another approach which could be usefull to you if you use "longer" timeframes:
assume you use 5m timeframe to trade.
You could use 1m data to backtest and resample to 5m for your signals.
That way, you'll only get signals at the "5m" marks - but you have "intra-candle" data. It's not tick-data - but you have 5 more datapoints "per candle".

This will also work for ROI / backtest as it'll only use the low of the 1st minute (not the low of the full 5m candle - for example).

It becomes more useful if you use "longer" timeframes (1h or so) ... but i guess also for 5m strategies it can increase your accuracy, since you simulate intra-day behaviour.
