### ISSUE TITLE
Docker image for raspberry in docker hub

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2473]
Hi,

Is it possible to create an image for the raspberry (built with ci)? It really takes long to built, export, load.

Have a nice day.

**Comment by xmatthias** [comment]
not at the moment... (or rather - not with TravisCI).

Travis times out after ~50 minutes - building the docker-image for raspberry on travisCI takes ... "longer than that" (not sure how much longer, exactly).

You can see my tries [in the feat/improve_travis branch](https://github.com/freqtrade/freqtrade/tree/feat/improve_travis) ... and in travis [here](https://travis-ci.org/freqtrade/freqtrade/builds/520402220).

Generally, i'm pretty unhappy with TravisCI (random test-failures because binaries are missing - which are fixed by restarting the job ...) - and a unclear future since they've been aquired a year ago (and let go most employees) - so I think moving away from TravisCI can make sense.

I did some experiments with Azure pipelines (building it works there)- and i intend to test github actions for this as well. Both offer a lot longer runtime (~6h) which will be more than enough to build this image. 
In addition to that, at least azure is also faster than travisC.

However, i don't wan't to run CI in both Travis and Azure/github (not for more than a transition period, anyway) to save resources (even if i don't pay for them - save the planet...).

However, I also don't want to rush the decision (and testing this all these setups takes some time and patience, since it involves a lot of "waiting time"...).
So yes, this IS on my agenda, there is no issue on it since i've been working on it "on and off" ... and it'll probably come in combination with moving to another CI - or right after that step.

**Comment by xmatthias** [comment]
some updates: 
github Actions job seems to run (takes 1h for raspberry alone though)...

https://github.com/xmatthias/freqtrade/runs/292703337

I pushed the image to a test-dockerhub location for now ... the "_pi" image should work on raspberry - but i didn't have time to test it yet as i was "hunting" for other problems ... 

https://hub.docker.com/r/freqtradeorg/freqtradetests/tags

**Comment by xmatthias** [comment]
further feedback to this after testing the image:

seems to work just fine (build on github CI!)

```
pi@raspberrypi3:~/freqtrade $ sudo docker run --rm freqtradeorg/freqtradetests:test_pi --help
usage: main.py [-h] [-v] [--logfile FILE] [-V] [-c PATH] [-d PATH]
               [--userdir PATH] [-s NAME] [--strategy-path PATH]
               [--db-url PATH] [--sd-notify]
               {backtesting,edge,hyperopt,create-userdir,list-exchanges,list-timeframes,list-markets,list-pairs,download-data,plot-dataframe,plot-profit}
               ...

Free, open source crypto trading bot

positional arguments:
  {backtesting,edge,hyperopt,create-userdir,list-exchanges,list-timeframes,list-markets,list-pairs,download-data,plot-dataframe,plot-profit}
    backtesting         Backtesting module.
    edge                Edge module.
    hyperopt            Hyperopt module.
    create-userdir      Create user-data directory.
    list-exchanges      Print available exchanges.
    list-timeframes     Print available ticker intervals (timeframes) for the
                        exchange.
    list-markets        Print markets on exchange.
    list-pairs          Print pairs on exchange.
    download-data       Download backtesting data.
    plot-dataframe      Plot candles with indicators.
    plot-profit         Generate plot showing profits.

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Verbose mode (-vv for more, -vvv to get all messages).
  --logfile FILE        Log to the file specified.
  -V, --version         show program's version number and exit
  -c PATH, --config PATH
                        Specify configuration file (default: `config.json`).
                        Multiple --config options may be used. Can be set to
                        `-` to read config from stdin.
  -d PATH, --datadir PATH
                        Path to directory with historical backtesting data.
  --userdir PATH, --user-data-dir PATH
                        Path to userdata directory.
  -s NAME, --strategy NAME
                        Specify strategy class name (default:
                        `DefaultStrategy`).
  --strategy-path PATH  Specify additional strategy lookup path.
  --db-url PATH         Override trades database URL, this is useful in custom
                        deployments (default: `sqlite:///tradesv3.sqlite` for
                        Live Run mode, `sqlite://` for Dry Run).
  --sd-notify           Notify systemd service manager.

```
