### ISSUE TITLE
Rename the git branches

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2496]
As exchange in slack channel the naming of the branches don't follow common naming conventions.
A proposal is to rename the develop -> master and master-> release.

Impact :
- don't forget to update documentation. See #2495

**Comment by hroff-1902** [comment]
I propose to postpone it, to be applied after moving to pypi.

**Comment by xmatthias** [comment]
yes -  i guess that's why it's an issue ... still we shouldn't forget it ...

**Comment by gaugau3000** [comment]
Hi,

It is just to not forget (i am aware of dependency explain by Matthias yesterday). I don't know of in a project management way how we can link to #2112 and a kind of say to do A before B as it is a dependency.

I remove technical debt in title as it is know  flagged.

**Comment by xmatthias** [comment]
With the current incentives (also by github) to get rid of the term "master" (by which certain groups of people / etnicities feel offended by) - i don't think we'll fully implement this proposal (simply because it's not necessary).

We can change "master" to "release" at basically any point in time - but we'll probably keep the name "develop" - as i HOPE this term will not offend anyone.
