### ISSUE TITLE
Market change proposal to Backtest report

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#2524]
I can see the profit / loss ratio of the strategy in the backtest report.
However, I would like to see the profit / loss status of someone who does not trade crosses.
For example, my strategy made a 10% profit. On the same date the market increased by 40%. So my strategy is not profitable.

It might be better if there's a report called Market change. Can be added as an optional parameter
For example: freqtrade backtesting --marketchange

| pair          |buy count |avg profit % |cum profit % | Market Change %
|:-----------|-----------:|--------------:|--------------:|---------------------:|
| ADA/BTC  |           35 |            -0.1  |            -38.8 |                        5.0    |
| ARK/BTC  |           11 |            0.41 |            -4.52  |                      -20.8   |
| BTS/BTC   |           32 |              0.32 |             10.1 |                       40.2   |

**Comment by xmatthias** [comment]
well, that's basically comparing to "hodl". (Buy and Hold).
we've had this requested before here: #1913 (in combination with CCI30).

Yes, i guess it makes sense - I'll move tracking of this to this issue - and keep the other one for CCI30 - so the 2 are seperate and can be worked on seperately.

**Comment by gaugau3000** [comment]
@acemi1  I am not sure about the need to include this metrics (Buy and Hold, CCI30). Maybe you would like to compare a trend following strategy on 1 day timeframe Vs Buy and Hold because you stay a long time in the market (it can be a kind of referential), or maybe strategies you stay a lot of time in the market (stop and reverse strategy based). But this is really particular use case. Market can loose 80% of is marketcap in 1 year but it can have no/little influence on a 5 min timeframe with trades of 30 minutes duration. Buy and hold is not a strategy by the way so compare to it i'm not sure.

Have a nice day.

**Comment by acemi1** [comment]
@gaugau3000  If you are doing backtest for too many coins, it can be a convenience to see the strategy's profit / loss status at a glance.
As I wrote before, it can be done as a parameter; So it won't hurt anyone.
I tested Gekko boots before. Gekko also has this feature as standard.

![ichi 60 dakika](https://user-images.githubusercontent.com/39681665/69000530-3dc25b00-08e2-11ea-8edf-1793520aa002.jpg)

**Comment by xmatthias** [comment]
to be honest, the command `freqtrade plot-profit` does something like this (not in numbers, but graphically).

It shows you the movements of each pair - and compares it with another graph showing your profit. 
You can see a sample of this [in the documentation](https://www.freqtrade.io/en/latest/plotting/#plot-profit).

While i do see value to compare it over time - i'm not sure about the total / sumarized value.

just seeing "market moved 20% - but my strategy moved 19%" does not say it's a bad strategy - not if it had a dump of 50% in the middle - which will be obscured by this.

**Comment by acemi1** [comment]
> pair 	buy count 	avg profit % 	cum profit % 	Market Change %
> ADA/BTC 	35 	-0.1 	-38.8 	5.0
> ARK/BTC 	11 	0.41 	-4.52 	-20.8
> BTS/BTC 	32 	0.32 	10.1 	40.2

I've just started learning python. I don't know how to add the last column in this table.
I found the necessary lines in the backtesting.py database. But I don't know how to write the change between the first candle and the last candle.

**Comment by hroff-1902** [comment]
Comparing to Gekko, in Gekko this is simplier, since it only trades one pair if I understood properly...

How can we handle it? By adding "Market Change %" column into the backtesting table? That would be nice... Shall we remove the starting instable timeframe, which is excluded for the strategy under backtesting, so that the time frame for which the backtesting is performed and the period for this value be the same?

What about "Avg Price Change %", as in the plotting, is there place for it?
How's this avg is calculated -- with equal weights? Or with currency pricecap taken from some source, for example?

**Comment by xmatthias** [comment]
the plotting "avg price change" does only work for plotting i think - at least how it's done now.
It uses the average close price across all currencies - but assume you got BTC/USDT (8000) and LTC/USDT (50) ... 5% pricechange in LTC will barely be visible in the average because of the high price of BTC - but if i was in that trade, it'll make a difference on my p&l.

Ideally, this is done on eihter log-returns or pct-change per candle - which would give comparable results.

we may also consider this for the plot-profit script - however the current way "kinda" works there as visually, you see all lines, not just the average line.

**Comment by hroff-1902** [comment]
> the plotting "avg price change" does only work for plotting i think - at least how it's done now.
> It uses the average close price across all currencies - but assume you got BTC/USDT (8000) and LTC/USDT (50) ... 5% pricechange in LTC will barely be visible in the average because of the high price of BTC - but if i was in that trade, it'll make a difference on my p&l.

But it means that this change is also barely visible in the plot, the avg price change will actually be close to the change of most mature pairs in the pairlist and thus is also useless...

**Comment by xmatthias** [comment]
well no - you can disable the average and look at it per pair - which makes it useful again.

On the other hand - it's just a tool to give you some idea how the market moved - the more interresting part in plot-profit is the lower plots ...

**Comment by vakker** [comment]
I also think the hodl strategy would be a useful metric at least for basic benchmarking.

**Comment by xmatthias** [comment]
well it's problematic as to how you'd calculate this.
in theory, you can easily write a Hodl strategy just for backtesting and compare to it using `--strategy-list`.

However - assume you have 10 pairs in your whitelist - but max_open_trades set to 3 (only have 3 trades open at all times).

How should the HODL strategy compare all of these? it would open a position on 3 random pairs - but that's not comparable as maybe 3 other pairs would have been better.

Similarily - buying all 10 pairs just because it's the HODL strategy is also wrong - since this would asume a multiple of the capital you've really got.

**Comment by acemi1** [comment]
https://github.com/freqtrade/freqtrade/issues/3518#issuecomment-648655577
What you say is quite logical. If the market price decreased by 50% and then made a profit of 120%; Hold strategy will display 10%.

However, there must still be a% rate at which we can compare the success of the strategy. (I'm not sure how it should be calculated, your opinion is important in this matter)
There are good and bad examples in the attached screenshots, and Strategy is profitable in both examples. When using Backtest or hyperopt, it is not possible to draw graphics like this every time. So is my strategy successful? I do not know.

Suppose we test the data in the test range with an indicator that repaints like zig zag. Can evaluation be made according to the result? For example, let's take 50% or 60% of the result.
if the result of zig zag indicator is 260%; Hold = 130% is acceptable.
(I just conveyed my opinion. I'm not sure it's a good idea)

Bad example
![bad](https://user-images.githubusercontent.com/39681665/86054577-11b7ac80-ba63-11ea-8fef-54087bf770ba.jpg)

Good Example
![good](https://user-images.githubusercontent.com/39681665/86054578-12e8d980-ba63-11ea-8083-a6241aeedd32.jpg)

**Comment by hroff-1902** [comment]
HODL assumes you buy and hold some asset or a portfolio of assets.
Assume your bot is trading BTC pairs. What asset should you hold to calculate the performance of HODL benchmark?

**Comment by xmatthias** [comment]
The way i've done this now is by taking the first and last price of every asset to calculate the difference, and calculating the mean of all pairs, which gives you the overall market change (of the pairs you backtested).

For most EUR pairs on kraken, i get ~50% gain for this year (january til a few days ago). 

Yes, you can game this for sure - but it'll at least give you "some" direction - and it's been requested quite often.
