### ISSUE TITLE
ticker_interval cannot be defined only in strategy file ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2531]
Hi,

docker image id  : 6d06e14cee5c

When i try to define the `ticker_interval` only in strategy file (`ticker_interval = "15m"`) i have this error :
`2019-11-14 10:43:05,787 - freqtrade - ERROR - Ticker-interval needs to be set in either configuration or as cli argument --ticker-interval 5m`

But in the documentation it says :

> The following parameters can be set in either configuration file or strategy
> - ticker_interval

Have a nice day.

**Comment by xmatthias** [comment]
yeah ... this happens with "a few" parameters - which should be copied - but are required by the config validation ...

You can have a look at these in `constants.py` - i think the ones impacted are ticker_interval, stake_amount and stake_currency.

In theory, it's as easy as removing them from the constants dict - but there is no further validation (now!) - so it's on you to make sure to have them in "one of the 3 places".

I have an idea for this which will fix this "mid-term" ... and i would not want to touch it now, since we'd then need to probably "rewrite" that part again.

**Comment by Tekpre012** [comment]
it also happened to me to leave the interval ticker in the strategy, but removing it from the config the hyperopt no longer worked for me. So now it's a duplicate
