### ISSUE TITLE
discrepancy from backtesting and trade ?

### ISSUE THREAD

**Issue by antoniosap** [freqtrade/freqtrade#2574]
Question:
backtesting trials work fine. sell and buy.
trade don't emit any buy sell signal ?
why ?

```
2019-11-26 07:11:25,128 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2019-11-26 07:11:25,128 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair XLM/BTC.
2019-11-26 07:11:25,173 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair XLM/BTC.
2019-11-26 07:11:25,203 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair XLM/BTC.
2019-11-26 07:11:25,224 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2019-11-26 07:11:25,227 - freqtrade.strategy.interface - DEBUG - trigger: 2019-11-26 06:05:00+00:00 (pair=XLM/BTC) buy=False sell=False
2019-11-26 07:11:25,228 - freqtrade.freqtradebot - DEBUG - Found no buy signals for whitelisted currencies. Trying again...
```

**Comment by hroff-1902** [comment]
See this: https://www.freqtrade.io/en/latest/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet

How many trades were found during backtesting? What timerange was used for backtesting? Have you backtested the strategy on the same timerange (ticker_interval)?

**Comment by antoniosap** [comment]
buy count = 28
timerange = 42 days
ticker_interval = 5m
average trade duration = 6:58:00
same set of whitelisted pairs = yes
exchange = binance

Exchange: binance
Stake per trade: 0.002 BTC
Minimum ROI: {'0': 0.17369, '17': 0.05925, '32': 0.03754, '45': 0.0}
Stoploss: -0.1
Ticker Interval: 5m

I've been waiting for days. no buy / sell

**Comment by xmatthias** [comment]
well 28 trades in 42 days does not say too much - all buys could be within the first (or last) 10 days of these 42 days.

Best [load the backtest results into a dataframe](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) and verify when they happen (it's 28, so you should be able to analyze this easily).
Things to look out for:
* are all trades evenly distributed over time, or are periods with high activity, vs. periods with low activity?

Also, read through [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting) and [strategy - common mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies)

If the trades are well distributed in backtesting, it could be that the buy-signals are generated by using data which is not available in dry-run mode but during backtesting, so the bot has no chance to make any buy since no buy-signal can be generated for technical reasons
could be 
- using data from the future
- using absolute indexing 
- using too long indicator windows (dry-run has ~490 candles available) 
- something else entirely i'm not thinking about at the moment...

**Comment by antoniosap** [comment]
after 7 days trade begin

**Comment by hroff-1902** [comment]
Your strategy may be constructed to create signals only on, say, bullish market and be silent at the bear market conditions, for instance. Or be waiting for strong trend and be silent during whipsaws...

Or vice versa. 28 trades for 42 days means ~2 days between signals *at avarage*.

Try to analyse the charts as @xmatthias suggested.
