### ISSUE TITLE
Bug in Freqtradebot._get_min_pair_stake_amount()

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2575]
```
    def _get_min_pair_stake_amount(self, pair: str, price: float) -> Optional[float]:
...
        return min(min_stake_amounts) / amount_reserve_percent
```

This is wrong. max value of 2 limits should be returned instead.

For example, if as on Binance for ETH/BTC market, limit cost min is 0.0001, limit amount min is 0.001, price is 0.020405, then min returns `0.001 * 0.020405`, which is less than limit for cost, 0.0001.

<s>BTW, the limits returned are in the quote currency. Is it okay? Should not they than be in the base currency?</s>

**Comment by xmatthias** [comment]
just so i understand this correctly ...

minimum stake amount is a combination of 2 things - minimum cost - and minimum amount.

currently we use `min()` - but you're proposing to use `max()` ... so the minimum pair stake is the higher one of the 2, because we cannot go lower than the "higher" minimum?

(darn this is odd to even formulate ...)

**Comment by hroff-1902** [comment]
this description seems to be correct, with a small correction:
"so that the minimum pair stake is the higher *all* of the 2"

**Comment by hroff-1902** [comment]
Detailed examples here: https://github.com/freqtrade/freqtrade/pull/2576#issuecomment-559010350
