### ISSUE TITLE
No fiat currency is displayed

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#2589]
## Describe your environment

  * Operating system: Ubuntu 18.04 VM
  * Python Version: 3.7 (`python -V`)
  * Branch: Master
  
## Describe the problem:

Since yesterday the following error message appears:

`freqtrade.rpc.fiat_convert - ERROR - Could not load FIAT Cryptocurrency map for the following problem: OperationalError`

Some other in Telegram chatgroup also noticed the same error.

Kind regads

**Comment by xmatthias** [comment]
It's related to coinmarketcap - to have the bot start anyway you can simply remove `fiat_display_currency` from your configuration. 
It won't convert to that currency then, but will not impact trading, just the informations you're getting via telegram.

It seems like coinmarketcap has some problems over the last few days (or it's intentional, as they try to deprecate their free api)... 
It's been deprecated for over a year now - but libraries did not adapt the new API (as it would require an api key, and will probably not be free anymore ...).

**Comment by hroff-1902** [comment]
@OtenMoten is it okay now?

**Comment by hroff-1902** [comment]
Closing it as seems it was a temp. problem at the coinmarketcap and no further input provided.
Feel free to reopen it if you think it's relevant.
