### ISSUE TITLE
Fatal exception!

### ISSUE THREAD

**Issue by Mixcoatl5** [freqtrade/freqtrade#2593]
Operating system: 18.04
    Python Version:  3.6.9
    CCXT version: 1.19.86
    Branch:  Develop
    Oracle Virtual box (don't know if it is relevant info) 

![Exception](https://user-images.githubusercontent.com/58388876/69913431-09997f00-1438-11ea-8eff-56dd68ef6a75.png)

Hello guys,
I tried to install freqtrade based on steps on freqtrade site with all packages. I tried to reinstall many times but I always got the same issue which you can see above. 
I am trying to put to operation freqtrade for over a week now, but since I am newbie in python I don't know what else I can do and I am desperate now. I googled but did not find anything useful for me.

Please could anybody help me?

**Comment by xmatthias** [comment]
The problem seems to come from the strategy (bbrsi.py). It'll work fine with the sample strategy (try rnning with `-s SampleStrategy` - but don't use it for real money!)

You're importing `fishers_inverse`from `freqtrade.indicator_helpers`. This has been deprecated several months ago, this module moved to technical.

Best install the [technical module](https://github.com/freqtrade/technical/), and change the import from `from freqtrade.indicator_helpers import fishers_inverse` to `from technical.indicator_helpers import fishers_inverse`.

**Comment by Mixcoatl5** [comment]
Thx a lot for your help! Fatal exception is already gone and I am able to start backtesting and trade commands without any problems. backtesting provides me results based on strategy and data I downloaded so its working perfectly.
But when I start trade command nothing happen in long time as you can see in image below
![Screenshot from 2019-12-01 15-21-17](https://user-images.githubusercontent.com/58388876/69915567-c3044e80-1450-11ea-84fe-9da343d55d5a.png)

"Heartbeat" sound to me like "I am working, just w8ing for signals", am I right or is there anything else which is not working? My telegram bot do not start during heartbeating.

And maybe one more question... These "missing data fileup..." is that ok?

Thx a lot!

**Comment by hroff-1902** [comment]
Pls read: https://www.freqtrade.io/en/latest/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet

You can see in the backtesting results how frequently your strategy is supposed to create trades, maybe it's only once a week.

If the initial problem has gone, pls close this issue since the it's no longer actual. Pls do not paste many different points in the same issue because it will quickly get to mess.

**Comment by Mixcoatl5** [comment]
Ok, copy that! Thanks for your help, I really appreciate it :)

**Comment by xmatthias** [comment]
> These "missing data fileup..." is that ok?

Well yes - most exchanges don't return data for candles without volume, so depending on the ticker interval this is absolutely normal (and will appear more often for lower ticker intervals). Also exchange downtimes can cause this since at that time there was no volume either.

> My telegram bot do not start during heartbeating.

Please check your configuration - the section `"telegram"->"enabled"` needs to be set to true and the token / chatid need to be inserted correctly.
