### ISSUE TITLE
Newsletter ?

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2596]
Any possibility on including a newsletter so we are updated on the current updates per branch? I think this would be useful for a lot of us who actively use freqtrade but do not have time to monitor all the contributions on the slack.

@xmatthias @hroff-1902

**Comment by xmatthias** [comment]
You can watch the repository on github to be notified of changes if you don't want to monitor slack. 
You have the option to see all changes, or to see updates only for releases (if you're busy ...). 
Releases include a changelog with the changes done in this release - so this will give you what you need - which is all changes done within this release, in one summarized form.


Otherwise, the answer is no - i do not plan to start nor maintain a seperate newsletter service. 
Keep in mind that maintaining that will be time we'll then spend not working on improving the bot (or our strategies, or living our lifes, for that matter), so i'd rather spend time any of these things than maintaining yet another method to notify.

**Comment by hroff-1902** [comment]
@Dante2333 In the (nearest) future Freqtrade will be moved to pypi, develop be renamed to master and fetching new versions from github repo by ordinal users will be discouraged (this will be an option for the devs/advanced users testing new features 'on-the-fly'), so you'll also see all the relevant new issues and major changes in the release notes for the new releases at pypi. So the need for a special notification service will be even less...

To be honest I was also thinking of a project twitter channel with the copies of the NEWS messages we publish in the Slack, but I guess I'm also too lazy for that... An option for a separate channel at Slack for the announcements was also discussed, as @xmatthias mentioned but was rejected in the meantime.

As @xmatthias said, we started pinning the NEWS messages at Slack, let's see for some time how this will work...

**Comment by xmatthias** [comment]
Going to close this as i think we have enough methods to keep uptodate on releases.
