### ISSUE TITLE
Hyperopt now asking for a strategy? Syntax error which was not previously found

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2603]
2019-12-02 19:12:32,474 - freqtrade - ERROR - No strategy set. Please use `--strategy` to specify the strategy class to use.

ubuntu 18.04 lts
Python 3.6.8
ccxt==1.20.22
346d381ab87f9961a034dac7fc45d714210aaf81

**Comment by xmatthias** [comment]
Yes it is. 
previously we used DefaultStrategy - but that's FAR from what your real strategy will probably look like, so defaulting to that does not make sense.

it's documented [as breaking change](https://github.com/freqtrade/freqtrade/wiki/Breaking-changes-to-the-comand-line-interface), and we've also pinned the release in the slack channel #general.

**Comment by gitgitgat** [comment]
i don't get it, hyperopt now needs a strategy as well?

**Comment by hroff-1902** [comment]
It was always needed a strategy, but previously it was (sometimes incorrectly) using the DefaultStrategy implicitly. It's incorrectly in some (many) cases, because the strategy contains attributes that may significantly change the results of backtesting (hence hyperopt) so you may simply do not get it when the strategy is used implicitly. Now you should specify explicitly either the DefaultStrategy/SampleStrategy (if it suffies to your hyperopt) or your custom strategy that accompany your hyperopt. This is more controllable and more explicit for a user so it was choosen to be this way.

**Comment by gitgitgat** [comment]
Okay, thanks

**Comment by hroff-1902** [comment]
Closing it since the question was answered.
Feel free to reopen if this makes sense.
