### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mj1300** [freqtrade/freqtrade#2609]
## Step 2: Describe your environment

  * Operating system: ____ windows 10
  * Python Version: _____ python 3
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

when i wants to use informative pair i got this weird error but admin in slack help me to figure out what it says the log is:
```

2019-12-03 21:11:32,009 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\optimize\__init__.py", line 44, in start_backtesting
    backtesting.start()
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\optimize\backtesting.py", line 453, in start
    preprocessed = self.strategy.tickerdata_to_dataframe(data)
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\strategy\interface.py", line 429, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\strategy\interface.py", line 429, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\strategy\interface.py", line 445, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "C:\Users\test\Desktop\freqtrade-develop1\freqtrade\strategy\default_strategy.py", line 71, in populate_indicators
    data = self.dp.get_pair_dataframe("BTC/USDT", ticker_interval="1h")
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\data\dataprovider.py", line 84, in get_pair_dataframe
    if len(data) == 0:
TypeError: object of type 'NoneType' has no len()
```
it just need a btc data to use that so plz change this log error

**Comment by xmatthias** [comment]
The only thing we can change in this case is to return None instead of an error (which would be correct, anyway) - since this occurs only if no data can be found for the pair you're requesting.

This however means that the case of no data being returned must be handled by the strategy (which it should be, anyway) - otherwise the error will simply be moved from the dataprovider file to your strategy.

**Comment by hroff-1902** [comment]
Should not the OperationalException with a human-readable message proposing to download the date first be issued, as in the case of non-informative pairs?

**Comment by xmatthias** [comment]
Why fail? the log states (as warning) that no data for this pair is available. 

the same happens if you backtest 20 parirs, and miss data for 1 of these pairs .
It only fails if NO data is available - for none of the 20 pairs i wanted to backtest.

**Comment by hroff-1902** [comment]
> Why fail? the log states (as warning) that no data for this pair is available.

Because the reason is that the data for informative pair(s) were not downloaded before and should be downloaded if this pair is used. Otherwise the results of backtesting will not be correct even if no error is produced in the custom code.

> It only fails if NO data is available - for none of the 20 pairs i wanted to backtest.

This also is not correct, I guess.

**Comment by xmatthias** [comment]
> This also is not correct, I guess.

Why should one missing pair cause backtesting to fail? 
It'll be 100% correct - but without taking this missing pair into account.


well in that case you'll also need to fail if the start / end of the period is missing.
but that won't work - as many "newer" pairs lack history - so you're preventing me from backtesting all of 2019 for all pairs i desire to trade, because 2 pairs started trading in April.
