### ISSUE TITLE
Closing an individual trade

### ISSUE THREAD

**Issue by joshuar87** [freqtrade/freqtrade#2615]
Hi there,

I would like to "Assist" my bot at times according to my intuition. Is it possible to close an individual trade when I would like to before the "Sell signal" or "Stop loss"? Out of curiosity what would the bot track if I manually sold the trade on the exchange?

Thanks,

**Comment by xmatthias** [comment]
if you sell it manually on the exchange, then you'll need to close it manually in the database - since this is almost impossible to track correctly (assuming you "co-use" the account for bot-trading and manual trading).


you can (and should) however use `/forcesell <tradeid>` - which will sell the trade immediately - and update the database correctly.

**Comment by joshuar87** [comment]
Great, thanks a lot for the answer

**Comment by hroff-1902** [comment]
closing it since the question was answered

**Comment by antoniosap** [comment]
I try enable bot forcesell. Then /forcesell id
Don t work
