### ISSUE TITLE
Trailing stop hyperopt invalid results

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2617]
##  Describe your environment

  * Operating system: linux
  * Python Version: 3.7.5
  * Branch:  Develop
  * Last Commit ID: 8dd9b5c6fba973b98defc0f9a9e2e3c01af735dd
  
## Describe the problem:

Depending on the strategy, hyperopt may produce invalid results.

My trailing hyperopt just returned the following result.
However, configuring trailing_stop_positive > trailing_stop_positive_offset is not possible (we prevent this as part of config validation).

```
Stoploss:
{'stoploss': -0.34474}
Trailing stop:
{   'trailing_only_offset_is_reached': True,
    'trailing_stop': True,
    'trailing_stop_positive': 0.33186,
    'trailing_stop_positive_offset': 0.0542
}

```

Leaving out the irrationally high numbers my stoplosses reach... this configuration results in `The config trailing_stop_positive_offset needs to be greater than trailing_stop_positive in your config.` (also shown on slack).

### Further thoughts

Now i'm not 100% certain if the error is with hyperopt thinking about it.

The current validation we have in place ensures that "positive stoploss" cannot lead back into negative values. (5% offset and trailing_stop_positive at 10% could be a -5% sell).
However, I think it might be a valid case to say that a stoploss is -10% initially, and once the trade reaches 2% profit, it should be pulled tighter - to 5%. 
This could lead to -3% loss - but on the other hand it is not 10% loss anymore.

**Comment by hroff-1902** [comment]
I can be worked around/fixed

What is the complete list of constraints on trailing stop parameters?

* `trailing_stop_positive_offset > trailing_stop_positive`, got it,
* `trailing_stop_positive > 0`, as I can see from configuration_validation. This is satisfied due to the min. boundary for the dimension for this parameter in the hyperopt space...
* any dependencies on the value of stoploss setting?

**Comment by xmatthias** [comment]
no - the 2 conditions within `config_validation` are the only ones i'm aware of.

as said - i'm not certain if the conditions make sense though ... also thinking about it - `trailing_stop_positive > 0` seems wrong - 
it's a stoploss so setting it to 0.05 will mean it trails by 5% - not that it's set to 5% profit - 
so -0.05 would make more sense.

stoploss is used as `-1 * abs(stoploss)` anyway since we need it to be negative - and we accept only negative values for `stoploss` - so this is a major inconsistency.

**Comment by hroff-1902** [comment]
As for stoploss, stoploss should also be positive value in the config/strategy, and the needed sign is applied to it (minus for long trades, plus for shorts (in the future).
Because you say "stoploss is N points/pips", "stoploss is N percents", "stoploss is N USD", with no "minus" in that sentences...
