### ISSUE TITLE
Allow pyramiding of buy trades

### ISSUE THREAD

**Issue by JanAbraham** [freqtrade/freqtrade#2640]
May I request an option to allow pyramiding for buy trades? Currently only one trade is hold per trading pair and only after the remaining one is closed, then a new buy trade can be issued. Backtesting and Hyperopting support pyramiding.

There should be several safety options associated with that:
- max amount of open trades per pair
- max amount of consecutive orders (to avoid overheating when the buy signal is triggered too often)

Unfortunately, I am only an investor but not a coder ... but would be great if someone could take this little challenge ;-)

**Comment by xmatthias** [comment]
Backtesting / hyperopt don't really support pyramiding (there's no logical limitation to consecutive orders ... or even a maximum amount per pair).

However:
we have multiple issues open around this topic -  #1519 and to some extend also #2183 - which will enable this to be implemented - but will need to happen first.

Unfortunately it's not something done quickly, since it'll require a lot of changes to support this first (freqtrade was not developed with this in mind).

I'm going to close this since it's tracked in the other issues, and keeping a 3rd issue open for the same thing will not make sense.

**Comment by JanAbraham** [comment]
I saw it now, especially #1519 after you added pyramiding in the title. Thanks for that! Will follow the other case then.

**Comment by xmatthias** [comment]
yep - i changed the title since it is difficult to refind if you're not looking for exactly the title - and pyramiding is another word for position stacking - so now people (hopefully) have twice the chances to find that issue ...
