### ISSUE TITLE
Refactoring pair name handling

### ISSUE THREAD

**Issue by jblestang** [freqtrade/freqtrade#268]
Code is crippled with` pair.replace('_', '-'),` what about adding a method in the exchange class that defines the delimiter and remove `pair.replace` in all the code ?

**Comment by gcarq** [comment]
Sounds good to me

**Comment by jblestang** [comment]
after much thinking, I think the name of the pair should be automatically created by the bot. We define the **stake_currency** as for example BTC, and the list of pairs needs to be only something like *[ "XVG" ,  "XRP" ]*. The bot can then form the correct pair

**Comment by gcarq** [comment]
Thats a good idea, it also gives more flexibility when switching the stake_currency on a regular base.

**Comment by hroff-1902** [comment]
This issue consists of 2 diff. parts: the original message and the proposal in the comment (5 Jun 2018).

First one is not actual for long time: mapping of symbols in the pair names is only made when the filename is generated.

Second one is better be refused: there can be more than one market on the exchange with the same quote currency and our base (stake) currency.

**Comment by xmatthias** [comment]
Funnily, i've been looking at this issue just this week, and came to a different conclusion.

`pair.replace("/", "_")` is used twice (3 times) - once to saveand load data, and once as plot filename - so i didn't see it as anything that needs action (we've had this code-segment around 20 times in the code - mostly in places where it wasn't needed) - and that's when this issue was created.

For the 2nd part - i've had the dream to create a Pair class (my experiments around that are almost 6 months old ...).
I think it would simplify a lot of things ... we'd have `pair.quote`, or `pair.as_filename` or ...

I've played around with that part a bit and i think it would work - all while supporting both `XRP/BTC` and `XRP` (+ stake currency) configuration in the pairlist (as proposed above) - which would actually be very easy to do if it's a class creation.

The part i didn't investigate yet is how to integrate that with the database (maybe `str(pair)` ...) but we're not creating new trades that often, so i guess that would work fine, too.

**Comment by hroff-1902** [comment]
First part is completely not actual for the current code base, right -- I guess it was actual more than an year ago, when the codebase contained many such pair name conversions, it's not an issue anymore.

The second proposal:

No problem with generation of the pairs from the stake currency symbol and symbols for pairs. With a class as you mentioned, or in any other way. The point here is that the markets (which symbols do not contain '/') can also be tradable -- like options and futures. An exchange may also contain "pairs" (in our terms, how we define them -- a market with '/' in the symbol name) with same quote currency -- like "ETH_H19/BTC" and "ETH_M20/BTC". And I think that support for trading futures and options is more important than this proposed ability to specify the list of quote currencies instead of current list of pairs/market symbols (in the future). So if we decide to move to this direction, the current pair lists (lists of market symbols in the future) should be kept, it cannot be replaced with the new proposed list of currency symbols. If the list of currencies will be implemented, the current list of pairs/markets should also be kept. And this can be too complex for users, to have both approaches supported in the configuration.

**Comment by xmatthias** [comment]
I'm not sure i understand the point about the same quote currency...

>  "ETH_H19/BTC" and "ETH_M20/BTC".

you could specify these as "ETH_H19" and "ETH_M20" - quote-currency is BTC - no? - so this would still work ... ? 

> And this can be too complex for users, to have both approaches supported in the configuration.

this is a good point ... as said, i experimented about possibilities - but did not implement a single line within freqtrade regarding this yet...

**Comment by hroff-1902** [comment]
> you could specify these as "ETH_H19" and "ETH_M20" - quote-currency is BTC - no? - so this would still work ... ?

In the current aproach yes, but 1) this wont allow to trade markets with no slash in the symbol, 2) I think that quote/base currency should actually be taken from the ccxt market info dict, which contains 'quote' and 'base' items. So all current 'pair.endswith(stake_currency)' should be changed to `get_base_currency(market, stake_currency)`, where `get_base_currency()` checks the base currency against ccxt market info dict, not against the trailing part of the pair(market) symbol name. Same for qoute currency. This functionality already exists, after introducing `list-markets` command, the usage of this should simply be refined. This will easily allow to use options/futures market symbols that do not contain slashes in the names.
