### ISSUE TITLE
Suggestion for format of history data files

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2680]
* in sep. files for asset-timeframe, as now
* each file is a list of chunks.
* chunk = tuple or dict with {start_datetime, end_datetime, data}
* data is as now a list of ohlcv rows
* so current format is equal to one chunk, with no start_datetime, end_datetime stored
* the chunks are merged together (normalizing process) when they are stored:
```
    01.01    01.02    01.03    01.04    01.05    01.06    01.07
    |....|....|....|....|....|....|
Stored on disk (data for 01.01-01.02, one chunk):
    |========|        |        |        |        |        |
download-data 0105-0106
    |        |        |        |        |========|        |
Result: no normalization needed, stored 2 chunks on disk, for 01.01-01.02 and 01.05-01.06
    |========|        |        |        |========|        |

then

Stored on disk (two chunks):
    |========|        |        |        |========|        |
download-data 0102-0103
    |        |========|        |        |        |        |
Result before normalization:
    |========|========|        |        |========|        |
After normalization, two chunks (01.01-01.03 and 01.05-01.06), stored on disk:
    |=================|        |        |========|        |

then 

download-data 15.05-15.06. 
    |        |        |        |        |        |====|   |

-- only 01.06-15.06 downloaded, merged into the existing chunk, two chunks on disk: with data for 01.01-01.03 and 01.05-15.06
    |=================|        |        |=============|   |

```

* when you fill gap 01.03-01.05 on the "picture" above, there should be one chunk stored (merged with neighbours)...
* Why to store start and end timestamps in the chunks along with data? To keep leading and trailing unfilled candles in the chunks.
* Chunk is not for one month/day (it's only on the "picture") -- if you download N candles, it creates a new chunk of N candles, if it does not have a neighbouring chunk with which it can be merged)

Edited:
So now it's json of format: `[[date, o, h, l, c, v], [date, o, h, l, c, v], ...]`

I propose (json as well) `[{"start": start_timestamp, "end": end_timestamp, "data": [[date, o, h, l, c, v], [date, o, h, l, c, v], ...]}, {"start": start_timestamp, "end": end_timestamp, "data": [[date, o, h, l, c, v], [date, o, h, l, c, v], ..]}, ...]`

**Comment by hroff-1902** [comment]
^^ when you fill gap 01.03-01.05 on the "picture" above, there should be one chunk stored (merged with neighbours)...

**Comment by hroff-1902** [comment]
Why to keep start and end timestamps? To keep leading and trailing unfilled candles in the chunks.

**Comment by hroff-1902** [comment]
Chunk is not for one month/day (it's only on the "picture") -- if you download N candles, it creates a new chunk of N candles, if it does not have a neighbouring chunk with which it can be merged)

**Comment by xmatthias** [comment]
Please use the Edit button instead of spamming multiple comments (one per sentence ...).

**Comment by xmatthias** [comment]
first of all - that's a long way out - currently we ONLY support JSON - so we'll first need to make the storage format dynamic (i plan to work on that soon).

then:
why invent a new storage format when there's probably millions of formats out there to pick and choose from?

* What are the benefits of this format over other formats (not JSON!), which allow "seek" -> loading of only a subset of data from disk?

> Chunk is not for one month/day (it's only on the "picture") -- if you download N candles, it creates a new chunk of N candles, if it does not have a neighbouring chunk with which it can be merged)

so i could have 5m candles for today - and for 2 days ago - but would be missing yesterdays candles?
Assuming data is uninterrupted (which it should be, for backtesting) - then you'd always have a neighboring chunk of data ... ? 

Unless i misunderstand something, I think allowing this will result in very bad user experience, since backtest results will be inreliable (due to a lot of missing data "in between").


-----------
As mentioned above - this would basically reinvent a new storage format - which i don't think makes sense for freqtrade.
While Json is definitely not an ideal format for this type of data, there's a ton of other formats out there, and by supporting just a few of them we should be very well covered.

Think about the following formats - and then explain to me why we should spend our time inventing a new format, which is time we could spend improving things traders really care about (hint - it's not data formats as long as they work quickly and without errors).

* csv 
  * definitely not ideal - but will allow users to load data in excel ... which is what many "business" users love to use
* sqlite/ sqlalchemy (one database per pair / or one common database)
  * allows selecting data as needed - so i can have 1 year worth of data, but select only 3 days of 1m candles very efficiently without reading all 20Gb from disk.
  * also allow other databases like postgres or whatever is supported by sqlalchemy
* hdf5 
  similar behaviour to sqlite - but optimized for a ton of data in one file)
* influxdb
  optimized timeseries database - very fast (but has some setup overhead)
. . .

**Comment by hroff-1902** [comment]
it's still json -- list of dicts (or tuples in square parents)

**Comment by xmatthias** [comment]
that makes it even worse to me...

with json (and that's a problem with json in general) you always read the whole file - even if you only need 10% of it (data downloaded for all of 2019 for "full" backtests - but run backtesting for 1 month only).

Other formats will not do this, which makes them inheritly fast...

**Comment by hroff-1902** [comment]
definitely yes, but this suggestion is for current media, when data are stored in the json files. Without changing the "media".
Current implementation also reads all the data if we backtesting for one month an year ago. The suggested format allows downloading only that one month data, not for the whole year from the exchange.

**Comment by xmatthias** [comment]
I think i'm going to close this issue soonish if you don't object.

I don't see a point in having chunked data within one file, as you 

* increase the risk of having gaps in your history if the verification logic is not 100% solid
* complicate the handling of that data, since freqtrade needs to check if there are gaps in the data, ...
* lose the advantage of only having old data (smaller files) - so it would introduce a LOT of complexity without much gains
* create a lot of potential issues/questions from users complaining "i have data for 2 months ago and this month - why can't i backtest all 3 months" -> because the middle-month is missing (see below for more details).

Having gaps in the data is currently not possible and i think that's good that way.
Assuming you have data up to 20 days ago - and run `download-data --days 2` - it  would still download 20 days (not 2 days as requested), since gaps in the download are not allowed.

If this is really what's needed we can make a "slice" command which seperates parts of the data into a seperate datafolder so it's quicker to load from this - but with #2719 this can be captured/mitigated by using more efficient data-formats.

So you would have downloaded 2 years of data - and create one folder for 2018, one for 2019-01 - one for 2019-02, (and so forth).
This will allow quicker loading - which is impossible with the above format.

**Comment by hroff-1902** [comment]
closing as the proposal was rejected
