### ISSUE TITLE
new user-defined callback for buys/sells

### ISSUE THREAD

**Issue by maxma-bit** [freqtrade/freqtrade#2681]
In addition to populate_indicators/populate_buy_trend/populate_sell_trend, I propose to add four
new methods/callback, say: BUY_traded, SELL_ traded, BUY_ordered and SELL ordered.
Freqtrade runs the new callback Buy_traded (Sell_ traded) AFTER a BUY order (or respectively a SELL Order) is successfully completed on the exchange.
I believe that such new callbacks would be useful.
To explain, let's consider only SELL, it would be useful to have a callback that freqtrade run when a SELL operation is successfully executed on the exchange (i.e. to know that the trade BUY-SELL is actually successful seems a very relevant info for the strategy). In such a callback, one could program a dynamic strategy, that is to adapt the strategy dynamically based on the positive confirmation of the trade that took place.
For example, after a successful SELL, one could decide whether to issue another BUY straightaway, or whether to wait for a different condition to occur.
Namelly, this callback Sell_ traded could elegantly solve the freqtrade problem of locking the pair anyway after a SELL (to avoid the reopening of the trade if the buy-signal may still be active). With the callback Sell_ traded the user could explicitly program in this callback, if a BUY order should be issued again immediately so as to increase the frequency of trading, or to wait on some condition.

Finally, for completeness and generality,  I suggest adding also the two new methods (say BUY_ordered and SELL ordered) that freqtrade runs BEFORE a BUY order (or respectively a SELL Order) is successfully completed on the exchange. By way of example , the BUY_ordered callback could be usefull to amend the price/amount of the order. Or, to cancel an order before the unfilledtimeout expires, see issues #2646 .

**Comment by xmatthias** [comment]
> With the callback Sell_ traded the user could explicitly program in this callback, if a BUY order should be issued again immediately so as to increase the frequency of trading, or to wait on some condition.

I think this is an odd style to trade. you've just completed a trade and would like to buy the same pair again ... why not stay in the trade and avoid the 2x trading fees you'll be spending by doing a sell and buy order consecutively.

> one could program a dynamic strategy, that is to adapt the strategy dynamically based on the positive confirmation of the trade that took place.

This would not work with backtesting, since the callbacks will never happen in backtesting.
Backtesting works by analyzing the whole dataframe at once (For performance reasons - otherwise it would be dead slow) and then executing buys / sells based on the rules (max_open_trades, roi, stoploss, ...).

Even if we were to call the callback, you wouldn't be able to modify the buy signal since they're already set and analyzed before.

>  By way of example , the BUY_ordered callback could be usefull to amend the price/amount of the order. Or, to cancel an order before the unfilledtimeout expires

well how would you decide to do this? if it's in the strategy, it's something static ... so unfilledtimeout will work for that.
#2646 is about giving the user the possibility to decide when to cancel it while the trade is running - which needs to be done remotely - which i don't see well when every user needs to implement that method on his own in the strategy.

**Comment by xmatthias** [comment]
I don't think callbacks after the order is filled will make much sense, as they would be purely informative (return values would not be relevant).

Pair locking can now be done with [protections](https://www.freqtrade.io/en/latest/plugins/#protections).

callbacks for "before" an order is placed are available as [order confirm](https://www.freqtrade.io/en/latest/strategy-advanced/#bot-order-confirmation) callbacks with `confirm_trade_entry()` and `confirm_trade_exit()` respectively.
