### ISSUE TITLE
ask_strategy configuration

### ISSUE THREAD

**Issue by maxma-bit** [freqtrade/freqtrade#2682]
I'm having a little trouble understanding the part of the doc related to ask_strategy. In particular, the doc says that when ask_strategy.use_order_book is set to false, then the selling of open trades using Order Book Asks is not enable.
 However, it is not clear whatelse is the bot going to use to sell open trades? The documentation does not clarify what the alternatives are. What does the bot take as a reference to sell, if this parameter is false?
In particular, what is the difference between: (ask_strategy.use_order_book set to FALSE), and (ask_strategy.use_order_book set to TRUE and (order_book_min=order_book_max=1)) ? 
What's wrong with the following interpretation of the above two alternatives:
Assume that the ticker_interval is 15m.
Il (ask_strategy.use_order_book set to FALSE) then the ask price is kept the same for all 15 minutes.
While in the case (ask_strategy.use_order_book set to TRUE and (order_book_min=order_book_max=1)), then the ask price changes at every minute according to the first position of the Order-book?

**Comment by xmatthias** [comment]
Both of your options are not 100% correct.

The latest price (or order price) is always retrieved once the buy / sell decision has been taken - so we don't know the current price until we have a buy-signal (therefore it also won't stay the same ...).

> Il (ask_strategy.use_order_book set to FALSE) then the ask price is kept the same for all 15 minutes.

with orderbook disabled, we'll use the return value of the `fetch_ticker()` api endpoint - using the "ask" value for buying, and the "bid" attribute for selling. 
This represents the last value on the exchange - but it "may" lag a little behind - at least exchanges state to not use this to get the latest price, but use orderbook instead.

> While in the case (ask_strategy.use_order_book set to TRUE and (order_book_min=order_book_max=1)), then the ask price changes at every minute according to the first position of the Order-book?

With orderbook enabled, we'll fetch the orderbook (once the buy / sell decision has been taken) and use the corresponding side ('bids for buy,  'asks' for sell).

For Bids (buying) - we'll use the `order_book_top` quote from 'bids' (so if that's set to 1, it's the price closest to the other side, if it's 2, it's the 2nd price slot, ...).

for asks (selling) - it's slightly different:
It'll iterate each slot between `order_book_min` and `order_book_max` - and verify if the trade would be possible in this position. This has the advantage of placing orders early, hoping that the price moves up - and then being early in the queue for the sell.

Personally, i find this a very dangerous approach (since the order is placed, a stoploss on exchange would need to be candelled first) - but it can make sense if you're using very tight time limits (`unfilledtimeout.sell'). 

By setting `order_book_max` and `order_book_min` to the same value, you can archive the same behaviour than for buying - "picking" a spot in the orderbook queue as price.

**Comment by maxma-bit** [comment]
thanks for the clarity of the answer

**Comment by xmatthias** [comment]
i'll also add this in a similar way to the documentation ... so the next person doesn't have to open an issue ... and i don't have to dig through the code to get the answer 😆

**Comment by hroff-1902** [comment]
@maxma-bit pls verify the changes made to the documentation in #2686
