### ISSUE TITLE
Help in understanding strategy parameters.

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2688]
This issue has been off-topic from the very getgo, therefore i'll reopen it as #2696.

Please read the next message about what this issue is about.

**Comment by botsedge** [comment]
Thanks for explaining and here is a simple question from exactly the inexperienced (non python pro) user you mentioned.
How do i know the results of my strategy substeps?

I do not mean the obvious ones like ATR or BB or something i mean how do i know the result of a math expression for example? Can i log that somewhere?

When trying to handcode my strategy i see differences in the orderbook and on the chart (real world not backtesting) and i am trying to find out what causes this

- slippage
- commission
- time delay
- front running
- wrong parameter in strategy result
- other

for most trades i have ruled out slippage and commission since i can see that in my order history

But i am not so sure about my parameters so i would like to be able to log them somewhere if possible.

**Comment by xmatthias** [comment]
I'm not sure this belongs to this issue ... which is about subtle errors in the strategy which cause the bot to fail ... not about analyzing why a particular strategy performs worse than expected.

For your problem, best look at the [jupyter notebook](https://www.freqtrade.io/en/latest/strategy_analysis_example/ - or in `user_data/notebooks/strategy_analysis_example.ipynb`, where you can load your strategy, and look at the buy / sell signals it generates.

> When trying to handcode my strategy i see differences in the orderbook and on the chart (real world not backtesting) and i am trying to find out what causes this

I'm not certain what you mean with this ... orderbook is something that changes multiple times per second ... so that's kindof expected?

**Comment by botsedge** [comment]
I don´t mean to be off topic so i will take a look at the suggested links.

For the orderbook what i mean is:

Depending on the cryptopair the orderbook is not always changing within a second or even lower timeframes. If there is no or low volume available, the inside market can stay put for a very long time.
But once it changes the chart changes as well, so if the inside buy offer goes up so should the chart. 
Let´s say i expect my signal to be generated with the next up move and i don´t get a buy order generated by freqtrade then something is off. So in case of handcoding a strategy without using TA-Lib indicators i assume the mistake is in my own coding of the strategy (that is why i need to know the results of my strategy calculations)

As far as i understand freqtrade, the bot gets its realtime data via ccxt which in turn connects to the exchange configured in config.json
Most exchanges get their chart data via the [https://www.tradingview.com/rest-api-spec/](url) which means i can manually check my anticipated strategy parameters against a tradingview chart or against a tradingview chart within the exchange i am working with.

But the freqtrade built in indicators are calculated via the TA-Lib math not via the exchange built in tradingview indicators. There should be no difference in results since both probably use the same standardized math for an indicator but there could be.

If not using TA-Lib indicators there obviously is no difference and the problem always lies within the calculation.

This was just to explain what i mean with the orderbook issue mentioned earlier.

**Comment by xmatthias** [comment]
> Let´s say i expect my signal to be generated with the next up move and i don´t get a buy order generated by freqtrade then something is off.

well we only use completed candles by default - so if you are on 5m candles, you can only expect a change of signal every 5 minutes - orderbook movements don't really play a role in this - nor do "repainting" indicators - which would be recalculated intra-candle - but are a very dangerous thing since it's something you can't recreate / reconstruct once time moves on.

If you're using ta-lib, or any other library does not matter at all.

However, as mentioned above - this has nothing to do with this issue - so best open a new issue or join the slack channel to discuss problems you encounter.

**Comment by hroff-1902** [comment]
> I don´t mean to be off topic so i will take a look at the suggested links.

I'm sorry, but this is explicit offtopic and this is clearly seen -- all answers are for your questions and are not related with the initial topic content.

@xmatthias Should we:
* close this issue and create an new fresh one with the same topic content?
* delete the offtopic comments? (however, the questions and your answers (and mine if I post what have to answer) can be useful for other readers)
* something else?

I have more to answer @botsedge on indicators, tradingview and the differences in results, but I do not wish to make it HERE, where all this is complete offtopic.

**Comment by xmatthias** [comment]
I'll close this now, feel free  to comment / ask for reopen if the questions above have not been answered.
