### ISSUE TITLE
Sharpe Ratio formula incorrect (Hyperopt loss function)

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2727]
**edit @xmatthias **: Adding links to the most relevant comments - since this first post is empty anyway

Proposed solution calculation:
https://github.com/freqtrade/freqtrade/issues/2727#issuecomment-569979202
Addressing concerns about using daily returns: 
https://github.com/freqtrade/freqtrade/issues/2727#issuecomment-569988986
More concerns about using anything below <hourly returns:
https://github.com/freqtrade/freqtrade/issues/2727#issuecomment-570033907

**Comment by djacky** [comment]
It seems that the calculation for the Sharpe ratio (for the Hyperopt loss function) may be incorrect...Here is the calculation in the default file:

        expected_yearly_return = total_profit.sum() / days_period

        if (np.std(total_profit) != 0.):
            sharp_ratio = expected_yearly_return / np.std(total_profit) * np.sqrt(365)
        else:
            # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
            sharp_ratio = -20.
        return -sharp_ratio

It seems that you are first taking a daily average of the profits (over the timeframe period specified in the hyperopt function), and then calculating the Sharpe ratio using a standard deviation of the total trades. But I don't think this is correct. For the formula to be correct, you would need to first get an average daily standard deviation, and use that in the Sharpe ratio. Another way is to use the following formula:

        R = total_profit.cumsum()
        r = (R - R.shift(1))/R.shift(1) # for arithmetic gains
        r = R.diff() # for dollar gains

        if (np.std(total_profit) != 0.):
            sharp_ratio = r.mean()/r.std() * np.sqrt(365)
        else:
            # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
            sharp_ratio = -20.
        return -sharp_ratio

**Comment by xmatthias** [comment]
well yes, we know that the sharpe-ratio formula used is not 100% correct. 
Decisions taken when developing this are explained  https://github.com/MontrealTradingGroup/freqtrade/issues/2#issuecomment-511585756 and https://github.com/MontrealTradingGroup/freqtrade/issues/2#issuecomment-514295888 by the original author - basically the formula had to be adapted to suit day-trading over long-term investing it was originally developed for.

## current SharpeHyperOptLoss calculation

For the calculation - the total profit % is broken down to to "daily" profit - so if hyperopt has a timerange of 1 month, we divide by 30 (the number of days within that month). 
By then multiplying with `np.sqrt(365)` this result is annualized. 
Without doing this, we would not know which sqrt to take, since everyone can define a different timerange for hyperopt.

The variable name `expected_yearly_return` is a bit missleading here, since it's really daily returns, not yearly returns.

However, the mean is not the problem anyway - the Standard-deviation is what's really wrong (in both formulaes). We're using the standard-deviation "per Trade" (your formula does the same) - but it really should be run on an aggregated trade list (probably per day?) to be correct.



### Apart from that  / regarding your formula:

You're first using `cumsum()` to calculate `R`.
using `R.diff()` below (that's the only line that counts, since `r` is reassigned in line 3) has 0 effect other than removing the first value - since `diff()` is (almost) the inverse of `cumsum()` - so i guess you can save this step alltogether. 
Also - asuming you didn't change the first few lines of the function, then `total_profit` contains the profit percent - not the absolute profit - so this is NOT dollar gains.

Apart from that - by using `r.mean() / r.std() * np.sqrt(365)` - you're calculating the ratio "per trade" and annualize that, instead of "per day" (what `SharpeHyperOptLoss` currently does).

Now the annualization seems wrong to me in your formula - since the formula assumes to have a daily std-dev - but you're passing in a "per trade" standarddeviation - just as the current implementation does.


I'm sure this formula will work too, and will also help you hyperopting  - but it's not really closer to the original sharpe ratio formula than our approach - it's just ... different.


Anyway, hyperopt is not looking at the exact number the function returns, but instead is trying to minimize the value, so as long as a "better" strategy get's a better sharpe result, it'll be suitable for hyperopt. If sharpe should terminate at 10 - and this goes to 30 - possible - but not relevant as long as the the return of 30 is really a better result.

**Comment by djacky** [comment]
Thanks for the quick reply. 
First, yes you're right about the `cumsum()` and `R.diff()` functions I implemented...There was no need for that...sorry :) 
 
Also, yes your right, I'm using the Sharpe ratio based on each trade. I was just confused on why you were using the `expected_yearly_return` based on daily trades, and `np.std(total_profit)` based on each trade. For me, it just made sense to calculate the ratio on either daily trades, or each trade, but not mixing both (as is done in the default file). 

So if we wanted to calculate the standard deviation based on daily trades, and make everything consistent, how would we do that in this code?

**Comment by xmatthias** [comment]
Well the input - `results` is a dataframe with the following columns:

https://github.com/freqtrade/freqtrade/blob/3327ebf2b1dfcbf1d083cb1c7878fcc2075713b0/freqtrade/optimize/backtesting.py#L30-L45

so i guess you could resample (something like `results.resample('D', on='close_time').agg({'profit_percent': sum, 'profit_abs': sum})`) to get the sum of daily returns - and then work from there.

Note: the above is untested, just dumped out of memory ... and even though the column says `profit_percent` - it's not a percent value, but a ratio.

Note2: if you succeed in implementing this correctly - feel free to share :smile:  we're always looking for improvements

**Comment by djacky** [comment]
Thanks! Yea, I'll definitely work with this and see what I can do. I'll update this page if I find anything interesting...

**Comment by djacky** [comment]
With the resample command you provided, I think the correct Sharpe ratio can be computed as follows:

        sum_daily = results.resample('D', on='close_time').agg({'profit_percent': sum, 'profit_abs': sum})*100

        if (np.std(total_profit) != 0.):
            sharp_ratio = sum_daily['profit_percent'].mean() / sum_daily['profit_percent'].std() * np.sqrt(365)
        else:
            # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
            sharp_ratio = -20.

        return -sharp_ratio

Now, everything is consistent (mean and standard deviation based on daily results).
I'll test this out and let you know if I get good/better results.

**Comment by hroff-1902** [comment]
Daily results... And how to be when backtesting (hyperopting) on 1m timeframe for 6h timerange?

**Comment by djacky** [comment]
The Sharpe ratio is calculated based on daily results, but you can backtest with any timeframe you want. If you want to calculate the Sharpe ratio for different timeframes, you will have to change `np.sqrt(365)` to the value you wish based on your timeframe. You will also need to change the resample command that @xmatthias  provided from days to whatever frame you need. @xmatthias , is this possible?

**Comment by xmatthias** [comment]
it's a pandas function - obviously you can resample to almost everything (also 2 hours if you need to ...). 

I would advise against going < daily level though (maybe hourly level could work) - resample creates exactly one line per period - so resampling to minutes for a 1y timeframe wil result in 525600 lines - which will have a rather huge performance penalty.

i don't think that backtesting (nor hyperopt) for 6h timerange makes too much sense ... you'll probably see exactly one trend / move - everything < 1 week or 2 weeks even for 1m timeframes will most likely highly overfit and only lead to losses when deployed in real life - so i'd think this is a real edge-case.

While i don't see this as a valid concern since results will be bad anyway, we can still handle that by having this loss-function require a certain minimum timerange length to correctly work - so it could fail / require minimum 1 week of timerange to yield proper results.

On the other hand i'm asking myself if annualization of intra-day strategies does even make sense, or if we should monthlilize (is that a word??) short timeframes instead.

For example, for 5m timeframe, i'm closer looking at weekly / monthly returns - yearly will probably not be relevant since markets will most likely change (especially in this short timeframes) - and the strategy may not work 2 months from now, while yielding perfect results this and next month.

**Comment by djacky** [comment]
Generally, most people in the trading world speak of Sharpe ratios in a daily frame. There are also monthly frames, but rarely used. I have also seen rolling Sharpe ratios, but in my opinion, it's overkill. Implementing intraday Sharpe ratio optimization is a little risky because, as you stated, trends constantly change. But if people know what they're doing, then it may be an interesting feature. 

By the way, I tested the function in https://github.com/freqtrade/freqtrade/issues/2727#issuecomment-569979202, and it seems to be working quite nicely! I'm getting reasonable Sharpe ratio values now with good gains. So it looks good...everything is consistent.

**Comment by yazeed** [comment]
> Generally, most people in the trading world speak of Sharpe ratios in a daily frame. There are also monthly frames, but rarely used. I have also seen rolling Sharpe ratios, but in my opinion, it's overkill. Implementing intraday Sharpe ratio optimization is a little risky because, as you stated, trends constantly change. But if people know what they're doing, then it may be an interesting feature.
> 
> By the way, I tested the function in [#2727 (comment)](https://github.com/freqtrade/freqtrade/issues/2727#issuecomment-569979202), and it seems to be working quite nicely! I'm getting reasonable Sharpe ratio values now with good gains. So it looks good...everything is consistent.

Which timeframe did you end up using it for, on resample and np.sqrt()?

**Comment by djacky** [comment]
@yazeed On the resample, I use the daily time frame...so you have to use np.sqrt(365) in this case

**Comment by yazeed** [comment]
Just to sort of give feedback about my usage/testing of @djacky's hyperopt loss method, I think it successfully filtered 2 epochs for me today that claimed to have (8690%+ tot profit, but due to the daily resample, had less than -0.71 sharpe ratio). I imagine they would have distorted the results of the hyperopt under the default sharpe method, as these noisy trades below would have been accounted for.

```
========================================================= BACKTESTING REPORT ========================================================
| pair      |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration      |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-----------------:|---------------:|:------------------|---------:|-------:|
| VIA/BTC   |          21 |         399.25 |        8384.23 |       8.39261279 |        4192.11 | 2:48:00           |       10 |      0 |
```

@djacky's method did not bring this result as a best result even though it had the highest total profit %, while I imagine the regular sharpe method would have.

Note: Hyperoptimizing my own strategy, for past 2 years period, across top 90 assets on binance. Best realistic result with @djacky's method brought around (800% roi).

**Comment by xmatthias** [comment]
what timeframe were you using? 1h? daily?

**Comment by yazeed** [comment]
The interval for this strategy is 5m, and the resampled sharpe loss is based on daily. The result for VIA/BTC seems odd, what's the easiest way to print a table showing the trades history as exported in a back-test?

> what timeframe were you using? 1h? daily?

**Comment by xmatthias** [comment]
I would not necessarily print the list - but [load and analyze it interactively](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) ...

**Comment by yazeed** [comment]
Still not familiar with how to do it with Jupyter notebooks, I feel we could use a flag to simply sequentially print out trades exported via backtesting for ease.

> I would not necessarily print the list - but [load and analyze it interactively](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) ... (but in the end, you can use probably that method to load the backtest result and simply use `print(result)` ...

**Comment by yazeed** [comment]
@xmatthias What would also be really nice to have is a quick way to print out the trades of an epoch. Is that something I'm currently missing by any chance in freqtrade?

**Comment by hroff-1902** [comment]
> @xmatthias What would also be really nice to have is a quick way to print out the trades of an epoch. Is that something I'm currently missing by any chance in freqtrade? It might just be a shortcut to show the backtesting results table for an epoch result.

I thought about this: for backtesting, this may be an option, which prints the trades; for hyperopt it seems to be inconvenient, but for the `show-hyperopt` command this also be okay, similar option as for backtesting

**Comment by yazeed** [comment]
> > @xmatthias What would also be really nice to have is a quick way to print out the trades of an epoch. Is that something I'm currently missing by any chance in freqtrade? It might just be a shortcut to show the backtesting results table for an epoch result.
> 
> I thought about this: for backtesting, this may be a cli option, which prints the trades; for hyperopt it seems to be inconvenient, but for the `show-hyperopt` command this also be okay, similar option as for backtesting

Perhaps a flag can be provided to **show-hyperopt** to print trades for that epoch?

**Comment by hroff-1902** [comment]
> > > @xmatthias What would also be really nice to have is a quick way to print out the trades of an epoch. Is that something I'm currently missing by any chance in freqtrade? It might just be a shortcut to show the backtesting results table for an epoch result.
> > 
> > 
> > I thought about this: for backtesting, this may be a cli option, which prints the trades; for hyperopt it seems to be inconvenient, but for the `show-hyperopt` command this also be okay, similar option as for backtesting
> 
> Perhaps a flag can be provided to **show-hyperopt** to print trades for that epoch? That same flag can be applied to backtesting. This would be very convenient.

Exactly, like `--print-trades` or something like this

**Comment by quantitative-technologies** [comment]
> With the resample command you provided, I think the correct Sharpe ratio can be computed as follows:
> 
> ```
>     sum_daily = results.resample('D', on='close_time').agg({'profit_percent': sum, 'profit_abs': sum})*100
> 
>     if (np.std(total_profit) != 0.):
>         sharp_ratio = sum_daily['profit_percent'].mean() / sum_daily['profit_percent'].std() * np.sqrt(365)
>     else:
>         # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
>         sharp_ratio = -20.
> 
>     return -sharp_ratio
> ```
> 
> Now, everything is consistent (mean and standard deviation based on daily results).
> I'll test this out and let you know if I get good/better results.
> In `sum_daily`, you can even subtract some percentage to take slippage into account.

I haven't read through the rationale yet, but I also noticed that the currently implemented Sharpe Ratio is simply wrong. It will give apples and oranges comparisons for strategies that trade on different frequencies.

**Comment by djacky** [comment]
> > With the resample command you provided, I think the correct Sharpe ratio can be computed as follows:
> > ```
> >     sum_daily = results.resample('D', on='close_time').agg({'profit_percent': sum, 'profit_abs': sum})*100
> > 
> >     if (np.std(total_profit) != 0.):
> >         sharp_ratio = sum_daily['profit_percent'].mean() / sum_daily['profit_percent'].std() * np.sqrt(365)
> >     else:
> >         # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
> >         sharp_ratio = -20.
> > 
> >     return -sharp_ratio
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > Now, everything is consistent (mean and standard deviation based on daily results).
> > I'll test this out and let you know if I get good/better results.
> > In `sum_daily`, you can even subtract some percentage to take slippage into account.
> 
> I haven't read through the rationale yet, but I also noticed that the currently implemented Sharpe Ratio is simply wrong. It will give apples and oranges comparisons for strategies that trade on different frequencies.

The formula is correct if you are trading based on one frequency (in the code snippet, this would be based on the daily timeframe). It will obviously not work if you are comparing strategies with different frequencies.
