### ISSUE TITLE
where can i found new Strategy ?

### ISSUE THREAD

**Issue by rabinhod** [freqtrade/freqtrade#2736]
I'm just programmer and i have little knowledge about trading but it's not enough to create my own trade Strategy
where can i found new Strategy ?
and how Can I learn it ?

**Comment by xmatthias** [comment]
You can find a collection of strategies in the [freqtrade-strategy](https://github.com/freqtrade/freqtrade-strategies) repository.

A note of caution:
Not all are profitable, some only work for certain markets / certain periods of time (depending on the trend...).
They are there mainly to serve as a inspiration / template for your own strategies, not so much to be used "as is".

You'll still have to learn some about trading i would think - otherwise it may be very difficult to create anything remotely profitable. 

Also - make sure to don't take unnecessary risks by following the process -
* Backtest
* dry-run (also known as forward testing)
* only if the above 2 show acceptable results - trade real money

**Comment by rabinhod** [comment]
Thanks for the quick reply

I found just 5 Strategy in  [freqtrade-strategy](https://github.com/freqtrade/freqtrade-strategies) repository and i think they are a little old ! 
because i use them in Backtest and all of them didn't get good result !

I think the better way is i start to learn trading and write my own strategy !

**Comment by hroff-1902** [comment]
* You can try to migrate strategies from tradingview's Pine into freqtrade rules.
Tradingview contains sources available for their sample strategies. Add a strategy on a chart (Indicators & Strategies --> Built-ins --> select a strategy), then press Show Source Code for that strategy added to the chart. This will give you an idea for the strategy, which you'll be able to translate into freqtrade's buy/sell signals, backtest on the same timerange and compare the behavior...
* Classic trading/technical analysis books: Bollinger on Bollinger Bands, books by Ehler, etc -- they all contain examples of the strategies offered by the authors.
* Also may be a good starting point: The Encyclopedia of Trading Strategies Hardcover by Jeffrey Owen Katz Ph.D., Donna L. McCormick (https://www.amazon.com/Encyclopedia-Trading-Strategies-Jeffrey-Ph-D/dp/0070580995)

**Comment by hroff-1902** [comment]
> I found just 5 Strategy in [freqtrade-strategy](https://github.com/freqtrade/freqtrade-strategies) repository and i think they are a little old !
> because i use them in Backtest and all of them didn't get good result !

There a much more in a subdir: https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies/berlinguyinca 😆

**Comment by xmatthias** [comment]
@hroff-1902 i guess we should move these "up" a folder ...

**Comment by rabinhod** [comment]
@hroff-1902 @xmatthias 

Thank you for your time,

**Comment by hroff-1902** [comment]
> @hroff-1902 i guess we should move these "up" a folder ...

agree
