### ISSUE TITLE
sync / resync Wallet (refresh)

### ISSUE THREAD

**Issue by AndreWas1581** [freqtrade/freqtrade#2756]
Hello !
I am missing a feature like sync/resync wallet.

I've done a deposit to binance. It wasn't recognised by freqtrade.
Start/stop hasn't worked for this.
Changing the deposit from ETH to BTC and stop/start hasn't worked either.

Only shutdown an start new has taken the new amount into calculation.

**Comment by xmatthias** [comment]
Updating wallets is done every time the bot takes action (opens / closes a trade).

Doing this more often (like every iteration) would probably result in bans from the exchange, since the balance call is rather expensive (from an api limiting perspective).

This is also not exposed intentionally towards the user - so you cannot accidentally block your bot from the exchange (which can lead to losses due to sell-orders not being placed) by pressing that button too often, therefore i'm not sure if this SHOULD be exposed to the user at all.

`/reload_conf` would have worked for your case - since that will recreate the whole bot class.
However i think it's a rather limited case (waiting for the next buy / sell would be sufficient), since the balance is irrelevant to bot operations as long as it's not buying / selling.

I'll however also make sure that we're updating the balance before buying - as i'm not sure without checking.

**Comment by AndreWas1581** [comment]
There are two reasons that the balance can change.
First, like above, I've put some extra cash to the exchange to reach the minimum buy amount.
Second, Binance allows staking, there could be a (daily) reward which changes the amount of a coin.

In both cases I want to see the changed amount.

So there are two possibilities, first, let only freqtrade calculate and work with the known balance or second update the balances and use that amount.

**Comment by xmatthias** [comment]
The first part (making sure balance is updated before buying) has been implemented in #2734. 

I'll have a look at a refresh balance when `/balance` is called every hour or so (more often won't make sense - `/balance` is NOT made to replace checking balances on the exchange.
