### ISSUE TITLE
Issues hardcoded timeframes 15s timeframe - FTX

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2757]
## Step 1: Have you search for this issue before posting it?

yes

## Step 2: Describe your environment

  * Operating system: ubuntu
  * Python Version: python3
  * CCXT version: latest
  * Branch:  Develop
  * Last Commit ID: latest
  
## Step 3: Describe the problem:

*when using `freqtrade list-timeframes --exchange ftx` it will return "Timeframes available for the exchange `FTX`: 15s, 1m, 5m, 15m, 1h, 4h, 24h
"
then when trying to to download 15s then the error comes:
"freqtrade download-data: error: argument -t/--timeframes: invalid choice: '15s' (choose from '1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w')"

### Steps to reproduce:

  1. list available timeframes for ftx
  2. get 15s timeframes
  3. cant download 15s timeframe when trying to use `freqtrade download-data -c ftx.json --days 360 --timeframes 15s`
  
### Observed Results:

*it was explained above*

### Relevant code exceptions or logs:

  ```
freqtrade download-data: error: argument -t/--timeframes: invalid choice: '15s' (choose from '1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w')  ```

**Comment by xmatthias** [comment]
Amost identical to #1861 - but with another exchange-provided field.

**Comment by xmatthias** [comment]
While i agree that the timeframes should not be hardcoded, i think running on <1m tickers does not make much sense - and will result in almost exclusive losses.

If you think about it - assume you use only one pair - which takes ~1s to download history, and ~2s to calculate the indicators for - so now you're 3s into the candle (assuming process_trottle is set to 0 - so the bot continuously runs).

Creating the trade will require another 2 calls (one to get the price, and one to create the order). Unless you're on a VERY fast network, you'll buy 4-5s into the candle - which for a 15s candle is >30%.


On a side note: by removing the 15s limitation on startup, there are a ton of other points where this could fail, since all of freqtrade assumes a minimum of 1m ticker interval.

So while removing the hardcoded timeframe list - i will add a limitation for <1m timeframes (mainly to prevent people from losing unnecessarily).

**Comment by hroff-1902** [comment]
we can:
* get timeframes for all exchanges, take the union of all sets.
* check the timeframe at the bot startup

**Comment by xmatthias** [comment]
why? 
timeframe is only needed for "exchange-related" subcommands - so we can validate it within the exchange too (please check out the PR which implements this).

**Comment by hroff-1902** [comment]
btw, list of all timeframes (with `"block_bad_exchanges": false` set in the config):
```
$ for e in `freqtrade list-exchanges -1 -a`; do freqtrade list-timeframes --exchange $e -1 2>/dev/null; done|sort -u

10m
12h
15m
15s
1d
1h
1m
1M
1w
1y
20m
24h
2h
2w
30m
3d
3h
3m
45m
4h
5d
5m
6h
8h
```
-- just to have it here...

**Comment by denisdbv** [comment]
So, how can I switch to 15s? I get invalid choice.
