### ISSUE TITLE
FTX symbol_amount_prec wrong 

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2759]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: ubuntu19.10
  * Python Version: 3.7
  * CCXT version: latest
  * Branch: Develop
  
## Step 3: Describe the problem:

Bot found buy opportunities but can't buy using market 

### Steps to reproduce:

  1. Run with linkbull/usd pair on ftx
  2. Wait
 
  
### Observed Results:

  * What happened? It said couldn't buy 0.0
  * What did you expect to happen? To buy as usual. Do know that you can buy as small as 1 dollar on ftx spot markets (even less) 

### Relevant code exceptions or logs:

  ```
  2020-01-11 08:13:20,316 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 20 ...
2020-01-11 08:13:20,317 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2020-01-11 08:13:20,469 - freqtrade.freqtradebot - WARNING - Unable to create trade for LINKBULL/USD: Could not create market buy order on market LINKBULL/USD.Tried to buy amount 0.0 at rate None.Message: ftx {"error":"Size too small","success":false}                                                                                 
2020
  ```

**Comment by xmatthias** [comment]
This is not limited to market-buys - limit buys will probably suffer from the same problem (depending on the pair - most likely).

The problem is caused by ccxt returning precision as decimals - while the ccxt documentation states it should be "The amounts of decimal digits accepted"

> `precision`. The amounts of decimal digits accepted in order values by exchanges upon order placement for price, amount and cost.
[source](https://github.com/ccxt/ccxt/wiki/Manual#market-structure)

I've opened an issue with [ccxt](https://github.com/ccxt/ccxt/issues/6364) for this ... but honestly, this problem leads me to belive that FTX is not well integraded / tested with ccxt... which will mean that support in freqtrade is far far away.

**Comment by Dante2333** [comment]
Don't worry, I'll debug it.

**Comment by xmatthias** [comment]
@Dante2333 Creating dry-run trades now works with this version. I don't have an account on FTX - so please report back if it does work for you too, thanks.
