### ISSUE TITLE
Introduce the 'developer' mode

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2762]
Introduce the `--developer` option (a common one), which switches on some features we would not like to expose to the users, but what can be handy for devs. The option can be hidden -- no description in the argparse helpstrings. not listed in the available options.

Semantics:
I'm now thinking of
* Forces `"block_bad_exchanges": false`; to allow experimental working with bad exchanges without the need to change config everytime.
* Probably, after #2760 : allows trading for `15s` timeframe.

Short description can be added into development.md

**Comment by xmatthias** [comment]
well if it's just aboud "block_bad_exchanges" - then it should be called accordingly.

If it's about other, experimental / non-official settings (do we have these??) - then i'm against it.

Assume you run `freqtrade --developer` - and encounter a strange problem ... now which of the 5 settings that were implicitly changed did cause it?
 
you'll need to create a config and investigate one after the other anyway. 

Since we allow "incremenal" configs i think this is easiest taken on by the following:

```
freqtrade trade --config user_data/config.json --config user_data/config_devsettings.json
```

(with the 2nd config setting the configurations according to what you're trying to test at this point in time).

For the above reasons - i think a "explicit" configuration change changing what you're trying to test at this point in time will be better and cause a lot less frustration (on the developer side running this).

**Comment by hroff-1902** [comment]
Agree, I tried to understand for months what else besides switching off the check for bad exchanges could be included in this "mode" and did not yet found anything, the config (for the new exchange) can be used for this, with `"block_bad_exchanges": false` included.

Closing it now.
