### ISSUE TITLE
A few questions for the principle of operation in production

### ISSUE THREAD

**Issue by veffisot** [freqtrade/freqtrade#2767]
Hello,

I have a bot running in production mode so I would like to know some important aspects:
1. I launched with a white list of pairs and e.g. a bot bought currency in ETH / BTC pair. I have an active offer. If I start the bot again without this pair on the list, will the bot continue to observe and sell the currency from this pair when it reaches the conditions of the strategy?
2. Changing the number of active offers - I understand that increasing for more active offers should not be a problem. What if I now have 7 and change to 5?
3. Change the main unit of the cryptocurrency. Suppose I have ETH set to 0.1 Will something happen if I change to 0.05 or 0.2?
4. Is there a command that will stop all new purchases and just wait until it can sell active offers? (I want to reach the moment when all offers will be completed and I will have zero active offers). Is this how "/ stop" via Telegram works?

All questions have the assumption that I have several active offers.

**Comment by xmatthias** [comment]
I will assume that if you're talking about offers you really mean trades / positions.

1) active trades are tracked as long as the database is not reset / changed - so you can stop / restart the bot. Just make sure that the database file is not removed / changed - and if using docker, that it's mounted from the host system.
2) active / open trades are tracked, not considering the `max_open_trades` setting. This only affects new trades. see point 4 for side-effects of this.
3) this will only impact new trades, open trades will remain "as is".
4) no. `/stop` will stop the bot - so it will not look for sells too. the only thing that remains active in this case is stoploss_on_exchange - since that is, as the name implies - on the exchange. What you're looking for is `/stopbuy` - which will basically set `max_open_trades` to 0 - thus preventing new trades from being opened.

**Comment by xmatthias** [comment]
@veffisot Does the above answer your questions sufficiently so we can close this issue?

**Comment by hroff-1902** [comment]
closing it since no further info provided and the original post was answered
feel free to reopen
