### ISSUE TITLE
Real trading Vs. Backtest results

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2792]
I wanted to ask this community, how can we make the backtest results as close as possible to the results in real trading?

Obviously, the same strategy has to be used (with the same `max_open_trades`, `stake_amount`, etc...). But in terms of the `bid_strategy` and `ask_strategy` parts in the CONFIG.JSON file, how should we set this up so that the results in real trading are as close as possible to the backtest results?

**Comment by xmatthias** [comment]
the short answer is - you can't.

Backtesting has to take certain assumptions (listed [here](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting).

bid / ask strategy are defined by current price action (or orderbook)... which is intra-candle data- which is unavailable during backtesting.

Just think about a regular candle. 
Unless you look at lower interval data, you won't know what happened intra-candle - you know how it opened, and how it closed - and which were the high and low points.
But - did price jump from Open, to Low, to High, to close - or from Open, to High, to Low, to Close?
or something else?

### An example: 

Assume you hit a stoploss - backtesting will take the stoploss value as the sell-price.

In real trading, you may get this value as sell price too- or price jumped by another % lower - so that's the rate you'd get at that point. 
This can be somewhat mitigated by using `stoploss_on_exchange` (if available for your exchange) which should guarantee you the "correct" rate - but that still assumes that the coin had the liquidity to fill your order.

You can add slippage parameters (or something else) to modify the backtesting results - most of which will change backtest results one way or another - but it still won't be aligned 100% to real trading - as you won't always get the same slippage for all trades, as that will rely on sub-second market data.

not considering the difficulty to acquire this data - the sheer volume of data will kill every backtest you'd try to do based on this data when using more than a few pairs for a very small timewindow (you can probably simulate this by backtesting 1m for more than 2 months with more than 10 pairs [precise numbers will differ based on your pc specs]).

**Comment by djacky** [comment]
@xmatthias thanks for the quick response! 
I suppose that you would get the worst slippage when `ask_last_balance` = 0 (since this would just buy at the current selling price)...Given the limited data, yes I think approximating the slippage into the backtest results would be the best option...I guess this would be done in the BACKTESTING.PY file with something like `results.profit_percent - x`, where `x` is the slippage percent you want to approximate (similar to what is done in the HYPEROPT_LOSS_SHARPE.py function).

So I guess running in `dry_run` mode would be the best option to simulate real trading. Am I correct in asserting that when a buy order is sent in this mode, the worst case slippage is taken into account (since it is just buying at the current selling price)?

**Comment by xmatthias** [comment]
> ..I guess this would be done in the BACKTESTING.PY file with something like `results.profit_percent - x`

For backtesting, it is probably not that simple as the data may be reused going forward (assuming you export the results).

Technically - slippage in backtesting is implemented  (hidden) and can be simulated by using a fixed fee (binance has 0.001 as fee - so supplying `--fee 0.0015` would simulate a slippage of 0.05% (adjust to your needs). [documentation](https://www.freqtrade.io/en/latest/backtesting/#supplying-custom-fee-value).

Since using a static slippage will have exactly the same effect - i don't think it's worth to separate this into a dedicated parameter - as all we'd do in this case is add it to the fee multiplier anyway.

> So I guess running in dry_run mode would be the best option to simulate real trading. Am I correct in asserting that when a buy order is sent in this mode, the worst case slippage is taken into account (since it is just buying at the current selling price)?

Well assuming you use limit orders (the default setting) - then you place the trade at the best spot without invoking a market order (which would happen for buying, if `limit > best ask`, for selling  `bid < best bid`).

so - let's assume the following orderbook (heavily simplified):

```
...
102
101
-------------Current spread
99
98
...
```

last trade filled at 100.

Now using ask_last_balance = 0.0:
A buy order would be placed at 99 - a sell order would be placed at 101.

using ask_last_balance = 1.0:
A buy order would be placed at 100 - a sell order would be placed at 100.

Using anything between will be used as ratio (0.5 would place it at 100.5 / 99.5 - if that's an allowed value for this pair).

Now in the 2nd case - you'd have the "top spot" and the next coming in and trying to market-buy would be filled with your order.
Obviously you've also given away 1% of profit (in this case - usually lower).

Using 0.0 on the other hand will put you to the "end of the queue" in this orderbook slot - which may have it's downsides as well.



Note: this is an unrealistic example ... you could make wins purely based on the spread in this scenario...

**Comment by djacky** [comment]
Thanks for the detailed explanation @xmatthias ...
So just to confirm, setting ask_last_balance = 1.0 allows you to buy faster (with the risk of high slippage)
And setting ask_last_balance = 0 allows you to buy slower (and possibly reduce slippage)...is my understanding correct? I was under the impression that it was the other way around because on the freqtrade website, it stated the following:

> The bid_strategy.ask_last_balance configuration parameter controls this. A value of 0.0 will use ask price, while 1.0 will use the last price and values between those interpolate between ask and last price.

So from this statement (and from your example above), it seemed that ask_last_balance = 0 would set a buy order of 101, and ask_last_balance = 1 would set a buy order of 100...

**Comment by xmatthias** [comment]
a buy order will be placed at 99, or 100 (for the above example). If it were placed as 101 (assuming the sample above) - it would be converted to a market order (all exchanges i used so far)- which would usually mean higher fees (on some exchanges / depending on the level).

`ask_last_balance` is NOT about faster or slower - it's about the price that's used. If it's filled fast, slow, or not at all, does not depend on this setting - but how the market reacts / moves forward. 



If you look at the relevant code for this:

https://github.com/freqtrade/freqtrade/blob/9c2f21b07eda29a16849892a6b83ef739c98e05b/freqtrade/freqtradebot.py#L243-L250

`ask_last_balance` only comes into play if ask < last (see example below)

The example above assumes a pretty static situation - where the last trade was exactly in the middle of the spread - and markets did not move.
However, crypto markets can move within subseconds (or be illiquid, having 0 trades for minutes)- so let me do another example:


```
...
102 <- last trade
101  # asks
-------------Current spread
99   # bids
98
97
...
```

In this case price is pushed down by available orders (but until no trade is filled "last" won't change).
so it would use 101 or 102 (assuming `ask_last_balance` is 0 or 1 - or 101.5 if ask_balance is 0.5).
now the calculation is done using `ask + ask_last_balance * (last - ask)` , 
which in this case translates to 
`101 + ask_last_balance * (102 - 101)`.


### ...
Thinking about this - I'm currently concerned if buying looks at the "right" side of the orderbook ... since irrelevant of the `ask_last_balance` ratio - it'll always be filled immediately (and probably as marketable order).

i suppose #1059 tried to highlight this issue too (but not clearly stated that we look at the wrong side) - but the "marketable" problem can also come in if you place the buy-order at 99 and the price moves lower just in that second - so i suspect that's why that was missed.

**Comment by djacky** [comment]
Let's look at each possible scenario and see what we can deduce from this...

- if `ask = 101 < last = 102`, a buy market order would just be filled at the price of 101 (because the buy price would be between 101 and 102 for any `ask_last_balance` in (0,1)). 

- if `bid = 99 < last = 100 < ask = 101`, then the buy order would be  `ask + ask_last_balance * (last - ask) = 101 +  ask_last_balance * (100 - 101)`. So in this case, the buy order would be anywhere between 100 and 101. Thus setting `ask_last_balance = 0` for this case would be equivalent to doing a buy market order.

- if `last = 98 < bid = 99 < ask = 101`, then `ask + ask_last_balance * (last - ask) = 101 +  ask_last_balance * (98 - 101)`. So in this case, the buy order would be anywhere between 98 and 101. Again, setting `ask_last_balance = 0` for this case would be equivalent to doing a buy market order.

Is my interpretation of the equation correct?

**Comment by xmatthias** [comment]
i think the first point is wrong.

1) `ask_last_balance`  is irrelevant as "ask" will be used (first branch of the if - since `ask < last`).

2 / 3: setting `ask_last_balance =0` will always use the last ask price. 


Now while this is important (so let's not stop with this) - it's not related to real / backtesting alignment. 

In my opinion, none of the options related to price in either `bid_strategy` or `ask_strategy` will have a huge influence on alignment.
They're relevant to determine if the order is filled or not (and how quickly / at what price) - but backtesting does not have any of these prices unless they happen to "collide" with the candle's open.

**Comment by djacky** [comment]
Thanks @xmatthias ...
I think `bid_strategy` or `ask_strategy` will have some influence because if orders are not filled (or partially filled), then that could have a huge impact on the results. Backtesting assumes that all orders are instantly filled as soon as the strategy condition is satisfied. But in real trading, partial or unfilled orders can have a big influence...here is an example (assume constant stake amount):

Backtest results (for one day, for example):
`Ticker A: profit = 1.5% (order fully filled)`
`Ticker B: profit = 10% (order fully filled)`
`Ticker C: profit = -5% (order fully filled)`

Real results:
`Ticker A: profit = 1.5% (order partially filled: 20% fill)`
`Ticker B: profit = 10% (order partially filled: 10% fill)`
`Ticker C: profit = -5% (order fully filled)`

You can see that in real trading, there is a significant loss because of the ordering process...that's why I thought that `bid_strategy` or `ask_strategy`  were important factors with respect to the backtest results. But I guess that it is really difficult to backtest these kinds of situations because it requires large amount of data (as you had stated earlier). But it may be possible to do this if trading with longer candle intervals. For example, if trading and running a strategy with daily candles, one can use minute candles to simulate the order filling. 

What might be interesting for the backtest is to implement a kind of random filling process for each order, run several iterations with random fills, and then take the average of those iterations for the backtest. One can even set the fills based on the volume of each ticker (where tickers with high volume can have a higher percentage fill and tickers will lower volume can have a lower percentage fill). This might be an interesting project.

**Comment by xmatthias** [comment]
to be honest, i don't think that simulating unfilled orders makes sense. it'll consume a ton of processing power with almost no gain - but that's about it.

Based on me running the bot, i almost never experience unfilled / half-filled orders. 
I suspect it's a question of strategy in combination with timeouts, stake-amount and the pairs you're trading - but i still find it overkill to try and simulate something which does occur completely at random.

> But it may be possible to do this if trading with longer candle intervals. For example, if trading and running a strategy with daily candles, one can use minute candles to simulate the order filling.

While filling up daily candles with minute data sounds like a good idea in theory - memory won't play along with this, and backtesting 1 month with 1d candles will not make anyone happy.

It'll have the same constraints we have now with backtesting 1m candle data.
You can only do a handful of pairs once you pass the 1 month timerange ... which isn't such a huge problem when backtesting based on 1m data ... but it is for daily candles - since then you only got a history of 30 days to generate even one signal - which will kill even the simplest SMA50 strategy right away.

Sure, you could avoid loading the data to memory and load that from disk "at request" - but that'll make backtesting unusably slow as an SSD is a lot slower than any memory - and thinking about a strategy with a decent amount of trades, it would mean loading the data from disk 100ds of times.


## Assume unfilled order simulation

Assuming we could easily simulate unfilled orders via some random function - backtesting would not be aligned any better, but most likely worse in most cases- since you can never have backtesting know which of the trades will not fill - so it'll be completely random, pushing backtesting results either above or below real trading results.

Your example pulls profit down - but if the stoploss-trade entry isn't filled at all (trade C) - backtesting will suddenly show a spike of 5% - which is a LOT worse than being aware that unfilled / partial filled orders are not accounted for.

Also, since it'll be using some random assignment - running backtesting 5 times in a row will cause 5 different results. 

By using a average over these results we'll automatically falsify results even more - i can go months without an unfilled trade - backtesting on the other hand may always "randomly" assign one or more - so it's wrong "just like that".



> What might be interesting for the backtest is to implement a kind of random filling process for each order, run several iterations with random fills, and then take the average of those iterations for the backtest. One can even set the fills based on the volume of each ticker (where tickers with high volume can have a higher percentage fill and tickers will lower volume can have a lower percentage fill). This might be an interesting project.

For this you don't need to run backtesting more than once. Export results, load them into a jupyter notebook, and "play" with reducing the amounts at random (obviously recalculating profit after that).

Yes, the endresult will change (total profit) - but what it'll tell you in the end is nothing about your strategy. Profit % will be identical (not the absolute profits, obviously).

---------------

Personally, i think if you're experiencing a lot of unfilled trades, you might want to reconsider the pairs you're trading as they're most likely very low volume pairs - which are dangerous as that these might mean that you're unable to get out of a trade via stoploss.

**Comment by djacky** [comment]
Indeed. Profit % will not be changed, but absolute profits will. Perhaps some of my coins had low volume, and was causing this discrepancy...I will look into higher volume coins and see if this makes a difference. Thanks for your help @xmatthias !
