### ISSUE TITLE
Forcesell didn't update Balance

### ISSUE THREAD

**Issue by AndreWas1581** [freqtrade/freqtrade#2793]
## Step 1: Have you search for this issue before posting it?

Not found a similar question

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: 2.7.17 / 3.6.9____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master
  * Last Commit ID: 7c53dcb0afd2ad663faad4bc03406f0575c87f6b(`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
After /Forcesell XX Balance isn't updated.
Before Forcesell : 
BTC:
 Available:  0.00274315
After Forcesell : 
BTC:
 Available:  0.00274315

Balance on Exchange (Binance) 
0.00326254

Looks like /forcesell sells the given Amount but didn't update the Balance (BTC).

### Steps to reproduce:

  1. /balance
  2. /forcesell XX (Telegram-Bot)
  3. /balance

**Comment by xmatthias** [comment]
A few questions first:

does /balance also contain the balance of XX (the sold currency) - or is this gone in the 2nd call?

I think this should be fixed in #2768, in combination with #2734 most likely.

One thing to consier about this: 
`/balance` is a convenient feature - however calling it too often will lead to blocks on the exchange - therefore manually calling it is limited to 1 per hour (using the latest develop) - this is not implemented in master (what you are currently using) at all.

Also, it's not intended to replace looking at balance on the exchange - /balance does not claim to be 100% uptodate all the time and may be lagging behind.

**Comment by AndreWas1581** [comment]
It looks like : 
/forcesell has sold the coins against BTC
/balance didn't notice, it's the same after several hours.
A /balance after a buy shows the right amount of BTC.

The steps of the balance are only recognisable if you calculate them in your poket calculator.

Maybe you can alter the message of /balance, that it will only be checked if a buy/sell occurs.

To your question above, I was only looking at the BTC-balance, which was the same.
After 3 hours it was still the same amount.

After a buy the /balance is right, and it's also right for all other coins. (some had wrong value)

#2768 is the same, thank you for finding.
So we can close this problem.

**Comment by xmatthias** [comment]
i'll have a closer look at the code before closing ... but it should (in theory) be fixed in the latest develop version - assuming a maximum of 1h delay is acceptable.

we maybe should put this as a note in the documentation ...

**Comment by xmatthias** [comment]
You're right - in case of forcesell wallets are not updated if the trade fills immediately (either via market order - or by luck with a limit order).

should be a quick fix

**Comment by hroff-1902** [comment]
@AndreWas1581 thanks for reporting 👍 

The fix has been merged into the current develop branch, pls verify.
