### ISSUE TITLE
Allow arbitrary ccxt arguments in top-level 'exchange' settings branch

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2863]
As a follow up after #2860, to log the possible enhancement in a sep. issue:

In order to avoid duplication of same sub-account name (that's only one possible application), we could allow passing arbitrary data items from `'exchange'` top-level settings branch as kwargs, as it's done for `ccxt_config` and `ccxt_async_config` (and values in `ccxt_config` and `ccxt_async_config` will be merged with top-level settings).

So it will also enable my configuration ('headers' item above, in the top-level 'exchange' branch of settings) I (errorneosly, since now it's impossible) proposed in #2860. 

With this, the rateLimit setting can also be used straight in the 'exchange' branch, if same value is supposed for use in both `ccxt_config` and `ccxt_async_config`.

**Comment by xmatthias** [comment]
Doing it on the top level exchange object is a terrible, terrible idea (and it's not needed, either).

for the async version of the exchange - neither the API keys, nor the subaccount name (nor anything else) will matter - so you only need it in `ccxt_config`.

Now we can add a combined subkey which will be added to both ccxt objects if that's really needed (i think it's not - see above for why).


But passing the whole exchange object into the ccxt constructor is very prone to breaking ccxt. keep in mind that every KwArgument passed to ccxt will be added as attribute to ccxt.

This however means that if the kwargument accidentally collides with a function name - it'll overwrite that function name, breaking freqtrade/ccxt in a way that's very difficult to debug.

Doing this will limit our ability to add any additional attribute to the exchange key - and future versions of ccxt may break for certain exchanges, due to naming collisions (not even sure if they would not break today).

**Comment by hroff-1902** [comment]
> Doing it on the top level exchange object is a terrible, terrible idea (and it's not needed, either).

I meant the top-level of exchange branch of settings, it's not about Exchange objects, only about settings.

**Comment by xmatthias** [comment]
Yes i know. 
See above for reasons as to why... It'll limit our ability to add new configuration options to the exchange.

**Comment by hroff-1902** [comment]
okay, agree, closing this.
