### ISSUE TITLE
config structure for ask/bid strategy

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#2867]
The ask/bid_strategy config objects include these options:
- `use_sell_signal`
- `sell_profit_only`
- `ignore_roi_if_buy_signal`
That were moved from experimental some time ago.

This I think is a little confusing because the rest of ask/bid strategy deals with orderbook based config, and in general is not backtestable.
So I think it would be better to semantically separate options that can be (potentially) tuned with optimization, from live only options.
Now this reasoning is invalidated if backtesting gets orderbook support, which is unlikely...so I dunno.

**Comment by xmatthias** [comment]
I doubt backtesting can get orderbook support (simply because the data isn't available).

However, i agree with your reasoning - having this in bid/ask_strategy is also wrong if we start supporting short trades - since then "sell_profit_only" would apply to the "other" side. It's also wrongly worded then though - as it should be called "exit_profit_only" - but i guess that's a different topic.

On the other hand - i tend to leave these options out of my configs completely, and define them at the strategy level - where it doesn't matter where in the configuration the options are copied to.
Assuming tuning - i am working at the strategy, and keep the config the same - that's the simplest way to get consistent (well hopefully improving) results.

**Comment by hroff-1902** [comment]
when shorts will be supported, then bid_strategy/ask_strategy should probably become enter_trade/exit_trade in the config, if they left in the config
