### ISSUE TITLE
Bad trailing stoploss behaviour

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#2873]
So I just came across this weird case where freqtrade bought SNT/BTC and market sold it instantly, not sure why it had to “emergency_sell” it. Said binance order would trigger immediately, is it because of moving books? Why not try again? This actually caused it to market sell it, 1 sat below its open_rate.

```
2020-02-05 22:07:22,469 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=102, pair=SNT/BTC, amount=3543.14974799, open_rate=0.00000157, open_since=2020-02-05 21:00:36)
2020-02-05 22:07:23,471 - freqtrade.persistence - INFO - Updating trade (id=102) ...
2020-02-05 22:07:23,471 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=102, pair=SNT/BTC, amount=3543.00000000, open_rate=0.00000157, open_since=2020-02-05 21:00:36).
2020-02-05 22:07:23,970 - freqtrade.exchange.binance - INFO - stoploss limit order added for SNT/BTC. stop price: 1.41e-06. limit: 1.4e-06
2020-02-05 22:08:30,132 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{43408958})in order to add another one ...
2020-02-05 22:08:31,134 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market SNT/BTC. Tried to sell amount 3543.0 at rate 1.62e-06. Message: binance Order would trigger immediately.
2020-02-05 22:08:31,134 - freqtrade.freqtradebot - WARNING - Selling the trade forcefully
2020-02-05 22:08:32,158 - freqtrade.persistence - INFO - Marking Trade(id=102, pair=SNT/BTC, amount=3543.00000000, open_rate=0.00000157, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2020-02-05 22:08:32,158 - freqtrade.persistence - INFO - MARKET_SELL has been fulfilled for Trade(id=102, pair=SNT/BTC, amount=3543.00000000, open_rate=0.00000157, open_since=closed).
2020-02-05 22:08:32,632 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'exchange': 'Binance', 'pair': 'SNT/BTC', 'gain': 'loss', 'limit': 1.6342534e-06, 'order_type': 'market', 'amount': 3543.0, 'open_rate': 1.57e-06, 'current_rate': 1.56e-06, 'profit_amount': -1.407e-05, 'profit_percent': -0.00252728, 'sell_reason': 'emergency_sell', 'open_date': datetime.datetime(2020, 2, 5, 21, 0, 36, 100588), 'close_date': datetime.datetime(2020, 2, 5, 21, 8, 32, 158033), 'stake_currency': 'BTC', 'fiat_currency': 'USD'}
2020-02-05 22:08:32,690 - freqtrade.freqtradebot - WARNING - Could not create trailing stoploss order for pair SNT/BTC.
2020-02-05 22:08:32,690 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Attempt to handle closed trade: Trade(id=102, pair=SNT/BTC, amount=3543.00000000, open_rate=0.00000157, open_since=closed)
2020-02-05 22:08:33,946 - freqtrade.freqtradebot - INFO - Pair SNT/BTC is currently locked.
```

**My trailing stop configuration is as follows:**
```
    # Trailing stop
    # These attributes will be overridden if the config file contains corresponding values.
    trailing_stop = True
    trailing_stop_positive = 0.01551
    trailing_stop_positive_offset = 0.03581
    trailing_only_offset_is_reached = True
```

Apparently this is because for **snt: Removed SNT/BTC from whitelist**, 1 unit is 0.637%
if this moves 2 pips, it's 1.2% ... which is too close to your "trailing-stop-positive". Reference: @xmatthias on slack.

It did this 3 times within 24 hours, incurring the only losses my strategy had out of more than 35 5m trades. So it's obvious why I'd want to solve this, without changing my trailing stop loss configuration.

I propose the following, a mechanism for freqtrade to calculate this before opening the trade, since it knows in advance which price it would buy the pair at, and where it would need to place the stoploss/trailing stoploss at beforehand. Avoiding such trades, would help ensure smarter trade execution by freqtrade.

The current behaviour causes you to lose trading fees + spread by such unintentional trades.

Once we agree to a solution, we can then start working on a PR.

**Comment by xmatthias** [comment]
Honestly - the solution to this is rather simple - we have the [Precision filter](https://www.freqtrade.io/en/latest/configuration/#price-pair-filter).

In the end, you have 2 options for such pairs - increase your stoploss (giving this pair more room for small downward moves) - or filter out pairs where 1 trade can move the pair for 1% (if ou want to keep a stoploss at 1.5%, that is).

Its perfectly valid to have a pair with a high minimum tradable value in the pairlist if the strategy is aware of that and the stoploss / ROI / whatever must be adjusted to that - giving it room to move.

> I propose the following, a mechanism for freqtrade to calculate this before opening the trade, since it knows in advance which price it would buy the pair at, and where it would need to place the stoploss/trailing stoploss at beforehand. Avoiding such trades, would help ensure smarter trade execution by freqtrade.

we do check stoploss capability below (so if a pair trades at the minimum tradable price, and minimum tradable lotsize) - protecting against the case where you buy 20X - but if price drops too much minimum tradable size becomes 25X (so it's dust - unsellable amounts).

Now your check is more difficult - and you need to consider what's actually happening when this error happens.

Assume this case:
Freqtrade intends buys the asset at 100 - intended stoploss (based on your configuration) is 98.5 (1.5% below).
So any check verifying that stoploss > initial buy price will always be correct (stoploss must be negative).

To come back to your logs
SNT was bought at 0.00000157 - with an initial stopprice of 0.00000141 - which was the order it was able to place.
With that - the check you're proposing will not make sense as it wouldn't have prevented this case anyway - as the initial stoploss (11% below entry) was placed correctly.

It's the trailing stoploss that's pulled too close. 

------

Now based on your logs - it tried to place a new trailing stop at 0.00000162. That's 3% above the entry price.
The pair moved above that on the 5th feb in the UTC afternoon (this is 4ish pm) - but only for a very short amount of time. 
Between cancelling the stoploss, and creating a new one, the price moved that 1% below it's high again (this can happen in split-seconds in crypto trading - especially with pairs which move 1% per 2 tiks).
Now since price moved below the stoploss limit again - placing the stoploss did fail on the exchange.

![2020-02-07-063401_1126x557_scrot](https://user-images.githubusercontent.com/5024695/74003697-d6152c80-4973-11ea-9455-041350b3d4a7.png)

The reason for creating a forcesell is protection of your assets. Your configuration told freqtrade to place the stoploss at 0.00000162. With trailing stoploss, this stoploss will never be lowered anymore, so while freqtrade could retry - it wouldn't be able to place the stoploss before price moves above this bar.

Problem with that is - if the pair dumps, you'd lose all your money in that trade - so forcing this trade to be sold will protect your assets (yes, it caused losses - but only a few % - not 100%).

**Comment by yazeed** [comment]
Thanks for the thorough explanation here, I've been testing it out in the past few days, and you're right about how it happens.

Nowadays with increased volatility on altcoin it seems to be even more common.

I have a proposal in terms of what could be done here instead of immediately market selling, to try and place the limit sell order one tick below current price, once and if that fails too, then maybe it's best to market sell. The reason I'm suggesting this is that market sells can sometimes cause too much slippage.

**Comment by xmatthias** [comment]
well if you want a limit sell instead of market - then that's possible too: [docs](https://www.freqtrade.io/en/latest/configuration/#understand-order_types)

simply use 
```
order_types = {
    "emergencysell": "limit",
  }
```

It will not retry with market afterwards - but why should it ?
Placing a limit order will almost never fail - not because price moved to "something".
For binance - it may convert it to a marketable limit order (selling it immediately at best price) - if the sell limit was below the current price. in that case, you'll not get "Limit" - but a more favorable price for yourself.

if the sell-limit is placed above current price - it'll simply stay there until it's cancelled or price moves "back up" to that level.


If you think about it, freqtrade tried to place a stoploss and failed now it placed a new limit order (which will work).
If that limit times out (regular sell timeouts apply) - then it'll cancel that order and place a new limit order.
"Emergency" is over the moment the sell-order was placed correctly.

**Comment by yazeed** [comment]
@xmatthias I thought about doing that, but using limit for emergencysells is too much risk, as too fast price slippage can skip an order potentially causing you to lose higher than intended on some pairs.

I'd like to keep this issue open for a bit more time as I investigate potential enhancements in this area. Specifically, I'd like to first understand why I'm getting too many emergencysells, due to moves in trailing stop loss price being attempted above current pair price.

I have tested against this by adding small logic to prevent trailing stop from ever being attempted above current price, and it seemed to enhance my exits to a great degree. I don't feel ready to submit a PR for it yet though, still playing with it and testing it.

**Comment by xmatthias** [comment]
> I understand PrecisionFilter can help avoid this all together, potentially, but I'm exploring a potential enhancement without having to skip entire pairs.

I don't think it's `PrecisionFilter` - but `PriceFilter` that can help you with that, eliminating very low value pairs.
PrecisionFilter only considers your initial stoploss - trailing stoploss setings do not matter (it's a protective filter against pairs at the lower end of the tradable range).


Honestly, if you're having a lot of emergency sells because of stoplosses placed above current price, you're most likely trading pairs which have a rather high 1pip % change in combination with a very tight stoploss.

----

Trading very low-value pairs is valid - but you need to adjust your strategy to it - and use a larger stoploss (also larger trailing stoplosses).

Using a tight stoploss for such low-value pairs will also cause huge missalignment between backtesting and real mode (which wouldn't be a problem for ETH/USDT - for example).

The reason for that is how we evaluate trailing stoploss - we assume high first (adjusting stoploss) - and then low (causing very quick sells very often).

While this is realistic to a certain extend, it's problematic if the minimum change of a candle is 1% (1pip = 1% change) - then this will trigger a sell every single time.
visually, you can identify these pairs easily (see screenshot above for example) - all candles seem rather long - but most only changed 1-2 units.

In reality however, price may move to low first, then high ... but high is not relevant anymore, as low already caused the stoploss to trigger.

**Comment by xmatthias** [comment]
Will close this as the reason has been explained (too tight a stoploss on a pair with "binary" patterns).
