### ISSUE TITLE
Feature/enhancement- adding bot uptime.

### ISSUE THREAD

**Issue by sanket-k** [freqtrade/freqtrade#2885]
I would like to suggest a feature, adding bot uptime to be viewed via telegram alerts  it would reset if the bot is restarted, with the `/stats` option as suggested by @xmatthias .

e.g if my strategy was based on a higher time frame maybe 4h, and the market is currently going against the rules, so it would just not trade for days or maybe a week, in that case i would want to know just how long the bot is up (and if i need to re-think my strategy)
same goes if my strategy has too many entry conditions

**Comment by hroff-1902** [comment]
for this particular case you should better calculate the calendar/hours externally, in an external tool/script, since freqtrade process might fail and be restarted by systemd, for example -- so it won't keep proper uptime anymore...

but I'm not against this idea, even think that this info can be useful (or attractive to a user)

**Comment by sanket-k** [comment]
rite, would just displaying how many hours/days it has been running solve this issue??

> since freqtrade process might fail and be restarted by systemd,

this could also be a metric we would be interested in (incase it was restarted, how long it has been it has restarted and maybe the user can review the logs around that time)

> but I'm not against this idea, even think that this info can be useful (or attractive to a user)

thanks, yeah it would save a bit of effort and time to find out if it performing as expected (or if a review is needed)
