### ISSUE TITLE
left over amounts

### ISSUE THREAD

**Issue by AndreWas1581** [freqtrade/freqtrade#2909]
## Step 1: Have you search for this issue before posting it?

Yes, I have. nothing here or in dokumentary

## Step 3: Describe the problem:

I am searching for a feature to handle left over amounts.
I discovered following, Binance ATOM/BTC
Freqtrade bought 2, sold 1 a few times.
So there was a left over amount of 6 ATOM. 
(Atom is only sold as a whole number)
 
I sold them manualy on exchange. 

Does there is / will be a feature like "sell_left_over" or "include_left_over" : true,
which includes the available amount in the sell order ?

It's the same with other currencies. 

Another possibility is to change the left over to BNB from time to time.
(Its possible to convert small amounts to BNB once 24h without fee)

Thank you.
Andi

**Comment by hroff-1902** [comment]
pls fill the form

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by hroff-1902** [comment]
> (Atom is only sold as a whole number)

Do not think so:
ATOM/BTC
Minimum Trade Amount: 0.01 ATOM
Minimum Order Size: 0.0001 BTC
Current price~=0.0005, so something close to 0.2 ATOM ~= 0.0001 and should be okay for trade...

How do you define stake amount?

**Comment by AndreWas1581** [comment]
My mistake, It is LINK/BTC.
I've choosen the wrong coin.
Like written above, Freqtrade buys 2 Link and sold 1 link.

So there was (at that time) 6.99 Link left on balance, to which no open trade exist.

Looks like binance subtracted 0.002 Link as fee, so from 2 link are only 1.998 Link available for sell.
(Which is as a whole number = 1)
That leeds to the question above, the left over amount wasn't included in the sell trade.

Is it possible to have a switch, with which you can define to include /exclude the left over amount ?

**Comment by AndreWas1581** [comment]
°	Operating system: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)
°	Python Version: Python 2.7.17 Python 3.6.9 (python -V)
°	CCXT version: none (pip freeze | grep ccxt)
°	Branch: Develop 
°	Last Commit ID: 889929f782802bac920a90296ca53df412a60550 (git log --format="%H" -n 1)

**Comment by xmatthias** [comment]
well for LINK/BTC - it's impossible to sell 6.99 - you can only sell full numbers - so 6, or 2, or 1 - but not 1.99 - therefore freqtrade needs to "round down".

``` 
'amount': {'min': 1.0, 'max': 90000000.0},
```

Fees are deduced from LINK because you've either configured your account to not use BNB - or you don't own any BNB.
in my personal Opionion, that's a obscure way binance has to draw you towards owning / using BNB.

Now you can sell 6 LINK manually on the exchange - but the only thing you could do with the leftover 0.99 LINK is to convert them to BNB (it's called binance dust - just search for that term and you'll find plenty of ressources) - as that's < minimum tradable amount (you also can't buy 1.01 - as you can only buy full amounts.

Now there is only one solution to this in my opinion - sell the 6 LINK manually - convert the remainder to BNB (potentially more ... to have enough for fees in the future).

Then make sure your account is setup to use BNB fees - as then the fees will not be deduced from the "target currency" - Link in case of buying LINK/BTC - but BNB fees will be used instead (which also happen to be half the amount regular fees are - at the time of writing).

Freqtrade itself cannot do much in this regards - simply because it's a limitation of the exchange which disallows selling amounts < 1.

**Comment by AndreWas1581** [comment]
Hello Matthias,
your described solution is the solution I currently use.
After a few days I convert the left over to BNB.

My question is for a new feature./a switch :
Lets go by the example above 
after a few trades there is an amount in balance, to which there is no open trade.
The buy is like every time the same.
buy : 2 Link
added balance : 2-0.002 = 1.998 Link
lets asume the resulted balance is 6.99 Link :
with new switch (include left amount) : sell 6 LINK
with new switch (exclude left amount) : sell 1 LINK

**Comment by AndreWas1581** [comment]
wrong button :)

**Comment by xmatthias** [comment]
that assumes that the bot is controlling the whole account.

but what if it's not? 
you'd sell all my HODL assets (potentially costing me huge profits as my coin skyrocketed the day after).
These amounts are unaccounted for - yes - but i also don't want freqtrade to go around selling assets  where it may (or may not) have opened the trade for.

How would you calculate profit for a trade where you bought 2 LINK - but sold 6 LINK? is that a 300% profit just because the amount is trice as much? i don't think so ... but without any reference at what rate that asset was bought, the whole profit calculation won't work anymore.


Personally, i think that the effort to either buy BNB - or to manually sell the "accumulated" assets manually is not too high. 
Also consider that for LINK, you've accumulated 6 now - but for most other assets, the remaining stuff will be "binance dust" even after a few trades ... for which the only solution is the "convert to BNB" button (that's what i have to use every now and then after doing tests without BNB (i usually pay fees in BNB).

**Comment by AndreWas1581** [comment]
You are right. 
But it's the angle how to look at the profit.
Just a short example. 
I buy 2 LINK at 2$, thats 4$.
The price is now rising to 2.50$.
I can only sell 1 Link, so there can be two views :
1. 1 Link at 2.50$ is a loss, compared to the 4$ invest
2. 1 Link at 2.50$ is a win, compared to the 2$ invest

I think it is not nessesary to implement the sell of left over amounts in the main code, maybe it's better to have a little helper called once a week.
My thoughts are following :
In the sell-code you can add a line of code to compare if whole buy amount is sold or not.
If it's all sold, then there is nothing more to do :)
if it is not sold, the amount is added to a SQL with the share price.
The little helper is called once a week and looks if the amount is for sell or not.
Its then sold, the win can be calculated because we have bought it before.

**Comment by xmatthias** [comment]
I'll close this one as #3239 introduced the "eating fee dust" method - which accidentally (on purpose) solves this problem.

Assuming you start on a fresh account:

This means - if you buy fees in base currency - and bought 20 ATOM - you'll be left with say 0.9 ATOM after the first trade (it's able to sell 19 ATOM due to minimum lot sizes).

The 2nd ATOM trade (buying 20 ATOM again) will then take fees off of the 0.9 ATOM - leaving you with 0.8 ATOM (and so forth), but selling the 20 ATOM it bought.

This will continue until you're out of "ATOM-Dust" - basically solving the problem you're (we're all) having with binance dust. Then a trade will be selling with 19 ATOM again - but the next 10 trades are again eating into the dust of this one trade.


Hope this makes sense.
