### ISSUE TITLE
Docker container as non root user

### ISSUE THREAD

**Issue by CavalloneChen** [freqtrade/freqtrade#2927]
The current docker container uses root user by default. This caused permission problems from the host side. For example, I can't edit files from binded folders without sudo.

**Comment by xmatthias** [comment]
that is correct, and i've stumbled over this just this week.

The problem is - changing it now to a non-root user will break everybody's running setup - because then the docker-running bot won't be able to read it's own files (trades.sqlite for example).

**Comment by hroff-1902** [comment]
won't fix? documentation issue?

**Comment by xmatthias** [comment]
I don't know ... 
I'd really like to fix it as it bothers me myself (but for other reasons than the above) - but ideally in a way that won't break users installations and require a "chown" for all files created by the bot.

**Comment by hroff-1902** [comment]
what's the problem describe and use `--user` option of `docker-compose run`?

**Comment by xmatthias** [comment]
I think the point is to add a `USER someuser` line in the Dockerfile.

It's a valid point - as running as root within docker can cause security problems and is generally seen as bad practice.

It's the update process (from running as Root to non-root) that worries me - as then the new container would loose access to the already existing files.

**Comment by xmatthias** [comment]
@nardholio i think you misunderstood this issue....

The problem is that the process within docker is running as root user (most other containers use a dedicated, non-root user).
This has security implications as in theory, a root user within docker could gain root access to the host (assuming the container is started with certain capabilities).

Also, files created by the container on a bind directory will be owned by root - making them difficult to access.

Now changing this in the dockerfile is as easy as adding a user within the container, and using the `USER <createduser>` command within the dockerfile.


The problem is, that this change would break every running container, as the new container (with the new version) would lose access to the files the previous container created...

**Comment by mmintel** [comment]
I'm experiencing the same issue on WSL2 and docker, everything created by docker is having root permissions. Do you have a workaround for this?

**Comment by xmatthias** [comment]
it's currently intentional that everything is owned by root.
For host-level permissions, you should be able to get around this with "user id mapping" - but please research this yourself as we don't give support on this - as you can mess up your permissions / docker installation with it quite nicely...


But exactly this is showing the issue i'm referring to - Transitioning from a root-based container to a non-root based container will not work, as your existing files will have the wrong permissions, which will cause a lot of errors for users simply upgrading their containers.
