### ISSUE TITLE
Money Management simple method

### ISSUE THREAD

**Issue by Gambi97** [freqtrade/freqtrade#2933]
## Equity curve trading
This method aims to exploit the operations on the equity trend to capitalize on its good moments and abandon it in the dark moments.
A first model is to build a moving average of the equity itself and to verify when the two lines cross, in order to identify roughly favorable or unfavorable trend periods.
the number of periods to choose for the construction of the average depends on the type of system, although often, the use of a 25/30-period moving average provides good results.

![TT_D_Above_Average](https://user-images.githubusercontent.com/26504853/74613752-40b32e80-5111-11ea-88a2-e63936e8aacc.jpg)

The method avoid trades when the equity curve is below its moving average.
The drawdowns are much more acceptable and the worst period of the system is kept in "freezing", resuming operations only during the subsequent positive recovery.
In addition, this type of stop also prevents the risk of finding a system, which for any reason no longer works.

![unnamed](https://user-images.githubusercontent.com/26504853/74613768-85d76080-5111-11ea-8c1b-1a24beb15b0c.jpg)

A problem that could arise is when the equity crosses the moving average even during a positive trend and consequently continues to activate and deactivate the bot. 
As in this case

![Media mobile-figura1](https://user-images.githubusercontent.com/26504853/74613938-8c66d780-5113-11ea-84a9-64634714d7b5.jpg)

Obviously the bot should continue to operate in any case in order to continue to "draw" the equity curve, the idea would be to make it switch in dry mode when it crosses the moving average from above and return it to real money mode when crosses the average from below.
You can find a lot of material about it by searching for "equity curve trading" on google.
### For now I have not yet reasoned on the implementability, I would like to understand if this function can be useful to freqtrade.
*thank you*

**Comment by xmatthias** [comment]
To be honest, this seems to me to be as simple as using the following Guard condition in your strategy:

```
...
    (dataframe['close'] > dataframe['ema25']) & 
...
```

Leaving aside if it would be possible or not to switch from dry-run to real money and back - it doesn't make sense in my eyes, as it's not what dry-run is or tries to be or tries to do.

Dry-run aims to emulate/simulate live trades as cloesly as possible, giving you confidence in your strategy, so by simulating trades where your strategy tells you not to trade MUST give you bad results in the dry-run results.

If you really want to have a bot trade when the strategy tells you not to trade (for confirmation that the decision not to trade was correct - then best use the same exact strategy in a 2nd bot instance, and reverse the Guard condition (above).

This will give you completely seperate databases / statistics - otherwise you'd lack easily accessible data to differentiate the trades cleanly.

**Comment by Gambi97** [comment]
I can't understand how a 25 period moving average inserted in the **strategy** as a filter can represent the functioning of equity curve trading.
They are two detached things.
Out of curiosity, however, I verified what you said by inserting in my current strategy an average of 25 periods as guard.
I did a backtest of the strategy and this is the result.

**this is the current equity without the moving average in the strategy**
![profit_normal](https://user-images.githubusercontent.com/26504853/74637981-5fdeaa00-516b-11ea-926c-282b2fa959e6.png)
as you can see there are big drawdowns around March 2019 and January 2020

**this is the current equity with the moving avarage in the strategy**
![profit_ema](https://user-images.githubusercontent.com/26504853/74638398-1b9fd980-516c-11ea-94d7-dd8fbe867c5d.png)
the drawdowns continue to be present and more or less the same size

**Comment by xmatthias** [comment]
What you understand as equity is nowhere described above.
To me, equity is one currency (XRP, for example) - where the above method does work just fine.


Since it's nowhere described above - How would you calculate the equity curve you're referring to? 
Or is it some additional data set pulled from an external source of some sort?

**Comment by Gambi97** [comment]
An equity curve is a graphical representation of the change in the value of a trading account over a time period. 
**let's assume (just to understand each other) the combined profit graph represents my equity curve.**
can we both agree on this?

_so how should the MA move above this if you don't trade anymor?_

obviously if you stop the bot then rightly the equity could no longer rise above the average.
In fact, the key concept is that the bot never stops.
There are 2 ways it should work:
## equity > ema25  
bot operates with a real account (normal, nothing strange)
## equity < ema25  
bot continues to operate.
but not with the real money portfolio, but with a sort of simulated wallet (maybe in my previous answers I used the term dry_mode improperly, what I wanted to understand was a sort of virtual account) so that it can continue to trace the graph of the combined profit and then cross the moving average from below.
# example
I take one of the previous images as an example.
The green line represents the trend of profit combined with real money, it can be noted that for a period it has remained constant precisely because the bot has stopped.
Why did it stop? because the green line (combined profit) crossed the moving average from above.
Once the moving average has been crossed then the bot will no longer work with real money, but will work in a simulated way until the blue line (simulated combined profit) crosses the moving average from below.


![unnamed](https://user-images.githubusercontent.com/26504853/74673775-35fba680-51b0-11ea-94c4-056b51476721.jpg)

I hope I have been clearer.
I'm trying to explain it as best as possible because it is a "simple" technique that avoids heavy drawdowns and also makes the strategy more profitable under certain conditions.

investopedia also talks about it in the second part of the page that you linked to me: [Investopedia](https://www.investopedia.com/terms/e/equity-curve.asp)
@xmatthias ;)

**Comment by xmatthias** [comment]
I'm not certain this strategy is applicable to Crypto ... and i'm not sure if you can't replace the "lost x trades in a row" with something looking at the current BTC price, as 90% of the pairs appear strongly correlated to that.


-----

Am i right in assuming that the above strategy would be based on the assumption that the current market trend will continue - and that trades are not independent from each other?

I'll ping @gaugau3000  here as i think he might have something to contribute as i know he did some very detailed statistical analysis - and had an opinion on the remainder of this post here: https://github.com/freqtrade/freqtrade/issues/2582#issuecomment-559241021 

----

Ignoring implementability (as you said above) - i'm hesitant on having/wanting this as part of freqtrade (core). 
While it doesn't implement buy/sell signals on it's own - it still seems to be a very "belive it or not" approach (as are many other things, too).

I can see the benefits to it looking at the curve above - but on the other hand it would base the "buy" decision of the current trade on top of the outcome of the last x trades,  - which would assume that trades are correlated to each other - and that because the previous trade was a loss, the current trade has a higher chance of being a loss - which (while it sometimes seems as such) is not really the case.

**Comment by hroff-1902** [comment]
I like the idea overall, this can be combined with a solution for long-awaiting #1841

**Comment by Gambi97** [comment]
The method works with certainty in classical finance, but as @xmatthias  says well I have no certainties that it also works for cryptocurrencies.
I'm sorry I don't have strong programming skills to be able to start implementing something and as I said I wouldn't even be able to define the difficulty of inserting a feature like this.
If you need something, however, I remain available for clarification.
good day and thank you @hroff-1902  @xmatthias

**Comment by hroff-1902** [comment]
the question here how to define equity here? is it the wallet total (with realized and unrealized PnLs), at the ends of candles (to make it a series of values to calculate MA on it)?

**Comment by Gambi97** [comment]
Equity should be described by the graph drawn by the profits and losses of the strategy.
For example:
if I had $ 1000 in my wallet, the equity would start at $ 0 when I started the bot.
Two strategies could be used as "sampling time":
N of operation
therefore for each closed operation a point associated with the gain or loss is assigned.
days
consider all the operations closed in a day, add to see the compound gain and then assign the value
Each method has its pros and cons in terms of robustness and noise.

![untitled](https://user-images.githubusercontent.com/26504853/74860516-15b31f80-5349-11ea-9cf7-6e65b0f9ae18.jpg)
_it is a matlab plot in which I entered totally random data only demonstration and added an average to two periods_

So at the end of the 5 days, when there were 9 trades (yes I was wrong and I didn't include the tenth trdes in 5 days by mistake), the value of my wallet will be $ 1004

Maybe you could also use the tredesv3.sqlite database (hypothesis, I don't know your structure )
in which if I multiply the amount per trade with the percentage profit I get what interests me.
Extrapolating this data, maybe you could start creating an equity?
have I not considered something?

**Comment by xmatthias** [comment]
well equity (the way i understood it from your previous explanations) would be the same than running `/daily` - but per trade and doing a rolling average over the last 25 (closed) trades.

The key here is that trades will be switched into "simulation" mode when the drawdown-factor is reached - but the trades still need to happen (in a simulated way).

All profit calculations need to ignore these "fake" trades - but they still need to be present in the database to calculate the equity curve.

----
In the end, it's probably an additional column indicating if a trade is fake or not - and all queries on the database need to be changed to respect that.

And that's part of the problem - this will require modifications all over just for this very specific usecase ... which will be integrated deeply into freqtrade ... 

My fear is that it'll become something similar to edge - which does too many things (for my taste) and is not too well maintained as none of the currently active maintainers "really" use it for much ...

**Comment by Gambi97** [comment]
What if instead of passing the bot in simulated mode we simply lowered the risk by lowering the capital on each trade?
that is, when the equity goes below the average at 25 periods I decrease the amount per trade, in this way I would avoid heavy drawdown anyway.
For example, I have a strategy that when it is above the average opens position with a fixed amount of $ 50, now let's pretend to be below the 25 period average:
Without equity curve trading
if for every trade I open position with $ 50 and I have a 5% stoploss then if I had to make 10 trades in a row I would lose ($ 50 * 5%) * 10 = $ 25
With equity curve trading
if for each trade I open positions with $ 25 and a 5% stoploss then if I were to make 10 trades in a row I would lose ($ 25 * 5%) * 10 = $ 12.5

the drawdown would still remain but would be limited.
I would not even consider lowering the risk by halving the stoploss otherwise the strategy would be distorted.
So could it be more easily implemented without completely changing the structure? @xmatthias

**Comment by xmatthias** [comment]
this will strongly depend on the initial stake amount - and on the exchange used.
example: 
i want the bot to trade 100 EUR on Kraken - and have 3 positions open.
Now that'll be roughly 33Eur per trade.

Halving this would bring me to 17ish EUR - which is < 20, which is the minimum tradable amount for at least some pairs on kraken.

It's probably ok if you trade higher amounts - but you would not start a strategy you don't fully trust with high capital - but at least i myself validate dry-runs by using low stakes to begin with.


if it's just about using a different stake - then open issues (like #848) will be able to solve this request - as then it must be handled completely in the strategy.

Obviously it'll then require more coding skills from the user - which in the end, will probably raise more questions than it'll be able to answer.

**Comment by gaugau3000** [comment]
Hello,

I am a little bit skeptical about the way that an equity curve act has it is a market :
- moving average can have sense in a market because of  [Self-Fulfilling](https://www.investopedia.com/ask/answers/05/selffulfillingprophecy.asp) because it can represent a trend/support... But your equity curve is not a market and your trades doesn't care about moving average : each trade is independant. Even if it is funny/original to would like to trade in an equity curve :-)
- Here the article that explain what you would like to do [EquityCurveFactsAndMyths](https://kjtradingsystems.com/EquityCurveFactsAndMyths.pdf)
- The only method i use for money management is this one [montecarlo simulation](https://towardsdatascience.com/improving-your-algo-trading-by-using-monte-carlo-simulation-and-probability-cones-abacde033adf) i have implement the method in a github repo if you would like to test. As we can read trades database in freqtrade the rule i use is simple : if the current drawdown amount in live > 1.5 * median drawdown amount compute during backtest montecarlo simulation the bot stop trading (this not mine but the one of Kevin Davey)

Have a nice day.

**Comment by xmatthias** [comment]
After looking at this again, we'll not be implementing a mix of dry/live bots (where half of the trades are live, and half are not.
The effort (and mainly, confusion) this would create in communicating with the user is not worth the benefit.
Not having any comment here for over 3 years now also clearly shows that it's not interesting to others.


What you're actually trying to do (as described in https://github.com/freqtrade/freqtrade/issues/2933#issuecomment-588896735) can now be archived with a clever combination of [callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) - more specifically with the [`custom_stake_amount()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management) callback.
