### ISSUE TITLE
Data Provider/Source: Glassnode

### ISSUE THREAD

**Issue by nomad5am** [freqtrade/freqtrade#2946]
Hey guys,
is it possible to use glassnode as a data provider and use their metrics in a freqtrade strategy?

Some examples: 
https://studio.glassnode.com/metrics?a=BTC&m=indicators.Nvt
https://studio.glassnode.com/metrics?a=BTC&m=transactions.TransfersVolumeToExchangesSum

API:
https://docs.glassnode.com/api/transactions#exchange-inflow-total

This would be absolutely fantastic! Is it possible?

**Comment by hroff-1902** [comment]
No, only if you programmatically will fetch their data using their API in your custom strategy.
In other words: feel free to implement it. 😉

**Comment by xmatthias** [comment]
Let me also explain why we won't implement this.

There's a multitude of "additional dataproviders" out there - all with different validity.
Now i don't judge any one of these - however we'll leave it up to the strategy author to eventually implement one of their API's or not - because most likely, it'll only benefit a very small subset of people (who belive in the data this particular dataprovider has / calculates / imagines).

If we start adding this, then we'll most likely also have to support the other providers once someone asks for hit - which is unmaintainable (remember this is an open source project, we work on this in our free / spare time - and resources are already tight).

For that reason, we'll leave such functionalities to users, and focus on core functionality of the bot.

Thanks for your understanding.
