### ISSUE TITLE
FTX - list-pairs only lists spot markets

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2953]
Using defaultType futures; as xmatthias told me, there's no defaulttype on ftx ccxt file, how should we proceed about this? @hroff-1902 

https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py 

https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py

**Comment by xmatthias** [comment]
Well - not at all at the moment.
If any, it's an issue for ccxt ... and our main exchanges are bittrex, binance and kraken - so if we need to develop new methods to support something, then it's for one of these exchanges first, not for "unsupported" exchanges. 

The defaultType i told you on slack was a "shot into the dark" - already assuming it would not work, but who knows what ccxt has in it's bag of tricks.

#2940 does some work / testing on binance for that ... so if that works, it might make sense to open an issue on ccxt for that. 
However before we got confirmation that trading futures on binance works, i would not act on this at all ... simply because we don't know if it works to open orders or similar things yet.

**Comment by kroitor** [comment]
To clarify: the reason for having a `defaultType` config option for Binance in CCXT boils down to markets. In most cases, an exchange would have different format of market ids for spot vs futures. That allows to work with both types of markets simultaneously (both the spot markets and the futures markets). If that is the case, we can load all types of markets in `loadMarkets` and use all of them at the same time. In Binance, however, the ids are identical between spot BTC/USDT (`BTCUSDT`) and futures BTC/USDT (for which the id is also `BTCUSDT`). Therefore there's a conflict between spot/futures market ids, and when it comes to parsing those ids, it's hard to distinguish between them to properly identify the corresponding markets (spot or futures) by their ids. This is the reason why we cannot load both types of markets from Binance at once and we have to work with them separately using the `defaultType` option to avoid conflicts and confusion.

**Comment by hroff-1902** [comment]
Why cannot ccxt work with them as with two different exchanges, with different exchange ids -- say 'binance' and 'binance_fapi', without any defaultType? Their APIs are almost completely different...

**Comment by kroitor** [comment]
> Why cannot ccxt work with them as with two different exchanges, with different exchange ids -- say 'binance' and 'binance_fapi', without any defaultType? 

It can:

```Python
binance         = ccxt.binance()
binance_fapi = ccxt.binance({'options':{'defaultType': 'future'}})
```

↑ This is technically the same as:

```
binance         = ccxt.binance()
binance_fapi = ccxt.binance_fapi()
```

We do not think that `ccxt.binance({'options':{'defaultType': 'future'}})` is very different from `ccxt.binance_fapi()`, because in both cases it requires a specific exchange id or a specific option, which is technically the same thing.

> Their APIs are almost completely different...

Not really completely different. The public APIs and 50-75% of the private APIs are the same.

**Comment by Dante2333** [comment]
How would we be able to use ftx futures if there's no defaultoption for FTX but the symbols are different. @kroitor

**Comment by xmatthias** [comment]
what @kroitor is saying is that if the symbols are different, they should be in the `load_markets()` call.... 

the `defaultOption` is not a ccxt standard as far as i know, it's ONLY implemented for binance (so far, anyway).

**Comment by kroitor** [comment]
@xmatthias 

> if the symbols are different, they should be in the `load_markets()`

Right!

>  is not a ccxt standard as far as i know, it's ONLY implemented for binance

.. and OKEX v3 and DigiFinex for some endpoints. We're going to focus on the unification of futures and other derivatives soon.

@Dante2333 FTX futures are available by default, you don't have to do anything special to access them with CCXT.

**Comment by Dante2333** [comment]
Yep, just found it, will close this issue!

**Comment by xmatthias** [comment]
> @Dante2333 FTX futures are available by default, you don't have to do anything special to access them with CCXT.

we know - the problem is with Freqtrade ... but it wasn't clear from the initial report what the real problem was ...

we'll have a look at this ... :)

**Comment by hroff-1902** [comment]
unification of this INSIDE the bot is also simple -- we could add a 'subexchange' setting in the 'exchange' branch of settings, so setting it as `"subexchange": "fapi"` will add `{'options':{'defaultType': 'future'}}` into the config params passed to ccxt binance exchange object during initialization... (Should be implemented on the exchange-specific manner, in the freqtrade exchange-specific class) Other exchanges may have other 'subexchanges' available and pass other values needed for ccxt to properly select the API sub-set...

**Comment by xmatthias** [comment]
yes - but let's first wait if #2940  is successfull in testing ... :)
