### ISSUE TITLE
nan value when indicator is based on 500 or 499 candle during dryrun

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2977]
Hi,

Using this code :

```
dataframe['natr_500'] = ta_lib.NATR(dataframe, 500)
dataframe['natr_499'] = ta_lib.NATR(dataframe, 499)
dataframe['natr_498'] = ta_lib.NATR(dataframe, 498)
print('natr_500 : {} natr_499 : {} natr_498 : {} '.format(dataframe['natr_500'].values[-1],dataframe['natr_499'].values[-1],dataframe['natr_498'].values[-1]))
```
I got this output :

`natr_500 : nan natr_499 : nan natr_498 : 0.908125710784621`

Tested in dry run with binance exchange.

For far i know freqtrade work with a maximum of 500 candles in dry/live.

Have a nice day.

**Comment by xmatthias** [comment]
unfortunately that's not correct.

Freqtrade fetches 500 candles - drops the last (binance returns incomplete candles - so most indicators would be repainting).
Now there are ways to get the 500 candles ... but then it'd be on you to somehow prevent repainting - as you'd get the incomplete candle slightly differently on every iteration (assuming it changes, obviously).

So you're getting 499 candles.

A better way to test this is to use `print(f"{pair} - {len(dataframe)}")` - it'll print the length of the dataframe directly.

**Comment by gaugau3000** [comment]
Hi,

I should have present this issue like user centric this instead of technical angle: 

Given i read in the doc :
`startup_candle_count should be below ohlcv_candle_limit (which is 500 for most exchanges) - since only this amount of candles will be available during Dry-Run/Live Trade operations.`

My understanding is when i use :

 ```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

dataframe['natr_500'] = ta_lib.NATR(dataframe, 500)

 def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (   
                  (dataframe['natr_500'] > 1)
            ),
            'buy'] = 1

        return dataframe
```

Then i expect to have a buy when the condition is satisfied (but of course it will never happend).

For the tech part : I understand why `natr_500 : nan` because the dataframe has length of 499 but why `natr_499 : nan`

Have a nice day.

**Comment by hroff-1902** [comment]
500 is a default number of candles to download on bittrex (or binance). So this is used.
Then the last (incomplete) candle is removed. The resulting Dataframe is passed to the strategy.
Sometimes the length is higher -- if downloaded data contain gaps (due to binance outage, for instance, still available in the dataframes on 1d timeframes) and those gaps were filled -- then the length of the dataframe will include additional filled candles.

Maybe documentation should be adjusted: in sence that you should not make many assumptions about the actual length of the dataframe.

**Comment by xmatthias** [comment]
honestly, i assume because ta-lib uses 499 historic candles for the calculation (excluding the current one) for NATR calculation.

This should be pretty easy to recreate - using a lower value (5 for example) and visualize it as rows should also require 5 historic candles (having the first value in the 6th (indexed with 5) row.

Never used that indicator myself though - i'd say open an issue with ta-lib - but i am not certain about the level of support you're going to get - since the C source seems pretty much unsupported.

**Comment by xmatthias** [comment]
I think the below screenshow shows the problem quite nicely.

I've got a dataframe with lenght 10 (don't look at the values, it's random...).
Now using ta.NATR(10) produces empty results (as apparently, it requires 10 startup candles, and assigns the value into the 11th row).

Using `ta.NATR(9)` does work as you'd expect it to.

![2020-05-22-072000_659x399_scrot](https://user-images.githubusercontent.com/5024695/82633884-a9241700-9bfc-11ea-9cfc-8d5fc3ac11f0.png)


Interrestingly, it's not happening for other indicators (SMA) - so it IS tied to using NATR.

This is however nothing we can really help with - it's either intentional (based on the NATR formula) - or accidental (a bug in ta-lib) - neihter of which we can (nor should) fix in freqtrade

**Comment by xmatthias** [comment]
Hope you're fine with me closing this - i wouldn't know how we could help with this...

if there's additional questions regarding this, best ask them to the ta-lib developers (or the ta-lib python wrapper [here](https://github.com/mrjbq7/ta-lib)) - they're also a quite helpful bunch...
