### ISSUE TITLE
Override exchange nonce function

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2990]
We should probably override ccxt exchange nonce function and use one based on milliseconds:
```
exchangename = ccxt.exchangename({'nonce': ccxt.Exchange.milliseconds})
```
https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

From ccxt docs:
>  You should override it with a milliseconds-nonce if you want to make private requests more frequently than once per second!

This can help prevent exchange errors, if they are caused by this (the following from Slack):
```
2020-02-28 09:06:14,351 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2020-02-28 09:06:16,445 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}"
2020-02-28 09:06:16,445 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 3 times
2020-02-28 09:06:19,447 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}"
2020-02-28 09:06:19,447 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 2 times
2020-02-28 09:06:22,451 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}"
2020-02-28 09:06:22,451 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 1 times
2020-02-28 09:06:25,448 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}"
2020-02-28 09:06:25,448 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 0 times
2020-02-28 09:06:28,452 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}"
2020-02-28 09:06:28,452 - freqtrade.exchange.common - WARNING - Giving up retrying: get_balances()
2020-02-28 09:06:28,452 - freqtrade - ERROR - Could not get balance due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}
(.env) (base) root@vmanager6003:~/freqtrade# 
```

**Comment by hroff-1902** [comment]
maybe `time.monotonic() * 1000` should be used, it guarantees monotonic sequence of values.

**Comment by xmatthias** [comment]
why not check the time of the machine you're seeing this? 

I've seen this mostly if the time is not 100% correct, and i suspect that using milliseconds will probably worsen this problem - so before implementing something do VERY carefull testing.


Also - kraken has an option per api key for a "nonce window" 
https://support.kraken.com/hc/en-us/articles/360001148023-What-is-a-nonce-window-
... which may also help with this.

Assuming we need to override it - i would stick to the CCXT samples and use `{'nonce': lambda: ccxt.Exchange.milliseconds()}`. no need to reinvent the wheel - and making requests more than every millisecond will get you blocked anyway.

**Comment by hroff-1902** [comment]
that's not actually about this particular problem a user have, but as a workaround for a more general problem: ccxt nonce is based on the seconds timestamp, so when there are more than one request to a private api is issued to the exchange in one second, it can be rejected (since requests will contain same nonce value)

**Comment by xmatthias** [comment]
no, nonce should be in epoch to me- so it's always counting forward (epoch / unix timestamp is in UTC by definition).
monotonic is just a counter - which works well for measuring time intervals - but not to measure absolute time as it's starting point is "undefined" - so it's completely unsuited for calculating nonce unless you're 100% certain you'll NEVER change server.

Just assume for a second that a user migrates from one server to another (but obviously keeping the API keys - because there's no logical reason to change these).
monotonic might have a different "undefined" starting point - so you'd have all requests blocked.

Also i'm not sure how monotonic behaves after restarts (it's undefined according to the documentation)- so by changing that you could break restarting and resuming freqtrade (with or without docker...).


In my opinion, the solution to the problem stated above is in the Kraken api console - changing the nonce window to a different / higher value - although if i'm honest,Ii've been running a kraken bot for the last 4 weeks without EVER getting this message (but also without changing the nonce window).

Does this happen all the time or just "from time to time" ? 
Best stick to the ccxt documentation - which recommends to regenerate the API keys - maybe the keys have been used in another application that generates the nonce differently.

**Comment by hroff-1902** [comment]
`monotonic()`, yes, was a bad (incorrect) idea, since we do not know what values can be returned on different servers and even with consecutive runs...

`millisecond()` seems to be better. My doubt was the following: when the time on a system is adjusted, `milliseconds()` (and current nonce calculation, which used `seconds()`) can return lesser values, which will cause errors from exchange.

> Ii've been running a kraken bot for the last 4 weeks without EVER getting this message (but also without changing the nonce window).

Okay, I'll: close this issue by applying #3001, it's a good addendum which has to be in the docs in any case, I'll also test this on live Kraken for some time with a specially crafted strategy, my idea that you have not noticed this because you did not have many buys/sell on the same candle (same throttling iteration within same second -- this should produce errors according to the ccxt docs... I'll open then this issue when (and if) I'll know particular conditions about how these errors can be reproduced.

**Comment by xmatthias** [comment]
well `millisecond()` may cause this - yes - but i don't know any way to have a counter always count up, syncronized across different systems and operating systems - which can handle time adjustments without counting down.

**Comment by hroff-1902** [comment]
in case of `milliseconds()`, if the system time was adjusted back at a small fraction of a second or even seconds, next retry will use proper nonce value, only temporary errors will appear, so I see `milliseconds()` as a good approach. But need to find the particular conditions first to show why changing from current seconds to milliseconds is really needed...

**Comment by xmatthias** [comment]
yeah - the problem is that by using "non-ccxt standard nonce" - we'll break debugging usages where we use ccxt commands directly to get the raw output from an exchange ...

**Comment by tomismrkolj** [comment]
Since two days after updating windows docker to 3.2.1 I cannot start live trading. The following error occurs.

freqtrade.exceptions.TemporaryError: Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

Have reinstalled Docker for windows, sync windows clock to ntp and have put - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro" to the docker-compose.yml
      
Any ideas?

**Comment by xmatthias** [comment]
depending on the docker configuration - it's probably using WSL2.
you'll need to sync the clock with WSL2 seperately (it's a WSL2 bug, as it doesn't sync the time with  the windows machine).
