### ISSUE TITLE
Some suggestions for improvement 

### ISSUE THREAD

**Issue by Kaidokuni** [freqtrade/freqtrade#3006]
A few suggestions for improvement, but I don't know if they're feasible.  
1) Compare the performance for different time frames but for the same strategy or list of strategies?
2) Adding the time frame to what the hyperopt can modify --spaces time frames (maybe it's too huge?)
3) On telegram, Have a  /balance plot or /graph to have a graph of the profit
4) Can we create a command line (--hyperopt-create-epoch 247) to be used after executing a hyperopt and this command line will creates a configuration file and a strategy file with the parameters of the specified epoch and like that it can ready to be use for backtesting (with the configuration/strategy file named after the objective result for example and copied from the specified --strategy and so partially replaced with the new parameters)

**Comment by hroff-1902** [comment]
1 and 2 are the same. First, it will not work with optimizer, since results are completely different on different timeframes (with same values to other parameters in the hyperspace). Second, this is hardly achievable with the current code base, since freqtrade loads only one set of historical data, for one timeframe. Third, you can easily make this manually by running the hyperopt subsequently for different timeframes, probably multiple times for each, and by manual selection between results for bests, using some criteria external to hyperopt. So, taking all this into account, this won't (and probably even cannot) be implemented and any efforts for this does not worth, use subsequent runs of the hyperopt, varying the timeframe in the cli options, for example (can even be automated with a shell or python script).

3. Do not know, plotting is the @xmatthias 'es episcopacy...

4. It's simple to achieve -- just transfer the methods from the hyperopt file to a strategy as is, with all those triggers, selectors and trading conditions, and create the `params` dictionary variable at the module's global level, assigning all those values from 'epoch 247' -- and the strategy should work exactly as it was found for that epoch 247...

**Comment by xmatthias** [comment]
> On telegram, Have a /balance plot or /graph to have a graph of the profit

I'm not a huge fan of this - and i don't think the implementation and maintenance effort is worth the benefit.

While we have the plotting module using plotly - that will not work for sending via telegram, which would mean we'd probably have to reimplement the wole thing.
Even assuming plotly supports saving to PNG (did not investigate that yet) - the main usage of telegram is the phone - so you'll see a profit-plot on the small phone screen - which will not tell you very much as you can't even read the numbers.

My aim would be to someday have a webui on top of freqtrade, which would make this irrelevant anyway, as that webui can support such things out of the box.

**Comment by xmatthias** [comment]
As stated above, options 1 and 2 will not work as it would require loading the data for all timeframes to hyperopt - and the resuts would be too different to compare.

Option 3 does not make sense, we'll have Graphs in [freqUI](https://github.com/freqtrade/frequi) soon.

we have another issue for tracking 4. (#3464) - therefore i'll close this issue.
