### ISSUE TITLE
Save pair locks in persistence

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#3034]
This is a PR to discuss potentially saving pair locks in persistence, just to avoid rebuys if you happen to restart freqtrade.

This can be done by saving the timestamp of the last candle in persistence that it locked at, and checking against it on freqtrade startup _and /reload_conf?? (confirmed that also resets locks)_, the timestamp would only need to be updated when a lock actually takes place.

This is important when using high timeframe trading strategies, as you might need to restart client or /reload_conf, and you might not want pair locks to reset.

Finally, we can use a config to **persist_locks** default to false, so current behaviour would remain for those who prefer that it does reset.

**Comment by yazeed** [comment]
If you like the idea, possibly I or someone can work on a PR for this.

**Comment by xmatthias** [comment]
personally, i don't really see a reason why anyone would want to reset locks on restart ... so defaulting that option to true will be fine.

now on the other hand, an rpc to "/show_locks" might be nice ... and eventually `/clear_lock ETH/BTC` ... should someone want to reset this remotely (assuming long timeframes - like 4h or so).

Considering the above - maybe a "lock_reason" would make sense there too (which might only have 2 possible states, automatic or custom) ... so you know if your strategy did the locking, or the automatism because a pair was sold.

----

for implementation "details" - i would use a integer / number column instead of a datetime column - sqlalchemy has some strange behaviour around timezones ... (you put it one way, get it out another way if the underlying database does not have timezone support) ...  
it can be fixed (`.replace(tz='utc')`) - but i would try to avoid it where i can...
