### ISSUE TITLE
Stoploss does not work properly in the real trade.

### ISSUE THREAD

**Issue by Superior18** [freqtrade/freqtrade#3043]
* Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.23.81
  * Branch: Develop
  * Last Commit ID: 77944175e27bcd7851a83863f5df15f3577d61de

Hi
I used your robot in Binance and realized that stoploss would not work in real trade.
Configuration file:
```
{
    "max_open_trades": 6,
    "stake_currency": "BTC",
    "stake_amount": 0.000160,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "ticker_interval": "5m",
    "dry_run": false,
	"trailing_stop": false,
    "trailing_stop_positive": 0.005,
    "trailing_stop_positive_offset": 0.0051,
    "trailing_only_offset_is_reached": false,
    "stoploss": -0.03,
    "unfilledtimeout": {
        "buy": 5,
        "sell": 525600
    },
    "bid_strategy": {
	    "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
	    "price_side": "ask",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 9,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
"THETA/BTC",
"REN/BTC"
],
        "pair_blacklist": [
            "BNB/BTC",
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "xxx"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Reports received from the telegram:

```
FreqTrade, [09.03.20 18:33]
Trade ID: 223 (since 3 hours ago)
Current Pair: THETA/BTC
Amount: 11.0 (0.00016 BTC)
Open Rate: 0.00001415
Current Rate: 0.00001370
Current Profit: -3.37%
Stoploss: 0.00001373 (-3.00%)
Open Order: (limit sell rem=11.00000000)
```

```
FreqTrade, [09.03.20 18:33]
Trade ID: 225 (since 2 hours ago)
Current Pair: REN/BTC
Amount: 17.0 (0.00016 BTC)
Open Rate: 0.00000936
Current Rate: 0.00000887
Current Profit: -5.42%
Stoploss: 0.00000908 (-3.00%)
Open Order: (limit sell rem=17.00000000)
```

As you can see, Current Rate is now lower than Stoplosss, but the trade is still open!

**Comment by xmatthias** [comment]
what's your order_types configuration (within strategy) look like?

are you using stoploss on exchange?

Also, both orders show "open order" - what's the rate these were opened at? (i think it'll be easiest to check this on the exchange).

I do have a suspicion based on your configuration ... but i'd need answers for the above first to be able to answer with certainty.

**Comment by Superior18** [comment]
I had forgotten to put the "Order Type" section in the config file
Now, as below, I added it to the config file:
```
    "order_types": {
    "buy": "limit",
    "sell": "limit",
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": false,
    "stoploss_on_exchange_interval": 60
    }
```
and also,
In the strategy file I have not included the "Order Type" section.
But trades are still open after the config file is reloaded!

```
Trade ID: 223 (since 3 hours ago)
Current Pair: THETA/BTC
Amount: 11.0 (0.00016 BTC)
Open Rate: 0.00001415
Current Rate: 0.00001319
Current Profit: -6.97%
Stoploss: 0.00001373 (-3.00%)
Open Order: (limit sell rem=11.00000000)
```
```
Trade ID: 225 (since 2 hours ago)
Current Pair: REN/BTC
Amount: 17.0 (0.00016 BTC)
Open Rate: 0.00000936
Current Rate: 0.00000881
Current Profit: -6.06%
Stoploss: 0.00000908 (-3.00%)
Open Order: (limit sell rem=17.00000000)
```

**Comment by xmatthias** [comment]
well order_types does not have to be in the configuration - having it in the strategy is perfectly fine (that's how i handle it, anwyay).

What's the "limit price" of the sell-orders? (as said, best check this on the exchange).

**Comment by Superior18** [comment]
I put a screenshot of the Binance Sell Order below : 
https://i.ibb.co/QvDvWQZ/screenshot-26.png

**Comment by Superior18** [comment]
This looks like a bug.
All settings are correct. Even in dry-run mode everything works correctly. But that's not in real trading.

**Comment by xmatthias** [comment]
It's not - it works as intended - but it's caused by a misconfiguration - and there's even a warning about the risks included.

Please carefully read this section of the documentation - and specifically the warning box which warns about stoplosses which can be missed: https://www.freqtrade.io/en/latest/configuration/#sell-price-with-orderbook-enabled

> Using ask_strategy.order_book_max higher than 1 may increase the risk, since an eventual stoploss on exchange will be needed to be cancelled as soon as the order is placed.

Since your `ask_strategy.order_book_max` is at 9, the bot immediately checks the next 9 slots of the orderbook - and places a sell-order at the first slot it would be profitable.

Now taking the example from the documentation of an orderbook ... this is what happens:

```
109  # <- it walks up to this point
...
103
102
101  # ask
-------------Current spread
99   # bid
98
97
...
```

Now i assume you use a "relatively" low min-roi - which means a sell-order is placed almost immediately. Since it's checking a total of 9 orderbook slots, this can be a substancial amount in certain cases.

This also falsifies dry-run results - as the same behaviour happens in dry-run - but assuming the order is filled almost instantly.

On top of that - you've increased  `unfilledtimeout.sell` to 525600.
The sell-order will therefore "remain there" forever ... otherwise the order would've been canceled max. 30 minutes into the order - and the appropriate stoploss would've been created.
Both configurations alone are not necessarily a problem, but in this constellation they can be if the market goes against you, as this sell-order will remain there until you manually cancel the order - or price reaches this level again.

-----

The bot itself works as intended - and default-settings for order_book is false on both buy and sell side - with the assumption that users understand the implications of settings changed. 

I've just noticed that the default configurations contain a 9 in this place - which should really be a 1 (to avoid this very niche behaviour) - so that's the only thing which can be seen as a "bug" - which is a default-configuration which (if another setting is changed) acts slightly differently.

Best change `ask_strategy.order_book_max` to 1 - so this wont' happen for new trades (won't affect this trade unless you cancel the order on the exchange manually).
I'll also update the default-configurations to this - so noone else will struggle over this without intend in the future.

**Comment by Superior18** [comment]
Thank you very much for this excellent support.
This robot is undoubtedly the best open source trading robot.
I read your explanations carefully and this question came to me.
Can't the robot automatically cancel the sale order if reach StopLoss if I set `unfilledtimeout.sell = 525600`?

**Comment by xmatthias** [comment]
that would be a possibility i did think about myself this afternoon (while looking at this issue) ... but it's currently not there - and unfortunately, it's not as simple as it sounds (not the detection, but the handling of such a case).

i suspect the placed stoploss would need to be a market sell order (ignoring sell-order configured) - as the assumption is that a sell-order is "left hanging" - and once we're below our intended stoploss, we sell immediately - which will probably not work with a limit sell order - as that would be placed "too high" in almost all cases (assuming price is going down hard).

The best method against this will remain a stoploss-on-exchange ... however that ties up the asset - so has to be canceled once the limit-sell-order is placed.

**Comment by hroff-1902** [comment]
why should sell order be cancelled if the rule says `unfilledtimeout.sell = 525600` explicitely, which means 'hang for very long time (525600 s)'?

**Comment by Superior18** [comment]
I want Sell Order stay open forever, unless the price <= stoploss.
In this case, the robot immediately cancels previous Sell Order and create new sells at Stoploss price.

can you help me?

**Comment by xmatthias** [comment]
well that's simply not possible at the moment.

#2872 will introduce a custom callback to cancel orders, where (as a workaround) you can check for this within the strategy and eventually cancel the limit order.
