### ISSUE TITLE
Tagging of buy & sell conditions 

### ISSUE THREAD

**Issue by Fredrik81** [freqtrade/freqtrade#3081]
## New feature request

Ability to tag buy and sell strategies and print what triggered the buy and sell in telegram bit output. 

## Example:
Having two dataframe.loc where we can tag a name to each. 
Dataframe.loc[
(
   (Condition)
), 'buytag'] = 'my tag1'

Dataframe.loc[
(
.   (Condition)
), 'buytag'] = 'my tag2'

**Comment by hroff-1902** [comment]
continuing the discussion started at Slack:
-- the idea itself is great.
-- I would like to keep the float as the return value from populate_buy/sell_trend methods. In the future, this value can be treated as the position size (i.e., 0.5 returned would mean "open the position, but with 0.5 amount of "normal" position size"). Discussible.
-- so in this case and due to this reasoning, another columns (like "buy_tag"/"sell_tag") should be used instead
-- helper functions, like `buy_condition(condition, "buy_tag")` can be added, which will incapsulate both `.loc` for the sell signal and setting the tag. This will, even without tag, would simplify the strategies, so that a user would not write those multiline `.loc` expressions explicitely.

**Comment by xmatthias** [comment]
one thing is for sure - it'll need to be documented well.

I guess it can easily be done using masks:

``` python
cond1 = (dataframe['rsi'] < 30) & (dataframe['volume'] > 0)
cond2 = (dataframe['macd'] > dataframe['macd_signal']) & (dataframe['volume'] > 0)

dataframe.loc[cond1, 'buy_tag'] = "rsi<30"
dataframe.loc[cond2, 'buy_tag'] = "macd_signal_cross"

# dataframe.loc[cond1 & cond2, 'buy_tag'] = "both-conditions"

# Define condition
dataframe.loc[cond1 | cond2, 'buy'] = 1

```
Note: this will NOT be a good strategy - so please don't even TRY to use this as it is just a quickly hacked together thing to demonstrate possible use of the `'buy_tag'`. 

Now obviously if both signals would apply the "2nd line" wins, so macd_signal_cross would apply.
This can be captured with the 3rd line - but that'll make it slightly difficult.

---

Now i'm not convinced about the "helper methods" - they won't give you much if you consider the above context.
You'll still need the masks (`cond1`, `cond2`) - you'll need to pass them (with the dataframe + the text) to the function - so i don't see any benefit while using the below

``` python
dataframe = buy_tag_function(dataframe, cond1, 'rsi<30')
dataframe = buy_tag_function(dataframe, cond1, 'macd_signal_cross')
# dataframe = buy_tag_function(dataframe, cond1 & cond2, 'both')

dataframe.loc[cond1 | cond2, 'buy'] = 1
```

To me, this is such an easy assignment that the function-call looks more complicated, as it hides the final column name.

This might seem tempting, but i'm not keen on debugging peoples strategies that used `sell_function()` instead of `buy_function()` - simply because it can be avoided by being explicit in what is happening - which is leaving the pandas-code as is.

**Comment by barisengez** [comment]
does it make sense to such an addition?

```
# Indexes for backtest tuples
DATE_IDX = 0
BUY_IDX = 1
**BUY_TAG_IDX** = 1,5 (joking ofc :) it ll go +1 incrementally)
OPEN_IDX = 2
CLOSE_IDX = 3
SELL_IDX = 4
**SELL_TAG_IDX** = 4,5
LOW_IDX = 5
HIGH_IDX = 6
```

and i would ignore multiple condition hits and just go for the first hit condition. otherwise it ll become a condition table instead of a buy/sell tag.

@xmatthias s approach in the first code sample makes complete sense to me, even as it is in the sample. why were you against that sample code?

**Addition:** I see it was proposed for telegram but I would love to see these buy/sell tags on backtest results. it was even my initial trigger for my attention on the subject.

**Comment by xmatthias** [comment]
> why were you against that sample code?

noone rejected the proposal of using a "reason" column (naming not defined) - but it's not been important enough to anyone to spend time on either - and as such - it's an open enhancement. 

I've been against using helper-methods - as at least in the usecase / usage i came up with, it seems to be more complex than the "direct assignment" case.


I'm not sure about backtesting - it'll make backtesting-results again more complicated to read through - so while it may seem to be a good idea, it'll take away the "one glance" determination if it's good or bad.

You can sure give it a try - if it's done in a concise, unobstructive way, we can for sure include it. If it clutters results too much, we might wanna put it behind an optional command line flag (but i'd leave that open for the moment).

As said before - i assume you're proposing to make a PR - as i don't see this as anything important for the moment, and as such will not be spending time on it myself.

**Comment by GluTbl** [comment]
Hello, can we mark the buy tag option in the plotting also ? Like marking the "buy_tag" as that of "buy" signal?
