### ISSUE TITLE
Fee calculation + stoploss support + trade amounts on FTX

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#3103]
So, while testing live trading on FTX using freqtrade. I've spotted a few FTX inconsistencies that I'll be logging here, so that we can start working on them in the future:

1. Fee calculation seems to fail all the time with this error (Leveraged tokens, haven't tried perps or options trading yet):

`2020-03-23 15:31:19,595 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=225, pair=DRGNBEAR/USD, amount=0.01231875, open_rate=2789.00000000, open_since=2020-03-22 20:00:34) failed: myTrade-Dict empty found`

2. Stoploss on exchange is not supported yet on FTX, looking at ftx.py it's obvious that it's lacking the param config that enables it as well as the needed stoploss() and stoploss_adjust() methods.

3. Freqtrade keeps getting out of sync on orders (amount) on FTX, occasionally I get these occurrences which I have to fix manually from the DB:

`2020-03-23 11:10:48,474 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 0.0091, Wallet: 0.0082`

**Comment by xmatthias** [comment]
First of all - please use one issue per discovered problem. Otherwise discussions get confusing and we're stuck with issues we cannot ever close because one minor thing was never done, but the issue would be 90% done - but noone will be able to figure out which part is still missing.

1) that's not relevant for FTX i think. as far as i know, FTX does subtract fees from the "correct" side of the pair (not the destination pair, but the source pair) - so fees should apply correctly. This message mainly applies to binance, which subtracts fees from the Destination currency (or BNB - but then it's not relevant again).

2) that's not even really an issue - just something which is "to implement and test" ...but as mentioned slack - it's really just a "noone invested the time into this yet" more than anything.

3) Without a full log for this, it'll be impossible to find the solution to this (also - please use a separate issue for this.

**Comment by Dante2333** [comment]
On the fee calculation, since FTX can have multiple fee tiers which actually rely on volume .. or different discount; it would be ideal if we could query over api to get current account fees then use them from that moment in time for freqtrade?

https://help.ftx.com/hc/en-us/articles/360024479432-Fees

For 2, give me exactly what you would need to I can pass it to FTX devs and see if we could have stop-loss on exchange; 

For 3 I think you are trading with a very small amount and then when the leveraged token fluctuates then you are not reaching the minimum amount to sell.

**Comment by xmatthias** [comment]
for 2 - i have a (kindof working) implementation locally - but it needs a few of the open PR's (mainly #3112) to be merged to function properly, so i'll keep that to myself for now to avoid problems.

for 1) i will have a look at fees when i get time - it's part of #2649 ... as fees are not always handled correctly for many exchanges.

**Comment by hclivess** [comment]
I've been testing PERP futures, stoplosses do not trigger because `Unable to sell trade: Not enough amount to sell`

**Comment by xmatthias** [comment]
@hclivess Please open a seperate issue for this, which fills out the issue template to show us which version etc. you're using.

Also, we'll be needing the logs from the time of the buy (a few lines before / after the buy) - as well as the logs from the time of the sell, otherwise we cannot verify your issue.

**Comment by hclivess** [comment]
@xmatthias OK, thank you. I might be doing something wrong, but freqtrade thinks the wallet balance is 0, which it is, because there is no "token balance in the wallet", it's in a separate category

**Comment by Dante2333** [comment]
He's testing futures, wallet balance is actually 0, you dont have a token called X when you are trading futures.

**Comment by xmatthias** [comment]
Looking at futures for FTX won't make much sense until ccxt implements their unified futures interface (scheduled for Q2 - so we'll not look at it as we'd be replicating the work ccxt will do in this direction).

I'm not sure what is missing for FTX (it's the balance point for sure - which does not return future values) - but might be other things as well we will discover once we move forward with this in the future.


Now for the original points of this issue:
fee calculation has been reworked in #3239, (although i don't think it was broken for ftx before).
3 should also be fixed by #3239 as i suspect it had to do with fees (although we never got a log of this - so are unable to confirm.
stoploss support will come (i have a working implementation - but need to test that a bit further.
