### ISSUE TITLE
FATAL EXCEPTION AFTER IMPORT IMP

### ISSUE THREAD

**Issue by shiftaET** [freqtrade/freqtrade#3136]
* Operating system: Ubuntu
  * Python Version: 3.6 
  * CCXT version: 1.17.363
  * Branch: Master 
  * Last Commit ID:
  
## Step 3: Describe the problem:
It was working fine until i edit the INIT flie and now it wont tun even with the default..

python3.6 ./freqtrade/main.py -c config.json

/home/mtg/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 42, in main
    config = Configuration(args).get_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 255, in get_config
    self.config = self.load_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 46, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 74, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 48 column 9 (char 1260)

**Comment by xmatthias** [comment]
Please read the error message before posting.
It clearly says (in the last line):
`json.decoder.JSONDecodeError: Expecting value: line 48 column 9 (char 1260)`

so the error is in line 48 - column 9 (whatever there is - it's wrong).

Please also note: As said in #3135, 

The version you're using is an outdated fork of freqtrade.
To get further support for the version you're currently using, best contact the course-creators on udemy directly - or raise the issues in the forked repository [here](https://github.com/MontrealTradingGroup/freqtrade/). 
Support in the repository is pretty sparse - and the version itself is 1.5-2 years old now - so i would not trust it with my money - but i guess it's fine to follow the course  in dry-run mode.
Also, the ccxt version is just as old - so it may or may not work on exchanges (maybe their api has changed) ... so overall i see it as risk using this old version.

If you'd like support from us (in this repository), please update to the version provided by this repository(we've fixed a TON of bugs since the fork was created).

Thanks for your understanding.
