### ISSUE TITLE
sell behaviour considerations

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#3145]
## Tight stoplosses
For problems like #3046 and #2873  ... The bot rightfully sells if the price is already below stoploss...however, something like `stoploss_grace_period` could make sense? 

- Basically don't do anything for this amount of time after you bought the pair (Here it could be interpreted also as _after_ the signal date when in shorter timeframes the bot is more likely to finalize buy orders after the signal candle).

- The counter argument would be don't use tight stoplosses. 
The counter counter argument would be that tight stoplosses are better for high volume pairs and worse for low volume pairs, at which you would argue that you could run the bot with different pairlists.

- Or add something like #2872 as a sell callback, that is when the bot fails to place a stoploss let the strategy decide returning a `SellType` that the bot should try to execute, or a grace period itself or a combination of both...

## To stoploose or not to
- If you set `stoploss_on_exchange` you can't put up a sell order; it is clear (also from the docs) that (most) exchanges only allow one type of order at a time. Here it could be useful a configuration like trailing stoploss, that enables sell orders or stoploss on exchange depending on price.
I thought it could use a `sell_roi_positive_offset`:
```
if price > trailing_stop_positive_ofs + sell_roi_positive_ofs:
    set_sell_order()
else:
    set_stoploss_on_exchange()
```

**Comment by xmatthias** [comment]
well something like #2872 will come for more things (buy/sell price for one - but potentially also for other things).

now i'm not sure what the `grace_period` should do ... not place a stoploss ? 
so you're unprotected for the first 5 minutes - if the markets dump you're suddenly 20% below your entry price - but stoploss of 5% didn't protect you as it happened within the "grace_period" ? 
I don't think that's a viable option.

tight stoplosses are a problem - yes - especially if the price moves below the "stoploss price" right before placing the stoploss ... but i would not know how else to handle this as assuming that the stoploss triggered - and initiating an "emergency sell".
That's a market order by default - but can be changed to a limit order as well (which however can be cancelled if price moves "away too fast" - so that's pretty insecure, too).

> To stoplose or not to

I'm not certain what you're suggesting here  - yes, when you place a sell order (irrelevant of the usage of orderbook or not) - the stoploss order has to be cancelled.

Just to understand what you mean:
Assuming you've placed a sell limit order at 120USDT (via orderbook or ticker pricing)- but price moves away from you (it's now at 118 USDT) ... 
you would want to cancel the sell-order, and return to a stoploss order - right? 

Now this is exactly what #2872 will enable you to do ... you get a callback every iteration - and the strategy decides "please cancel my order" - which will return it to a stoploss order (unless the sell-signal is still present i guess, in which case a new sell order (but with a new price) would be placed.

If this is about using `order_book_max != order_book_min` (walking up the orderbook, basically) - then my best suggestion is to not use this. 
It's dangerous as hell (stoploss handling - unfilled orders since they are placed assuming price will still raise `order_book_max` steps in the orderbook) - very prone to misconfiguration (using the worng price_side will walk "down" the orderbook for sells) - and every time i even think about this feature i'm thinking if it wouldn't be best to drop this ..

**Comment by orehunt** [comment]
> now i'm not sure what the `grace_period` should do ... not place a stoploss ?
> so you're unprotected for the first 5 minutes - if the markets dump you're suddenly 20% below your entry price - but stoploss of 5% didn't protect you as it happened within the "grace_period" ?

It can either not place a stoploss at all, or use a stoploss relative to the current price instead of the buy price, which will always execute successfully. 
Yes if the price drops 10x it will place a stoploss of 0.05 on a -10x so basically over zero. 

But if you care about absolute amounts, then emergency sells should be executed through #2968 . This makes much more sense from my pov. 
If the bot received a signal, then it _has_ to give some buffer time to validate such signal, otherwise you are effectively only loosing. An emergency sell means there is `0` chance profit and `1` chance loss. So you always loose in this case and the bot is bullying the strategy telling it _"you looser with your silly signals"_

This is just a temporary measure since the grace period is supposed to handle the noise, if the price didn't go up after the grace period, then the signal is wrong and it should do an emergency sell..._but at least you tried!_

I don't think there is another way to handle this automatically, apart from the callback on sell timeout, if the bot doesn't know what to do it should ask the strategy.

> Now this is exactly what #2872 will enable you to do ... you get a callback every iteration - and the strategy decides "please cancel my order" - which will return it to a stoploss order (unless the sell-signal is still present i guess, in which case a new sell order (but with a new price) would be placed.
> If this is about using order_book_max != order_book_min (walking up the orderbook, basically) - then my best suggestion is to not use this.

I was thinking that when there is no `sell_signal`, a sell order can be placed at current mininum `roi` price, or you can have the stoploss set (and ignore roi). But in order to decide which one to set you apply some logic (like price conditions). 
If you want to use the orderbook at this point, you only use it to find the position right above your `roi`, and you put the order below it, instead of placing it at exactly your roi; that's it and no other mangling with orderbooks.

While when there is a sell signal, you should be more pressured for a sell, so you would only want to choose between what's between the top ask and top bid with `ask_last_balance` and indeed ignore orderbook depth.

**Comment by xmatthias** [comment]
I think i should clarify one point up first - one of the main keys should be to protect users assets - which means that we'll try to have stoplosses "not missed" - and if they are, get out of that trade immediately (emergency-sell).

Now this can lead to more losses than necessary - but assuming that the price will raise again "for sure" will lead to positions you're stuck in for a long long time.
Compare it with holding on to an XRP / ETH / BTC position you bought in Jan 2018 (close to the BTC high)- which is now down ~70% - you can hold on to it hoping it raises again "soon"- but it's better to cut the losses and free the capital for trades which do have potential.

> I was thinking that when there is no sell_signal, a sell order can be placed at current mininum roi price, or you can have the stoploss set (and ignore roi). But in order to decide which one to set you apply some logic (like price conditions).

in crypto, the risk for this is too high - so I would not want to support such a feature (that's the reason implementing `roi_on_exchange` or something similar won't make sense, even though some exchanges would support "take-profit" orders).

Assuming you're close to your ROI (within x%) ... so you cancelled your stoploss and are now waiting for ROI to trigger - but suddenly, the market dumps by 10%.
Now the risk is lower on high-volume pairs - but on shitcoin-pairs with low volume, one big order can push the price around almost at will - so now you've blown your stoploss (you can't have both orders open at the same time) - just to "wait" for roi to fill... - so instead of eating the 5% stoploss, you're now down 10% or more ... 
The topmost priority should be to protect capital.

Now this can still happen with a regular limit sell order - but for that to be created you need to be "very close" to the destination price.

> It can either not place a stoploss at all, or use a stoploss relative to the current price instead of the buy price, which will always execute successfully.

But this would not protect users capital - if i set a stoploss of 5% - then i assume i'm only risking 5% of this stake - otherwise i'll be stopped out. 

Take the scenario you mentioned above - 
you buy at 100 USDT - now price drops 10% "within the grace period".
You're now placing the stoploss starting with the 90USDT instead of the 100 USDT - so you're now risking ~15 USDT - instead of the configured 95USDT 

Even worse - not even the 15 USDT can be guaranteed - if the price dropped 20% within the grace period, you'd now be risking ~23 USDT (`80 USDT * (1 - 0.05)`).


The percentages in the above scenario are not even relevant, if it's 1% or 10% stoploss - the thought is the same - i set the stoploss to define how much of my capital i want to put at risk within one trade.
Adding an option to "not respect this" is completely idiotic in my opinion.

... this will completely blow the whole risk consideration.

Stoploss (the initial stoploss) MUST be the hard stop line - trailing stops can move above this with ease - but NEVER BELOW THIS - and the stoploss must be calculated based on the (real) entry price - not on a price the asset happened to have 5 minutes after i bought it - as that could have me down 20% already (you also can't calculate profit off of this - as then freqtrade would tell you you're up 10% - but in reality you lost 10%).
---- 

Now an alternative approach i could imagine is to use a time-based stoploss (similar to ROI) - so where set the "stoploss is 10% in the first 10 minutes, and 5% after this, and 1% after 2 hours" ... but this will be very difficult to combine with all the other stoploss options like trailing stop, only trail after profit.
I assume also for trailing stop, you'd want to set "trail 5% for the first 20 profitable minutes, then with 1%" ... which is very difficult to combine into a structure which is simple to configure yet allows all these possibilities.

> But if you care about absolute amounts, then emergency sells should be executed through #2968 . This makes much more sense from my pov.

I think you've misunderstood #2968 - or the concept behind. That's not so much about open positions - but about how the last few trades fared. 
It'll not trigger "emergency-sells" - the idea is to stop buying if this scenario applies - to avoid giving the gains you made in the last few weeks back within one night (happened to me in February ... ) :) 
The bot would still execute open trades "as usual" - according to the strategy configuration (respecting stoploss / roi / sell-signals) - but stop entering new trades.

**Comment by orehunt** [comment]
> Now this can lead to more losses than necessary - but assuming that the price will raise again "for sure" will lead to positions you're stuck in for a long long time.
> Now an alternative approach i could imagine is to use a time-based stoploss (similar to ROI) so where set the "stoploss is 10% in the first 10 minutes, and 5% after this, and 1% after 2 hours" ... but this will be very difficult to combine with all the other stoploss options like trailing stop, only trail after profit.

You can already set a negative minimal roi and be more generous on the stoploss, so it doesn't trigger and for trailing it can be alleviated by enabling the positive offset. I think time based stoplosses are not needed because stoplosses are supposed to be "atomic" and their purpose is to react to dumps/retracements, so if you want to take a time based loss you put a negative minimal roi.

> Assuming you're close to your ROI (within x%) ... so you cancelled your stoploss and are now waiting for ROI to trigger - but suddenly, the market dumps by 10%.

No this is not a fair argument. You would adjust your offsets accordingly to the volatility of the pair you are trading, if the pair usually swings by 10% then you will switch to sell orders only after it is positive by 10%. It's up to you to set the right offset just like trailing stop.
> I think you've misunderstood #2968 - or the concept behind. That's not so much about open positions - but about how the last few trades fared.

I meant that the same concept can be applied for emergency sells, because in those kind of scenarios it is most likely to happen.
> But this would not protect users capital - if i set a stoploss of 5% - then i assume i'm only risking 5% of this stake - otherwise i'll be stopped out.
> The percentages in the above scenario are not even relevant, if it's 1% or 10% stoploss - the thought is the same - i set the stoploss to define how much of my capital i want to put at risk within one trade.
Adding an option to "not respect this" is completely idiotic in my opinion.
this would completely blow the whole risk consideration.

Except that:
- if you sell instantly you are not risking, you are just loosing.
- An emergency sell is already *very* likely to be below stoploss, so the whole risk assumption is already broken.
- I don't think that a grace period is more idiotic than an emergency sell, they are on a par on being best effort solutions to a case where the bot doesn't know what to do

**Comment by xmatthias** [comment]
Are you sure you understood when / how emergency_sells are triggerd?

They are triggered if the stoploss could not be applied. There is (as far as i've seen so far) only one reason for this - the price moved below stoploss - so selling this pair IS the right move, as the stoploss did trigger (not on the exchange though, in this case, as we've just been moving the stoploss).

> No this is not a fair argument. You would adjust your offsets accordingly to the volatility of the pair you are trading, if the pair usually swings by 10% then you will switch to sell orders only after it is positive by 10%. It's up to you to set the right offset just like trailing stop.

So what would you use for LTC/USDT?  
It usually swings 2-3% in an hour ...  but it can also dump 4% in a 5 minutes (probably in 1m).
In this case - it was almost +1% in the candles leading up to this - and then drops almost 5% in an instant - and so the numbers don't matter - it's these kind of events you need to protect from - but can't with your approach (especially not when you start looking at lower volume pairs).

![image](https://user-images.githubusercontent.com/5024695/78793484-c4bbc100-79b2-11ea-9918-1e41a2f20b5d.png)


> An emergency sell is already very likely to be below stoploss, so the whole risk assumption is already broken.

Yes - it will be below the stoploss. But if my stoploss was 5% - i'm selling at -7% - maybe -8% (assuming i didn't have the bot down for a a week - but it's really a timing issue which it usually is).
The reason for the emergency sell is that stoploss was already broken - otherwise the stoploss could've been placed.

> Let me clarify that after the grace period you would apply the real stoploss anyway and sell whatever, and I would think for the grace period to last no more than what is currently the default timeout for sell orders (15m)

Just to understand this - you'd buy at 100 USDT - wait for 15 minutes - and then apply 90 USDT as my 10% stoploss ... but for this time - i'm unprotected and my asset could fall to 50 USDT ...
Now what? i'm trying to place the stoploss at 90 USDT - which will fail, trigger emergency sell - but instead of selling for 88 USDT (stoploss failed as it dropped FAST) - i'm now selling for 50 USDT  - so thank you, you've just cost me 30 USDT because of the "grace period"...

**Comment by orehunt** [comment]
> Are you sure you understood when / how emergency_sells are triggerd?
They are triggered if the stoploss could not be applied. There is (as far as i've seen so far) only one reason for this - the price moved below stoploss - so selling this pair IS the right move, as the stoploss did trigger (not on the exchange though, in this case, as we've just been moving the stoploss).

Yes, and the reason it happens most of the times is because the spread of the pair swings the price below the stoploss. But if you look at this this way it helps I think: 

In the very unlikely scenario that you can't place a stoploss of a pair you just bought, it _might_ as well have been the case that you would have bought it a few instances later at the price it is now, so from a statistical point they could be the same price, your wallet of course would disagree :)

> So what would you use for LTC/USDT?

If history tells you that it can dump 5% in less than the time the bot can tell the exchange to switch from sell order to stoploss and you want as less risk as possible you will put it as high as you have to, where is the issue here? I think it is just parameters tuning...

> Just to understand this - you'd buy at 100 USDT - wait for 15 minutes - and then apply 90 USDT as my 10% stoploss ... but for this time - i'm unprotected and my asset could fall to 50 USDT ...
Now what? i'm trying to place the stoploss at 90 USDT - which will fail, trigger emergency sell - but instead of selling for 88 USDT (stoploss failed as it dropped FAST) - i'm now selling for 50 USDT - so thank you, you've just cost me 30 USDT because of the "grace period"...

:p You place it at 10% of 90USDT or 5% or whatever less, you will loose a little more, you won't get 88USDT but at least 81USDT and you will have given time to also go the other way around, it could also just trigger the relative stoploss immediately after, but the point is to give a time `>0` in which a buy signal can be validated.

This can maybe help too, lets formulate the outcome like this:
```
risk_adjusted_reward = ±(P&L + P&L * time_at_stake) - (1 / liquidity)
```
Issueing an emergency sell on an order that was just bought means that `time_at_stake == 0` and `P&L` is `<0`,
so it becomes:
```
= - P&L - (1 / liquidity)
```
which is strictly negative.

**Comment by xmatthias** [comment]
I don't like this issue ... it's mixing 2 completely unrelated things in my opinion.

* One is the problem with cancelled stoploss orders right after a buy
* the 2nd is the point of using take_profit orders.

the 2nd point does not provide benefit in my opinion - there is not added benefit to add  a sell order at 120 EUR right now (while the price is 110 EUR) - against placing the order when the price is at 119 EUR (which can be 2-3 orderbook slots above the current price).

For that reason, I'd like to keep this issue focused on the first of these points to avoid further confusion.

----

If your stoploss is cancelled right after the buy - then it's clear that your stoploss is to tight. There's no bullying of the strategy - it's simply a misconfiguration (stoploss can be set in the strategy - so it's bullying itself at max).

Remember, **it's a stoploss** - a stoploss defines the maximum amount of money i would want to risk.

If the price slides below that right away causing the stoploss to trigger - then your stoploss was too tight - and the buy signal was not good (but that's a different topic).

We're talking about "unable to place" stoplosses - but what if it's placed correctly? then it would sell right away - as the price slid below the stop-price.
This is correct behaviour - otherwise it would not be a stoploss anymore, but a "sell loss recomendation" at best.

Let me ask you - why is it ok to loose "a lot more than stoploss" right away without applying the stoploss - but stoploss triggering would be ok after 15 minutes? 

----
### think about real trading

you look at the chart - "see your perfect setup" - you buy - and place your stoploss (i hope).
Even if you don't place the stoploss, you'll have a clear plan - exit if it goes below X - take profit if it's above Y (or trail it until it falls back by n%).

This has nothing to do with the bot  - but about trading concepts.
 
You would not stay in the trade if it blows past your target stoploss right after buying - you would try to get the hell out to cut your losses.

The same will happen right after buying and 20 minutes after buying (the time should not make a diffeence) - if it falls below what you're willing to risk for this trade (which defines your stoploss - if done right) - you **must** exit the trade (otherwise i'm pretty certain you'll blow your account soon).

**Comment by orehunt** [comment]
I think I replied already to all your points in my last post and you keep using the word risk for an edge case where there is no risk and only loss...we are starting to go in circle here...so I won't continue..

**Comment by xmatthias** [comment]
So your point is - let's ignore the edge-case (to cover another edge case, which can be avoided by setting a wide enough stoploss) at the risk of costing the user the full (or half) amount of the trade?

**Comment by xmatthias** [comment]
Going to close this - as ignoring a stoploss would be considered a bug, and i can see no benefit in this.

what you're asking for can be accomplished with trailing stop (to some extend) - and may be covered by future enhancements allowing to dynamically set the stoploss from the strategy - 
so the real stoploss can be -50% - and after 1 minute you set it to 5% (or whatever a realistic stoploss might be).


---

Having the bot allow some time to go as far below the configured stoploss as it goes would be very risky (considering recent market crashes of 30% or more within very short timeframes, we must consider that risk in that case would be 50-100% of the position).
Most assets did recover "for the most part" - but not all did recover completely - or in a short timespan - so you'd end up stuck in a trade at -30% for weeks until it recovers to "acceptable means" ... just because the bot ignores stoploss for the first minute - and the buy-signal didn't anticipate a (never before happened) 30% crash.
