### ISSUE TITLE
Data Downloading

### ISSUE THREAD

**Issue by davideser** [freqtrade/freqtrade#3151]
Hello everybody.
I downloaded the files typing..
`  freqtrade download-data --exchange binance`
then
`  freqtrade download-data --exchange binance -t 1m, 3m,5m,15m,30m,1h  --days 200  --dl-trades `
I downloaded many things... xD
Basically I downloaded data and trades

The first few times that I started backtesting, the results were not very good, they have been improving for a few days.
<img width="760" alt="dubbio" src="https://user-images.githubusercontent.com/47193260/79074159-1df55e80-7ceb-11ea-8ca2-174d432588c1.png">
Now do I need to convert something? or is it okay?
I read that you need to convert files ...
`convert-data` ???

If you have any advice, I'm happy to listen.

Thank you so much!

**Comment by xmatthias** [comment]
`convert-data` is only if you wanna use a non-standard dataformat. 
Usually, that's not something you would need at this point.

Honestly, if you performed the actions in the sequence explained above, then you should probably remove all files - and use `freqtrade download-data --exchange binance -t 1m, 3m,5m,15m,30m,1h --days 200` (or whatever data you need).

For binance - you should **NOT** use `--dl-trades` (it's made for exchanges that don't provide this type data).
It'll convert the trades-data (raw tick data) to ohlcv candles. 
This works fine - but it's still better to use exchange provided ohlcv data if possible (which it is for Binance).

Since you did run a combination of the two - the data "may" be messed up (difficult to prove / check) - so it's best to remove all files, and start from scratch (downloading ohlcv does not take forever ... not for 200 days, anyway).

PS: binance provides data since mid 2017 ... (but not for too many pairs).

**Comment by davideser** [comment]
@xmatthias  thank you for reply me very quickly.
Thanks a lot for the explanation on the `convert-data`

So now I will have to delete all the files in that folder and use this code.
`freqtrade download-data --exchange binance -t 1m, 3m,5m,15m,30m,1h --days 200`


about the days... 200 days is too much?
Isn't it better to have a larger data download?

**Comment by xmatthias** [comment]
Well - you don't have to delete - but i would suggest as it's not clear to me which command did create which files - and you would want to start with the data that's aligned to the exchange as much as possible.

It's also not really about `convert-data` - you'll have no use for it i think ... :) 

personally, i have >2 years of data - but for backtesting, i rarely use more than a few months at a time (`--timerange ` is your friend).

This allows you to shift your intervals / test the strategy on unseen data.

**Comment by davideser** [comment]
Ok I am understanding your reasoning. 
I can also use 60days, it is also faster. Correct ??

I have to add this command  `--timerange ` when i make backtesting?

`freqtrade backtesting --datadir user_data/data/binance --strategy Strategy01 --timerange= 20180131-20200512 `

You advise me to use: `--export trades `at backtesting ?

**Comment by xmatthias** [comment]
well obviously using 30 days is faster than 200 days because thats 170 days fewer data.
However using only 30 days will also taint your strategy towards the last 30 days - so depending on the trend there, your strategy may perform badly in other conditions.
---- 

well it depends - using `--export trades` is a must if you want to plot the results - or do further analysis.

If you're just looking at the results and then "Move on to the next strategy / try" - then you won't need it ...

**Comment by davideser** [comment]
Hi, used
`freqtrade download-data --exchange binance -t 1m, 3m,5m,15m,30m,1h`

then

`freqtrade hyperopt --config.json --strategy BBRSI --hyperopt BBRSIOPT --hyperopt-loss-SharpeHyperOptLoss -e 5000 --spaces all
`

and backtesting with time range but...

<img width="1137" alt="bug" src="https://user-images.githubusercontent.com/47193260/79108709-30b57500-7d77-11ea-9173-dcb8e463e18d.png">

**Comment by xmatthias** [comment]
well - the correct syntax for download-data is `freqtrade download-data --exchange binance -t 1m 3m 5m 15m 30m 1h` (seperated by spaces, not commas).

so i suspect the download-data command went by ... very fast ... ;)

**Comment by davideser** [comment]
Ok thank you so much. The last question if you see this picture, do you see " Loading data from 2020-03-14 yp 2020-04-12 (28days)

If i want to download 2 year data of backtesting. es: like 2018to2020
How can I do ?

**Comment by xmatthias** [comment]
`freqtrade download-data --days 700` (now 700 is a guess  - but should give you roughly 2 years).

**Comment by davideser** [comment]
Thanks a lot.
I downloaded everything.

Now I am finding the best parameters for the strategy.

I'm playing with backtesting and optimization. At the moment to many values ​​(- xx%)
<img width="1349" alt="bug" src="https://user-images.githubusercontent.com/47193260/79225589-4309de80-7e5d-11ea-87a5-050ce8d35186.png">


I have one last question before I close the post. How come I still have these errors?

**Comment by xmatthias** [comment]
well you got a lot of "missing data st start" - which can come from pairs which only got listed after a specific date.


the "missing data fillup" messages are usually periods with either no volume - or of exchange downtimes - but leaving these candles "empty" does not play well with most indicator libraries (as they don't check the date).

**Comment by davideser** [comment]
How can I go about solving it?

The results of backtesting and optimizations are not very good.

**Comment by xmatthias** [comment]
well - it's warnings - basically just letting you know ... not having data for the first few months for many pairs might mean that your backtesting period should start later ... 

You can't really "solve" it if a pair wasn't listed on an exchange before April 2019 ... apart from changing the backtesting period to start at that date.

If backtesting results are not good - then that's not the fault of these warnings, but of the combination of indicators used (maybe in combination with the selected pairs ...).

**Comment by xmatthias** [comment]
I'm going to close this as the original question has been solved.
