### ISSUE TITLE
Suggestion - Ztom for ordermanagement

### ISSUE THREAD

**Issue by magick93** [freqtrade/freqtrade#3189]
https://github.com/ztomsy/ztom is an [Order Management](https://www.investopedia.com/terms/o/oms.asp) library that uses CCXT.

While Freqtrade likely already has something similar, this project, from my limited experience seems very stable - it does what it is meant to do very well.

The benefit of using a dedicated, 3rd party, reliably OMS is that Freqtrade development could focus more on trading logic (when, why and how much) rather than the lower level issues related to order management.

**Comment by xmatthias** [comment]
After having a quick look at it, this seems like a project that's not widely used / known - and also it doesn't seem very active. (12 stars, 24 commits on master, only 2 of which since August 2019).

There's several points which are clearly missing with this libray, and eliminate it from being used in Freqtrade:

* not widely known (12 stars)
* no community (all commits are from the same person)
* only 2 commits in almost a full year (-> not well supported) - only 24 commits in total
* only tested against binance (even with ccxt, exchanges do have nuances where they require different values depending on the exchange)
* does not support many ordertypes (no support for limit / market orders (not sure what is used - but you can't select it seems), no stoploss orders)


Thanks for the proposal, but this library is not an option at this stage (for reasons see above), maybe if it becomes more active, gathers a community and supports what we need - and is tested and has proven it's reliability against multiple exchanges.
