### ISSUE TITLE
Make stoploss as dynamic as roi

### ISSUE THREAD

**Issue by hclivess** [freqtrade/freqtrade#3206]
My suggestion is to change `stoploss` from float to a dictionary so it can be programmed to self-adjust in dwindling trades. The goal of this change is to give more flexibility to strategies and to reflect time passed in it. For example low timeframe strategies would have a stoploss that tightens with time to decrease risk, as the trade would be out of its planned timeframe.

Example:

```
stoploss = {

        "0": 0.20,
        "10": 0.15,
        "20": 0.10,
        "30": 0.05,
}
```

**Comment by xmatthias** [comment]
I'm not certain if this is really a good approach...
It sounds like a simple option as we have it for ROI - but if you consider that trailing-stoploss is another option - i think the 2 would be conflicting (and people would expect different things depending on their needs).

```
stoploss = {

        "0": 0.10,
        "60": 0.07,
        "120": 0.05,
        "180": 0.02,
}
trailing_stop = True
```

Assume the  above configuration  - but in combination with trailing stop (I'm intentionally leaving out the different "positive" options for now).

Now what would this mean? 

Let's assume an entry-price of 100 USDT (for simplicity...).

It trails for the first hour at -10% (`stoploss=90USDT`).
Now assume it did did raise 2% in the first hour to 102 USDT - so stoploss is now at -8% (trailing at -10% of current price).

The configured stoploss "jumps" to 7% after the hour.
should it then immediately sell as it's below 8% (92USDT) from the initial price? 
or should the configured 7% be subtracted from the current price (102USDT) (so it's now trailing at 7% (and stoploss would now be at ~95 USDT) ?



If you now also add in `trailing_stop_positive` and `trailing_stop_positive_offset`, then already thinking through how it should behave becomes difficult - as it'll depend on the strategy. 

* Maybe i wanna trail it and pull the trailing stoploss closer as it raises?
* But maybe i wanna pull the stoploss closer only if it's not raising ... but keep it at a static X% below current price if it's raising ...
* maybe i want to disable time-based options once it starts trailing ... ? 

---


Currently i don't see any way to make this possible in a way users will understand and be able to configure easily - not without utterly confusing people as to how stoploss works in combination with trailing stop, trailing stop possitive, ... etc. 

It's easy as long as it's a static stoploss - but very complex with trailing stoploss, as that has very many options...

**Comment by hroff-1902** [comment]
it may be difficult to manage it with stoploss on exchange...

**Comment by hroff-1902** [comment]
but the idea seems to be interesting for me,
need to study the objections by @xmatthias in more detail though

**Comment by xmatthias** [comment]
well - mainly my objection is that it's conflicting ...
as long as trailing_stop is inactive, it'll be ok - but once you enable that it becomes highly confusing - as you have 2 (eventually conflicting) logics working on the same, single value.

stoploss on exchange is not a problem - that's just similar to trailing stop - cancel and recreate after every change of interval (that's the smallest of all problems)

**Comment by hclivess** [comment]
But isn't roi interacting with the trailing stoploss in the same manner? It could be disabled by default, just as roi is set to one element in most cases. Only those who need it could use it, others would simply:

stoploss = {
        "0": 0.10
}

I also suggested because I thought this would be easy to add as it exists in roi. The problem with the trailing stoploss is that it is trigger-based, not time-based. This would mostly serve to cut off trades that are lingering for too long in loss with a specified range.

**Comment by xmatthias** [comment]
> But isn't roi interacting with the trailing stoploss in the same manner?

no - it's not that simple i'm afraid.

ROI looks at the positive side - so an ROI of 0.1 will look if profit is > 10%.
for ROI, it's clear that it's calculated from the open_price.

for stoploss, it's not so clear as it can have different options.
You MUST calculate stoploss from open_price (when it's static).
You MUST calculate stoploss from the maximum reached price for trailing stoploss.

```
stoploss = -0.05
```

Just the above configuration can have 2 different theoretical values (depending if trailing_stop is True or False.
It'll be 95 USDT (and stay there for static stoploss) - but it can be anything > 95UDST for trailing stoploss.

**Comment by Timmeeehhh** [comment]
As an addition to this, I was thinking about setting the stoploss as a number instead of a percentage. In my case, the lowest value of the second to last candle.

`stoploss = dataframe.iloc[-2]['close']`

At the moment this is not possible, but I could rewrite to a percentage: 
`stoploss = (dataframe.iloc[-2]['low']-dataframe.iloc[-1]['close'])/(dataframe.iloc[-1]['close'])`

Can someone tell me in which file 'stoploss' is defined, to resolve this error:
`NameError: name 'dataframe' is not defined`

**Comment by xmatthias** [comment]
@Timmeeehhh you can't change stoploss per pair at the moment, sorry.

**Comment by acemi1** [comment]
I have a suggestion.
After purchasing;
If the price makes 5% profit: Trailing Stop 1%
If the price makes 10% profit: Trailing Stop 3%
If the price makes a 50% profit: Trailing Stop 10%
If the price makes 100% profit: Trailing Stop 15%

stoploss = {

         "0.05%": 0.01,
         "0.10%": 0.03,
         "0.50%": 0.10,
         "1%": 0.15,
}

**Comment by xmatthias** [comment]
and that's the reason why i think this is a bad idea (as pointed out above).

the initial proposal assumes this to be a structure similar to roi - where it's `<min>: <value>`.

Now for trailing stop, you'd need it as `<profit>:<offset>`.

However, maybe someone else would like to combine these two - which would make this rather complex to configure (and mainly, errorprone for non-experienced users):

trail with 0.5% if 1% profit in the first hour, then trail with 0.2% if 1% profit, or with 0.3 if 2% profit ... (see what i mean?)



The structure to even configure this will become very complex very soon (due to the many options we support in regards to stoploss/trailingstop/trailingstopwithoffsetonly  

... so i strongly doubt that we'll implement anything like this in the near future, as the combination of the already existing options with a new way to configure stoploss will multiply itself from a configuration option point of view.

**Comment by xmatthias** [comment]
with #4089, this will become possible (there's an example specifically built for this issue).
