### ISSUE TITLE
allow disabling strategy validation

### ISSUE THREAD

**Issue by aak-dev** [freqtrade/freqtrade#3211]
**For building accurate renko or other candle types its best to have main dataframe updated with the given parameters.**

### Enhancement Proposal
introduce a parameter, like internals.check_dataframe = False (True by default) to switch off dataframe checks and specify in the docs that it shall only be used when the user understands what he is doing.

**Comment by xmatthias** [comment]
Please update the above post with a problem description or enhancement proposal including more information.
From the above it's not clear what you'd like, so unless we get more information we'll have to close it.

Thanks for your understanding.

**Comment by hroff-1902** [comment]
as I understood it from Slack:

he uses renko dataframes with renko bricks and indicators built on this renko brick, and he substitutes the original dataframe with the renko dataframe; previously it was okay, but with the current freqtrade version he obtains an error that the number of rows in the dataframe was altered (our checks for the dataframe we introduced are in action).

In principle, it's okay for dry/live since only last row is used as the signal.

Possible extension: introduce a parameter, like `internals.check_dataframe = False` (True by default) to switch off dataframe checks and specify in the docs that it shall only be used when the user understands what he is doing.

**Comment by aak-dev** [comment]
thanks for reiterating in a better way @hroff-1902.

**Comment by hroff-1902** [comment]
the setting allowing you to change the dataframe merged into develop branch, pls review
(See `disable_dataframe_checks` in https://www.freqtrade.io/en/latest/configuration/)
