### ISSUE TITLE
FTX Updated Fees for spot market 

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#3219]
Most FTX pairs spot markets are 

X/USD and in the past the fees were paid in USD but now with the latest update they are paid in X. 

This needs to be updated on freqtrade as right now Freqtrade thinks we bought Y amount of coins but we actually bought Y - Fee coins

**Comment by xmatthias** [comment]
Please include a bit more detail - it's not clear what the problem is from this description.

Also, please including the (api) output of an order (`fetch_order(order_id)`) (and if necessary the corresponding trades from `.fetch_my_trades(pair)` from ccxt) you're having the problem with, thanks.

**Comment by Dante2333** [comment]
This is not related to freqtrade it self but FTX;

In the past any spot market trade paid fees in USD rather than BASE currency, FTX changed this and freqtrade still thinks he paid USD when in fact it paid base.

**Comment by xmatthias** [comment]
I am aware of this - and freqtrade does handle this usually (binance does something similar) - therefore, letme ask again:
which version of ccxt are you using?
which error did you encounter (if it's with an assed bought, we'll need the logs from the section right after the trade was filled).

Also - since it'll then be related to a specific order / trade - Please provide us with the ccxt values for the corresponding order + trade.

**Comment by Dante2333** [comment]
CCXT version 1.26.85; i need to wait for a fresh buy, current logs are not useful as I have like 10 files with 11074 lines each, couldnt find a buy instance.

**Comment by hroff-1902** [comment]
the fix was merged into develop, pls verify
