### ISSUE TITLE
Sell_profit_only option not working properly

### ISSUE THREAD

**Issue by flogui** [freqtrade/freqtrade#3319]
## Step 1: Have you search for this issue before posting it?
Yes
## Step 2: Describe your environment

  * Operating system: Ubuntu on a vps
  * Python Version: 2.7.17
  * CCXT version: 1.27.54
  * Branch: Master
  * version : 2020.4 on a live trading bot
  
## Step 3: Describe the problem:
I had multiple orders that had negative profit while the sell_profit_only option was set to true. As you can see in the screen above : 

![image](https://user-images.githubusercontent.com/65234052/82125648-96968180-97a7-11ea-95e9-f04d6bfbd99a.png)

Here is my config file:

[config.txt](https://github.com/freqtrade/freqtrade/files/4638810/config.txt)

And the logs after restarting my bot :

![image](https://user-images.githubusercontent.com/65234052/82126009-f5f59100-97a9-11ea-8744-b1a92a1aa902.png)

Thanks in advance for your help,
Florian

**Comment by xmatthias** [comment]
this is almost surely caused by the use of market orders (it's visible in the screenshot of the startup logs).


You're using the right "price-side" for market sell orders  (bid side for sells) - which, based on your config - will be the "bid" value from `fetch_ticker()` - which corresponds to the first value in the orderbook.

Now freqtrade needs to know "a" price to evaluate if the trade is positive or not even if you're using market orders (where price would not be relevant). It's using the best bid (in your config) for this - however since you're placing a market order, there is nothing guaranteeing that you'll get filled at that price - as market orders get filled at ANY price the next buyer is willing to buy.

If you've ever live-watched an orderbook, you'll know that there's always orders comming in and out (also on the topmost orderbook spot), and the orderbook is rarely stable (even if maybe no trades are filled).
Now either the top-most orderbook value didn't have enough volume to fill your order - or it was pulled right before your order was placed (or someone else filled it with a market order) - but there's many possibilities as to why this can happen.

---
Since it's a market sell - the real close-value is available for telegram (market orders fill immediately - by definition) - so the real value is available.

Telegram does hint at this as well (not obvious, and honestly, not intentional):
You'll see `Current Rate` and `Close Rate`. These 2 are quite different - the "sell" decision was based on `Current Rate` - but the trade was executed at `Close rate`.
Current Rate is slightly higher for both trades - which i think will be sufficient to move these trades positive (without doing the math myself now).


You can also have a look at this in the database, there are 2 columns for close-rates - `close_rate` and `close_rate_requested` - quess which is which :D

**Comment by flogui** [comment]
Ok that's what I thought. Uhm so, what do you think can patch this unwanted behaviour. Making limit orders ? 
I still don't have understood how and why use the orderbook functionality, but is it something I must dig into ? 
Btw thanks for your exhaustive and fast answer !

**Comment by xmatthias** [comment]
limit orders will solve this as they limit (<- see the name) the order - so you'll always get filled at that price (or better).

Now obviously that doesn't mean that the order is filled - if price moves away from your order - it may be cancelled - so both market and limit orders do have drawbacks.

freqtrade's orderbook functionality is just another way to get the prices ...

one way you MIGHT be able to improve this is by increasing `ask_strategy.order_book_min` and `ask_strategy.order_book_max` (but keep them at the same value!).

To explain how that would work:
since your ask-side is bid - in the below orderbook situation freqtrade would use 99 as price. 
If you enable orderbook (at this side, anyway) and increase the 2 values mentioned above to 2 - then it would assume the price as 98 ... effectively reducing the "assumed" profit of a sell order.

now since you're still using market orders - you MIGHT get filled at 99 - or at 98 .. but changes to be filled at 98 or 99 are higher than if the assumed price is 99.


```
...
103
102
101  # ask
-------------Current spread
99   # bid
98
97
...
```

**Comment by flogui** [comment]
Thanks ! I better understand the utility of the orderbook. The orderbook thing is more clear now than it was when I read the docs.
