### ISSUE TITLE
Kali Linux installation issue virtualenv command not found

### ISSUE THREAD

**Issue by joe-nano** [freqtrade/freqtrade#3350]
Has anyone encountered any issues with Kali Linux installation problems? 
Particularly there is a Pip3 installation error and also a virtualenv error. 

There seems to be an issue as the files of pip3 seem to be installed on the .local folder

Also they tried installing the virtual environment but there seems to be an issue, please advise how I could go about this, says that virtualenv command not found

![image](https://user-images.githubusercontent.com/35530212/82517651-7c490480-9b15-11ea-9bb2-7ed368600f29.png)

**Comment by xmatthias** [comment]
One thing to note up front: Kali linux is an expert system. Certain things are just not user friendly because noone cares, as their target audience has enough technical knowledge to fix eventual problems.

If you've got to ask the above question, best use a different system like Ubuntu - which is designed to be user friendly.


If you're keen to continue with Kali linux, best search help in Kali linux expert forums. This question however has nothing to do with freqtrade, nor with it's installation, but on how to get your system up and running correctly.

I'm sorry, but helping you get your system fixed is clearly not something we will be able to help you.
Thanks for your understanding.

**Comment by joe-nano** [comment]
Hello Xmatthias,
I installed my bot on an Ubuntu, just checking if anybody has encountered this with Kali. Someone was using Kali and had this problem. I think he's certainly expert using Kali. But I recommended Ubuntu instead. Thanks for your response.
