### ISSUE TITLE
Bugs in downloading data

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3354]
These issues were found for new unsupported excange (qtrade), but indicate general problems in handling downloaded data.

How to reproduce:
-- (update to latest ccxt)
-- run `freqtrade download-data --exchange qtrade -t 1d -p CCX/BTC` twice

* First time download-data creates json files with empty list: `[]`, which is probably is not incorrect, but should be at least reviewed. Maybe the proper behavior here would be avoiding creation of the datafile with the empty list...
* On the second run, ohlcv_load() fetches empty DataFrame and fails assigning columns to it, should be gracefully handled.

**Comment by xmatthias** [comment]
I don't see this as a bug in freqtrade to be honest (i mean - nothing is crashing - it's just saying "downloaded with length 0".

if you run `ct.fetch_ohlcv('CCX/BTC', '1d', since=int((datetime.utcnow() + timedelta(days=-5)).timestamp() * 1000))` - you'll get no result.

if you run `ct.fetch_ohlcv('CCX/BTC', '1d')` - you'll get 98 candles starting with the first of January - ending mid-april (also verbose mode confirms this).


On the contrary - if you run `freqtrade download-data --exchange qtrade -t 1d -p CCX/BTC --days 200` - you'll get the data as shown above (from January 10th until April 15th). 
Running this again does NOT download further data - so either their api is broken - or ccxt has a bug in their pagination - but either way, i don't see this as a freqtrade bug.

**Comment by hroff-1902** [comment]
Nah, my bad. When I was localizing the reason, I moved from the long list of pairs in the config to one pair set in the cli, as above, and decided that the rest of pairs is not downloaded after the error.

Actually, when run as `freqtrade download-data --exchange qtrade -t 1d -p CCX/BTC TAO/BTC`, for example, the data for TAO/BTC is downloaded after the error.

Not a bug, closing.

**Comment by xmatthias** [comment]
But what's wrong with CCX/BTC then?

is it a pair that was only traded between january and april ... ? strange things are happening ...

**Comment by hroff-1902** [comment]
Nothing wrong with the pair -- simply no data for (more than) last 30 days.

I (wrongly) thought that this situation is incorrectly handled by download-data/other commands that load data and that it prevents other pairs from being loaded...

**Comment by xmatthias** [comment]
ah i see 👍
