### ISSUE TITLE
Catching rate limited

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3361]
Bittrex

##  Describe the problem:
Setting  rateLimit too low, sometimes get the bot banned 

### Steps to reproduce:

"ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
  
### Observed Results:

  * What happened?
Banned
  * What did you expect to happen?
Immediate Waiting for 30s or more (instead of retrying 3 times and wait 30s)
Dynamic change of ccxt rateLimit for more 50 (ie 200->250)

### Relevant code exceptions or logs:

  ```
2020-05-23 04:29:45,402 - freqtrade.worker - INFO - Bot heartbeat. PID=652, version='develop-d31a091d', state='RUNNING'
2020-05-23 04:30:13,926 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: TimeoutError
2020-05-23 04:30:13,926 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: TimeoutError
2020-05-23 04:30:45,533 - freqtrade.worker - INFO - Bot heartbeat. PID=652, version='develop-d31a091d', state='RUNNING'
2020-05-23 04:30:45,562 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BCH/USDT due to RateLimitExceeded. Message: GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=fiveMin&marketName=USDT-BCH 429 Too Many Requests <!DOCTYPE html>

 2020-05-23 04:36:07,650 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 3 times
2020-05-23 04:36:07,828 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair LTC/USDT due to RateLimitExceeded. Message: GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=fiveMin&marketName=USDT-LTC 429 Too Many Requests <!DOCTYPE html>

<title>Access denied | bittrex.com used Cloudflare to restrict access</title>
  ```

**Comment by xmatthias** [comment]
i think you misunderstand how `"rateLimit": 200` works.

it's passed diretly to ccxt, overriding the ccxt default (which is supposed to be adapted to each exchange...).
By assigning it manually in freqtrade, you're telling ccxt "i know better" - which is fine if you know you're only doing this action which doesn't "cost" much.

If you look at our sample configurations, we have different settings per exchange (bittrex is in `config.example`.
For binance, we know 200 works fine (through extensive testing). 
For bittrex, everything below 500 will most likely get you banned - but you may need a higher number if you're using a high number of pairs in your pairlist).

If you're experiencing bans, please raise the rateLimit parameter (Or remove it from the configuration to use the CCXT default) and restart the bot.

---

We do not implement dynamic backoff - nor will we in the future. RateLimiting is handled by ccxt by setting the rateLimit parameter to something appropriate.

If we were to wait 30s - then 60s - that would mean you might skip your stoploss as we're not doing anything for 60s (bittrex has no stoploss on exchange, so constant updates are important) - therefore the rateLimit parameter has to be selected so you are not getting banned in the first place.

The main reason for not doing this automatically is because exchanges usually handle this in an increasing manner.
Assume the exchange Blocks you for 1m - you're not doing anything for this minute - but the next block is for 10m - then we are not allowed to do anything for 10 minutes...

Therefore - either leave the defaults as they are (which are tested to be working) - or if you lower / change them - then please do so at your own risk.

**Comment by Pascal66** [comment]
Ok, understand, thank you.

**Comment by hroff-1902** [comment]
Well, actually freqtrade implements some kind of backoff -- if a temporary error appears (including that caused by exchange banning for amount of requests), and this error does not disappear in 4 attempts (our exchange retrier implements this), then this unrecoverable temporary error is raised at the top level, catched in the worker which throttles the bot logic, and in this case it sleeps for 30 seconds, before it runs for the next throttling iteration. Anyway, that's all what freqtrade can do in this case, if the banning time is longer, we cannot find it before throttling next time.

All rateLimit logic is incapsulated in the ccxt lib in the same time, it's just a parameter passes to ccxt.

**Comment by fridary** [comment]
@xmatthias Is there cache mechanism if I run 10 bots (10 strategies) and each has 100+ the same pairs? If strategy use `1m` interval, so this is 1000 reqs/minute and I get rate limit. Can I cache fetched data and share among bot instances?

**Comment by xmatthias** [comment]
@fridary You should scale horizontally, to multiple different VPS servers to avoid this.
Exchanges usually do rate-limiting by IP address.

Also - please don't revive issues that are over a year old, thanks.
