### ISSUE TITLE
Introduce "--pairs" and "--export-filename" in hyperopt module

### ISSUE THREAD

**Issue by apneamona** [freqtrade/freqtrade#3407]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: 1.28.49
  * Freqtrade Version: 2020.4

## Describe the enhancement
I would like to make some suggestions for hyperopt module:
- introduce optional argument "--pairs",
- introduce optional argument "--export-filename",
  so we can control the process using a script if we need to calculate parameters for multiple pairs individually and/or to save the current hyperopt file under a custom name instead of deleting the old file and creating new one

**Comment by xmatthias** [comment]
`--export-filename` - definitely makes sense.

I'm not convinced about `--pairs` though. 
Hyperopt (similar to backtesting) supports and uses freqtrades pairlist configuration - which combines white-, blacklist and filters to get to the final pairlist. 
Overriding this with --pairs would be a very clumsy interface (mainly because you'd need to specify 20, 30 pairs in sequence, without syntax error (missing space, additional comma) on the commandline.

I personally doubt that too many use it like this for download-pairs (Unless testing somethign quickly with 1-2 pairs).

**Comment by hroff-1902** [comment]
It should not be called `--export-filename`, because file with hyperopt results is not an 'export file'

In current terms, `hyperopt-list` subcommand exports csv-file, that's the hyperopt export file, using `--export-filename` for hyperopt results will introduce mistakes, which file it's applied for.

**Comment by hroff-1902** [comment]
`--pair` for hyperopt may have only sense if same option is added for the `backtesting` subcommand

**Comment by xmatthias** [comment]
what's the difference between changing the script vs. changing the configuration?

also - you can pass in `--config -` as last option - passing in an almost empty config with the pair if you really want it in the script ...

**Comment by hroff-1902** [comment]
* changing the "main" config file can be difficult for scripting (need to parse json/save it)
* yes, the use of a special config with the pairlist consisting of a single pair can be a solution for it (since that config can be easily crafted, instead of parsing the "main" config)
* however, passing a pair or a list of pairs is easier anyway, we already have this option in other subcommands, so adding it for backtesting/hyperopt would be logical and not heavy for implementation.

I would also make it as a "Good First Issue" (if you agree this is a useful addendum)

**Comment by apneamona** [comment]
Hello again.
The idea behind this proposal is precisely to enable the testing of pairs individually, in search of their best parameters, in an effort to group pairs according to the same or similar parameters.
As mentioned here, I now run this using multiple config files and a simple bash script.
I haven’t thought about how to call the new option, but maybe ‘--per-pair’ makes sense, instead of ‘--pairs’.
With this, we could use the existing list from the config file and / or issue a command and a new parameter '--per-pair BTC/USDT ETH/USDT ...' for example, and to expand this idea a little.

**Comment by apneamona** [comment]
The idea behind proposing a new '--export-file' parameter is precisely to enable some sort of saving mechanism, in addition to the existing replacing mechanism.
Again, I wasn’t thinking about terminology, but maybe it could be something like ‘--save-as’ or something.

**Comment by apneamona** [comment]
Question: where can I express something about the greatness of this project and the work you all have done? Well done!

**Comment by xmatthias** [comment]
I still don't think that `--pairs` should be added to backtesting. 

It'll collide with the pairlist configuration, overwriting that (which can lead to other, unexpected results).

The --export parameter on the other hand makes sense - but i'd like to have hyperopt store it with timestamp if this is not specified - didn't happen only to me to overwrite / delete my results accidentally by restarting hyperopt  - however that's a "bit" more challanging as hyperopt-list and hyperopt-show will need to be able to "refind" the latest of these files.

**Comment by xmatthias** [comment]
`freqtrade hyperopt` will now preserve previous results (timestamp is part of the filename).

Further commands (`freqtrade hyperopt-list`, `freqtrade hyperopt-show`) can use the newly introduced `--hyperopt-filename` argument to specify a particular file - otherwise the commands will default to the last available file.

**Comment by apneamona** [comment]
Very nice. Thank you.
