### ISSUE TITLE
when will freqtrade add short trading?

### ISSUE THREAD

**Issue by ZhenZinian** [freqtrade/freqtrade#3436]
## Describe the enhancement

considering it is crucial in bear market, will freqtrade support short trading? when?

**Comment by xmatthias** [comment]
Since we are an open source project, with everyone contributing their time for voluntarily, and for free, we do not provide any timing estimates.


we do have a few open issues which relate to this, #892 - which however needs #2183 to be in place first, so feel free to subscribe for updates to either of these issues.

One final note:
Personally, i find this issue offending to everyone contributing to freqtrade - since you are demanding to know "when will this happen" without even taking the time to search through the issues to see if we have issues relating to this topic (see links above), which is a clear sign of disrespect towards everyone spending time on this project.


Thanks for your understanding.

**Comment by ZhenZinian** [comment]
thanks for reply and Im very much appreciate your work.

will stay tuned
