### ISSUE TITLE
Using historical data in live trade for initialization?

### ISSUE THREAD

**Issue by gletreut** [freqtrade/freqtrade#3442]
## Describe your environment

  * Operating system: Linux-4.15.0-101-generic-x86_64-with-glibc2.2.5
  * Python Version: Python 3.8.2
  * CCXT version: ccxt==1.27.1 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2020.4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hello,

It seems that whenever starting a bot in production mode with the `trade` command, the initialization phase waits from that time until the startup candle defined in the strategy is reached. Provided that there is historical data available, is there a way to use it for computing strategy indicators from an earlier initiation time so that trades can start right away when the `trade` command is launched?

I hope this is the right place to ask. Best.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well - the short answer is no, that's not happening.

When freqtrade starts up in trade mode, it fetches the last 500 candles for all pairs in the pairlist.
This will happen for every pair at every candle to ensure there can be no mistake in building the candles ourselfs.


Freqtrade itself has no mechanism to wait "startup_candle" in trade-mode - this variable only matters in backtesting, where it'll use this as "additional" data on top of the defined timerange.
For trade mode itself, it has no sense either - since the bot always has access to the last ~500 candles - all indicators should correctly calculate for the last candle (that's the one that matters in trade mode).

However, a strategy might be able to cause this, assuming for example it assigns a variable with every iteration which only acts once this reaches a certain threshold.

**Comment by gletreut** [comment]
Alright, I must be missing something else. Thanks!
