### ISSUE TITLE
Possible to only process full candles?

### ISSUE THREAD

**Issue by djangcy** [freqtrade/freqtrade#3498]
## Describe your environment

  * Operating system: Ubuntu 18.04.4 LTS
  * Python Version: 3.6.9
  * CCXT version: 1.18.119
  * Freqtrade Version: 0.17.3
  
## Your question

Is it possible to only make buy/sell decisions after a full candle has been placed?
For example: If I use a 5m ticker in my strategy, the bot will only be able to trigger buys/sells on each candle (being 5 minutes apart) after processing it.

**Comment by hroff-1902** [comment]
> Is it possible to only make buy/sell decisions after a full candle has been placed?

Yes, current incomplete candle is always removed, if it's provided by exchange.

**Comment by djangcy** [comment]
Would that mean that if the current candle is incomplete, the previous candle is used?

**Comment by xmatthias** [comment]
yes. the incomplete candle's close would repaint - change every few seconds.
That creates very unreliable signals - there's whole whitepapers about repainting as it's a huge problem ...

If you only use candle data and technical indocators for buy / sell signals, the signals will only change at the full candle.
However - if you use realtime data (orderbook, ticker) - then signals may change in between too.

Also - selling is always possible via either ROI, stoploss or trailing stoploss - as these are evaluated at every iteration - and not just at fulll candles (otherwise you might blow your stoploss big-time ...).

**Comment by djangcy** [comment]
Thank you so much for the response. I've managed to fix the problem :)

**Comment by operational13** [comment]
Hi Matthias,

Based on what you said: '_Also - selling is always possible via either ROI, stoploss or trailing stoploss - as these are evaluated at every iteration - and not just at fulll candles (otherwise you might blow your stoploss big-time ...)._'

Is there a way for the user to decide if they would like to execute the ROI/SL/TSL at the end of the candle instead of immediately during the progress of the candle? I notice the assumptions during backtesting are different to that of live/dry run trading, and would like to see if I can manipulate live/dry run trading to mirror backtesting.

Thank you!

**Comment by hroff-1902** [comment]
> Thank you so much for the response. I've managed to fix the problem :)

I wonder, what was the problem?
