### ISSUE TITLE
Sending Buy signal while Sell signal is active

### ISSUE THREAD

**Issue by gathad** [freqtrade/freqtrade#3551]
## Describe your environment

  * Operating system: WSL, Ubuntu 20.04 LTS
  * Python Version: python 3.8.2 
  * CCXT version: 1.30.34 
  * Freqtrade Version: freqtrade developer-11290645 
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,

I'm trying to create a bot which buys some coins according to buy signal and just sell it after limit order is filled. So, I'm letting the sell signal activated continuosly. But I realized that bot is not buying while sell signal is activated. I have found something similar "bot is not selling while buy signal is activated" but it's not the case right now.

The logic is simple, I'm trying to buy low priced coins from bid price and sell them just after buying to ask price for 1 satoshi profit. I have configured bid and ask strategies according to that. So there is no problem on this point too. But since I'm sending sell signals always, I can't buy anything. 

-I have tryed to buy everything on dryrun (buy if the close is lower than 20 BTC) and send also sell signal (sell if the close is lower than 20 BTC). Bot didn't buy anything. 
-I have changed the sell signal (sell if the close is higher than 20 BTC, so condition is always false) it did buy everything. 

How can I configure it just "buy even the sell signal is active" and "sell even buy signal is activated (It's on documentation, no problem on selling point actually)"? Is there any configuration etc. for that?

**Comment by xmatthias** [comment]
The short answer is - you can't. 

This approach would be too risky for almost all strategies, as it would result in buy / sell iterations within seconds depending on the rest of the configuration.
Please adjust your strategy accordingly, to NOT send a sell-signal if you've got a buy-signal - otherwise the bot will simply not buy (as you've already observed).

Just to reiterate this - we also have no plans to change this behaviour as it's fully intended as it is, and any change to it would only lead to problems.

If you want an "immediate" sell you can also use ROI: `{"0": -1}` instead of always setting sell-signal to 1 - which will sell each pair immediately, no matter at what price.

**Comment by gathad** [comment]
Hello,

Thank you for very fast answer.

Minimal roi solution will work fine on my strategy.

I want to ask another question about stoploss. Maybe it will be better if it's going to be another issue. 

There is no explanation about stoploss limit order while stoploss on exchanger is deactivated. Is it using askstrategy to select the price? Is it using order book? If not, is there a way to use order book and select ask or bid price for stoploss?

**Comment by xmatthias** [comment]
stoploss and ROI both use the configured pricing strategy (for the sell side, obviously), which is [documented](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders).

**Comment by gathad** [comment]
Thank you very much.

I'm closing the issue since I have got all answers clearly and there is no bug or issue.
