### ISSUE TITLE
Backtesting an ichimoku TA based strategy using different timeframes for informative and trading pairs causes df to miss informative pair data 

### ISSUE THREAD

**Issue by teixeluis** [freqtrade/freqtrade#3593]
## Describe your environment

  * Operating system: Raspbian 10 (buster)
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.30.64
  * Freqtrade Version: freqtrade develop-86cf6201
  
## Describe the problem:

I have created a strategy where I am using the ichimoku indicator (from https://github.com/freqtrade/technical), and attempted to define as informative pairs, the same pairs used for trading but with a larger timeframe (in my test, 1d for the informative and 5m for the trading pairs).

As such I load and populate the indicators as shown below. First I obtain the informative pairs based on my configured whitelist, with a 1 day granularity, and then the dataframe is populated both with the values from the ichimoku ouput, for the 5m timeframe, and with another set of entries to contain the output from the ichimoku function, but applied based on the 1d timeframe:

```
    def informative_pairs(self):
        # get access to all pairs available in whitelist. 
        pairs = self.dp.current_whitelist()

        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1d') for pair in pairs]

        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Ichimoku Cloud:

        ichi=ichimoku(dataframe)

        dataframe['tenkan']=ichi['tenkan_sen']
        dataframe['kijun']=ichi['kijun_sen']
        dataframe['senkou_a']=ichi['senkou_span_a']
        dataframe['senkou_b']=ichi['senkou_span_b']
        dataframe['cloud_green']=ichi['cloud_green']
        dataframe['cloud_red']=ichi['cloud_red']

        # Obtain the informative pair dataframe:

        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe='1d')

        print("populate_indicators: informative dataframe obtained: ")
        print(informative.tail())

        # Populate the dataframe with its data:

        ichi_informative = ichimoku(informative)

        dataframe['tenkan_inf'] = ichi_informative['tenkan_sen']
        dataframe['kijun_inf'] = ichi_informative['kijun_sen']
        dataframe['senkou_a_inf'] = ichi_informative['senkou_span_a']
        dataframe['senkou_b_inf'] = ichi_informative['senkou_span_b']
        dataframe['cloud_green_inf'] = ichi_informative['cloud_green']
        dataframe['cloud_red_inf'] = ichi_informative['cloud_red']
        dataframe['close_inf'] = informative['close']

        print("populate_indicators: resulting dataframe: ")
        print(dataframe.tail())

        return dataframe
```
However, unless I match the two timeframes (which is pointless in my use case), when I run the backtests (after having downloaded the 5m and 1d data), the result from populating the dataframe does not contain any of the ichimoku output from the informative dataframe:

```
populate_indicators: resulting dataframe: 
                           date      open      high       low     close     volume    tenkan  ...  tenkan_inf  kijun_inf  senkou_a_inf  senkou_b_inf  cloud_green_inf  cloud_red_inf  close_inf
26322 2020-07-11 09:30:00+00:00  0.000002  0.000002  0.000002  0.000002  3500032.0  0.000002  ...         NaN        NaN           NaN           NaN              NaN            NaN        NaN
26323 2020-07-11 09:35:00+00:00  0.000002  0.000002  0.000002  0.000002  2097117.0  0.000002  ...         NaN        NaN           NaN           NaN              NaN            NaN        NaN
26324 2020-07-11 09:40:00+00:00  0.000002  0.000002  0.000002  0.000002   762097.0  0.000002  ...         NaN        NaN           NaN           NaN              NaN            NaN        NaN
26325 2020-07-11 09:45:00+00:00  0.000002  0.000002  0.000002  0.000002  3578594.0  0.000002  ...         NaN        NaN           NaN           NaN              NaN            NaN        NaN
26326 2020-07-11 09:50:00+00:00  0.000002  0.000002  0.000002  0.000002   649084.0  0.000002  ...         NaN        NaN           NaN           NaN              NaN            NaN        NaN

```

Is this the expected behavior? Is it related to the diferent timeframes (e.g. inability to resample the less granular source of data)?

### Steps to reproduce:

  1. build strategy with the populate_indicators and informative_pairs functions shown above
  2. download the candlestick data for the two used timeframes (in my test I used 1d and 5m for the informative and trading pairs respectively)
  3. run the backtesting for the period covered by the downloaded candlesticks.
  
### Observed Results:

  * What happened? dataframe not fully populated. Backtesting results were invalid.
  * What did you expect to happen? dataframe populated with output from both ichimoku calls.

### Relevant code exceptions or logs

If I backtest with startup_candle_count > 0 and informative and trading pairs have different timeframes, I obtain the following exception:

```
populate_indicators: resulting dataframe: 
                        date      open      high       low     close        volume  ...  kijun_inf  senkou_a_inf  senkou_b_inf  cloud_green_inf  cloud_red_inf  close_inf
84 2020-07-07 00:00:00+00:00  0.000002  0.000002  0.000002  0.000002  1.971748e+09  ...   0.000001  8.225000e-07  7.600000e-07             True          False   0.000002
85 2020-07-08 00:00:00+00:00  0.000002  0.000002  0.000002  0.000002  5.754905e+09  ...   0.000002  8.225000e-07  7.600000e-07             True          False   0.000002
86 2020-07-09 00:00:00+00:00  0.000002  0.000002  0.000002  0.000002  2.774248e+09  ...   0.000002  8.225000e-07  7.600000e-07             True          False   0.000002
87 2020-07-10 00:00:00+00:00  0.000002  0.000002  0.000002  0.000002  2.723224e+09  ...   0.000002  8.250000e-07  7.600000e-07             True          False   0.000002
88 2020-07-11 00:00:00+00:00  0.000002  0.000002  0.000002  0.000002  1.214834e+09  ...   0.000002  8.325000e-07  7.600000e-07             True          False   0.000002

[5 rows x 19 columns]
2020-07-14 23:45:36,784 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/lteixeira/projectos/crypto/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/lteixeira/projectos/crypto/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting.start()
  File "/home/lteixeira/projectos/crypto/freqtrade/freqtrade/optimize/backtesting.py", line 401, in start
    min_date, max_date = history.get_timerange(preprocessed)
  File "/home/lteixeira/projectos/crypto/freqtrade/freqtrade/data/history/history_utils.py", line 371, in get_timerange
    for frame in data.values()
  File "/home/lteixeira/projectos/crypto/freqtrade/freqtrade/data/history/history_utils.py", line 371, in <listcomp>
    for frame in data.values()
  File "/home/lteixeira/projectos/crypto/freqtrade/.env/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/home/lteixeira/projectos/crypto/freqtrade/.env/lib/python3.7/site-packages/arrow/factory.py", line 184, in get
    return self.type.fromdatetime(arg)
  File "/home/lteixeira/projectos/crypto/freqtrade/.env/lib/python3.7/site-packages/arrow/arrow.py", line 234, in fromdatetime
    tzinfo,
  File "/home/lteixeira/projectos/crypto/freqtrade/.env/lib/python3.7/site-packages/arrow/arrow.py", line 83, in __init__
    year, month, day, hour, minute, second, microsecond, tzinfo
TypeError: integer argument expected, got float
```

In this case I am not totally sure this is unexpected because obviously if the informative and the trading pairs have different timeframes, there will be no alignment between the respective candle indexes and their timestamps. If this situation is expected to you have a suggestion on how can we configure this scenario? Is it possible to also tell how many candles from the informative pair must occur before engaging in trades?

Thank you

Cheers

**Comment by xmatthias** [comment]
I think your main problem is understanding how pandas works.
Think about it as an excel sheet ... in the end, it's not that different (although alot more powerfull).

The way you're assigning 1d data to 5m data MUST give you empty rows, since you're assigning 1d candles to 5m candles. 
a simple example:
you have 3 days of 5m data (~500 candles) - and 20 days of daily data (20 candles).

Now you assign a column of 20 values to a column with 500 values. The way you're doing it, the 20 days will end up in the first 20 rows.
The days / time will not match - which can introduce a lookahead bias (backtesting is using data it should not know - as it did not happen yet).
If you were to plot `dataframe.head()` instead of `dataframe.tail()` - you'll see that there is data - but not everywhere - and it's data from completely different days.

In dry / live this often works accidentally (but is not guaranteed), if both dataframes are of the same length (as the last rows match - but this is accidental and not something you can rely on).
It'll also seem to work if the right dataframe is longer (more daily candles for whatever reason) - but then you'd be using old daily data for current trading decisions (eventually ignoring the last few days).
---

The proper way to do this is by merging the dataframes based on time.
There is [technical](https://github.com/freqtrade/technical/#usage) which aims to simplify that (you should be able to reuse the 2nd part of the example (no need to resample - but to "resampled_merge").

below are roughly the steps `resampled_merge` executes (if you'd rather do this yourself):
* Rename columns to be unique (so `"close"` becomes `"close_1440"` (1440 minutes per day))
* Merge data on `"date"` (this assures that the 5m data from sunday matches with the daily "sunday" column
* forwardfill (use the same value for the whole day)

Now the forwardfill step is optional (but usually required / desired) - as otherwise you'd end up with a dataframe as follows:

```
2020-07-01 00:00:00 open high low close close_1d
2020-07-01 00:05:00 open high low close NAN
2020-07-01 00:10:00 open high low close NAN
...
2020-07-01 23:55:00 open high low close NAN
2020-07-02 00:00:00 open high low close close_1d
2020-07-02 00:05:00 open high low close NAN

```

It's important to point out that any indicators you need on the longer timeframe MUST be calculated before resampling, as otherwise they would be on the 5m frame - with hundreds of times the same value.

**Comment by teixeluis** [comment]
Hi @xmatthias, thanks for the thorough explanation. Will make the appropriate changes to account for the resampling of the data after calculating the indicators from the longer dataframe.

Cheers
