### ISSUE TITLE
freqtrade:master_pi docker-compose does not persist trades

### ISSUE THREAD

**Issue by RaphaelNanje** [freqtrade/freqtrade#3598]
## Describe your environment

  * Operating system: Raspberry Pi 3b
  * Freqtrade Version: freqtradeorg/freqtrade:master_pi freqtrade 2020.6

## Describe the problem:
The dry-run database does not persist after stopping/starting docker. It seems like the docker container is not writing to tradesv3.dryrun.sqlite in the user_data folder.

`tree -L 1 user_data/`
```
tree -L 1
.
├── backtest_results
├── config.json
├── data
├── hyperopt_results
├── hyperopts
├── logs
├── notebooks
├── plot
├── strategies
├── tradesv3.dryrun.sqlite
└── tradesv3.sqlite

8 directories, 3 files
```
`ls -la`
```
total 68
drwxr-xr-x 10 root   root    4096 Jul 13 22:48 ./
drwxrwxr-x  3 ubuntu ubuntu  4096 Jul 13 22:37 ../
drwxr-xr-x  2 root   root    4096 May 27 21:16 backtest_results/
-rwxrwxrwx  1 ubuntu ubuntu  4236 Jul 13 22:48 config.json*
drwxr-xr-x  3 root   root    4096 May 27 21:46 data/
drwxr-xr-x  2 root   root    4096 May 27 21:16 hyperopt_results/
drwxr-xr-x  2 root   root    4096 May 27 21:16 hyperopts/
drwxr-xr-x  2 root   root    4096 Jul 13 22:00 logs/
drwxr-xr-x  2 root   root    4096 May 27 21:16 notebooks/
drwxr-xr-x  2 root   root    4096 May 27 21:16 plot/
drwxr-xr-x  3 root   root    4096 May 31 02:54 strategies/
-rw-r--r--  1 root   root       0 Jul 13 22:00 tradesv3.dryrun.sqlite
-rw-r--r--  1 root   root   20480 Jul 13 21:59 tradesv3.sqlite
```
### Steps to reproduce:

1. `sudo docker-compose run --service-ports freqtrade trade -s BBRSI5m --dry-run`
2. Allow freqtrade to make a few trades
3. ctrl-c
4. `/status table` on telegram

### Observed Results:

  * What happened?
  No active trades found in database
  * What did you expect to happen?
  I expected the trades to persist.

### Relevant code exceptions or logs
```
2020-07-15 22:25:14,137 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-07-15 22:25:14,137 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 12 ...
2020-07-15 22:25:14,139 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2020-07-15 22:25:14,141 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
```

**Comment by xmatthias** [comment]
The log suggests that you are not using the docker-compose file freqtrade provides (at least not without heavy changes), as that has the database url fixed to `user_data/tradesv3.sqlite` (see below).

Now you can change this db-url to whatever you want - but you must make sure it's part of a mountpoint (which by default, is all of `/freqtrade/user_data`) - otherwise the database only exists within the docker container - and will be deleted as soon as you upgrade / restart.

while it's possible to mount the file directly - i would advise against that and instead change the db-url to be something within user_data/, as otherwise you must make sure that the database exists before starting the container - which can lead to odd errors.

https://github.com/freqtrade/freqtrade/blob/18a5822a339cc3c88bc460df4a430f9c554e2cdf/docker-compose.yml#L13-L21

**Comment by RaphaelNanje** [comment]
Thanks adding the --db-url to docker-compose run --service-ports freqtrade trade -s BBRSI5m --dry-run solved it!

I ended up making a Makefile so I don't have to keep changing the DB URL:
```make
dryrun:
        sudo docker-compose run --service-ports freqtrade trade -s BBRSI5m --dry-run --db-url sqlite:////freqtrade/user_data/tradesv3.dryrun.sqlite 
liverun:
        sudo docker-compose run --service-ports freqtrade trade -s BBRSI5m --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite 
```
