### ISSUE TITLE
edge refactoring and strategy interface

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#3602]
Refactor edge by changing strategy interface #2183:
- introduce methods `populate_stake_amount`, `populate_stoploss`, etc..
- the bot would consider the value on the last candle during live just like signals
- wherever currently the bot checks with `if self.edge`... those calls would use these methods and would do what edge currently does
- the edge calculation and filtering would be done in an `EdgeFilter` or in `process_loop_start` (and the edge filter would just fetch the precomputed filtered pairlist)

By default the new methods would give a flat column of the values given by the config/strategy, which retains 100% backward compatibility, while edge would be provided as a parent strategy and no more hard coded in the bot.

**Comment by xmatthias** [comment]
I'm tempted to add a new label here called "I want that" ...

it'll declutter Edge (it does too much - and should be split out - and I've long been been in favor of refactoring that).

I do mostly agree.
The only point i'm not certain (and i think we need to be careful):

> the bot would consider the value on the last candle during live just like signals

What exactly do you mean with this? 

> introduce methods `populate_stake_amount`, `populate_stoploss`, etc..

yes(ish) - but i think it should somehow be aligned to #2183 .
Allowing dynamic stake-amount is part of that issue as well (open 50% of stake, ...) - but i like the idea of having a separate call (it can also be used by backtesting - with default just returning stake_amount) - as that is most likely the most flexible way to do this.

We just need to ensure it ain't colliding with "dynamic stake-amount" we already have (by setting stake_amount to unlimited ...) - but i guess if the method returns "unlimited", then the existing dynamic logic kicks in - so it wouldn't be heavily breaking either.

**Comment by orehunt** [comment]
> The only point i'm not certain (and i think we need to be careful):
> 
> > the bot would consider the value on the last candle during live just like signals
> 
> What exactly do you mean with this?
> 
roi/stoploss would always fetch what's and the latest (by date) candle, while buy/sell would have to locate by the date matching the signals...we are assuming vectors here right? That's why i called them `populate_` and not `get_`

**Comment by xmatthias** [comment]
at least for ROI, that'll definitely not work (but i'm also rather sceptical about stoploss ...).

Assume i run hourly candles - but have my ROI set as follows:

```
{'0': 0.1, '90': 0.5, '100': 0.3, '360': 0.1}
```

Even though we're working on hourly candles, ROI switches twice within the 2nd candle (first to 0.5, then to 0.3). When using the last candle value, you cannot recreate this - which causes a problem.

This is obviously difficult to reconstruct in a vectorized way (i guess that's why it hasn't been implemented in edge, although other reasons were brought forward at that time).
However, to be somewhat aligned, this should be respected (it is in backtesting - which checks both values against the same candle's high - and if either of the 2 matches, it'll sell at that point - as it would during live / dry).

---

A similar problem appears with trailing stoploss if you consider all options and combinations freqtrade offers at the moment, which includes (from memory - may be missing one):
* static stoploss - at X% of entry
* trailing all the time
* trailing only after it's positive
* trail only when positive with a different value 
* trail always, but use different value when positive

The big advantage of using `stoploss` as a callback is that you could do this dynamically - which i think you'd loose (or at least complicate a lot for users) if it's assigned to a column.

Now the stoploss callback is something to discuss for sure - both ways have benefits and drawbacks:
as value:
* can be easily changed intra-candle to "whatever" suits current price action
* usually easier for users - as you can simply "return" a value, instead of assign it to the dataframe
* easily use different stoplosses depending on the current trade situation (my assumption was to call this with the trade object, so the user can decide to return a different value based on current profit / loss state - which would close #1193 )

as column: 
* easier to handle during backtesting
* less flexibility for intra-candle changes
* speedup for vectorization 

Now i wouldn't want to base a callback decision on the fact "can it be vectorized" or not - but based on the fact "is it easily understandable for the user / does it offer the flexibility users want". 
The main reason for this is that the vectorized method is only a draft - is not proven to work / align - so it could very well be that the vectorized backtest implementation will never be finished.
