### ISSUE TITLE
Infinite loop in "freqtrade.exceptions.ExchangeError: Insufficient funds 

### ISSUE THREAD

**Issue by MT00x** [freqtrade/freqtrade#3638]
### **Describe your environment**
Operating system: Centos 7
Python Version: 3.6.8 (python -V)
CCXT version: ccxt==ccxt==1.31.37
Freqtrade Version: freqtrade develop-7e98003

### **Describe the problem:**
The bot stop placing order, so i checked in console and was continue printing "freqtrade.exceptions.ExchangeError: Insufficient funds "
I went at the begging of the error and just before there was a warning say 
`"WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"
`
After 4 retry it started to give the exception "freqtrade.exceptions.ExchangeError: Insufficient funds.... " forever.

So I checked the order directly in Binance and the order was correctly placed.
From that moment the bot was in "loop" trying to place a new stoploss_limit_order for ever.
Deleting the order from Binance resolved the issue and the bot exit from loop.

### **Observed Results:**

- What happened? 
The bot always print the same exception in console, no trade is placed.

- What did you expect to happen? 
A warning via telegram message would be helpful in this case

### **Relevant code exceptions or logs**

[PasteBin complete logs here](https://pastebin.com/n3wvPAna)

```
`2020-07-24 20:55:36,584 - freqtrade.persistence - INFO - Updating trade (id=16) ...

2020-07-24 20:55:36,584 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=16, pair=SXP/BTC, amount=4.00000000, open_rate=0.00019642, open_since=2020-07-24 18:55:18).

2020-07-24 20:55:39,617 - freqtrade.exchange.binance - INFO - stoploss limit order added for SXP/BTC. stop price: 0.00017678. limit: 0.00017502

2020-07-24 20:55:45,222 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"

2020-07-24 20:55:45,222 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 3 times

2020-07-24 20:55:46,533 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"

2020-07-24 20:55:46,533 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 2 times

2020-07-24 20:55:48,817 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"

2020-07-24 20:55:48,817 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 1 times

2020-07-24 20:55:54,083 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"

2020-07-24 20:55:54,083 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 0 times

2020-07-24 20:56:04,363 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}"

2020-07-24 20:56:04,364 - freqtrade.exchange.common - WARNING - Giving up retrying: fetch_order()

2020-07-24 20:56:04,364 - freqtrade.freqtradebot - WARNING - Unable to fetch stoploss order: Order not found (id: 7662377). Message: binance {"code":-2013,"msg":"Order does not exist."}

2020-07-24 20:56:05,104 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):

  File "/projects/freqtrade/.env/lib64/python3.6/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()

  File "/projects/freqtrade/.env/lib64/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order
 `
```

Thank you

**Comment by xmatthias** [comment]
we've had this error in the past. it's supposed to be fixed since #3531 .

for a detailed explanation of what happens, please read this comment: https://github.com/freqtrade/freqtrade/issues/3499#issuecomment-650801197
short summary: it's binance's fault, as they receive the order, but fetch_order doesn't return that order for a few seconds.

Now the logs above indicate that binance does not return the order for 19 seconds (which i already find extreme, all previously reported cases (to binance support / ccxt) - the order was not available for a maximum of 5-10 seconds).

Please run the below to verify that the order-id indicated in the logs is the correct one and that the order-id is now findable.

```
import ccxt
ct = ccxt.binance({'apiKey': '<yourAPIKey>', 'secret': '<your_secret'})
order = ct.fetch_order('7662377', 'SXP/BTC')
print(order)
```

---

If the order is available now, i'm not sure how we are supposed to fix this. We can't increase the timeout indefinitely - if we place the order and binance and binance won't return the order for the next 20 seconds - where is the limit at which we decide "binance this order wasn't placed correctly" ... ?

**Comment by MT00x** [comment]
Ok, understand. Unfortunately I don't have this order anymore.
If it will happen again I'll make the verification you suggest.
Anyway in your opinion, it would not be useful to have these errors reported via Telegram?

Thank you

**Comment by xmatthias** [comment]
even if you don't have the order anymore - it should exist in the API, so the above should show the order details.

**Comment by MT00x** [comment]
Ah, ok.. that's the result
```
>>> ct = ccxt.binance({'apiKey': 'MmNoFDZo5LdQC8J7YggaLgaK3bt22riAk7SCQ7CbRRBJGXIinKn54vmjTW56WqIC', 'secret': '77Ui1KYyhdllIKci0Dlc70LBtJjB9EkAJWJSbFEnBKVlMJtd7wi9egmqDEiOd576'})
>>> order = ct.fetch_order('7662377', 'SXP/BTC')
>>> print(order)
{'info': {'symbol': 'SXPBTC', 'orderId': 7662377, 'orderListId': -1, 'clientOrderId': 'Kpua3nW74nyEE4DDA0mWGI', 'price': '0.00017502', 'origQty': '4.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'CANCELED', 'timeInForce': 'GTC', 'type': 'STOP_LOSS_LIMIT', 'side': 'SELL', 'stopPrice': '0.00017678', 'icebergQty': '0.00000000', 'time': 1595616941898, 'updateTime': 1595619342275, 'isWorking': False, 'origQuoteOrderQty': '0.00000000'}, 'id': '7662377', 'clientOrderId': 'Kpua3nW74nyEE4DDA0mWGI', 'timestamp': 1595616941898, 'datetime': '2020-07-24T18:55:41.898Z', 'lastTradeTimestamp': None, 'symbol': 'SXP/BTC', 'type': 'stop_loss_limit', 'side': 'sell', 'price': 0.00017502, 'amount': 4.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 4.0, 'status': 'canceled', 'fee': None, 'trades': None}

```

**Comment by xmatthias** [comment]
Well in the end, this confirms my suspicion.

The order was placed at 2020-07-24 18:55:41.898Z (this is UTC Time - should correspond to 20:55:41 in your timezone).
Now freqtrade (logs are in your timezone) asks for the order - first time at 2020-07-24 20:55:45 (4s after the order was placed.

It's then waiting and retrying until 2020-07-24 20:56:04 - which is 23s after the order was placed.

The problem is - this is a "disappeared" order (unfindable via the API).
From freqtrade's point of view, this can have multiple causes
* order placement failed
* exchange had a "hickup" and didn't place the order
* exchange had a "hickup" and returned the wrong order-id
* user deleted the order from the exchange
* order is not stored correctly yet   <--

Now the last is what is happening here.
To me, waiting 23 seconds for the exchange to correctly return an order is sufficient - waiting any longer will cause interruptions to the bot if any of the other reasons happen - as the bot might end up waiting "forever" on this order.

So we've seen a delay of at least 23seconds.

---

> If the order is successfully placed, and the order number is returned. But this order information cannot be found by GET /api/v3/order.
> 
> Binance’s ordering process is hitting the matching engine first, and then the order information will be sent to downstream channels, including the persistence layer, Websocket server, etc. The biggest advantage of this design is that the entire trading system is very scalable and will not be limited by common restrictions, like IO, etc.
> 
>This endpoint GET /api/v3/order takes data from the persistence layer . According to the above information, there is a time gap from the matching engine to the final persistence. This time difference may be over 10 seconds at the moment when the market price fluctuates greatly. Our system is constantly optimised to keep the delay within 1 second.

[source - binance forums](https://dev.binance.vision/t/why-see-this-error-message-order-does-not-exist/46)
The user "dino" seems to be with afiliated with the binance exchange (he answers most posts with "we have ..."), explaining that this delay may be over 10s. (however, 23s is twice as much).
however, it also claims that they try to optimize their systems to keep this delay within 1s.

With that info - i do feel that 23s we're currently waiting is sufficient.
For sure, we can add another few seconds - but what if 1m is not enough? how long should we really wait for the order to show up correctly via the exchange's API?

**Comment by MT00x** [comment]
Thank Young @xmatthias , this is clear and obviously FT can not handle this situation, it is Binance issue/too high delay .
What do you think about notify a "insufficient fund" via Telegram?

**Comment by Prossi79** [comment]
@xmatthias thanks again for the good explanation ... what I do not understand - _"This endpoint GET /api/v3/order takes data from the persistence layer . According to the above information, there is a time gap from the matching engine to the final persistence"_ ... after this delay of x sec (10 or 20plus) binance got the order in the system, is that correct? 

why is this "disappeared" order (unfindable via the API)?

**Comment by xmatthias** [comment]
@Prossi79 it's explained binance forum link i posted above - it's a "implementation detail" of the binance API (to me it's a bug - but who am i to critizise)...

**Comment by Prossi79** [comment]
@xmatthias you are one of the core devs of one of the best open source crypto trading bots, thats who you are. 

Thus I think you are the good one to clarify this API "bug" or implementation detail with them. Binance must have a some contact person for that right?

**Comment by xmatthias** [comment]
#3649 will add another layer of backoff - so it'll wait another few (17) seconds.

This will have freqtrade wait for 1 + 2 + 5 + 10 + 17 = 35 seconds.
I think if binance isn't showing an order after 35 seconds (which i already find extreme) - then they got a real severe problem in their API...

**Comment by devilsinthedetail** [comment]
35 seconds is a lot. I wonder if Binance is starting to slow down automatic traders.
Just to clarify, this will only wait a maximum of 35 seconds if binance does not return the trade, so the average wait time will be much lower, right?

**Comment by xmatthias** [comment]
the average wait time will be 0 (assuming binance "finds" the order immediately) - as then we're never getting to the "retry" part.

The reason is [this](https://dev.binance.vision/t/why-see-this-error-message-order-does-not-exist/46) - and i've found a post in a different language from 5 days ago - where they also confirm that in peak times, the "delay" is 10s ... but i've seen 2 or 3 logs now where waiting 20+ seconds was not enough.
