### ISSUE TITLE
Binance - Paying with BNB Fees question

### ISSUE THREAD

**Issue by devilsinthedetail** [freqtrade/freqtrade#3648]
In the documentation it is stated that :"Accounts having BNB accounts use this to pay for fees". Is this hard-coded or is this using the setting I set on Binance? 

Another question I have is, does it make sense to use BNB fees? We pay maker and taker fees so with BNB this would be 0.15%, while without BNB it will be 0.2%. Now the BNB coins your holding will slowly be reduced when using BNB as fees, so if BNB goes to 40, you effectively paid 0.3% in fees. If this is correct it might make sense to just pay without BNB as the price will likely increase. Is this a correct assumption or is there some mistake I made?

**Comment by xmatthias** [comment]
BNB fees are a binance concept.
It's a setting in your account page - which allows you to disable them eventually (it's enabled by default, but applies only if you actually own BNB).

Now the fee reduction does make sense in my eyes, as that makes a trade profitable at an earlier stage.

Note that freqtrade does include fees in profit calculations - and if the exchange uses BNB fees, the calculation is also done with the reduced fee % (it's also assuming that if you bought with BNB fees, selling will also use the reduced BNB fee rate - which can be wrong in theory - but it's most likely not the case).


Yes, BNB fees will be consumed and slowly go down - but if you consider your total capital (BNB + BTC + USDT + ...) - then it's no different than paying with anything else (just at a reduced rate).
The difference when not using BNB is the 0.05% in fees you pay more - and that it's USDT that's slowly going down (not considering the profits your bot hopefully makes).

**Comment by xmatthias** [comment]
I'll assume this question as answered.

Feel free to reopen if it's still not clear.

**Comment by devilsinthedetail** [comment]
I would like to reopen this, in light of the current run of BNB. I think if BNB is very volatile, the bot would need to rebuy some BNB based on fees sold, otherwise you can end up with losses in case you buy back your BNB manually (and potentially buying at the peak). 

Would it be possible to have it automate a BNB buy (lets say once a day)?

**Comment by xmatthias** [comment]
I don't think that's a good idea (and it can cost you in theory), first of all because it's binance-specific, and then because it can cost you if you buy BNB at the peak - doing this manually will be better, as you can pick the right time to buy (not at a peak, ideally).

Alternatively, you can use a bot with BNB as stake-currency - not give that bot the full balance - and have it accumulate BNB in the process.

In general (if you don't wanna do that), best make sure you have enough BNB  available so the but can work.

However, also "non-BNB" fees are handled correctly by freqtrade - it's just costing you the "regular" fee price - not the BNB reduced price.
