### ISSUE TITLE
Hyperopt usage

### ISSUE THREAD

**Issue by guizmoau** [freqtrade/freqtrade#3655]
Just a stupid question.

The output result of hyperopt need to be interpreted manually and will not apply to the strategy used otherwise ?

**Comment by xmatthias** [comment]
You'll need to transfer the hyperopt results to your strategy as documented [in the documentation](https://www.freqtrade.io/en/latest/hyperopt/#understand-the-hyperopt-result).

**Comment by guizmoau** [comment]
And that transfer cannot be automated ?

**Comment by xmatthias** [comment]
there's a few reasons it's not possible at the moment.

* it would remove the incentive for users to actually understand their strategy ... which can help identify problems, or tune it better
* No one yet found it worthwhile investing the time - as transferring the parameters can be done in a short amount of time.

For me, the first point is the reason that i'll most likely never actively work on this - and that i'm not a big fan of efforts that try to facilitate this.

We'd then have tons of users without any trading understanding (nor IT background).
This creates a huge support burden, which means we will spend most of the time answering questions that could be found in the documentation - or which are "my hyperopt shows i'm profitable - but live is not" - which are simply a waste of time for people donating their free time to help with this project.

---

For sure - it CAN be automated - so feel free to implement and make a Pull Request for this if you think it's important.

Myself, i find it a waste of time, as it's very difficult to implement a "hyperopt to strategy" conversation in a way that covers all possibilities users could be using in their hyperopt file (we do provide samples, but no one forces you to strictly follow these - so there's millions of other posibilities which we can't even start to fully test).

If the conversation is not working (maybe because you used a generator with f-string naming), it would be again up to the people donating their free time to try and find a fix.


Also, for a final strategy, you'd want to remove all indicators the final strategy is not using, to avoid calculating 100 indicators when the strategy is only using 5 of them.

**Comment by guizmoau** [comment]
Totally understood and agree with your points 👍
