### ISSUE TITLE
Fiat USD trading question

### ISSUE THREAD

**Issue by andykov** [freqtrade/freqtrade#3657]
Hello. Tell me, please. I trade Pairs.
If the `stake_currency` option specifies USD, then in `stake_amount` 0.2 is it 20% or $ 0.2?

```
"stake_currency": "USD",
"stake_amount": 0.2,
"fiat_display_currency": "USD",
"pair_whitelist": [
            "BTC/USD",
            "ETH/USD"
        ]
```

I am confused by the **Tot Profit USD** column. Are the values shown in the screenshot in dollars or a percentage?

![Терминал_2020-08-04 18-00-54@2x](https://user-images.githubusercontent.com/5297016/89309754-7c6c9100-d67c-11ea-904d-ff0447a5e467.png)

**Comment by Theagainmen** [comment]
stake_amount is the absolute amount of stake you want to put per trade. So for USDT (don't know what exchange you're on, but didn't know USD pairs existed) you could have a stake_amount of 100 USDT per trade. For BTC as your stake currency, you would have something like 0.01 BTC there.

The tot profit USD shows the total profit it made for that pair in USD. So it made 0.0127 USD profit for BTC/USD, which is not a lot, but that's because your stake amount is set to 0.2 USD, which is also not a lot. The tot profit % tells you that compared to your stake amount it's a profit of 1.27%.

**Comment by andykov** [comment]
Thanks for the detailed answer.
