### ISSUE TITLE
Don't repost orders if they are the same

### ISSUE THREAD

**Issue by joshuar87** [freqtrade/freqtrade#3658]
Hi there,

Would it be possible to check if the exact same order is already on the exchange before cancelling it and reposting it? I.e. if an order does not get filled and therefore cancelled because of timeout and then reissued at the exact same amount and price. I spoke to Binance support and they say their limit orders are 
filled according to a price/time priority. Which means if you have an order at the same price as someone else then whomever made the order first gets filled. So not cancelling an order that would be the same betters your chance of a fill which is great for low volume coins. Another advantage is less Telegram notification spam. 

I am happy to look into this if you wish?

**Comment by xmatthias** [comment]
Well your best bet is to increase your unfilled_timeout - so the order is not cancelled in the first place.

There's 2 reasons why an order would be placed again:
* your timeout is < timeframe (10m timeout, 15m candles)
* your strategy has a "sticking signal" problem - this can be mitigated by using "crossed" comparisons, instead of > < comparisons.

When freqtrade cancels an order, it assumes it's not going to be placed again - and if it is, then the price will be recalculated according to the new market situation.

Any reasonable timeout will most likely not have the order placed at the same value, but at a different value (you'd assume that price after timeout is EXACTLY the same as it was 10 minutes ago).

So to make an example with real numbers:

* Order is placed at 10:00 with a price of 100 USDT.
* order is cancelled at 10:10:00
* order is placed again at 10:10:01. <-- details below

Since the price is recalculated again at 10:10:01 - to get the same price of 100 USDT - the orderbook would have to look like almost exactly the same - which is very very unlikely.

Yes, prices can return to the same value again - but i see this as a theoretical problem - as timing would need to be precise per second - otherwise the order will be placed again at 100.01 USDT - not at exactly 100 USDT - which is a different price.

It's theoretically possible on a very low volume pair - but even there, the orderbook will fluctuate - even if there are no trades executed as there are no buyers / sellers - so the order will also there be placed at a different value.

**Comment by xmatthias** [comment]
I'll assume this as answered - as reposting the same order is almost impossible in practice (as explained above).

Feel free to comment below / reopen if there's still something to add to this issue.
