### ISSUE TITLE
Make the back-test as similar to normal run as possible

### ISSUE THREAD

**Issue by baont** [freqtrade/freqtrade#3672]
## Describe the enhancement

When i run tasks related to back-testing operations (back-test, plot back-test result, export back-test result..), i saw that the strategy's analytic functions (populate_indicators, populate_sell_trend, populate_buy_trend) only run once with all the test data, while in normal run mode, these functions run every 5 seconds with the latest data. Why don't we make the back-testing as close to the normal run as possible, like sliding a window thought the back-test data and run these functions with every window?

**Comment by xmatthias** [comment]
the reason is quite simple - this would make backtesting dead slow.
Currently, we analyze the data one time - so we calculate all indicators exactly once (ideally in a vectorized way - to make it performant - but this is really up to the strategy).

So lets assume we run one vectorized indicator across the whole dataset (say - 20.000 Datapoints - which is roughly 6 months of 15m data).

Assuming the analysis runs once (as it is at the moment) - it'll take one second (1s) (excluding data-loading and the rest of backtesting - which is what really takes most of the the time in backtesting).

Now what you're proposing is to chunk this data into 500 datasets (so it's 20.000 / 500 = 40) - so we're running the analysis (that took 1s previously) 40 times. 
This will not take 40 seconds, but close to it (say 35 secons)- as most vectorized functions are written in c - so we need to pass the data 40 times to this function.


While this may sound acceptable - it becomes a long wait soon once you don't run backtesting for one pair, but for 20 or 50 pairs (which is common in backtesting).

Also - backtesting is used during hyperopt, so this would make hyperopt impossible - as hyperopt is basically running backtesting (excluding indicator analysis) for thousands of times (or whatever is specified as `--epoch`).

----

I also don't see how this would better align backtesting and dry-runs - as it can still not simulate unfilled orders, or slippage.

The only benefit it would have is to capture people's errors (using future data, using too long historic data) - but these points are documented - so in my opinion, they neither justify the development effort, nor the performance penalty this would incur.

**Comment by baont** [comment]
thank you for a very quick and detail explaination

**Comment by xmatthias** [comment]
I've actually even had a mistake above - the total count of chunks would not be 40 - but `20.000 - 500 = 19500` (as it must be a rolling window stepping forward one step at a time (always only looking at the last candle of this iteration.

I've also fixed this typo above - but if interested, you can see the previous version by clicking on the "edited" button above.

**Comment by nviitala** [comment]
What if there would be another backtesting script, which would be more accurate? People could choose which one to use per situation.

Sometimes the backtesting results differ too much from the real results. In some cases I've got a lot of profit from the timespan when backtesting has shown loss and vice-versa.

**Comment by xmatthias** [comment]
@nviitala Please don't revive issues that are a year old.

we now have `--timeframe-detail` for this - where you can backtest your exits with a timeframe as low as 1m.
It'll obviously be slow - but it's your choice to have it slow.
