### ISSUE TITLE
How much data do I need for hyperopt parameter to work correctly?

### ISSUE THREAD

**Issue by PythonCommander** [freqtrade/freqtrade#3673]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-e079d36f (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, I have a few questions about using hyper-opt on Freqtrade.

1. When using hyper-opt on 15 minute chart, how much data should I need to produce excellent results? 

2. When using hyper-opt, should my config file only contain one cryptocurrency during optimization or is it fine if multiple cryptocurrencies are listed in config file during optimization?

3. If multiple cryptocurrencies are allowed during hyper-opt, could this skew the accuracy of the strategy working since each cryptocurrency trades differently or would my strategy just become more universal?

The reason I ask these questions is because I have used Sharpe Ratio hyper-opt on 30 days of historical data for 20 cryptocurrencies, and ran 10,000 Epochs to optimize my 15 minute strategy. The hyper-opt results 700 trades within one month with 600% profit. Which sounds very good but when I do the exact same thing with 3 years of historical data for those 20 cryptocurrencies the hyper-opt only results an average of about 30 trades with less profit(Avg Total Profit: 50%).

**Comment by xmatthias** [comment]
there's no clear answer to this - obviously, the more data, the "more universal" the strategy.
If that's good or bad, don't know. You should however try and cover different market-cycles (bear / bull / consolidation) in your data ... so the strategy has seen "most" things at least once.

On the other hand, too much data may taint it towards rare events that happened 3 years ago - but are unrealistic to happen again ... so there's no "clear" answer to this.


You can (and to me, should) use multiple pairs - otherwise the strategy will be VERY optimized for one pair - but even if this pair trades similarly - it'll not be identical - so it might not be a good fit for anything in the end - resulting in bad performance on unseen data.

Running hyperopt multiple times will not produce the same strategy (even if you use the same data) - as it's a Bayesian search - which will descent into a local minima - so running it for 10000 epochs may (or may not) be the best thing to do.

Generally, hyperopt results should always be evaluated manually and with a grain of scepticism - some results tend to generate very few, highly profitable trades (these strategies are rather high risk - as you'll leave the bot on for a year to get 30 trades).
