### ISSUE TITLE
Edge module doesn't use config's minimal_roi

### ISSUE THREAD

**Issue by pnmartinez** [freqtrade/freqtrade#3721]
## Describe your environment

  * Operating system: Ubuntu 18.04 LTS
  * Python Version: 3.7
  * CCXT version: 1.33.23
  * Freqtrade Version: freqtrade develop-085839c
  
## Your question

Hello. Tinkering with `edge_positioning.py` now.

I've checked that  **changing the `minimal_roi` in the `config` yields the same edge results**, even though the startup logs tell me that `minimal_roi` is overriding the strategy (see below).

```
[...]
2020-08-26 11:58:47,504 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'minimal_roi' with value in config file: {'0': 0.01} # this is a mock dictionary
```

I cannot see how this can be possible: _different ROIs should lead to different sell signals, and these should lead to different performances and edge results._

My theory is that the **edge module does not effectively load config's sell conditions**, as it calls `advise_sell()` which in turn calls strategies' `populate_sell_trend()`.

I would like confirmation on this last point.

**Comment by xmatthias** [comment]
I would recommend to carefully read the [edge documentation](https://www.freqtrade.io/en/latest/edge/)

> Edge does not consider anything other than its own buy/sell/stoploss signals. It ignores the stoploss, trailing stoploss, and ROI settings in the strategy configuration file. Therefore, it is important to understand that Edge can improve the performance of some trading strategies but decrease the performance of others.

**Comment by pnmartinez** [comment]
I am sorry @xmatthias , but I cannot track that down in the code: I don't know what "its own buy/sell/stoploss signals" means. For what I can understand, `interface.py` mounts the sell methods from the strategy on `edge_positioning.py`

If I am not mistaken, the flow goes:
```
edge_positioning.py 
    calculate(  
        interface.advice_sell( ) 
    )
```
In `interface.py`:
```
interface.py
    advice_sell( 
        **@abstractmethod**
        populate_sell( ) 
     )
```

If I am not mistaken, `populate_sell()`, being an `abstractmethod` is instantiated from the strategy on that same `interface.py`.

**Comment by xmatthias** [comment]
There is no need to track this in the code (why would you?)

It's clearly documented that edge does NOT respect ROI, nor trailing stoploss.

The only thing that matters for edge is sell signal and the initial stoploss.

**Comment by pnmartinez** [comment]
Hello again, @xmatthias .

There's no need to be rude either, but everyone has its own life and motives, so let's skip that part and keep it civil and technical. We really appreciate the continuous support you offer, but I'll make sure to emphasize that more in the future.

Just to be sure: **edge uses the buy/sell signals set on the strategy file**, as there's no other file in the codebase that contains those. Is this correct?

Thanks a lot in advance.

**Comment by xmatthias** [comment]
My intend was not to be rude - but to me, the answer to this question is clearly stated in the documentation - and i will not give extensive explanations about things where it's obvious that the documentation was not consulted first.

---

yes, but it uses ONLY the buy and sell signals set explicitly (in the buy / sell column of  the dataframe) and the static stoploss.

While ROI and trailing stoploss might also be seen as sell signals - these are simply ignored by edge (as stated in the documentation). 
It's terminology, really - for freqtrade, a "sell signal" is whenever  the sell column in the dataframe is 1 (and you're in a trade, obviously).
---


Edge is implemented in a completely vectorized way. 
While this brings performance benefits, tracking ROI and trailing stoploss would not work very well this way (and the original author was very explicit to intentially not implement either of these methods).

Due to this architectural difference, edge is not supporting all other features (roi, trailing stop, trailing stop positive, ...) freqtrade offers - so your strategy must have a good sell-signal as well to work well with edge enabled.
If it doesn't (and you rely on ROI / trailing stoploss for the most part) - then edge is most likely not something for you / your strategy.


Personally, i find it very hard to find a good buy signal - but a LOT harder to then find a good sell signal ... so most of my strategies would not be suitable for edge.

**Comment by pnmartinez** [comment]
Same feeling here, @xmatthias : the difficult ones are actually the sell signals.

However, I was interested in how edge works, because running it independently can bring some general insights (e. g.: it is a good way to do a sensibility study of the dependence between `stoploss` values and expectancy/returns).
----
Regarding the "just read the docs" topic: honest to god I always do a search in issues and the docs - but the project has now lots of literature! Sometimes it's a needle in a haystack situation.

And by the way: I see that you are the one which usually responds to all issues, which can be heavy in the long run. Are you the only active core developer now, by any chance?
