### ISSUE TITLE
Telegram Performance command gives the old trades performance.

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade#3732]
system: LINUX
PYTHON VERSION  : PYTHON 3.6.9
freqtrade Version : freqtrade develop-ce15c551

**Comment by kiandp** [comment]
Hi
When I run Performance command on TELEGRAM I receive the performance for my previous strategy and my previous trades, however, I have terminated all my previous trades.
Now I am running a new strategy with different pairs but when I run the "Performance" command I don't receive the performance for my new trades I still get the old ones with old pairs!
Before this issue arises, I ran 2  different strategies in one telegram bot & that's should be the reason why Telegram is behaving like this & because I left some trades open and then canceled the bot process and changed the strategy and also pairs so telegram couldn't sell the pairs. But I re-ran the same strategy and closed those trades through the bot with "FORCESELL ALL" command.
Is there any command exists to reset or delete all the process and clear its memory from previous strategies?
Please help me to fix this issue?
Thanks in advance for your time and knowledge.

**Comment by xmatthias** [comment]
When not specified otherwise, freqtrade will use the same database.
Since you did not delete / move / specify a different database, freqtrade will continue to use the same database for every new start.

You can specify a different database by using `--db-url sqlite:///trades_coolstrat.sqlite`.
You can also move the existing database (search for `.sqlite` files in your folder and rename / remove this).

**Comment by kiandp** [comment]
Thanks again for your fast response.
I fixed the issue with your help .
