### ISSUE TITLE
delisted pair results in 100% position loss

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#3769]
My bot just executed, a sale with a loss of -100%, I mean it sold at 0 btc.

I do not know what this was due to, obviously in my stop loss that is not indicated, it is -35%.

It so happens that INS / BTC is going to be delisted just today from Binance 09/11/2020

It could have been this problem. Is there some way the Bot can alert you to this kind of thing.

Luckily I was in dry-mode.

```
Binance: Selling INS/BTC
Amount: 1675.04187605
Open Rate: 0.00000597
Current Rate: 0.00000000
Close Rate: 0.00000000
Sell Reason: stop_loss
Duration: 5 days, 10:06:38 (7806.6 min)
Profit: -100.00% (loss: -0.01001000 BTC / -0.010 BTC)
```

**Comment by xmatthias** [comment]
well yes - if the coin is delisted, then it will not have a price (which might be even reported by the exchange as 0.0 - which it does).

The binance API  does not provide a "will be delisted on" attribute (as far as i could find), so the only way to know which coins will be delisted is by following the binance anouncements and blacklisting (and/or removing from the whitelist) such coins.
Feel free to let me know if you discover how the API is returning this - so far i did not find this information outside of the anouncement pages.
The [binance dev page](https://dev.binance.vision/t/can-the-api-team-add-a-new-symbol-status-like-will-be-delisted-soon-if-symbol-is-known-to-be-delisted-in-future/425) has this as a feature request - however i don't think it's been implemented yet.


Technically, the bot did what it's supposed to - since you're unable to sell this pair now - it is technically a 100% loss.
A stoploss will protect you if the price of an asset falls from 100$ to 10$  (-90%) - however if the coin is just "gone" - no stoploss (neither on nor off the exchange) will protect these assets.

While unfortunate, i would not know how else the bot should react - given the information available.

**Comment by jblestang** [comment]
Can we simply ignore a price value of 0?

**Comment by xmatthias** [comment]
why? 
There is no more pair trading with INS on binance (and once a pair is delisted, i don't think a pair will come back) - so you're not able to get these funds back anyway - so technically - the bot is correct, this is a 100% loss.

**Comment by jblestang** [comment]
Sometimes a swap is the reason a delisting, this was the case for ERD , meaning the exchange will convert your ERD to the other asset after delisting unless you sold it.

**Comment by xmatthias** [comment]
Unless you find a way (via the exchange's API) to figure out this transition - i don't see how the bot should handle this automatically - as the information is simply not available (you need to read through through announcements to find this information).

In the end, the bot will not sell the asset at a price of 0.0 in live mode anyway - as the market is already closed at that point.

**Comment by jblestang** [comment]
Hopefully yes you are right, binance will not allow the trade to take place.

**Comment by xmatthias** [comment]
Well, that's not even a "hopefull" - it's a fact.
the pair is gone - trading is halted - you can't even find the chart on binance anymore since ~1 hour ago (it was available when i first looked at this issue).

That will mean - binance wil allow no more buys (nor sells) to take place on this market.

**Comment by xmatthias** [comment]
Going to close this, as unfortunately, echanges don't provide this information via API, but only via "anouncements".
There's 2 possibilities in case of a delisted coin - either it's a total loss (you can't sell it against anything anymore) - in which case showing it as -100% is correct - or it's been replaced with a new coin (in which case, you should be able to update the database row with the new pair-name).

Either way, it's not something freqtrade can do automatically (because the information is not available in a machine-readable format) ... so i don't think freqtrade can do anything automatic at this point in time (hopefully, exchanges will provide this information in the future...).

**Comment by JhorAVi** [comment]
![image](https://user-images.githubusercontent.com/34365455/160754255-cb964370-ea58-47d8-9ae2-4885b2aa3392.png)
It's March 30, 2022 and I have this same problem dry running freqtrade develop on Binance 
The bot is holding ANY/USDT at -10% for few days but I almost had heart attack when freqtrade suddenly tries to sell it at -100% vaporizing all my profits! I wish freqtrade to provide none scary output.

**Comment by moinonin** [comment]
One possibility could be a public/private read/writable API where the community could update delisted assets so that the rest of the community could use it to programmatically blacklist the assets from their bots once announced. I have also experienced this problem with BCD and it sucked

**Comment by JhorAVi** [comment]
> One possibility could be a public/private read/writable API where the community could update delisted assets so that the rest of the community could use it to programmatically blacklist the assets from their bots once announced. I have also experienced this problem with BCD and it sucked

I see a repository about that matter here.
[https://github.com/leonardvdj/delist_util](url)
I wish such functionality is built-in with freqtrade.

**Comment by xmatthias** [comment]
we can for sure implement such functionality _if it exists as an api_ (best across exchanges).

We'll however not resort to parsing news pages (also not through other libraries) - as this will be too faulty and can lead to missunderstandings / missinterpretations (like - BTC/USDT was delisted)

As such, the best thing will be to push your exchange for such an endpoint.

**Comment by moinonin** [comment]
> we can for sure implement such functionality _if it exists as an api_ (best across exchanges).
> 
> We'll however not resort to parsing news pages (also not through other libraries) - as this will be too faulty and can lead to missunderstandings / missinterpretations (like - BTC/USDT was delisted)
> 
> As such, the best thing will be to push your exchange for such an endpoint.

Indeed pushing the exchange is a good option. I wrote as an improvement during the recent survey (for binance). Hopefully they will see

**Comment by xmatthias** [comment]
> Indeed pushing the exchange is a good option. I wrote as an improvement during the recent survey (for binance). Hopefully they will see

Ideally, they'd provide it via markets - as a "will be disabled on" option - so we know it in advance, and can handle the  trade gracefully (closing it before it is gone - or even prevent entering if it's delisted within X days).
