### ISSUE TITLE
Accessing bid-ask prices in strategy file

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade#3773]
I was wondering whether there is a controlled way of accessing bid-ask prices within a strategy file, in order to implement a strategy that uses bid-ask spreads?
Apologies, but I couldn't find anything in the docs.
Thanks

**Comment by xmatthias** [comment]
You can access these prices using the dataprovider [as documented here](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-dataprovider).

You can use either orderbook or ticker ... however both make an active call to the exchange, so make sure you have rateLimit active - otherwise you might run into blocks very soon.

**Comment by zlac116** [comment]
Thanks @xmatthias. Apologies, I missed this part of the docs.
