### ISSUE TITLE
Dry run vs real run inconsistency

### ISSUE THREAD

**Issue by holda29** [freqtrade/freqtrade#3902]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: 2.7.17
  * CCXT version: 1.33.18
  * Freqtrade Version: develop-8e8f328b
  
## Why the dry run does strongly different results?

I am running Freqtrade with customised strategy, but I am unable to get any positive result despite the fact, the dry run does excellent outcomes.
I am running the exact configuration, with only difference in dry_run: true,  dry_run_wallet amount and missing API key.

But for the last week it looks like this:
dry run: + 262 USDT
real run: -94 USDT

my config is bellow:

Thanks!
```
{
    "max_open_trades": 2,
    "stake_currency": "USDT",
    "stake_amount": 750,
    "tradable_balance_ratio": 0.97,
    "fiat_display_currency": "CZK",
    "amount_reserve_percent": 0.05,
    "amend_last_stake_amount": true,
    "last_stake_amount_min_ratio": 0.5,
    "dry_run": false,
    "cancel_open_orders_on_exit": true,
    "trailing_stop": true,
    "trailing_stop_positive": 0.01,
    "trailing_stop_positive_offset": 0.011,
    "trailing_only_offset_is_reached": true,
    "stoploss": -0.05,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 20
    },
    "bid_strategy": {
        "price_side": "bid",
        "use_order_book": false,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "order_types": {
        "buy": "limit",
        "sell": "market",
        "emergencysell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
            },
    "order_time_in_force": {
        "buy": "gtc",
        "sell": "gtc"
    },
    "pairlists": [
        {
        "method": "VolumePairList",
        "number_assets": 70,
        "sort_key": "quoteVolume",
    },
    {"method": "AgeFilter", "min_days_listed": 10},
    {"method": "PrecisionFilter"},
    {"method": "PriceFilter", "low_price_ratio": 0.01},
    {"method": "SpreadFilter", "max_spread_ratio": 0.005},
    {"method": "ShuffleFilter", "seed": 42}
    ],
    "exchange": {
        "name": "binance",
        "sandbox": false,

        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500,
                    },
        "pair_whitelist": [
        ],
        "pair_blacklist": [
"BNB/USDT",
"BTC/USDT",
"USDC/USDT",
"TUSD/USDT",
"BUSD/USDT",
"ETH/USDT",
"BCH/USDT",
"LTC/USDT"],
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
"telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },
    "db_url": "sqlite:///tradesv3.sqlite",
    "initial_state": "running",
    "forcebuy_enable": true,
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": false,
    "strategy": "CombinedBinHAndCluc2",
    "strategy_path": "user_data/strategies/",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
}

```

**Comment by xmatthias** [comment]
With the information provided (only the final sum) - there is not much to look at.

Have both bots been running for the same amount of time?
have both bots done ~the same amount of trades?
do you experience a lot of cancelled orders on the live-bot?
what's the most common sell-reason?

Always consider that dry-run assumes that trades fill "almost immediately" - which is often not the case in production.

#### most likely cause 

Based on your "pricing strategy" (bid/ask configuration) - you're posting a limit order on the buy side, and you're waiting for it to be filled for the buy side.

Your sell side is missconfigured.

You're using market orders on sell. While there is nothing wrong with it (although personally, i find it risky as you'll not know how much you move the price on "shitty" assets) - you **MUST** reverse the price side as [documented here](https://www.freqtrade.io/en/latest/configuration/#market-order-pricing) to avoid problems.

taking the example of the above configuration page:
* Your dry-run bot buys at 99 - the order fills (dry-run assumes it fills at 99 immediately). It then checks for sells - say it finds a "profitable" sell position at 101 - which would be a 2$ gain. Dry-run assumes this as filled immediately (it's a dry-run order).

* Your live bot buys at 99 - the order fills at 99 (however after a minute - as it's a limit order "waiting" for price to come down). This is not a problem - but CAN lead to slight missalignment between dry and live, as the order might be cancelled as well.

  It then checks for sells - say it finds a "profitable" sell position at 101 (based on ROI) - which would be a 2$ gain. The bot posts this order as a **market** order - so the real fill-price will be "across the spread" - basically selling at 99$ (or below - depending on the market depth). 

The problem here is - the bot thinks that while posting the order, it'll be able to sell it for 101. But with market-orders, that's not the case. Therefore, you MUST tell the bot to use the bid-side for your sells - so it's looking at 99$ - and "knows" that it's not going to profit.

**Comment by holda29** [comment]
I will try, thanks a lot Matthias!
