### ISSUE TITLE
Is it a good idea to run many pairs in a single Freqtrade instance?

### ISSUE THREAD

**Issue by c0d3r34d3r** [freqtrade/freqtrade#3906]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

So I want to trade with 32 pairs but running them all on a single instance and monitoring DEBUG logs with `-v` flag shows that it takes a long time to process them all and generate buy/sell signals. So I split them up by 8 and I am running them on 4 different Freqtrade instances all trading with the same exchange account and stake amount set to unlimited.

Can this cause any issues?

By splitting them up there is less processing to do for each iteration that generates buy/sell signals.

Overall, is splitting up pairs to different instances just for faster decision-making a valid concern and solution?

**Comment by xmatthias** [comment]
Yes, this constellation will create issues.

If you're using multiple bots against the same exchange account, you must use fixed stake-amounts - otherwise the calculation will be wrong - as using "stake_amount=unlimited" assumes that the bot can use total amount in the exchange.

On binance, you may get around this by using subaccounts - but you need to request them via support and it's not fully straightforward.

Also - when running more than 2 bots on one exchange, rate-limits can become an issue. ccxt handles ratelimiting for one instance - however the 4 instances you're running are not connected, so it's possible to go over rate-limits.
It works okish with 2 bots (depends on number of pairs + trade frequency) - but can cause problems nonetheless.
In that case, you'd need to spread it out horizontally, and run it on multiple servers to avoid rate-limiting problems.

I cannot tell you the exact limits for this - maybe for your strategy 3 or 4 bots work - you'll see this if you get "Rate limit" errors in your logs.

**Comment by c0d3r34d3r** [comment]
I handle rate limits by running them in separate VM with different public IPs, I also downsized the rate limit config in my config by factor of 4.

> If you're using multiple bots against the same exchange account, you must use fixed stake-amounts - otherwise the calculation will be wrong - as using "stake_amount=unlimited" assumes that the bot can use total amount in the exchange.

Can you elaborate on this please? What calculation will be wrong?
Assuming all bots run with "stake_amount=unlimited" then if one uses all the balance on order, the others will simply not be able to trade, no? Or can it cause other issues?

**Comment by xmatthias** [comment]
in theory this is correct - but it can still lead to failed buys assuming 2 or more bots will buy "the last slot" at the same exact time.

As said, the calculation will be different to what you'd expect.
with one bot, each position will be equally sized (up to the last one, eventually).

in your case however, positions form different bots will be scaled down with each trade that's opened.

Assume your total stake is 1000, and each bot uses 10 open trades (so one position is 100$).

* bot 1 buys 1 position for 100$
* bot 2 buys 1 position. It assumes the total available assets to be 900 - so it'll buy for 90$.
* bot 3 buys 1 position. Total "seen" available balance is now 800, so it'll buy for 80$.
* bot 1 buys a 2nd position - the assumed available balance will be 1000 - 90 - 80 - so the new position will be around 83$.

It'll make position-size quite unpredictable.

It's unknown and untested what will happen "in the end" - once your balance is exhausted.

Either way, it's an unsupported configuration combination i can only recommend to not use this way - and we will not support.

**Comment by c0d3r34d3r** [comment]
Thanks for the answer!

One more question.

> Assume your total stake is 1000, and each bot uses 10 open trades (so one position is 100$).

Do you refer to `max_open_trades` setting by 10 open trades?
So for total stake of 1000 and `max_open_trades` of 10, each position is 100.
But what about settings `max_open_trades` to `-1`? What is each position's worth then?

**Comment by xmatthias** [comment]
max_open_trades is taken into account for backtesting (unless you explicitly disable this) 

You can set either `max_open_trades` to -1 - or `stake_amount` to unlimited, but not both.
One of the 2 must be given, otherwise the bot has no way to calculate any position size, as it's either `available_balance / max_open_trades` - or `stake_amount * "until balance runs out"`.

**Comment by xmatthias** [comment]
I'm going to close this as i think this has been answered.

Feel free to comment below / reopen if it's still unclear.
