### ISSUE TITLE
Good to have currency buying and selling exact date with time

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3914]
## Describe your environment
(if applicable)

  * Operating system: Mac/Linux
  * Python Version: _____ (`python -V`): Python 3.7.7
  * CCXT version: _____ (`pip freeze | grep ccxt`): ccxt==1.37.12
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker):
freqtrade develop-84c50bf1

## Describe the enhancement

*Explain the enhancement you would like*

Currently there is no any date and time while buying any currency in telegram status message. It will be great if we have the exact buying time as well as selling time. This can help while doing back testing so that we know exactly in which point the currency buy or sell trigger got executed.

**Actual**:
Binance: Selling VIA/BTC
Amount: 76.56967841
Open Rate: 0.00001306
Current Rate: 0.00001318
Close Rate: 0.00001330
Sell Reason: trailing_stop_loss
Duration: 0:53:50 (53.8 min)
Profit: 1.64% (profit: 0.00001639 BTC / 0.224 USD)

**Expected**:
Binance: Selling VIA/BTC
Amount: 76.56967841
**Open Date: 2020-11-01 16:43:26.935246**
Open Rate: 0.00001306
Current Rate: 0.00001318
Close Rate: 0.00001330
Sell Reason: trailing_stop_loss
Duration: 0:53:50 (53.8 min)
Profit: 1.64% (profit: 0.00001639 BTC / 0.224 USD)

I can fix this issue if you would like to allow me to do so. I can try to fix it.

Thanks

**Comment by xmatthias** [comment]
I don't think that's necessary, since every telegram message has a date and time attached (see all the way to the right):

![2020-11-01-191901_492x123_scrot](https://user-images.githubusercontent.com/5024695/97810851-273e1c80-1c77-11eb-9523-5537faf7b2ee.png)

In addition to that, it'll  make the output even longer and make it more complex by adding information that's then there twice.


also, for your usecase, you'll have a very hard time to do this for 100ds of trades - so if you want to compare, it's way better to follow the [documentation](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-live-trading-results-into-a-pandas-dataframe) and load the data from the database.

**Comment by NilanjanaBala** [comment]
Ok, got it. It can be avoided. Thanks
