### ISSUE TITLE
Config.json is not found

### ISSUE THREAD

**Issue by tmeteay** [freqtrade/freqtrade#3926]
Hello everyone,
been trying to launch the bot via docker but even though there is a config.json under user-data I get the following error:

```
2020-11-04 07:51:16,151 - freqtrade.worker - INFO - Starting worker 2020.10
2020-11-04 07:51:16,151 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-11-04 07:51:16,151 - freqtrade.commands.trade_commands - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.
2020-11-04 07:51:16,151 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/configuration/load_config.py", line 49, in load_config_file
    with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
    config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
  File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
    config = deep_merge_dicts(load_config_file(path), config)
  File "/freqtrade/freqtrade/configuration/load_config.py", line 52, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.
```

how come is there a step a missed?

**Comment by xmatthias** [comment]
While you mention you're using docker - it's unclear if you're using docker-compose (simple) or plain docker (more difficult to have right - we would need the exact command you're running)

My best suspicion is that you're not mounting the user_data directory correctly - but it's a guess, as nothing more precise will be possible with the information provided.

**Comment by xmatthias** [comment]
well having docker-compose installed does not mean you use it.

What's the command you use to run the bot?

**Comment by tmeteay** [comment]
umm... I feel like the stupidest person but I just run it through docker. after following quickstart guide

**Comment by xmatthias** [comment]
as said - without knowing what command you're executing - i can't tell you why it's not working.

**Comment by tmeteay** [comment]
> as said - without knowing what command you're executing - i can't tell you why it's not working.

I just try to run the image from docker and it gives the error in the op. I don't know any other method to execute.

**Comment by xmatthias** [comment]
when running a docker image, you MUST give it some command.

Without this command, we will be unable to help you.

**Comment by tmeteay** [comment]
Ok I guess I missed some steps on https://www.freqtrade.io/en/latest/docker_quickstart/ here. I will try starting over.

**Comment by xmatthias** [comment]
also according to the quickstart, you should be running either `docker-compose up` - or `docker-compose run ...` or something else.

I've now asked several times in this issue for this command (the documentation includes multiple such commands - so how should we know at which step you are?

Please provide this command in the next comment, or i'll assume that you don't want help and i'll close this issue.

**Comment by tmeteay** [comment]
I think you should close this issue as I don't run any commands I just click the green run button on docker. But I will start over. If I encounter the same issue I will try to solve it myself.

**Comment by xmatthias** [comment]
well just clicking the green button is not in the documentation ... and i don't think it'll work (i also don't know "where" you click the green button - as i don't have a green button with docker).

**Comment by stigmaknight123** [comment]
use 

freqtrade trade -c user_data/config.json

**Comment by Pradeepkumarpalanisamy** [comment]
@tmeteay and others still undergoing with this problem, the docker container needs to be started with the following command once you entered your inputs in config.json file

docker-compose up -d

https://www.freqtrade.io/en/stable/docker_quickstart/

**Comment by roadbridgeaward** [comment]
Since the beginning of the thread above, @tmeteay is talking about "Docker Desktop" and @xmatthias is talking about "Docker Compose" and this is why @tmeteay mentioned the presence of a run *button* which exist in "Docker Desktop" but not in "Docker Compose" because "Docker Compose" is a command line tool, and this is why also @xmatthias was unable to find this same button in "Docker Compose".

All of the above is obvious for most users with some experience with Docker, but is not that obvious for brand new users.

Back to the fundamentals: the straightforward tendency of a new user when following the instructions in [ https://www.freqtrade.io/en/2020.5/docker/#docker-quick-start ] is to click the link [ https://docs.docker.com/compose/install/ ] and as of Oct 2023, this page tends to have the new user go to [ https://docs.docker.com/desktop/install/windows-install/ ] (if s/he is a Windows user) and now comes the HUGE """Docker Desktop for Windows""" button which is very attractive for the new user to click. This first sight flow causes the user at the end to have  "Docker Desktop" installed instead of "Docker Compose". "Docker Compose" is what is intended by the script of commands mentioned in [ https://www.freqtrade.io/en/2020.5/docker/#docker-quick-start ].

Fortunately, this is not a big problem, because even the user who installed "Docker Desktop" instead of the intended "Docker Compose", can still find "Docker Compose" included inside "Docker Desktop". S/he can locate the intended "Docker Compose" at pathname "C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe" (of course you might need to change the pathname based on your specific installation pathname).

**Comment by xline82** [comment]
Well said roadbridgeaward. some people just want to be an a$$ and act like everyone should use the command line. while most of the time it is the better option to use the command line. it does not mean a$$es should act like everyone should, especially while knowing what the actual issue is but refusing to acknowledge it because of their ego. this is why i hate people, because they get butt hurt because someone hurt them at some point in their life and they couldn't defend themselves so they must get online and act like an insecure tw@t to make up for it. just my 2 cents. delete the truth if you must
