### ISSUE TITLE
dont exit after 1 day for negative profit drymode

### ISSUE THREAD

**Issue by polakenfold** [freqtrade/freqtrade#3928]
freqtrade develop-66efb5cc 
fully update 1 month ago or so

hi
sorry again that i commented on closed issue,
want to exit after 1day if profit is <0
but this ROI doesnt work very well.
In backtesting trades exits after 1500 min as below but not in dry-mode.

my startegy:
minimal_roi = {
        "1500": -1,
        "1440": 0.01,
        "80": 0.02,
        "40": 0.03,
        "20": 0.04,
        "0":  0.05
    }

drymode telegram config shows:
Exchange: binance
Stake per trade: unlimited BTC
Minimum ROI: {'1440': 0.01, '80': 0.02, '40': 0.03, '20': 0.04, '0': 0.05}
Stoploss: -0.1
Timeframe: 5m
Strategy: Strategy005b

does it make any sense?

**Comment by xmatthias** [comment]
then "something" is changing / overwriting your configuration.

* Either you have minimal_roi in the strategy twice (then it would happen in backtesting too)
* a wrong strategy file is loaded
* configuration is different from backtesting and sets strategy

Best look at the log output when the bot starts - it'll tell you where ROI is coming from.

Also, make sure that the path of the strategy matches with your expectation - since we load based on strategy Class name, multiple files can contain this class - which can lead to a lot of confusion.

**Comment by polakenfold** [comment]
i managed to get it workin, but taking out #  another ROI seting,
is there a max ROI items?

**Comment by xmatthias** [comment]
no, in theory you can have 100ds of ROI items (until you're out of memory, most like - but i never tried).

best bet is that you've got a subtle syntax error "somehow" - or that the Roi is comming from "someplace else" - like configuration.
