### ISSUE TITLE
ROI not triggered when reached

### ISSUE THREAD

**Issue by rodrigo-brito** [freqtrade/freqtrade#3932]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.33.52
  * Freqtrade Version: freqtrade develop-a9e7ee81
  
## Your question

My ROI is defined as `minimal_roi: {'60': 0.02, '120': 0.015, '0': 0.01}`.
But in the backtest, I got an average profit of 3.8%, The maximum should be 2%. It is possible? What I'm doing wrong?
In the backtesting result, the ROI is triggered less than expected.

```
========================================================= SELL REASON STATS =========================================================
|        Sell Reason |   Sells |   Wins |   Draws |   Losses |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|--------------------+---------+--------+---------+----------+----------------+----------------+-------------------+----------------|
| trailing_stop_loss |    1473 |   1473 |       0 |        0 |            3.8 |        5604.01 |          5609.61  |        1120.8  |
|          stop_loss |     798 |      0 |       0 |      798 |           -1.2 |        -955.85 |          -956.802 |        -191.17 |
|                roi |       7 |      7 |       0 |        0 |            1   |           6.99 |             7     |           1.4  |
======================================================== LEFT OPEN TRADES REPORT ========================================================
```

Backtest logs. I am using, ROI, stoploss and trailing stop.
```
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.02, '120': 0.015, '0': 0.01}
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 12h
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.01
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2020-11-08 16:37:38,883 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.011
```

**Comment by xmatthias** [comment]
your ROI configuration (and also trailing stop) will not work correctly for backtesting - not with the timeframe you're using.

Backtesting buys always at the candle open, you're adjusting ROI 3 times within the candle that opens.
This may work in live - but backtesting is limited to the candle data (open, low, high, close) - but it does not know of intra-candle moves, or in what sequence these happen.

as described in the docs under [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting), stoploss happens first (so does trailing stoploss at the moment) - so ROI is not evaluated unless stoploss / trailing stoploss happens - which in backtesting, has a very high chance in this configuration.

within 12h - there's a very high chance in many pairs that a pair moves by 1% up or down, triggering trailing stop (which uses high - trailing as sell signal). 
#3929 might change this behaviour in the future - but it won't solve your root problem, as you also use a stoploss of 1%.
This stoploss is too tight for such a long timeframe (for backtesting - for the reasons above).

You should be able to test this by setting "trailing_stop=False" - you'll notice that almost all sells will become losses, since in 12h, almost all candles will swing 1% down and 1% up - so no matter how good your signal is - you didn't really do anything other than optimizing / exploiting against the assumptions backtesting makes.

**Comment by rodrigo-brito** [comment]
Hi @xmatthias thank you for the fast response.
I was suspecting this behavior, and possibly my result was false.

**Comment by rodrigo-brito** [comment]
I think it's very difficult to know how a signal is triggered first. Maybe, if a backtest can uses a small time frame, it can be reproduced with bigger accuracy. For example, to run backtesting in a daily time frame but it runs over a candle in hours or minute timeframe.

**Comment by xmatthias** [comment]
while possible in theory - it would become very slow - and make hyperopt basically unusable (hyperopt runs backtesting in the background).

also, it would become a requirement to have "lower level" data for a backtest - which is currently not the case, so you can download 12h data only, and backtesting will work perfectly fine for you.
