### ISSUE TITLE
Regarding self.lock_pair logic 

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#3948]
Hi,

Currently the `pair locks` will lock a pair based on the `timeframe` of the `config.json` file; if not specified by introducing some logic within the `populate indicators` function.

`self.lock_pair(pair, until, [reason])`, "until" is a datetime object in the future (per the documentation). 

Here's the issue.

Currently, swing trading on higher dataframes will result in that any optimization will result in having the `trailing_stop_loss` or `stoploss` be quite tight ~1-2%.
There's no way to be certain what happened within a tick of a candle that could have triggered that during the data of the OHLCV that could match or approximate a live result.

Including stoploss or trailing within the equatiaion of a hyperopt, will result in that all the "reasons" for selling be pushed towards trailing mainly, resulting in a high `Trades` count, for example, 

```|   Best |     67/100000 |     8017 |   3640    0 4377 |        0.60% | 48,328.90670512 USDT (4,828.06%) |         85.0 m |    -12.1201 |   ```

That result was using 12h on 
```Hyperopting with data from 2017-08-20 00:00:00 up to 2020-11-11 00:00:00 (1179 days)``` with 10 pairs whitelisted, meaning that at least it bought every single day for at least 8/10 pairs. (I tried some results before opening this issue, and the same scenario happened). This is due (correct me if I make the wrong assumption) that the `buy-signal` was True, but the pair was sold due to some reason that was `not` the `sell-signal`, meaning that the trade will be `locked` until the next candle arrives, but if the `buy signal` is still evaluating to `True`, then it will buy again repeating this pattern until a `sell-signal` comes.

The main flaw with this is that mainly there's 1 way to enter a trade, and that is by capturing the buy signal, but there are a few ways to exit it (stoploss, trailing and sell signal). since we cannot predict the future, and we cannot know the duration nor quality of the buy signal, it is safer to assume that every signal is optimal only "once", if there's an exit (for any reason) we should wait until the next "buy" signal comes, that is:

buy signal => enter trader => stop-loss/trailing/sell => **wait until the next buy signal, not by evaluating the next candle, but by waiting for the buy signal after the sell signal** (the reason is that we can discard the signal, rather than retrying it during the next candle).

Is there's a way to archive this behavior?

Ps. I read that `pair_locking` is not available during backtesting (hence, neither during Hyperopts), is there's a way to emulate this logic within the strategy? (ie. If there's an exit of the buy signal, wait until the "next buy signal after the sell signal")

Thanks for reading the long issue, I tried to be as descriptive as possible.

**Comment by Corfucinas** [comment]
An example on `1d`

```
1175 2020-11-05 00:00:00+00:00  14144.01  15750.00  14093.56  15590.02  143741.522673  15887.340  ...  0.872962  71.502212  73.851391    86.427414   70.104516    0     0
1176 2020-11-06 00:00:00+00:00  15590.02  15960.00  15166.00  15579.92  122618.197695  16363.165  ... -0.012720  71.422097  73.754556    86.157581   70.033438    1     0
1177 2020-11-07 00:00:00+00:00  15579.93  15753.52  14344.22  14818.30  101431.206553  15536.255  ... -0.540431  65.732832  66.941010    68.434847   64.959049    1     0
```

The last two columns are `dataframe.buy` and `dataframe.sell`, as you can see, they are two "1" in the column on `2020-11-06` and `2020-11-07`, meaning that if the trade got stop or hit a trailing, (either in profit or loss) it will retry as soon as the next candle arrives.

**Comment by xmatthias** [comment]
That's quite a confusing description, and seems to combine multiple different, unrelated questions.

manual pair locking does not apply during backtesting for now, and you can't emulate it either.
However, automated locking, which happens in dry/live modes (automatically lock until the end of the candle) will happen automatically.

---

Looking at your signal, it appears to be a "sticking" signal (or one that's always active) - i guess you can get similar - but more realistic results by using `dataframe['rsi'] < 25` (for example) - buying whenever RSI is below 25.
This signal will "stick" for a longer period of time (multiple candles). 

Yes, this will lead to rebuys in backtesting - and it will lead to the same in dry/live. The sell reason (sell-signal / something else) has nothing to do with it - as the rebuy will always happen unless you have both buy and sell signal active (which is a sign of a rather badly designed strategy - as it can't decide if it should buy or sell).

The problem becomes worse - as the assumption is usually that the signal is "strong" at the beginning, and weakens towards the end (taking the RSI example). 
So your signal is active for 3 candles, but whenever the entry happens in the 3rd candle, it's more likely to be a loss. 

Leaving sells within the same pair out of the equation for now, this can also happen when `max_open_trades` is limiting further buys - so another pair sells in the middle of the 3rd candle, leading to a buy right before the signal disappears - so manually locking a pair will not protect from this, and relying on it is a good receipt for failure.

---

In general, trailing stop parameters should be choosen to be > avg swing per candle - so for 1d candles, 1-2% will definitely be too low - as it's only exploiting the backtesting logic - but not creating a good strategy.

---

I also don't really understand why you think that the sell-reason matters - no matter if the sell is because of a sell-signal, ROI or trailing stop, the logic for locking will be identical - and multiple buys within the "sell" candle (on the same pair) will not happen in backtesting.

**Comment by Corfucinas** [comment]
@xmatthias 

Yes, sorry regarding the title....feel free to edit it.
Let's leave the automated locking out of the topic, since as you said it's not possible to emulate.

I didn't say that the sell reason mattered, it's just that any sell reason will result in similar behavior -as you correctly pointed out- if the buy signal is "sticking". As you mentioned, the buy signal is usually the strongest at the beginning, and any reentry will result possibly in a loss.

Is there's a way to include this logic within the strategy? That is for the buy signal to have to wait until there's a sell signal in order to reenter the market? 
In that scenario, the buy signal will enter on the "first" candle, exit via any reason (stop,trailing or sell), but will have to wait until the "next new signal" rather than wait for the next candlestick and use the "sticking" signal.

**Comment by xmatthias** [comment]
> Let's leave the automated locking out of the topic, since as you said it's not possible to emulate.

This is wrong - automated locking does not need to be emulated, it's available implicitly.

---

In the [hyperopt documentation](https://www.freqtrade.io/en/latest/hyperopt/#configure-your-guards-and-triggers), we make a difference between triggers and guards.
This is an artificial distinction - but it serves well to make you think differently about them.

a guard could for example be: `dataframe['emashort'] > dataframe['emalong']` ... while a trigger could be `crossed_above(dataframe['emashort'], dataframe['emalong']`.

The difference is the "crossed" - which generates just one signal - and is not active as long as emashort is above emalong. The initial entrypoint will most likely be the same (when short crosses above long) - but while the first option is active until the reverse cross happens, the 2nd possibility is just active for one single candle.


Your signal (2 consecutive buy signals) indicates that you're only using guards - and no triggers. In which case, you'll always have this problem.

**Comment by Corfucinas** [comment]
@xmatthias 

Yes, that seems to solve the problem, basically, I need to find one "trigger" to avoid the "sticky" signal.

**Comment by xmatthias** [comment]
Great.
I'll close this as i think this should answer your question.

let me know if you still got questions related to this.

**Comment by Corfucinas** [comment]
Thanks for the answer!
