### ISSUE TITLE
Certain config parameters don't do anything

### ISSUE THREAD

**Issue by Samaoo** [freqtrade/freqtrade#3953]
## Describe your environment

  * Operating system: Windows 10 (I tested with and without docker)
  * Python Version: 3.8.5
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The config parameters below don't do anything:
```
"timeframe": "5m",
"dataformat_ohlcv": "hdf5",
"dataformat_trades": "hdf5"
```

### Steps to reproduce:

  1. Add the listed parameters to a config
  2. run ```freqtrade download-data -c the_config_you_edited.json```
  3. As you can see below, it will use the defaults instead of using the parameters from the config
```
2020-11-15 18:37:35,929 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2020-11-15 18:37:35,929 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-11-15 18:37:35,929 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
```
  
### Observed Results:

  * What happened?
The default values were used instead of the values from the config
  * What did you expect to happen?
That the values from the config would be used

**Comment by xmatthias** [comment]
You're right, it's wrong for ohlcv and trades data (because the cli argument specifies a default)

for timeframes however, it's correct the way it is.

`timeframe` (singular) is used for trading / backtesting / hyperopt ...  the corresponding command line switch is `-i`, `--timeframe` / `--ticker-interval`.
`timeframes` (plural) is used for data-downloading - specifying it in the configuration is currently not possible (it's also nowhere documented that this would be possible). It's available as `-t` / `--timeframes` - and takes more than one element.
