### ISSUE TITLE
How to make bot to send notification to multiple telegram account

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3969]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
How to make bot to send notification to multiple telegram account?
Is there any way i can do it? Currently i get notification only on the telegram bot. I tried to create a telegram group and added the bot but i don't get notification onto that group. Any though please ? 

thanks
  
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Since the telegram channel has the power to control your bot, this is not something we intend to support actively.
You're also not sharing your API keys to your exchange i would hope.

You can use a telegram group (as [documented here](https://www.freqtrade.io/en/latest/telegram-usage/#use-group-id) - and if configured correctly, this should work just fine.

However, you should be carefull who is in this group, as everyone can forcesell all pairs, and depending on the configuration, also forcebuy - which if done with malicious intend (or for fun...) can have negative financial consequences for you.

**Comment by NilanjanaBala** [comment]
Thanks @xmatthias for your time and reply. You are right, looks like every body form the group can play with the bot which is not a good idea. If we can make only adim to play which can solve this issue.

**Comment by xmatthias** [comment]
Honestly, this is not anything that i think is worth the effort to implement and i will surely not dedicate any time to this.

If you think it's a must, please implement and submit a Pull Request (including tests, ...).

Otherwise, either trust the people in your group (keep the group limited to people you trust 100%) - or keep the bot in your private messages (which is what it's designed for).
