### ISSUE TITLE
Average loss on stoploss order in backtesting is -0.3 lower than the actual stoploss

### ISSUE THREAD

**Issue by Samaoo** [freqtrade/freqtrade#3973]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

For example, if the stoploss in the strategy is -5, the average loss on stoploss orders will be -5.3 in backtesting

**Comment by xmatthias** [comment]
yes, and it's kinda intentional (even though it's not really documented).

For the below - assume live mode  with a stoploss of -0.05 (-5%).

Then the -5% will be your stop price - not the price you're filled. 
Let's assume binance (with stoploss on exchange):
Then the -5% will be your stop price - but a stoploss-limit order (the only stoploss order supported by binance) has 2 prices, the stop price (-5%) - and the limit price (which by default os -1% from the stoploss, so -6%).

Now your order will usually fill somewhere between -5% and -6%. Sometimes it'll fill at -5.001% - sometimes at -5.99% ... but everything in between is possible.

It get's worse if the exchange uses stoploss-market orders - where you only have the stop-price - and the subsequent order is a market order - which in theory can fill at -9% if market drops fast and has low liquidity (even though your stop-price was -5%).

Now backtesting does not know liquidity at every pricestep - but we know that a fill at exactly -5% is rare (possible, rare - but backtesting aims to be more conservative ...).

Hope this makes sense.

**Comment by Samaoo** [comment]
That makes sense, but I think it should be documented

**Comment by Samaoo** [comment]
I think it would make more sense if the loss on a  backtesting stoploss order would be the average of the stop-price and the limit-price instead of a fixed value

**Comment by xmatthias** [comment]
Honestly, if your strategy's backtest performance  depends on this, you've already lost once your strategy hits real markets, where the orderbook will determine if you're filled or not.

Best familiarize yourself with the [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting) - which if you think about it carefully will make it clear that backtesting can never be 100% correct.
You can play them to make your strategy look better in backtesting - and for dry / live, you should always assume that these results can be a bit lower - simply because of unfilled orders - and because in reality, you'll rarely get exactly the candle's open price as price for your candle.

---

also what if the exchange only has stoploss-market? (or that's the selected stoploss type)?
Do we then average between the stop-price and 0 (because in theory, a stoploss-market-order can fill on 1$ - even for BTC/USDT where the stop was at 15.000$ .. )

**Comment by Samaoo** [comment]
I understand that backtesting will never be 100% correct but I still don't think it makes sense to use a fixed value that can't be changed, I think it should at least be customizable in the strategy or config.

**Comment by moinonin** [comment]
@Samaoo  I assume by this statement ".... your order will usually fill somewhere between -5% and -6%. Sometimes it'll fill at -5.001% - sometimes at -5.99% ... but everything in between is possible". The value stated there is some kind of average. Probably not just of the two but of all the pairs (that gets the stop loss). Correct me if I am wrong @xmatthias

**Comment by Samaoo** [comment]
I don't understand what you mean.
