### ISSUE TITLE
Trailing stop loss, when is it triggered ?

### ISSUE THREAD

**Issue by Tigzy** [freqtrade/freqtrade#3985]
Hello,
I'm running a strategy with the following: 

```
Initial Stoploss: -0.1
Trailing stop positive: 0.002
Trailing stop offset: 0.006
Only trail above offset: True
```

Sometimes, when the market has pump/dump, I can see trailing_stop_loss being triggered but with losing trade. 
I know this is because of market sell, and that limit sell is good for fixing this, but my question is the following : 

When is a trailing_stop_loss triggered for selling ? Is it only when a candle ends, or is there a re-check periodically inside candles ? 
If only at candles, is there a way to specify different time check for selling condition ? 

For example my strategy uses 15m timestamp for calculations, but what if the market drops suddenly ? It would be great to be able to check intra-candle for sell condition. The telegram bot sends sell notifications at random times, not respecting candle timestamps, so that's why I'm wondering...

**Comment by xmatthias** [comment]
stoploss, roi and trailing stoploss are checked periodically (every `process_throttle_secs` - which defaults to 5s).

sell-signals are checked at the same intervals, UNLESS you're setting "process_only_new_candles" to true.
However, you're only getting complete candles (no incomplete candles, as that would lead to repainting and to unrepeatable results) - so if you're using TA on top of the dataframe alone, you'll always get the same result, as the candles won't change unless a new candle is posted on the exchange.

You can work around this in several ways by using faster data (all of which are in the documentation).

---

With your configuration, you'll most likely get a lot of emergency sells. These happen if a coin bumps, the bot tries to adjust the stoploss - but while doing so, the market dumps below the stoploss price, causing the bot to be unable to place the order.
Since emergency-orders default to market, you're likely to dump below profit - as you've also only got an offset of 0.6% ... and on illiquid pairs it's rather simple to push the price by a few 0.x% with a market order (doesn't even have to be huge ...).

In my opinion, everything below 1% (or 0.5%, depending on then pair) for trailing will not work in most markets, as crypto moves too fast for this.

**Comment by Tigzy** [comment]
Thanks for the answer 👍 
In fact it works very well for scalping, taking advantage of small moves rather than waiting for big pumps.
"Waves" are usually moving by around 0.5% to 2%, and I'm only interested in top liquid pairs; I don't think I'm using emergency selling (?)

So what you're saying is that sell signal is checked every 5 seconds, but will be processing the same data for 15mns (the candle timestamp) ? Using smaller timestamp would indeed be the solution, however when I do so the results are totally different. I guess my TA also adapt to this timestamp, which I don't want. Any pointer ?

**Comment by xmatthias** [comment]
Emergency-sell will be used whenever stoploss on exchange fails to be created.
It's not optional (although you can switch between market and limit orders).


Sell-signal is using the same data for 15m - but ROI / stoploss are checked every 5 seconds.

Either, your TA is based on 15m - so it's fine as is - or it's based on 5m or 1m data - in which case you MUST use that as timeframe.

**Comment by Tigzy** [comment]
Thanks. I'll try to refactor my TA using lower timeframe.
Can you clarify just that ? 

`Sell-signal is using the same data for 15m - but ROI / stoploss are checked every 5 seconds.`

Does that mean ROI / stoploss will download new price every 5 seconds, or it will reuse the same price from the last candle for 15mns ?

**Comment by xmatthias** [comment]
ROI / stoploss use the current price (either via fetch_ticker, or via fetch_l2_orderbook - depending on your configuration).

It's fetched every 5 seconds for all open trades - and decisions are based on this (otherwise we would run a VERY risky bot ...)

**Comment by Tigzy** [comment]
Ok, thanks for confirmation. 
So this means it's very unlikely to have such a massive drop (0.6% + fees) in 5 seconds right ? 
So how's that possible, because of market sell ? 

Also checked lower timeframes but not working well, because of false positives. Smaller candles means more noise.

**Comment by xmatthias** [comment]
in crypto, drops of 1% and more within 1 second can happen rather frequently, this can be caused by one large market order, too.

If you're using market sell - you must make sure to use the correct [pricing strategy](https://www.freqtrade.io/en/latest/configuration/#market-order-pricing).

Obviously, market orders do not guarantee a execution price - so even if you use the correct configuration, you may think you're selling at 90$ - but in reality there's no volume so your price drops to 85$ ... or even lower.

**Comment by Tigzy** [comment]
`in crypto, drops of 1% and more within 1 second can happen rather frequently, this can be caused by one large market order, too.`
I would agree for illiquide coins, but usually such drop take around 30 seconds to 1 mn. 
I guess it can also be some delay with API calls / networking + calculation and time to execute the sell order, anyway...

I've reverted to limit orders for now, we shall see... 
Huge thanks for your timely support, this is greatly appreciated 👍

**Comment by xmatthias** [comment]
whenever there is such a drop, the binance API is usually heavily overloaded, so failed network requests / slower than usual responses are common during that time.

there's not really much the api consumer can do against this - as it's undersizing of their API infrastructure.
