### ISSUE TITLE
Optimizing on SharpeHyperOptLoss

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#3989]
Hello all,

How can I run the SharpeHyperOptLoss in the environment? Is there any code like python3 ./freqtrade/main.py -c config.json (..)? I absolutely want to use that hyperopt function because I do not get the same results if I run a backtest on the optimization parameters. This makes it truly a waste of time, but I have already read that this is probably because of the old sharpe formula. I am currently using freqtrade 0.17.3, but I guess there is already a newer version. If I am not able to run the SharpeHyperOptLoss code in this version, can you please tell me how I should update the newest freqtrade version? I have already investigated a lot of codes on the freqtrade.io website, but it just doesn't work. Normally if my version is up-to-date, I should be able to run a code like freqtrade trade config.json --strategy (name).

Thank you for your reply.

Cheers,
Mathias

**Comment by xmatthias** [comment]
version 0.17.3 is a version that's over 2 years old.

Since we're an open source project where people donate their free time, we do not support outdated versions.

Best read the [documentation](https://www.freqtrade.io/en/latest/) to get up to speed what changed (tons of things have changed - so commands you used before may now have a slightly different syntax).

I would also recommend to scrap your installation and start from scratch, as i'm not sure updating from this version will work flawlessly.
you should be able to keep your strategies / user-data directory, although some adjustments may be necessary.

**Comment by mathias5986** [comment]
Hello Matthias,

Thank you for your message. I saved my strategies and recreated a virtual machine.

On the website of Freqtrade (https://www.freqtrade.io/en/latest/installation/) it is not very clear for me whether I need to start with the "Quick Start" and move on afterwards to the "Custom Installation" or should I immediately go to the "Custom Installation"? I have already tried many options (first "Quick Start" then "Custom Installation, ..), but I still get some errors. Quite strange .. Every time I get an error, I delete my virtual machine and re-install it to do nothing wrong.
Moreover, should I run these commands in the Freqtrade folder itself or just in the home directory ?

sudo apt-get update
sudo apt-get install build-essential git

I suppose that the TA LIB and the code regarding the virtual environment need to be run in the /freqtrade/ folder.

Thanks!

**Comment by xmatthias** [comment]
which OS are you using for your virtual machine? make sure it's an updated one to avoid problems.

the quickest way to get started is by using [docker-quickstart](https://www.freqtrade.io/en/latest/docker_quickstart/) - this will require a working docker installation - but otherwise there is no installation necessary (I would however not run docker within a virtual machine, that's adding 2 layers of virtualization ...)

If you don't want to use docker, you can use the quick install method (setup.sh) - obviously we'll need some dependencies (python 3.7 or 3.8) to preexist for this to work.

Usually, you will not need the "custom installation", unless you don't want to use the setup.sh script. It's there for completeness - but i would not use it unless you're familiar and confident with running linux.

**Comment by mathias5986** [comment]
I am using Linux on the Oracle VM VirtualBox (Ubuntu 64-bit).
If I run the first code, I get this message:
![image](https://user-images.githubusercontent.com/74938818/100120170-f0bf8000-2e77-11eb-856f-1089d902e7ad.png)

So first, I run sudo apt install git, which perfectly works, and then I re-run : 

git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
# git checkout stable  # Optional, see (1)
./setup.sh --install

But afterwards, I get stuck with python3.8 -m pip:
![image](https://user-images.githubusercontent.com/74938818/100120850-b4d8ea80-2e78-11eb-9234-2aa67a0ab191.png)

I have this Python version:

**Comment by mathias5986** [comment]
![image](https://user-images.githubusercontent.com/74938818/100121137-113c0a00-2e79-11eb-9cff-872e6ad2fc7f.png)

**Comment by mattneel** [comment]
`apt-get install python3-pip`

**Comment by xmatthias** [comment]
We are not providing support for getting python (nor pip) installed - they are listed as prerequisites.

Best use google to find out how to install this (it will depend how python3 was installed to your system, so the solution we could provide may not cover your method of installation).

Thanks for your understanding.

**Comment by mathias5986** [comment]
I made it already to enter the environment! Thanks! Just wondering why I can't download new data:
![image](https://user-images.githubusercontent.com/74938818/100132497-ca084600-2e85-11eb-853d-96bfcebdae0d.png)

**Comment by xmatthias** [comment]
because freqtrade doesn't seem to be installed? did you encounter some erorr during the setup.sh installation process?

**Comment by mathias5986** [comment]
Hello Matthias,

Great news! It finally works, but I had to install more than just the "quick start" (also some codes from the custom installation). I don't know anymore what I did haha. However, now I see that a lot has been changed! Classes of optimization and strategy files don't need to be defined anymore in the __init__.py. A good sharpe rate is shown in green and the structure is extremely clear with already some strings mentioned in the ROI. What does ETA actually mean and last but not least, can you please tell me what your favorite hyperopt optimization function (sharpe, sortino)? Thanks once again!

Cheers,
Mathias

**Comment by xmatthias** [comment]
there is no favorite - they simply optimize for different targets - one favoring lower losses / drawdowns, one bigger profits.
it'll depend on your trading style / goals / ... that's why we don't offer one loss funcion, but multiple.

ETA is there to show you how long hyperopt may still be taking.
Obviously it's a very rough estimation and it can also increase over time (it knows how many epochs you run, so after the first 100 epochs, it knows you ran 10% of the 1000 epochs you're going to run ... -> you can estimate how long it still takes.

**Comment by xmatthias** [comment]
I'll close this as i see (#3994) that you succeeded in running hyperopt.
