### ISSUE TITLE
multipe buys & sells within candle

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade#3991]
Hi Team,

I have a bot that is using 5min candles, which sometime buys and sells within the 5min candle, when trailing stops are initiated.
Sometimes after it has sold, it buys again within the same candle.
Is there a config/setting that will prevent the bot from buying again within the same candle, without affecting the refresh rate for the ROI and stop losses?

Thanks
zlac116

**Comment by xmatthias** [comment]
freqtrade will not buy the same asset again, however it may buy another asset if a trade-slot (max_open_trades) becomes available mid-candle.

You can't really prevent this from happening, as usually the signal is present for the whole candle - assuming you do traditional TA

**Comment by zlac116** [comment]
Thanks for the quick response.
I've just noticed that the bot is actually continuously buying (the same asset after it has sold) in the subsequent candle because the strategy buy condition still holds.
Is there a smart way of getting the bot to only buy/sell the same asset only once it has received new ohlcv info, I guess similar to the backtest?

Thanks

**Comment by xmatthias** [comment]
assuming you're using a recent version - then the bot will NOT buy the same asset within the same candle due to pair locking until the next candle arrives (this is to make it similar to backtesting).


It will buy once a new candle arrives, as that is new information. 
This is identical to backtesting - if your candle still shows the signal after it sold, then also backtesting will buy with the next candle (assuming trade-slots are available).

If this is not what you desire, then you must adapt your strategy - as it's suffering from a "sticking signal".
for example:
your only condition is `dataframe['rsi'] < 30` - this means, there's a signal as long as RSI is below 30 - which can result in multiple buys if rsi stays below 30 for longer.
the correct way for this would be to create a signal (which is only there once):
`qtpylib.crossed_above(dataframe['rsi]', 30)` - which will only buy when the rsi crosses 30 - not whenever it's on one side of it.

**Comment by NilanjanaBala** [comment]
@xmatthias qtpylib.crossed_above(dataframe['rsi]', 30) getting error as 

    qtpylib.crossed_above((dataframe['rsi'], 30)) &
TypeError: crossed_above() missing 1 required positional argument: 'series2'

Looks like qtpylib.crossed_above function needs to pass both as dataframe. Is thought can we can do it?

**Comment by zlac116** [comment]
This is what I thought, using the `qtpylib.crossed_above` to check whether a parameter switches from one side of a specific level to the other. I'll need to make changes to my strategy.

As always appreciate your help! Thanks

**Comment by xmatthias** [comment]
@NilanjanaBala 
your syntax is wrong (carefully compare parenteses between your and my version from the post above), you're passing a tuple to the function, not 2 arguments.
