### ISSUE TITLE
Help to implement buy_params and sell_params Hyperopts to strategy

### ISSUE THREAD

**Issue by jonatasfreitasv** [freqtrade/freqtrade#4014]
Hello,

any help me to implements buy_params and sell_params Hyperopts to strategy? In docs is not so clear.

```
 # Buy hyperspace params:
    buy_params = {
        'adx-enabled': False,
        'adx-value': 34,
        'fastd-enabled': True,
        'fastd-value': 45,
        'mfi-enabled': True,
        'mfi-value': 11,
        'rsi-enabled': True,
        'rsi-value': 40,
        'trigger': 'macd_cross_signal'
    }

    # Sell hyperspace params:
    sell_params = {
        'sell-adx-enabled': True,
        'sell-adx-value': 98,
        'sell-fastd-enabled': True,
        'sell-fastd-value': 74,
        'sell-mfi-enabled': True,
        'sell-mfi-value': 83,
        'sell-rsi-enabled': False,
        'sell-rsi-value': 98,
        'sell-trigger': 'sell-bb_upper'
    }
```

**Comment by xmatthias** [comment]
To be honest, i think the [hyperopt documentation](https://www.freqtrade.io/en/latest/hyperopt/#understand-the-hyperopt-result) is quite clear if you read it from top to bottom, as it's one sample, which also shows how to implement the solution in a strategy (only for buy side, but the sell side is identical).

If you have **specific questions** (which includes how far you got, and where specifically you got problems), feel free to ask them. 

However, dumping a result here and asking "please do the work for me" is not going to happen.

We are an open source project, where people donate their time for free to help other people. I will however not give my time for free because you are too lazy to properly read and understand the documentation.

Thanks for your understanding.
