### ISSUE TITLE
Time out backtesting number of trades

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4032]
Hello,

On which time out data is the number of trades per day (backtesting, summary metrics) based ?
Because this can significantly change if you take for example buy and sell time out 1 minute or 30 minutes.

Is this based on the default value?
Buy: 10
Sell: 30

Thanks,
Mathias

**Comment by xmatthias** [comment]
Your question does not make sense, the 2 things have nothing to do with each other.


Backtesting has nothing to do with timeout. 
Trades per day is simply the `amount of trades / number of days`

Please also try to use the [documentation](https://www.freqtrade.io/en/latest/backtesting/#summary-metrics) instead of asking here.
 
This is an open source project, and people donate their time to improve the bot - answering questions that are already in the documentation will only waste people's time, so please do your research BEFORE asking questions that can be answered by the documentation.

Also, for such questions, please use either the Discord or slack Servers (where people will then most likely refer you to the documentation).
Thanks for your understanding.
