### ISSUE TITLE
Hyperopt vs Edge Positioning

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4048]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

As I understand it, **Edge Positioning** ignores strategy configuration, and dynamically decides stoploss, trailing stoploss, and ROI, using probability. So theoretically it should improve with time, without any changes to the bot configuration.

Whereas **Hyperopt** requires the downloading of historical data, backtesting & Hyperopt testing, to output values, that then have to be manually configured in the strategy file.

So here's my questions:

1. I'm I understading this correctly? Is this how the two modules work?
2. Is there a reason to use Hyperopt, since Edge Positioning works automatically?
3. Can both be used? Since Hyperopt (manualy) builds an optimized strategy, and Edge Positioning ignores it.
4. Is there a way to automate the Hyperopt process? Downloading, backtesting & implementing configuration.

Thanks

**Comment by xmatthias** [comment]
I think you're comparing bananas to cars... (the two couldn't be further apart).


first of all, Edge has quite a few limitations (it will NOT use ROI, nor will it use trailing stoploss).

Also, Edge requires an existing strategy with good buy and sell signals, and will NOT touch your buy / sell signals.
Edge will however determine the allowed risk (stoploss), and  in trading mode, will determine if a pair should be in the whitelist or not (based on performance over the last X days).


Hyperopt on the other hand uses regular backtesting under the hood, and can also be used to create buy / sell signals from scratch (not fast, and often a "human idea" is better), but it's still a possibility.

1) please read  the docs, especially the [edge documentation](https://www.freqtrade.io/en/latest/edge/) very carefully. it'll answer most of your questions.
2) see above explanation
3) Edge does NOT ignore the existing strategy, it will use buy / sell signals from the strategy, so to generate this, you might need 
4) Downloading of data should be done once, with incremental data downloads after that. Automating this does not make sense, as using different data, you'll remove yourself from the possibility to validate your results via backtesting.
Hyperopt results must be transferred to the strategy manually. This is intentional as it ensures there is a "human thought" behind the strategy, which we hope will improve user's understanding of the strategy that was generated, and will help detect potential issues with the result.

**Comment by aristosv** [comment]
Obviously I had it totally misunderstood. Thanks for the explanation.
