### ISSUE TITLE
edge is broken always get INFO - Active pair whitelist is empty.

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#4056]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.6 (`python -V`)
  * CCXT version: latest docker (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest docker (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. enable endge
  
### Observed Results:

 I tried everything including:
1.  set empty strategy only buy trend rule `dataframe['buy] = 1`
2. use the default config file 
3. adding 30+ pairs in config

No matter what i get `INFO - Active pair whitelist is empty.`

**Comment by xmatthias** [comment]
Edge is not broken, but your settings are wrong.
If you only use a buy signal (but no sell-signal) - then edge will not work.

Please read **and understand** (!!!) the [edge documentation](https://freqtrade.io/en/latest/edge) very carefully.

Edge will require tuning / configuration to your strategy, as it requires a certain minimum expectancy over the last `calculate_since_number_of_days`. If that's not met, edge will remove all pairs from the pairlist.

This is intentional, and there's only a few reasons for this: 
* Your strategy did not generate enough trades in the last `calculate_since_number_of_days` days (tune this parameter)
* your strategy does not generate any winning trades (you most likely don't have a sell signa)
* your `minimum_expectancy` is too high, so your strategy does not reach it

**Comment by macd2** [comment]
I'm using trailing stop as my exit strategy. So I have `use_sell_signal = True` than i set it manually to `dataframe['sell'] = 0 ` and than edge should be using exclusively the trailing stop!?

**Comment by xmatthias** [comment]
Let me repeat what i said above. 
Please read the [edge documentation](https://www.freqtrade.io/en/latest/edge).

You don't even have to read it all, the main, relevant section is in the 4th line (the first Note box):

> Edge Positioning only considers its own buy/sell/stoploss signals. It ignores the stoploss, trailing stoploss, and ROI settings in the strategy configuration file. Edge Positioning improves the performance of some trading strategies and decreases the performance of others.



That documentation clearly states that edge will require a valid sell signal, and will ignore ROI and trailing stoploss as exit signals. This means, your strategy is not suitable for edge. Please disable it or develop a good sell signal.

**Comment by macd2** [comment]
How can it be that I have a perfectly valide strategy, it works without edge. The fact that it stops working as soon as you turn on edge doesn't make any sense  to me.  

Also edge is optimizing the `stoploss` which should be check regardless if there is a sell signal or not, so at least run edge with the stoploss only. Or provide a setting in config to substitute exit strategy for trailing stop...

I'm sorry but having edge require different settings then the rest of the bot doesn't feel right to me. 

In any case thanks for the reply!

**Comment by xmatthias** [comment]
It's clearly stated in the docs, and was an explicit decision from the authors to only support Sell signals and static stoploss with edge.

Your strategy is perfectly valid, and will work just fine without edge.
If you want to use edge, you must have a sell signal for exits. 
That doesn't make the strategy invalid, just not compatible with edge.

Your strategy will most likely also not work that well if you start switching markets (from BTC to USDT, or BTC to ETH) ... that also doesn't make the strategy "invalid".

> I'm sorry but having edge require different settings then the rest of the bot doesn't feel right to me.

Keep in mind, this is a free, open source project, where people donate their FREE time to support othe people.

If you think this is needed, please step up and implement support for ROI and trailing stoploss instead of complaining, and on top of that, wasting peoples time by not reading the documentation.
Thanks.

**Comment by hsozen** [comment]
> Let me repeat what i said above. Please read the [edge documentation](https://www.freqtrade.io/en/latest/edge).
> 
> You don't even have to read it all, the main, relevant section is in the 4th line (the first Note box):
> 
> > Edge Positioning only considers its own buy/sell/stoploss signals. It ignores the stoploss, trailing stoploss, and ROI settings in the strategy configuration file. Edge Positioning improves the performance of some trading strategies and decreases the performance of others.
> 
> That documentation clearly states that edge will require a valid sell signal, and will ignore ROI and trailing stoploss as exit signals. This means, your strategy is not suitable for edge. Please disable it or develop a good sell signal.

I'm having the same problem and there's valid buy and sell settings. The same strategy works fine on my computer and it gives the error mentioned above on my friend's computer. What about that? The same strategy same settings, two different computers. They even both have the same config file. Yet the aforementioned error keeps popping up. Is there a specific reason for this empty list event? 
P.S. I have read the documentation and some important parts are not clear enough there. There's even code it says working in the documentation yet doesn't function in the "stable" version of the program. I don't know if they work in "development" versions.

**Comment by hsozen** [comment]
> ## Describe your environment
> * Operating system: ubuntu
> * Python Version: 3.6 (`python -V`)
> * CCXT version: latest docker (`pip freeze | grep ccxt`)
> * Freqtrade Version: latest docker (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
> 
> Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.
> 
> ## Describe the problem:
> _Explain the problem you have encountered_
> 
> ### Steps to reproduce:
> 1. enable endge
> 
> ### Observed Results:
> I tried everything including:
> 
> 1. set empty strategy only buy trend rule `dataframe['buy] = 1`
> 2. use the default config file
> 3. adding 30+ pairs in config
> 
> No matter what i get `INFO - Active pair whitelist is empty.`

Hey, hi! I experienced a similar thing. In the error it says pair whitelist is empty. It means "there is no pair to add in the trading pairs list". So, do you have any filters such as Precision Filter, Age Filter, Range Filter or any sorts? They might be the reason. I have removed the filters just now and the strategy worked without any error.

**Comment by stash86** [comment]
It's not broken. That just mean edge found that none of the pairs satisfy the requirements you set in the config.

Either improve your strategy, or loosen the edge parameters, or don't use edge at all

**Comment by xmatthias** [comment]
Please don't revive 2 year old issues. It's very unlikely that the same solution will apply to you.

it'll also send notifications to everyone that ever commented in this issue - which is clearly unnecessary.

If you have a problem now (with a different version than the one from 2020 - which is VERY likely - open a new issue.
