### ISSUE TITLE
Possibly slightly wrong informative pair merging

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#4073]
When merging longer timeframe to a shorter one, the timedelta is added to the date:
https://github.com/freqtrade/freqtrade/blob/f320cb0d7a12e064018967cf049dd6719fff8ddb/freqtrade/strategy/strategy_helper.py#L35

then it merges to the shorter timeframe with these dates..
https://github.com/freqtrade/freqtrade/blob/f320cb0d7a12e064018967cf049dd6719fff8ddb/freqtrade/strategy/strategy_helper.py#L42-L43

So lets say we are merging a `1h` timeframe to a `5m` timeframe and there is a signal `True` at `00:00` on the `1h` timeseries. 
With this merge, the signal will appear in the `5m` timeseries also at `00:00`. However the `00:00` candle for the `5m` timeframe is received at `00:05`, that is five minutes later than the time you actually received the `1h` candle, which should have been received at the candle with date `11:55`. 
So after merging, the values should be shifted backward (`shift(-1)`)..or the merging dates should be reduced by one unit of timedelta of the shorter timeframe..
```python
informative['date_merge'] = informative["date"] + pd.to_timedelta(minutes_inf, 'm') - pd.to_timedelta(minutes, 'm')
```

**Comment by xmatthias** [comment]
hi @orehunt,

all candle dates are candle open dates (to keep in mind for the rest below, both for myself and for future readers)

I'll use 15m below, as this is easier to visualize (but the concept remains the same for 5m and 15m candles)
i've intentionally left all timestamps, also the one that's not shown to users usually (`date_merge_1h`).

![2020-12-16-195613_1219x286_scrot](https://user-images.githubusercontent.com/5024695/102393524-c70dfa80-3fd8-11eb-84af-d4dfcb0a83ec.png)

If i understand you correctly, then what you're saying is that the 15m candle at 23:45 should be merged with the 1h candle of 23:00 instead of with the candle of 22:00 (which is currently the case).

what you'd see as correct would basically look as follows?
(notice that the 23:45 candle is merged with the 23:00 candle)

![2020-12-16-201415_1216x294_scrot](https://user-images.githubusercontent.com/5024695/102395350-48668c80-3fdb-11eb-83bf-af04a47fb4da.png)

**Comment by orehunt** [comment]
@xmatthias Yes, that is correct, the `23:45/15m` candle is received at the same time of the `23:00/1h` candle, therefore should be merged on those dates. 

To be precise, currently, it does not merge `22:00/1h` to `23:45/15m`, it merges to `22:00/15m` and forward fills to `23:45/15m`
