### ISSUE TITLE
telegram causing freqtrade issue?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4074]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

Today telegram went down and could not communicate with freqtrade. So I restarted freqtrade and the logs showed me these issues, and I think they were caused by telegram.

https://paste.ofcode.org/kT3hHMapyFMDZiKXFAiNuY

Also freqtrade could not start again, so I disabled telegram in config.json and freqtrade started again, and then it was ok. But while writing this, if I enable telegram in config.json, freqtrade will not start.

Does it make sense that telegram causes freqtrade not to function correctly? Or could I have configured something wrong?

Thanks

**Comment by Youbadawy** [comment]
Well, it does make sense when you have it configured to use telegram. I believe we should create the option to automate through a second messaging option, maybe discord?

**Comment by aristosv** [comment]
I don't think it makse sense to stop freqtrade from functioning simply because it doesn't communicate with telegram. Telegram is simply a method to communicate with the bot. It shouldn't affect trading.

**Comment by Youbadawy** [comment]
Of course, I agree with you, when telegram is down is should not stop the bot from trading. If we are discussing the continuous improvement for the bot nothing should interfere with trading as long as it does not directly affect your strategy! 

Other than the current work around of turning off telegram in config, is maybe have a backup bot through another messaging service, and if that is down as well, I would say create a requested exception, in case they are both down to ask user whether to continue without a "communication bot"...

Apologies if the form of my suggestions does not fit the norm, I am quite new to the github community, but appreciate all the hard work the freqtrade members have put into this project, it is quite a marvelous creation!

Looking forward to contributing soon!

**Comment by Youbadawy** [comment]
If someone can direct me towards the section of the code about telegram, I could try and duplicate the bot for a discord bot?

**Comment by xmatthias** [comment]
telegram may be down ... but it'll not impact trading operations, and a running bot will continue to run (it will not crash, and trading operations won't be impacted).

Freqtrade will however (probably) not start when telegram is down (as noted above). 
Disabling telegram for the time being is the right thing to do ... i think however it's correct to force a manual user action ... 

almost no one is checking the startup log very accurately (neihter am i, unless something is failing), so silently (with log message) failing to initialize telegram will lead to the user thinking he'll be notified when buys / sells / ... - which however is not going to happen.

Since telegram is down, there's no way to notify the user other than "failing to start" ... and even having alternative rpc methods (discord, ...) would not help, as we cannot assume other methods are configured - and one RPC method cannot depend / use another RPC method - these are decoupled for a reason.

**Comment by aristosv** [comment]
I only noticed telegram was down because I restarted freqtrade while telegram was down and freqtrade would not start.

If I hadn't restarted freqtrade I would have no idea if it was buying/selling etc, because telegram would not notify me. So whether I restarted freqtrade or not, I would have no way of knowing if it was buying/selling etc.

I think the freqtrade service is too important to depend on telegram to start, but that's just my 2cents.

What I would do, is perhaps implement smtp configuration in config.json, and email the user if something is wrong with telegram. You need to somehow reach the user to let them know that their normal communication method is down. But this is just a suggestion. I don't have the knowledge to implement such a feature.

Either way telegram is back up again, so freqtrade is working just fine. Thanks for taking the time to reply, freqtrade is great by the way 👍

**Comment by xmatthias** [comment]
using email is a VERY bad idea.

If you've ever tried to configure a server (potentially without domain assigned) to send emails that are actually reaching your gmail inbox, you'll know that that's not a route you will want to go down.

**Comment by aristosv** [comment]
I meant an smtp relay. Like using a gmail account to relay emails to the user.
