### ISSUE TITLE
a better way of creating strategy rules

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4084]
Looking at a python strategy file, can be a bit hard to understand how it will actually behave once freqtrade is running. I don't want to sound ungrateful for all the hard work that goes into building this wonderful program, but at my age it's not easy to learn a new programming language.

So I was wondering if there is an easier way of building the rules that go into a strategy file, so it would be easier to create and eventually understand them better.

I came across something that made it a lot easier for me to create basic strategy rules, and thought "**if I could get this to generate python code I can use in a freqtrade strategy file, it would be fantastic!**"

This is how it works:

![Greenshot 2020-12-18 08 01 55](https://user-images.githubusercontent.com/528302/102580545-6b8e5a80-4107-11eb-8293-b33b3212d37d.png)

I know it's a lot to ask, but I'm just thinking out loud here.
No such tool exists, right?

**Comment by xmatthias** [comment]
Not to my knowledge, no.

It's also unlikely that we'll be building such a thing - at least in the near / mid term.
While it sounds great in theory, it'll be limiting you very soon as you'll be limited to the combinations built into the UI, while a strategy / python code does allow you to do whatever you want.

Consider that freqtrade is an open source tool. Everyone working on freqtrade does this on their free time, so building this thing would take a huge chunk out of people's free time, which they would better spend with their families, or work on improving their own strategies.
It'll also be of no benefit to the people developing it, because these are the people most liklely capable to write a strategy easily - so i strongly doubt anyone will be willing to invest the time for this.

It's different if it's were a commercial bot - where people are paid to work on the bot, and people pay to use the bot - as then having things simple for users is a great focus, as that means you attract more inexperienced users, which means more revenue for you.


As said, it'd be great to build such a thing (maybe into [freqUI](https://github.com/freqtrade/frequi)) - basically as a simple strategy generator ... but unless it's a contribution (maybe you struggle with python, but are a great JS developer?) i doubt that we'll ever add this - simply because it'd be a great time investment with doubtful benefits.

I say doubful because while attracting more users is great on one side - this will attract a lot of inexperienced users, so while the entry is simpler, there'll be a lot more "simple" questions (most of which can be answered with a simple google search or by reading the docs) - which in term will increase the pressure on maintainers / experienced users.
We see this each time BTC surges (more publicity for crypto overall - so more people try a bot) ... and this would - potentially at least - not improve things.

**Comment by aristosv** [comment]
Thanks for the explanation, and all the work going into freqtrade.
