### ISSUE TITLE
good specs for backtesting and hyperopt

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4087]
I am looking to buy a used computer to use exclusively for backtesting and hyperopt. I found some old computers with Xeon and i5 (2nd & 3rd generation) Quadcore CPU's and 8 or 16GB RAM.

What would be a good balance between performance & cost to run this task? Is there a specific CPU I should be looking for? I'm not looking for super fast calculations, but the computer I am currently using can't cope with hyperopt, and sometime it even kills freqtrade while backtesting. (8GB RAM)

Not looking for any warranties either. Just a general guideline on what would be a good enough purchase to backtest and hyperopt.

Thanks

**Comment by xmatthias** [comment]
it's pretty tough to give you any recomendations - hyperopt will require a ton of RAM for sure, but the amount will depend on your hyperopt parameters (timerange, timeframe, number of pairs).

You can run a year of hyperopt on 2h candles on probably 4gb of ram for ~50-100 pairs - but if you try the same with 5m candles, it may not work.

In general though - more memory is always better - more CPU's will only help you in hyperopt - but you need to fit the data in memory at least once per (hyper)core ... so on a quadcore, it's at least 8 times (because a quad-core has 8 virtual cores, nowadays).

**Comment by aristosv** [comment]
thanks for the info!
