### ISSUE TITLE
Hyperopt with indicator paramater

### ISSUE THREAD

**Issue by ozandem** [freqtrade/freqtrade#4190]
For I understand about hyperopt we can only adjust rsi, adx and etc. What I want to try is that changing parameter of indicator which we will use. As a example:
```
    bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_upperband'] = bollinger['upper'] 
```

How can we adjust bollinger parameter in hyperopt. Like try every number between 1 and 20 for bollinger window stat. I didnt see any guide for that, so maybe there is no way to do.

**Comment by xmatthias** [comment]
It's mostly lack of imagination that leads people to believe that hyperopt does not allow this.

Most likely the most efficient way is to calculate 20 columns with bollinger bands from 1 to 20 window - and then let hyperopt pick the right column.

best take [AverageHyperopt](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py) as example and adjust it to your needs.

The only thing that'll not work is using tuples for the Categorical Space - but you'll not need this for Bollinger anyway as you only have one parameter, not two, so  don't take this 1:1, but while thinking about it and adjusting accordingly.

**Comment by xmatthias** [comment]
I hope the above gives you enough pointers in the right direction to get this working.

If you have further questions relating to this, please use the [discord channel](https://discord.gg/MA9v74M) to get support / help from the community.
People there love to help with challanging problems assuming the documentation has been consulted first.

**Comment by qkum** [comment]
> It's mostly lack of imagination that leads people to believe that hyperopt does not allow this.
> 
> Most likely the most efficient way is to calculate 20 columns with bollinger bands from 1 to 20 window - and then let hyperopt pick the right column.
> 
> best take [AverageHyperopt](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py) as example and adjust it to your needs.
> 
> The only thing that'll not work is using tuples for the Categorical Space - but you'll not need this for Bollinger anyway as you only have one parameter, not two, so don't take this 1:1, but while thinking about it and adjusting accordingly.

We need an example of this in the hyperopt folder imo.

If you are not a veteran programmer you don't know how to do that.

Even if I look at the veteran programmer's hyperopt code, it is so confusing looking at (using nonsense variables named anything from t to GodGenetics with no commenting).

The code for sure is there, but a programmer still learning, can't even read it, and therefore can't figure out how to do the same for your indicator of choice.

Just because people slacked on the commenting before sharing their code - making it useless for those with too low a current coding skill.

I have been looking for a hyperopt solution for Bollinger bands for years now.

Maybe it is time to share an example.

It will likely end up being me who shares one. Because 2021 my coding skill should be enough together with a day of work to figure it out.

- In a noob-friendly format ofc.
-  Sharing veteran code is only helping people who could write it themselves (pointless?)
