### ISSUE TITLE
Dynamic stake amount is higher than expected

### ISSUE THREAD

**Issue by devilsinthedetail** [freqtrade/freqtrade#4200]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.7.3 (`python -V`)
  * CCXT version: ccxt==1.39.33 (`pip freeze | grep ccxt`)
  * Freqtrade Version:freqtrade develop-b9f3410d (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot is trading with dynamic stake amounts which are higher then expected. Given following configuration:
  ```
max_open_trades : 7,
"stake_amount" : "unlimited",
"tradable_balance_ratio": 0.99,
  ```
and assuming a starting balance of 1000, the bot should use 
  ```
currency_balance / (max_open_trades - current_open_trades)
= 1000 / (7 - 0) = 142.8
  ```
for the first trade and 
  ```
currency_balance / (max_open_trades - current_open_trades)
= (1000-142.8) / (7 - 1) = 142.8
  ```
for the second. Which is the way it should be. What seems to happen for short timeframes ('1m') in my case is that closing a trade and opening the next one is not synchronised, i.e. balance is already available again but bot still calculates with current_open_trades > 0, leading to the following:
  ```
currency_balance / (max_open_trades - current_open_trades)
= (1000) / (7 - 1) = 166
  ```
I observed this happening for 1,2, and 3 trades, making the bot suddenly trade with 250 instead of 142.8. 
I only have logs from Telegram for now but try to get some directly from command line. I also did not observe any pull request handling this yet from my version to the newest one. Thanks for looking into this, I hope to be able to provide some logs in the next days.

**Comment by xmatthias** [comment]
I don't think there's much we can do for this case.

What happens is the following:
* bot opens a sell order (it'll be a limit order, otherwise this problem does not exist).
* bot waits for the sell-order to fill - and checks for this every `process_iteration` (usually 5s) by querying the api 
  * the moment the above reports "filled" - the order is marked as filled locally.
* bot tries to open new buy order

The moment your sell-order fills on the exchange, the balance will be available.
Now some exchanges (binance, i'm looking at you specifically) have a delay between filling an order, and reporting the order as filled via orders API. 
This delay get's worse with higher volume as it's depending on their load - so it's not something we can say "wait 10s" .. the wait can be between <1s up to 1 minute (at least that's what i saw in my tests - but i suspect it can be worse in very high volume situations).

While the bot protects itself from failing due to this - it'll obviously throw the calculations off, since the API reports inconsistent results. There's 2 endpoints involved, `balance` and `fetch_order`.

`balance` will contain the amount calculated based off of the filled order
`fetch_order` will still report the order as unfilled, even though it filled and the `balance` endpoint has the balance available again.

This behavior makes the calculation "wrong" - as the balance from this "closing" trade is part of balance ... but it's also part of "locked assets in trade".
The way this calculation is done is to allow adding / removing balances from the api (e.g. withdrawals / deposits) - and recognizing this kindof immediately.


Until freqtrade knows that the order was filled, it cannot mark the order as complete (the order might need to be cancelled or could be canceled on the exchange for some reason) - and since the API is reporting inconsistent results, this can happen.

The only solution i can think of will be one of the following methods:
* use market orders (these fill immediately, so are not impacted by the above delay problem) - check the impact on your strategy though
* use static stake amount - which will remove the need for this calculation
* accept it as is ... (by opening this issue, you already mention that this is not really what you're after).

**Comment by devilsinthedetail** [comment]
Thanks for the detailed answer. This means a simple wait after each trade would not work? And from the solutions you mentioned, is there one which you use or did you never encounter this problem?

**Comment by xmatthias** [comment]
personally, i use static stake amount - but it's because i run multiple bots against the same account / same stake-currency, not because of this problem.

Waiting will work in theory - but has a LOT of downsides.
As said above, you don't know how long you should wait. 
Waiting 20s might be ok in most cases - but in high volume situations, it could be 1m or more (I've seen a issue from another bot which claims they observed wait-times of up to 5 minutes between orders filling, and the API reporting it correctly). 

It'll also slow the bot down for other trades too (so your ROI might be late to trigger) ... so i don't see how this will improve the situation.


At max, i could imagine a "maximum_stake" setting.
Say you set that to 200 - so while your correct stake would be 142.8 - the maximum it'll use is 200 (instead of the 250 you calculated). While it's a "stupid" workaround - it's the only i can imagine to work properly (considering the buggy/laggy API).

**Comment by devilsinthedetail** [comment]
Alright I see, not that easy to implement then. I worked around the stake-currency problem with sub-accounts so I thought its better to get the compound interest on each trade instead of adjusting it manually after X hours (I guess that's what you are doing currently?). To automate that, the bot would need to calculate some baseline which it keeps for X hours adjusting the static stake amount, you think this would be easier to implement? I guess the problem then is how to get the baseline as it needs to be at a time when the bot is not trading,...

**Comment by devilsinthedetail** [comment]
Well, maybe not that hard to implement? 
```python
if no_open_trades:
    static_stake_amount = current_balance / max_open_trades
```
which can be called with every loop as it only adjusts the stake amount when no trade is running and therefore the full balance is available.

**Comment by xmatthias** [comment]
it's based on the (false) assumption  that the bot will (at some point) exit all positions and that startup of the bot will happen with no existing positions.

Neither of the 2 can be taken for granted.
It MAY work for your strategy - but other (slower) strategies may have multiple trades open at all times.

Basically for a slow strategy, you'd NEVER update the static_stake_amount - so you can use the static-stake amount i'm using as well.

you'd also never get to this point if you restart the bot with open positions - so the bot would simply not know how much stake to use - and would either guess or use the current method.

**Comment by xmatthias** [comment]
maybe the best answer for this might be to use a `stake_amount_max` (or similar) setting for dynamic stake amount - which tops the size of dynamic stake at a certain point.

While it'll not really solve this problem, it could be a valid workaround, avoiding the sudden huge stake (although the stake would still be higher than usual).

It's problematic for sure that the API's don't properly report balance at all times - but it's unfortunately not something we can detect or actively influence.

**Comment by xmatthias** [comment]
the PR (#4775) will reduce the impact of this problem, as it'll evenly space trades - so the trade-amount won't be significantly higher than the other amounts.
