### ISSUE TITLE
Take profit (sell order) on a exchange straight after buy - OCO order?

### ISSUE THREAD

**Issue by unplugged8** [freqtrade/freqtrade#4207]
Hello,

Great project and I'd like to thank all the contributors.

Would it be possible to add a function to set 'take profit' straight after buy?
The bot could calculate % from minimal_roi after buy and set the sell on the exchange so in case of bot problem/server downtime/ sell would be triggered on the exchange without a need of bot running 24/7.

I've been using 3commas for bots using tradingview custom signals and the bot sets the sell order(take profit) based on the buy price/trade size and % tp set in the bot settings and sets sell order on a exchange after success buy.

Thank you for all your effort and time on this project.

**Comment by xmatthias** [comment]
Freqtrade offers a similar possibility for stoplosses via stoploss on exchange.

I don't think this is something we'd want/need, and i don't see what benefit it would bring.

Setting a Take profit (limit sell x% above spot) would put your capital by 100% at risk. 
In case of a market crash, your order would stay in place, but price dropped by 50% (or more) - without a re-raise in sight (assuming the bot is switched off, obviously).

Just look at 2018  (XRP / LTC / ETH) for examples of this, which (in case of the mentioned currencies) did not yet reach the level they had early 2018.
To even break even, you'd therefore need to stay in the trade (have your assets locked up) for years. While this may be fine for you, it's not the goal of freqtrade.

For this reason, protecting the user's assets is key / very important. 
By setting the stoploss on the exchange (which is the revers from what you'd want), you get the "server downtime" protection by having the order on the exchange - and your maximum loss per trade is clearly defined as "stoploss".


Would we placethe take_profit order on exchange, you'd be protected from "not selling at profit" - at the cost of risking 100% of your trade in case of a market crash.
Also if you leave your bot running, you'd be slower in case of a crash (where it's VERY important to be fast) - as you'll first have to cancel the order on the exchange before you're able to place the stoploss order.


Freqtrade is however designed to be "always running" (i think that's the main purpose of a bot), so it can trade / make you money while you do something else (or sleep).
If you were to switch it off most of the time, there's not much benefit over doing the trades manually, so it's missing the purpose of using a trading bot.
The main risk you'd be running into with this is that markets crash and the bot is not aware - or that opportunities arise and the bot is missing these.


For these reasons, i don't think this is something that we'll implement - mainly because i don't see what benefits this would bring other than increasing people's risk unnecessarily.
It would also increase the code complexity / code maintenance burden on the team maintaining this in their free time, so unless you can come up with some very good reasons why this is a must, i don't see freqtrade implement this.

**Comment by unplugged8** [comment]
Thanks for a quick reply. 

That's why to "protect user's asset"  would be beneficial to use this option - binance introduced OCO orders (One Cancels the Other) so in this case after buy, you're placing TWO orders - TP and SL - when one is hit, the other is cancelled.

Just assume the coin went up 9% up and for some reason bot stopped working... Coin went up another 5% and then reversed 30%. If the bot didn't place a stoploss, it would go past your SL anyway (assuming you set the SL 10%).

If the bot would place OCO order straight away on the exchange after buy order you are protected both ways (in my example you would close the trade with 10% profit).

I apologise if this is a waste of time for you. The question arose because I'm running virtual machine with freqtrade(I'm planning to set it up on the server so it keeps running 24/7) and there was a power failure and bot stopped running. I missed my TP and SL wasn't hit... I didn't lose any money because I left the trade open but it made me think how I can protect myself better.

Plus I think the bot would perform better because it would release some memory (it wouldn't have to check all the time for TP and SL conditions).

**Comment by xmatthias** [comment]
Binance is basically the only exchange that supports OCO orders.

We're however supporting multiple exchanges officially (binance, bittrex, kraken, ftx) - and many more which most likely just work out of the box - and the effort to implement a feature just for one exchange is currently not worth the time, especially as this would require changes to the main logic of the bot.

If you think this is a must, best implement this and submit a Pullrequest (please with tests, so we're sure not to break this in the future - and it doesn't break anything that's currently working).

**Comment by unplugged8** [comment]
Thanks xmatthias. I really appreciate your input. 

Unfortunately I do think too it would require changes to the main logic of the bot... 

I'm not a python expert - I just started to learn the code to install, run and understand how the freqtrade works. I've started to using it to automate my strategy.
 
Just imagine you have 30 trades on freqtrade and suddenly binance exchange goes down and in that time crypto market loses 30%... It would be a DISASTER!

At least with OCO orders you would be protected - you can always contact support to make a claim in a BLACK SWAN event...

Anyway, great project, sending all the best to all the people who contributed to it.

Thank you :)

**Comment by xmatthias** [comment]
Stoploss on exchange will protect you in this case.

You can also combine this with trailing stoploss, which will (almost) give you what you need - but with the potential to stay in the trade if the move goes paset your configured take-profit.

**Comment by unplugged8** [comment]
Not the fan of trailing stoploss tbh - crypto is too volatile - I rather take 10% and up to the next trade. There is always another trade :) 
Will go with a SL on exchange then. Thanks again :) Closing as I don't want to waste any more of your time :)
