### ISSUE TITLE
Binance Will Update the Ticker of XZC to FIRO

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4221]
Hello everyone!

Should we stop operating in this currency before the update is done, to avoid losses?

What should we do?

https://www.binance.com/en/support/announcement/4a06d6ab6abb4f08b12bb93d6fec30ec

**Comment by xmatthias** [comment]
if i understand this correctly, you COULD leave it running and just update the database manually for the opened trade (if there is any).

It's however unclear what will happen to open orders (will they be cancelled, ...).
I guess it's also possible that price movement behaves "anormally" - either because everyone want's in, or because everyone want's out - or because FIRO get's for some reason a higher or lower valuation (potentially for no apparent reason).

For that reason, i'd suggest to not trade it until the update is complete (you can add it to the blacklist ...) - but as said, manually updating the database SHOULD work as well - as the conversion seems to be 1:1 between XZC and FIRO.

**Comment by moinonin** [comment]
In some cases they have had a very proficient way of transitioning. I remember when ERD changed to EGLD. I had some in the wallet, they cancelled all orders and refunded it's EGLD equivalent in full once the transition was finalized. I don't know however if it was EGLD the company or was it binance exchange that made it smooth. You may wish to inquire from binance

**Comment by tutecode** [comment]
When I had EGLD, my bot "dry-run" sell the crypto in -99%. I lost all the money

**Comment by xmatthias** [comment]
well that would suggest that price "dropped" to 0 - or to almost nothing.

As mentioned above, it will not be handled automatically, so the easiest way will be to simply blacklist the pair (both pairs) until this action is over.
