### ISSUE TITLE
Run FT on AWS 

### ISSUE THREAD

**Issue by ambrel5** [freqtrade/freqtrade#4242]
I was able to run docker-based freqtrade on my machine. Now I want to run it as docker container on AWS cloud.

- pull image to repository (OK)
- launched virtual machine / ECS cluster (OK)
- deployed container as EC2 task (OK)
- launch task (failed)

Error message:
STOPPED (Essential container in task exited)

Maybe ECS & EC2 are not the best way to run the freqtrade image. What are other options? Which resources on AWS are best to run freqtrade? How to config them properly?

--------------------
From AWS Support:

**Essential container in task exited**
_If a container marked as essential in task definitions exits or dies, that can cause a task to stop. When an essential container exiting is the cause of a stopped task, the Step 6 can provide more diagnostic information as to why the container stopped._
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html

**Comment by xmatthias** [comment]
the simplest way will be to deploy a ec2 (or lightsail) virtual machine, install docker and docker-compose there and run the bot just as usual.

While freqtrade may run in an ECS cluster (maybe), we don't officially support that (i never used ECS), so unless you have experience with it, are willing to experiment around, and are able to find solutions on your own, best use the simple "VPS + docker" method.

**Comment by wired00** [comment]
For any other weary traveller who attempts to get freqtrade running in ECS. There are a number of issues you will come against. 

1) You of course will need to deal with EFS mount to persist

**Comment by wired00** [comment]
For any other weary traveller who attempts to get freqtrade running in ECS. There are a number of issues you will come against.

- You of course will need to deal with EFS mount to persist the sqlite database incase the EC2 instance running your ECS tasks is thrown away due to failed health checks (I was using EC2 not fargate for compute). Infant, this applies even if using standard EC2 with docker manually installed and configured (as suggested).
- You will need to prebuild the `config.json` with appropriate settings ahead of time then copy to the instance. 
- You will need to preconfigure the directory structure on the instance 
- You will need to copy the docker-compose file to the instance
- You will then need to mount a volume into the appropriate location within the image so that the default freqtrade image picks it up and has access to everything within `/user_data` etc
- This is all straight forward stuff, however the issue i had was once the container starts it simply did not have access ahead of time to everything i mentioned above. It is as if the ECS task kicks off and the volume does not mount correctly or the working directly is not correct. Even thought working_directory is set and i am sure the volume mounts correctly. very strange. I can ssh to the instance, start via `docker-compose up -d`, `docker exec -it freqtrade /bin/bash` and i see that it's running without issue... very strange...

It's probably something really simple, and I'll come back to it later. I might post the example AWS CDK code here incase it helps someone else out...

Anyway, for now I'm going to resort back to simply using AWS CDK to provision my stack, but it will be a simple VPC > ASG > EC2 > Docker implementation as suggested above.
