### ISSUE TITLE
Edge use all the available balance 

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#4252]
## Describe your environment

  * Operating system: Ubutunu
  * Python Version: 3.8.5
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-c4224198
  
## Describe the problem:

*Edge use all the balance, despit the fact as it can make max x trades according staticpairlist (ie 2/5, etc...)*

### Steps to reproduce:

  1. Enable edge
  2. Use config: 
```
    "max_open_trades": -1,
    "stake_currency": "EUR",
    "stake_amount": "unlimited",
    "position_staking": true,
    "tradable_balance_ratio": 0.98,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "amount_reserve_percent": 0.05,
    "amend_last_stake_amount": true,
    "last_stake_amount_min_ratio": 0.5,
    "cancel_open_orders_on_exit": true,

```
  3. I have 5 static pairs, edge determine to use 2 pairs : 
  Minimum expectancy and minimum winrate are met only for ['ETH/EUR', 'BTC/EUR'], so other pairs are filtered out.
  
### Observed Results:

  * freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: **all balance available**
  * Using **all balance available** / number of trades determined by freqtrade

**Comment by Pascal66** [comment]
Maybe `"capital_available_percentage": 0.5` in edge conf wich isnt documented or deprecated ?
or `"tradable_balance_ratio": 0.5` give the ability to do 2 trades at same time to edge ?

**Comment by xmatthias** [comment]
`capital_available_percentage` was replaced with `tradable_balance_ratio` - but this defines how much of your TOTAL account you want to trade.
so assuming you've got 1000$ in your account, and you'd like the bot to only use a maximum of 500$ - then this is your setting.

The configuration you show above does not include edge - but that's the most important thing when edge is enabled.

There's multiple options to control position size with edge, the most important most likely is "allowed risk" - which controls the allowed risk per trade.

If you say the bot is using the full account for one trade, then this setting is misconfigured.


I can only encourage to really study the [edge documentation](https://www.freqtrade.io/en/latest/edge/) until you fully grasp it - i know it's quite difficult to understand, but the whole topic is not the easiest.

**Comment by Pascal66** [comment]
Using : (with allowed risk 1/3)
```
    "edge": {
        "enabled": true,
        "process_throttle_secs": 1440,
        "calculate_since_number_of_days": 25,
        "allowed_risk": 0.333,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.2,
        "stoploss_range_step": -0.001,
        "minimum_winrate": 0.01,
        "minimum_expectancy": 0.01,
        "min_trade_number": 10,
        "max_trade_duration_minute": 7200,
        "remove_pumps": false
    },
```
Still make a full balance trade.
```
2021-01-23 22:35:05,177 - freqtrade.wallets - INFO - Wallets synced.
2021-01-23 22:35:05,181 - freqtrade.edge.edge_positioning - INFO - winrate: 0.3333333333333333, expectancy: 0.9410601332580939, position size: 85.95860823, pair: ETH/EUR, capital in trade: 0, free capital: 85.95860823, total capital: 85.95860823, stoploss: -0.03, available capital: 84.2394360654.
2021-01-23 22:35:05,184 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 84.2394360654 ...
2021-01-23 22:35:05,185 - freqtrade.freqtradebot - INFO - Checking depth of market for ETH/EUR ...
2021-01-23 22:35:06,607 - freqtrade.freqtradebot - INFO - Bids: 416.75851043, Asks: 243.89546928, Delta: 1.7087587221702245, Bid Price: 1013.321, Ask Price: 1023.888, Immediate Bid Quantity: 0.19464, Immediate Ask Quantity: 1.11714599.
2021-01-23 22:35:06,609 - freqtrade.freqtradebot - INFO - Bids to asks delta for ETH/EUR DOES satisfy condition.
2021-01-23 22:35:06,610 - freqtrade.freqtradebot - INFO - Executing Buy for ETH/EUR.
2021-01-23 22:35:06,611 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-01-23 22:35:11,168 - freqtrade.wallets - INFO - Wallets synced.
```

**Comment by Pascal66** [comment]
Prefer to read the code it can be understandable all around the world.
how it actually work with all : 
```
toTrade = (balance+capital in trade) * 0.98 (tradable_balance_ratio) = 84.24
allowed_capital_at_risk = toTrade * 0.333 (allowed_risk) 84.24*0.333=28.05
```
this must give with a stoploss of 0.03 
`position_size  = min(allowed_capital_at_risk 28.05 , 28.05/0.03=935) ` 
and not
`position_size  = min(free_capital 84.24, 28.05/0.03=935) `
https://github.com/freqtrade/freqtrade/blob/9a3c425cf408f2eacc7c16856bfe605ed7caaf0f/freqtrade/edge/edge_positioning.py#L162
like it does
`freqtrade.freqtradebot - INFO - Found open order for Trade(id=124, pair=ETH/EUR, amount=0.08313203, open_rate=1013.32100000, open_since=2021-01-23 21:35:09)`

**Comment by Pascal66** [comment]
Sorry if edge part doesnt fit to the actual things and related to a different programmers.

But the the doc says inverse as the code, and you ask to read the doc until I fully grasp it ?

I know how to drive a car, I dont ask you if you use Michelin or Brigeston, it's your choice.

You gave me a car, take care of what part you done on it

**Comment by xmatthias** [comment]
Don't feel upset because no one responded here for a few days. This is no commercial project where you're paying for support, and i think you don't quite understand this.

It may be a bug, it might not be a bug - it will need further investigation.
If you find the solution, you are more than welcome to submit a pull request fixing it. It will also simplify investigation if it's really a bug, as we then know what you think is the right approach / calculation.


---

However, please understand that this is an open source project, with people donating their **FREE time** to work on it, and try to improve it.

I will therefore NOT accept statements like the one you made above (quoted below, so it's clear which part i find very offending).

> You gave me a car, take care of what part you done on it

This is an insult to everyone who EVER contributed to this project. 
Everyone who contributed worked on it in their free time. You have therefore NO right whatsoever to demand we fix this right away, or even investigate right away. It will be investigated when time allows.


I understand it might be a problem for you and you want it fixed right away - so how about trying to be helpful instead, and try to create a pull request trying to fix the issue? 
This will help you quickly, and will help others as well as the investigation is already done, and only needs validation / verification.

I will therefore ask you to change your tone here - otherwise i'll have to limit your possibilities open issues / comment here further.
Thanks for your understanding.

**Comment by Pascal66** [comment]
I'm not feel upset. You ask me (and other) each time to read the doc.
I just see that the doc, and your advise doesnt correspond to the code.

I expect to be a non six week rabbit, and when  there's something wrong, just accept it.

**Comment by xmatthias** [comment]
After investigating another issue, i think your problem comes from a bad setting of `allowed_risk`.

The `allowed_risk` does NOT refer to the complete position size per trade (similar to the combination of `stake_amount="unlimited", max_open_trades=3` in non-edge modes), but to the amount you're ready to **lose** during one trade.

You're setting `allowed_risk` to 1/3rd (0.33)  - which means you're willing to lose 33% of your account in one single trade.
However, to risk 33% of an account with a stoploss of 2% - you'll need to use quite some leverage.


If i open a trade with 100$ with a stoploss of 5% - then my capital at risk is 5% - and this is how this "allowed risk" is intended (and also [documented](https://www.freqtrade.io/en/latest/edge/#position-size) with math examples).

Your having `allowed_risk=0.33` will tell me that i'm allowed to lose 33$ with a stoploss of 5% - so to get to this, i'll need to invest a lot more than 100$, specifically 33$ (allowed capital at risk) / 0.05 (stoploss) - so i'd need to buy for 660$ which obviously i won't have in the account, so it's simply going "all in" on that trade.

By reducing `allowed_risk` to a proper value (most likely it'll be something < 10%) - you'll allow the calculation to work correctly.
