### ISSUE TITLE
Derived strategies

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#4279]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.5 (`python -V`)
  * CCXT version: 1.40.86 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.12 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
How do I import MyAwesomeStrategy in order to write my derived strategy MyAwesomeStrategy2, like in [this documentation page](https://www.freqtrade.io/en/latest/strategy-advanced/#derived-strategies)? Assuming both in user_data/strategies/
Thank you.

#### Edited - some follow up 
I've tried ```from user_data.strategies.myawesomestrategy import MyAwesomeStrategy```, getting the ```No module named 'user_data'``` error.
However, if I ```import ipdb``` before the above from...import statement, everything went alright.
This is very strange to me. There must be a more freqtrade-style way of deriving strategies without using a third party module.

**Comment by xmatthias** [comment]
interrestingly, the above works for me (under certain circumstances which are however default) - which honestly surprised me a bit.


The documentation takes a very simple approach and doesn't comment on this for now - so it basically assumes both strategies are in the same file.

---

Your import (`from user_data.strategies.myawesomestrategy import MyAwesomeStrategy`) assumes that the file with MyAwesomeStrategy is called `user_data/strategies/myawesomestrategy.py` (if upper/lowercase is different this will fail).

It will also depend how you installed freqtrade - assuming you used `pip install .` instead of `pip install -e .` - then it'll also fail (as the search-path is now different).

on top of that, your user_data must be in the cloned freqtrade directory (using `--userdir ../whatever/` will NOT work). if you use `--userdir user_data` it'll work (if the above is fullfilled).


the easiest way to make this work "kindof" reliable is by manipulating the search-path to include the strategy's directory.

``` python
from pathlib import Path
import sys
sys.path.append(str(Path(__file__).parent))

# assumes the original file is `myawesomestrategy.py`
from myawesomestrategy import MyAwesomeStrategy

```

**Comment by kumkee** [comment]
> It will also depend how you installed freqtrade - assuming you used `pip install .` instead of `pip install -e .` - then it'll also fail (as the search-path is now different).
> 

On my local machine, I installed by `pip install freqtrade`. Would that fail me too?

I'll try your pathlib solution on both of my local machine and remote Docker image. If it is successful, I'll come back and report it here.

**Comment by xmatthias** [comment]
yes, that will fail too - it'll ONLY work for a linked install.

as said, the doc is clearly not complete in this regards ...

**Comment by kumkee** [comment]
The pathlib trick works on docker image as well. Please update the documentation accordingly.
