### ISSUE TITLE
Persistence when manually changing a balance at the exchange

### ISSUE THREAD

**Issue by drpaprika** [freqtrade/freqtrade#4299]
Hi,

How does Freqtrade's database management deal with the event when the user manually changes a balance in Binance (for example we bought/sold BTC or received from/send to other sources) ? 

For example, let's say that I want to trade on ETH/BTC. I start trading with 1 BTC on January 1st. On February 1st, I have 3 BTC : I realize that my strategy is good (+300%) and I decide to manually buy more BTC. I buy 10 BTC, so now my balance is 13 BTC.

I could also give the example when the user withdraws BTC from the exchange.

- Does Freqtrade detect it automatically or does the user needs to manually update the values ?
- How are the profit/loss updated ?

Thank you,
DrPaprikaa

**Comment by xmatthias** [comment]
withdrawals / deposits in stake currency don't really matter, and `/balance` will pick them up either after trade-action, or after at least an hour.

Profit/loss calculations are based on trades, not on the account (so you can have 10 BTC - but really only allow the bot to trade 1 BTC - it won't matter for the calculations).

It's a bit trickier if you "steal" the bot's trades (say it buys 1 ETH - and you sell that ETH manually on the exchange).
Then you'll need to update the database manually removing the trade (or inserting the sell-price) - otherwise freqtrade will not pick it up.
To PROPERLY handle this, don't sell it manually, but use `/forcesell`.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
