### ISSUE TITLE
Wrong convertion BTCST/BTC

### ISSUE THREAD

**Issue by severe-hed** [freqtrade/freqtrade#4307]
When calling /balance command in Telegram bot:
BTCST:
 Available:  0.00486000
 Balance:  0.00486000
 Pending:  0.00000000
 Est. BTC:  2.47001423

Seems like wrong formula used: 2.47001423/0.00486 = 508,2333806584
But actual price is 0,0019676 what is 0.00486/2.47001423

**Comment by xmatthias** [comment]
i didn't know that such a pair existed ...

leaving that aside, i guess the problem is that the pair name starts with the stake currency.

https://github.com/freqtrade/freqtrade/blob/6c87c498716cf0f32de07dbb84615c0d3a276cd3/freqtrade/rpc/rpc.py#L451-L456

seems easy enough to fix i hope - most likely by using something like 
`pair.startswith(stake_currency) and not pair.endswith(stake_currency): ...`

**Comment by xmatthias** [comment]
should work now on develop ...
