### ISSUE TITLE
Cartesian / brute force product for a config.json [Question - Enhancement ]

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#4312]
# Cartesian / brute force product for a config.json

Is there any Hyperopt method to make some **_Cartesian / brute force product_**, to generate all the possible combinations and show the best of the results for the existing parameters in the` config.json` file?

I've been looking, but I don't see anything unless you develop it yourself.

**Comment by xmatthias** [comment]
I'll see this as a question for now.

you can optimize certain parameters (like trailing stoploss, roi).

It's not possible for the full config - but that wouldn't make sense either, as most parameters only have influence once you run in production, not for backtesting, so you can't really test them either (like a timeout - you'll never encounter order timeouts in backtesting or dry-run - so how would you want to determine the "best" setting for these in a test environment)?

**Comment by Cazs03** [comment]
I understand that the configuration is only loaded at startup.
But the way is to have somehow like you can backtest with different parameters over and over again, it returns different values.

In Hyperopt mode, it returns the best stoploss, roi, etc.
But in the same way but evaluating only the parameters defined to obtain the best "**Profit, Lower losses, Avg trades ...**"

In the end, you can run different configurations yourself and analyze the data obtained based on what you are looking for.
But it is a long and tedious task.

**This would be something different from Hyperopts.**
In the end and only assuming this should have influence on production once one is comfortable with the "parameters" that have been found.

**Comment by Cazs03** [comment]
At the moment I had thought of the simplest values as `true / false` and with a single objective as indicated `"Profit, Lower losses, Avg trades ..."`

**Comment by xmatthias** [comment]
All values that can be updated in hyperopt can be found in the [documentation](https://www.freqtrade.io/en/latest/hyperopt/).

For now, it's unclear which parameter specifically you'd like to modify that also have an impact to the result - as said, 90% of the parameters are for live / dry only and don't change the results of backtesting, and the ones that do can be set via the strategy as well.

New spaces can be added with "relatively" low effort - however i don't see which parameters cannot be optimized at the moment that would also make sense.

**Comment by Cazs03** [comment]
I understand what you tell me, for the moment, i will continue using the documentation for hyperopt.
However, the backtest above all these parameters:
`use_sell_signal sell_profit_only ignore_roi_if_buy_signal`

They seem to return different results among others.

However, I appreciate the assessment and your response, you can close the issue, if you consider it.

**Comment by xmatthias** [comment]
there's a problem with these parameters, which is why simply optimizing them might not be a good idea...
they're really "cheat" parameters in most cases - so even outside of a optimization, you should consider carefully if you want to use them, or rather improve your signals per se.


* `ignore_roi_if_buy_signal` - while ROI might be reached for this trade, the strategy is also saying to buy again now. While you can prevent this with Protections now - it's still a bad idea to sell on ROI if your signal is still valid (either your buy-signal is wrong - which means it's not worth much - or it's correct and you're giving up lots of profits).
If setting this to False improves your profits, then either your ROI is too low, your sellsignal is not good, or your buysignal triggers too often.

* `use_sell_signal` can disable the sell-signal completely. You can get the same result by not having any condition for your sell-signal, which (depending how you design your hyperopt) is easily doable.

* `sell_profit_only` is a cheat, really - as your sell-signal is either valid (which tells you to "sell now, this market will go down") - or it isn't (in which case you shouldn't use it anyway.
Chances are, if you need to use this, you'll hit stoploss more often (unless it's insanely wide so it doesn't trigger too often) )

**Comment by Cazs03** [comment]
Thanks for the deep explanation about the differences, I understand that the development of this functionality does not imply a possible improvement.
For my part I can conclude this thread.
