### ISSUE TITLE
Get dust trads 

### ISSUE THREAD

**Issue by xdubx** [freqtrade/freqtrade#4324]
## Describe your environment

  * Operating system: Raspbian 10
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: ccxt==1.40.99(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1 stable (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Sometimes the bot create dust. I don't understand why. So my bitcoin get Split in the current coins so I don't geht my full trade amount. Iam using Binance. For example : 

🔵 Binance: Buying DNT/BTC
Amount: 51.30696933
Open Rate: 0.00000442
Current Rate: 0.00000442
Total: (0.000227 BTC, 7.394 EUR)

✳ Binance: Selling DNT/BTC
Amount: 51.00000000
Open Rate: 0.00000442
Current Rate: 0.00000443
Close Rate: 0.00000443
Sell Reason: sell_signal
Duration: 0:20:47 (20.8 min)
Profit: 0.03% (profit: 0.00000006 BTC / 0.002 EUR)

Now I have  0.30696933 DNT dust und blocks a small amount bitcoin. 

It's because a trade for the value  51.30696933 are not possible or why something like that happened?

**Comment by xmatthias** [comment]
you either don't own BNB, or have BNB fees disabled on binance.

Binance will therefore subtract the fee from the "target" currency - which will usually result in the last "bit" to be unsellable due to minimum lot sizes.

Freqtrade will use this dust eventually in future trades (should it decide to ever buy DNT again) - however it'll be a slow process and it'll probably never zero out completely.
The better alternative: convert all dust you got to BNB, enable BNB fees, and buy some more BNB so the bot can benefit from the reduced BNB fees.


Side note:
This is not related to freqtrade, would you buy manually on the exchange, the exact same thing would happen if you don't use BNB fees.

**Comment by xdubx** [comment]
Thx. Yes with BNB fees the problem is complete away :)
