### ISSUE TITLE
Get the last price of coin -ticker['last']- not working correctly

### ISSUE THREAD

**Issue by ozandem** [freqtrade/freqtrade#4328]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7
  * CCXT version: 1.40.99
  * Freqtrade Version: develop-65459086
  
## Your question

**Purpose:** Buy the coin whenever above ema value.
![image](https://user-images.githubusercontent.com/69985262/107123970-c6dffc00-68b1-11eb-9431-5d7a484414e2.png)

**Try:** To bought in the red area we should get last price of coin whenever bot scan this coin.

```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['ema'] = ta.EMA(dataframe, timeperiod=100, price='close')

        if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ticker = self.dp.ticker(metadata['pair'])
                dataframe['last_price'] = ticker['last']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                 (dataframe['last_price'] > dataframe['ema']) &
                 (dataframe['high'].shift(0)<dataframe['ema'].shift(0))&
                 (dataframe['low'].shift(0)<dataframe['ema'].shift(0))
            ),
            'buy'] = 1

        return dataframe
```
`timeframe=1m  Coin list:80`

Using ticker['last'] as in doc, it should allow me current price. So I dont want the close price. What I want is whenever bot scan this coin get the current price and if this price above ema just buy. To be make sure it is first candle which is break ema I check dataframe['high'].shift(0) and dataframe['low'].shift(0) must be below ema.
 I am using shift(0) because shift(1) gets two previous candle.(Main reason if i get right I dont work with 'close' I work with 'last_price')
 
 **Problem:** Sometimes it is not buying in the red area. It is buying in next candle. And sometimes the price where it bought is below ema value.

Maybe I am doing something wrong or another approach might be more usefull.

**Comment by xmatthias** [comment]
i'd say it'll depend on the exchange you're using. 
while many exchanges do provide the "last" value, not all do (then it's None).

It's also not guaranteed to be updated 100% right in time - again, this will strongly depend on the exchange (and sometimes time).


Instead of using shift(0) - you can just not shift it at all (that's what shift(0) does) ... that'll be simpler (and i'm not sure how `shift(0)` is defined exactly, maybe this does something unexpected ...).

Also, since you're using 1m candles, timing will  become an issue as  you have many pairs (80 is quite many for a 1m timeframe, if you're using active calls, anyway). 

Consider that `ticker()` is an active call to the exchange - so you're doing that 80 times (once per pair) - which depending on rate-limit settings and your connection and the exchanges response time (api load...) can get you > 1 minute per bot iteration - so for pairs "later" in your pairlist, you might end up in the next candle.

there's really nothing Freqtrade can do for such a case, simply use fewer pairs ...

**Comment by ozandem** [comment]
I am using Binance for exchange and you are most likely right about 80 pairs. Because sometimes result is right sometimes not. As you mention there is nothing Freqtrade can do I will close the case. Thanks for your answer
