### ISSUE TITLE
Transform Buy/Sell price off the price the indicator goes off at

### ISSUE THREAD

**Issue by guaranaja** [freqtrade/freqtrade#4341]
I have notices that my indicators consistently go off within a certain % of where the coin actually tops out or bottoms, this is ok but I'm trying to thing of how I can get a little closer to the money. Is there a way to set the buy/sell a specific amount off when the indicator is flagged?

**Comment by xmatthias** [comment]
i have no idea what your question is, or what you would like to do.

I'm sure it'll make sense for you as you know what you'd like to do - but i don't.

Try to reformulate / write it in a clearer way.

**Comment by tech705** [comment]
I've tried everything even deleting new pipe yet I'm still flodded these
emails. Any solutions??

**Comment by xmatthias** [comment]
@tech705 you should be able to disable notifications in your github profile (so this only shows up in your github profile, not via email).

Alternatively, use "unwatch" at the VERY top of the github repository.

Both above solutions will require you to be logged into github with the right account.

**Comment by guaranaja** [comment]
Sorry, I tend to see RSI go off in my strategy roughly 1-3% above the bottom or below the top of the actual floor/ceiling. I would like to know if there is a way for freqtrade to check the current price when that goes off and set the actual buy or sell a set percentage off that current price. I appreciate you taking the time to follow up.

**Comment by xmatthias** [comment]
assuming with "RSI goes off" you mean that it's triggering a signal ... then you'll need to be careful.

Most indicators use the candle's close to calculate their values. While in charts, it may seem like it "crossed" in the middle of the candle - it's really only sure it'll cross once the candle is closed (before that, the close value could still drop below, causing the cross to disappear). 
This problem is called Repainting - and is quite common in tradingview strategies.

You can use the current price in your strategy (in live modes) as [documented](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum), but you cannot set the buy / sell price from the strategy at the moment (there's issues requesting that if you look around, but so far no one has taken the time to implement this).

**Comment by guaranaja** [comment]
Ok thanks!
