### ISSUE TITLE
Convert Kraken official data download to OHLCV

### ISSUE THREAD

**Issue by thisiscam** [freqtrade/freqtrade#4343]
## Describe your environment
(Not applicable)

## Describe the enhancement

Kraken officially has history data download available on google drive:
https://support.kraken.com/hc/en-us/articles/360047543791-Downloadable-historical-market-data-time-and-sales-

I was wondering the possibility to use this data directly, instead of using the very time consuming data-download command in freqtrade. 

To that end, I created this script (WIP) https://gist.github.com/thisiscam/59ddae2ba2348bc8b2f4358e596fbb46 that attempts to convert the csv dumps into OHLCV consumable by freqtrade. The code seems to work/run, but I haven't tested if the correctness of the conversion. 
I'm not really sure why freqtrade uses the API to download trade data for kraken -- maybe there's information that's missing from these data dumps so this approach will not work? 

If the maintainers of this repo have any interest in incorporating the code, please feel free to reuse any part of that script.

**Comment by xmatthias** [comment]
The obvious downside is that it's only refreshed once per quarter (i think) - so i think it's not very useful in general, as you'll miss up to the last 3 months.
Also the way `download-data` works (for kraken) prevents you from "filling" the remaining data.

If you are interested in incorporating this (and think others will find it useful), please submit a Pull Request which will add it directly.
We will then be able to look at it, eventually request changes or suggest improvements.

Please understand however, that I will NOT go hunting for other peoples code trying to incorporate it and identify eventual weaknesses, even if that code is posted seemingly complete (at first glance) to a github issue.

**Comment by thisiscam** [comment]
> Also the way download-data works (for kraken) prevents you from "filling" the remaining data.

Could you elaborate on this? Why is it not ok to combine the downloaded data dump with the streaming API data?

> Please understand however, that I will NOT go hunting for other peoples code trying to incorporate it and identify eventual weaknesses

I understand. Just posting it here in case someone finds it useful in the future :)
I might take a stab at integrating this, but since  it seems like backtesting is working for me now, that will be a lower priority to me. 

Feel free to close the issue!

**Comment by thisiscam** [comment]
> The obvious downside is that it's only refreshed once per quarter (i think)

I think that's mostly fine for backtesting. The current quarter can be fetched through API. My issue with the current setup is that downloading the full history will take approximately 6 days for me. Compare that to the Google drive dump download which just takes <1 min..

**Comment by xmatthias** [comment]
> Could you elaborate on this? Why is it not ok to combine the downloaded data dump with the streaming API data?

To download more than the last 720 candles from kraken, you must use the `--dl-trades` method (kraken does not provide more ohlcv history through their API).
This method will download the raw trades (a lot larger than regular OHLCV, and combined with kraken's insane rate-limits, data-download becomes very slow) and convert the raw trades to candles.
It'll do so for the whole period that's downloaded.

Therefore, by using your script, followed by `download-data --dl-trades (...)` with the intend to fill up the remaining data, would actually remove the converted csv data again, so you'd have to pick to either use this data, or the last few months.

Assuming a 5m timeframe, that'll give you at max a week of data.
Since you're downloading the data from the csv, which is updated quarterly, you'll be missing between 0 and 3 months (assuming they really update regularly) of backtest data, which is actually the most relevant data, as markets change all the time.


Ideally, the data should be combined / appended, however that's not currently the case and honestly, i have no plan / time in doing so for now.

**Comment by thisiscam** [comment]
I see. I think it might be easier to just merge the ohlcv files. 
I think my read of your post is that there’s nothing technically wrong with merging — it’s just yet to be implemented. That’s good enough for me to verify this, thanks!
