### ISSUE TITLE
Proposition strategy switch

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4344]
Hello guys,

I am experiencing some different backtest results from period over period, which is actually normal. But in my opinion it is quite difficult to backtest/forward test in these exceptional/extremely high volatile times. I am always struggling on the periods and timeframe I have to backtest, because I have some great returns from Aug 2020 - Now, for year 2020 I have still positive returns, but if I backtest on year 2019, it is extremely negative.

Would it be possible that you create for example 3 strategies: 1. If the market goes up by let's say 10%, we use strategy 1. 2. If there is 'no movement' over a particular period (market neutral), we use strategy 2. If the market is down by 10% we use strategy 3.
Would it be possible to implement that?
What a great improvement would that be?

Cheers,
Mathias

**Comment by xmatthias** [comment]
the simple answer is no.
How would we determine if the market goes up or down?
the problem is, there's no correct answer to this question - everyone will want to use a different indicator / method to determine what to use.

----

You got 2 options for this, either by running 3 bots (with 3 strategies) - each with the same "trennd" indicator checking for a exclusive option (see below).

You then combine your signals with this the following way:



``` python
# Strategy1
(dataframe['trend'] == 'up') & (...)
# Strategy2
(dataframe['trend'] == 'down') & (...)
# Strategy3
(dataframe['trend'] == 'side') & (...)
```

or, you combine it into one

``` python
(
    (dataframe['trend'] == 'up') & (...)
) |
( 
    dataframe['trend'] == 'down') & (...)
) |
(
    (dataframe['trend'] == 'side') & (...)
)
```


Obviously, both above methods assume that you got a indicator / method that determines trend reliably (everyone will disagree with that anyway, as everyone thinks differently on how to properly identify a trend - what timerange to look at, what pairs,  ...)

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by piratoskratos** [comment]
Maybe something useful would be a **/strategy _MyOtherStrategy_** command on telegram; something that let you switch to another strategy manually if you see that you are in loss since X day(s) and think that you need to move to another strategy.
