### ISSUE TITLE
Missing documentation about Pairlist Filters

### ISSUE THREAD

**Issue by cakeslice** [freqtrade/freqtrade#4350]
Here's some important questions that I didn't find an answer to in the docs:

With the exception of RangeStabilityFilter/VolumePairList, do any of the other filters refresh over time?
If they don't, are they triggered anyway if a parent filter refreshes?

Do the refreshes happen in backtesting too?

**Comment by xmatthias** [comment]
backtesting generates the pairlist once at startup (using data from right now - which is why VolumePairList is not allowed there - as that would introduce a systematic forwardlooking bias).
The real-time data needed for the filters is not available for historic periods for the most part, and changing the pairlist in the middle of backtesting would be very slow (and is not possible with the way backtesting works either).


In general, all filters apply whenever the original generator (initial pairlist) refreshes - however some data will be cached as it doesn't make sense (for example the AgeFilter will never refresh - if a pair was available once, it'll always be available, as the "available date" cannot become lower over time).

**Comment by cakeslice** [comment]
Thanks!

What about pair refreshes in the middle of the list, in live/dry trading like this:

```
{ "method": "StaticPairList" },  # Won't refresh
{ "method": "PrecisionFilter" },  # Won't refresh
{
  "method": "RangeStabilityFilter",  # Will refresh
  "lookback_days": 10,
  "min_rate_of_change": 0.05,
  "refresh_period": 1440
},
{ "method": "SpreadFilter", "max_spread_ratio": 0.005 },  # Will be reapplied if RangeStabilityFilter refreshes?
{
  "method": "PriceFilter",  # Will be reapplied if RangeStabilityFilter refreshes?
  "max_price": 200,
  "min_price": 0.03,
  "low_price_ratio": 0.01
},
{
  "method": "VolumePairList",  # Will refresh. Will be reapplied if RangeStabilityFilter refreshes?
  "number_assets": 100,
  "sort_key": "quoteVolume",
  "refresh_period": 1800
},
{ "method": "PerformanceFilter" }  # Will be reapplied if RangeStabilityFilter or VolumePairList refreshes?
```

**Comment by xmatthias** [comment]
for volumepairlist - the refresh only applies to list generation - not on filtering.

For RangeStability - it'll always apply (so in your case it'll refresh every 1440 seconds).

In general, you shouldn't configure different refresh periods for different filters - that will make your result flucky at best - as some data will be based on "right now" - while others will be based on data that's a few hours old.
