### ISSUE TITLE
Edge uses up all the funds available in the account - completely ignoring tradable_balance_ratio

### ISSUE THREAD

**Issue by clintonmagro** [freqtrade/freqtrade#4353]
## Describe your environment
  * Operating system: Windows 10 using Docker to run
  * Python Version: Whatever the docker-compose uses I am not doing any changes
  * CCXT version: Whatever the docker-compose uses I am not doing any changes
  * Freqtrade Version: freqtrade 2021.1 (docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I deposited 200eur worth of BTC in my Binance account. I spun up an instance of FT using Docker with the configuration as below. I noticed that when I had `tradable_balance_ratio` anything other then `1` I was getting an error that the available amount is less than the stake amount. In fact the stake amount was always ALL the BTC available in my account. I noticed when I set balance ratio to 0.5 the error would say "Available funds is <half the BTC> available but stake is <all the BTC>

### Steps to reproduce:

Start FT with the following settings:
 * "tradable_balance_ratio": 0.5    //anything but 1
 * "stake_amount": "unlimited"    //because this makes sense - it is calculated by edge
 * "max_open_trades": -1             //again makes sense - auto calculated

edge settings
* "allowed_risk": 0.4
* "stoploss_range_min": -0.01
* "stoploss_range_max": -0.05
* "stoploss_range_step": -0.001
* "minimum_winrate": 0.35
* "minimum_expectancy": 0.02
* "min_trade_number": 40
* "remove_pumps": true
* "max_trade_duration_minute": 1440
    
### Observed Results:

  * What happened? edge wants me to use all my funds when trading
  * What did you expect to happen? when tradable_balance_ratio is set to 0.5 I expect edge to calculate whatever stake but not more then 0.5 of my account. ie: a stake cannot be bigger then the tradable_balance_ratio. This is really useful because I run 2 instances of FT and both are tradable_balance_ratio=0.45 and that means they can work in harmony without overstepping, leaving 10% spare just in case there are rounding issues and whatnot.

**Comment by xmatthias** [comment]
I think the main cause for this is your "allowed risk" parameter.

The default for this is 1%. While this might be a bit low depending on your account size, setting this to 0.4 (40%) will cause odd effects.

This is not your maximum position size, but how much capital you're going to risk.

The below is also described in detail [in the edge docs](https://www.freqtrade.io/en/latest/edge/#position-size) - but maybe an example with $ instead of ETH will make it easier to read ...

Say your account is 1000$ - and your "allowed risk" is 40% (as are your settings above).
edge will calculate the stoploss of - say 2%. 

Capital at risk will therefore be 1000 * 0.4 - which is 400$.
now the problem is - to lose 400$ to a 2% stoploss, you'd have to invest 20.000$.
Obviously you don't have this - so the position size is "all in".

In this combination, there is a slight bug  disrespecting `tradable_balance_ratio` - and therefore opening the position with 2000$ instead of the 1000$ you allowed the bot to use - however the bigger problem will be your position size, as the bot will go "all in" all the time.

**Comment by xmatthias** [comment]
the "over-spending" (more than tradable_balance_ratio) won't happen with the latest develop as of aa79574 - but it'll still go "all in" due to your configuration.

**Comment by clintonmagro** [comment]
Hi xmatthias, thank you for clarifying. I now have the following configuration:

"allowed_risk": 0.01
"minimum_winrate": 0.35
"minimum_expectancy": 0.02

I can confirm that it made 2 trades now and that the value chosen is not ALL IN.
Very cool indeed! Thank you Sir! :)

I think you can safely close this ticket.

**Comment by xmatthias** [comment]
Great, thanks for your feedback!
