### ISSUE TITLE
custom stoploss & backtest

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4357]
## Describe your environment

  * Operating system: __ubuntu 20.04__
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: __last___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __develop__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Simple question, is custom stoploss in strategy taken in consideration when doing a hyperopt or backtest?
Thank you in advance.

**Comment by zn3x** [comment]
In backtesting yes, you are essentially testing your strategy against market historic data.
In hyperopt, you are the one who decides `stop_loss` in your hyperopt using `stoploss_space()` function, hyperopt objective is to find the suitable strategy to your needs (including stop_loss), you can of course make a fixed stop_loss in your hyperopt if you want. 
Take a look at the documentation for more info

**Comment by xmatthias** [comment]
in short - yes it's supported (otherwise the docs would mention it's not).

Stop is a tricky part with hyperopt  - you shouldn't combine trailing-stoploss with custom stoploss - so it'll work fine UNLESS you optimize also for the trailing space.
Then it'll also (kindof) work - but trailing and custom stoploss will compete - and the one "closer" to the current price will be set (stoploss never moves away from current price - then it would remain where it is).

**Comment by rylos** [comment]
Perfect thank you.
I'm not using trailing space in hyperopt as I use custom stoploss in strategy, so hyperopt is forced to use it. I use only roi and stoploss spaces.

**Comment by xmatthias** [comment]
Then you're all good 👍
