### ISSUE TITLE
Difference between amount and amount requested in the trades table?

### ISSUE THREAD

**Issue by varunrai** [freqtrade/freqtrade#4363]
Noticed there are two columns in the database table trades - amount and amount_requested both of the columns have the difference in the decimal precision (see the attached image below). What are the differences between the two columns?

![image](https://user-images.githubusercontent.com/1327311/107857314-ba871080-6e68-11eb-9fd8-cfe223001e05.png)

When selling the bot is using the amount column which would be different from the actual amount bought on the exchange. This eventually results in a lot of residual amounts across the traded currencies. The accumulation can become significant over time.

**Comment by xmatthias** [comment]
amount_requested is the mathematical amount (stake_amount * open_price for limit orders).
amount is what you got (rounded to the exchange's precision.

the residual amounts happen due to fees (they are called binance dust, usually).
On binance - if you don't own BNB (or have BNB fees disabled), the exchange will deduct fees from the receiving currency.
So you buy 100 XRP/BTC - but you only get 99.9 (assuming 1% fee).
You can however only sell full XRP's - so you can only sell 99 XRP.

Freqtrade can't do anything in this regard - however it'll eat into the dust with future trades of the same pair - however it's unlikely that it'll ever even out.

to avoid them:
* buy BNB 
* make sure BNB fees are enabled
* convert the dust you got to BNB to get rid of it

Freqtrade will then use the BNB's you have in your account for future fees.

**Comment by varunrai** [comment]
that makes sense. 
I will check the configuration on my account as i recall, i do have some BNB. May be the BNB fees is disabled. 

Thanks for your quick response.

**Comment by xmatthias** [comment]
You should be able to see the fee currency in the database (or also in the trades history of the exchange)
