### ISSUE TITLE
Force sell if profit & disable stop loss commands

### ISSUE THREAD

**Issue by MetalDroid** [freqtrade/freqtrade#4364]
Hi, I don't know if this is the best way to make suggestions, if not, sorry!

**First suggestion:** /sell_all_profits command (or other name)

I put in situation: Suppose we have multiple open trades and several positives, But we have analyzed the market and we believe that everything is going to the underworld.

This command would serve to close all the positive trades before a major misfortune occurs. The rest of the trades would continue to work.

**Second suggestion:** /cancel_sl <trade_ID> | all

In this case suppose we see a price drop in a trade, but our analysis indicates that sooner or later it will recover.

The command would allow us to deactivate the stop loss selectively or globally if our manual analysis was correct.

Currently the only way I have found to do this is by deleting the trade and controlling it from the exchange, but it is somewhat unwanted, since I think we prefer to have control from the bot.

I wish I could contribute in another way, but I have never programmed in python. I'm sorry

Greetings

**Comment by xmatthias** [comment]
For the first - i think we're covered.
you can use `/forcesell <tradeid>` or `/forcesell all` to sell trades.
By using `/forcesell <tradeid>` - you've even got more control, as you can sell only 2 of the 5 trades, as the others may not be going down based on the analysis.

---

For the second:

It's called stoploss for a reason.
It'll protect your assets. if you want to move without stoploss, then use a very wide stoploss (-1 or more) - and have a good sell signal selling eventually.

However, we will under no circumstance allow users to disable stoploss - as that's a receipt for desaster.

**Comment by MetalDroid** [comment]
Regarding the SL I understand your point, although I will try to improve the explanation for the first suggestion:

I think that command would serve for stages in which the entire market falls, and we could avoid many potential losses by forcing the closure of all winning trades.

For example today much of the market fell, having 60 active trades, 20 were positive at that time but they ended up accompanying the market and they fell too.

The `/sell_all_profits` option would have allowed us to close those 20 positive trades at once since one by one it is a slow and dangerous process especially if the profits per trade are less than 2%.

Before I forget, thank you very much for your great work, it is a software wonder 👍

**Comment by xmatthias** [comment]
but you're pointing out the biggest problem on this already.

it's very specific to your needs / desires - but you might only want to sell trades above 2% ... 
the next might want it for all trades that are between 2% and 10% trades, letting everything above that run on in hopes that it'll recover.

others might want to sell only negative trades, letting positives run ..., or exclude a single trade because i belive that REEF/USDT (random pair, no investment advice!) will be successfull, even if all other trades fail.

using `/focesell <tradeid>` will give you this flexibility, by deciding for yourself which ones to sell.


I guess you can come up with a script using the API that does what you ask specifically - but i don't see it as part of freqtrade itself, as you can't even make this configurable - it'll depend based on the situation you're in, and we can't possible account for all these scenarios.

**Comment by MetalDroid** [comment]
Thank you, you have made me think about all this and you are right, It could lead us to make bad decisions for fear of losing and the reality is that the strategies are designed so that we lose that fear and let the bot work for us

I close the topic 👍
