### ISSUE TITLE
Parallel strategies on same machine could cause problem ?

### ISSUE THREAD

**Issue by ericrv01** [freqtrade/freqtrade#4378]
## Describe your environment

  * Operating system: XUbuntu V20.04
  * Python Version: Python 3.8.6
  * CCXT version: 1.39.79
  * Freqtrade Version: 2020.12
  
## Your question
Hello,

My question is related to running two strategies / bots in parallel on one machine? #1768

I'm currently running 2 instances of freqtrade on one server, each one having its database and config file.
One is working with usdt, the other one btc, with different pairs.
All is fine.

In the issue 1768, it's said that we should'nt configure the same currencies or pairs (and I want to do that)
Could you please explain why it's a problem, and if the problem can be solved with 2 machines?

Many thanks, your soft is awesome !

Regards

Eric

**Comment by xmatthias** [comment]
it's an issue that's almost 2 years old ... 

As long as you don't trade the same currency (both trade USDT pairs) - you should be fine. 
Also this works, but in that case you could not use dynamic stake (`stake_amount="unlimited"`) - as then your calculations would be wrong.

The only thing i'd do is to exclude BTC/USDT, otherwise (depending on the config) - the BTC bot may use the assets the USDT bot created to trade - which will cause failures in the USDT bot, as there won't be anything left to sell.
