### ISSUE TITLE
Add Additional Configuration Items to Hyperopt Spaces

### ISSUE THREAD

**Issue by werkkrew** [freqtrade/freqtrade#4380]
I am hesitant to work on this myself given my experience with python but I am suggesting an additional "space" be added to the hyperopt process to cover the following configuration parameters that can have a dramatic effect on strategy performance:

```
    use_sell_signal = True
    sell_profit_only = False
    sell_profit_offset = 0.0
    ignore_roi_if_buy_signal = True
```

In taking a look at the code it seems like the existing hyperopt class would be really easy to extend in this way.

I envision a default search space just as there is with stoploss, trailing, and roi_space which can be overridden in the user stoploss as such:

```
    @staticmethod
    def config_space() -> List[Dimension]:
        return [
            Categorical([True, False], name='use_sell_signal'),
            Categorical([True, False], name='sell_profit_only'),
            Real(0.001, 0.05, name='sell_profit_offset'),
            Categorical([True, False], name='ignore_roi_if_buy_signal')
        ]
```

**Comment by xmatthias** [comment]
i'm honestly not sure about the value of optimizing these.

While they can have a rather big influence on your strategy results - they're really only crutches covering up weaknesses in a strategy, so if you optimize these (or combine this optimization with other spaces) - you'll create a huge search space - where half of the things will be changed but won't apply (e.g. use_sell_signal=false and optimizing sell signal).

I've listed the downsides one by one not so long ago https://github.com/freqtrade/freqtrade/issues/4312#issuecomment-773288467

**Comment by werkkrew** [comment]
Ok, just thought I'd put it out there. If you and others ultimately decide its not a good thing - I trust your judgement.

**Comment by xmatthias** [comment]
i see them as cruches - your sell signal is either good - or it isn't (say you sell when you're > upper Bollinger band - you're either above and should sell - or you aren't and you shouldn't sell).
The market won't change it's further actions just because you're still red - so it's often (with good sell-signals, anyway) the case that by not selling even if the strategy tells you, you run into a stoploss.



I'll add it as enhancement for now ... but personally, i probably won't work on this for quite some time (that doesn't mean others can't pick it up and submit a pull request for it).

**Comment by werkkrew** [comment]
After spending more time with Freqtrade I now no longer see the value in doing this and will be closing this request.
