### ISSUE TITLE
stake_amount and tradable_balance_ratio?

### ISSUE THREAD

**Issue by IHateNameStealers** [freqtrade/freqtrade#4400]
I'm still uncertain what the correct setting needs to be for the "stake_amount" and "tradable_balance_ratio".

Lets say that I have USD $200 in my Bittrex account, and no trades going.
Now I do not want Freqtrade to use only $100, and use it for max 2 open trades.
I have set the "max_open_trades": 2, and I think that this is correct.
Now what does the  "stake_amount" and "tradable_balance_ratio" needs to be set to?

Thank you for any info on this.

**Comment by xmatthias** [comment]
I think the [documentation](https://www.freqtrade.io/en/latest/configuration/#configuring-amount-per-trade) should explain this quite well...

you can either use 2 static stakes of 50$ (tradable-balance_ratio will not matter unless your total balance were 100$.
Alternatively, you can allow the bot use dynamic stakes.

by setting `tradable_balance_ratio` to 0.5, you're allowing the bot to use 50% of your total balance, and with stake_amount=Unlimited, it'll use half of your account for this.

It's however not guaranteed to use 100$ - assuming it loses the first 2 trades, it may only use 95$ of this (because the total balance is now 190$).
Stake size will also be affected by anything else you do with the account - say you manually trade the 100$ the bot is supposed not to touch - then the 50% will apply to the remaining 100$ - and the next stake will be 25$ - as now 50% of the wallet is 50$ - no longer 100$.

**Comment by IHateNameStealers** [comment]
All clear now. Thank you.

**Comment by IHateNameStealers** [comment]
Sorry to bother you again, but for some reason I'm now getting warnings that the stake amount is to small.
I've got $150 USD available, and have set max_open_trades to 2, stake_amount to unlimited, tradable_balance_ratio to 0.5
The warning is for ADA/USD, and many more "currencys"
So basically Freqtrade has $75 USD to trade with.... Or.. Am I missing something here?

```
{
    "max_open_trades": 2,
    "stake_currency": "USD",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.50,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },

```

```
2021-02-19 16:49:56,728 - freqtrade.wallets - INFO - Wallets synced.
2021-02-19 16:49:56,739 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.5864317725500143 ...
2021-02-19 16:49:56,739 - freqtrade.freqtradebot - INFO - Executing Buy for ADA/USD
2021-02-19 16:49:56,740 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-02-19 16:49:58,225 - freqtrade.freqtradebot - WARNING - Can't open a new trade for ADA/USD: stake amount is too small (0.5864317725500143 < 27.844500000000004)
```

**Comment by xmatthias** [comment]
this would suggest that your balance is not 150 USD, otherwise i don't see why you'd get a price this low.

what does `/balance` show you?

**Comment by IHateNameStealers** [comment]
```
EUR:
 Available:  51.54029542
 Balance:  51.54029542
 Pending:  0.00000000
 Est. USD:  62.53372412
USD:
 Available:  150.71687548
 Balance:  150.71687548
 Pending:  0.00000000
 Est. USD:  150.71687548

Estimated Value:
 USD:  213.25059960
 USD:  213.25
```

**Comment by IHateNameStealers** [comment]
Got it working after deleting the tradesv3.sqlite db file (and stopping / staring Fregtrade again)
I've got no idea if deleting the file had anything todo with it.

**Comment by xmatthias** [comment]
changes to the configuration are not applied "live" - but only when restarting (or explicitly reloading the configuration).

Deleting the database should not mater.

**Comment by IHateNameStealers** [comment]
Than I have no clue what fixed it. And yes I did restart the server after I made changes to the config file.
