### ISSUE TITLE
Binance "order not found" warning

### ISSUE THREAD

**Issue by thisiscam** [freqtrade/freqtrade#4403]
## Describe your environment

  * Operating system: macOS
  * Python Version: 3.9 (`python -V`)
  * CCXT version: ccxt==1.41.70 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-7a6b73c (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Using Binance, I sometimes see this warning message:
```
freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: XXX id: 1234567). Message: binance {"code":-2013,"msg":"Order does not exist."}"
```
This seems to be caused by the error discussed here:
https://dev.binance.vision/t/faq-error-message-order-does-not-exist/46/15.

@xmatthias I suppose you were involved in that discussion thread?
I'm wondering what is the resolution for this issue in freqtrade? Currently I'm seeing  DDosProtection backoff delays being applied and retries until the order is found? I'm curious if applying backoffs this way will actually cause delays in the system's strategy analysis?

**Comment by xmatthias** [comment]
it's quite simple - binance API can report wrong information (and Binance does admit it does, but think their API is still correct and performant).

Say you place an order (`create_order()`) - and then immediately fetch the order (`fetch_order()`) - then the fetch_order might not find this order for several seconds (i've observed it up to 1 minute, but i found other reports that claim delays of 5 minutes).

The "backoff" will slow the bot down for sure (it's waiting for the API to "refind" the order) - but i wouldn't know how to handle this differently, as we got NO information about the order - if the order filled, was it even accepted, cancelled, or is it still pending (or what else happened with it).

Now the backoff does not happen all the time, but only during high volume times, so it's not a problem 95% of the time.

Feel free to complain to Binance about their api performance - but as you've seen in the thread above - they simply don't care - so i've given up on this route (although i do think that as an exchange, they're legally obliged to return correct information via their API at all times, so you might be able to sue them about this - but i'm not interrested in legal battles ... )

**Comment by thisiscam** [comment]
> so it's not a problem 95% of the time

IMO that depends. High volume could sometimes mean high profit opportunities. 
--- now that's just theory, and I have no justification of how much of an impact this really is.

> The "backoff" will slow the bot down for sure (it's waiting for the API to "refind" the order) 

Would it be possible for us to avoid this behavior at all? Like, the bot should treat newly created order as "confirmed", unless at a later time it receives that the order is cancelled? Or perhaps there should be a "in-progress" state for order? 
I can implement this logic and PR if you think this is plausible.

**Comment by xmatthias** [comment]
that's what happens when placing the order anyway.

The problem starts one iteration later (by default ~5s) 
we need to check on the order and verify if it's still open, was filled, ....

The problem is - not finding an order can mean too many things to handle it correctly in all cases:
* the order was never placed / the API returned a wrong order_id so our order_id is wrong (this is very rare)
* the order was placed, but the API doesn't find it yet (this problem)
* the order was placed, the api finds it (but it's not filled yet) (no error yet)
  * Now you cancel the order manually on the exchange (maybe by mistake, maybe intentional)
    some exchanges will still return the order (but in a cancelled state)
    other exchanges, will return "OrderNotFound" - making the error identical to the error you're trying to fix.


The big problem is, there is NO difference in the error - as in all cases, the error is `OrderNotFound`.
It took me forever to find this solution (which didn't break all other usecases) - so if you think you're able to fix this - please consider all the above cases as well.

I don't think it's possible - now without  "fixing" one problem, we'd breakbreak it for the exchanges by assuming the order is still there (but the user cancelled the order in the meantime). 

I see the "cancelled on the exchange" problem as more severe.
for example  you sometimes "intentionally" cancel a stoploss order to force the bot to place a new one (i generally run with 60s, but if a pair moves quickly i'd like the bot to pull the order closer).

By "assuming" my order is still there (even though i cancelled it) - you're basically breaking trailing stop completely for this order - as it'll never cancel this order (it'll assume the order is there because you still get `NoOrderFound`- while it really isn't there anymore).

**Comment by thisiscam** [comment]
@xmatthias Thanks for the explanation, that helps clearing thoughts a lot.

> It took me forever to find this solution (which didn't break all other usecases) 

Just to confirm, the current solution is that we keep trying to find the order for 5 times? 
What happens if we cannot find the order even after the retries? The order is then considered lost? 

My understanding have led to the following solution:
1. An order should have a _processing_ state, which means that the order is submitted, but not _confirmed_ by one `fetch_order` call. In this state, the order's funds is "locked", just like a _confirmed_ order.
2. We should have a clock ticking for each _processing_ order -- say 5 minutes (could be configurable too). If a _processing_ order times out, the order becomes _cancelled_. 

In my view, this should be almost the same as the current solution, except that the timeout clock and the rest of freqtrade is allowed to run in parallel. 

Now regarding 

> the order was never placed 

This should cause the above timer just to time out.

> the API returned a wrong order_id so our order_id is wrong (this is very rare)

For a starter, we should just treat it as if the newly created order was never placed (therefore lead to a timeout), and another order is placed instead (i.e. just like the user manually placed an order on the exchange).

For a more advanced fix, we might be able to match with this "another order" by comparing timestamps, amount, price etc., and intelligently recover the lost order. 

Does this make sense?

**Comment by thisiscam** [comment]
Actually, I think I'm ok with changing this line https://github.com/freqtrade/freqtrade/blob/3629892fc35fec3b6daaa2938371d4c1614cbe32/freqtrade/freqtradebot.py#L969
to
```python
order = self.exchange.fetch_order(trade.open_order_id, trade.pair, count=0) # do not retry
```
I think this will still satisfy your use cases  while giving more time to other part of freqtrade? Since the fetch_order will be executed in the next 5s again anyways, and there's sort of no/little point in getting the order earlier than 5s later (also  I think DDOS backoff will also have that delay anyways).

Am I missing anything?

**Comment by xmatthias** [comment]
The backoff is incremental - in total (worst case) it'll wait for about a minute - but in almost all cases it works after the 2nd retry (which is about a 10s delay).

> Am I missing anything?

yes you are.

By not retrying, you'll get the "NoOrderFound" exception - which causes the bott to immediately assume the order as "not found / lost / cancelled" (basically as non-existant)- which will make the bot try to place the order again.

That'll be fine if you are
* 100% sure the network to the exchange will NEVER fail (it will - it's internet after all)
* you will never experience the bug above, and ALL your orders will be responded to immediately (CANNOT be the case, otherwise the backoff would be fine, as you'd never hit this).

Since the above things will not be the case - the consequences will be
* the bot buys the same asset again (you now own 200 XRP instead of the 100 you wanted to buy)
  *  the bot will NOT handle the first 100XRP, as it doesn't know it owns them
* on the sell side, it'll try to sell the asset again, running into "not enough funds" problems.
  * this should be handled by the "order refind" algorithm - but that's not intended to be used on a regular basis, only in exceptional cases) - so it'll slow the bot down significantly.

---

Feel free to give fixing this a try if you really wish the way you describe above - but your approach would:

* use the Order table more extensively - at the moment it's ONLY used to refind lost orders (and for informative purposes) - the orders table is not queried for anything beyond that
* properly implement this timeout (based on the order table - which will give you the order's post date)
* make sure this works for all ordertypes (market, limit, (on both buy and sell sides), stoploss on exchange)


It'll not be a 1 line fix, but most likely a few days of work to get it all aligned and working and tested properly (including tests, obviously).
Luckly, it should (most likely) be limited to the freqtradebot (and maybe models and exchange) class - not touching 100 files in the process (excluding tests)

**Comment by thisiscam** [comment]
My understanding is that when `trade.open_order_id` is not None, the bot will not re-create/duplicate an order?

For selling:
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/freqtradebot.py#L693

For buying:
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/freqtradebot.py#L369

Stoploss probably needs some other treatment, but note that Line969 is only for open_order (not stoploss order)

**Comment by xmatthias** [comment]
your links seems quite off ...

`open_order_id` will be set to None once `fetch_order` doesn't find the order.

**Comment by thisiscam** [comment]
> open_order_id will be set to None once fetch_order doesn't find the order.

Could you point me to where this happens? I did a global search and see that `handle_cancel_buy` is doing it.
But note that there is a `continue` here, which prevents `handle_cancel_buy` being invoked.
https://github.com/freqtrade/freqtrade/blob/3629892fc35fec3b6daaa2938371d4c1614cbe32/freqtrade/freqtradebot.py#L972

**Comment by xmatthias** [comment]
Please use a good editor and search yourself.

I'll not explain every line or where to find it - if you require that, then you'll clearly not be able to change any of this without breaking something else.

**Comment by thisiscam** [comment]
I'm not _requiring_ you do anything; I'm simply asking for a favor since you are more familiar with this project.
If you don't have the time/energy for this, that's totally ok.

I have changed to `count=0` and l think I'm seeing what I'm expecting. Thanks

**Comment by xmatthias** [comment]
It's as simple as doing a search for `open_order_id` throughout the project, and identifying where it's reset.
If you can't (or won't) do that yourself (but ask me again and again for it) - then it's simply a waste of time for me.

As said above, it'll not retry the query - however it'll also lose the order as `open_order_id` is reset in the process.
