### ISSUE TITLE
Use custom source for OHLC+VOL data for live modes

### ISSUE THREAD

**Issue by baswientjes** [freqtrade/freqtrade#4410]
## Describe your environment
(if applicable)

  * Operating system: Linux, but should also apply to others
  * Python Version: any
  * CCXT version: any
  * Freqtrade Version: new

## Describe the enhancement

Wouldn't it be nice to have FreqTrade read its OHLC and volume data (or any other if needed) from a custom source? Meaning: have a script (could be a FreqTrade instance, but any other script would work) download OHLC+VOL data to a database, and have several FreqTrade instances use this data source for trading.

This prevents every FreqTrade instance from gathering its own data from the exchange API, using up precious API calls (there are limits).

For instance: let one FreqTrade instance (or other script) gather OHLC+vol data for every whitelisted pair that is traded on an exchange into a database. Have any number of FreqTrade instances (be it Docker containers or otherwise) trade on that data, rather than have each instance gather its data on its own accord.

**Comment by xmatthias** [comment]
I'm sure this would fit your usecase (and you're probably also able to set this up), however the effort to implement this (and mainly to support this) will not be worth the time.

The main problem is probably not the implementation, but the (support) problems that will occur from this. Considering that most users of freqtrade are non-technical, we'd end up with 100ds of questions related to this, because it WILL be an operational challange to set this up properly.
Users will  need to make sure that the "main" instance is started first, that it's always available (otherwise the bot will simply stop trading) - that the main instance is reachable from the clients, ...

This is all no problem if you're technically capable for sure - but for a new user, this will be close to impossible to setup without support.


As this is a small, open source project, we'll not be able to handle this without burning out maintainers, so i'm sorry, but this is not an option.
In theory, you should be able to set this up with some custom proxy (which pipes requests to certain endpoints to other sources) - but it's not something we can support officially.

**Comment by biiiipy** [comment]
+1 @xmatthias 
The absolutely best solution is to setup a caching proxy, that will cache data requests and will work transparently for any bot

**Comment by SaidAlSouti** [comment]
is it possible to provide the ability to override the call for these data so we can use our own data source if we want to?

**Comment by xmatthias** [comment]
@SaidAlSouti no it's not - and and that's also not planned.

Keep in mind that this is also a 4 year old issue - which will now ping everyone for comments here (hence locking it to prevent further spam).
