### ISSUE TITLE
Out-of-core processing for Backtesting and maybe Hyperopt

### ISSUE THREAD

**Issue by scientes** [freqtrade/freqtrade#4427]
## Describe the enhancement

This may have come Form or another already but especially hyper-opt needs very much ram for large datasets, so that many have to reduce the amount of concurrent jobs or cannot train on larger sets of data. Using something like Dask to only load data thats needed for the optimization would be nice, as an optional feature.
Also for those not memory bound like me,using another joblib backend you can distribute the optimizations to multiple computers:
```python
from dask.distributed import Client
import joblib

client = Client(processes=False)             # create local cluster
# client = Client("scheduler-address:8786")  # or connect to remote cluster

with joblib.parallel_backend('dask'):
    # Your scikit-learn code
```
 [dask-ml](https://ml.dask.org/hyper-parameter-search.html#hyperparameter-incremental) also has some hyperparameter optimizations in a distributed fashion which may be an alternative. I'd gladly would want to develop this feature, but my understanding of this project is a bit limited to achieve something like this. 
 
 Note: Dask will be less efficient on small datasets, so this should be an optional feature at best.

**Comment by xmatthias** [comment]
i don't think dask will give you what you want.

we do only load the data in memory that's needed - so using dask would only use the memory in a different format - not really less (unless you run 1 dask process per machine - which however won't work with hyperopt).

The problem with hyperopt isn't backtesting per se (it's actually pretty fast once you remove the data-loading - which isn't happening in hyperopt more than once) - but it's not 100% parallelizable.
This means:

* load data (1 core)
* analyze data (1 core)
* start hypreopt (8 cores)
* after 30 epochs - start baesian serach
  * backtest (8 cores)
  * wait for all backtests to complete
  * baesian search (1 core)
  * backtest (8 cores)
  * wait for all backtests to complete


The real problem is the non-parallelizability of the skopt baesian search.
According to the skopt repository, it's really the algorithm that's not parallelizable, as it needs to account for all previously evaluated points, and find the next-best local minima (or direction towards the local minima).

dask-ml doesn't seem to support any advanced hyperparameter tuning (like baesian search) - unless i missed that HyperparameterTuner - but is basically doing a grid-search or random-search - which will underperform hyperopt by ages.

--- 

The much bigger problem with dask in my opinion is - while it may be powerfull and fast if setup correctly, setting it up correctly as a non-developer is non-trivial, which means most users of freqtrade will most likely fail with it.

It's also good at processing Tons of data in parallel (or only loading data that's needed) - however that'll not work with backtesting - as we need to load the full dataset - and then analyze it.
While in theory, we could ommit loading - say "high" if you don't use it - we don't really know that as the strategy is user-provided (oftentimes, users won't know themselfs, as many indicators take the whole dataframe).


The only point you could optimize with dask here is maybe the loading (it's pretty fast if you use hdf5) and analyzing (which is even faster, but depends heavily on what the strategy uses).

I don't think it'll be a good time investment - as rewriting what you would need to rewrite for this to work (without changing the user interface!) would take weeks of time - which is much better spent elsewise.

**Comment by scientes** [comment]
Thanks for the in depth answer!

**Comment by quantsirius** [comment]
All clear, thank you. But is there a way to finish Hyperopt with large datasets? I tested sample_strategy earlier for 2 years dateset. 32GB of RAM absolutely full after 3 hours. The Hyperopt almost stopped as system goes swap.

**Comment by xmatthias** [comment]
hyperopt in general will become slower the more epochs you run (That's part of the algorithm used).
Also, after a few 100 epochs, often the results won't improve much anymore - therefore we recommend to do multiple hyperopt runs with smaller lengths.

The duration will depend not just on the timerange, but also on timeframe and number of pairs used (you can easily hyperopt 5 years of 4h candles ...).
