### ISSUE TITLE
Failed to kill subprocesses on this platform. Pleaseinstall psutil

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#4439]
**Hello dear community,**

this issue is related to https://github.com/freqtrade/freqtrade-strategies/pull/127 I uploaded a few days before.

After 2 days and 3 remaining hours the hyperopt crashed. The details are listed below.

## Describe your environment

  * Operating system: `Ubuntu 20.04.02 LTS focal`
  * Python Version: `3.8.5`
  * CCXT version: `freqtrade docker-62885166`
  * Freqtrade Version: `freqtrade docker-62885166`

## Server Hardware Profile (it's a VDS (virtual dedicated server))

 * 3 physical cores
   * AMD EPYC 7282 2.8 GHz
 * 24 GB RAM
 * 180 GB NVMe SSD
 * 250 Mbit/s Port

## Steps to reproduce:

  1. The command I used to run this hyperopt:

`sudo docker run -d --name HO-SwingHighToSky -v ~/.freqtrade/configs/conf-ho-swing-high-to-sky.json:/freqtrade/config.json -v ~/.freqtrade/user_data/:/freqtrade/user_data freqtrade hyperopt --hyperopt HOSwingHighToSky --hyperopt-loss SharpeHyperOptLossDaily --strategy SwingHighToSky -e 12000 --spaces default --timerange=20210101- --eps --dmmp`

  2. You can find the strategy and hyperopt files I used here: https://github.com/freqtrade/freqtrade-strategies/pull/127
  
### Observed Results:

The hyperopt had run very well for two days with good results like `|   Best |  2173/12000 |      847 |    483  358    6 |        1.07% | 9,052.74835697 USDT  (904.37%) |      1,569.9 m |    -16.1652 |` but it crashed 3 hours before it would finished.

### Relevant code exceptions or logs

  ```
 [Epoch 11239 of 12000 ( 93%)] ||| [ETA:   3:27:33, Elapsed Time: 2 days, 3:05:17]
 [Epoch 11245 of 12000 ( 93%)] |/| [ETA:   3:26:00, Elapsed Time: 2 days, 3:08:22]
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 11250 of 12000 ( 93%)] |-| [ETA:   3:24:44, Elapsed Time: 2 days, 3:11:02]
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 11250 of 12000 ( 93%)] |\| [ETA:   3:24:44, Elapsed Time: 2 days, 3:11:02]
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 11250 of 12000 ( 93%)] ||| [ETA:   3:24:44, Elapsed Time: 2 days, 3:11:02]
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 11250 of 12000 ( 93%)] |/| [ETA:   3:24:44, Elapsed Time: 2 days, 3:11:03]
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 11250 of 12000 ( 93%)] |-| [ETA:   3:24:44, Elapsed Time: 2 days, 3:11:03]
2021-02-25 01:47:34,353 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 718, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 622, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
neo@vps:~$
  ```

**Comment by xmatthias** [comment]
let's leave out the fact that i don't believe it'll have found much better results after maybe 2000 epochs (it's Bayesian search, it'll be "stranded" in a local minima it probably won't find out again).
...


According to the internet, searching for this error (https://github.com/SCCAF/sccaf/issues/16) - it seems like it's a slightly different form of OOM errors, which fails to properly kill the processes.

Now the error seems to be fixed by installing psutil - however, it'll still be a out of memory error - it'll just (hopefully) be terminated a bit more gracefully.

**Comment by OtenMoten** [comment]
Thanks for replying this fast.

Do you have sources or more keywords regarding to "Bayesian search"?

So, a workaround would be that I add this line to my Dockerfile:

`RUN pip install psutil`

I will try and run again.

**Comment by xmatthias** [comment]
well it's a workaround that will change the error-message.

It will however not change the fact that it's running out of memory.

> Do you have sources or more keywords regarding to "Bayesian search"?

[Hyperopt docs](https://www.freqtrade.io/en/latest/hyperopt/) - 2nd paragraph

The main principle is that new points are calculated based on previous results.

it's similar to gradient decent in a way ... just the algorithm HOW to calculate the next point is slightly different.

Think about it as being a 3d map with peaks and valleys - you start at a random point (for hyperopt, 30 random points) - and then try to find the lowest point (calculated by the stoploss function).
you'll take the lowest point(s) - and try to move from there, hoping to go lower.
You'll move up some, you'll move down some (which will determine the further direction).

Unfortunately, you may end in a valley that seems to be the lowest point - but in reality, there'd be a different, deeper valley in a different point - but you're never getting there as all directions you move in will result in higher loss results.


Now the difficulty with hyperopt - it's not a 3d space, but a N dimensional map (depending on the number of dimensions you're trying to hyperopt).

By using fewer epochs - but running hyperopt multiple times, you'll start at different random starting points (unless you use the same --random parameter) ... which can give you completely different results - depending on the number of dimensions obviously).
That's why - in general - we recommend to only run hyperopt for 1-2000 epochs - but multiple times to get different starting points.


You can also use [this as visualization](https://www.researchgate.net/figure/Local-and-global-minima-in-CBGWO-based-on-the-naivenaive-Bayes-objective-function-Blue_fig3_334383183) to understand how this works in principle i guess - but it's the only the image i looked at - not any of the text (so please don't complain if it's not good).

**Comment by OtenMoten** [comment]
> well it's a workaround that will change the error-message.
> 
> It will however not change the fact that it's running out of memory.
> 
Could I avoid this with stock up the RAM or is this in generel a error in the software?
> > Do you have sources or more keywords regarding to "Bayesian search"?
> 
> [Hyperopt docs](https://www.freqtrade.io/en/latest/hyperopt/) - 2nd paragraph

Thanks.
> By using fewer epochs - but running hyperopt multiple times, you'll start at different random starting points (unless you use the same --random parameter) ... which can give you completely different results - depending on the number of dimensions obviously).
> That's why - in general - we recommend to only run hyperopt for 1-2000 epochs - but multiple times to get different starting points.

I wondered always about what's the best epoch size, solved. ;-)

> 
> You can also use [this as visualization](https://www.researchgate.net/figure/Local-and-global-minima-in-CBGWO-based-on-the-naivenaive-Bayes-objective-function-Blue_fig3_334383183) to understand how this works in principle i guess - but it's the only the image i looked at - not any of the text (so please don't complain if it's not good).


Thanks for this detailed explanation of this mechanism. I was informed by Mohsen's Udemy course about this and yet it's more clear to me.

**Comment by xmatthias** [comment]
> Could I avoid this with stock up the RAM or is this in generel a error in the software?

It's out of memory ... considering that ALL previous results must be kept in memory (12k in your case) - as well as the data to backtest (for each pair)  - including the parameters it tried already - memory consumption will raise with more epochs.

You can avoid it by limiting parallelism (-j <num>) - it'll default what your system allows - but you can limit it so it'll also take fewer memory.
