### ISSUE TITLE
Show the Trade ID in the Telegram message when an order is opened/closed.

### ISSUE THREAD

**Issue by Th0masL** [freqtrade/freqtrade#4443]
## Describe the enhancement

Hi :)

I was thinking that it would be useful to have the Trade ID written somewhere in the Telegram message when a Trade is opened/closed.

The current message are something like that :

Buy :
```
Binance: Buying TFUEL/USDT
Amount: 1434.94033573
Open Rate: 0.08637600
Current Rate: 0.08637600
Total: (123.944406 USDT, 102.451 EUR)
```

Sell :
```
Binance: Selling TFUEL/USDT
Amount: 1434.94033573
Open Rate: 0.08637600
Current Rate: 0.08727900
Close Rate: 0.08727900
Sell Reason: trailing_stop_loss
Duration: 0:30:28 (30.5 min)
Profit: 0.84% (profit: 1.04656656 USDT / 0.865 EUR)
```

I think it's not needed to add a new line, so it probably makes sense to add it on the line of the symbol, like that :

Option 1:
```
Binance: Buying TFUEL/USDT (#14)
Binance: Selling TFUEL/USDT (#14)
```
Option 2:
```
Binance: Buying #14 - TFUEL/USDT
Binance: Selling #14 - TFUEL/USDT
```
Option 3:
```
Binance: Buying Trade ID 14 - TFUEL/USDT
Binance: Selling Trade ID 14 - TFUEL/USDT
```

Other ideas on how to write it ?

It should be easy to do, so I can make a PR for that, just let me know.

Thoughts ?

**Comment by xmatthias** [comment]
i'm personally not really convinced about the usefulness of this ... what difference does it make if it's trade id 14, or trade id 25 that's beeing bought currently?

if any, then the shortest (so 1 or 2) ...

**Comment by Theagainmen** [comment]
I don't see any useful case for this too.. adding this in every message would add in 99% of the cases useless information to the message. Whenever I want to remove a trade or forcesell I just use /status table to get the ID. And even if this was added I'd still use /status table since I'd probably have to scroll up in the chat to find the buy/sell message with the ID..
If it was useful I would gladly look in implementing this :D

**Comment by Th0masL** [comment]
I understand that it might not be useful for most of the people, it's just that I had a specific case where I was trying to look at an historical data and I was trying to find what was the Trade ID of a specific trade that happened days ago.

How would you guys feel if we add an option in the telegram section of the config to allow user to eventually add more detail to the telegram messages ?

Like something like that :

```
    "telegram": {
        "enabled": false,
        "token": "your_telegram_token",
        "chat_id": "your_telegram_chat_id",
        "show_trades_ids": true
    },
```

**Comment by ozitrance** [comment]
:+1:  for this feature

It can be useful in some cases. For example, I wanted to query the database for a few interesting orders and then I realized there is no way to match an order from telegram to the database, unless you hit the /status button in the middle of the trade... 

Could also be useful for debugging and troubleshooting sometimes too.

**Comment by xmatthias** [comment]
> How would you guys feel if we add an option in the telegram section of the config to allow user to eventually add more detail to the telegram messages ?

as said, i'd prefer the "smallest" option (1 or 2).

Making it optional is ... kinda overengineered i'd think - while it might seem tempting at first (make everything optional ...), almost noone will care enough to actually change that setting, so it's probably time better spent elsewhere.

In the end, possibilities are quite high that you might change the default to disable this, only to regret it later should you EVER come across the need to use this - so while i'm not convinced about the need for this, i also don't think i'd change the default to disabled (simply because maybe it will come in handy at a later point).

**Comment by Th0masL** [comment]
Sounds good, then I will implement and test the option 1 on my side, and make a PR when ready :)
