### ISSUE TITLE
data-download from kraken requires more than 2GB RAM

### ISSUE THREAD

**Issue by anyn99** [freqtrade/freqtrade#4449]
## Describe your environment

  * Operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-66-generic x86_64)
  * Python Version: 3.8.5
  * CCXT version: 1.42.19
  * Freqtrade Version: develop-0bb80d14
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I have a system with 2GB RAM here.
I downloaded trade data from kraken using something like 'freqtrade data-download --dl-trades -t 5m --timerange 20210101-'.
Now everytime i try to load this historical data, e.g. by doing 'freqtrade data-download --dl-trades -t 5m --days 8',
the freqtrade process gets killed by kernel because of using up all my memory :-(

### Steps to reproduce:

  1. Get a chunk of trade data as json.gz
  2. Try to use it by downloading more, or try to convert it to json
  3. wait for oom
  
### Observed Results:
See above

### Relevant code exceptions or logs

Last line in freqtrade before it says "Killed"
  ```
2021-02-26 21:45:18,044 - freqtrade.misc - DEBUG - Loading historical data from file user_data/data/kraken/BTC_EUR-trades.json.gz
  ```
dmesg line after that
  ```
[  328.009746] Out of memory: Killed process 1513 (freqtrade) total-vm:2139844kB, anon-rss:1851456kB, file-rss:1896kB, shmem-rss:0kB, UID:1000 pgtables:4044kB oom_score_adj:0
  ```
size of file as json.gz is in the range of megabytes:
  ``` 
-rw-rw-r-- 1 xxx xxx 77009691 Feb 26 03:39 BTC_EUR-trades.json.gz
 ```

that looks like a bug, doesn't it?
Or do i have a chance when using more memory??

**Comment by xmatthias** [comment]
It's not freqtrade itself that's having a problem (not in trade mode) - but it's the data-download from kraken which must use trades-data and convert that to candles (because the kraken-api doesn't support historic ohlcv data).

This will load all trades for one pair into memory, and do the conversion for the whole timeperiod (which means, if you got 1 year of trades data, it'll load all trades for this pair into memory).

unfortunately, it's known that this will take a sizable amount of memory (you say the file is in the range of MB - it's 77MB zipped, if you unzip (`gunzip <file>`) it it'll be a lot more).

Now this whole data needs to be loaded into memory (unzipped!) and then converted to candles (which will again take a bit of memory).

The 2Gb estimate we specify on the site is for trading mode - not for all modes (e.g. hyperopt will not work on 2Gb). Download-data will also usually work unless you're on kraken (or another exchange that doesn't provide ohlcv data) - where the conversion has to take place on your machine.

I don't see this as fixable with a reasonable amount of time investment - and a 2gb machine will probably also not work correctly for backtesting either - so i'd suggest to use a machine with more power for "investigative" work (download-data from kraken, backtesting, hyperopt).

2Gb will be fine to run the bot operationally (in trade mode) - but not for the more labor-intensive work like backtesting and hyperopt.

**Comment by anyn99** [comment]
Thank you for clarifing this!

I can confirm that most of the times backtesting works fine with 4GB RAM, but for hyperopt sometimes more is needed.
It of course mainly depends on the timerange and number of currency pairs that are tested. ;-)
