### ISSUE TITLE
Are Market orders really that risky?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4453]
I have been doing some reading on Market vs Limit orders, and as I understand it, market orders will complete faster with a risk of not getting the wanted price, whereas limit orders are slower, because they wait for the correct price to be reached. This makes it more likely for a Market order to go through, while a Limit order will wait for the correct price.

This is the reason (I think) I have been getting a lot of messages like this one.

Binance: Cancelling Open <buy or sell> Order for <coinpair>. Reason: cancelled due to timeout

As a result, by the time a sell order is placed with a profit, a 30-minute timeout is long enough for the value of the coin to drop and the sale is never completed.

So, I am considering changing the configuration to Market orders and even setting the stoploss_on_exchange to true, to make things even faster.

```
"order_types": {
    "buy": "market",
    "sell": "market",
    "emergencysell": "market",
    "forcesell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 60
}
```

In the fiat stock market, a trader receives an order and then has to place it. That takes a few minutes and the price might change. This is why a Limit order is useful.

But with freqtrade, we might be talking about seconds from the time a signal is received and the order is placed.

**My question is:**

Is it really that risky to use Market orders, in this world of automated trading and high speed/low latency connections? And I assume using stoploss_on_exchange makes things even faster, which lowers the chance of the price significantly changing, from the time an order is placed, until it’s executed.

**Comment by xmatthias** [comment]
first of all, when using market orders, make sure to invert price-side too, otherwise roi / stoploss calculations will be off - as documented [here](https://www.freqtrade.io/en/latest/configuration/#market-order-pricing).


then, i don't think you fully understand the difference - also when manually trading, you can very easily use market orders - it'll depend on your approach - if you think price will skyrocket from here, and never look back, you use a market order to be sure to get in.

If you think it'll do a small pullback before taking off, you use a limit order and place that below the current price.

execution speed is not really relevant - if i place a (small) limit order "on the other side" of the spread - it'll fill instantly (just as a market order would)


---

the difference will depend on your order size.
for a 20$ order, a market order will fill at the first price of the other side in most cases.

if your orders are 1000$ - then your risk is that you push the market around - which means that your market order will eat up (or down) the orderbook - so while the initial spread was 99$-101$ - your sell-order may sell for an average of 95$ or less (it filled all available limit orders between 99$ and 90$).

Now assume you're running on ROI - and had a 1% ROI sell (calculated based on the 99$ price).
Now it's selling at 95$ - so you're suddenly at a loss for an order that you thought you're profitable.

if you'd instead have used a limit order with inversed price sides, your sell would've taken place at 99$ - maybe it would have taken a bit to fill - or not filled at all - but youre guaranteed to get the price you specify or better (in your favor).

The real difference will depend on order size, as a order close to the minimum tradable limits (say 20$) will not push markets around as a 1000$ order would - or as a 10k$ order would.




there's some examples of market orders gone wrong too - there was an instance early last year, where on one (low volume) exchange, BTC price shot up to 300k$ for a second, because a whale used a market order instead of a limit order.
if you then had a limit sell-order at 250k  - you could've become rich ... :laughing:

**Comment by aristosv** [comment]
ok, understood, thanks

**Comment by jbishop129** [comment]
> there's some examples of market orders gone wrong too - there was an instance early last year, where on one (low volume) exchange, BTC price shot up to 300k$ for a second, because a whale used a market order instead of a limit order.
> if you then had a limit sell-order at 250k - you could've become rich ... 😆

(closed issue I realize, but just wanted to add my two cents):  I believe something like this happened with `STORJ` about a week ago. For one candle, it skyrocketed over 100%. I only noticed this because I was on the lucky side of that spike with a sell executing. In reviewing my trade performance, I was wondering why STORJ was my top performer, at something like 113% overall, and discovered this bit of luck. 
To @xmatthias' point, understanding order books, and the impact your own order size has on the market itself can be among the many keys to a successful strategy. Thanks for the detailed explanation.
