### ISSUE TITLE
freqtrade.freqtradebot - WARNING - Buy Price from orderbook could not be determined.Orderbook:

### ISSUE THREAD

**Issue by Botman-Hotman** [freqtrade/freqtrade#4468]
## Describe your environment

  * Operating system: ubuntu 20.10 
  * Python Version: 3.7 (`python -V`)
  * CCXT version: 1.40.99 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1 (`freqtrade -V`)
<img width="1680" alt="Screenshot 2021-03-01 at 13 09 56" src="https://user-

  
## Your question

I have the robot running on a VPS, it finds buy signals no problems but this message is put out all the time instead of buys. I am using a Sandbox API Key from Binance. I found some information about how the order book delivers data but I am unsure why this error message keeps appearing.

2021-03-01 12:49:40,673 - freqtrade.freqtradebot - WARNING - Unable to create trade for BTC/USDT: 
2021-03-01 12:49:45,571 - freqtrade.wallets - INFO - Wallets synced.
2021-03-01 12:49:45,574 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 50 ...
2021-03-01 12:49:45,574 - freqtrade.freqtradebot - INFO - Executing Buy for BTC/USDT
2021-03-01 12:49:45,574 - freqtrade.freqtradebot - INFO - Getting price from order book Bid side.
2021-03-01 12:49:45,683 - freqtrade.freqtradebot - WARNING - Buy Price from orderbook could not be determined.Orderbook: {'bids': [[50159.91, 0.000475]], 'asks': [], 'timestamp': None, 'datetime': None, 'nonce': 186}

**Comment by xmatthias** [comment]
as you configured the bot to use the orderbook (and look at ask side) for prices, it's therefore unable to get a valid price.
while falling back to the bid side would be a possibility, that's against the user will as the side is clearly configured.

It's a protection against buying in "broken" markets too - if you have no sellers, your order would never fill. Worse yet - you might be unable to sell an asset you bought if there is noone trying to buy back.

----

it's a common problem on sandbox exchanges - no volume (and no orders / very wide spread).
the only people there are either testing bots, or testing custom scripts (and not many will do that either at the same time than you).

While sandbox exchanges can work to test general functionality of new exchanges (or new features on existing exchanges) - you can't use it to determine if your strategy / configuration will work correctly or not.
That's why we have dry-run, which will simulate orders on the live exchange (it won't place any orders on the exchange).

If you log into the sandbox webpage, you'll see that the orderbook on the ask side is empty (noone is willing to sell at this moment).

**Comment by Botman-Hotman** [comment]
Amazing thank you for the reply I was worried it wouldn't work if I went into production mode with it. Obviously dry run the order fulfills automatically always, would I kind of have to take a percentage or orders being fulfilled away as a good rule of thumb?

**Comment by xmatthias** [comment]
in general, it'll depend on how you price your orders (and which markets you work in, and how your signals work).

if your signal triggers "slightly" early - with the price going down first, before taking off - you're probably fine.
if it triggers as it just took off a minute ago - it might be better to reverse pricing sides ... or even use market orders (although i don't really like these personally, as you give up control about the filling price).

**Comment by Botman-Hotman** [comment]
I will have to do some more research into order books and how they operate so I can decide if I want to use limit orders or market orders for my strategy, appreciate your time friendly neighbourhood advice man👍
