### ISSUE TITLE
How is total profit calculated? Is it in USD or in comparison to what your trading with?

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#4496]
If I set `ask_strategy.use_sell_signal` to `false` and then use a strategy like [freqtrade_backtest_validation_freqtrade1](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/Freqtrade_backtest_validation_freqtrade1.py) and then backtest on Feb5-Mar5 for the 1m ticker, I'll get a profit of `40.41%`, but also notice that there's a market change of `39.88%` and that it looks like I'm holding most of my trades for the entire time.

I'm trading with BTC, so Is my profit being calculated based on how much my BTC has increased or how the wealth of my wallet has increased in comparison to the dollar? In terms of what I'm told for my profit increase, I don't really care about how it's increased in relation to the dollar, because if I have a 40% increase in profit, but the BTC and crypto has generally just gone up by 40% then I could have made the same profit without making any trades. I only really care about how much my BTC has increased, because this tells me that I'm making a profit by trading.

**Comment by xmatthias** [comment]
Market change is a missleading and (in my opinion) stupid measure whenever you're using more than one pair in crypto markets.
You can use that with stocks because you can buy a S&P tracking fund - but you can't do that in crypto, you need to own every single pair.
so even if market raised by 40%, you would not have made this as profit (not assuming you use more than very few pairs).


You see 40% increase of the market - but to reach that, you would have to have bought ALL pairs at equal stakes at the beginning of the backtest period - assuming a pairlist of 50 pairs, that assumes quite some starting capital as you have "minimum tradable" amounts to consider too.

The bigger problem comes when you backtest more than a month (say a year).
You'll see "x% market gain" ... but what you don't consider is that your current pairlist is already biased towards "winners" - you'll only have "surviving" pairs in your pairlist, and new paris that didn't exist a year ago.

If you use today's pairlist (say top50 volume coins), and look at it in 1 year, i'm pretty certain that 3-5 (if not more) will have disappeared - so they would not be in your future pairlist anymore, and would otherwise draw your market change down by quite some margin, as these must be considered a 100% loss.

---

Profits are calculated as profit - so if you start with 1000$, this is the profit (on top) of this amount. #4454 will improve how this is shown, hopefully then it'll be clear.

**Comment by samgermain** [comment]
@xmatthias Ok, I was reading some other posts related to the profit %, can I now calculate my profit as the increase in BTC(The coin I'm trading with) instead of the dollar?

**Comment by xmatthias** [comment]
well profit will be in stake-currency - so your stake-currency is btc, then that's what it'll be used.

I always use $ as example, as the numbers (and subsequently, math) is easier with full numbers than with 0.00001 ...

**Comment by samgermain** [comment]
So [this number](https://i.imgur.com/wA41xLf.png) is profit in BTC, because btc is my stake currency, meaning that if I had 1 btc, then after this I would have 1.38 btc?

**Comment by xmatthias** [comment]
yes, and it's also explained [here](https://www.freqtrade.io/en/latest/backtesting/#summary-metrics) - if you look at the "top table" you'll also see the absolute profit next to it, which will help you understand it.
But as said, the output of this will change soon anyway, which i hope will make this clearer.

**Comment by samgermain** [comment]
Does the update work? I downloaded the commit you linked, but I noticed it's not published to develop or master, so I'm just wondering

**Comment by samgermain** [comment]
The updates are much more clear. Thank you

**Comment by xmatthias** [comment]
it's a proposed pull request ... kindof still in testing, but it's mostly only details that are beeing changed now (i hope)
