### ISSUE TITLE
How can I know when a candle touches my indicator and then close above?

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#4506]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 1.41.35(`pip freeze | grep ccxt`)
  * Freqtrade Version:  develop-fa8156b3 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I want to make a strategy that sounds something like this.

**BUY entry:**
- when RSI crosses above 30
- wait until a candle touches my ema50 indicator 
- wait until the next candle close above ema50 (if there are more than 3 candles close between this one and the one which touch first the ema50 ignore it)

How can I know when one candle touch my ema50 level and also another one within the 3 next candles it did close above ema50?

```
 (qtpylib.crossed_above(dataframe['ema50'], dataframe['ema200'])) &
        (
                    (dataframe['ema50'].shift(1) <= dataframe['close'].shift(1)) |
                    (dataframe['ema50'].shift(2) <= dataframe['close'].shift(2)) |
                    (dataframe['ema50'].shift(3) <= dataframe['close'].shift(3))
        ) &
(dataframe['ema50'] < dataframe['close'])
```

I would say is something like this but is not working as expected. Is there any way how can I check it? Or any other alternative in order to achieve this?

**Comment by Vildnex** [comment]
So... No one can help me or at least give me a hint regarding this? :(

**Comment by xmatthias** [comment]
well, you haven't given it even a day to answer ... while I try to be rather responsive here, it's still free time invested into helping others ... so i wouldn't start pushing before a week or so passes.

i'm not sure what you define as "touch".
You're checking if EMA is below close in at least one of the prior 3 candles - and if it's below the current candle.

that's not a touch - this will trigger whenever RSI crosses 30 and close is below EMA (and was below ema for the last 3 candles).
Sure, your condition can accidentally also be true ... but it's not quite what you're checking for.

You might want to exchange the 3 OR conditions with `qtpylib.crossed()` calls (each with the respective shift offsets on both sides) - so it's really touching / crossing in either direction - but i guess it'll also take a bit of experimentation to get it right (also because it's not quite clear what you're after).

**Comment by Vildnex** [comment]
I know, you are right, sorry if I was too forceful.

Basically what I want is something like this what I am trying to achieve is something like this:

![image](https://user-images.githubusercontent.com/10352059/110527210-57169880-811f-11eb-9770-eb0739cea9d0.png)

1. First I will wait for EMA 50 cross above EMA 200 (the yellow circle)
2. After that I will wait for N(I don't know this N number) candles until I see a candle that "touching" the EMA 50 or crossing EMA 50 in other words (the blue circle)
3. And last but not least I want to wait until a candle close above EMA 50, this should be within 3-4 candles period, otherwise, I will just ignore the previews 1 and 2 conditions and take it all over again (pink circle)

So far I've come with the strategy which I posted above, but I am not sure how can I write a condition such as if (1) is True, then and just then check for the rest conditions (2) and (3). And also I should check for them just from the candles after the (1). I'm not sure if I explain my problem right, I hope that you will understand.
