### ISSUE TITLE
Swapping Bid/Ask side changes results by quite a margin

### ISSUE THREAD

**Issue by Botman-Hotman** [freqtrade/freqtrade#4515]
I have been testing for a couple of weeks and I wanted an opinion. 

When I have the Bid/Ask sides of price the normal way around the bot performs very well and SL are only hit when they need to be. I understand that dry mode assumes all orders are filled. 

However when I swap the Bid/Ask sides to stress test the robot, it makes similar gains but the SL hits more often and it wipes most of my profits away. would you say this is a sign the strategy isn't very good? 

I have optimised, backtested, forward tested and the strategy performs well no matter where I choose to backtest from. Just wanted a more experience opinion as I feel I am close to going live but this worries me a bit.

**Comment by xmatthias** [comment]
swapping the side simply means that you're accepting to pay the spread.

it'll obviously also change the way stoploss orders are priced - if they now hit a lot more frequently, it's probably a sign that the stoploss (or trailing stop?) was too tight in the first place.
The "swapped" sides are used for both sell-price and stoploss calculation - so obviously now the spread is also "added" into the stoploss.


Assuming the stoploss was on the exchange in real mode, i think this way it's more realistic - as dry-run can miss a "very small sling" below the stoploss - as it's getting the updated price ~once every 5 seconds.

The amount of difference will in the end depend on your strategy - if it lives from many "fast" 1% gains (and few stoplosses) - it can cost you profitability - but a simulation can never be 100% accurate - so without swapping sides, you'd also risk a lot of unfilled orders, which can also draw you into the red.

**Comment by Botman-Hotman** [comment]
Thanks for the reply, 

The hyperOpt suggested a SL of 2.8% and TSL of 1.3%, I chose to go for a 8.5% SL instead but if it hits this all the profits are gone after 2 or 3 hits. 

Perhaps changing the minimum values of the Hyperopt and using the Sharpe Ratio hyper loss would make more realistic SL to use in production as I feel a 2.8% is not viable, thoughts?

**Comment by xmatthias** [comment]
2.8% is okish depending on the timeframe.

In general, to not exploit how backtesting / hyperopt works, a stoploss should be bigger than the average move of one candle in your timeframe.

**Comment by Botman-Hotman** [comment]
Using a 4H timeframe. Can I keep this open for a moment. Perform a new Hyperopt with a slight increase of SL and TSL, test for a couple of days and see if this improves results? I think it would be good for anyone who gets to this point and has the same issues.

**Comment by Botman-Hotman** [comment]
So I have the same robot with the normal bid/ask side, i have tested both for the same amount of time and the results are complete opposites. I back tested over a year at different intervals and it was profatble on all, I added filters to remove SHITCOINS, and still with profit. Not sure what this means when swapping bid/ask and I get bad results compared to normal sides with good results. 

Using market orders FYI

**Comment by xmatthias** [comment]
well, assuming you tested on dry-run ... then using market or limit orders don't matter, as dry-run assumes all orders are filled at the price given.
So in theory, i could place a sell-order at 100k$ for BTC - and it would assume it filled (which it will not do in real markets - as price is not that high yet).

if you're using market orders in live, you MUST switch order sides (that's how market orders work) - otherwise all calculations will be off / wrong.
by switching sides, you'll obviously pay spread - so it will depend on your strategy - if it's doing thousands of 1% gains, switching sides will have a huge impact - if you're running a longer-term strategy that does 5%+ ains at a time, the impact will be minimal.

It's not specific to freqtrade either, it's simply how markets / the orderbook works - also when manually placing an order, you mus take a concious decision which price to take - if you'll use market or limit orders (when using market orders, you're ALWAYS paying the spread (by definition) - and often a higher fee as well (depends on the exchange).

**Comment by Botman-Hotman** [comment]
Okay I understand what you mean, so using Market orders and swapping the side incorporates the spread you will pay, hence the losses (as it does have several ROI's/TSL that returns 1% regularly - but when the sell signal happens its usually 5% +). Using limit orders enables you to get the better price without the spread but you have the risk of it not being filled? Sorry you have probably said this before but I am still quite new to the concept of an order book.

**Comment by Botman-Hotman** [comment]
I think I understand now what swapping sides meant, coming from forex the orderbook is a bit strange to me. The link below is what help the penny drop, for me to understand and hopefully anyone else, happy trading. 

https://guides.cryptowat.ch/trader-education/trading-order-types#market-order
