### ISSUE TITLE
Stop loss on exchange is removed after setting a limit order

### ISSUE THREAD

**Issue by denniskis** [freqtrade/freqtrade#4523]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.75.
  * Freqtrade Version: develop-4b689f5b
  
Thanks for the awesome project!
I noticed that a stop loss (on exchange) is removed when the buy limit order is placed. Is it possible to keep it? The price can go down and the bot is waiting until it times out but during this time the coin can free fall and you don't have a stop loss which is dangerous. OCO order on binance is a very cool feature. Is it possible to have the same functionality with freqtrade?

Thanks

**Comment by xmatthias** [comment]
the exchange does only allow you to have either a sell (i assume you mean sell, even if you write buy above), or a stoploss order placed (otherwise you'd be using the same amount twice).

While OCO orders are possible on binance, this is not a "binance only" bot, and no other exchange supports this - so currently, we don't plan on incorporating this.
