### ISSUE TITLE
dynamic stake_currency possible?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4586]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.66
Freqtrade Version: freqtrade develop-7e45af97
  
## Your question

I was explaining to a colleague the basics of freqtrade, and his first question was "when closing a trade, can the bot buy other cryptocurrencies, instead of selling back to the stablecoin? (eg USDT)"

For example when a trade reaches the minimal_roi and the bot sells, why can't it find other coins to invest in, instead of selling back to USDT, and then opening another trade?

That got me thinking, can I have a dynamic stake_currency? Is that possible, or would it even make sense to do that?

**Comment by xmatthias** [comment]
No, it doesn't work, and it also makes very limited sense.

For example, the bot would buy REEF/USDT - the only other pairs on Binance at this moment are REEF/BUSDT and REEF/BTC - so you'd be limited to BTC.

While it sounds nice to be able to sell REEF in exchange for XRP - that's not going to work simply because most combinations will not exist.

Also, the patterns you'd see (REEF/BTC vs. BTC/USDT) will not be identical, so what looks like a chance for REEF/BTC, might be a bad spot to buy BTC from a USDT point of view.

**Comment by aristosv** [comment]
Thank you for the explanation.
