### ISSUE TITLE
startup_candle_count can cause confusing results when backtesting multiple strategies together

### ISSUE THREAD

**Issue by brookmiles** [freqtrade/freqtrade#4631]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3

## Describe the problem:

When backtesting multiple strategies at the same time, if one of those strategies uses a `startup_candle_count` larger than another, it can cause the results of the other strategies run at the same time to be altered.

### Steps to reproduce:

  1. Backtest several strategies at once
  2. Run the same backtests again, adding or changing one strategy to use a much longer `startup_candle_count`
  3. Compare the reported results between the two runs, some of the unchanged strategies may report different results
  4. Run a plot-dataframe on the strategies which reported different results the second time, and note that there may be trades plotted which do not match plotted buy/sell signals
  
### Observed Results:

  * What happened?

Originally, I was trying to figure out why the plot for my strategy was showing orders which did not correspond to buy/sell signals:
![20210330-140719-msedge](https://user-images.githubusercontent.com/323682/112938184-20530180-9164-11eb-8032-9e0a7e0afd0b.png)

I confirmed I was plotting the correct backtest results file, as well as re-fetching trade data, and various other steps to make sure I was seeing correctly plotted data.

Eventually I realised that by adding or removing one of the strategies from my backtest set, the problem would appear or disappear, and that the reported results of the other strategies in the set would change, eg:
```
============================================================== STRATEGY SUMMARY ==============================================================
|    Strategy |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USD |   Tot Profit % |    Avg Duration |   Wins |   Draws |   Losses |
|-------------+--------+----------------+----------------+------------------+----------------+-----------------+--------+---------+----------|
|    BbandRsi |      4 |           8.12 |          32.47 |          162.372 |           5.41 | 2 days, 4:30:00 |      4 |       0 |        0 |
| AwesomeMacd |     15 |           3.59 |          53.81 |          269.102 |           8.97 |  1 day, 2:52:00 |      9 |       0 |        6 |
==============================================================================================================================================
```
vs.
```
=================================================================== STRATEGY SUMMARY ==================================================================
|             Strategy |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USD |   Tot Profit % |    Avg Duration |   Wins |   Draws |   Losses |
|----------------------+--------+----------------+----------------+------------------+----------------+-----------------+--------+---------+----------|
|             BbandRsi |      6 |           8.74 |          52.46 |          262.372 |           8.75 | 1 day, 21:50:00 |      6 |       0 |        0 |
|          AwesomeMacd |     17 |           4.63 |          78.65 |          393.326 |          13.11 |  1 day, 5:11:00 |     12 |       0 |        5 |
| Test_Backtest_Change |      0 |           0.00 |           0.00 |            0.000 |           0.00 |            0:00 |      0 |       0 |        0 |
=======================================================================================================================================================```
```

Narrowing down the problem further, I eventually realized that the problematic strategy was using a `startup_candle_count` of about double the length of the other strategies in the list, and that removing the `startup_candle_count` of that strategy restored the results of the other strategies to their original values.

At first I thought this might be a corruption issue, but after testing things further I finally realised that the entire backtest is using the highest `startup_candle_count` out of all of the listed strategies, and applying it to all of them, instead of each strategy using it's own specified `startup_candle_count`.  

While repeatedly testing a set of strategies, adding or changing a strategy with a higher `startup_candle_count` can alter the results of all of the rest of the strategies in the set, and additionally causes the reported backtest results of those strategies to no longer match the plotted output of the strategy which happens in isolation.

  * What did you expect to happen?

Changing, adding, or removing strategies from the list of strategies included in a backtest should not alter the results of the other strategies listed.

When plotting the results of a strategy backtested in a set, the plotted trades and signals should match.

**Comment by xmatthias** [comment]
To be honest, this is fully intentional, and the biggest `max_candle_count` will be used.

https://github.com/freqtrade/freqtrade/blob/71dea3fb93b347660c3989329ce04cb6d0f767ef/freqtrade/optimize/backtesting.py#L120-L121

freqtrade loads the data only once when backtesting multiple strategies (this is the advantage of `--strategy-list`).
This startup-period is then removed again once the "real" backtesting starts.

For example:
You backtest 1h candles with `--timerange 20210101-` and a startup period of 48 (48 hours).
Backtesting will now load data from 2020-12-29 (48 hours earlier) - and run the `populate_*` methods.

Once this is completed, the dataframe is adjusted to start on 2021-01-01 - so the first trade can (in theory) happen right after midnight - with all indicators populated correctly.

If you have missing data at the backtest start period, there's been a bug i fixed in #4628 which caused this "move up" to not happen.

---

Assuming all data is available (no pair's data starts mid-backtesting - which will show a warning as below) - and you got slightly more data than you backtest (you're using --timerange with a start date bigger than the data start), then the results will not change as the data won't change.

```
2021-03-30 07:58:42,856 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair SXP/USDT, data starts at 2020-07-20 12:00:00
```

If a strategy result changes anyway, then it means that the specified startup-candle-count is defined wrongly - which means the result of the "single run" will be wrong as the first buy cannot happen in the first backtested candle.

Unfortunately, this is not always obvious - on some indicators you specify a lookback of 10 candles - while in the background, it requires 20 or more candles to startup (so simply looking at the default values is not always correct).

**Comment by xmatthias** [comment]
@brookmiles is this ... explained with the above so we can close it?

**Comment by brookmiles** [comment]
Yeah, I don't think the behaviour is _great_, but... I can accept that it's the responsibility of the author/strategy to correctly set the startup candle count, and I can't think of a strong argument for freqtrade to do anything different from what it currently does.
