### ISSUE TITLE
Regarding LoggingMixin

### ISSUE THREAD

**Issue by guplersaxanoid** [freqtrade/freqtrade#4633]
I was wondering why freqTradeBot inherits a class that handles logging. I found a commit(https://github.com/freqtrade/freqtrade/commit/8d9c66a638af5fa57d11bc5dde8563ebf2ede984) that made this change. The maintainer claimed that this was done to prevent over-logging. Can somebody forward me to the issue where this particular complaint was posted? I will close this issue right away.

https://github.com/freqtrade/freqtrade/blob/71dea3fb93b347660c3989329ce04cb6d0f767ef/freqtrade/freqtradebot.py#L39

**Comment by xmatthias** [comment]
It's a Mixin (relatively common in python), it's not inheriting (at least the intend is not inheritance, even if technically that's what it is), which provides some helper-methods.

Without this, all log-messages are posted all the time. Since Freqtrade works as an endless loop (handling buying / selling forever) - this can lead to the same message being posted on every loop (~every 5 seconds).

If i show you the same message 200 times, you'll not learn something new. The login-mixin handles caching for the log-messages and only logs the same message only every X seconds / minutes.
Technically, the same functionality could be copied around ... but there's little point to that.

**Comment by guplersaxanoid** [comment]
Thank you @xmatthias , I see your intent there. Keep up the good work,  I am quite impressed with this repository.
