### ISSUE TITLE
"Unlimited" stake amount wrong calculation

### ISSUE THREAD

**Issue by rextea** [freqtrade/freqtrade#4642]
## Environment

  * Operating system: mac catalina
  * Python Version: 3.7.7
  * CCXT version: 1.43.27
  * Freqtrade Version: 2021.3

## The problem:

When using "unlimited" stake amount, sometimes the stake_amount get bigger (and even double) than your actual - balance / max_open_trades

It's happening when you've got a paltrily filled trade

### Steps to reproduce:

  1. Trade using stake_amount "unlimited"
  2. Wait for a partly filled trade
  3. Then your stake amounts should be disrupted 
  
### Observed Results:
total_balance = 1000
max_open_trades = 2
I'm expecting each trade to take 500$.

1) First trade - try to buy 500$ -> it gots partly filled and takes only 100$
2) Our balance now is 900$
3) Second trade will take 900$ as stake, instead of 500$ as expected

I've seen it's happening in this method: _calculate_unlimited_stake_amount
it's splinting the available_amount / free_open_trades, but sometimes it's not the wanted behavior

@xmatthias - I can try to fix it, but I think it's too sensitive part of the system, so hope you can take care of it easily

** Another Observed bug - when a trade got partly filled and left with very low value, it's get stuck forever because the rest can't be sold (MIN_NOTIONAL)

**Comment by xmatthias** [comment]
> ** Another Observed bug - when a trade got partly filled and left with very low value, it's get stuck forever because the rest can't be sold (MIN_NOTIONAL)

This is basically #3622  ... the alternative to cancelling the slightly filled order is to not cancel it - but if price never returns to that price, it'll simply lead to an order that's open indefinitely - which will also not solve the problem.
Replacing the order at a higher price might work - but will lead to different problems and potential high losses (as the price is now higher, your trade opportunity is most likely gone).

---

Feel free to give this a try - there'll be a review anyway, so it'll not matter who wrote the code, i'll have a look at it (and it's better if it's NOT me writing it - as then it's a 2nd pair of eyes reviewing)

i'm not sure it's the splitting itself that's the problem, but how you define `available_amount`. At the moment, it's taking the "free" amount in stake currency - as that'll be 900$ in your example, and you're splitting it by 1 (the amount of trade-slots still to fill) - it's mathematically logical.

the complexity with changing this is most likely with the last stake amount ... as it can't become too small - but it also shouldn't leave 400$ untouched ... ?

**Comment by brookmiles** [comment]
A few people have reported this as a bug in the discord.  While it might make mathematical sense, I think it's "wrong" for users in that it violates expectations.  It's surprising behaviour, and in a bad way especially because it increases financial risk.

Like you mentioned, there are cases where you probably don't want to have an amount slightly smaller than wallet / max trades sitting unused.  At the same time, I don't think anyone expects that after adding money to their wallet, that the entire available amount will be used on a single trade.  This is surprising and dangerous, and unlikely that anyone would specifically want this behaviour to happen.

After giving it some thought, it occurred to me that you might be able to use total_wallet / max_trades as a maximum, and trade whichever is smaller, (total_wallet / max_trades) or unused_stake.

In @rextea's example, with a partially filled trade using $100, and $900 available in the wallet, it should use ($1000 / 2) = $500 for the next trade because it's smaller than $900, and the $400 should remain unused.  The user has specified two rules 1) no more than 2 trades, and 2) use wallet / 2 per trade.  Leaving $400 untouched until the partial fill closes makes sure that both of those rules are followed, and there are no surprises.  User can manually close the small trade if they want to free up that slot for a full size trade.

This roughly the same situation if the user has some open trades, and adds more money to the wallet.  You start with $200, and two trade slots, one trade fills at $100.  Then you decide to add $800 to your wallet.  The next trade should fill at $500.  Once the first small trade closes, trades will continue to fill at ~$500.

The current behaviour can continue to be used if you have _less_ than (wallet / max trades) available for trading.  This would account for rounding errors, fees, or trade value increasing the size of your wallet.  If your total wallet is $200, but you have one trade open, and only $90 available to trade, you could open a trade with that amount because it's less than (wallet / max trades) = $100.

**Comment by xmatthias** [comment]
as said above, i'm not saying this is correct as is - and you're probably right, it should be "full usable wallet / max_open_trades" to account for this, not just the full wallet / available trades.

the fillup / amendment of last stake happens at another level (one step after) - so in the reverse case (you have 1 trade open for 600$ and 1000$ in the wallet) - the remaining 400$ are either used (amend_last_stake) or not.

**Comment by ghost** [comment]
Hi! Just jumping in to report basically the same issue (2021.3). Happened on my 2 bots yesterday. I had the 2 bots set with buy limit and I got 1 position opened with almost double stake amount and happened on 2 different bots on 2 different machines with 2 different binance api keys.

Later I changed again the 2 bots config with buy market and this morning happened again, opened one of 6 positions much bigger than expected. Again, in 2 different bots.

**Comment by Arminova** [comment]
I have the same problem with real money and I forced to stop the bot. It worked without problems from3-4 weeks ago, but 3 days ago I notice that the stake amount is random! 

`
Binance: Buying INJ/USDT 
Amount: 11.81000000
Open Rate: 17.44460000
Current Rate: 17.44460000
Total: (206.021 USDT, 205.970 USD
`
`
Binance: Buying DGB/USDT
Amount: 2213.50000000
Open Rate: 0.13924000
Current Rate: 0.13924000
Total: (308.208 USDT, 308.132 USD)
`
`
Binance: Buying TKO/USDT
Amount: 46.37000000
Open Rate: 2.28000000
Current Rate: 2.28060000
Total: (105.724 USDT, 105.697 USD)
`
`
Binance: Buying REEF/USDT
Amount: 8477.00000000
Open Rate: 0.03688923
Current Rate: 0.03690000
Total: (312.710 USDT, 312.633 USD)
`

only first order has correct stake amount. I could not solve the problem yet. the bot works without problem in dry run mode

**Comment by xmatthias** [comment]
@pamben i suspect you're having more than 1 bot running (or do manual trades with stake_currency) - so the available stake for one bot is varying.
This is however an unsupported feature, if you run more than 1 bot on the same account, then please use static stake amounts.

**Comment by Arminova** [comment]
I have only one bot running on my account. I didn't do any manual trade in this one. I am using a separate account for manual trading
