### ISSUE TITLE
[Feature discussion] Orderbook in Backtest

### ISSUE THREAD

**Issue by ShinobiWPS** [freqtrade/freqtrade#4643]
Hi team,
I am considering adding the ability to use historical data of orderbook for backtest.
What's the current level of support for this feature?
Which are the most important areas to look at in the vodebase for this?
Any limitations you may know already before I start?

**Comment by xmatthias** [comment]
It's quite simple - it will not work - so best drop this idea and don't waste time.

Exchanges don't provide historic orderbook data - which means you'll need to capture it in real time - so the usefulness of this will be very low (you'll need to capture data for weeks without interruption before you can start backtesting these weeks).
As you'll need that for many pairs (all pairs you want to backtest) - you'll run into exchange ratelimits whiel capturing the data- and storage problems (you'll need to capture it every second or so - which will become huge very soon) - which will then translate to memory problems once you want to use the data in backtesting.


Due to the limits and size of that data - it'll also not be applicable for 95% of the users - so the complexity it will most likely add to the codebase will be a liability and maintenance burden i'm not willing to have in freqtrade (if you can make this in 3-10 lines, maybe - but that's not going to be possible).
