### ISSUE TITLE
pytest report

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4687]
Do you need pytest reports? If not let me know, and close it.

## Describe your environment

  * Operating system: ubuntu server
  * Python Version: 3.8.5
  * CCXT version: 1.46.38
  * Freqtrade Version: develop-79604ea90

## Describe the problem:

Just a pytest report by running a plain 'pytest'. I did not notice a problem in actual operation of the software before or after running it.

### Observed Results:

```
FAILED tests/optimize/test_backtesting.py::test_backtest_start_multi_strat_nomock - FloatingPointError: divide by zero encountered in double_scalars
FAILED tests/rpc/test_rpc_apiserver.py::test_api_ui_fallback - assert '`freqtrade install-ui`' in '<!DOCTYPE html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compati...
FAILED tests/rpc/test_rpc_telegram.py::test_send_msg_sell_notification - AssertionError: assert '⚠ *Binance:*...-24.812 USD)`' == '⚠ *Binance:*...-24.812 USD)`'
FAILED tests/rpc/test_rpc_telegram.py::test_send_msg_sell_notification_no_fiat - AssertionError: assert '⚠ *Binance:*...t:* `-57.41%`' == '⚠ *Binance:*...t:* `-57.41%`'
```

**Comment by xmatthias** [comment]
Pytest runs in different environments in CI - so i know all tests are passing (except for 2 related to the `/log` endpoing which randomly fail).

This is somehow related to your environment (difficult to tell why at first glance though).

The 2nd test that fails ("install UI") i know about - it fails if the UI is installed already, simply running `freqtrade install-ui --erase` before running the tests will fix that test - the others are ... somehow related to your environment i guess.

I suspect it's caused by either a database that's (accidentally) loaded - or by a config that changes some settings.
Maybe try to move the user_data directory out of the way - as this WILL impact testing to some extend.

**Comment by epigramx** [comment]
Oh: nice: thanks. It goes through perfectly in a vanilla directory (with the exception of warning np.float is deprecated in favor of float) mainly because of local configurations/user dirs being out of the way I believe.

I should be running it every time I see changes in code in case it catches anything odd I guess.

**Comment by xmatthias** [comment]
I know about the `np.float` warnings - they anoy me as hell ... but they're from scikit-optimize, so nothing we can fix directly.
