### ISSUE TITLE
Deploying freqtrade dockers on Azure Container Instances (ACI)

### ISSUE THREAD

**Issue by sanderklous** [freqtrade/freqtrade#4690]
## Describe your environment

  * Operating system: OSX
  * Python Version: 3.9.1 (`python -V`)
  * CCXT version: 1.40.99 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi,
I'm trying to deploy my docker image on Azure (ACI). Not for development, but to run my trading algorithm. The instance runs, but it cannot find the configuration file. This makes sense, because I cannot mount the user_data directory, as I do when I run the docker on my local system.

What would be a good solution for this? I can of course copy everything I need into the docker image, but it might not be a very good idea, given the security warning in your documentation (which makes sense, because it contains private keys for both the exchange and telegram). Eager to hear what you think would be a good approach for this.

If I should copy the config file and other files from user_data to the image, could you tell me how to do that? When I add the COPY statement to the Dockerfile it doesn't find the config.json file. I probably need to point it to the local environment somehow.
Thanks,
-- Sander

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by sanderklous** [comment]
Okay, the copying I found, I have to remove config.json from .dockerignore. This fixes part of the problem, as for dry_runs I don't need to include private keys for the exchange in the configuration.

**Comment by xmatthias** [comment]
Running on Container services without persistant storage is neither supported nor recommended.

While you now add the `config.json` (and probably also the strategy) into the container (which i wouldn't do - at all!), your database will also not be persisted, so should ACI decide to restart your container, it'll probably also reset all your trade progress (because your database is empty).

On top of that, container services usually restart containers from time to time, usually by first starting another container and then destroying the initial one - which would lead to a (faulty!) restart of the bot.
I say faulty because the new bot will not properly start if you use telegram - as you cannot have 2 telegram bots running at the same time.

Our recommendation is to use a VPS and install docker there - where you can both mount directories (circumvents both the above problems) - and fully control when things are restarted.

Container instances are usually also rather expensive - it may seem cheap - but running one vcpu on ACI seems to cost around 35$ per month on azure ... for which i can get 3 mid-powered VPS servers on Digitalocean at 10$ each ... or 7 low-powered VPS at 5$ each ...
Usually, the container services are not designed to have a container run 24/7 - in which case they will become rather expensive.

**Comment by sanderklous** [comment]
Okay, thanks. One of the container Use Case I had in mind was to hyperopt each of the trading pairs in a different container. Still needed to figure out how to collect the results. I'll go for the VPS option instead.
