### ISSUE TITLE
Backtest populate (Backtest "Brute force" tool)

### ISSUE THREAD

**Issue by Regul777** [freqtrade/freqtrade#4709]
After my previous experience I decided to discuss before make a pull request (as I did with my --cfg improvement).
The feature that I want to discuss is "Backtest populater". In backtests you have the ability to make a list of strategies or pars to backtest. I want to propose to make a structure to be able make a list of ANY configuration parameter as well as a strategy name and pair is only the one of the parameters. How I see it:
First of all, we must make some small improvements to be able to config strategies by argument line and by config.json
```
config.json:
{
"strategy_cfg": {"timeframe": 14}
}
```
or as I proposed through args -> config.json:
```
freqtrade backtesting --cfg strategy_cfg.timeframe=14 ...
```
these parameters will be applied to the strategy.

The next thing, you have a few ways to create a populated (maybe not the best term, but let's use it for now).
1) make it through arguments, e.g. 
```
--bp strategy_cfg.timeframe=[13,14,15]
```
or compare the strategies:
```
--bp strategy=["SmaStrategy", "RsiStrategy"]
```
2) make a "populater"
```python
class DemoBtp(IBacktestPopulate):
    def get_timeranges(self) -> List[TimeRange]:
        return [
            # 2020
            TimeRange.parse_timerange('20200101-20210101'),
            # 2021
            TimeRange.parse_timerange('20210101-20210301'),
        ]

    def get_config_variants(self):
        sub_configs = [
            {
                "tradable_balance_ratio": [0.99],
                "exchange.pair_whitelist": [
                    ["BTC/USDT"],
                ],
            },
            {
                "tradable_balance_ratio": [0.1, 0.2, 0.3, 0.5],
                "exchange.pair_whitelist": [
                    ["BTC/USDT", "XRP/USDT", "ETH/USDT"],
                ],
            },
        ]

        return ({
                    "timeframe": ['1m', '5m', '1h'],
                    "strategy_params.timeframe": [13,14,15],
                    "strategy": ['SmaStrategy', 'RsiStrategy'],
                }, sub_configs)
```

as the result you will have a list of results with different backtests with different parameters. The main idea is to be able to config and compare ANY config parameter or a strategy parameter and compare them (it's worse than hyperopt, because it's just "brute force", but just comfortable). I am showing all the configs in the first column. Not the best for the console output for a bug amount of parameters, but ok for a small variety of params. 

The example of backtest_results in Jupiter notebook with the "Backtest populate" (you can see variety of params in the first table):
![image](https://user-images.githubusercontent.com/433392/114279093-3f298180-9a09-11eb-9637-847a2bb564ef.png)

**Comment by xmatthias** [comment]
To be honest, i'm not sure it's a good idea.
The config structure you propose looks ... rather complicated, and it'll be very difficult to get it correct (unless you're a developer / familiar with json files).

While backtesting allows you to use different strategies, it enforces ONE timeframe on purpose.
The only reason to even allow the `--strategy-list` parameter is because it avoids reloading data over and over again, which you'd void with this approach.

By using this "brute-force" approach, you'd very quickly lose control over the combinations - as it'll become a cross product (any combination with any combination) - without ANY logic to eventually exclude some configs because they don't make sense, or because going in "this direction" would cause worse resuts (which is what hyperopt does).

Your "populater" alreaddy has 2 (timerange) * 4 (balance_ratio) * 3 (timeframe) * 3 (params.timeframe) * 2 (strategy) = 144 different backtests this would run (which means loading data 144 times, calculating indicators 144 times ...) - so this will get out of hand VERY quickly, especially as you're running the FULL backtest again and again - not just part of the backtest logic (as you already list different timeframes, you must start at the dataloading step).

On top of that, it's intentional that hyperopt does not allow hyperopting the `populate_indicator` function - as this is potentially the slowest part (depending on the indicators).

---

With the new hyperoptable parameters (check the docs / PR #4596  - it's great!), some of these things might be available easily (with small changes to hyperopt).
That way, you can take advantage of using hyperopt, which brings the speed (no dataloading and populate_indicator in single epochs), and is not brute-force, but controlled, (hopefully) moving in the right direction to minimize the loss function,

multiple timeframes will not be possible, neither will hyperopting the populate_indicator function, but to be honest, i'm not interrested in supporting that as it'll make hyperopt very slow.
If you really must / need it, you can work around that by calculating the indicator in `populate_buy`- but that'll be rather slow and a waste of energy, as you'll end up calculating the same indicator 100ds of times - but it's the decision of the strategy author - not a slowness that's introduced by freqtrade.

**Comment by xmatthias** [comment]
I'll close this as the benefits #4596 provides makes brute-forcing parameters (trying everything without even trying to evaluate if the direction you're moving is correct) pointless and a waste of resources.
