### ISSUE TITLE
Variable stakes for static pairs

### ISSUE THREAD

**Issue by theluxaz** [freqtrade/freqtrade#4715]
## Describe the enhancement

*I would like to request a feature for static pairlists. It would be really useful for me and few other users of Freqtrade I discussed with to be able to set ratios/percentages of the the stakes for traded pairs.*

*For Example if you are trading 4 pairs and wish to stake more on some pairs than others, you could provide a JSON somewhere within a config to assign the following percentages of max available funds accordingly:*

```
{
    "BTC/USDT": 30,
    "ETH/USDT": 35,
    "AAVE/USDT": 15,
    "UNI/USDT": 10
}
```
*This means freqtrade would stake 30% for BTC, 35% for ETH and so on, instead of dividing the stake amount evenly based on max_open_trades.
For the sake of consistency 0.3 could be used instead of 30, allowing the maximum to add up to 
"0.90 tradable_balance_ratio".*

*The total value of the pair ratios should not exceed the set tradable_balance_ratio. When the total pair ratios does not reach the tradable_balance_ratio, the remainder could possibly be used as balance to to trade other pairs without provided percentages.*

*Here is an  example providing 2 out of the 4 available pairs, BTC and ETH, 30+35=65% or 0.65*
```
{
    "BTC/USDT": 30,
    "ETH/USDT": 35
}
```
*If the tradeable tradable_balance_ratio is 1.00, 35% could be split for for the remaining max_open_trades. For this example the max_open_trades is 4, 2 are reserved for BTC and ETH in the provided JSON, so other trades in staticPairList not included in this json would get 35/2 = 17.5% of the balance per trade.*

*Let me know if this feature could be viable. I don't understand too deeply how other pairlist handlers are implementation-wise, so I am not sure how compatible this could be with others than StaticPairList, although being able to increase the stake amount/ratio for specific pairs would be really nice.*

**Comment by xmatthias** [comment]
> The total value of the pair ratios should not exceed the set tradable_balance_ratio.

This part suggests that you didn't understand what `tradable_balance_ratio` stands for.
It's the percentage of the full wallet that's available to the bot. What comes out of that is assumed as 100% available for freqtrade.

e.g. your wallet is 1000$ - and `tradable_balance_ratio` is 0.5.
This will mean that for freqtrade, only 500$ (50% of the total wallet) willl be used - and these 500$ will be seen as 100% of the available capital.

---

That said - i don't think this is a useful feature - at least not as proposed. 
While it may seem nice at first, you'll find it quite limiting very soon. A better approach will be #3886 - which gives control of this to the strategy - so the user/strategy get's to pick himself based on "~random~ custom rules".

That PR is however not ready (and currently not in a mergable state), and hasn't seen any activity in a while.
That doesn't invalidate the approach though - which will give a lot more flexibility than a fixed config (especially since your approach will fail for volumepairlist, which is what most users seem to use).

**Comment by theluxaz** [comment]
> This part suggests that you didn't understand what tradable_balance_ratio stands for.
It's the percentage of the full wallet that's available to the bot. What comes out of that is assumed as 100% available for freqtrade.

Sorry for unclear description, what I meant by this is that the sum of stake amounts (%) for pairs should not exceed the percentage available for freqtrade (allowed for trading), or 100% for that matter, just as a safeguard. I also forgot to mention in my first post that this is talking about dynamic staking.

But True having the ability to select the stake amount based on a pair or other metrics pair within the strategy would be more useful, it would also allow integrated AIs to choose custom trade amounts in the future. I just hope this allows to define the percentage to use (dynamic staking) rather than an absolute value, as it should stake more or less depending on the changing total amount in the wallet.

The reasoning for this request is that when allowing freqtrade to trade I would like to allow the bot to stake larger dynamic stake amounts (by a percentage) based on trading pairs. For example if the bot is more reliable and profits more reliably on more stable pairs such as BTC, in contrast to pairs such as HOLO, ONT or other less reliable ones, where a smaller stake amount is preferable as big gains are possible, but the risk is much higher. 

Since not all trading pairs behave in the same way, it would be nice to be able to mitigate that risk in some way. As discussed in the thread you linked somewhere, it would also be a way of a kind of portfolio management. As you said Freqtrade is a trading platform, not a portfolio management one, however it would still be useful when let's say you really think some cryptos are rising soon, using UNI as an example, but bot keeps buying the same amount of WEED (just an example where the coin is not likely to increase much or have a risk of falling hard) as other promising coins. Of course you could blacklist those pairs you like less, but this would require a lot of manual maintenance to keep the blacklist up-to-date, hence just increasing the stake % for preferable pairs and using the default lower dynamic stake for others is the easiest way.

Sorry for the long post or unclear explanations, and thank you the response xmatthias. As you said, control within the strategy is much better as proposed in the linked thread. How much has the person developed it in terms of completion? I could try to help out in coding this, although I expect it would take a little while to fully understand how the implemenation of Freqtrade works, or can this task be done just by understanding a few parts of the system?

**Comment by xmatthias** [comment]
i'm not sure / convinced about the usage of percentages as return values ... while it may fit your particular usecase, i think it'll be limiting / complex for many others and i therefore think having a fixed value will give people more control (nothing prevents you from calculating the stake in the  method based on your percentages ... ).

well first of all, it'll need rebasing / merging with the current develop branch, as quite a lot has changed, especially in the backtesting file.
I'd then (probably) also change this to also provide the available / consumed stake - which will simplify calculations / decisions.

after looking at the changes necessary, it MAY be faster to restart the PR and copy/paste what's necessary (rather than rebasing / merging). for one, because the PR does not change 10000 things ... and for the other, because almost everything changed in the meantime to allow compounding in backtesting.

**Comment by theluxaz** [comment]
Thank you for the reply, I will see what I can do, but it will likely take some time. I'll restart the PR once it's functional in some way.

**Comment by xmatthias** [comment]
That sounds good - take your time, it's not going away :laughing:
