### ISSUE TITLE
/performance command

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4726]
Why when I send /performance to the bot, reply me

```
<b>Performance:</b>
1.  <code>XVS/USDT 998.69% (2)</code>
2.  <code>WRX/USDT 998.64% (1)</code>
3.  <code>RVN/USDT 762.01% (3)</code>
4.  <code>LUNA/USDT 727.90% (2)</code>
```

**Comment by xmatthias** [comment]
a) please fill out the issue template, otherwise i'll close this issue without further comment.
b) Is this the full response, or is the "end" truncated and there would be a lot more pairs?
c) are the percentages correct? (they seem kinda high - especially for one pair)...
d) what does the log say around the time when you call this?

**Comment by tutecode** [comment]
Sorry, this is the problem, when I send /performance. The first message send with this error, and the second message is good.

![photo5163771130975201458](https://user-images.githubusercontent.com/54072234/114586933-8b6c0000-9c5b-11eb-96b8-ff28325af3ca.jpg)

**Comment by xmatthias** [comment]
Will be fixed in a few minutes - i'll link the commit to the issue - so once it closes - wait for CI to finish, then it'll be fixed on the develop version.

Thanks for reporting.
