### ISSUE TITLE
Can't define `custom_stoploss()`

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#4737]
I have `use_custom_stoploss = True` and a `custom_stoploss()` in my strategy class.
But I get exceptions because line 575 of `strategy/interface.py`, in `IStrategy` class, has a line like:

```
stop_loss_value = force_stoploss if force_stoploss else self.stoploss
```

Where I don't even have `self.stoploss` defined in my strategy.

I get this exception:

```
AttributeError: '{MyStrategy}' object has no attribute 'stoploss'
```

**Comment by xmatthias** [comment]
stoploss is mandatory in either configuration or strategy and will serve as the initial (hard) stop.

Not having it would mean a pretty high risk, as not every user is a developer, so we must also cover the case where custom_stoploss never reuturns a valid value without putting 100% of the trade at risk (because there is no stoploss).

You can set the stoploss value to something pretty low (like -0.6 or -1) to get around it - but then it's an explicit user decision, not by mistake in a custom loss function.

for next time:
Please fill out the issue template. it's there for a reason and  i'll close issues without it.

**Comment by avibrazil** [comment]
I’ll try with a very low stop loss as (-0,6 or lower) in the hope my custom stop loss will act before. Thank you for the tip.

**Comment by xmatthias** [comment]
as said, it's intentional that this is a required field - so users are forced into an explicit decision to use a very wide stoploss - not run into it by a malfunction of a custom stoploss function.
