### ISSUE TITLE
KuCoin fees paid with KCS and falling back to wallet amount

### ISSUE THREAD

**Issue by yagmot** [freqtrade/freqtrade#4738]
I noticed you've added some commits dealing with KuCoin so I wanted to warn you about an issue I've run into. Maybe you can add something to the documentation about this, as I'm not sure if it warrants any changes to the bot.

KuCoin has their own coin called KCS, and they offer a discount on fees if you use it to pay for them. This is activated with a simple switch on the web interface and app. If you enable this option, it will deduct the fees from your KCS holdings instead of the quote currency used for the trade. If you are low on KCS, it will fall back to the quote currency.

The problem is that if you also trade KCS with freqtrade, the amount remaining in your wallet can fall below the 98% fallback limit used by `_safe_sell_amount`, and so the bot will never sell. (to avoid this, I change that number to 50%).

With that in mind, what is the thinking behind the 98% limit? What is the scenario where you wouldn't want to fall back to  `{wallet_amount}` if it's below `{amount}`?

**Comment by xmatthias** [comment]
So this KCS token is similar to BNB on binance ... 

in the end, that means it should simply be blacklisted (which is what we also recommend for BNB, btw).

the "98% " rule is there for another case. 
Some exchanges deduct fees off the "receiving" currency - so if i trade XRP/USDT - and i buy 100 XRP - i'll only get 99.9 XRP, instead of the ordered 100.

Assuming i can only trade full XRP (lot-size=1) - i'm now unable to sell the 0.9 XRP (this will result in "coin dust").
The problem now is that if the fee fails to update for whatever reason, the bot still tries to sell 100 XRP (it's usually not the case, only if something failed on updating the fee for the buy order).

The 98% rule is there to still be able to sell in these cases, with the assumption that fee for one order should not exceed 2% (it's usually below 1%).

By changing that to 50%, you're probably causing problems  with the profit calculation - so while the bot may report a profitable sell - it's not really profitable anymore.

It's pretty simple - if you buy the 100 KCS - but you only sell 50 KCS - that trade automatically lost 50% of it's value, so to even be break-even, the price would have to raise by 100% ... which is probably not the case.
