### ISSUE TITLE
Docker image with technical indicators

### ISSUE THREAD

**Issue by jisnardo** [freqtrade/freqtrade#4752]
Hi,

Is there any docker image with technical indicators from https://github.com/freqtrade/technical/?

https://hub.docker.com/r/freqtradeorg/freqtrade/tags?page=1&ordering=last_updated

https://github.com/freqtrade/freqtrade/blob/develop/Dockerfile

Custom image build:

https://github.com/freqtrade/technical#usage

Dockerfile

```
FROM freqtradeorg/freqtrade:stable

RUN pip install technical
```

Thanks.

**Comment by xmatthias** [comment]
the `:develop` image includes the technical module since about a week.

For stable, you'll have to install technical manually for now by inheriting from the image like shown [here](https://github.com/freqtrade/freqtrade/blob/stable/docker/Dockerfile.technical).

Once we do a new release (probably in a few weeks) - technical will be part of the regular stable image as well.
