### ISSUE TITLE
Telegram command to change strategy

### ISSUE THREAD

**Issue by evranch** [freqtrade/freqtrade#4763]
I have a couple strategies that I like to switch between as market conditions change (tuned to work better in bull/bear markets basically). As I'm often on mobile most of the day, it's inconvenient to login to my server, stop the bot and restart it with a new --strategy.

Would it be fairly simple to make a /strategy telegram command that switches the strategy and reloads the configuration?

**Comment by xmatthias** [comment]
You can use `/reload_config` to reload the configuration, but you have to change the strategy in the configuration yourself.

Changing configuration settings (and persisting them) itself via telegram is currently not possible - and there's currently no plan on incorporating this in the near future.
It's problematic as it would need to write the configuration - which might be in read-only in a docker-container, or have permissions that prevent the bot from writing.

Both the above are perfectly valid setups (the config is read-only from the bot's perspective anyway) - but would cause your command to fail.

Writing configuration files would also slightly change them in certain cases (if you have comments in the file, these would disappear) - which is clearly undesired.

**Comment by evranch** [comment]
Thanks, it makes sense how configuration settings can't be easily changed, especially from a persistence standpoint. However if I don't want to change any global configuration and only want to switch which strategy is being run, would this still require writing to any files?

Basically all I'm doing now is killing and relaunching freqtrade i.e.

Ctrl-C
freqtrade trade --strategy Strategy2

It appears /reload_config kills and starts a new instance of the bot, which runs the entire init process including this code which sets the strategy either from the config file or the commandline:

```
        # Set strategy if not specified in config and or if it's non default
        if self.args.get('strategy') or not config.get('strategy'):
            config.update({'strategy': self.args.get('strategy')})
```

Could we config.update({'strategy': to a value passed from Telegram while starting the new instance and override it the same as if it had been passed from the commandline?

Sorry if this is a stupid question, I have very little python experience. If this was C/C++ I would just try it out and send a pull request.

**Comment by xmatthias** [comment]
At a quick glance - i don't see this as possible.

`/reload_conf` is tearing down almost everything, and reloading the configuration files from disk to reset eventual "online" changes done / update to the settings that have been made (that's what it's developed for, so that's non-optional).

Not updating the strategy would break this (you can add a "strategy" key in your config instead of using `--strategy` - so it can be changed by editing the configuration).

As this would break other, intended flows, i don't see this as feasible at the moment, not without breaking other things. 

---

On top of that, it'd also be quite dangerous - assume you use something "autostarting" (docker, systemd, ...).
As the "changed strategy" only lives in memory - a server or process restart would revert to the initial strategy - which is for sure not what you'd want.

**Comment by evranch** [comment]
Makes sense, thanks for considering the idea though.

Personally I run freqtrade manually with _screen_ on a Google micro instance precisely because I don't want it autostarting and trading in unknown conditions.

**Comment by xmatthias** [comment]
I can understand that - the problem is, for freqtrade i MUST consider all usecases - and the "autostarting" one is 
* the recommended one
* the one most used

therefore having in-memory strategy changes which revert back to the config after a restart are simply too dangerous.
