### ISSUE TITLE
quick question about ./Dockerfile

### ISSUE THREAD

**Issue by jpmolinamatute** [freqtrade/freqtrade#4795]
## Describe your environment

  * Operating system:  Archlinux with kernel 5.11.15-arch1-2
  * Python Version: 3.9.3
  * CCXT version: ccxt==1.48.22
  * Freqtrade Version:  2021.3
  
## Your question

This is kind of a development question, as far as I can see most scripts and relevant commands are being executed as root, assuming that freqtrade can be executed as a regular user why do we need sudo?

**Comment by xmatthias** [comment]
the next release (2021.4 / current develop) will no longer use root within the docker container, but will use a non-privileged user for this.

To enable a kindof smooth transition however, we need sudo within the container to change the permissions of the user directory to that non-root user, otherwise a simple update would fail for most users.

My intend is to potentially remove this sometime in the future (but not within the next 3-5 releases) - but i'm not sure about it yet, because docker creates non-existing host-directories (`user_data` in our case) as root if the directory didn't exist before, which would cause errors when starting freqtrade.

**Comment by jpmolinamatute** [comment]
makes total senses, thanks for the explanation @xmatthias
