### ISSUE TITLE
IRIS/BTC Selling Caution

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4813]
Hello! What happend with Iris, because I don't have stop-loss and there is an caution icon.

![iris](https://user-images.githubusercontent.com/54072234/116122041-a39a4100-a697-11eb-85e6-5b6f74b081d7.jpg)

**Comment by xmatthias** [comment]
Apparently you have a stoploss of ~35-37% - and the bot ran into this stoploss.

This is something normal.
The "warning" icon is the regular icon for stoplosses (X for sells for loss, and rockets for higher profit trades).

**Comment by tutecode** [comment]
> Apparently you have a stoploss of ~35-37% - and the bot ran into this stoploss.
> 
> This is something normal.
> The "warning" icon is the regular icon for stoplosses (X for sells for loss, and rockets for higher profit trades).

But is strange because I have another cryptos less than 35%-37%. I repeat, I have not "stop-loss". My stop-loss is "-1"

![iris2](https://user-images.githubusercontent.com/54072234/116139284-3ba22580-a6ac-11eb-88be-07cd3400d84b.jpg)

**Comment by xmatthias** [comment]
As i mentioned to you explicitly before - if you expect help, please fill out the issue template - otherwise i'll close this issue. As you've "removed" the issue template multiple times now, see this as last warning, future issues without the issue template filled out will simply be closed without further notice. 


Also, for this case, please provide the logs for around the time of the sell so further analysis is possible.
