### ISSUE TITLE
24h change in strategy

### ISSUE THREAD

**Issue by terter-ctrl** [freqtrade/freqtrade#4827]
## Describe your environment

  * Operating system: Linux
  * Python Version: 2.7
  
Hi, 
I would like to add to my strategy to trade only pairs which are 24h positive. What is the best way to do it?
does dataframe['close'] is the current price if I add 24h close to informative pairs? should I work with orderbook?
Can you add some code here which will give me direction?
Last question, is it possible to check this feature in backtesting?

Thanks :)

**Comment by xmatthias** [comment]
You should be able to use something like `dataframe['close'].pctchange(<number>)` - where number is the number of candles you want to use to look back.

Now this number will depend on your timeframe, and on very short timeframes (1m) it will not work because you don't have a full day of data at all times.

If done correctly - it will work in backtesting as well.
I'd suggest to research how to do this with pandas in general, as it's a freqtrade feature, but a simple pandas feature.

**Comment by froggleston** [comment]
The correct function is `df['close'].pct_change(x)`, note the underscore. (Only necroing this due to a question in discord).
