### ISSUE TITLE
save positions and all trade history  in database

### ISSUE THREAD

**Issue by cyaxaress** [freqtrade/freqtrade#4828]
freqtrade version: 2021.3

Is it possible to save all open positions in database? my server restarted last night and I started freqtrade bot again but all trade history deleted and now I have to manage them manually

**Comment by xmatthias** [comment]
Freqtrade is storing all trades (open and closed) in the database, which by default is "trades-v3.sqlite".

If you're running with docker, you should make sure to select a file that is mounted into the container, otherwise it'll "reset" when a new container is deployed.

You can specify this url with `--db-url` - by using `sqlite://` - you're using a in-memory database which would reset after a restart.
The default however is `sqlite:///trades-v3.sqlite` - which will create a file in the current working directory.

**Comment by cyaxaress** [comment]
Yes I use docker image but I dont know how to set my database :( can you please write that complete line of code?
how can I mount file into docker image and use it as database?

thank you

**Comment by xmatthias** [comment]
I would recommend to read the [documentation](https://www.freqtrade.io/en/stable/) from top to bottom.

It includes the information you need (on top of having it posted above).
