### ISSUE TITLE
Non binary signals

### ISSUE THREAD

**Issue by bab3nk0v** [freqtrade/freqtrade#4845]
## Describe the enhancement

Let's consider the following setup: we have 10 open slots for trades and 30 possible pairs that we can buy.

The strategy can possibly have a way to distinguish between more and less likely to win pairs, but currently there is no way to set some priority to them, we can only return 0 or 1.

What if we can give strategy an ability to set some values in [0..1](smth like strategy confidence score) in populate_ methods, then freqtrade will sort the pairs according to this score and buy most reliable ones?

If it seems reasonable, i can try to implement it as some additional option in config(or a custom pairlist handler, but i'm not sure about it). It definitely won't break the strategy API since it still will be able to return all ones/zeros instead of scores.

**Comment by xmatthias** [comment]
i see 2 problems with this ...

* pair ordering is determined by the pairlist
* using something different than 1 / 0 will probably / potentially collide with #2183 - which would use this for "different" purposes (leverage / short).


Now while 2 might be a longer shot (not immediate) - using this for "pair ordering" now would be problematic, as it'll restrict further usage of it.

I'm also sceptical about the first point ... but in general, i'm not against giving this "control" to the strategy - but i don't think overloading the buy signal with it is a good approach.

**Comment by bab3nk0v** [comment]
> pair ordering is determined by the pairlist. 

That's true. It could be a custom pairlist, but if memory serves me right it's executed before the strategy logic, so...

The easy way is the config option that switches on strategy responsibility for the ordering and disables the pairlist responsibility. It case of conflicting APIs the priority can be a new column, e.g. 'score'/'confidence'/'win_probability', whatever.

I also see another way: allow pairlists to be executed after the strategy and use strategy output. So, every pairlist will be able to use an option like "execute_me_after_strategy: True". With such architecture the problem becomes the problem of creating custom pairlist.

**Comment by xmatthias** [comment]
The pairlist must be running before the strategy - otherwise you'd need to download ALL pairs from the exchange (300+ for binance USDT alone) ... 

if you run the strategy first, you'd have no data - and i doubt you'll then be able to determine a proper ordering.

i'm pretty ... sceptical to have multiple columns (more than buy / sell) do too much - it'll become complex rather fast i'm afraid ...

**Comment by bab3nk0v** [comment]
> The pairlist must be running before the strategy - otherwise you'd need to download ALL pairs from the exchange (300+ for binance USDT alone) 

Ok, let's call it not the pairlist but create some brand new entity smth like "after stategy handler" with an ability to apply a bit more logic.

Maybe, we can reuse Edge positioning somehow? It has control over stake_amounts and pair priorities, but it's a huge monolitic blackbox right now. Is it possible to extend it in a more configurable way so that it allows strategy developer to apply custom formulas?

**Comment by xmatthias** [comment]
in hindsight, edge is done wrong - it does too much in a too inflexible way ... but afterwards you're often wiser.

in theory, all you need to do is determine the last pair in your pairlist - and then "remove" all buy-signals that you had in your strategy you don't want triggered on - so all "still active" signals are acted on.


Now that's a .... difficult thing to do in it's own right - so i'd think you need to clearly specify what you're after.

At first, it was sorting of pairs - now we're talking about controlling "whatever" else ... which will move into dangerous territory (not because we shouldn't have that - but because it should be 2-3 PR/issues - not mashed into one).
