### ISSUE TITLE
Enhance Request: SQL Server support

### ISSUE THREAD

**Issue by evanokeefe39** [freqtrade/freqtrade#4874]
## Describe your environment

  * Operating system: Docker / freqtrade image stable
  * Python Version: Docker / freqtrade image stable
  * CCXT version: Docker / freqtrade image stable
  * Freqtrade Version: 2021.2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Exploring SQL server support since with SQL Alchemy we have flexibility to use other SQL engines than sqllite. Have gotten as far installing all the SQL Server drivers and pyodbc on top of  freqtrade base image. Can run 'freqtrade trade ' and connect, but when it tries to create the initial tables I get this error on the first run:

pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'stoploss_order_id' in table 'trades' is of a type that is invalid for use as a key column in an index. (1919) (SQLExecDirectW)")

But seems to create the table anyway since its there with all the correct columns in ssms.

Running a second time i get this error:

sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'ft_pair' in table 'orders' is of a type that is invalid for use as a key column in an index. (1919) (SQLExecDirectW)")

### Steps to reproduce:

1. Create SQL Server and DB on Azure (add client to firewall? yes)
2. Add a login and user with "db_ddladmin" role
3. create a new docker image with dockerfile:

`FROM freqtradeorg/freqtrade:stable

WORKDIR /freqtrade
COPY ./user_data ./user_data

RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        apt-transport-https \
        curl \
        gnupg \
        unixodbc-dev \
        gcc\
        unixodbc \
        libpq-dev \
 && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
 && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
 && apt-get update \
 && ACCEPT_EULA=Y apt-get install --yes --no-install-recommends msodbcsql17 \
 && apt-get install -y --reinstall build-essential \
 && pip install pyodbc \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/*

ENTRYPOINT [ "/bin/sh ", "-c" ]
CMD [ "echo", "hello" ]
`
4.  Build and run with  docker run -it --entrypoint /bin/bash <your image>/<your image>:<your tag>

5. Fill in blanks of this command and run in container shell: 
freqtrade trade -c ./user_data/config.json --strategy <your awesome strategy> --db-url 'mssql+pyodbc://<user>:<password>@<host>:1433/<db name>?driver=ODBC+Driver+17+for+SQL+Server'

I think it will involve modifying the the core freqtrade persistence code and I am a bit lost at the moment when it comes to that :)

**Comment by xmatthias** [comment]
The column is defined as String - and to have an Index. 
I can't see what would need to change in this  (we don't do anything special with this)- if it's creating problems with mssql, best create a minimal scenario and raise an issue with Sqlalchemy.

There is nothing involving a key (this column is not part of the primary key) - so the error does not make sense.

You might wanna try one of the other mssql drivers (like pymssql).
If it also doesn't work there - then best use postgresql as database (if you don't want to use sqlite).

While sqlalchemy should support mssql - mssql support in python in general is not very good in my experience (there's 3 drivers, but none of them does work without a lot of messing around).

---

Please don't expect much help in this issue - freqtrade officially supports sqlite - and will also work on postgresql (i know multiple people using this).
You're probably the first using mssql - and if it doesn't work - you'll have to do the "legwork" yourself to investigate why it doesn't work (changes to freqtrade will have to be VERY minimal - otherwise we'll simply add mssql as non-supported database to avoid impacting other databases.

**Comment by bzed** [comment]
@evanokeefe39 Using postgresql on Azure should give you less pain. Also thanks and :+1: @xmatthias for working on pgsql support!

**Comment by xmatthias** [comment]
Your best bet will be to use postgresql if mssql is giving you problems (as mentioned above).

We don't officially support either - but postgresql works out of the box - and i see no point in trying to support mssql if it is failing with random errors.

**Comment by evanokeefe39** [comment]
Awesome, thanks for the responses guys I will definitely have a go with postgres! Cheers!
