### ISSUE TITLE
What different between `amount` and `amount_requested`

### ISSUE THREAD

**Issue by kamontat** [freqtrade/freqtrade#4876]
## Describe your environment

  * Operating system: Linux
  * Python Version: Python 3.9.4 (`python -V`)
  * CCXT version: ccxt==1.48.76 (`pip freeze | grep ccxt`)
  * Freqtrade Version:  freqtrade 2021.4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I notice that when bot buy and sell crypto it always has some amount left without sell. After some debug I found that when we execute buy/sell it will always using `amount` data in Trade. The problem is somehow in db amount is less than amount_requested.

<img width="380" alt="CleanShot 2021-05-05 at 00 34 09@2x" src="https://user-images.githubusercontent.com/14089557/117045367-a0f3b780-ad39-11eb-9b26-a1c7bf5614a9.png">

**Comment by xmatthias** [comment]
If you're not using BNB to buy fees (assuming binance) - then binance will take the fee from the "receiving currency.

So the bot would request 100 XRP  (`amount_requested`)- but you only get 99.9 (`amount`) - because the 0.1 is used to pay the fees.

As you can only sell full XRP (coin is an example - not sure if that's the case for XRP) - you'll be left with 0.9 XRP which you can't sell (called binance dust).

The only way to avoid this is to have BNB in your account - and enable paying fees in BNB.

`amount_requested` has no operational meaning (it's only stored, not used for anything as it's irrelevant) - but will allow you to determine these differences.

**Comment by kamontat** [comment]
You said correct, after I buy some BNB, amount and amount_requested is the same now.
