### ISSUE TITLE
About buy and sell signals at occurring the same time

### ISSUE THREAD

**Issue by quents** [freqtrade/freqtrade#4880]
## Describe your environment

  * Operating system: macOS Big Sur
  * Python Version: python 3.9 (`python -V`)
  * CCXT version: ccxt==1.44.2 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.3 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

My strategy uses different parameters of an indicator in buy and sell signals, and that can result in buy and sell signals trigger at the same time. If that occurs, it doesn't sell the the pair because of (I guess) that line in "interface.py" file:

`            sell_signal = sell and not buy and ask_strategy.get('use_sell_signal', True)`

However, I want to prioritize the sell signal if buy and sell happen at the same time. If I remove the portion "and not buy" from the condition, it appears to work yet I wanted to make sure if that is the only way or is there any possibility that I break something else changing that.

**Comment by xmatthias** [comment]
The problem with inconclusive signals is that it creates confusion (and can be quite dangerous).

If your strategy says "sell" - but also "buy" - and you're in a trade, you'll usually want to remain in the trade - otherwise it might buy it again (or buy it after this candle).

a better way is to handle this in the strategy - and setting the buy-signal to 0 where sell is set (`dataframe[dataframe['sell'] == 1, 'buy'] = 0` ) - that way  the buy-signal will be removed from the strategy when the sell signal is also active.

**Comment by quents** [comment]
Thank you for the quick response, your advice gave the same result with the core code change. My mentality there actually is "if sell signal occurs, give up and buy something else" :) It increases the performance according to the backtest, by the way.

**Comment by xmatthias** [comment]
the idea is not bad - and by using it this way, it's consistent also for plots / graphs - otherwise one signal will overlap with the other signal, and you'll probably struggle to see that both signals overlap.
