### ISSUE TITLE
Bot not trading possibly from SAPI endpoint upgrade

### ISSUE THREAD

**Issue by Novitec1** [freqtrade/freqtrade#4894]
Hello, 

My bot suddenly stopped trading completely.  I went back it an optimized it as I thought maybe the issue had something to do with that without success.  After reading through my Binance notifications I can across the notice to API users on delisting WAPI endpoint and I am going to assume this is why my bot will no longer trade.

What do I need to upgrade in my code and where do I upgrade it so my bot can start trading again???

Thanks in advance

**Comment by xmatthias** [comment]
Please fill out the issue template (the one you deleted when posting this issue).

Also, if there are any issues / problems - then the logs will point these out.

The wapi deprecation is not going to happen until August according to the binance message - so that'll for sure not cause any issues at this point (and it won't cause problems in August either, as freqtrade is not using any WAPI endpoint).

**Comment by Novitec1** [comment]
Thanks Matthias.  I have resubmitted the question with the correct information.

**Comment by xmatthias** [comment]
closing in favor of #4897
