### ISSUE TITLE
Permission issues on docker images

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4917]
While running the container on linux I stated to meet the following issue:
```
PermissionError: [Errno 13] Permission denied: '/freqtrade/user_data/config.json'
```
I think that It may be cause of I have to run docker compose under sudo:
`
sudo docker-compose up -d
`
But I don't think its a reason.

**Comment by xmatthias** [comment]
using sudo with compose is always wrong and points to an installation problem.

The docker-images recently changed to run as user (no longer as root).
As such, they can no longer read files which have wrong permissions (like root).

Fixing this can be as simple as running `docker-compose run --rm freqtrade create-userdir --userdir user_data` again (which will attempt to fix permissions in the user directory).

If this does not fix your issue and you'll require more assistance, then please fill out the issue template (the one you deleted when opening this issue) - otherwise i will not be able to provide any further help as i have to take guesses about your environment.

**Comment by snussik** [comment]
`Fixing this can be as simple as running docker-compose run --rm freqtrade create-userdir --userdir user_data again (which will attempt to fix permissions in the user directory)` this command and `docker-compose build` after helped.

Buy the way, I faced up with this bug too: #4839 and think that they are of the same nature. In my workflow I don't create files on server - just upload them and it (I think) causes permission issues.

**Comment by alexander171294** [comment]
If you are using fedora, or SELinux distributions, and you see permission error running freqtrade create-userdir 

```
2021-11-16 00:35:56,668 - freqtrade.configuration.directory_operations - WARNING - Could not chown user_data
2021-11-16 00:35:56,668 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/deploy_commands.py", line 26, in start_create_userdir
    userdir = create_userdata_dir(args["user_data_dir"], create_dir=True)
  File "/freqtrade/freqtrade/configuration/directory_operations.py", line 69, in create_userdata_dir
    subfolder.mkdir(parents=False)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'user_data/backtest_results'
ERROR: 1
```

Then, you have this problem: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

And the solution is add `:Z` at the end of volume in your docker-compose.yml file like this:

```
    volumes:
      - "./user_data:/freqtrade/user_data:Z"
```
