### ISSUE TITLE
Very long Hyperopt time

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4928]
## environment
  * Operating system: Ubuntu 16.04.4 LTS
  * Freqtrade running in docker

Are there any options to decrease Hyperopt time? I run 200 epochs for half an hour. If I increase depth and number of epochs - it can be days.  
Its not like my 16 cpu cores scream :( Only some of them:
<img width="1279" alt="Screenshot 2021-05-13 at 20 25 03" src="https://user-images.githubusercontent.com/16715490/118162714-bd72ac80-b429-11eb-8a72-74b1d3458e1b.png">

Do I need some flags or something else in order to utilise all cores?  Seems to be a bug.

ps. I think that epochs run from core to core one by one according to what I see in htop (not simultaneously)

**Comment by xmatthias** [comment]
Hyperopt will run backtesting in parallel - but calculating the next points in your space to try will be running in 1 core (this is a limitation of the scikit-optimize algorithm, which cannot be parallelized).

after each set of epochs - scikit-optimize will gather all previously evaluated parameters and try to calculate the best next parameters to try your strategy with.

The more parameters you have in your space, the more calculation effort will result out of this.
This is however not a bug, but expected behaviour based on the algorithm limitation.

**Comment by snussik** [comment]
Could you give me advice: what is the most efficient way to run hyperopts with large number of parameters and several thousand of epochs? As how I see it now, I just have to run several 2cpu instances with different hyperopt strategies and just wait for a couple of days for result.
Am I right?

**Comment by xmatthias** [comment]
don't use large spaces. That'll usually not get you pretty good results.

It's better (and designed for) to start with an idea and then tune the parameters - not giving hyperopt 100ds of parameters with a "pick any combination" mentality.

**Comment by snussik** [comment]
`giving hyperopt 100ds of parameters with a "pick any combination" mentality` that's what I really wanted ))
Thanks.
