### ISSUE TITLE
Why Onlyprofit Hyper takes into account the cumulative profit? 

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#4934]
Hi Matthias, recently I was hyperopting using the OnlyProfit function and I realized that the Profit column takes into account what in the backtest is the Cum Profit %.

This leads to cases where the cum profit % is actually higher, but the tot profit % (or the tot profit FIAT) are lower than before the hyperoptimization.

I think, especially when taking the "unlimited" stake amount into consideration, the right data to optimize for is the tot profit % (or the tot profit FIAT), since that's what we look for and if the strategy is well set, this can lead to a bettere w/d/l as well because, in order to improve the tot profit %, the hyper function needs to find better quality trades.

From my point of view this is a better setting for this function, what do you think?

**Comment by xmatthias** [comment]
Personally - i don't use "OnlyProfit" hyperoptloss - as it does not care about risk / drawdowns whatsoever - so results are not ... tuned to my risk preferences.

I guess you're right - it's been a while since that loss changed - and with the introduction of compounding to hyperopt, doing a `profit_ratio.sum()` will most likely not return the correct results.
