### ISSUE TITLE
multi space hyperoptable params

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4935]
## Describe your environment
freqdev

## Describe the enhancement
sometimes multi space hyperoptable params will be usefull
like that
... space="buy"): hyperopt just for buy strategy
... space="sell"): hyperopt just for sell strategy
... space="same"): hyperopt for buy equal to sell
... space="both"): hyperopt for buy and sell two defferent values

It can usefull for dont repeating code tnx

**Comment by xmatthias** [comment]
you can always use `--spaces buy sell` (or any other combination) to hyperopt both buy and sell spaces.

I would not see what "multi" would include - as it's the same as `--spaces buy sell ...` - and there is no further determination of which parameters you'd like to hyperopt.

In case of hyperoptable parameters, you can control this with the "optimize" flag - which you can disable to exclude certain parameters from hyperoptimizing even though they would fall into the selected space.

**Comment by mablue** [comment]
i mean not in command line. I mean the code.
In code we have space="buy" or "sell"
that if We need a same buy and sell variable so we shoud add two time a variable
but if there is a multi  or all type we can just add one to make a same value or defferent value to buy and sell params with one line code

**Comment by xmatthias** [comment]
i'm ... not certain about the usecase for this (i understand what you mean - but i don't think it's a valid usecase)

Assuming a simple RSI strategy if you're using a rsi < 30 or rsi > 30 ... you won't be able to use the same paramter for buying and selling.

it's the same for categories - even though you might buy on RSI cross - you might be selling on something completely different (like SAR cross) - so i would think that having the parameters seperate would be beneficial (?)

**Comment by mablue** [comment]
No no noo
I allways use same or different hyperopted but same porpused values for my strategys.
for example:
buy_rsi = IntParam(25,75,default=50,space="buy")
sell_rsi = IntParam(25,75,default=50,space="sell")
buy_operator = "<"
sell_operator = ">"
Its not dry
I shoud use this if i need defferent values:
rsi = IntParam(25,75,default=50,space="all")
or if I need a unic value for all buy or sell:
rsi = IntParam(25,75,default=50,space="same")

its not just for my strategy.sometimes we need to write bunch of same value hyperoptable params and will repeat the code 2times. that we just need it in all buy and sell or not for all two we just need it as timeframe for example:
fastTimePeriod = IntParam(7,14,default=9,space="all")

**Comment by xmatthias** [comment]
> or if I need a unic value for all buy or sell:
> rsi = IntParam(25,75,default=50,space="same")

This will not work. You will only have one  `rsi.value` - so only one space will be hyperopted.

While i can see the "both" option (both buy and sell) (it's part of both spaces - but only one value will be outputted) - the "same" option will not work as we would need to have a `rsi.buy_value` and `rsi.sell_value` - in which case it's clearer to have 2 seperate parameters.

This will make the interface confusing and misaligned (the same parameter has different properties depending on a parameters) - and is therefore not something that will be considered.

**Comment by mablue** [comment]
you know some times I want to optimize a global value for two buy and sell.
but I dont want to rehype the buy values.
in this point I shoud remove space=buy from my code and change it to space=sell so use to hyperopt with this spaces (--spaces sell trailing)
except that I will get error that say: you havent sell hyperoptable params!!
why its confiusjng?
rsi.value inside sell populator means sell_params.rsi.value
and in buy populator means buy_params.rsi.value
and the default is just for all two the same value except we add result dict on the top
it will be very usefull to global values hyperopt.may somebody like to hyperopt a thing inside informatives.it will be usefull there too

**Comment by xmatthias** [comment]
Your assumptions are wrong. 

Every parameter (say `rsi_val = IntParameter(...)`) is available once (one instance) for the whole strategy.
If you're using this in `populate_buy` - or `populate_sell` - does not matter.

So let's assume we configure the following: `rsi_val = IntParameter(..., space='both')` 

You're now using this `rsi_val` in both `populate_buy_trend` and `populate_sell_trend`.
You run hyperopt with `--spaces buy sell` - so you will get the same value for your buy and sell trend - if it's 30 for one epoch, it will be 30 for the whole epoch (in all methods). If it changes to 31 - it will be 31 for all methods.

If you now run hyperopt with `--spaces buy` - the exact same thing will happen (it's defined as hypothetical 'both' - so it will be part of both spaces).
The parameter will ALSO change for the sell space - because there is only one instance.

Also, if you run with `--spaces sell` - the parameter will also change for the buy methods.


while you mention ` buy_params.rsi.value` - this shows that you didn't understand how this works (please read the documentation multiple times - until it becomes clear).

`buy_params` defines the value to be used - so `buy_params: {'rsi': xxx}` is loaded to the rsi parameter.
you cannot use `buy_params.` in your populate-methods - that's simply wrong.

**Comment by mablue** [comment]
I know it will be same.
I know its not true to use buy_params
I swimming inside docs last weeks. you know.
i just want to say what I mean
for example if rsi can undrestand where is it called(inside which method.it can findout which value will be passed)
and I just want to reduse code repeating on globall things.
yes I can set globalls to space= "buy" but its not true way its confuse the reader of code cuz its not just for buy space I use it for example as an optimal timeframe on both buy and sell or on other standard metods...
but when I want hyperopt it for example just for sell I will rehype whole buy params too!
it will be a list i think:
space=['buy','sell']
and in methods
if result dict avalble .it go and check the place of call and find which value will be set
if dict is not avalble the default value will be passed
if space='none' it will be a global value that hyperopt for all a same value.
its the best approche to do.

**Comment by xmatthias** [comment]
Thanks for your idea - but we will not be implementing this (at least not the way you're proposing it here).

It's better to repeat the parameter and **be explicit** in what it will be, rather than having a very confusing interface (the same parameter has different meaning based on context) which will only raise questions and lead to implementation errors.

we "might" add a "both" option at some point - which will include the parameter in the space in both buy and sell spaces - however the parameter will have the same value for the whole duration of one epoch.

As that option will however not work the way you're proposing it above, i'll close this issue to prevent confusion.

**Comment by mablue** [comment]
Tnx to you too.
Hope I can say what I mean
An option to converting something like:
```
optimal_buy_timeframe0=IntParameter(4, 20, default=10, space="buy")
optimal_buy_timeframe1=IntParameter(4+10, 20+10, default=10+10, space="buy")
optimal_buy_timeframe2=IntParameter(4+20, 20+20, default=10+20, space="buy")
optimal_sell_timeframe0=IntParameter(4, 20, default=10, space="sell")
optimal_sell_timeframe1=IntParameter(4+10, 20+10, default=10+10, space="sell")
optimal_sell_timeframe2=IntParameter(4+20, 20+20, default=10+20, space="sell")

```
To:

```
for i in range(3):
   optimal_timeframe[i]=IntParameter(4+(10*i), 20+(10*i), default=10+(10*i), space="same")
   
```
Or for hyperopt defferent values for buy and sell:
```
for i in range(3):
   optimal_timeframe[i]=IntParameter(4+(10*i), 20+(10*i), default=10+(10*i), space="both")
   
```

And in 
Buy method:
It can undrestand which value will passed by location of calling.
For example if
```
buy_params = {
   "optimal_timeframe" =[10,20,30]
}
sell_params = {
    "optimal_timeframe" =[5,7,9]
}
```

In buy strategy method the value of self.optimal_timeframe[1] will equal to 20
And In sell strategy method the value of self.optimal_timeframe[2] will equal to 9

@xmatthias

**Comment by xmatthias** [comment]
I understand what you mean.

That would be a very confusing interface, so please accept that i said no to this proposal.

You might think it would be useful - but it will be very confusing.
Thinking about maintainability and supportability of the project - my decision to this proposal is no, and it is final (the same parameter will NOT get different meaning depending on the method where it's used).

**Comment by mablue** [comment]
Ok.no need to same! let think about "not same" or "both" its the main thing of this issue . "Same"   is just make hyperoptin process more faster

**Comment by ppkantorski** [comment]
I have parameters like sampling and acceleration that I would like to be the same for both buy and sell spaces.  If I use the same parameter in the buy space for both buy and sell,  hyperopt ends up messing up and producing inconsistent results.  Because of this I too think a “both” space would be very helpful.  I’m currently trying to see if there is a way to get around this.

**Comment by mablue** [comment]
> I have parameters like sampling and acceleration that I would like to be the same for both buy and sell spaces. If I use the same parameter in the buy space for both buy and sell, hyperopt ends up messing up and producing inconsistent results. Because of this I too think a “both” space would be very helpful. I’m currently trying to see if there is a way to get around this.

It should not be hard to spliting one line with space=both to two line with space =buy and space= sell.not manually, I mean programmagically(programmatically)
Yhe only problem is time :)
