### ISSUE TITLE
freqtrade.service after reboot in RPi (no RTC)

### ISSUE THREAD

**Issue by JackBananas** [freqtrade/freqtrade#4936]
## Describe your environment

  * Operating system: Raspbian GNU/Linux 10 (buster)
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.48.76
  * Freqtrade Version: freqtrade 2021.4
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

After enabling the freqtrade.service in order to automatically start after a reboot, following the instuctions found in the documentation, it fails. I found two bugs:

If the service states "After=network.target", the service cannot connect to my trade exchange (binance) due to a connection error.

If the service states "After=network-online.target", the service cannot connect to my trade exchange (binance) due to a time sync error (I suspect the problem with the time sync is beacause of the lack of RTC in the raspberry).

### Solution I have found

My solution has been to modify the freqtrade.service file to include:
After=multi-user.target
Restart=always
  
I don´t know if this way is the most elegant or efficient (spoiler: I don't think so), but at least it works.

I would helped me a lot any warning about this issue in the documentation (as there is for the location of the user services in the raspberry, for instance).

Thanks in advance.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

If anybody wants to, I can upload any related log.

**Comment by xmatthias** [comment]
on a raspberry - i'd personally suggest to use docker instead of systemd (i'd generally suggest to do that ...).

The systemd service is not designed for a raspberry (obviously there's nothing wrong with it per se) - as that system has a very "unique" approach to time (it'll ALWAYS start with a wrong time, and only have a correct time once the network is available and connected for a few seconds).

as far as i know, `multi-user.target` will not guarantee that the time has been updated (it'll depend and can be a race condition) ... so i don't think there's a "clean" way on a raspberry to handle this (not with a systemd service, anyway).

**Comment by JackBananas** [comment]
I also think that it works because of the `Restart=always` condition more than the `multi-user.target`.

I close the issue. I hope this could be helpfull for somebody someday.
