### ISSUE TITLE
Split hyperopt iterations

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4950]
I've faced with tthe issue when hyperopt results file require large ram to be read. I realize that the more epoches I make the bigger is file.
Regarding, that each hyperopt job statrs with random seed, it could be fine to make several smaller epochs than 1 big: 10 x 1000 epochs instead of 10000 epoches.
But  this is interactive process: I have to run one job after another manually as freqtrade doesnt allow simultaneous hyperopt jobs. And thats not fine.
Is it possible to run splitted hyperopt jobs somehow without useing additional instruments like apache airflow of smth. similar?

**Comment by xmatthias** [comment]
Freqtrade does not allow simultaneous hyperopt jobs because these would eat ressources of each other (each would require RAM + CPU - so you'd run out of memory (most likely) and have processes killed - or freeze your system (which pick depends on your system).

There's no such method for freqtrade - and benefits of it would be more than questionable - as you'd then have 10 different hyperopt-files to analyze, compare and figure out which one contains the better results.

Usually, you will want to vary something after the first set - as you see that "X" does not work properly, or "Y" would be better.

As said before - Optimizing with insanely large spaces is not a good idea and will usually not result in very good endresults. Using a supervised approach (optimizing first buys - based on a pre-selection of some indicators) - then sells, and then maybe stoploss - obviously having sane defaults to begin with) will yield better results.

**Comment by raoulbuzziol** [comment]
I use a simple `bash` function to run 20 times 500 epochs and have the result joined.
The outputs are 4 files: 
- hyperopt best results
- hyperopt profitable results
- all the Total Profits together
- a joined csv export with all the results

I run the below script with a command like this (that would run 20 times the hyperopt with the specified parameter):
`run_hyperopt MyBaseFileName 20 "-c btc_a_v3.json -c btc_x_spl.json -s MyStrategy --timerange 20210401-20210501 --max-open-trades 100 --stake-amount 0.001 --starting-balance 0.1 --enable-protections --hyperopt-loss SortinoHyperOptLoss --epochs 500 --spaces buy sell"`

```bash
#!/bin/bash
source ~/freqtrade/.env/bin/activate

function run_hyperopt {
    basefilename=$1
    runs=$2
    hyperoptparameters=$3

    fb=results/$basefilename._b.txt
    fp=results/$basefilename._p.txt
    ft=results/$basefilename.TP.txt
    fcsv=results/$basefilename.csv

    echo "###################" | tee -a $fb $fp
    echo "################### Hyperopting $runs times" | tee -a $fb $fp
    echo "################### parameters: $hyperoptparameters" | tee -a $fb $fp
    echo "###################" | tee -a $fb $fp

    i=1
    while [ $i -le $runs ]
    do
        echo "###################"
        echo "################### Hyperopts number $i of $runs" | tee -a $fb $fp
        echo "################### parameters: $hyperoptparameters"
        echo "###################"

        freqtrade hyperopt $hyperoptparameters

        echo ""
        echo "################### Hyperopts number $i of $runs"
        freqtrade hyperopt-list --best       --no-color 2>&1 > /dev/null | grep -o "/home/.*fthypt" | tee -a $fb
        freqtrade hyperopt-list --profitable --no-color 2>&1 > /dev/null | grep -o "/home/.*fthypt" | tee -a $fp
        freqtrade hyperopt-list --best       --no-color | tee -a $fb
        freqtrade hyperopt-list --profitable --no-color | tee -a $fp
        grep "Total profit" $fb > $ft

        freqtrade hyperopt-list --export-csv $fcsv.tmp
        if ! test -f "$fcsv"; then
            sed "s/$/,exec_name/" $fcsv.tmp | head -n 1 >> $fcsv
        fi
        sed "s/$/,\"$basefilename\"/" $fcsv.tmp | tail -n +2 >> $fcsv
        rm $fcsv.tmp

        ((i++))
    done

    echo "###################"
    echo "################### Hyperopts DONE. $runs times"
    echo "################### parameters: $hyperoptparameters"
    echo "###################"
}
```
