### ISSUE TITLE
Performing trade on the same candle with signal

### ISSUE THREAD

**Issue by talhazan** [freqtrade/freqtrade#4965]
Hello,

Since there's no documentation over such practice I think it would be valuable to have such explanation, for those who use low timeframe rates (5m,1m) the importance of performing a trade on the same candle is crucial.

I would like to know what modification I need to perform in the strategy in order to have trade on the same candle that a signal is being triggered.

Much thanks for your great work.

**Comment by xmatthias** [comment]
Almost all indicators are based on the candle's close value (unless explicitly specified differently).
All values except for open, are still due to change for the duration of a candle. 
Using the "unfinished" candle is called repainting - and freqtrade will not allow this by only providing complete dataframes.

As such - signals are available at the beginning of the next candle.
While it "seems" like it's a delay of 1 candle, it's actually a misinterpretation of timeseries data. 
The signal might be on the 10:00 candle - but the 10:00 is the candle's open date, of a candle that goes from 10:00-10:05 - so the sell entry at 10:05 is happening at the earliest possible point from this regards.

**Comment by talhazan** [comment]
Thank you Matthias, 

So the right approach would be faster MAs to 'compensate' ?

**Comment by talhazan** [comment]
While at it, if using the 'open' price to trigger a trade, it can ponteitally be triggered faster?

**Comment by xmatthias** [comment]
i assume you're looking at scalping - but i have my doubts that you can be scalping with freqtrade successfully (i have my doubts about scalping in crypto-markets in general, as most fees are pretty high for that type of trading).


In general though - speed is almost never the issue - if you THINK that's the issue, then the signal is bad / too late.

Freqtrade will only give you closed trades - so what you're asking is not relevant.

**Comment by talhazan** [comment]
You are explaining that the trade will always be performed after the candle was ended, regardless if I use 'open' price to trigger the trade?

**Comment by xmatthias** [comment]
A trade will happen as soon as the "buy" signal is switched to 1 (this can in theory also happen intracandle).

Regular strategies based on TA will only do this when a candle is closed - as freqtrade will only give you closed candles to avoid repainting.

**Comment by talhazan** [comment]
Interesting, can you elaborate more on this? If i write my own indicators from scratch, performing the calcs outside of ta and providing the trigger to FT would it be possible? or the approach of "faster MAs" is more logical here?

Is there an example somewhere you noticed we can use in this thread?

**Comment by talhazan** [comment]
![image](https://user-images.githubusercontent.com/83101768/118486849-c235aa00-b722-11eb-9892-da5dff092c94.png)

In this example i'm using lzsma with very short window, the trades that happens one candle later will consider as loss.

if i'm changing the calculation to use openprice, it will damage the strategy even further since the trade will happened on once candle is completed right?

I can find a faster indicator to trigger the buy signal even a bit earlier, that will compensate the situation, but the quality of the signals is a different topic, is there are way to override this, by concept i understand that FT does not support it, but for edge cases i think it should.

**Comment by talhazan** [comment]
You are right, using 'open' will trigger the trade on the same candle. it's represented "wrongly" right?
![image](https://user-images.githubusercontent.com/83101768/118488445-68ce7a80-b724-11eb-864b-998525bcf543.png)
Obviously it messes up the strategy, but that can be handled

**Comment by xmatthias** [comment]
well the representation is kindof correct - as this is when the signal appears.

But the signal itself will be assigned to the prior candle. Assuming you're using "crossed" - you can quite clearly see that the cross happens in the prior candle (although it's kidden because the candles are not visible).

**Comment by talhazan** [comment]
Thank you Matthias, I've collected more data to prove that something is not 100% accurate, either "dry mode" is causing this, or different, bug maybe. but that is just an assumption.

I've collected data from several recent trades in a scalp type strategy:

In the following example, which "ended" in profit trade, but the majority ends in loss.

13:00 Buy signal at 27.522 
13:02 Trade at 27.865
13:04 Sell signal - IGNORED 
13:06 Buy signal - IGNORED 
13:08 Sell signal at 27.957
13:09 Sell Trade at 27.838

Attaching the UI sc' for reference 
![image](https://user-images.githubusercontent.com/83101768/118992964-c7e2f800-b98d-11eb-9b07-6910f0983b92.png)

What are the chances that the "dry run" market data is generating this maybe faulty data? I noticed some trades "appear on the candle" in the right timeframe, with minimal difference then 'close' price.

The configuration in this case is market/market.

Much appreciated.

** note ** this strategy input is 'close' the previous screenshot attached is with 'open' as for testing purposes.

**Comment by xmatthias** [comment]
at a first glance, i'd suspect that you either have a very large pairlist (which will not work on 1m candles) - or that your signal is instable (so what you plot at a later time is different to the signal when "this" candle is the latest).

Please provide logs - otherwise no further analysis is possible.

**Comment by talhazan** [comment]
Actually there's one pair in this instance, The signal is very stable, Thank you but no further assistance is required.... I'm stopping using this application
You can close and delete this ticket.
Regards
