### ISSUE TITLE
No module named 'ta' error in docker 

### ISSUE THREAD

**Issue by trapatsas** [freqtrade/freqtrade#4966]
I'm using the following Dockerfile.technical file, as suggested in other similar questions:

```
FROM freqtradeorg/freqtrade:develop

RUN pip install --user ta
RUN pip install technical
```

I always get the same error from strategies using TA-lib:

```
2021-05-17 12:12:37,248 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/GodStra.py due to 'No module named 'ta''
2021-05-17 12:12:37,425 - freqtrade - ERROR - Impossible to load Strategy 'GodStra'. This class does not exist or contains Python code errors
```

Since TA-lib is not just another library, but highly recommended for technical analysis, can we add a properly configured Dockerfile.technical in the repo just to avoid the same question again and again?

**Comment by xmatthias** [comment]
> but highly recommended for technical analysis

 Just because one strategy uses it, it's FAR from being highly recommended.
I assume this is what the module itself claims - unless you have some independent source for this statement, i'll assume it as your personal opinion.
The interface ta provides is rather cumbersome to use (unless you're very familiar with object-oriented programming).

---

Your scripts / dockerfile seems outdated - please use the [latest documentation for this](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose).
you will no longer need technical - as it's included in the default freqtrade docker images - the install itself seems fine.

As for providing a dockerfile for this - i don't see any reason to do that.
It's one library of many, and i don't see what makes it stand out amongst all of them.
