### ISSUE TITLE
Hyperopt freeze on "Calculating indicators"

### ISSUE THREAD

**Issue by talhazan** [freqtrade/freqtrade#4971]

**Comment by xmatthias** [comment]
The simple answer: simply be patient - it will end eventually - it's simply calculating an indicator - which is probably a slow one to calculate.

This will be caused by the indicator you're using - some indicators calculate fast (in a vectorized way) - others are slow and require a rather long time to calculate.

Considering your parameters, hyperopt will calculate `26 * 2 * length(pairlist)` times the `linreg` indicator.
Depending on the indicator (i don't know this indicator, so maybe it's fast, or it's slow to calculate it once for 37000 rows) - this can take a while.
you can use backtesting to get an idea on the duration - and then multiply that by 62 (26 * 2) to get an average expected duration.


Aside from this - 
Your double-loop does not make sense (the zlhma parameter has no influence on anything other than the column name)

**Comment by talhazan** [comment]
Thank Matthias, 

How do you recommend to approach this, there are simply two params to calculate (in other strat it works fine, but as you mentioned, completely different indicators)

there's a chain below that loop, i just posted on liner, that line is using the var 'lhma' as timeperiod
        for lhma in self.buy_lhma.range:
            for zlhma in self.buy_zlhma.range:
                dataframe[f'lhma_buy_{lhma}_{zlhma}'] = pta.linreg(dataframe['close'], lhma)
                dataframe[f'lhma2_buy_{lhma}_{zlhma}'] = pta.linreg(dataframe[f'lhma_buy_{lhma}_{zlhma}'], lhma)
                dataframe[f'lhmab_buy_{lhma}_{zlhma}'] = dataframe[f'lhma_buy_{lhma}_{zlhma}'] - dataframe[f'lhma2_buy_{lhma}_{zlhma}']
                dataframe[f'zlhma2_buy_{lhma}_{zlhma}'] = dataframe[f'lhma_buy_{lhma}_{zlhma}'] + dataframe[f'lhmab_buy_{lhma}_{zlhma}']
                dataframe[f'zlhma_buy_{lhma}_{zlhma}'] = pta.sma(dataframe[f'zlhma2_buy_{lhma}_{zlhma}'], zlhma)
                return dataframe

**Comment by xmatthias** [comment]
Your syntax is wrong - you shouldn't return from within the loop (that will return on the first iteration).

Apart from that - it looks okish with what you posted now ... so you'll simply have to be patient i guess - although you could move the calculation of the "initial" indicator  (`pta.linreg` lines) out of the inner loop and then use it within the inner loop - so it's not done multiple times.

**Comment by acarli82** [comment]
Hi,
i have find the problem; it isn't possible create graph with trade running :)
