### ISSUE TITLE
Trading at Binance with stake_currency unlike BNB is ambiguous (pair blacklist)  

### ISSUE THREAD

**Issue by eleyvapro** [freqtrade/freqtrade#4987]
## Describe your environment

  * Operating system: macOs 11.2.3
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3

## Your question
Hello guys, I hope it is a misunderstanding from myself but, taking in consideration this configuration below and according to the doc: => [For Binance, please add "BNB/<STAKE>" to your blacklist to avoid issues](https://www.freqtrade.io/en/stable/exchanges/#binance-blacklist)

- "stake_currency": "USDT"
- "pair_blacklist": ["BNB/.*"]
- having "use BNB to pay fees" activated at Binance

is it mean, summarising that You can't trading with BNB at Binance?

**Comment by xmatthias** [comment]
yes(ish).

assuming you only have 1000USDT in your account (no other currency) to start with.
The bot then buys 200$ XRP, and for 200$ BNB.
It's now selling the 200$ XRP - and binance will use the (now) available BNB to pay for fees - so now your BNB trade is no longer 200$ - but 199$ (or less). 

As "other" trades eat into the BNB trade amount - the profit calculation will be wrong - and depending on the amount of trades, the amount can become too low to sell (not necessarily with a 1000$ wallet - but if you're testing a strategy close to the lower tradable limits).

As such - we've had many cases where BNB trades where stuck (became unsellable because now they are < minimum tradable).

Blacklisting BNB is a recommendation - if you do have BNB available already - you can also trade on it - but often people use it on a fresh account - where it can cause problems.

**Comment by eleyvapro** [comment]
Thanks @xmatthias for your help! I got it, I specially dont see it like big issue if you can cancel the trade in Binance manually when that happens.

**Comment by xmatthias** [comment]
it's a suggestion to avoid problems - is all.

assuming you own an amount of BNB - you can also trade BNB without much problems (unless you run out of the "available" BNB funds before).

**Comment by eleyvapro** [comment]
Yeah, especially when Binance biases for BNB in every single feature, it is almost impossible not having that coin in your wallet.
