### ISSUE TITLE
List of Coinbase Pro issues

### ISSUE THREAD

**Issue by bastulli** [freqtrade/freqtrade#4997]
Anyone have a list of issues that cause Coinbase Pro to not work well the freqtrade/CCXT API?  Would like to start trying to resolve known issues.

**Comment by xmatthias** [comment]
Well coinbase pro does not have fetchTickers - so you can only use pairlist methods which don't require tickers (basically StaticPairlist, and one or 2 filters).
that's however not a ccxt limitation, but one of the exchange - so unless you have influence on their API methods (i doubt that) - there's little you can do for this.

other than that, i'm not aware on what doesn't work - but i never used them - mainly because i find their fee structure to be insanely high...

**Comment by bastulli** [comment]
> have influence on their API methods

 :( well it looks like Kraken is the next best exchange.  Thanks for the reply xmattias!

**Comment by xmatthias** [comment]
well not having volumepairlist is not a blocking point - you can still get happy using a static pairlist...
