### ISSUE TITLE
Candle data for actual trades 

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5000]
## Describe your environment

  * Operating system: Windows
  * Freqtrade Version: latest(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hey!

I am using the strategy_analysis_example.ipynb, and at the bottom, there is a section on loading live trade results from sqlite db to jupyter notebook. Now what I have observed is that the open-dates and close-dates are not the same as when I download candles and load backtest results. I would like to further optimize my strategy and improve it on actual trades, but it's not possible if I don't have a way to connect it what my strategy actually "saw" from the ta lib indicators for the given time.
How is it possible to get this?

Thanks for the help!

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Live trades will not happen "exactly" at the candle's open date - but a few seconds later (simply because in reality, time passes, where backtesting only simulates this).

Freqtrade provides helpers to move dates to the candle start (e.g. `timeframe_to_prev_date`) - which i guess should help you move the trades to the correct location.

**Comment by szucsaaron2** [comment]
Thank you!
