### ISSUE TITLE
Abort trades in downtrend (Forecast)

### ISSUE THREAD

**Issue by eleyvapro** [freqtrade/freqtrade#5016]
## Describe your environment

  * Operating system: macOs 11.2.3
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3

Hi fregtraders,

After this dumping weeks dealing with Elon's tweets, I realised that most of the time the protections were kinda useless, of course this depends on your configuration, but according to an strategy with generous **populate_sell_trend** and **custom_stoploss** it could end up with many open trades and only after it closes the position the protections will help you but maybe too late. I know this is how works and Im not against that, on the contrary, but why not to forecast and avoid buys when the market is having downtrend (because your strategy).

I did a kind of protection for skipping trades which are already populated for being open, according this I got a little better performance in each of my strategies in backtesting:

~~~
"forecast_buy": {
    "enabled": true,
    "open_trades_threshold": 0.55, =>  open trades reach this threshold according to max_open_trades
    "neg_trades_threshold": 0.4, => max open trade negatives to consider to skip new one trade
    "profit_limit": -0.015, => profit to consider negative in downtrend
    "time_from": 5, => considering negative open trades after 5min
    "time_to": 60 => considering negative open trades till 60min
  }
~~~

For instance, the configuration above for a max_open_trades = 25:

**_Scenarios when ignore new trades:_**
case 1 => 5 negative trades of 13 currently total open with -1,5% or less profit within (after 5min to 60min)
case 2 => 10 negative trades of 25 currently total open with -1,5% or less profit (after 5min to 60min)
case 1 => 7 negative trades of 18 currently total open with -1,5% or less profit (after 5min to 60min)

**_Scenarios when will still open new trades:_**
case 1 => 9 of 10 negative trades from -1,5% or less profit (after 5min to 60min) **cause**: open_trades_threshold not reached
case 2 => 10 of 25 negative trades with -1% or positive profit (after 5min to 60min) **cause**: profit_limit not reached

What do you think guys? is there already something in place in the project which I missed? maybe Edge can achieve the same thing... by the way I can share my code if you think it is useful, part of this code is placed in 
**FreqtradeBot::execute_buy** and **IStrategy::confirm_trade_entry** which is critical location for heavy computation and I pretty sure that you can do it much better including it in a proper place, Python is just my 2nd language and just for fun, so my expertise here is limited.

Cheers

**Comment by xmatthias** [comment]
`execute_buy` is definitely the wrong point to place this.

To me, this sounds like it will be very specific to your particular strategy - and will most likely fail on many others.
It'll be quite risky to remain "stuck" in a downside trade - which is preventing other trades (which might be highly profitable) from succeeding.

As such - i don't think it'll be a good fit for the framework. It MIGHT work for your strategy - but i think it can also cause a lot of "missed profitable buys" - obviously depending on the strategy that's being used.

**Comment by eleyvapro** [comment]
That's interesting, you talk about preventing other trades with "highly profitable" so what do you think the protections do when stops the bot? so your explanation about this feature wouldn't fit, I could say the same thing for protections, though.

But I going to give you reasons why protections feature is actually worse and I would prefer using forecast rather than protections
- Protections stops buys for a fixed period of time, "preventing other trades" even if the market is recovering.
- Forecast skips buys if your are having false positives buys, so if the market suddenly change automatically will be able to buy again because the criteria of your current stake list has changed (neg_trades, profit_limit, time...)

Another topic here to take in consideration:
- Correct me if im wrong, this framework has a big limitation, you cannot have more than one stake_currency or free pair stakes. That means: you will never trade something like that (ETH/BNB, BTC/ETH, BTC/USDT) in the same bot, which complete transforms your "highly profitable" in "lucky profitable" just because you have the same reference coin to trade with, and no way to take advance of some of then. for instance your stake is BNB, if it goes down, all your pairlist can forget the idea to have a good profit.
- but there is another reason, everybody knows that crypto market is specially sensitive to downtrend/uptrend with BTC, which are the chances to have a pair with a complete opposite direction to the rest of the pairs? so yeah again "highly profitable" becomes in "remotely profitable"

**Comment by xmatthias** [comment]
maybe you're misunderstanding me.

I'm not saying this can't provide you benefits - but it can easily be done in the strategy (`confirm_trade_entry`) and does not require any changes to the freqtrade codebase - and results WILL depend on the strategy used - not every strategy will benefit from this.

Also - the "reliance" on BTC pairs can easily be covered by having BTC/Stablecoin as Informative pairs, looking at this.

---

If you think it is a must to have this in freqtrade as "X" cannot be done in the strategy, best submit a Pull request which contains that part so we can discuss.

it should be a minimal implementation (readable code, not 1000nds of lines) - while providing a lot of flexibility.

Please note: To consider it for merging - the PR **must** include tests and documentation, otherwise it might get accidentally broken, and noone will know it even exists.
If you're unsure with tests, we can help with this eventually - but the majority of the work is expected to be done by the PR submitter.


> Correct me if im wrong, this framework has a big limitation, you cannot have more than one stake_currency or free pair stakes

You can run multiple bots to circumvent this limitation. Having this in instance bot would increase the maintenance effort and complexity.
Since this is a free, open source bot (with people using their free time to work on it), i don't see this happen - as time is limited - therefore unnecessary complexities must be avoided.
