### ISSUE TITLE
EnsembleStrategyV1 not working in dry mode but does in backtesting

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#5065]
* Operating system: Windows 10 Pro 20H2
  * Python Version:  3.8.5
  * CCXT version: 1.50.6
  * Freqtrade Version: develop-74d75599
  
Hi all, I'm trying to run EnsembleStrategyV1 (attached). This attempts to use multiple strategies and selects a subset to generate buy signals and another subset to generate sell signals. The first question would be, is this a fundamentally sound thing to do?  Because in backtesting it produces _insanely_ good results. If it is OK in backtesting, is it OK in dry or live modes?

If the answer above is yes to all (and I'm a little skeptical because of the results which blow all other strategies clean out of the water) I'm having difficulty getting it to work in dry mode, there seems to be a problem with informative pairs in not having candle data available. It appears to be OK if I use strategies that don't have informative pairs, it also works in backtesting with all strategies being the same in that it produces the same result as one single strategy being backtested. I've attached the error which just continually repeats in the logs. Any insight into this? Thanks!

[EnsembleStrategyV1.py.TXT](https://github.com/freqtrade/freqtrade/files/6576263/EnsembleStrategyV1.py.TXT)
[informative_pair_error.txt](https://github.com/freqtrade/freqtrade/files/6576272/informative_pair_error.txt)

**Comment by perkmeister** [comment]
This can be removed now

**Comment by xmatthias** [comment]
your strategy needs to collate all other strategies informative pairs - freqtrade will only call the strategies method to get informative pairs - not all others too (freqtrade doesn't know WHAT you do in your signal generation).
As such, the strategy must make sure that freqtrade is aware of ALL informative pairs that are eventually needed.

Apparently, the strategy doesn't do that - therefore the data is not available.

As most strategies do a bad job at checking if data is actually there - it'll simply fail - instead of failing gracefully - but the result is the same - it simply doesn't work...

**Comment by perkmeister** [comment]
Thank you Matthias, this is very useful information. Sorry for seeming to be too needy, I need to learn more python think ;)

**Comment by perkmeister** [comment]
Just to let you know, I think this is fixed by adding the following to the strategy:

    def informative_pairs(self):
        pairs = self.dp.current_whitelist()
        informative_pairs = [(pair, self.informative_timeframe) for pair in pairs]
        return informative_pairs
