### ISSUE TITLE
fiat-convert: coingecko symbols are not unique

### ISSUE THREAD

**Issue by bzed** [freqtrade/freqtrade#5080]
## Describe your environment

  * Operating system: Debian testing
  * Python Version: 3.9.1 (`python -V`)
  * CCXT version: doesn't matter (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

While working on #5067 I've discovered that the coingecko coin list has duplicated symbols

```
In [7]: from pycoingecko import CoinGeckoAPI
   ...: cg = CoinGeckoAPI()

In [8]: a=cg.get_coins_list()

In [9]: b = [x['symbol'] for x in a]

In [10]: len(set([x for x in b if b.count(x) > 1]))
Out[10]: 747
```

https://github.com/freqtrade/freqtrade/blob/a0893b291a099b928ced567b9ef81f2d2795717a/freqtrade/rpc/fiat_convert.py#L54 also wrongfully assumes that the symbols are uniqe.

I've added a hand-hacked workaround for the symbols from binance in #5067 - but a more general solution might be needed.

**Comment by xmatthias** [comment]
I guess you should rather raise this against either the PyCoingecko repository - or better yet with support from coingecko (but i doubt either of them will do anything for this, as it's a problem of no standardization across the crypto space).

Crypto symbols are (in some cases) not unique - and the same coin can be called A on one exchange, and B in another exchange. 
This can happen with small tokens (atm - which can be "Africa to Mars" and "Atletico Madrid Fan Token") - but sometimes also affects bigger tokens, if they are listed with different names on different exchanges.

We will definitely not have this list hand-coded / hard-coded anywhere - as it will be outdated tomorrow, as exchanges list coins all the time.
If you think that's a requirement - will you commit to keeping this list uptodate (for all supported exchanges) ... otherwise, that's clearly a no-go.

**Comment by bzed** [comment]
Well clearly not PyCoingecko's fault.

What would be the best fix imho
- get the marketcap for duplicate symbols
- remove all with marketcap == none
- for those that are left, use the higher marketcap.

Thats a few lines of code, with a result that could be cached for a longer time.
I'd be happy to write that, just not sure what the best place for it is.

In the current state, fiat conversion for some well known coins will give awkward results.

**Comment by xmatthias** [comment]
where marketcap == none - sure - these can be dropped easily (you should also check for `market_cap == 0.0` - this seems to be prevelant ...)

I'm unsure about the 3rd point. 
Assuming we have 2 coins with different marketcaps - what makes the "higher" market-cap the right one?

In my understanding, it'll depend on the exchange - and picking the "wrong" one might lead you to trade a coin with a market-cap of a few 1000$ - instead of the one with millions - simply because the "guess" was wrong. 

It's safer to remove these completely if we can't be sure which one is traded on this particular exchange.
