### ISSUE TITLE
Allow VolumePairList filter during BuySignal calculation in Backtesting

### ISSUE THREAD

**Issue by bilal-amsterdam** [freqtrade/freqtrade#5105]
I have an idea to get backtesting result a bit more representative for the behavior in dry-run / live. I am curious what you think of it.

The idea is to allow the VolumePairList filter to work in backtesting (which is currently no supported). Not for filtering the pairs before the logic calculation but as part of the calculate buy signal of the dataframe. Using OHLCV data of the candles, freqtrade knows for each pair what the volume was in a candle. The system can then calculate for each candle, what the volume was for that pair for the last X candles. It can then also order the pairs using this calculated volume. Freqtrade can then only allow buy-signals to lead to an actual trade is the volume-based rank of the pair is lower than the amount of pairs defined in the VolumePairList filter.

This reason for this change concerns the pair selection and the fact that for backtesting we want a set of pairs that cover different behaviours. This however leads most of the times to a pairlist which is larger than we would use when using a dynamic filter in dry-run/live. So for instance the pairlist iterativ is using for backtesting consists of 97 pairs, while if we go live, we might limit it to a dynamic list of 40-60. Because the list is larger in backtest than in live, we will get more buy-signals in backtesting than in live, which will not give representative results. You can off course compare strategies with each other even if the pair list is too large, so the result are still good for strategy building/comparing.

If you take in the backtest list as many pairs as you would filter in live, this is also not representative, since in live situation you probably take the top 40-60 pairs volume based, and freqtrade refreshes continuously, while in backtest you have 1 list for the whole backtest period, which could cover months. So the backtest list would not contain the top coins for each day of that period, which would lead to too few buy signals or buy signals you would normally not have since these pairs would be filtered out.

The above change would allow you too put as many pairs in the backtest list as you like, to cover all behaviours in the backtest period, but still get a representative amount of buy signals as when you would get in dry-run or live. It would emulate the behavior of the dynamic filter used in live in the config file better I think.

**Comment by bilal-amsterdam** [comment]
Apologies if this is not the correct way to input it. First ever issue on Github.

**Comment by xmatthias** [comment]
You'll run into memory / performance issues with this very soon.
To "really" cover how volumepairlist works, you'll need to use ALL available pairs on binance (for USDT stake, that's currently 271 pairs).

While not all of them will have decent volume now, many will have had that in the past.
So to reliably backtest with a volumepairlist of say 50 active pairs for a year - you'll still need to have, and load, (and calculate) the data for all 271 pairs.
Otherwise you might pick 100 pairs - but just because their volume is high now, doesn't mean it was half a year ago, so the pair with the lowest volume today  might've been in the top 10 half a year ago (and yes, these things do happen).

As such - you'll run into performance issues - backtesting will start to take a very long (analyzing 271 pairs to get a backtest of 50 pairs will take quite a long time - depending on the indicators used).


To me, it seems like a "nice to have" - but dangerous to have wrong (which will lead to missleading results) - and probably not worth the time investment to develop this.

If you think you must have this, feel free to submit a Pull request (it'll have to include tests and documentation - at least before being merged)  - but i'll surely not spend time on this as the benefit will be questionable.

**Comment by bilal-amsterdam** [comment]
Thanks for your reply and many thanks for this great product!

I understand your point. For the purpose of strategy development and strategy comparison, it is indeed not needed to have this feature. And I also see the risk in performance and the fact that it would only work if we use all pairlists (which would have backtesting take too long).

Taking this into account, I will close this issue.
