### ISSUE TITLE
Showing on CAGR and MDD in backtest results

### ISSUE THREAD

**Issue by systemquant** [freqtrade/freqtrade#5106]
This is a very simple enchantment, but I think it is so helpful for intuitively comparing strat's performances.

<img width="656" alt="Example" src="https://user-images.githubusercontent.com/85345804/121263953-5bef1200-c8f1-11eb-9e71-89b45f29d48c.PNG">
Such as this image, showing CAGR and MDD is extremely intuitive for comparing strategies, higher CAGR(profitability) and lower MDD(risk) is better!

It's about showing CAGR (geometric mean of yearly profits, `(current total stake)/(starting wallet)^(1/years passed)`, (simply,) years_passed = days_passed/365)  and MDD (`((strat's)max - min / max) * 100%`, currently freqtrade has the _drawdown_, but it is unintuitive because it gives ratio based on starting wallet stakes).

This will make freqtrade's backtests look more intuitive and easier to compare strats.
How do you guys think about this very little enchantments?

**Comment by systemquant** [comment]
~~_**Consideration:**_ (this is not essential)
Maybe adding the sharp ratio for backtest can be also good. And we have codes in the hyperopt so all we need to do is just using that code. But can there be a little performance changes for backtesting? If so, just adding option params(such as --sharp true) to show sharp ratio might be good.~~

**Comment by xmatthias** [comment]
we do have an issue for sharp already (#1907 ) - but so far, it was not important enough for anyone to actually spend time to implement it.

We have a section for strategy metrics - i'll surely not mind having others added there as well if they make sense.
I'm however not sure what MDD will be based on - you say "max - min / max" ... but max / min of what? absolute wallet? relative profits ... you can do min/max calculations on many things - so it's kinda unclear to me for now how this calculation should look like.

**Comment by systemquant** [comment]
That means absolute wallet including current open positions(maximum total stake - minimum total stake / maximum total stake)

I think it has already there named max drawdown high and low. That will do exact thing. 
The problem of current drawdown ratio is it is calculated through (high-low / starting stake) but it is not intuitive because profit compounds, so if drawdown happened later on, it gives bigger ratio, so it highly depends on when max drawdowns happened. So adding one more metrics that does not influenced by compounding. (And I found this exact thing extremely useful in other systemic trading tools, they are using it too.)

![1](https://user-images.githubusercontent.com/85345804/121329020-c9319000-c94f-11eb-94c5-42f5bf9f4354.png)
This means (-)21% MDD 

(And for sharp ratio - I agree it's not a necessary thing. So can bother with it later.)

**Comment by EmbraysiteReal** [comment]
Hello, Guitheg and me have implemented the "MDD". We computed MDD on each trade since drawdown are always linked to a position, then we took the one with maximum amplitude. In fact, we computed de maximum MDD in the set of trades.

With our function, people can see the worst drawdown among all their trades.

systemquant : We didn't really understand "That means absolute wallet including current open positions(maximum total stake - minimum total stake / maximum total stake)".
Do you mean considering the value of all position (in USDT for exemple), sum them all to make a function that fluctuate like crypto market curve then compute a "MDD" on it. By the way it won't be a true MDD but it could be interesting

We doing the pull request right now
EDIT : The issue is not closed since CAGR is not implemented yet
