### ISSUE TITLE
Returning buy price for previously made trade

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5120]
## Your question

Hi!

My question is, is there a way to get the price of a previously made trade, and then use it in a strategy?
So for example, my strategy buys BTC at 12:00, and it is holding it. And then at 12:10 my strategy calculates all the indicators plus also retrieves the price of when the trade was made.

Best wishes!

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) is your friend and does cover this.

It should be noted that the method documented there shall not be used in any `populate_*` method (at least not in backtesting), otherwise backtesting will no longer work (this data is not available during the populate stage of backtesting).
