### ISSUE TITLE
Could not fetch historical candle (OHLCV) data for pair

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade#5124]
* Operating system: Ubuntu 22.01
  * Python Version: 3.8.10
  * CCXT version: 1.50.70
  * Freqtrade Version: develop
  
I'm getting the following messages occasionally when downloading data. Does this mean that there will be missing data? If so, will 'freqtrade download-data' without specifying dates fill in this missing data, or only append data from the last datetime? Is there an existing programmatic method for checking for missing data?

freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USD due to ExchangeNotAvailable. Message: coinbasepro GET https://api.pro.coinbase.com/products/BTC-USD/candles?granularity=60&start=2008-01-11T07%3A00%3A00.000Z&end=2008-01-11T12%3A00%3A00.000Z"
freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times

**Comment by xmatthias** [comment]
Freqtrade will retry these calls 4 times (with incremental backoff) - assuming that it's a temporary exchange hickup.
Obviously if the subsequent calls also fail, you'll have a problem - but that usually only happens if rate-limits are configured wrongly (to low), or if the exchange is down at that point in time.

As such - there shouldn't be a problem with it.
