### ISSUE TITLE
Weird Hyperopt Results

### ISSUE THREAD

**Issue by theway0007** [freqtrade/freqtrade#5136]
## Describe your environment

  * Operating system: CentOS 7 VPS
  * Python Version: Python 2.7.5 (`python -V`)
  * CCXT version: ccxt==1.51.3 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-e2bbc0a (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I am having weird hyperopt results in the meantime. Would like to know is this normal? I am running 200+ currency pairs with 1m chart for 100 days.

![Screenshot 2021-06-15 044751](https://user-images.githubusercontent.com/85905507/121957756-6ac44180-cd95-11eb-9bb8-b41df4c8c309.png)

**Comment by xmatthias** [comment]
without seeing the parameters it's difficult to tell for sure - but i'd suspect that you're using compounding (stake_amount=unlimited), which can show pretty high results - simply because the last few trades have insanely high volumes (which would not be tradable, most likely).

Most likely, hyperopt is then picking either a very low positive ROI - or very tight trailing stoploss parameters - both of which can cause inflated results.

In the end, [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) apply also to hyperopt - so you should check that the resulting parameters are somehow sane.

**Comment by theway0007** [comment]
Yes I am using stake amount to unlimited. What's the best amount to set? Because I only make 1 trade at a time, which I would want all fund be in it.

**Comment by xmatthias** [comment]
stake_amount=unlimited is fine as long as your strategy is not exploiting one of the backtesting assumptions (which based on your results, your strategy most likely is).
