### ISSUE TITLE
Would strategy still work correctly if the buy signal generating indicator is only generated for the last row of data?

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5138]
## Your question

Hi!

My strategy takes a long time to run, and somehow I would like to increase its processing time. The indicator that I am generating which also creates the buy signal takes a longer time to create. 
My question is would the strategy still be functioning properly if I only generated the buy signal based on the last row of data?

I remember testing this previously and the backtesting was not functional in this case, but would it still work in live mode?
Or is there a way to reduce the size of the dataframe that is given to the strategy?

Best wishes and thank you for your support!

Áron

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
for backtesting it'll definitely not work as that needs the full dataframe populated.

For live - sure, it'll work (but freqUI plotting won't have any buy signals - but there's no "operational" problem other than that).
Make sure to not reduce the overall size of the dataframe though - but to only assign where needed. 

You'll also need to be careful to not "just" use the last candle unles you're very sure that works for your indicator.
Most indicators need a certain lookback (which is not always obvious, especially from 2nd level MA's) - and since it's "specific" to live - you'll need to make sure to somehow test this too.

**Comment by szucsaaron2** [comment]
Thank you!
