### ISSUE TITLE
Bot does not handle open trades in live

### ISSUE THREAD

**Issue by lyncker** [freqtrade/freqtrade#5144]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Inside Dockercontainer
  * CCXT version: Inside Dockercontainer
  * Freqtrade Version: freqtrade docker-ba106e6c
  
I have a live bot running since some weeks... beside all the trades which are bought and sold usually after some hours , there are 2 trades not beeing sold after more then 3 weeks.... 
Now I tried a /forecesell ID but the bot does not react ... all other commands are beeing handled as normal and the bot is trading as normal. Then I had a look at binance and I found out that one of these both trades does not exist. 
How can I handle this ? Should I go in the SQLIte file and delete these trades manally and sell the one stake by myself?

**Comment by barisengez** [comment]
you may use the command
/delete <trade_id>

**Comment by BobbyBobbyTheBobBob** [comment]
https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange

I just read that 10 minutes ago.

**Comment by barisengez** [comment]
> https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange
> 
> I just read that 10 minutes ago.

even better

**Comment by xmatthias** [comment]
@lyncker please check the logs on WHY it's failing to sell the trade.

Most likely reason: Half-bought - so the amount is too low to be sold on the exchange (you'll also not be able to sell that manually on the exchange) - or a "lost" order which is still on the exchange locking up the funds - although i doubt that as we have methods to detect and "refind" an order.

Either way - the logs will tell you what the reason is (i'd be careful with simply removing trades "blindly" ... and always want to understand why ....)

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
