### ISSUE TITLE
Buy and sell reason statistics in backtest results

### ISSUE THREAD

**Issue by barisengez** [freqtrade/freqtrade#5168]
**EDIT :** Just found out this is the exact duplicate of 3 months old #3081 which is closed
But maybe I can convince this time :)

**Current situation:** Today I saw someone trying to add extra indicators to detect which buy signal is triggered for which trade and another person also asked if we could see which trade is triggered by which buy signal. Also I see on famous iterativ strat NFI that he is assigning sell reasons in custom sell to get some kind of statistics on backtest. 

**Problem:** In recent strats, there are usually more than one buy and sell conditions. People (including me) starts asking which condition triggered the trade or what are the statistics of different buy/sell conditions in backtest. 

**The workaround :** adding the conditions as indicators and plotting the backtest with boolean subplots for each condition

**Proposal:** So I came with an idea of adding an extra "reason" column to strat cycle result: something similar of custom sell reason.

It will be an optional free text reason column that people can state and it will be shown on 2 extra tables in the backtest results identical to sell_reason table. lets say buy reasons and sell reasons and custom sell reasons will stay as a renamed custom sell reasons table for back compatibility.

```
# Indexes for backtest tuples
DATE_IDX = 0
BUY_IDX = 1
**BUY_REASON_IDX** = 1,5 (joking ofc :) it ll go +1 incrementally)
OPEN_IDX = 2
CLOSE_IDX = 3
SELL_IDX = 4
**SELL_REASON_IDX** = 4,5
LOW_IDX = 5
HIGH_IDX = 6
```

**Conclusion:** What do you think in general? If its plausible, lets elaborate.

**Comment by xmatthias** [comment]
#3081 is not closed but an open issue labeled as enhancement - which makes this in fact a duplicate (as such - i'll close it as there's no point in having the same issue there twice).

If you think it's needed - feel free to provide a Pull request for it (please including tests and documentation).
Otherwise - subscribe for the duplicate issue for updates on this topic - maybe someone else will be motivated to pick this up and implement it (it's not on my personal "todo" agenda for the moment).

**Comment by barisengez** [comment]
i got confused with status of another dupe sorry #5058
