### ISSUE TITLE
Batched Hyperopt

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade#5169]
I there a way to batch hyperopt for use on multiple computers. I see this, https://github.com/freqtrade/freqtrade/pull/2951, Is there a way to continue hyperopt after a power failure, etc?

**Comment by xmatthias** [comment]
Hyperopt cannot be continued - but it's often also better to start from scratch instead of doing 1000nds of epochs - as then you'll get a new random point.


It's based on scikit-optimize / scikit-learn - which as far as i know, cannot be scaled out across multiple computers - as such, i'd say no, that's not possible (especially considering that the bayesian search algorithm is not parallelizable, and therefore must be done on one core ).
