### ISSUE TITLE
Skipping TA Analysis for already analyzed candle

### ISSUE THREAD

**Issue by Borstinator** [freqtrade/freqtrade#5213]
Ubuntu 20.4
freqtrade 2021.6 (Docker)

Hey guys,
I've analyzed the loop of my bot with verbose enabled and saw a strange behavior in the logs. I use a timeframe of 5, 1h informative and 80 pairs. So every 5 minutes the bot fetches all my 80 pairs, convert the candles into dataframes, and then launches the TA Analyses.

At this point, I've noticed that the bot skips a few pairs. "Skipping TA Analysis for already analyzed candle". The bot goes on and checks for buys/sells and ends the loop.
Surprisingly now the bot starts another loop and fetches, converts, and analyses the skips pairs.

The skipped pairs seem to be random and change every 5 minutes. But I don't know why the bot skips the pairs in the first place. It has all the data downloaded and converted into dataframes.

Example:
https://github.com/Borstinator/test/blob/main/freqtrade.log

The first loop at 10:55:04 skips: SC/USDT, STMX/USDT,IOTX/USDT,ENJ/USDT,SUSHI/USDT,DENT/USDT,ZEN/USDT,MKR/USDT,COMP/USDT
which are then loaded and processed again in a second loop at 10:55:31

**Comment by xmatthias** [comment]
it's pretty simple - freqtrade will fetch data for all pairs in the first iteration - look at the last date to determine if it contains the last closed candle already. If it doesn't - it'll be "skipped" in this round - and will be analyzed in the next round.

it's a timing question in the end (all pairs are fetched asyncronously,so you won't really know which one is pulled first). 
If timing "falls" right onto the "new candle" second (:00) - it might be that for some pairs, it'll still get the old candle, while for others it get's the new candle (also async cals need to respect ratelimits ...).


There's 2 things that can affect this - both are from the exchange side (i'm not sure which ... as i never dove that deep into it - and i'm also not 100% sure how much sense such an analysis would make):

* exchanges only publish the new candle once the first trade in the new candle happens (otherwise there would be no valid open price)
* Exchanges may be late publishing the new (unfinished) candle.

Now personally - i suspect it's 1 - as i've mainly seen this on low-volume pairs ... but in theory, it could also be the 2nd pair.

**Comment by Borstinator** [comment]
Thank you for the detailed answer. :)

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
