### ISSUE TITLE
Mode to allow startup candles sent to populate_*_trend()

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#5242]
Would it be possible to have a user selectable mode that sends startup candle data in the dataframe that is passed to populate_trend() methods during hyperoptimising? This would allow indicators to be calculated from within those routines, and that would mean you could use  .values passed by hyperopt in the indicators without nested for loops or creating a large number of columns. A simple conditional inclusion of indicators in populate_indicators() or populate_trend() depending on whether hyperopting or not could allow normal startup candle free dataframes in other run modes. It could make it a lot easier for strategies that, for example, have multiple parameters in indicators like MACD to be hyperotable. I realise this may slow things down somewhat, but simplifies things. Interested in your thoughts.

**Comment by xmatthias** [comment]
Considering that we have the `.range` attributes now (in develop for now) for all parameters (except for `RealParameter`) - i don't see why this should be necessary. 
Having this possibility will only lead to bad practices.

Think about a simple case - you have "a few" parameters to optimize (say 3).
One of these is RSI between 20 and 40 (so a space of 20 parameters).

By calculating the 20 columns in `populate_indicators()` - you calculate each of the RSI's exactly once - no matter the epochs.

Now by moving this to the `populate_buy()`, you'd calculate it once every epoch. 
Assuming you run it for just a few epochs (say 100) - you'd be calculation 100x RSI (instead of 20x). Of these 100, there'll be a LOT of duplicate calculations - maybe because hyperopt finds rsi30 to be a sweet-spot - and does 60 of these epochs with an RSI of 30, modifying the other 2 parameters in the space.

**Comment by perkmeister** [comment]
Thanks Matthias. The analysis is good for indicators that have single parameters, but not for things like MACD which has 3. if the space sizes were say 20, 20 and 10 for such an indicator it would need 3 nested for loops and 4000 calculations, the number of calculations scales geometrically with the number of parameters used in the indicators and a very large proportion of those wouldn't get used at all. In that case calculating indicators in the trend methods becomes more efficient as that scales arithmetically with the number of epochs. 

Just a thought, someone has already posted a solution that involves adding the startup candles to the dataframe passed to the trend method, calculating the indicators, stripping the startup candles out again then doing the trend buy and sell calculations before passing the dataframe back to Freqtrade, I was just wondering whether it's worth natively supporting that.

**Comment by xmatthias** [comment]
After further consideration, i guess you're right (not just for your usecase, but in general) - startup-candle-count should be left in for all `populate*()` methods to prevent surprises - as we can't know (and technically don't care) what will be used within these methods.

#5285 will close this.

**Comment by perkmeister** [comment]
OK, thanks!
