### ISSUE TITLE
custom_stoploss can only increase

### ISSUE THREAD

**Issue by 010011x** [freqtrade/freqtrade#5249]
I'm trying to understand how **custom_stoploss** works, but I don't understand this. 
Documentation states that stoploss can only increase. What does it mean, when absolute value of return is used.

For example, in this example https://www.freqtrade.io/en/latest/strategy-advanced/#time-based-trailing-stop, stoploss is going in this direction.

[initial stoploss] -> [-0.10] -> [-0.05]

In this example, stoploss is going like this https://www.freqtrade.io/en/latest/strategy-advanced/#stepped-stoploss

(I assume those are trailing stoplosses below)

[initial stoploss] -> [0.2-0.07=0.13] -> [0.25-0.15=0.1] -> [0.4-0.25=0.15].

In some examples **custom_stoploss** returns -1 or 1 to keep using the initial or current stoploss value. I'm completely lost. In what direction can I change my stoploss ?

**Comment by xmatthias** [comment]
custom_stoploss returns a relative value to current price.
So by returning -0.10 - you're placing your stop 10% below the current price.

The stop can however never move to lower values once it reached certain values (this is however absolute values).

Assuming you constantly return that value - you're effectively simulating trailing stop to some degree.
As price raises - your stop will follow with a gap of 10%.
Once price falls however, the stop will remain  that location.

So assuming you buy at a rate of 100$ - and price raises to 110$ - your stop would be at ~100$.
If price now returns to 105$ - your stop will still stay at 100$ - and as such - will never be lowered again (otherwise it would not be a stop - but would move in parallel to the price - and would potentially never trigger.

hope this makes sense.
