### ISSUE TITLE
Installation failing on Ubuntu 20.04 on Raspberry pi

### ISSUE THREAD

**Issue by meauxt** [freqtrade/freqtrade#5253]
Unable to install Freqtrade on ubuntu 20.04 ( HW Raspberry pi 4 8GB)
## Describe your environment

  * Operating system: Ubuntu 20.04 Server for raspberry pi 
  * Python Version: 3.9 (`python -V`)

  
## Your question
Running ./setup.sh --install failing with the error below
```

Collecting tables==3.6.1
  Using cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/freqtrade/.env/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4lqe5mby/tables_fc9047b0a7c1409cb0e0d9e44bd0a7cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4lqe5mby/tables_fc9047b0a7c1409cb0e0d9e44bd0a7cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zp9lfx0m
         cwd: /tmp/pip-install-4lqe5mby/tables_fc9047b0a7c1409cb0e0d9e44bd0a7cd/
    Complete output (12 lines):
    /tmp/H5closesqczs4q1.c: In function ‘main’:
    /tmp/H5closesqczs4q1.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
        2 |     H5close();
          |     ^~~~~~~
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.9.5 (default, May 11 2021, 08:20:37)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1 (from versions: 2.3, 2.3.1, 2.4.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0rc1, 3.2.0rc2, 3.2.0, 3.2.1.1, 3.2.2, 3.2.3, 3.2.3.1, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.1, 3.5.2, 3.6.1)
ERROR: No matching distribution found for tables==3.6.1
Failed installing dependencies
```
Anyone faced this issue ?seems i need to open issue on tables. but just want to see if anyone was able to overcome the issue. please advise

**Comment by xmatthias** [comment]
The setup script assumes you're running on a platform that has wheels available, which are not available for python 3.9 on ARM.

As such - you'll need to have install dependencies. You're getting the error for hdf5 now - no need for an issue there, just lookup and install their development dependencies.
I know already however that this will not be the only error - and that further dependencies will most likely also fail (unless you have the required dependencies installed accidentally).

For a raspberry, the setup-script will only work when using python 3.7 (which is the default on raspbian) - not having a newer python available - and being on a raspberry image in 32bit mode.
Using any other operating system on a raspberry (other than raspbian) is not supported and on your own risk (which basically means - if things like this break - we will advise to use the supported version).

The recommended (and fastest) install method on a raspberry (and otherwise) is docker - as that will come prebuilt (again, not in arm64 mode).

**Comment by epigramx** [comment]
The default is 3.8 on Ubuntu 20.04, I guess they went out of their way to install 3.9.

**Comment by meauxt** [comment]
cool! will use docker then for now :) Thank you
