### ISSUE TITLE
Move Freqtrade from my PC to my VPS

### ISSUE THREAD

**Issue by quycmf8** [freqtrade/freqtrade#5254]
Hey guys!

Recently, I have done my test and let Freqtrade ran with real trade under my PC over 1 month. The result still very good so I decide to move Freqtrade from my PC to my new VPS.

The question is how can I move with all the data (current trade)  from my PC to my new VPS. Can you help me?

**Comment by xmatthias** [comment]
what you'll need is your strategy, configuration file(s) - and your trades .sqlite file.

Depending how you run freqtrade, these files will either be in the "current directory" - or in user_data - so you can simply move these files to the VPS.
Be sure to stop the local bot before starting the cloud bot, otherwise telegram will not like it.

**Comment by quycmf8** [comment]
OK. Thank you Sir!
