### ISSUE TITLE
Filter epochs to save when hyperopting to avoid excessively large files

### ISSUE THREAD

**Issue by Merinorus** [freqtrade/freqtrade#5305]
Hello,

Following issue #4950.
I've faced out of RAM issues when using hyperopt-show because I've run thousands of iterations.
Is it really useful to keep a track of all iterations?

I was thinking of a script that would lighten the .fthypt file by keeping, let's say, the 100 best epochs.

Wouldn't it be useful to add a parameter to the "hyperopt" command like --max-epochs-to-save (default : 100) in order to avoid excessively long files?

Or, maybe we should just not exceed 1000 epochs because it wouldn't be worth it according to the documentation?

Thank you!

**Comment by xmatthias** [comment]
I'm yet to see how big the `.fthypt` file is getting to cause this issue (maybe you can run a `ls -l` or `ls -lh` on the file to show me how big it really becomes - as i suspect something similar in #5149 - but never got a response.


To be honest, the documentation alrady recommends to use no more than 1000 epochs ([in the FAQ](https://www.freqtrade.io/en/stable/faq/#hyperopt-module)), and instead run hyperopt multiple times - and i doubt that you'll get the problem with only 1000 epochs.

---

Not storing all epochs can be problematic for multiple reasons - so that's definitely not a way i'd pursue.

first of all, you'll need to store the first 100 epochs anyway (as you'll not know what comes after).
As such, we'd then need to (for each epoch!) read all epochs - determine which ones are worth saving - and then save the whole file again.
This will have quite some impact on hyperopt (disk-operations are always slower than in-memory operations) - and it'll also put unnecessary strain to the disk (now we're appending to the file - your proposal would mean rewriting the whole file each time).


The other aspect is that if you're running 10_000 epochs  - you might end up with a few 100 "best" epochs that are quite similar (have very similar win/loss ratios, ...). 
This can be enforced / weakened by the loss function used - but experience has shown that after ~1000 epochs hyperopt often reaches a local minima and won't improve significantly afterwards.

As such - we'd store 100 "very similar" seemingly best epochs (best is determined by the loss function) - while maybe epoch 150 (in the sorted list of "best" epochs) would show what you're looking for (better win/loss ratio, more (or fewer) trades, ...).
I've quite often found myself go through the list and pick a "different" epoch (maybe one that wasn't labeled as "best" - simply because that had 100 fewer or more trades (which is what i was looking for in that particular strategy).

Therefore, you've now "lost" your potentially best epochs (assuming you read through the logs) - simply because they were never stored due to your loss function deciding they're not important to you.

**Comment by Merinorus** [comment]
Thank you for your insightful reply!
Indeed, the file becomes pretty big, about 4 GB. I'm on Windows 10, 16 GB RAM, freqtrade is running on Docker Desktop for Windows.
The "hyperopt show" RAM usage keeps increasing until all my RAM is used, then it crashed eventually.

As you say, it makes sense to use a maximum of 1000 iterations several times, each time with different spaces (buy, sell, roi... not everything at the same time).
