### ISSUE TITLE
implement function similar to barssince() on tradingview

### ISSUE THREAD

**Issue by duquel** [freqtrade/freqtrade#5315]
Is there any way to implement a function similar to barssince() in pine script?

the functions tells how many bars since a certain condition was true.
purpose would be to have that as a trade filter so as not to enter a trade where number of bars since buy signal is less than number of bars of a sell signal so as not to enter in the middle of an ongoing trade.
```
so as to only enter trades where there is a # symbol:
| = bar
||||sell||||||buy(#)||||buy|||||||||||||||sell|||||||buy(#)||||||buy|buy|buy|||||buy||||sell||||

does this make sense?



<!-- 
Have you searched for similar issues before posting it?
Did you have a VERY good look at the [documentation](https://www.freqtrade.io/en/latest/) and are sure that the question is not explained there

Please do not use the question template to report bugs or to request new features.
-->

## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well technically, it's a simple pandas dataframe - so i think a well formulated google (or alternatives) search should get you pretty far and get you results like [this](https://stackoverflow.com/questions/56942937/pandas-row-number-since-last-greater-than-0-value) and [this](https://stackoverflow.com/questions/54401636/pandas-number-of-row-since-condition).

now i've tried neither of these solutions - but the solutions look like they could provide what you need.

Feel free to post back with the result of your investigation - so others can benefit from this too.

**Comment by duquel** [comment]
thank you very much! I will check it out when I get to it. Should I close this?

**Comment by xmatthias** [comment]
yeah, I guess we'll close this.

feel free to post below once you've found the answer though - as that will help future users looking for the same :+1:
