### ISSUE TITLE
Questions about 'vendor stuff': qtpylib and pandas-ta

### ISSUE THREAD

**Issue by BillGatesIII** [freqtrade/freqtrade#5343]
I have two questions about 'vendor stuff'.

1. Should I use `import freqtrade.vendor.qtpylib.indicators as qtpylib` or `import technical.vendor.qtpylib.indicators as qtpylib`?
 
2. Is it possible to add the pandas-ta indicators to the vendor section? (https://github.com/twopirllc/pandas-ta).

Thanks.

**Comment by xmatthias** [comment]
for 1 - there's no difference - it's the same file that's there in both libraries - as far as i'm aware they're aligned (i try to keep them aligned).

2) 
it's technically possible to vendor anything - but it does not make sense in most cases.
Vendoring a package means it's up to freqtrade maintainers to maintain the library, make sure it's kept uptodate, and support in case of problems or questions.

The reason to vendor a package / file is because either it's no longer supported (and the library used needs some fixes that are not merged upstream as that is unmaintained), or because the upstream library has huge dependencies which would complicate and increase installation size (which is the case for qtpylib - as well as the fact that it's not actively maintained).

ta-lib on the other hand is not even used directly by freqtrade - so it's up to the strategy/strategy author to determine what packages are used - and eventually install required dependencies.
