### ISSUE TITLE
An additional, more accurate backtest mode supporting intra-candle prices

### ISSUE THREAD

**Issue by joshdifabio** [freqtrade/freqtrade#5367]
## Describe the enhancement

My strategy is performing well, but I'm certain I could get it performing better if I could backtest with intra-candle prices. I imagine many others are in the same boat.

With this in mind I propose a second, much slower, much more accurate backtesting mode which uses trade history APIs to calculate intra-candle prices. This will allow us to accurately simulate the behaviour of trailing stoploss, custom stoploss, and any other features which depend on intra-candle prices. 

I would like this second backtesting mode to mirror live/dry run as much as possible and to share as much code as possible with those modes, rather than the existing backtesting mode. I expect that this second backtesting mode might take tens of minutes or even hours to simulate a single calendar month, rather than seconds or minutes as does the existing backtesting mode. I see these two backtesting modes coexisting.

Some initial ideas:
- Replace calls to `datetime.now()` and `arrow.now()` with calls to some new clock object, which will return the current time in live/dry run modes and the simulation time in the new backtesting mode.
- Modify or extend `Exchange` to add the capability to fetch historical prices (e.g. via aggregated trade history). Fetch several minutes trades at a time and memoize to speed up requests for market price at specific points in time.
- Modify `DataProvider` to fetch historical values rather than current values when running in backtesting mode.
- Download and cache data on disk during backtesting rather than requiring data to be downloaded in advance.

I'm not an experienced Python developer, but I am a professional programmer with many years experience, and I'd be very willing to do the bulk of the work to implement this if it's considered a worthwhile addition to the project. I have some time available to do this over the next few weeks.

**Comment by xmatthias** [comment]
While the idea per se might be worth investigating - the proposed way / ideas don't not make sense.

Downloading trades-data as part of backtesting is a very bad idea (downloading trades-data for a few months and a few pairs will take **days** to download).
We do have `download-data` for this (with the `--dl-trades`) - which is required for kraken - but should work for other exchanges as well (although i never fully tested it there) - so the first step should be to validate that the trades data downloads correctly (without gaps).

There's also no need to replace calls to datetime.now() - as the only thing that's needed to be called will be `should_sell()` - which is not using datetime.now anyway (nothing in backtesting does, really).
As such - backtesting will not "significantly" change - and it will surely not touch freqtradebot nor do inline-calls towards the exchange.

Technically, the only difference to "current" backtesting would be that it'll call the `should_sell` method  100_000ds of times for every 1m candle (assuming there've been 100_000+ trades within that candle) - or at least once for every second (assuming we collate the trades-data to 1s candles).

One problem here will however be the amount of data (current backtesting will require all data to be in memory - and that's unlikely to change - at least not for the "strategy timeframe".

Loading trades on the other hand would have to be batched (load only a part of the available data) - to avoid running out of memory (trades-data is huge!). 

---

A potentially much simpler way for this might be to have a "backtesting timeframe" flag - where your strategy uses a 1h timeframe - but you can specify an additional "backtesting-timeframe" - which will run the simulation at 1m (or 5m or whatever smaller) timeframe.

With that, you'll get "insights" into the 1h candle - without having too much additional efforts in the code.

As a second step, we could (in theory) then "fake" a 1s timeframe (that timeframe usually doesn't exist on exchanges, and therefore must be faked) which is converted from trades data (outside of backtesting / persisted to disk) - which will then give you more insights into the candle - but i'd leave that open for now if that is really a necessity.
While the amount of data will still be huge, it'll definitely be smaller than trades data - where you can have 1000nds of trades per second on main pairs.

**Comment by joshdifabio** [comment]
Some additional context:

- I am trading 100-200 pairs on a short candle duration (5m. I want to use 1m but I can't,  because...)
- Backtesting doesn't work well with lots of pairs and 1m candles, because it requires all the candles to be loaded into memory at once. This prevents me from backtesting more than a few days at once with 1m candles
- My average wins are 1-2% on 5-30 min trades, so improving my custom stop loss performance by ~0.5% has a huge impact on profits when considering compounding

Preemptively loading all data into memory is unfeasible with a lot of pairs due to the implementation choices relating to backtesting mode. Adding historical trades into the mix will only exacerbate the issue.

I want a dry run mode which I can run on historical data at 10-100x speed.

> Downloading trades-data as part of backtesting is a very bad idea (downloading trades-data for a few months and a few pairs will take days to download).

I disagree. The proposed approach allows us to only download a small fraction of trades data, because we will only really need historic prices when deciding whether to _sell_ a pair, meaning we only need historic prices for pairs which we currently hold. Furthermore, we only need these prices every `config.internals.process_throttle_secs` seconds in order to accurately simulate live performance. This means downloading many thousands of times less trades data than preemptively downloading all of it as you propose. Furthermore, we can cache the data locally when we download it.

> A potentially much simpler way for this might be to have a "backtesting timeframe" flag - where your strategy uses a 1h timeframe - but you can specify an additional "backtesting-timeframe" - which will run the simulation at 1m (or 5m or whatever smaller) timeframe.

I thought about this too, but:
- it would be too low resolution to be trustworthy with regards to simulating trailing stop loss
- it would use too much memory to work with lots of pairs, as does the current backtesting mode with 1m timeframes

I think this is worth doing but it will not solve my problems.

The current live and dry run modes work great with lots of pairs on a short timeframe. I want something behaves as similarly to those modes as possible but which allows me to test historic data faster than realtime.

**Comment by xmatthias** [comment]
> it would use too much memory to work with lots of pairs, as does the current backtesting mode with 1m timeframes

this will depend on the implementation.
When using hdf5 as storage format, you can pretty efficiently selectively load data (so you can load 2 weeks of data without ever loading  all 3 years to memory).

Obviously this data will only be loaded for open trades - so i don't see this as a problem.

The mode you're proposing sounds tempting on the one hand - but the benefits will not justify the effort to implement and maintain this (unless you can implement this with a few 10's of lines of code, which i'm you can't, because that's simply not possible).

The main reason for this is that the mode i proposed above (especially with 1s resolution) will give you exactly the same - but without touching the effective order-handling logic (which is irrelevant for backtesting anyway).

---

Your proposal of "download what's needed" will also cause a lot of re-downloading - as i'd assume you'll run this mode, then improve your methods - and then run this mode again. Having the data stored will be a lot faster as you'll not need to respect ratelimits. I understand it'll be a bigger "upfront" commitment - but it'll pay off in the long run for sure.

**Comment by joshdifabio** [comment]
You previously suggested that preloading full trades data for "a few" pairs would take "days":

> Downloading trades-data as part of backtesting is a very bad idea (downloading trades-data for a few months and a few pairs will take days to download).

Extrapolating, this means that preloading trades data for 100s of pairs would take months or more, making it infeasible.

> Your proposal of "download what's needed" will also cause a lot of re-downloading - as i'd assume you'll run this mode, then improve your methods - and then run this mode again. Having the data stored will be a lot faster as you'll not need to respect ratelimits. I understand it'll be a bigger "upfront" commitment - but it'll pay off in the long run for sure.

I already suggested in both of my previous comments that we _cache_ the data when we download it. This would prevent unnecessary re-downloading of data. We would easily achieve a 10x speedup over dry run mode and gain the ability to replay previous days and months.

It doesn't feel like we're really moving forward here, and I don't want to waste your time or my time. I'll solve my own problem and not worry too much about doing the work in such a way that it can be merged back.

**Comment by xmatthias** [comment]
I'm sorry you feel this way. 
It seems like your fixed on your way without accepting any input or other opinion.

> Extrapolating, this means that preloading trades data for 100s of pairs would take months or more, making it infeasible.

Don't flip my words. 
I've said doing this as **part of backtesting** is not feasible - and i stick to that - as it'll mean worst case, you'll be waiting days for your backtest (assuming you have one "long-running" trade).

It is however not a problem to start your data-download once, let it run for a day or two (that's how kraken users need to do their data download (which has INSANE ratelimits of 3.1s per call). 
It's surely taking quite some time (possibly multiple days for 1y of data for a few pairs) - but it's not impossible.

---

if you only download the data you need, caching will be quite difficult to get right - and i'm not sure you'll get acceptable speeds for your simulation either.

Assume your simulation opens a trade on friday, 11AM ... you'll download the next 1000 trades - iterating forward until it closes out.

You then cache this data (from friday, 11am until saturday, 1am).
You slightly modify your strategy, which causes the next run to open at 10am ... you'll now need to figure out how much data you need, and starting from when you already have data.
While possible in theory - trades data is not very reliable (it's different depending on the exchange - sometimes by time, sometimes by id - making detecting the "end point" very difficult - and downloads slow as you can't really parallelize that).

Much worse - you'll end up with trades-data with holes in between (but you'll not really know where the holes are, and can't detect that as there can be periods without a trade).

Assuming downloading of this trade-data (for one trade) takes half an hour ... so you've just spent half an hour waiting for ONE trade (and your strategy of 100 pairs makes 200 trades) - and in the next run, the trade happens a day earlier (due to strategy modifications), you'll wait another half hour (Per trade!).
As such - i still think that doing data-download as part of backtesting is a very bad idea.

it's therefore much more realistic to download the trades-data beforehand - even if that takes a while(and consumes quite some storage).

---

My proposal doesn't really work that differently from yours - but in a potentially maintainable way (but i don't think you've taken the time trying to understand that).
Assume your strategy runs on 5m data - and you download both 5m and 1m data.
We generate all strategy indicators on 5m data - and start backtesting.

The moment a trade opens, we load the 1m data for that pair starting with the open_time - for a few 1000 candles (hdf5 data allows to filter on this) - trying to see when the trade should be closed. 
if the trade is still open after these 1000 candles, we can always load another 1000 candles (to avoid swamping memory).

While my example uses 1m candles (for simplicity) - this could also be applied to 15s or 1s candles (generated from downloaded trades data) - and that these will not have sufficient granularity is simply not true.

**Comment by joshdifabio** [comment]
> It seems like your fixed on your way without accepting any input or other opinion

I think we are both the same. We each think we know better. That's exactly why I think we're now wasting our time. Every idea I have you take issue with and vice versa.

When I dig into the code I'll look at both approaches and I expect it will be clear which is less work for me. I won't expect you to merge anything you're unhappy with.

**Comment by xmatthias** [comment]
I dont have issues with other approaches if they make sense.

Mixing backtesting with datadownload does not. We had such a mode a few years back and it caused nothing but problems (maintenance) and frustrations (on the user side), therefore this is for sure nothing i'll be accepting again.
If modes are clearly separated, we can look at it, but i still must keep maintainability in mind, and my proposal can do the same with a lot less maintenance effort.
