### ISSUE TITLE
Implement startup_candle_count for live (Performance optimization)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#5369]
Hi,

For far i have understand of freqtrade it will download 500/1000 candles depending exchange and every process_throttle_secs iterate through the whitelist of pairs and compute indicators.

The startup_candle_count seems from what i have look in the code only use for backtesting.

Now i have have a strategy that need only 20 candles and whitelist 150 pairs it compute in binance currently 150 * 1000 = 150 000 candles but it could be  150 * 20 = 3000 witch should reduce compute time.

For what i see when there is a new candle it ask to exchange api not the last candle but 500 or 1000 candle so maybe it could be faster to ask 20 and not 500/1000 candle (not sure because of cache mechanism server side) ?

Have a nice day.

**Comment by xmatthias** [comment]
we've been performing some tests about this in the past, and the fastest was using the default (at least on binance)- as that's what most people request and is therefore in cache - even though that cache will only live for a few microseconds.

You can however slice the dataframe in your method to the last X candles, calculate the indicators on it and then merge it back to that.

You can in theory also influcence the downloaded data from the configuration via an undocumented config setting (`_ft_has_params` - with ohlcv_candle_limit as subkey) - but not all exchanges will respect very low values and may still return a minimum amount of candles "just because".
Obviously, you'll need to make sure not to use this for data-downloading to avoid infinite waiting times.

**Comment by gaugau3000** [comment]
Hi,

I many tks for response. I have try to limit the number of candles (1000 -> 20 ) to try if i got better performance and the response is i don't have any :-) at least with ta lib library. It take 15 ms to compute 1 pair in both cases.

Many tks for help.

**Comment by ghost** [comment]
Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: gautier pialat ***@***.***> Fecha: 18/08/21  5:41 a.m.  (GMT-06:00) A: freqtrade/freqtrade ***@***.***> CC: Subscribed ***@***.***> Asunto: Re: [freqtrade/freqtrade] Implement startup_candle_count for live (Performance optimization) (#5369) 
Closed #5369.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freqtrade/freqtrade/issues/5369#event-5174014121",
"url": "https://github.com/freqtrade/freqtrade/issues/5369#event-5174014121",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xmatthias** [comment]
honestly - that's what i was expecting - and why i see this as an unnecessary feature.
