### ISSUE TITLE
The backtesting result are not shown in the console

### ISSUE THREAD

**Issue by constantinpricope2013** [freqtrade/freqtrade#5371]
## Describe your environment

  * Operating system: Ubuntu 18.04 (container under docker)
  * Python Version: Python 3.6.9 (`python -V`) 
  * CCXT version: 1.40.14 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi, while backtesting if I use a longer period of time in the end it does not show any result. For a shorter period is working.
I am using the docker-compose up command and modifying the docker-compose.yml file.

### Steps to reproduce:

  1. Download the docker image freqtradeorg/freqtrade:stable
  2. Try to backtest using docker
  3. Select large period of time (about half a year) for 5m strategies.
  
### Observed Results:

  * What happened?
  * Everything went well but the backtesting results are not shown in the console
  * What did you expect to happen?
  * That the backtesting results to be shown in the console

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade    | 2021-08-07 23:01:11,000 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-01-01 00:00:00 up to 2021-08-03 14:50:00 (214 days).
freqtrade    | 2021-08-07 23:01:11,001 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
freqtrade    | 2021-08-07 23:01:11,001 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Strategy005
freqtrade    | 2021-08-07 23:01:19,859 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-01-01 00:00:00 up to 2021-08-03 14:50:00 (214 days).
pricope@pricope-VirtualBox:~/Trading/ft_userdata$ 
  ```

**Comment by xmatthias** [comment]
i don't think you can (or should) use `docker-compose up` for backtesting, but instead use `docker-compose run --rm freqtrade backtesting ...` (as stated in the documentation) for backtesting, to keep the session interactive.

Using "up" can have the side-effect that the container will backtest over and over again (once backtesting is finished, the container will die - as the container is (by default) set to restart-unless-stopped, this means it'll restart over and over again).
As such - you'll need to be lucky to get the right "moment" to see the output - otherwise it's backtesting again already.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
