### ISSUE TITLE
Multiple bots in same binance account with different quote stable coin

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#5397]
Hi,

Now I'm trying two different strategies with 2 bots in different virtual env in different folders with different api keys.
But the second bot using BUSD for stake_currency trying to get rate for cryptos from the first bot whites list (this use USDT). Those cryptos are not added to the second bot whitelist.
I've tried to add them to blacklist but have no effect, in same way trying to get the rates.

![image](https://user-images.githubusercontent.com/14143598/128915617-19a5b03f-c5e3-4e60-8508-6d404307fe12.png)

Maybe somebody can help me with some advise how to avoid this.

Thanx

**Comment by xmatthias** [comment]
the most likely reason for this is that you're using a shared database (or at least a non-empty database).

As the requests originage from `.rpc` - it's caused by telegram / UI call that's trying to get current prices.

While seperate folders / venvs are not necessarily required, you will need to make sure to use different database files / databases, different telegram keys and different ports (when using FreqUI) - as documendted [here](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade).
