### ISSUE TITLE
Running the robot display requires a policy

### ISSUE THREAD

**Issue by linliang123** [freqtrade/freqtrade#5407]
freqtrade.exceptions.OperationalException: No strategy set. Please use `--strategy` to specify the strategy class to use.

**Comment by xmatthias** [comment]
Using freqtrade requires a strategy. This defines your logic for buying and selling.

Freqtrade includes a builtin strategy (SampleStrategy) that will be available if the [setup instructions](https://www.freqtrade.io/en/stable/) are followed - however i'd storngly recommend to vet this strategy well  if it works for your selected markets - otherwise you'll end up with losses.

Alternatively, you can look at the [strategy repository](https://github.com/freqtrade/freqtrade-strategies) or the channel `#strategy-collections` on [discord](https://discord.gg/p7nuUNVfP7) 


Also - for simple questions like this (which can be easily answered by the documentation) - please use the documentation, or if the documenation cannot help, please use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.

People there love to help **assuming the documentation has been consulted** first.
