### ISSUE TITLE
Some robot commands are not supported

### ISSUE THREAD

**Issue by linliang123** [freqtrade/freqtrade#5445]
## Describe your environment

  * Operating system: __macos__
  * Python Version: ___3.8__ (`python -V`)
  * CCXT version: __1.55.13___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __develop__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

### Steps to reproduce:
  1.Enable Robot command
### Observed Results:

  * What happened?
    freqtrade show-trades、freqtrade plot-dataframe 、freqtrade list-hyperopts These commands cannot be used properly
  * What did you expect to happen?
    Hopefully, these commands work
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
2021-08-17 19:33:20,373 - freqtrade.configuration.check_exchange - WARNING - Exchange "gateio" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.

**Comment by xmatthias** [comment]
these commands all have some prerequisites (like, having a database with trades available, having ran hyperopt beforehand, ...).

It's covered pretty well in the [documentation](https://www.freqtrade.io/en/stable/utils/) - and each command will have a certain situation when to use them (you can't use `show-trades` if you never ran the bot beforehand).
Also, some commands may have mandatory arguments. If you run into specific problems (after having read the documentation!!!) feel free to ask here - but generic "doesn't work and i didn't bother to read the documentation" are not very well seen here.

---

Honestly, i'm pretty frustrated with your questions here (especially since i know that you're doing this for work) and very close to blocking you - as you seem to be unable to even try and read the documentation.

Please consider this as last warning - as this is wasting my time. 

Thanks for your understanding.

**Comment by linliang123** [comment]
I'm sorry that all these problems are caused by the implementation of the conditions you said. I think you are delaying my time.

**Comment by xmatthias** [comment]
@linliang123 So think i should be reading the docs for you?

Please keep in mind, you're not talking to the support team of a paid service, but to volunteers working in an open source project.
i'm doing this voluntarily, in my spare, free time.
As such - i expect that people will read the documentation first, and try to understand what the commands they try to use are doing.

As you fail to do so i've warned you above - to which you respond by becoming offensive.

Please consider this as very last warning - the next step will be to block you from the freqtrade organization.
