### ISSUE TITLE
How to switch between two strategies on one bot?

### ISSUE THREAD

**Issue by Kaw11** [freqtrade/freqtrade#5446]
Hello!
After a few hyperopts and backtests I have found 2 best possibilities for the same strategy but for different market cycles: one for side market and one for bull market. So I'm thinking how it will look when trying to switch from one strategy to other when needed. The whitelist pairs are the same for both and same goes to stake currency. The time frame in config.json files will be different and strategy files will be different too. 
Would the best option for this be to have one (Telegram)bot and switching commands in Terminal using different config's (say configA.json and configB.json) and different strategies (strategyA and strategyB), or to have two (Telegram)bots and two opened tabs in Terminal one ready for bot1 and the other ready for bot2 and switch them with Telegram commands?

I understand that in both versions before switching I would need to force cell all open trades to not confuse both strategies/bots.

**Comment by aumcara** [comment]
Hello Kaw11,
I am affraid you will receive a reply recommending you to read the [Manual](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) ... 

brgs

**Comment by xmatthias** [comment]
Your best option is to find an exclusive condition (basically one that says "trade bot 1" or "trade bot 2") - and implement them with the inverse conditions in each strategy.
you'll then run both bots at the same time - but due to the exclusive condition, only one will buy.

you can also do this manually (maybe with 2 seperate commands / configs you got ready) - but it'll be manual and will not be possible via /telegram.
Alternatively, try to use `/stop` (or better, `initial_state="stopped"`) to only run one bot at a time.
Obviously, it'll then be manual switching (this is where the documentation linked above will come in - as you will have to have both bots running (even if only in stopped state).
