### ISSUE TITLE
Stoploss on exchange management: try to create new stoploss before canceling old one

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#5451]
Currently, the stop loss on exchange handling is like that:

1. Cancel the old stop loss
2. Try to create the new one

If there is an error while creating the new custom stop loss, no stop loss is active during the time gap between two process run.
It's a supplementary risk exposure.

*Explain the enhancement you would like*
My proposition is to change the function "**handle_trailing_stoploss_on_exchange**" to try to create new stoploss before canceling old one in order to always have an active stoploss

1. Try to create the new one
2. Cancel the old stop loss

**Comment by Axel-CH** [comment]
I think this feature could cause an "Insufficient found error" on a spot account. Maybe this feature could be activated via an option in config if it's not an issue depending on the exchange

**Comment by xmatthias** [comment]
i don't know any exchange that would allow this - so that option would be pretty pointless as it couldn't be used by any exchange.

Once you create a stoploss order, the funds become blocked/locked on the exchange - and the new stoploss order creation will fail until you cancel the old one.

I think this request comes from a "too close" stoploss - as this will only happen if your stop is closer than 1% to the current price.

your risk exposure will be subseconds usually - and can probably be reduced further by removing the ratelimit switch, or tuning the ratelimit parameters).
Also, should price really drop during that time, then a new stoploss will fail to be created, triggering an emergency sell.


---

assume for a moment that you could create as many stoploss-orders as you'd like without looking at available funds (which is not how exchanges work, at least not the ones i've worked with).

reversing this order would even increase your risk considering the following case:
* you create a new stoploss order
* cancelling the old stoploss order fails because it triggered just that moment

You've now got an open stoploss order - but your funds are gone.
Should that 2nd stoploss order trigger as well - you'd now be in a "surprising short" (Which the bot would not handle at the moment).
As such - your risk is now an unhandled short position ... - which will be basically unlimited risk (limited by account collateral), assuming the position raises indefinitely ... 

---

Now ideally, we'd have a "edit order" endpoint - which allows immediate updating of the order (Or cancel/create in the exchange's systems).
Unfortunately, almost no exchange has that functionality, and while ccxt is emulating that for some exchanges (not many - or no longer at all, not sure), it's usually just a "cancel order" followed by a "create order" call.
