### ISSUE TITLE
edit from telegram bot commands

### ISSUE THREAD

**Issue by umutrcc** [freqtrade/freqtrade#5463]
Hello, I would like to share this suggestion with you.
If there is a # sign at the beginning of the coin in every new notification (buy or sale) in telegram, it is enough to just click on it while searching for the past, this would be a very nice feature in terms of coin tracking.
eg #evx/btc
as

**Comment by xmatthias** [comment]
In principle, this sounds OKish (until you get to try it out).

the output of that looks pretty strange as telegram splits the pair name at the "/"
... so unfortunately, instead of being a nice feature, it turns into a distraction when you look at it and don't plan on using this functionality.

![2021-08-23-193024_369x144_scrot](https://user-images.githubusercontent.com/5024695/130491178-29b79eca-ef85-4b6b-863c-13c20696e1fb.png)

It is however no problem to simply use the search and type TRX/USDT to get all related entries.
