### ISSUE TITLE
Error determining price (aax exchange)

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#5477]
freqtrade develop-969156306

```
Aug 24 15:24:02 aaxusdt freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'float'
Aug 24 15:24:02 aaxusdt freqtrade.commands.trade_commands - ERROR - Fatal exception!#012Traceback (most recent call last):#012  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading#012    worker.run()#012  File "/root/freqtrade/freqtrade/worker.py", line 74, in run#012    state = self._worker(old_state=state)#012  File "/root/freqtrade/freqtrade/worker.py", line 111, in _worker#012    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)#012  File "/root/freqtrade/freqtrade/worker.py", line 132, in _throttle#012    result = func(*args, **kwargs)#012  File "/root/freqtrade/freqtrade/worker.py", line 145, in _process_running#012    self.freqtrade.process()#012  File "/root/freqtrade/freqtrade/freqtradebot.py", line 183, in process#012    self.enter_positions()#012  File "/root/freqtrade/freqtrade/freqtradebot.py", line 383, in enter_positions#012    trades_created += self.create_trade(pair)#012  File "/root/freqtrade/freqtrade/freqtradebot.py", line 440, in create_trade#012    return self.execute_buy(pair, stake_amount, buy_tag=buy_tag)#012  File "/root/freqtrade/freqtrade/freqtradebot.py", line 482, in execute_buy#012    proposed_buy_rate = self.exchange.get_rate(pair, refresh=True, side="buy")#012  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 1042, in get_rate#012    if side == 'buy' and ticker_rate > ticker['last']:#012TypeError: '>' not supported between instances of 'NoneType' and 'float'
Aug 24 15:24:02 aaxusdt freqtrade.commands.trade_commands - INFO - worker found ... calling exit
Aug 24 15:24:02 aaxusdt freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
```

**Comment by xmatthias** [comment]
"latest develop" is not a version, but a moving target that can change whenever you did the pull.

We're requesting the issue template to be filled out on purpose - failing to do so will have this issue closed without further comment.
While this may sound rude, there's too many issues opening without the template filled out, which ultimately results in unnecessary / pointless back and forth asking for the version.

**Comment by nodwan** [comment]
`(.env) root@aaxusdt:~/freqtrade# freqtrade -V
freqtrade develop-969156306
(.env) root@aaxusdt:~/freqtrade#  `

**Comment by nodwan** [comment]
And sorry now i‘was found the template. ok, i’will next time try use the template. about what is happen, the bot was running ok. from time to time  i’m make update (pull), later i’was get this error.  i‘m using the bot at aax exchange and USDT pair‘s. i‘m using some 1:1 cloned bot‘s at diffrent exchanges. but not update yet. aax was the first. i‘and i was look all is running and ok or not.

**Comment by xmatthias** [comment]
The error comes from determining the price.
Seems like you're using the "ticker" method instead of the orderbook to get pricing.

while in theory not a problem - we've often seen that some exchanges don't contain all information at all time (sometimes the "Last" entry is empty if there's no trade for a certain period).
While we look at last in particular, the error suggests that either "ask" or "bid" (depends on the configuration) was empty.

In summary, it'll mean that you can't really rely on this method to get prices - as sometimes not all fields are filed - which either means that the orderbook on one side was empty (unlikely, unless you're using very weak /low volume coins) - or that the exchange failed to fill this information.

I'd recommend to switch to using the [orderbook ](https://www.freqtrade.io/en/stable/configuration/#buy-price-with-orderbook-enabled) for both buy and sell sides.

While the bot shouldn't crash from it - i don't see this as a priority for the moment, as it's happening on on a random exchange (not a supported one), and can be worked around pretty easyily.
