### ISSUE TITLE
[Feature Request] Ability to mirror same bot signals in multiple accounts

### ISSUE THREAD

**Issue by arunavo4** [freqtrade/freqtrade#5502]
## Describe the enhancement
Running one Bot but mirroring the trades into multiple accounts will save compute resources. if there is are multiple accounts to manage.

One Main account and ability to add Sub Accounts to just mirror trade signals.

**Comment by xmatthias** [comment]
How would this differ to running the same strategy on multiple bots (with different keys)?

This is currently not foreseen / possible - and i don't see us adding it (unless you can provide very good arguments) - as it'll only add overhead / unnecessary code complexity, which we'll then have to maintain and support.

**Comment by arunavo4** [comment]
So let's say you manage 50 accounts then running 3 bots per account is compute-intensive doing the same work again and again.

**Comment by xmatthias** [comment]
You will not run the same strategy against 50 of your personal subaccounts.
There's no point in that for private accounts / traders i can see.

What you're asking for sounds like a professional requirement (running an investment company that's running freqtrade for it's clients), not something that's needed by private traders and crypto enthusiasts (which are the main target group of freqtrade).

Because of that, for now this sounds to me like you're trying to setup a company, and have the open source community work for you - which i'm afraid is not how this is going to work.

**Comment by arunavo4** [comment]
Nahh, just trying to setup for friends and family. But looks like it will take a long to setup these for everyone.
