### ISSUE TITLE
Forcesell ALL error when some partially filled open sell order exist 

### ISSUE THREAD

**Issue by yari0757** [freqtrade/freqtrade#5519]
if there are some partially filled open sell order exist, /Forcesell command not work well and Freqtrade faces some exception. I have two suggestion:
* cancel existing sell orders and again  open new sell order for all.
* warn user that there are partially field order
when user don't access to the exchange panel, there are no way to cancel some partially filled open sell order 
sorry, i am new in github and maybe don't open issue in true way.

**Comment by xmatthias** [comment]
Partially sold orders are currently left on the exchange for further filling.
there's also an open issue for that (#3009) - which makes this a (at least partial) duplicate.

Obviously this impacts also /forcesell - but a solution only for forcesell will not be possible without general handling for partially sold pairs - which is simply not there at the moment.

Unfortunately, minimum limits complicate this topic slightly - which is why this topic has never been acted on so far - as you can be left with "Unsellable" amounts (< minimum tradable amount) - in which cases not cancelling the order is the only option to be able to sell the asset at all (other than buying more to be > the minimum limit).
