### ISSUE TITLE
Sell market after the bot cancelling open sell limit order

### ISSUE THREAD

**Issue by Angel2298** [freqtrade/freqtrade#5539]
## Describe your environment

  * Operating system: ____
Operating system: ____ubuntu 64 bits
Python Version: _____ (`python 3.8.10
CCXT version: _____ (`ccxt 1.52.4
Freqtrade Version: ____ freqtrade develop-b8de3270
  
## Your question

So after searching on the issues I haven´t seen any similar question about this. But if you have a open limit sell order and after some time (the time that you configure in the config.json) it doesn´t get fulfill. The Bot automatically cancel the open sell order. 

So for example if after 30 minutes the bot cancel the open limit sell order, is there a way to configure the file to tell the bot that, after cancelling that open limit sell order to sell but in a market sell. I mean it has to be positive the roi. But it is possible or this has to be done manual?

**Comment by xmatthias** [comment]
you'll usually want to reduce the timeout to something lower.
The order will be placed again assuming the signal is still there - but especially on ROI, what you're proposing will not work.
Assuming price touched your ROI point - and a limit sell was placed.
If price continues to raise - your order would've been filled.
if price falls drops again, your sell would not be for "ROI" - but for ROI - "undefined amount" - which can also be a negative trade again.

You'll usually want to have the timeout configured to be below your timeframe length (so a regular sell signal will replace the order).
A better approach is however to make sure that the order is filled  - which can be done with by using different [pricing methods](https://www.freqtrade.io/en/stable/configuration/#sell-price).

Selling after timeout with market sells will sell for an indetermined price which is usually not a good option unless explicitly desired (use market-orders then) - which can turn a 2% profitable trade into a -2% negative trade very easily (assuming it was ROI - and timeout was 30m) - simply due to regular movements and slippage.
