### ISSUE TITLE
Define max buy price value for each pair list

### ISSUE THREAD

**Issue by kiero63** [freqtrade/freqtrade#5564]
Hi,

I would like to know, if a way is possible to set a max price value for each pair list. Because I notice that most of the strategies I used buy near the limit of the max value.
For example with ADA/EUR, the price is most of the time moving between 1,95 & 2.15 €, what I like to tell to the system is, you can buy this value only if the price is below 2,00€.
Maybe the same way can be apply for selling, if people don't want to take higher risk.

Thanks

**Comment by xmatthias** [comment]
Yes, this functionality is called strategy.
It's your strategy that tells the bot when to buy or when to sell - if your strategy tells the bot to tell when price is high - then your strategy is not good and needs some work.

You can obviously try to use static prices - but that'll be veryf luky and will not be working pretty well (assuming a pair increases or decreases significantly in value) - as it's based on current behaviour, which can be wrong a week from today (or a week or two ago).

Freqtrade itself doesn't have this builtin - and it won't as it doesn't make sense. this is what the strategy is for.

Freqtrade will not take the decision "let's buy because ADA/EUR is currently high" - it'll buy because your strategy decided "buy ADA/EUR" by setting the buy signal. If you're not happy with the signal your strategy is making, then work on your strategy.
