### ISSUE TITLE
Automatically choose the buy signal based on a hierarchy of performance

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#5581]
## Describe the enhancement

I was thinking that some buy signal perform better in certain periods (regardless the scenario). So I'd like to suggest to make freqtrade automatically choose the buy signal based on a hierarchy of performance.

For example, if buy signal 1 in the last 7 days has the best profit combined with the best drawdown, if a slot is free, that should be the first to trigger in case of buy signal available. Then the second in order of performance should be checked, and so on.

What do you think?

**Comment by ReynardoEW** [comment]
Check this https://www.freqtrade.io/en/stable/edge/

**Comment by Fimap9to1** [comment]
> 
> 
> Check this https://www.freqtrade.io/en/stable/edge/

Thanks but it seems that Edge Positioning is a rudimental function of what I'm suggesting.

**Comment by xmatthias** [comment]
Honestly, i don't see what you'd expect here (other than advise).

It's the strategy's task to determine if a pair should be bought or not.
freqtrade will act based on buy signals given - but the determination IF it should buy has to remain in the strategy. 
If freqtrade starts to decide "strategy told me to buy - but i'd rather not ... 'because' " - it'll start to become tricky with certain types of strategies (and pretty much unpredictable) - as there's some "black box" (for most people, anyway) deciding if buys are good or not (freqtrade will try to remain impartial - you can buy / sell whenever you like - it's up to the strategy to decide when - and your responsibility if you lose money because of that).


So if you have an idea in mind on how this should be done - feel free to implement it in the strategy.

All data you'll need should be available if you combine things from the documentation.

You can for example use [callbacks](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation) to prevent buys "last minute", or set the buy-signal to 0 in `populate_buy_trend()` if you think it's not worth buying at that time.

**Comment by Fimap9to1** [comment]
Ok thanks. It sure is up to the strategy but still, the future is always different so instead of waiting to lose performance because one of the buy signals is no longer performant in a new scenario, it would be good if the strategy could dinamically adapt itself to the new environment.

**Comment by xmatthias** [comment]
>  it would be good if the strategy could dinamically adapt itself to the new environment.

Yes, and your wording is the key - it's the strategy that needs to take care of this, not freqtrade.
Only the strategy knows what parameters / calculations can/should be made to determine if signals are no longer valid - as the signals are comming from the strategy. 

If freqtrade were to do this for you, you'd be forced into a certain type of strategy - and therefore lose flexibility, and potentially even the ability to run certain types of strategies with freqtrade.

**Comment by Fimap9to1** [comment]
Anyway, thanks.
