### ISSUE TITLE
"def amount_to_precision" and "def price_to_precision" in "freqtrade/exchange/exchange.py" would not round up if self.markets[pair]['precision']['amount'] is 0 and self.markets[pair]['precision']['price'] is 0 respectively

### ISSUE THREAD

**Issue by GluTbl** [freqtrade/freqtrade#5583]
the "if statement" in these two function will not execute if the precision value is "0".
This will result in impossible to round up in nearest whole number. eg Rounding "15.123" to "15". 

please change it with `if 'amount' in self.markets[pair]['precision'] and type(self.markets[pair]['precision']['amount']) == int:` and `if 'price' in self.markets[pair]['precision'] and type(self.markets[pair]['precision']['price']) == int:` respectively

**Comment by xmatthias** [comment]
I'll not make changes because someone assumes there might be a theoretical problem.

If you think something should be changed, please invest the time to submit a pull request - saving both of us time (you already took the time to figure out what you think is correct - so best do that as part of a Pull request).

If you only think it's wrong and require us to do analysis, please fill out the issue template and describe a realistic case where you think it's wrong.

**Comment by GluTbl** [comment]
Okey...
