### ISSUE TITLE
The bots suddenly stopped making trades. Suggestions?

### ISSUE THREAD

**Issue by debonx** [freqtrade/freqtrade#5594]
I run 2 bots in parallel with 2 different strategies. After a great start, they suddenly stopped trading since a couple of days. It's weird because they are set up with different pairs and different settings.

Logs are clean, heartbeats working properly.

Do you have any recommendations?

Thanks in advance.

**Comment by xmatthias** [comment]
there's 2 things to check - `/whitelist` and `/locks`.

Maybe your bot is "fully locked" due to some protection - or "something" dropped all pairs from the whitelist, so now it's empty.

Other than that, i'd not know what could cause this - except maybe that markets change all the time, so some strategies might be more active in some periods than in others.

**Comment by debonx** [comment]
Thanks for the answer. Unfortunately after checking, those looks ok, no locks and whitelist is good...

Is it possible some kind of restriction from Binance?

**Comment by xmatthias** [comment]
if binance is rate-limiting you, you'd see that in the logs, either as RateLimit, or as errors when creating trades (should API keys be problematic).

you might also check the UI for buy-signals - my big suspicion is, that there are simply none.

**Comment by debonx** [comment]
This is a great help. It's probably that. I will keep waiting and observe.

Thanks

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
