### ISSUE TITLE
ERROR:: Could not find a local HDF5 installation - WINDOWS issue

### ISSUE THREAD

**Issue by Kaw11** [freqtrade/freqtrade#5597]
Hi!
I keep having the same issue as this guy: https://github.com/freqtrade/freqtrade/issues/4162. 
But I don't use MacOS, I'm on Windows and my raspberry Pi has DietPi. Also it doesn't recognise the "brew" command (brew install hdf5)  and my python version is 3.7.2. So the requirements seem to be matching for everything to work, but still this keeps coming up: 

    ERROR: Command errored out with exit status 1:
     command: /root/Python-3.7.2/freqtrade/.env/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oto82oqt/tables_00fa77204c3140a0b06d00b349dfa2a8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oto82oqt/tables_00fa77204c3140a0b06d00b349dfa2a8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_f40nwy9
         cwd: /tmp/pip-install-oto82oqt/tables_00fa77204c3140a0b06d00b349dfa2a8/
    Complete output (12 lines):
    /tmp/H5close75p75yw9.c: In function ‘main’:
    /tmp/H5close75p75yw9.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
        2 |     H5close();
          |     ^~~~~~~
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.9.2 (default, Feb 28 2021, 17:03:44)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1 (from versions: 2.3, 2.3.1, 2.4.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0rc1, 3.2.0rc2, 3.2.0, 3.2.1.1, 3.2.2, 3.2.3, 3.2.3.1, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.1, 3.5.2, 3.6.1)
ERROR: No matching distribution found for tables==3.6.1

**Comment by xmatthias** [comment]
You're talking about 3 different things here. 
brew is a command for macOS - neither of which seems to be your system.

The logs suggest that you're trying to install on a linux system - so probably, your pc is windows, but the problem is on the raspberry (?) 

> Using Python 3.9.2 (default, Feb 28 2021, 17:03:44)

Also, your python version (while the directory is called python3.7.2) is NOT python 3.7, but 3.9.2.
That version is not supported on a raspberry at this moment, and we'll not be supporting installation in this combination.


You should probably use the docker file, which will be the simplest solution in your case (things seem pretty messed up ...).
Alternatively, follow the [installation instruction](https://www.freqtrade.io/en/stable/installation/#install-code) while making sure to use the raspbian section (but you MUST use python3.7 for that).

**Comment by Kaw11** [comment]
Right. Ok. Thank you, xmatthias! I'll take it from here then. Could you please leave this question open in case if I'll be needing any further assistance?

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
