### ISSUE TITLE
Support  loading/resolving strategies from directory modules

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5620]
## Describe your environment
(if applicable)

  * Operating system: OpenSuse 15.2
  * Python Version: 3.9.7 (`python -V`)
  * CCXT version: 1.55.54 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Python allows defining modules simply by `module.py` or `module/__init__.py`, however the latter is not supported for loading strategies. It would be nice for it to be supported in order to make sharing strategies easier: it would allow things like

```sh
# "install" strategies from a repo
cd user_data/strategies
git clone https://somehost.com/user/freqtrade_strategy AnotherStrategy

# run hyperopt and create .json
freqtrade hyperopt -s AnotherStrategy -e 500 # ...
```

Additionally, shared strategies could contain extra stuff like a `README.md` or whatever else.

# Possible implementation

Add a clause to  https://github.com/freqtrade/freqtrade/blob/4c268847d42043d53fc59751ffd1717125d9e0bd/freqtrade/resolvers/iresolver.py#L94 to search for `f"{object_name}/__init__.py"` and load that.

**Comment by xmatthias** [comment]
The filter on `.py` files is intentional, as we don't want freqtrade to load random files.

You'll need to be careful with terminology, too, a module is a python file - while a "directory module" is a package in python terminology. 

I think what you want to do can pretty easily be accomplished in another, simpler and already existing way:

Your clone command creates a directory called `AnotherStrategy`. 

You can simply use `--strategy-path user_data/strategies/AnotherStrategy` - and it'll load `user_data/strategies/AnotherStrategy/anotherstrategy.py` (or any other `*.py` file in that directory) just fine without any additional needs.

This will also allow you (in theroy) to have the same strategyName in different directories and switch directories (although you'll need to be careful with this - as it can get messy VERY quickly). 
The usecase for this would be the same strategy with changes from different people/repositories.

---

Your proposal (loading from package) would require additional work (by the strategy author) by having a `__init__.py` which correctly imports `AnotherStrategy` for the module to correctly "see" `AnotherStrategy` (otherwise you'd still need to iterate through all files in that directory - so the __init__.py file would not be necessary).

For a developer, this might be fine/easy to do, but many strategy-authors (often the ones with good strategies) are python beginners, but trading experts...
You're also forcing the "additional" repository to have the strategy at the root level of the repository (which is quite unusual for most python projects).
Usually, these should be in directories (which might then the module) - so you'd anwyay need to switch `--strategy-path` to get to the proper subdir of that repository.
That way you can also easily have different strategies (`AnotherStrategyA`, `AnotherStrategyB`) in the same repository (seperated in different directories) - which would not be possible with the proposed approach.

Loading from packages (directories) would also be messy from a `.json` perspective, as it's unclear where the `.json` would go - and might result in surprising results (if you load from the package, then the json file would be `__init__.json` - as it's named according to the file the strategy is loaded from).


I also don't quite understand the mention of the `readme.md` - you can always have this - it's of no relevance to freqtrade as it's not a `*.py` file - so i'll ignore this for now.

Your proposal would therefore require the following structure :
```
user_data/
└── strategies
    └── AnotherStrategy     <- This is the Package you cloned
        └── .git
        └── __init__.py       <- This must import the strategy from anotherstrategy.py
        └── anotherstrategy.py
        └── Readme.md

```

I think this is quite "limiting" the strategy repository into exactly this format. It'll also limit the repository from providing a (partial?) configuration file to go along with this strategy (which is something i've quite frequently seen).

To me, the following looks better (explained below how to accomplish) and allows for more flexibility in the "strategy repository".

```
user_data/
└── strategies
    └── AnotherStrategyRepo 
        └── .git
        └── Readme.md
        └── sample_config.json
        └── AnotherStrategy
        |    └── anotherstrategy.py
        └── AnotherStrategyB
            └── anotherstrategyB.py

```

You can load each of these strategies with `--strategy-path user_data/strategies/AnotherStrategyRepo/AnotherStrategy` or `--strategy-path user_data/strategies/AnotherStrategyRepo/AnotherStrategyB` already today.


For the moment, i don't see what benefit package-based loading would bring (on top of the existing method) other than additional complexity for the users (require `__init__.py`), and locking them to "1 strategy per repository".


---

The thing i can think of as (potentially) useful improvement in this regard (to load the above 2nd directory structure) would be recursive strategy loading (so it'll search all subdirs within the defined strategy path for `.py` files containing strategies).

That would also automatically (implicitly) accomplish your structure - but comes with some additional complexities (symlinks can in theory result in infinite recursion) - as well as potentially non-expected/desired outcomes for the user (why is it now loading the strategy from `user_data/strategies/archive/xxx.py` instead of `user_data/strategies/xxx.py`?)

**Comment by ghost** [comment]
I created an MR that hopefully clears things up. It allows importing items/symbols from _packages_ without using `--strategy-path` using the python import logic and falling back to how things work now when nothing is found. The code is hopefully clear enough.

> Loading from packages (directories) would also be messy from a .json perspective, as it's unclear where the .json would go - and might result in surprising results (if you load from the package, then the json file would be __init__.json - as it's named according to the file the strategy is loaded from).

This is something I'll have to look into. Maybe the `.json` will have to be named after the strategy, not the file since it will be possible for files to contain multiple strategy classes (especially `__init__.py` importing from multiple files).

**Comment by xmatthias** [comment]
i've never doubted the technical possibility of it being possible.
Just because it's possible doesn't make it a good idea though.

while you're showing the implementation in the PR (the how), i don't see why we would need this, and what benefits it would bring over recursive loading (which would be easier, too), and would accomplish the same thing.

For the moment, i think iterating through subdirectories is the way to go, and i see nothing that convinces me of even one benefit over that method (this may change if you know of something that can't be done then, but just the code will not suffice).

**Comment by ghost** [comment]
Hmmm... I'll close this issue then and let you write a description of what you expect to happen for recursive loading as well as what to look out for. For now, I'll plough ahead with this in my own fork and see what happens.

If after I implement this recursive loading does end up being better, I'll contribute the latter back here.

Thank you for your time.

**Comment by xmatthias** [comment]
I do apreciate the attempt to contribute things here. 
You should however also stay open for alternative ways of doing things.

The time wasted here is a shame - especially as the way i'd want to see this has been outlined before any work has been done (which is the whole point of opening an issue to discuss **before** creating a PR).

Please understand that your proposed way would result in a supportability problem, as one missing `__init__.py` level will make the whole sub-structure no longer loadable (it's no longer a package).

Worse, if a `__init__.py` was forgotten (or it doesn't import the strategy) - then an import of `from strategies.modulea import AwesomeStrategy` will not import the strategy, but the strategy module (the strategy would now be `AwesomeStrategy.AwesomeStrategy` (assuming the file is `AwesomeStrategy.py`).
As you're loading this as `modulea.AwesomeStrategy` - the strategy load will now fail - and it will not be obvious to non-experienced python users, and become a supportability problem for freqtrade.


This is obviously not a problem for generic contributions - but it's something to very deeply consider as maintainer.
As such, i'm grateful for every contribution - as long as the contributor remains also  open to alternative ways of archiving the very same goal, without being locked into "i want this done this way" while being shown a better, easier way to archive the same goal.
I understand the technical challange/complexity for this implementation will be higher than "descend into subdirectorie and search for *.py files there" (as such, it's more interresting for a developer), but it's also simpler to use, as it'll not depend on having `__init__.py` at every level, and will not require the whole tree typed out correctly.

I've outlined "what i'd expect" in this regards both above and in the PR - so i don't understand what you're looking for.

**Comment by ghost** [comment]
You're primarily focused on the non-dev user experience and would rather have devs contributing code to make the lives of non-dev users better, which is understandable. It's not that I'm against recursive loading as I do see the benefits for non-devs but as a dev, I want to go a little further with strategies. One simple example is inheritance or code sharing which isn't possible right now (unless I'm mistaken).

Our goals in this matter currently diverge, which is why I: 

 - closed the issue
 - am writing the feature in a fork
 - suggested creating a new, clean issue on one single topic: recursive loading

I just thought it would be better for you to create the issue and outline your expectations, possible pitfalls and expected tasks there to make it easier for whoever picks up the task to get started, without having to read this entire discussion. For example:

> # Goal
> 
> Support loading strategies from python files in sub-directories of the strategy path.
> 
> # Usecase
> 
> Use strategies from other repositories by simply checking the repository out into a subfolder in the strategies path.
> 
> ## Steps
> 
> 1. User checks out a repository into `user_data/strategies/AnotherStrategyRepo`  
> ```
> user_data/
> └── strategies
>     └── AnotherStrategyRepo 
>         └── .git
>         └── Readme.md
>         └── sample_config.json
>         └── AnotherStrategy
>         |    └── anotherstrategy.py
>         └── AnotherStrategyB
>             └── anotherstrategyB.py
> ```
> 2. User executes `freqtrade backtesting -s AnotherStrategyB`
> 3. Freqtrade backtests with AnotherStrategyB from `user_data/strategies/AnotherStrategyRepo/AnotherStrategyB/anotherstrategyB.py`
> 
> # TODO
> 
>  - [ ] recurse through subfolders in `IResolver._search_object` https://github.com/freqtrade/freqtrade/blob/4c268847d42043d53fc59751ffd1717125d9e0bd/freqtrade/resolvers/iresolver.py#L92
>  - [ ] recurse through subfolders in `IResolver.search_all_objects` https://github.com/freqtrade/freqtrade/blob/4c268847d42043d53fc59751ffd1717125d9e0bd/freqtrade/resolvers/iresolver.py#L170
>  - [ ] Add tests in [tests/strategy](https://github.com/freqtrade/freqtrade/tree/4c268847d42043d53fc59751ffd1717125d9e0bd/tests/strategy)
>  - [ ] Add documentation to [docs/strategy-advanced](https://github.com/freqtrade/freqtrade/blob/4c268847d42043d53fc59751ffd1717125d9e0bd/docs/strategy-advanced.md):
>   * example of checking out https://github.com/freqtrade/freqtrade-strategies
>   * warning about class name ambiguity: strategies shouldn't have the same names because only one will be loaded and it might be random which one that is

**Comment by xmatthias** [comment]
You never mentioned your final goal in the first place (the why) - and when asked (both here and in the PR) for advantages of this over the "recursive loading" method, i encountered silence - which i interpret(ed) as "there are none".

Having this as one of the advantages can certainly be a benefit (one you never mentioned...) - but i also see the risks  and challanges - especially with importing - as having one additional line in `__init__.py` or not can make `advanced.AwesomeStrategy` fail or load correctly (if the import in `__init__.py` is missing, the import must be `advanced.AwesomeStrategy.AwesomeStrategy`).

I've seen people i consider good developers struggle with such nuances for hours (not necessarily excluding myself ...) - so i can only imagine how frustrating / difficult it must be for non-developers (which might not even understand why it's failing even after encountering the fix).

To quote myself in the issue:

> Obviously you're free to convince me of the benefits over recursing through all files (THE killer feature which iterating down the directory tree won't give and why we must have that), but so far, i don't see any - so unless you can provide that feature, please treat this as a request to change it to recurse over directories instead of support loading packages.

This does not outright reject your approach - simply asks for "why do we need to have it this way, and can't have it the other, simpler way". 
Providing a good reason (one i probably do not see) is often enough to convince me - although you seem to have treated as a outright refusal (which it wasn't - just "refusal unless other arguments for "why this way" are provided" - which i consider a significant difference).

Your argument about code-sharing is not something i can simply throw away (now that you brought it up ...why so only now?? :fearful: ) - but i still see it a long way to go (your PR doesn't seem to handle `freqtrade list-strategies` at all ... which i'd clearly expect to also "see" these strategies) ... 


---

To your question - code sharing can be possible and is documented [here](https://www.freqtrade.io/en/stable/strategy-advanced/#derived-strategies).
It's surely not ideal - and for "real" codesharing, i'd encourage using a installable package to properly share code - which can then be imported as `lovelsgrief_strats.helpers` (or whatever else).
This approach could be documented - and i think should fulfill the need of developers ...
