### ISSUE TITLE
(sqlite3.OperationalError) database or disk is full

### ISSUE THREAD

**Issue by bigsee** [freqtrade/freqtrade#5621]
## Describe your environment

  * Operating system: Ubuntu 20.04 x64
  * Python Version: 3.8.10
  * CCXT version: Unknown
  * Freqtrade Version: 2021.7
 

## Describe the problem:

My bot has been running fine for over a month. I have not started or stopped in that time. One morning, I noticed there were no trades but simply a message in Telegram saying:

**Status:** `process died`

Some commands worked like `/help`, `/blacklist`, `/performance`, `/daily` worked. I tried stopping and restarting from  Telegram without any response. I also could not manually close out open positions with `/forcesell`.

I checked the logs and it seems that there was a SQLite or SQLAlchemy error (see below and title). `(sqlite3.OperationalError) database or disk is full`. However, the VPS I am running this on has nothing else running on it and has 25GB of space. The current size of the DB is `7520256` and it was last modified on Sep 22.

I checked other issues and around the Internet for clues on this error. But my disk space looks fine and nowhere near limits, as does the size of the DB file.

I note from [this SQLAlchemy link](https://docs.sqlalchemy.org/en/14/faq/sessions.html#faq-session-rollback) that the issue might be caused by an exception during a DB transaction which results in a rollback, but I don't understand this well.

What might have been the problem here and how might I prevent it in future?

Many thanks!

### Steps to reproduce:

N/A
  
### Observed Results:

N/A

### Relevant code exceptions or logs

  ```
Exception occurred within Telegram module
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/telegram.py", line 69, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 491, in _profit
    stats = self._rpc._rpc_trade_statistics(
  File "/freqtrade/freqtrade/rpc/rpc.py", line 348, in _rpc_trade_statistics
    trades = Trade.get_trades(trade_filter).order_by(Trade.id).all()
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2712, in all
    return self._iter().all()
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result = self.session.execute(
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database or disk is full
[SQL: UPDATE trades SET close_rate_requested=?, open_order_id=?, sell_reason=?, sell_order_status=? WHERE trades.id = ?]
[parameters: (8.204, '205066648', 'force_sell', '', 6778)]
(Background on this error at: https://sqlalche.me/e/14/e3q8) (Background on this error at: https://sqlalche.me/e/14/7s2a)

  ```

**Comment by bigsee** [comment]
P.S. I got this running again by restarting freqtrade on the server with `docker-compose`. It starting trading again but now I see some strange values under 'all trades':

```
ROI: Closed trades
∙ 431.469 USDT
∙ 368.903 EUR
ROI: All trades
∙ 8934157.969 USDT
∙ 7638642.524 EUR
```

On the assumption that I'm not now a millionaire (😅), does this mean that the DB's records have been corrupted somehow?

**Comment by xmatthias** [comment]
> `Original exception was: (sqlite3.OperationalError) database or disk is full`

I think the error is quite clear (although in combination with docker, it can have an alternative meaning).
Either your disk was full, or it had some other problem/error (like generic corruption).
As you seem to be using docker, make sure to check this BEFORE running any future docker commands - as `docker-compose down` may free some space.

It can also mean that sqlalchemy was unable to write to it - which could suggest that either your disk failed and was remounted in RO mode (happened to me on some crappy VPS from time to time and is fixed with a reboot).

Also regarding space - usually linux VPS's use multiple different volumes - so while /home/ might be full, your overall diskspace is still plenty - so you'll need to make sure to look at the right disks (where your database lies). You can check this with `df -h`

In the end, it's simply a write-error - which may lead to half-written records and database corruption (it's a file after all).
You may be able to "save" the file by opening it and look through the trades table - most likely one of the last records has some insane numbers ... removing that should bring your expectations back to earth :laughing: 

For future prevention ... best use some monitoring system (many VPS providers like DigitalOcean also provide some monitoring capabilities in their UI) to alert you on problems/errors.

**Comment by bigsee** [comment]
Thank you very much for your reply and for all your work.

Perhaps it was a disk space issue somehow. I had already used `df -h` to check this out before posting my issue. I can confirm that it shows different results now after the restart of the container, so not sure. Maybe something weird going on with Docker that I don't understand as there were definitely a couple of volumes saying 0% available that aren't saying that now, and one of them had `/docker/` in the path for sure.

I'm not sure that it was mounted in RO mode as one of the commands I could still use was to update the blacklist - `/blacklist [pair list]`. But I might also be wrong about that.

Anyway, will keep an eye on it as you suggest and see what monitoring tools the VPS provider has. It's a pretty reputable one I think, so hopefully there is something.

Cheers

**Comment by xmatthias** [comment]
`/blacklist <pair>` will not write to disk, but only keep the list to memory (it's not persisted, and disappears with a restart).
