### ISSUE TITLE
Freqtrade Backtesting optimization issue

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5653]
## Describe your environment

  * Operating system: Ubuntu Desktop
  * Python Version: 3.9.5
  * CCXT version:1.57.3
  * Freqtrade Version: 2021.9

## Describe the enhancement

*Explain the enhancement you would like*

When working with **large amount** of historical data, the ****freqtrade is using a lot of ram** while backtesting**, and when it isn't enough the **system just kills it** with no explanation, i had to resize my swap file size in order to make a such big backtesting.

Maybe i am the only  crazy one who is doing backtesting with a year of historical data, but this was just a big average test.

_I think it will be a good idea if the backtesting script would use a temp file for it's operations when the **ram is getting filled too much**
Also, it doesn't use multi threats for processing, it's a little slow when working with a lot of data_

**Comment by xmatthias** [comment]
With 16Gb of ram, i can backtest a year of 5m data pretty easily (obviously it'll also depend on the strategy a bit).

Backtesting itself is used by hyperopt (runs multiple backtests one after the other) - so everything that impacts beformance of backtesting negatively has to be avoided at all costs, otherwise hyperopt will become unusably slow.

Hyperopt is storing the data to disk (to move the data to other processes) - however for the duration of the backtest, the data is required in ram for quick processing.

It would technically be possible to store the analyzed data to disk (per pair) - but the performance impact for this is non neglectible (backtesting needs the candles for all pairs that happened at the same time, so we'd have to read all files again "candle per candle".
While this may be archivable - it'd mean a lot of disk operations, which are inheritly slower than normal memory operations.

If you don't have enough memory avaialble, the best bet is to use a large enough swap-file (maybe this should be added to the documentation).
It'll have similar performance implications - but without adding a ton of complexity to backtesting code - where i'd like to keep complexity mostly to the trading logic - not to handling memory edge-cases.
