### ISSUE TITLE
SharpeHyperOptLoss implementation

### ISSUE THREAD

**Issue by sidml** [freqtrade/freqtrade#5685]
I was going through the SharpeHyperOptLoss implementation [here](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/hyperopt_loss_sharpe.py)
It seems that the implementation is assuming the risk free rate to be 0 ! This doesn't seem to be a good assumption because the market isn't hovering around some mean value. If it were, then a risk free strategy like hodl will have 0 risk free return rate. In this case, assuming risk free rate to be 0 would have been justified.
Issues regarding the implementation have also been previously discussed [here](https://github.com/freqtrade/freqtrade/issues/27277).

**Comment by xmatthias** [comment]
You're not incorrect when it comes to a generic Sharpe ratio calculation, which shows the absolute value.

You'll however also consider how the value is actually used.
This particular case is however a hyperopt-loss function, so the concrete value it returns does not matter.
It's usage is to be calculated for every backtest result hyperopt produces (every epoch) - and then be used to determine which of these results is a better result.

All backtest-results in this context will have the same timerange - as well as timeframe. 
So 0 is as good a constant as any other, as it's purpose is not to be "THE sharpe ratio of this strategy" - but "is this result better than the previous one".

Using any other value may change the absolute value of the loss function - but the using a different risk free rate will not change which result is better or worse - as you'll still need to use the same risk free rate for every evaluation (in the context of one hyperopt run) - otherwise you'd not be able to rely on the hyperopt-result


This particular implementation is for sure unsuitable for generic calculations or statistics (for example #1907) - but for what it's used in the hyperoptLoss function - the risk free rate does not matter (is neglectible).
