### ISSUE TITLE
logging indicators

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#5707]
Hi;

I would like to be able to record in a log file the data of the indicators added in populate_indicators strategy file at the moment the bot open and close a trade.

How could it be done?

thanks.

## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well you can use `--logfile <logfile.log>` - which will write the standard log to disk (instead of only to stdout).

in your strategy, you should then be able to use logging, and output whatever you like to this file

``` python
# ... other imports
import logging
logger = logging.getLogger(__name__)

class MyawesomeStrategy(IStrategy):
    def populate_indicators(<...>):
        logger.info("MY text")
```

To get this at the "buy"/ "sell" points, best use the [confirmation callbacks](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation), which are called right before placing an order.
