### ISSUE TITLE
Problems trying to create a new API endpoint

### ISSUE THREAD

**Issue by sameh07** [freqtrade/freqtrade#5713]
* Operating system: Ubuntu
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.56.30
  * Freqtrade Version:freqtrade develop-11f08b005
  
api_schema.py:
class Test(BaseModel):
    test: str

api_v1.py
from freqtrade.rpc.api_server.api_schemas import Test ...
@router.get('/test', response_model=Test, tags=['info'])
def test():
    return RPC._rpc_test()

rpc.py
  @staticmethod
    def _rpc_test() -> Dict[str, Any]:
        return {
            "test": "New endpoint"
        }
rest_client.py
    def test(self):
        """Provides test analyse

        :return: json object
        """
        return self._get("test")

**Comment by xmatthias** [comment]
There's nothing obviously wrong except for syntax - but i suspect that's due to poor usage of the github platform (you can use tripple ` (followed by a language) to properly format code blocks).

Freqtrade is using pure fastAPI without any modifications - so your best bet will be the [fastapi documentation](https://fastapi.tiangolo.com/) to learn what is wrong.

As you're using docker, you'll also need to make sure that either the repository is mounted into the docker-container - or to rebuild the container each time.
With docker, you'll also need to use 2 different configurations (one with 0.0.0.0 to serve the API, one with 127.0.0.1 to call the api).

You're best off testing this part by querying one of the existing endpoints.

Also, while we try to assist users as much as possible, we're not supporting generic development problems, and assume that contributors (or future contributors) have a certain level of understanding of python (as well as the frameworks used that concern the files touched), or at least the dedication / capability to research basic problems on their own.

Otherwise, 90% of the work will be dumped onto maintainers to try and help clean up PR's - which we simply lack the time.
Thanks for your understanding.

**Comment by sameh07** [comment]
I do not see any syntax error here, I have used sysinfo as a guide.
