### ISSUE TITLE
How to close orders after selling them manually?

### ISSUE THREAD

**Issue by kurciqs** [freqtrade/freqtrade#5725]
## Your question

Look, I know this is the 3rd question within the last 24h hours, but I just sold the coins that the bot bought. 
The problem is that the bot still thinks the orders are real and working. He prints out every time that there's 4 different orders, even though my wallet only contains BTC and USD. 

Is there a way to cancel them?

The program works just fine, but I fear it might cause some trouble in the future. It also limits the program to think it only has 11 more buys left.

Thanks, help appreciated.

**Comment by xmatthias** [comment]
Please, before opening an issue, look at the Documentation.
Best read through it once (or at least fly over it) - so you know about the possibilities freqtrade has to offer.

It's really not fun answering questions the documentation covers - and it's also not a good way to get known in a project.

it's usually better to use [`/forcesell <tradeid>`](https://www.freqtrade.io/en/stable/telegram-usage/#forcesell) to sell pairs manually rather than selling them on the exchange.
Tha has the bot handle the sell - and it'll be recorded properly in the database.

As it's too late for that, you can either use the [sql cheatsheet](https://www.freqtrade.io/en/stable/sql_cheatsheet/) to manually update the database (be sure to use the correct values ...), or use `/delete <tradeid>` via telegram to remove the trade from the database completely (which is probably the easiest way).
