### ISSUE TITLE
Plotly Module Missing from Docker Image, arm64, need help

### ISSUE THREAD

**Issue by ppkantorski** [freqtrade/freqtrade#5729]
* macOS 11.6, M1 Mac mini 16gb, latest docker image

I am having the same exact issue as #3927, plotly module is missing.  I am using the latest docker image.  There was a solution posted, but I am confused as to how to apply it.

```
USER ftuser
# Install and execute
COPY --chown=ftuser:ftuser . /freqtrade/

RUN pip install -e . --user --no-cache-dir --no-build-isolation\
  && mkdir /freqtrade/user_data/ \
  && freqtrade install-ui

RUN pip install --user plotly

ENTRYPOINT ["freqtrade"]
# Default to trade mode
CMD [ "trade" ]
```

How do I run this command?  Do I modify the .yml file?  Can some one please explain the steps?  I am new to Docker.

**Comment by xmatthias** [comment]
first of all, be careful with solutions provided over a year ago. Things change all the time, so the solution posted there is no longer uptodate.


To use plotly via docker, youcan use the provided, prebuilt `*_plot` image.

Simply put - in your compose-file - use `freqtradeorg/freqtrade:stable_plot` as image (as also [documented here](https://www.freqtrade.io/en/stable/docker_quickstart/#plotting-with-docker-compose)), then you can use the plot-functions (`plot-dataframe`, `plot-profit`).

**Comment by ppkantorski** [comment]
Thanks for the quick response.  stable_plot helped, all is well.  On a suggestion side, I have found that using matplotlib.pylab + streamlit works better for displaying larger datasets (and data overall).  When you have too much data on plotly, it really has a hard time handling it.  I've been working on my own bot similar to this one for a while now, went down the Plotly route a long time ago before realizing its caveats.  Anyways, thanks again, really appreciate the assistance.  Feel free to close.

**Comment by qkum** [comment]
Sorry, but noobs like me still don't understand much.

Because we never encountered something like this before.

We need it spoon-fed sorry @xmatthias 

And I have read the documentary, but it is super confusing for non-veterans.

("Simply put - in your compose-file - use freqtradeorg/freqtrade:stable_plot as image ") = Normally means to "uncomment" something. But when I uncomment _"# image: freqtradeorg/freqtrade:develop_plot"_ I just get a docker cant read the docker-compose file error.

("To use plotly via docker, youcan use the provided, prebuilt *_plot image.") Makes no sense. Do we need to replace/delete freqtradeorg/freqtrade:develop_plot with "*_plot"? (sorry for the missing regex but the website removes  them)

Here is an image so we both agree what we are looking at.

Thanks a lot for your help and hard work as always.

![aaCapture](https://user-images.githubusercontent.com/40965179/137648301-bbe36f8d-f2e8-4879-a66f-f12cdc18e78a.PNG)

**Comment by xmatthias** [comment]
@qkum don't need to be a docker veteran to search the internet ... :)

You can uncomment any of the image: lines - but you'l need to make sure it's there only once. That's got nothing to do with freqtrade, but with a simple research on how docker-compose files work.
