### ISSUE TITLE
Freqtrade converts BTC to other coins Binance

### ISSUE THREAD

**Issue by Trance98** [freqtrade/freqtrade#5766]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.9 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
My freqtrade live instances are converting my BTC to other crypto on Binance when trading. Why does this happen? Is there a way to prevent it from happenning?
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
based on the description, i have no idea what you think it's happening.

If your stake-currency is set to BTC, then freqtrade will use BTC to trade against other currencies.
It'll buy a coin (say XRP) - and then sell this coin again, hopefully for a profit.

**Comment by Trance98** [comment]
Yes, my stake currency is BTC. What I'm finding is that my bots are trading BTC against other currencies, and they don't fully convert the other currencies back to BTC. My Crypto portfolio is getting more diverse per trade because when the bots close the trades(in profit/loss), it seems like there's always a residual amount of whatever crypto the BTC was traded against. To converting those residual amounts back to BTC after the trades have been closed is costing me in conversion fees as I have to convert the small balances to BNB then to BTC.

**Comment by xmatthias** [comment]
This is then caused by fees.
On binance, you're always paying the fee in "receiving" currency - 
For example: your bot enters a XRP/BTC trade (you wanna get 100 XRP) - you'll really only get 99.9.
now maybe XRP trades in 1x lotsizes, so you can only sell 99 XRP (you're left with 0.9 XRP).

these 0.9 XRP are called dust (it's often called binance dust ... as that's the most common exchange this happens).

The exact same thing will also happen with manual trading, you'll just not notice as much, as you'll probably not be buying (and selling) 50 different cryptos in a week.

You can avoid this by having BNB in your account (and enable BNB for paying fees).
Alternatively, leave the dust in the different coins, and freqtrade will eat into the 0.9 XRP with the next trade it opens on this coin. It'll however probably never go to exactly 0 - but it'll at least reduce the amount, and not make it worse over time.

Personally, i feel it's binance's attempt to get more people to own / use BNB to pay fees ... but it's at the exchanges disgression how they handle fees in the end.

**Comment by Trance98** [comment]
Makes sense. Thank you. I will try using BNB to pay for the fees and see how that works out.
