### ISSUE TITLE
buy_tag with value from dataframe

### ISSUE THREAD

**Issue by heizie78** [freqtrade/freqtrade#5778]
I'd like to add a value from the dataframe to my buy_tag. Within populate_buy_trend() I'm trying to do the following, but for the **bold** part it fails. Without that it is working fine. Can anyone help? Thx.

dataframe.loc[
            (
                    (dataframe['sl_prev_curr_scenario'].isin(self.buy_scenarios.get(metadata["pair"]))) &
                    (dataframe['sl_scenario_change'] == True) &
                    (dataframe['volume'] > 0)
            ),
            ['buy', 'buy_tag']] = (1, 'b|' + metadata["pair"] + '|' + **dataframe['sl_prev_curr_scenario']**)

**Comment by xmatthias** [comment]
please get used to fill out the issue template. You may think it's not needed, but we put it there for a reason, so not filling it out is like ignoring what we ask for (You'd not like that on your questions either, would you?).

---

The problem is that you're adding a series of type object (`dataframe['']`) to a constant string, which is not supported as such by pandas (so the 2nd part of the tuple would fail also without the assignment).

According to google / [stackoverflow](https://stackoverflow.com/questions/20025882/add-a-string-prefix-to-each-value-in-a-string-column-using-pandas) - `dataframe['sl_prev_curr_scenario'].astype(str)` should work for this - but i've never tried such.
In general, i'd recommend to research this independently of freqtrade, but in a pandas context - as i'm sure there's 100ds of people who encountered a similar problem before - and using string columns is not something very common with freqtrade, so your support here will be rather limited.
