### ISSUE TITLE
binance trades

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#5797]
## Describe your environment

  * Operating system: Raspian
  * Python Version: _____ (`3.7.3`)
  * CCXT version: _____ (`1.59.2`)
  * Freqtrade Version: ____ (develop)
  
for a few days, the bot has stopped trading, really open trades, I have looked in the logs, I do not find anything different, I use the same strategy and the same configuration file, in the same raspberry, everything exactly the same, I decided to change From stable 2021.8 to 2021.9, as it was still the same I decided to go to develop.

I do not find any errors in the bot log, the only thing is 

ccxt.base.exchange - DEBUG - GET https://api.binance.com/api/v3/klines?interval=1h&limit=1000&symbol=NUBUSD&startTime=1635023580000&endTime=1635200014223, Request: None None
anytime api dont request.

What could be the problem? 

thanks.

**Comment by xmatthias** [comment]
Markets change, so potentially, your strategy found some market condition where it's not trading for a while.

If the logs don't contain any other information, then we'll have to assume that it's the strategy that isn't generating any buy signals (most likely temporarily, maybe because BTC did "something" ...

**Comment by anakein** [comment]
but, this strategy in same computer with same config on kucoin is working and i have trades.

**Comment by xmatthias** [comment]
markets behave slightly different on different exchanges  - so just because it works on kucoin does not mean it'll also work on binance.
You'll probably also have different pairs / different pairlists - but even if not, you cannot assume that a good strategy on kucoin will also work on binance. 

You'll have to backtest the strategy on each individual market (assume BTC/USDT on kucoin to be a different market than BTC/USDT on binance) - and you'll see that they will not perform identically, even with the same strategy / same pairlists/same timeframes.

**Comment by anakein** [comment]
I fully understand what you are saying, but believe me if I tell you that I have written this after reading everything possible and a thousand tests. 

At first I thought the same, things of the market. But a strategy with an average of 2 trades per day, which has been fulfilled more or less always, having changed from volume to whitelist to check between exchanges with same pairs,, and the only purchase that I had in binance was curiously in a restart.

zero buy signals in 1 week, there is a problem. 

I even changed the strategy to one that I have for testing that constantly buys with an average of 30 trades per day, even with that strategy, zero buy signals.
Obviously the problem does not seem to be in the bot, i think this is in binance and its api.

**Comment by xmatthias** [comment]
well, you provide one single log-line, and expect us to make wonders, while at the same time blaming the binance API.

If it's a API problem, it would impact everyone (it doesn't my bot buys just fine).
This means, it's probably a problem with your setup (maybe api keys are wrong, maybe no buy signals) ...
Either case would show in the logs - but not in the one line you deem suspicious, but in a wider log range.

You can also check to see if you got pairs (`/whitelist` in telegram?) in your whitelist, but also this would show in the logs ...

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
