### ISSUE TITLE
Why do we need to re-download data on bot reload? 

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#5803]
Every time we do a reload to the bot it does download all the data, while it can cache the data and on reload get only the new data and merge old + new. 

is there any specific reason why it does not do that? Or it's just a feature that was not implemented yet ?

Thanks.

**Comment by xmatthias** [comment]
for the future: issues without issue-template will be closed without further comment in the future, so please fill this out.

Assuming you're talking about `/reload_conf` - then this is intentional.
It's tearing almost the complete bot down, only leaving the "outermost shell", before starting up everything again.

In some instances, caching would be possible, but you could also completely change the configuration (different stake-currency, different database, different exchange) - so handling caching would become difficult.

it also shouldn't be very common to reload the bot very often (if you do, you probably have a different question, really) - you'll not be changing your configuration every few minutes once the bot is running stable ... so i don't really see this as problem.

Caching would also mean we could not tear the bot down the way we do now, so you would be unable to use `/reload_conf` to solve some certain errors (like when the exchange returned invalid markets, causing the pairlist to be empty) - as that would then be cached, too.
We'd also have to manually detect what changed in the config, and invalid / drop the cached data selectively - which simply put - i see as unnecessary, and rather risky (and as such - not worth the effort to implement, and more importantly, to maintain - as this WILL become a maintenance problem).

**Comment by botzill** [comment]
I mean reloading bot itself as new changes are made in strategy file as we are improving it all the time. In our case, we do not change the config so often, mostly strategy improvements. I think having a way to cache it/reset when needed(via the config option) can be a good use case as well.

Also, why do we need to get all the last X(1000) candles at each timeframe interval refresh? Don't we need only the last one and merge it with the candles we already have?

**Comment by xmatthias** [comment]
You'll usually not change the strategy while running, but develop the strategy using backtesting, and then let it run in dry-run (unchanged) for a few days/weeks. 
If you're constantly changing the strategy, then i doubt you can make good evaluations on what worked and what doesn't, as your changes will compete with the market - so maybe something that didn't bring any improvement today will be ripped out tomorrow - but in tomorrow's market it would've been good.

> Don't we need only the last one and merge it with the candles we already have?

This is correct in theory - but will not lead to any improvement in practice.
It'll move the complexity of combining the candles to freqtrade (also more calculations) - but will still require the same amount of calls towards the API (which is the slow part) - so it's pretty pointless (and potentially error-prone, depending on the reliability of the exchange.
