### ISSUE TITLE
Kraken Will Not Buy

### ISSUE THREAD

**Issue by Smone5** [freqtrade/freqtrade#5815]
## Describe your environment

  * Operating system: Ubuntu 21.04
  * Python Version: Python 3.9.5
  * CCXT version: ccxt==1.58.47
  * Freqtrade Version: develop-0da5ef16e
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I am unable to buy or sell in the Kraken market. I am able to get data using the API and can see a buy signals happening in the code, but no orders are ever  made on the Kraken exchange. The code works fine in Dry Mode,  just when I go live it never buys and appears to keep running and running with no issue when it should be having a buying issue some sort.  

### Steps to reproduce:

  1. Test the bot in Dry-Mode, works
  2. Test the bot in Live Mode, fails
  
### Observed Results:

The bot never makes an order even though it is getting buy signals

### Relevant code exceptions or logs

There is actually nothing in the logs I can see an issue with. The logs look fine. That is why I am confused. I am wondering if it is a CCXT issue or something else that changed recently? I just put in code to know when the a buy was happening and I could see a buy should have occured, but it didn't. It works in Dry Mode, so it is something about Live mode.

<img width="1013" alt="Screen Shot 2021-10-29 at 11 03 06 PM" src="https://user-images.githubusercontent.com/19376953/139518116-9e698b04-aa93-4200-9fcb-31f5fc1a7269.png">

**Comment by xmatthias** [comment]
if there's an issue with the buy (ccxt / kraken / your api keys) (with placing the order) - you'd see this in the logs.

as you don't provide any information where you print the "buy" - it's pretty difficult to tell ... 
one thing you should check is if you have colliding buy/sell signals (if both buy and sell is active, freqtrade will not act).
The frequent "wallets synced" however hints that it's entering the enter trade path (otherwise i don't think it would sync this often) - but seems to encounter some issue.

You should definitely check the output of `/balance` to see what your balance looks like.
Maybe your api key permissions prevent the bot from seeing any available capital - and obviously it'll not attempt a buy if the available balance is 0.

Another thing to keep in mind with "reduced" logs is that some log-messages are only shown once per candle - so you might wanna check a wider range of logs to not miss certain logs (like - pair is locked for example).

Also, best let us know part of your settings (specifically everything related to balance, like `stake_amount` - and if applicable `available_capital`.


You can certainly run freqtrade in verbose mode by appending `-v` which will also log debug messages - but don't run it too long in that mode, as it's VERY verbose, and you'll need to scroll through a lot of "unnecessary" stuff before getting to what counts.

**Comment by Smone5** [comment]
Ok thanks for the response and giving me a few things to try. I will try them in the next few days. I think the verbose mode will help me a lot. It could be a settings in configuration as well. I am using dynamic balance. 

My code to show a buy was real simple:
```
        last_row_df = dataframe.iloc[-1:]
        val = last_row_df.loc[-1:,'buy'].reset_index(drop=True)[0]
        if val == 1:
            print('buy')
```

Below is also my settings in config for the account balance. I am able to see my actual account balance in Telegram when I enter "/balance". So that seems to be working. The API is getting some data. Something is stopping a buy. 
```
    "max_open_trades": 6,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 1000.00,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 5,
        "sell": 10,
        "unit": "minutes"
```

**Comment by xmatthias** [comment]
it'll depend a bit on your balance i think.
with this config, i can imagine that you run into "not enough money" issues if you got a "lowish" balance.

On kraken in particular, minimum limits depend heavily on the pair - but are in general pretty high (30$ and up) - so you should make sure you've got enough money for this config (your balance / 6 > minimum limit).

You should also print the "sell" column (and the pair) - as colliding buy/sell signals (both columns 1) will prevent buys.

Also make sure that your balance is actually in USDT (not USD or EUR) ... but i would not use USDT on kraken, you'll only have 12(ish) pairs to trade in that case ...

**Comment by Smone5** [comment]
The issue is resolved. It was my error. I was simply staking the wrong currency. The verbose output communicated it was canceling a trade because the stake amount was 0. So it became obvious it wasn't staking because I didn't have any balance to stake. Thanks again though.

**Comment by mdelhaous** [comment]
Hello everyone,

I’m currently setting up a Freqtrade bot using the config_examples/config_kraken.example.json file from the official repository. I’m running the bot in dry run mode to test my strategy, but I keep encountering the following error:

ImportError: Short strategies cannot run in spot markets. Please make sure that this is the correct strategy and that your trading mode configuration is correct. You can run this strategy in spot markets by setting can_short=Falsein your strategy. Please note that short signals will be ignored in that case.

What I Need Help With:

Strategy Configuration: What’s the correct way to configure my strategy for spot markets? Should I be disabling short signals entirely?
Error Resolution: How can I resolve this error and successfully run the strategy in dry run mode?
Any advice or pointers would be greatly appreciated!

Thank you!

**Comment by xmatthias** [comment]
@mdelhaous you're running a strategy made for futures (`can_short = True`) on a spot market.
While the simple solution is to change that flag - it's unlikely that the strategy will "just work" - as it may assume it can take short positions - which you can't on a spot market.

Now i'd apreciate if you'd not highjack **3 year old** issues with your problem that has absolutely nothing to do with it other than using the same exchange.
i'll hence lock this issue to prevent further noice in a long-closed issue.
