### ISSUE TITLE
startbuy command and stopbuy status from rest API

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/freqtrade#5836]
I'm using Freqtrade containers v2021.09 stable.

I'm working on a multi-bot external controller and I'm currently using the rest API feature to control them based on the whole entire market movements.

Now, sometimes I need to check bot status connected to the controller but `show_config` is not telling me if they are in a `stopbuy` state. Is there another way to find this info from the rest API?

Connected to this, my controller often use the `stopbuy` command. Is there any possibility to add a `startbuy`  instead reloading the entire configuration?

I'm not aware about the correct structure of Freqtrade, if you tell me that is possible to do (it's not code-breaking) I start to work on this.

Thank you for your work!

**Comment by xmatthias** [comment]
`/stopbuy` simply sets the max_open_trades to 0, and is not a "state" on it's own. 
so you should be able to check this via the count endpoint.

There is no endpoint / possibility to change max_open_trades via another endpoint, so you will have to use `/reload_config` to get back to your initial configuration.

It's also really meant for "slow, controlled shutdown" - where the bot stops buying, and exits trades in a controlled way, not as a measure to stop/start a strategy dynamically.
A much easier way for this will be to have this as part of your strategy conditions - for example, writing a small "flag" file - and if it's there, never set buy=1.

**Comment by pizzidellamaremma** [comment]
Ok, so the `stopbuy` set max_open_trades to 0. Now the `reload_config` makes sense...

My idea was to use exacly this controlled shutdown. 
Right now I can't create a common file between two containers because they are on separate machines and use only API calls to communicate.
Is there a way to split `reload_max_open_trades` from `reload_config`?

**Comment by xmatthias** [comment]
technically, it's for sure possible, but it's not planned anytime soon.
Restarting the bot with `/reload_config` is not a big deal ... so i don't see why that should be a problem.

If we implement an endpoint to modify configuration "on the fly", it'll however not be limited to this setting alone, as that would provide almost no benefit, while increasing the maintenance to this part of the bot (ensure it continues to work, ...)..

Allowing the change of settings on the fly has however wider implications as changing settings on the fly would not persist - so it'd only be "this way" until the bot is restarted. 
That however would create a quite bad UX (i changed this value to 5 - but it reset to 3 due to a server reboot) - and is therefore currently not possible, and also not planned to be done anytime soon - simply because this would provide very limited benefits, and will in the end not really make the people any profits.

**Comment by pizzidellamaremma** [comment]
I wasn't thinking about changing on the fly but an opposite command to `stopbuy` where it will reload only the exact number from the configuration file to make the bot start again the trades.

I will try some workarounds and I'll let you know.

**Comment by pizzidellamaremma** [comment]
I resolve it with a singleton status class.

Thank you for the support.
