### ISSUE TITLE
jupyter notebook root permission (how to install 'libgomp1')

### ISSUE THREAD

**Issue by WL0118** [freqtrade/freqtrade#5838]
## Describe your environment

  * Operating system: ____WINDOW 10 (docker_jupyter notebook)
  * Python Version: _____ (`python -V`) 3.9.7
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ freqtrade docker-20a61e03
  
## Your question

I am building my code with jupyter notebook(docker-compose-jupyter.yml). This is my first time using docker, so that I am not used to it. I hope someone help me to solve this problem. 

I am trying to install 'libgomp1' with this commend 'apt-get install libgomp1' on the jupyter notebook terminal(docker). However, this command requires the 'root' permission. Where can I find the password for the root? or how can I install 'libgomp1' on this jupyter notebook.

Also, please let me know how I can install 'libgomp1' in docker(docker-compose.yml) as well.

**Comment by xmatthias** [comment]
This is intentional, and is best practice for security reasons.

you can try to simply prefix your command with `sudo`.
If that doesn't work, you'll need to install dependencies in your docker file, which you should be able to easily change and add the following 3 lines (you'll obviously need to rebuild the image after that).

```
USER root
RUN apt-get install <whatever>
# Reset the user to ftuser
USER ftuser
```

**Comment by WL0118** [comment]
Thanks a lot!!!
I solved this problem with your help.
