### ISSUE TITLE
Member function of the strategy class to reduce an active trade amount by X%.

### ISSUE THREAD

**Issue by donjonson** [freqtrade/freqtrade#5857]
## Describe your environment
(if applicable)

Operating system: ____ Ubuntu 20.4
Python Version: _____ (python -V) 3.9.4.1
CCXT version: _____ (pip freeze | grep ccxt 1.59.2)
Freqtrade Version: ____ (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)
freqtrade develop-c7edffb

## Describe the enhancement

*Explain the enhancement you would like*
I am asking for something like a custom sell except I am asking for the bot to transfer some percentage of a trade out of its control. 

effectively I want to keep a portion of a trades profits for a given trade and leave it in whatever currency pair I am trading.  Basically it is a way to dollar cost average in to many coins for free.

**Comment by xmatthias** [comment]
Please use the search to find similar issues to the one you have.

Freqtrade does not support position staking, and an existing request can be found in #1519 .

**Comment by donjonson** [comment]
sorry this request is not for position stacking. it is to enable me to keep a portion of the coins the bot purchased and transfer them to another wallet without confusing freqtrade.

**Comment by xmatthias** [comment]
technically (under the hood) - it would be the same than position staking (but on the exit side) - as you'll only sell part of the trade (so you scale down a position).
Currently, freqtrade always trades in full lot sizes - selling (or buying) parts of a trade is not possible.

That will surely not be possible before position-staking is enabled (simply because the underlying parts are not there).
And to be honest, i currently don't really see this as something we'd want in freqtrade, as i don't see any reason to have this, other than increase your risk.

What a strategy like this would really do is the following:
buy coinX for 100$ (1$ a piece - so you get 100 coinX) - but forget about 50$ of this (this is what you keep).

Now assuming this trade goes against you - and freqtrade sells the remaining 50 coinX for a rate of 0.7$ (you used 30% stoploss).
Now your problem here is - your loss is not just these 30% - but potentially 30% + the 50$ you moved away - because the coin continued down and is now only worth 0.01$.

While it's obviously your money to trade - freqtrade's assumption is that it'll handle the trades it opens - and this is a base assumption i don't see changing.
