### ISSUE TITLE
huobi exchange

### ISSUE THREAD

**Issue by graz68a** [freqtrade/freqtrade#5915]
## Describe your environment

  * Operating system: Almalinux 8
  * Python Version:  3.9
  * CCXT 1.61.24
  * Freqtrade Version: 0.2.1
  
## Your question

I am trying to use huobi API with cctx/freqtrade bot however when I connect to huaobi I receive this

2021-11-17 10:29:19,350 - freqtrade.rpc.api_server.webserver - ERROR - API Error calling: All balances are zero.

I have  500 USDT in my huobi Exchange Wallet (USDT) 

cctx can connect to huobi to get pairs however it fails to get the balance.
Is it a freqtrade issue with huobi ?

**Comment by xmatthias** [comment]
If i remember correctly, then huobi requires a 3 tokens (key, secret and password) for the API to work, so you'll need to configure this.

With a reduced log however, it's very difficult to work with, as the log usually includes some more information, where we can read more than what you're giving.

---

Unfortunately, i cannot recommend using huobi at this point. 
You're probably the first to use it - but more importantly, it's also not providing any historic data (past 1500 candles from current time) - so it will be impossible to backtest your strategies.
Using data from other exchanges is VERY risky, as markets usually move slightly different between exchanges - so backtests should always be performed on data from the correct exchange - which is however impossible with huobi due to their API not having a historic ohlcv endpoint / parameter.

I'd recommend to pester huobi support about this - hoping that they'll add such an endpoint when enough people request it.

**Comment by graz68a** [comment]
thank you

**Comment by xmatthias** [comment]
> thank you

does that mean it's working now so we can close this?

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
