### ISSUE TITLE
How get available_pairs on class level?

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#5920]

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

As this issue also contains no content, i'll simply close it.

Please write proper issues (including the issue template, and a description of what you want to accomplish) in order to get questions answered.
