### ISSUE TITLE
Bar replay 

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/freqtrade#5951]
The backtesting in crypto is grossly inaccurate due to huge changes in the top 100 by volume pairs when we run through a period .
The dry run is the only way currently to test the stratergies in a reliable way.  However  for it to be reliable it takes a long time.

The solution for this is bar replay testing, This can already be found in trading view and amibroker and other applications. In this the each candle is fed one by one the application. This will really emulate the dryrun and wecan do it on histroric data and all the features in the dry run or live testing like volume pair list , edge etc can be applied if historic data is available correspoding to those or can be downloaded as in the dry runs. The performance and time required compared to backtesting will be very low however the reliablity of the results will improve greatly. The implemention will not be so complex as only requirement might be to feed historic data to the current dry run process.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

Please consider this as your last warning - your next issue without issue template will be closed without further comment.

---

Also, please don't open repeat questions - you asked basically the same question in #5833 (just with different wording) - and the answer will not really change.

You can use backtesting's `--timeframe-detail` to use a lower timeframe during backtesting (as documented [here](https://www.freqtrade.io/en/stable/backtesting/#improved-backtest-accuracy) - but it will use the same pairlist throughout.

Implementing a "speed up dry-run" is currently not possible, nor will we work on it anytime soon. 
The accuraccy will also not be what you expect, as it'd still be missing intra-candle data - which is what freqtrade is really using in a dry-run to determine if stoploss or ROI happened first within one candle, so there would be no real difference to backtesting with 1m detail timeframe.


If you think it's "not complex" - feel free to submit a Pull request (including passing tests please) for this - but as you're opening an issue, not as completed pull request - i think it's a "i think it's not so complex, someone else please implement it" question - which makes the "it's not so complex" statement invalid.

**Comment by bibinvargheset** [comment]
Its not abour timeframe detial, yes it can also be used, stoplosses can take candle low, the real need  is the dynamic volme pair list  , edge etc that is available in real/ dry runs to be used in backtesting, whether it be regular backtest or bar replay. Yes it is duplicate in terms of ultimate goal to have reliable backtest, I am trying to solve this issue but there are time contraints and lack of knowlegde about your huge and excellent  project.   As i have explained the current backtest are hugely inaccurate and irrelent in th crypto context and any methods we are implenting in the realtime should be available in the backtesting to make simulations relavaent and realistic.

**Comment by xmatthias** [comment]
what you're asking for (bar replay for dry-run) will not be possible as easy as you'll think - as all exchange calls will need to return a "proper" value, which has both correct content (for both the bot situation, as well as the assumed pricing on that moment).

Maintenance effort for that is almost certainly pretty high - so unless you can come up with a pretty minimal way to approach this, it's not something we'll support anytime soon.

supporting volumepairlist in backtesting might be possible (also with changing pairlists) - but is a different topic altogether.

Please leave edge out of this equation. 
Unless someone finds love in it and "adopts" it to work on it further (and maintain it), it'll probably be removed sometime in the near/mid term future, simply because the maintenance effort for it is higher than the gain it brings to the project (not to one particular strategy/user - but to the project itself).
