### ISSUE TITLE
run "Dry Run" forever

### ISSUE THREAD

**Issue by tabwnymhmd** [freqtrade/freqtrade#5954]
## Describe your environment

  * Operating system: ____( `Microsoft Windows [Version 10.0.19042.1348]` )
  * Python Version: _____ ( `python -3.10.0` )
  * Freqtrade Version: ____ ( `freqtrade - 2021.10` )
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**HELLO
I tested the bot on dry mode with the telegram. My problem is when I turn off my laptop the bot is stopping, how can I run the bot even the laptop does not work**

**Comment by xmatthias** [comment]
freqtrade requires to run all the time, so you can either leave your laptop on (not recommended, also due to potential network issues) or use a VPS (virutal private server).


You can get rather cheap ones on sites like vultr or digitalocean, or use the "oracle free tier" armhf offering (it will however require a reconfiguration after the free tier ends).

**Comment by tabwnymhmd** [comment]
Thank you for helping
