### ISSUE TITLE
Translation to Persian

### ISSUE THREAD

**Issue by AlirezaM02** [freqtrade/freqtrade#5960]
## Describe the enhancement

Due to many appeals from Iranians for a bot with such abilities, I've started to translate the bot UI and some other parts if possible to Persian language.

**Comment by xmatthias** [comment]
While i appreciate your efforts, i think the time would be better spent in working on other things (for example improving the existing documentation / wording, or working on "good first issue" issues).

Neither the UI, nor other bot internals contain difficult language  (nothing a simple google translate could not help with).

While i can potentially see benefits for the documentation, it's not something we will be adding or supporting anytime soon for the following two reasons:

* no one can validate the correctness of the translations due to lack of knowledge in these languages
* no one will maintain this going forward.

Therefore - thanks for your efforts, but we will not be able to accept any contribution in this regards.
