### ISSUE TITLE
Buy signal not executing at time

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#5968]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____3.6.8 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I have buy signal timeout 1 min on plot it shows buy signal at that time but it is executed 2-5 minutes later.  My config for buy is:
    "unfilledtimeout": {
        "buy": 1,
        "sell": 1,
        "unit": "minutes"
    },
	"order_types": {
		"buy": "limit",
		"sell": "limit",
		"emergencysell": "market",
		"forcebuy": "market",
		"forcesell": "market",
		"stoploss": "market",
		"stoploss_on_exchange": true,
		"stoploss_on_exchange_interval": 30,
		"stoploss_on_exchange_limit_ratio": 0.69,
	},
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
Is it possible to get this at time like it is ploted.

**Comment by Theagainmen** [comment]
The buy-timeout starts counting once you get the 'buy' message (in Telegram for example). I assume the delay you are talking about is because you see the buys happening a few minutes after the candle should have arrived? This is probably because you are running a strategy that requires a lot of resources (and you maybe run on low-end hardware), because of that it can only run your strategy completely every few minutes.

So what you should be looking at instead I think for your issue is this https://www.freqtrade.io/en/latest/configuration/#ignoring-expired-candles, this way if the buy signal happens 2 minutes after the candle arrived, due to your strategy being too intense and thus it needed those 2 minutes to calculate a possible buy signal, you can cancel it with this setting.

However can you verify maybe with the Telegram that your buy-messages times are the same as the ones in the plot? And what timeframe are you using?

**Comment by xmatthias** [comment]
Limit orders may or may not fill, depending on the price movements that happen.

Order timeouts (unfilledtimeout.buy and unfilledtimeout.sell) are not part of the plots - and are not directly tied to your strategy either. They simply cancel the order after the specified amount of time, with this time starting when the order is placed.

Your buy (when the order is created) should more or less align with the chart - unless your strategy takes too long to calculate signals - which means your system has trouble calculating everything in time. 
You can counter this to some degree with a shorter pairlist, or by using fewer indicators, or by simply upgrading your system to a more powerful one.

**Comment by zorann** [comment]
Ok thanks. I reduced max trading pairs ar and now works ok. Can i still ask you how to stop pair from trading for 1 hour if it drops 10%. I tried many ways but no success.

**Comment by xmatthias** [comment]
it'll depend on your timeframe ... 
assuming you use 1h candles, you should be able to use something like this as a "blocker" (note that you'll probably be too late, as it'll wait for the candle to close, and will not cover intra-candle swings either.


``` python
dataframe['dropped_too_much'] = dataframe['close'].pct_change(1) < -0.1
```

It's untested - and you'll need to incorporate it as guard in your strategy somehow...
you might also want to consider the 10% as a hyperperameter ... but that's then details you'll need to figure out by experimentation.
