### ISSUE TITLE
Unable to analyze strategy with informative dataframes

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#5975]
Have you searched for similar issues before posting it? Yes

## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10
  * CCXT version: 1.59.77 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop, updated today (also happened with a two week old develop version)
  
## Your question

I am using the Jupyter notebook template to analyze my strategy but it throws an exception as the strategy tries to load the informative dataframe from the dataprovider object that does not exist. I can't find information on how to initialize it, or give the historical data to the strategy resolver. 

The exception is: "AttributeError: 'strategy1' object has no attribute 'dp'" when executing 
informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)

Thanks!

**Comment by xmatthias** [comment]
yeah, i guess that's correct.
Dataprovider is injected into the strategy class at a later point. 

For full informative support (including the `@informative` decorator), you'll need an exchange class as well, which you'll not be able to create in the notebook without problems due to some async "magic" jupyter thinks is clever, which means full dataprovider support in a notebook will currently not be possible.

For limited support, you should be able to get away with the following:

``` python
from freqtrade.data.dataprovider import DataProvider

# create strategy object
# ...
strategy.dp = DataProvider(self.config, None, None)

# ...
```

As mentioned above, this will be limited to "regular" informative pairs, not the `@informative` decorator - but it'll work for most cases this way.

**Comment by dnuno89** [comment]
Thanks! This solves my issue.
