### ISSUE TITLE
Rest Api : Not authenticated

### ISSUE THREAD

**Issue by alimertustundag** [freqtrade/freqtrade#5981]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.8.10
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop
  
Hello guys, Sorry in advance for my bad english.

I want to write my own administration panel with rest api. But when I request username and password to get token, it gives me this error. "{"detail":"Not authenticated"}".

Values I Submit
username : ***
password: ***
botName: freqtrade
botUrl: http://127.0.0.1:8080

**Comment by xmatthias** [comment]
Well the message says it all - not authenticated, which means that your username/password is wrong (or the provided authentication information is wrong, anyway).

While we do support username/password (basic) authentication for all endpoints at the moment, please consider this as deprecated, and use JWT authentication for all endpoints except for the token endpoint.

You can enable the [openAPI panel](https://www.freqtrade.io/en/stable/rest-api/#openapi-interface) which will allow you to play with the endpoints interactively.

Freqtrade offers freqUI as UI, which is supported and will be developed further.
I'd also encourage you to consider contributing things you think are missing to freqUI instead of starting from scratch.

While you're free to make your own - we will not provide support for this.
So we assume that you're able to implement authentication (and understand an openAPI specification) without further assistance, otherwise, it's best to use freqUI.
