### ISSUE TITLE
Cant start trading

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#6017]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____3.8.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____2021.11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
After updating freqtrade and starting trading in dry-run i get these errors
2021-12-02 10:44:01,656 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 615, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 418 Client Error: I'm a teapot for url: https://api.binance.com/api/v3/exchangeInfo

**Comment by xmatthias** [comment]
a response code of 418 from binance is usually a sign that you're hitting the API too often (maybe you got some other bots running from the same IP).

I guess it can also happen when their api has problems - but it's pretty unlikely.
As it's on startup, i don't think it's because of this one freqtrade instance (not unless you have ccxt ratelimiting completely disabled).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
