### ISSUE TITLE
Publish APP mobile on markets

### ISSUE THREAD

**Issue by vallemar** [freqtrade/freqtrade#6023]
I have created a mobile client application to connect to our freqtrade servers through the integrated Rest API.

The application is public and anyone can help or just take a look: https://github.com/vallemar/freqtrade-app

I plan to publish the stable versions in the iOS and Android markets. Is there a problem if the application is called freqtrade?

Thank you!

**Comment by xmatthias** [comment]
Letme ask a different question first.
Why did you start a new application from scratch, instead considering contributing to [FreqUI](https://github.com/freqtrade/frequi)?

While freqUI is not "really" mobile friendly at the moment - that's only a (most likely pretty small) contribution away, and it's something that we are working towards.

your application seems like it is actually just a javascript application, not a native android/ios application.
It's even based on Vue, which is the same framework FreqUI uses, but a quick glance (at least based on the readme) makes me think it has fewer features than freqUI.

As such, i'd instead encourage you to contribute to freqUI, helping improve that (especially the mobile part), as you seem to have quite some skills there.

We can obviously also add "compile to mobile app" capabilities (so the Vue app can be compiled to android/ios), but i have to admit, i have very little (speak no) experience with that, and would probably do a PWA instead.
i don't really see a benefit of a "real" app for this (not for your project, not for freqUI) - as it's really just a webpage, with little to no direct interactions with device capabilities (like a camera) - which is where i'd see a "reactnative / vuenative" approach better suited..


---

I'm sorry if this will sound harsh, but i have very little patience (or understanding) for people who create something new from scratch "just because", instead of contributing to an existing project which covers almos the same, helping improve that instead, which would be a form of "giving back" to both the community, as well as assisting the maintainers/developers of the original tools.
If everyone would think this way, freqtrade would not exist.

---

You are obviously free to publish any app you wish, however i'd want you to make it _very clear_ that this application is not an official application, and that it's not affiliated with freqtrade directly.

I'd also appreciate if you'd not call the application "freqtrade" - but something else to avoid confusions (you can use freqtrade - but not only freqtrade).

we don't have any trademarks or similar on freqtrade (other than having a medium sized github presence i guess) - but i think having an application named "freqtrade" in an appstore would suggest it's freqtrade "itself" which will then run on the phone, which is clearly not the case.

**Comment by vallemar** [comment]
> Letme ask a different question first.
> Why did you start a new application from scratch, instead considering contributing to FreqUI?

There is no mobile application, I have not found anything about this in any freqtrade roadmap and I simply decided to create a project as the web application leaves a lot to be desired when accessed with a mobile device (this is not an offense to freqtradeui , was my thought at the time of creating the app). I think I could have asked on github or discord to contribute in freqUI but my application started as a simple personal app and little by little I have decided to add functionality to what it is today. For this reason, I did not initiate a contribution, simply because my initial intention was something very simple.

> your application seems like it is actually just a javascript application, not a native android/ios application.

The application I develop is not a web application. Although it is based on vue, it is a native application developed under the NativeScript framework that is similar to react native.

> It's even based on Vue, which is the same framework FreqUI uses, but a quick glance (at least based on the readme) makes me think it has fewer features than freqUI.

Yes, it has fewer functions today but over time this may change.

> As such, i'd instead encourage you to contribute to freqUI, helping improve that (especially the mobile part), as you seem to have quite some skills there.

I reiterated that I have not found anything for this purpose in freqtrade, if I am wrong I invite you to tell me where it is. If it had found something, it would not have created the application.

> i don't really see a benefit of a "real" app for this (not for your project, not for freqUI) - as it's really just a webpage, with little to no direct interactions with device capabilities (like a camera) - which is where i'd see a "reactnative / vuenative" approach better suited..

Well, this is debatable depending on the approach of each person. I personally believe that a native application will always perform better. Many factors influence here, such as the cost of development among others.

> I'm sorry if this will sound harsh, but i have very little patience (or understanding) for people who create something new from scratch "just because"...

I don't think this is fair, if everything were so perfect freqtrade won't exist since there will also be another project like freqtrade before starting this one and if it was the first I really congratulate you on this.
In addition, opening my project has been in a way a way of contributing to freqtrade, maybe not in the way you would like, but that was my intention. You may have to be more patient in these cases and speak calmly, which is why I have opened this issue.

> Obviamente, puede publicar cualquier aplicación que dese...

That is why I have opened this issue, to know the point of view of this community. And it seems fine to me, I will not publish the application under the name of freqtrade.

Still, if you are interested I could move my repo under freqtrade. I reiterate that my intention is to support this community, not to create my own. My way may not have been the best but this is how it happened, we cannot always be right in every step we take.

Sorry for this long answer, I wanted to answer each point 😂

**Comment by xmatthias** [comment]
> Although it is based on vue, it is a native application developed under the NativeScript framework that is similar to react native.

So it's not possible to share (most) of the frontend code for a nativescript application? In my (limited) understanding, it should be only infrastructure code / configuration that's necessary to convert a vue app to an application - but as I've never used that (and never looked at it) i could obviously be wrong.

This was my believe, anyway (and still is) - and if that's not possible, then i think nativescript / react-native have failed in framework design - as it'll require users to rewrite the same components / frontend code again and again, once for web / a mobile view of a webpage, and once for a "compilable" application - which i struggle to believe is true(obviously assuming both should look / function similarly).

> I reiterated that I have not found anything for this purpose in freqtrade, if I am wrong I invite you to tell me where it is. If it had found something, it would not have created the application.

We do have plans (and open issue) to make the webpage mobile-friendly - which the dashboard is (for the most part) now - and the "trade" view is not yet.
It's obviously not the same as a "native" application - but as you said elsewhere - it's debatable if a "real" application is necessary or not - and i've seen quite little difference in usability when using a PWA (with link on the homepage) over a real application - other than that the real application almost always takes longer to start (now that's obviously not a must - but an observation), as the browser is usually already running in the background.


A native application not on any roadmap for sure - but (assuming the above conversion) is possible easily, i'd be more than happy to have that (even though i don't think i'll create that myself, at least not in the foreseeable future that won't prevent others from contributing that).

i simply think that having one combined codebase will make maintenance easier.
Think about a new feature / functionality, which we'd now have to implement twice in frontend, once for the app, and once for the UI, which will be twice as much work, potentially with one being left behind.

> You may have to be more patient in these cases and speak calmly, which is why I have opened this issue.

I've been working on freqtrade for ~4 years now - and i've seen about 5 attempts on developing an application (or webpage, simply because vue wasn't convenient as a framework - in one case), which where at around the stage/functionality your's seems to be now (+- a few, depends on which one).

I don't know of a single one that's still maintained (maybe there is, but it's unknown to me) - so honestly, what i see is everyone trying to start something from scratch, potentially asking for help (don't mind that, eventually ...) - but as it's always "started an alternative from scratch" - it's difficult to gain support / other help - which leads to the project being unmaintained after a quite short amount of time, either because interest in the original author moves on, or for other reasons.
Now that's not a bad thing - but the way i think about it:

Would these people have invested the time they invested in these 5 attempts into collaborating on what exists - that would mean we'd have WAY more features in freqUI than we currently do, as it's usually good developers (a novice will "probably" not try to write something from scratch - unless it's for learning/practice).

You can see that as impatience - i see it as "wasted time" for the most part (at least from a project perspective) - as it's now 5 solutions that are at around the same level - but not quite usable as they are no longer maintained.

Now everyone tries to convince me that their project is different, will be maintained going forward - i'm yet to see that.

> Still, if you are interested I could move my repo under freqtrade.

Considering this seems to be a quite new app, i think i'd want to have it gain a bit more maturity first.
While moving it to freqtrade would give it an "official" feel, it also has downsides.
Assuming your interests change over time (speak, it'll become unmaintained), it'd move maintenance of that app to freqtrade team-members ... which would then mean we'd have to maintain similar frontend code twice (see above) - which i'm not sure we'd want to do at this point.

Maybe publish your app, we'll see how it goes, and we'll then talk again about this? (maybe on discord - where i find discussions like this easier).

> I will not publish the application under the name of freqtrade.

You might still want to include freqtrade in the name (and/or description) - so maybe the repo name ("freqtrade app") could work for that already? or something innovative like "freqApp" or similar (naming is hard, don't listen to me).

> Sorry for this long answer

Mine wasn't much shorter :laughing:

**Comment by xmatthias** [comment]
Eventually let us know the app store url's of the application once it's published. 

Also please don't see the above as rejection - while we are not moving that repository to the freqtrade org at the moment (i don't know you - might as well be a "dump it onto the core team and move on") - it's not a definitive no, just a "for now" approach.

**Comment by ketank1000** [comment]
@xmatthias 
I found this @vallemar already published this : https://play.google.com/store/apps/details?id=com.vallemar.freqtrade
I liked the design and lite version.

You can actually consider rebuilding app using flutter what do you say ?

**Comment by xmatthias** [comment]
> You can actually consider rebuilding app using flutter what do you say ?

no, for sure not.

We have freqUI - and we will develop the mobile mode for it further (the current mobile view is already okish - at least for the trade view).
A native app will provide no benefit, but only increased effort.

**Comment by ketank1000** [comment]
Just for curiosity, When can we expect the mobile mode ?

**Comment by xmatthias** [comment]
the mobile mode is in the current release - and will show up once you have smaller screensizes.

It's not applied 100% throughout the app at the moment - but the main view (trade screen) is now done differently for small devices.
