### ISSUE TITLE
Not compatible with python 3.10?

### ISSUE THREAD

**Issue by taymourheikal** [freqtrade/freqtrade#6041]
Trying to install freqtrade on my Macbook but get the following error:

```
./setup.sh --install
No usable python found. Please make sure to have python3.7 or newer installed
```

For reference:
```
pip3 -V
pip 20.2.2 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by xmatthias** [comment]
Freqtrade itself (excluding dependencies) should be compatible (i don't know anything that would be incompatible).

**However:**
the installation script does not support python 3.10 yet, and for now, we'll also not be adding support for it due to problems with dependencies.

This is because freqtrade depends on some libraries with C dependencies, which did not release support for python 3.10 yet, and therefore cannot be installed directly.

In theory, it should be possible to manually install all dependencies to run freqtrade, but i would advise against this, as you'll need to build several dependencies from source - which includes installing eventual binary modules, and in one case (pytables), installing the git master branch instead of the pypi version.

So while possible, it'll be a huge time hog - and you'd probably be the first to run freqtrade on python 3.10.


We'll be adding support for 3.10 once all dependencies have added support and we're able to run CI (you can track progress of this in #5677).
