### ISSUE TITLE
./setup.sh -u failed with [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/test-easy-install-80550.write-test'

### ISSUE THREAD

**Issue by terxw** [freqtrade/freqtrade#6044]
## Have you searched for similar issues before posting it?
yes

## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: Python 2.7.18/Python 3.8.10
  * CCXT version: ccxt==1.63.1
  * Freqtrade Version: freqtrade develop-e9c3f0cbb
  
## Describe the problem:
after running update I run into error: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/test-easy-install-80550.write-test'
### Steps to reproduce:

  1. cd ~/freqtrade; ./setup.sh -u or 
  cd ~/freqtrade; source .env/bin/activate; python 3 -m pip install -U -r requirements.txt
  
### Observed Results:
after installing all dependencies, installing newest freqtrade (as of 20211211) failed

### Relevant code exceptions or logs

 ```
  Successfully uninstalled freqtrade-develop-e9c3f0cbb
  Running setup.py develop for freqtrade
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kangus/freqtrade/setup.py'"'"'; __file__='"'"'/home/kangus/freqtrade/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/kangus/freqtrade/
    Complete output (28 lines):
    running develop
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/test-easy-install-80550.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/lib/python3.8/site-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    ----------------------------------------
  Rolling back uninstall of freqtrade
  Moving to /home/kangus/.local/bin/freqtrade
   from /tmp/pip-uninstall-btllrn1k/freqtrade
  Moving to /home/kangus/.local/lib/python3.8/site-packages/freqtrade.egg-link
   from /tmp/pip-uninstall-did3np6v/freqtrade.egg-link
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kangus/freqtrade/setup.py'"'"'; __file__='"'"'/home/kangus/freqtrade/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.

  ```

## What could be the problem

It seems to me that what should be local user installation tries to install freqtrade system wide

**Comment by xmatthias** [comment]
both above commands will install all code within a virtual environment (in .env) - assuming nothing fails in between. Nothing should go in neither system python, nor user level python directories - but all will stay within the virtual environment.

your second command has a typo (i hope it's a typo and hasn't been run as such, as i'm not sure on the impact of this) - and should be `cd ~/freqtrade; source .env/bin/activate; python3 -m pip install -U -r requirements.txt` (no space between python and 3).

Best run these commands manually one by one.
i'd assume that the "source" step fails - and as a consequence, the subsequent command is executed with the system level python, instead of the virtual environment python.

**Comment by terxw** [comment]
Yes its typo.

According to this:

https://github.com/pypa/pip/issues/7953

the problem is in setup.py


if i modify it e.g. I put these lines to the begining:
```
import site
site.ENABLE_USER_SITE = True
```
and run:

```
~/freqtrade/setup.sh -u
```

it works!

**Comment by xmatthias** [comment]
Let me repeat what i said above - installing freqtrade in your user site is wrong - and not a supported way to install freqtrade.
This makes your modification wrong in my eyes - and a project like freqtrade should never modify the system wide python settings to enable user_site - even if random people in an issue recommend this.


All our documentations either use docker - or install freqtrade in a virtual environment.
Since your system tries to install it in system python, this means your virtual environment is not working correctly.
You should be able to check this with the following:

``` bash
cd ~/freqtrade; 
source .env/bin/activate; 
which python
which python3
```

The last 2 commands should point to `.env/bin/python` (or python3). If they don't, then your environment did not load correctly - which probably suggests that either python itself is not correctly installed, or the `venv` module is not correctly installed.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
