### ISSUE TITLE
dataframe 1 time per pairs

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#6074]
## Describe your environment

  * Operating system:  ubuntu 20.04
  * Python Version: _____ (`3.9`)
  * CCXT version: _____ (`1.63.1`)
  * Freqtrade Version: ____ (last develop)

Hello;
IM developing my own strategy, I want to check the trend of bitcoin. This part is done, the problem is that when putting the function inside informative_pairs, for each pair it checks the trend and I would like it to only do it once each complete pairs step.

the flow would be:
- I check BTC / USDT or save if there is a trend.

Each pair will populate indicators and add the saved trend of BTC / USDT without testing it again.

we reached the bottom of the pair list and started again by checking the BTC / USDT.

thank you.

**Comment by xmatthias** [comment]
Depending on what comes out of your "btc" calculation, i guess you could store your results as [documented](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information) - which you probably shouldn't use for a dataframe though.

the detection, if you're in the first, middle, or last pair of the pairlist is left up to you - as from a strategy perspective, i think pairs should be treated independently (it should not matter if a pair is first or last in a pairlist - it should always generate the same signals - otherwise you could never rely on it to do any plotting or post-mortem analysis.
because of this - there is no easy / builtin way to determine which pair you're at within a pairlist (you obviously get the pair name).

**Comment by anakein** [comment]
ok, but, can you give  me one idea for implemented?, i try save dataframe outside function, but don´t work.
