### ISSUE TITLE
About populating indicators several times in backtesting mode, like in live mode

### ISSUE THREAD

**Issue by neimad1985** [freqtrade/freqtrade#6083]
Hello,

I would like to know if there is any way to make the backtesting mode act like the trade/live mode regarding indicators calculation.

I know that with backtesting mode the indicators are calculated once for the entire timerange to improve performance.
Is it possible to make backtesting calculate indicators for each new candle ? Even if it sounds like a bad idea because performance will be degraded a lot.
If not, do you think it is possible for me to modify the code quite easily to achieve that ? Any hint would be welcome.

Thank you.

**Comment by xmatthias** [comment]
a very simplistic form of this would be to simply slice the dataframe into a sliding window of 500 (so you have 0-500, 1-501, ...) - calculate indicators against that (as well as buy/sell signas) - and then only use the very last row of this for the "final" dataframe.
That's how live mode "really" does it - which will obviously mean you calculate all indicators "candle_count - 500" times.
Nothing hinders you from doing that within your strategy - other than patience (depending on the timeframe, this can take a VERY long time).

While i do have a (somewhat working) version of this - it has some caveats - and if it "really" does what you expect depends on the circumstances (informative pairs may still allow you to look into the future, ...).
it'll also only take care of "populate_indicators" - not on "populate-buy_trend" - but that would just be a small step.

Because of this (and because it's not "really" integrated so far) - it's not something that's available at this moment. to do this in a comprehensive manner (so users can't circumvent it unintentionally) is however no small task.

**Comment by neimad1985** [comment]
Thanks for your quick answer, as usual.
I will go for the "inside the strategy" way, modifying the bot seems risky to me. It is indeed smart to cut the dataframe into pieces, calculate everything I need and then step to the next turn of the loop with the next piece of dataframe.
Thank you, I close the question.
