### ISSUE TITLE
Freqtrade Sell Sign - Get Price Buy - open rate

### ISSUE THREAD

**Issue by ASilvaBR** [freqtrade/freqtrade#6111]
I am trying to create a sales order using the Freqtrade bot when:

The current price hits the entry price + ATR. I don't know how I can retrieve the entry price (The price I made the purchase). this is my code:

   _def populate_sell_trend(self, dataframe: DataFrame, metadata: dict)
-> DataFrame:
        dataframe.loc[
            (
                ( dataframe['high']>= dataframe['atr'].shift(1) +  ??open_rate??   )
            ) ,
            'sell'] = 1
        return dataframe

what do I put in place of open_rate?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

In `populate_sell_trend`, the entry price is not available reliably (not during backtesting).
While it's possible to retrieve it via the Trade object - that's not possible during backtesting due to the [backtesting execution logic](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic).

You should instead look at [strategy callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) to archive this - which will contain the trade object (which also contains the price).
