### ISSUE TITLE
markets refresh interval

### ISSUE THREAD

**Issue by Nassiotrader** [freqtrade/freqtrade#6129]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.9
  * CCXT version: 1.52.40
  * Freqtrade Version:2021.11
  
## Your question

Hello , Im new and I searched a lot so I could not find the right answer , I have a bot running and it happened to me that when market reached to my trailing_stop_positive_offset and its rejected my bot could not understand it to active it , may I now how long is market refresh time and how i can change it to few seconds ?
thank you

**Comment by xmatthias** [comment]
if your trailing stoploss is rejected - this usually means that your stoploss is too tight (which results in the current price being below the price).

This usually happens with unrealistic values (0.1% or similar) - where crypto pairs simply move by more in one single tick (or even spread is more - depending on your pricing strategy).

This has nothing to do with "market refresh time" - but is simple logic from an exchange perspective.

**Comment by Nassiotrader** [comment]
Dear xmatthias 
Thank you for respond, I think I could not explain my problem , here is an example of my problem :
<img width="470" alt="Screenshot 2021-12-29 at 09 22 04" src="https://user-images.githubusercontent.com/77458946/147641810-1aace71f-f2c6-4cb0-bc37-c5a5b6b28ca9.png">
as you can see in the picture I bought a coin and it growth for 4.87% and my trailing_stop_positive_offset was 3% only but it did not active it so price fall down ! is it because of market price refresh time or there can be another problem ?

**Comment by xmatthias** [comment]
the screenshot leaves more questions than answers.
What's the pair and timeframe (and exchange) for this?

Such long highs/tails can often happen within 1 second or less (so it's up during one trade - and right back down) - which freqtrade will have very little chance to capture correctly - and if it does, placing a stoploss order would either fail (stoploss-on-exchange) - or result in a timeout (regular limit order), as price already dropped below your stop - potentially to never reach this level again - at least not within the next few candles.

If you ignore that high as "single trade wick" (which i'll do due to lack of proper details) - your gain was never really more than 3%. It would obviously be great to be able to trade such wicks - but in my experience, it's near impossible even if you watch them live.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
