### ISSUE TITLE
Retrieve information about candles which are still open

### ISSUE THREAD

**Issue by Litom** [freqtrade/freqtrade#6135]
## Describe your environment

  * Operating system: Debian GNU/Linux 11 (bullseye)
  * Python Version: 3.8.8 (`python -V`)
  * CCXT version: ccxt==1.61.92 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Your question

From what I see, it is not possible to get the latest candle which is still open inside a strategy. The OHLCV dataframe which keeps track of all historical candle data (and also indicator values, buy, sell signal as additional columns) doesn't seem to have the most recent candle in the last row but rather the previous candle which is already closed.
I tested this out with ```dataframe.iloc[[-1]]``` and when retrieving e.g. the daily candles on 29.12.2021 the last line would be the already closed daily candle of 28.12.2021. Same with other timeframes.

Why does the candle not get stored inside this dataframe? Normally, I would have assumed that the last row would be the candle which is still open with already fixed OHL (open, high, low) values and a changing C (close price) and increasing V (volume) value after another request is made to the exchange. Does the most recent candle get stored somewhere else?

This has implications for indicator signals where triggers are desired even if the candle is not yet closed.

The issue is similar to this one: https://github.com/freqtrade/freqtrade/issues/1874
Although its possible to fetch the ticker without needing the orderbook workaround
```python 
data = self.dp.ticker()
``` 

**My current workaround thought to this would be something like:**
Step1: Copy existing OHLCV dataframe to dataframe2
Step2: Fetch ticker information and build a new row
```python 
data = self.dp.ticker()
opencandle = [(data[timestamp], data[open], data[high], data[low], data[close], data[volume])]
```
and then append this row to the copied dataframe, populate the indicator using this new dataframe and then delete the dataframe when the buy/sell logic has been executed as it gets recreated inside the next loop run.

Is there a better/easier way to get this value and properly populate inidactors across the entire chart and a reason why it is not included in the data frame?

**Comment by xmatthias** [comment]
>  would have assumed that the last row would be the candle which is still open with already fixed OHL (open, high, low) values and a changing C (close price) and increasing V (volume) value

this statement is plain wrong. The only value that's fixed until a candle is closed is the open. Both high and low can change throughout the candle until the next candle is opened.

---

Using unfinished candles will result in unstable indicators/signals - an effect called backpainting (something quite many tradingview strategies suffer from ...).

Most indicators (if not all) use the close value for their calculations (unless explicitly defined otherwise).
This means, using unfinished candles would result in a signal being there for the first half of the candle (Freqtrade would buy) - but in the 2nd half of the candle, this signal would disappear.

This creates a unreliable strategy with "ghost buys" - where you look at a chart, see a buy (but no buy singal) - and have no way to recreate why freqtrade would've bought.
This also means that you've got no way to backtest such a strategy.

For that reason, having unfinished candles is something freqtrade does not support - and will not support anytime soon.

---

A small warning for your way: 
Your way might also not work reliably - as on many exchanges, the return value of the `ticker` endpoint does not guarantee up to the second information.
