### ISSUE TITLE
Prioritizing trades

### ISSUE THREAD

**Issue by neimad1985** [freqtrade/freqtrade#6175]
Hello,

I have a question regarding prioritization of trades.
Say I'm working with 100 pairs and max-open-trades=5.
At some point I may have 5 active trades and some other buy signal coming from one of the 95 ramaining pairs.
The buy will be rejected because max-open-trade has been reached.
Now suppose I have some sort of scoring mecanism to say how worthy could potentially be a trade, some score which would say how much a buy signal is good.
Is there anyway/hack/workaround/feature to allow selling the least interesting actual position (based on its score or anything else) and go for another position which has a better score ?

The goal here is to trade as much as possible on the best opportunities so at some point I'd like to be able to leave a not-so-worthy position to enter a potentially better one.

The problem to me here is that the pairs do not communicate with each other to work together as a whole instead of competing against each other.

Thank you.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

> The problem to me here is that the pairs do not communicate with each other to work together as a whole instead of competing against each other.

That's something you have in your own hands with the strategy - you can make pairs comunicate with each other - or not - but it's the strategy that's taking decisions here, not freqtrade itself.

For the above case, you could for example combine something like `self.dp.get_analyzed_dataframe('someohterpairwithopentrade', self.timeframe)` in the `custom_sell` callback - and decide if you'd like to delete it or not.

You could store some "victim required" (and "this_is_the_next_victim") information via [information storage](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information) (can be just a flag, or info per pair ... up to you) - and use that in [custom_sell](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-sell-signal) to decide if you
* need to sell any trade
* sell this particular trade

It's more a problem of imagination / being aware of all parts of the documentation than freqtrade limiting anything.

i don't see Freqtrade  implement a "victimize" method  - which will make one trade the victim in favor of all a new trade, simply because there is no need for it.
Such things will always remain at the hands of the strategy.

**Comment by neimad1985** [comment]
First, apologies for not filling the issue template, won't happen again.
Second, thanks for answering anyway.

Third, I didn't actually think of using ```self.dp.get_analyzed_dataframe()``` not because I didn't read the doc but only because I don't use it that often so it didn't come to my mind, so thanks for reminding that.

That's nice that this is only a matter of imagination and not freqtrade disallowing it. So I guess I just have to read again the documentation and have a deeper think while doing so. I could for example use ```Trade.get_trades()``` to know about current trades and make decisions.

Thanks for your time.

**Comment by neimad1985** [comment]
Reopening this. First, repairing my mistake.

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.10
  * CCXT version: 1.59.2
  * Freqtrade Version: 2021.10

I am trying to access the trades with the function ```Trade.get_trades()``` but as I expected by reading [the documentation](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades), trades can only be fetched in dry/live mode, not backtesting.
If I try anyway I get an error:
```NotImplementedError: `Trade.get_trades()` not supported in backtesting mode```


When looking at the [backtesting code](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L537) I see that the ```trades``` object is a local object so there's is no chance that I can access it except by modifying the freqtrade code.

Am I right ? Is there any clean way to access the trades in backtesting mode ?

Thank you.

**Comment by neimad1985** [comment]
Ok, I didn't read the code correctly in the first place. I am now accessing the trades in backtesting mode with:

```
from freqtrade.persistence import LocalTrade
trades = LocalTrade.get_open_trades()
```

Can you confirm this is the good way please ?

**Comment by xmatthias** [comment]
no. You should not use LocalTrade at all - as it will not work correctly (and is not part of the interface, so can be changed/removed at any time).

you can however use `Trade.get_open_trades()` - which will basically do the same thing.

Please keep in mind that during backtesting, you cannot use any of the `Trade` functions as part of `populate_*` methods - only as part of callbacks.

**Comment by neimad1985** [comment]
Ok thank you for correcting the way to retrieve the trades.
Concerning when to use ```Trade``` functions, that's understood. I want to use this in ```confirm_trade_entry()``` so that's fine, it's one of the callbacks.
Thanks, I'm closing this.
