### ISSUE TITLE
It's possible to download all indicators? Since Open Time to Ignore in Binance?

### ISSUE THREAD

**Issue by luizpaulonievola** [freqtrade/freqtrade#6212]
* Operating system: Gentoo 
  * Python Version: 3.9 
  * CCXT version: 1.66.20 (
  * Freqtrade Version: 2021.12 
 
## Question

['Open Time', 'Open', 'High', 'Low','Close','Volume','Close Time',
    'Quote asset volume','Number of trades','Taker buy base asset volume',
    'Taker buy quote asset volume','Ignore']

"freqtrade download-data --exchange binance --pairs .*/USDT --days 1000 --timeframes 1m 3m 5m 15m 30m 1h 2h 4h 8h --data-format-ohlcv jsongz"

ohlcv to -> all

**Comment by xmatthias** [comment]
it's honestly unclear to me what your actual question is.

OHLCV data is what it says - Open High Low Close Volume - and `download-data` will download exactly that.
While the binance endpoint may be providing more data - it's not standard across all exchanges.
Because of this, ccxt is not providing this additional data in unified fields - and freqtrade will also neither download, nor store, nor load this data.
