### ISSUE TITLE
No trades since 2022

### ISSUE THREAD

**Issue by symbioticogt** [freqtrade/freqtrade#6214]
My bot was working flawlessly with Binance. Since Jan. 1 2022 it stopped making trades. I have not made any changes at all. Any ideas of a configuration change or Binance limiting something? The logs show no issues.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

There are no changes I'm aware of which would simply "no longer work since 2022" ... 
If there's breaking changes in the api, the logs would tell you.

Obviously, markets do change over time - so it might as well be your strategy that's currently "cautious" about entering new trades for whatever reason (or maybe it somehow includes the year / date part as part of some conditions) - basically the strategy is no longer generating buy signals.
I'd recommend to backtest the same strategy for the period in question (this year) with the pairs in your pairlist, to have some reference about how you'd expect the strategy to behave.

Obviously it can also have other causes which are not related to the year (for example your last lost trade pushed minimum stakes to below the tradable limits) - but that should show as rejected buys in your logs.

**Comment by symbioticogt** [comment]
Thank you for the reply and sorry for not following the template, my bad. Yes indeed the strategy was only generating sell signals. I have tested other strategies that generates a few buy signals but probably not enough to enter a trade. I'm very new, testing and learning a lot. Thanks once again.
