### ISSUE TITLE
How rest api CLI work?..

### ISSUE THREAD

**Issue by sethemis** [freqtrade/freqtrade#6220]

**Comment by xmatthias** [comment]
You can either use the cli script we provide (`scripts/rest_client.py`) - or alternatively start freqtrade and refer to the provided [open api specification / interface](https://www.freqtrade.io/en/stable/rest-api/#openapi-interface) on how to access the different endpoints.

**Comment by sethemis** [comment]
Hi thanks!, but in open [api specification](https://www.freqtrade.io/en/stable/rest-api/#openapi-interface) i dont see how it work
![CLI](https://user-images.githubusercontent.com/70799038/149324995-bf08602d-4e8c-473f-afba-17f2f3513c7b.jpg)

**Comment by xmatthias** [comment]
Freqtrade API uses standard Rest API patterns.
If you are unfamiliar with how rest api's work, i'd suggest to start learning that first.

Please keep in mind that this is an open source project, run by volunteers.
As such, we will not spend our time explaining things that can easily be found on the internet, and where the issue here is a simple lack of "will to search for an answer".
