### ISSUE TITLE
Add new data for existing pair without overwriting existing?

### ISSUE THREAD

**Issue by holycacao** [freqtrade/freqtrade#6222]
## Describe your environment

  * Operating system: docker
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.12
  
## Your question
TL;DR Why can't 2 non-overlapping trade data sets of the same pair exist in a single data directory?

I'm trying to download data from different, non-overlapping timeranges for the same pair (eg 20210901-20211001 and 20211101-20211201). I'd like to separately backtest these timeranges as they represent different market sentiments (eg bearish, bullish, etc). However, it seems that the download-data command doesn't allow for this?

If the date of the earliest existing trade data is _after_ the start of the newly requested trade data, it will completely overwrite the existing.

If the date of the earliest existing trade data is _before_ the start of the newly requested trade data, it enforces the trade data to be contiguous and uses the latest trade date (minus 5s) instead of the newly requested trade start date. This sort of accomplishes what I'm looking for, but means it downloads *a ton* more data than necessary. It also means I _must_ download data in chronological order or the above overwrite will happen.

It looks like I can just write these data sets out to 2 separate data folders, but that requires seemingly unnecessary management of the data sets.

**Comment by xmatthias** [comment]
Why would you store the data twice / separate? 
that's very inefficient for both the exchange (you'd potentially download overlapping data multiple times) as well as for the disk (you'd potentially download data 

You can simply download all data you need (from the earliest point in time) and then limit the datasets on use (backtesting, hyperopt, ... with the `--timerange` argument).

`download-data` is designed to download a huge junk (long history) once - and then download incremental sets of data up to the current point in time (ideally ran every few days/weeks).


What you're trying to do seems like a good idea at first, but is really pointless.
the moment you are content with the strategy result, you'll usually want to run against a longer timerange - in which case you'd need to use the full data (which is now not available, because you got it in 2 different ranges, in your case with a month missing in between) - which would lead to redownloading the whole data again.

you'll also have forgotten that you're missing October data 2 months from now - and then be surprised because results are not what you expect (backtesting now from `20210901-20211201`), therefore downloading data with "Missing" segments is not a function we support, or aim to support.

**Comment by holycacao** [comment]
> Why would you store the data twice / separate?
that's very inefficient for both the exchange (you'd potentially download overlapping data multiple times) as well as for the disk (you'd potentially download data

I would argue the current design is actually more inefficient than what I'm requesting. I'm requesting the ability to download _only_ what one needs. The current implementation forces one to download gobs more data than needed **and** -- if not used in the precise and rigid way it was intended to (ie download 1 large chunk of data) -- will **delete** and **redownload** previously downloaded data.

> the moment you are content with the strategy result, you'll usually want to run against a longer timerange - in which case you'd need to use the full data (which is now not available, because you got it in 2 different ranges, in your case with a month missing in between) - which would lead to redownloading the whole data again.

Not redownloading, but rather downloading _for the first time_ the missing segment of data.

Backtesting/hyperopt already warns if there is missing data - that is sufficient for the user's awareness. There's no need to hand-hold more than that. If a user wants to shoot themselves in the foot, so be it. :)

On an efficiency-related note, it should be possible to piecemeal download older trade data sets as long as they overlap with the existing data (this is already allowed for newer overlapping blocks). Ie if data exists from 2021-10-01 to 2021-11-01 and new data is requested from 2021-09-01 to 2021-10-01, it would be more efficient to only download the missing data (this still would adhere to your requirement that data is contiguous). To support this, the code that determines the `since` and `until` values (in `_download_trades_history` in `history_utils.py`) could be updated to:
```python
        if trades and since < trades[0][0]:
            if until is not None and trades[0][0] <= until <= trades[-1][0]:
                until = trades[0][0] + (5 * 1000)
            else:
                # if since is before start of existing data and until is after end, this could be more efficient if 2
                # get_historic_trades calls were supported - one to pull the data older than existing and one to
                # pull the newer than existing
                logger.info(f"Start earlier than available data. Redownloading trades for {pair}...")
                trades = []
```
Untested  code, but I think you get the drift? This could significantly reduce the amount of data downloaded.

**Comment by xmatthias** [comment]
> Backtesting/hyperopt already warns if there is missing data - that is sufficient for the user's awareness. There's no need to hand-hold more than that. If a user wants to shoot themselves in the foot, so be it. :)

there is a difference between warning if data at the beginning / end is missing, or if we need to analyze if (and how much) segments of data in the middle are missing.

---


download-data currently does not respect the end-date of a provided `--timerange`  - but will always download up to the current day. I don't see this as problem though - as you'll always want to backtest with "latest" data at the end (markets change over time, not just between different market cycles).

I'm not saying enhancements are not possible (like prepending data) - but data should remain continuous nonetheless, as detecting missing segments of data in the middle (and more importantly, fixing that) is not as simple as it sounds, especially as you'll also need to consider "intentionally" missing data like exchange downtimes (during which no new candles are expected).

Feel free to submit a PR (please with tests) which adds support to prepend data ... but I'm clearly against "holes" in the data.

> If a user wants to shoot themselves in the foot, so be it. :)

That may be true, the problem is the unintentional problems this causes (like downloaded "holy" [data with holes] data months ago and don't remember about the holes) - which in turn will end up as either issues here, or questions in discord (both of which we would like to avoid by making things as simple as possible for users).
