### ISSUE TITLE
Option to Delete all closed trades

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6229]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

After withdrawal, the profit percentage will be increased or decreased depending upon the profit.
Deleting the db file is not suitable as most of the time, there will be atleast one open trade.
So deleting all closed trades will kinda reset the db

**Comment by xmatthias** [comment]
This would wipe all history of the performance of the bot - and is therefore a quite dangerous "feature".
Even if you withdraw some of the profits - that won't mean the bot didn't make these profits - so it's usually desired to keep these profits visible.

This is therefore not something we'll be considering to add to freqtrade.

You can refer to the [sql cheatsheet](https://www.freqtrade.io/en/stable/sql_cheatsheet/) - and modify some of the commands there to delete whatever you desire from your database (delete from the Orders table first).

**Comment by sabatale** [comment]
@xmatthias Sorry if I'm hijacking the topic but is there an option to reset the performance?

I've deleted trades, deleted the bot and recreated a new one. But the performance still shows the trades returns that happened while I was doing my testing. Would executing a DELETE at the db level reset the performance? (I doubt it since I'm guessing clicking the delete button next to the order is supposed to that in the first place?)

**Comment by xmatthias** [comment]
@sabatale usually, simply deleting the database file is the way to go.

please make sure that the bot is not running while deleting the file, otherwise data may "leak" over and may get rewritten to the file again.
