### ISSUE TITLE
Short With FreqTrade

### ISSUE THREAD

**Issue by MauricioHorn** [freqtrade/freqtrade#6284]
1 Year ago someone make this question: " Is it possible to short with freqtrade. Instead of just profiting from buying and selling? If so could you please direct me on how this can be done"

I would like to know if this is already available or not, and if not, it will be updated soon? Thanks!

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Instead of asking the same exact question in 3 (!) different places - you could've simply referred to the [FAQ entry](https://www.freqtrade.io/en/stable/faq/#can-i-open-short-positions), or used the search To find open issues about this.

We're also not providing any timelines or ETA's, as all work here is done voluntarily, with people donating their free time - which is often also wasted in answering questions like this instead of working on actual features.
