### ISSUE TITLE
Backtest custom_exit_price limited to previous candle

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#6304]
Hi, thanks for an amazing project!

In the docs for custom_exit_price, it says:

`While Custom prices are supported in backtesting (starting with 2021.12), prices will be moved to within the candle's high/low prices. This behavior is currently being tested, and might be changed at a later point. custom_exit_price() is only called for sells of type Sell_signal and Custom sell. All other sell-types will use regular backtesting prices.
`

Can I ask what the thinking behind this is?

I'm trying to use the custom_sell and custom_exit_price to create a sort of take profit price as described here (https://github.com/freqtrade/freqtrade/issues/6269#issuecomment-1019069864).

I have a strategy where I set the price a few points above the close of the previous candle on the minute timeframe. Obviously this does not always occur in the same range as the current candle, but I am allowing for that by having a short time to close the sell and also by closing any trade regardless within a certain time period. So am not in danger of "losing it all" as per the previous post.

It seems like, with the necessary precautions, if we are specifying a price we are trying to close at that price and therefore there i no real reason for capping it to the candle. I understand the backtester can't tell whether we would necessarily be able to get that price.

I can see why this capping is is useful without these protectoins, so perhaps this would be better as a setting that can be toggled on and off?

Thanks,
Ali

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Backtesting currently assumes all orders to fill immediately.
So you can place a buy-order for 1$ - and get a insane ROI on that trade, simply because the price is actually 42k$ (or whatever it is today).

While you think it would be nice to place the order "a bit" above current price - it's a dangerous approach, as you might stay in that trade for a few more days if that price is never reached - missing other trades, so the impact of this is way higher.
The same would happen on plots, where trades would appear "outside" of the candle - which obviously cannot happen.

You're free to use any prices that are within the candle's low/high range. 
If you need a different price (higher or lower)- then delay the sell-signal until that price is within the candle (that'll then give you realistic sells - as it's actually possible for the order to fill at that price).

While we're evaluating this behavior at the moment (as it's mentioned in the docs) - this will never be an optional behavior for 2 reasons:
* you can cheat yourself
* Results become unrealistic
* results are very often shared - and it's very easy to show good results that are never actually archivable (see the 1$ BTC example from the start of this post).

While we don't really care about the first point - we still try to protect users as good as possible from missplaced hopes, and try to have backtests as realistic as possible - and having orders fill outside of a candle is not part of that.

**Comment by alisalama** [comment]
Thank you Matthias for that quick reply. That all seems sensible enough.

This seems like a sensible approach for my scenario, on the backtesting side.

> If you need a different price (higher or lower)- then delay the sell-signal until that price is within the candle (that'll then give you realistic sells - as it's actually possible for the order to fill at that price).


Thanks again!
