### ISSUE TITLE
What problem may arise when we share same db for 3 bots on same exchange and 1 bot is set to sell only?

### ISSUE THREAD

**Issue by mkavinkumar1** [freqtrade/freqtrade#6436]
## Your question
Use case:

Splitting 80 pairs into two 40 pairs for quick calculation for buying only and remaining 1 bot is set to sell only.

**Comment by stash86** [comment]
1. Why the 3rd bot? Why not letting 1st and 2nd bot handles their own trades?
2. Why not use separate db? I don’t see any reasons why not to, apart from having to use multiple frequi, but now that should have been no issue since we can add multiple bots into 1 frequi now


As for possible problem, the first one come to my mind is when both bots wants to open a trade at similar time, the one faster will get the priority and lock the database, and then when the second bot wants to access the database, it can’t gain access to the database, so it would throw exception.

**Comment by mkavinkumar1** [comment]
1.It won't miss sell signals because it will handle only open trades.
2.To share stake amounts
if exception throws, will bot stop?

**Comment by stash86** [comment]
I think you must have misunderstood something. There is no such thing as missing sell signal. If you think the bot should sell when it didn’t, check your code/frequi. You might have buy signal on the same candle, or you have some confirm_trade_exit.

And it also would introduce new problem, when your bots would buy when it shouldn’t, because a sell signal supposed to be active, and also the 3rd bot would sell when it shouldn’t because a buy signal supposed to be active

**Comment by mkavinkumar1** [comment]
I meant sell signals from custom sell

**Comment by xmatthias** [comment]
Each database must be dedicated to one bot.
Using shared databases is not supported, and can cause several issues (some known, some unknown).
There is no "sell only" mode - all bots will attempt to handle all open trades (also automatically adding them to their respective pairlist.

Please read the [running multiple bots](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade) documentation for more information.
