### ISSUE TITLE
Minimum resources for multiple bots

### ISSUE THREAD

**Issue by TEuler27** [freqtrade/freqtrade#6449]
I'm looking to deploy on an ec2 instance multiple freqtrade bots running on docker containers. I've seen the minimum hardware requirements on the docs but I'm wondering how do you think they would scale increasing the number of bots. Moreover i would like to know if my understanding of the minimum requirements are correct. I guess RAM would increase depending on how many indicators my strategies need while cpu would increase to ensure that every time the internal process of the bots runs i have enough performance to deal with calculations for the indicators, connection with the broker, ecc.

Let me know if i understood the needing of the bots correctly and for example if i wanted to run n bots how much vcpu and ram (approximately) i should have available

**Comment by xmatthias** [comment]
It's quite difficult to give you appropriate sizings - as it will solely depend on the strategy.
If you got a optimized strategy only using ta-lib indicators, it's probably fast

if it's slow indicators - it'll get worse.

That said, i usually recommend to scale horizontally after 2-3 bots. otherwise you'll run into rate-limit issues (which are usually by source-ip) - and with 4-5 bots firing at the exchange (usually at the same time - when a new candle drops) - you can run into "ddos limitation" errors quite quickly.

**Comment by TEuler27** [comment]
That's a good point that i didn't think of. I'll need to rethink my project structure then. Thanks for the advice!

**Comment by TEuler27** [comment]
Sorry if I come back to this issue. I looked into the rate limit problem and i don't understand where the issue would lie. For example ftx doesn't have rate limits on data requests so even if i have ~10 bots that require at the same time the new candle i should not be restricted or banned. Differently if all of my bots want to place an order at the same time then i could fall on a limitation since they have hard and soft limits on the orders number. I checked binance as another example and they allow 1200 (weighted) request per minute and they should be enough to get data (but again maybe not to place orders). So, just to make it clear, the rate limit problem would probably occur when multiple bots try to place orders at the same time, am i right? Or did I misunderstand the way the bots or the rate limit work?

**Comment by xmatthias** [comment]
order placement is one point - but fetching data is another.

Just give it a try - you'll see that after ~5 dry-run bots on binance, you'll start to get ratelimit errors (depends a bit on the timeframe and number of pairs) (But dry-run does not place any orders  or query any orders while in trades - and is therefore a magnitude lighter on ratelimits).
As such, 2-3 live bots should be safe - but when there's money on the line, you'll not want to risk a stoploss due to a ratelimit timeout.

200 weighted requests (the weight is the problem here) you don't get too far - fetching candles (ohlcv) is pretty expensive, so is fetching orders / placing orders.

FTX might be different (all exchanges are different) - I'm basing my estimation on binance since from experience, that's the exchange most people use.

if we start with other exchanges you'll have kraken as negative example, which will rate-limit you heavily on their public endpoints (so you'll not do much more than 1 request per second without problems) ...

**Comment by TEuler27** [comment]
Thanks, I should have enough info to work with now!
