### ISSUE TITLE
How I should understand 1970-01-01 in drawdown start and end?

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6451]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.71.73 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

Can somebody give me a quick help how I should understand the year range for Drawdown start and Drawdown end (1970-01-01)?
This mean there is no drawdown in the backtested period (actually was without drawdown)?

Thanks

![image](https://user-images.githubusercontent.com/14143598/155204049-34461db0-8564-4d42-8ae6-e64edbbae884.png)

**Comment by xmatthias** [comment]
That's correct - seems like you've had no losses - therefore no drawdown.

**Comment by rongybika** [comment]
Hi,

Thank you.

Actually I have another question but I don't think that it's necessary to open another issue because it's related to backtesting and hyperopt.
Today I checked some indicators data(like OBV) and could happen that until now I did everything in a wrong way.
If I'm not wrong we are getting the OHLC data in chucks (from Binance) of 500 units and because of this I should run backtesting and hyperopt for same length of chucks?
Like I said, today I backtested some strategy for 2021-01-01->2022-02-01 and 2022-01-01->2022-02-01 and the values of the OBV indicator was slightly different (seeing few elements on the end of the array).
Is there any description of the chucks received from different exchanges on live mode? (Binance, Kucoin)
Or can we use downloaded data together with the online received data? (let's say from database)

Looking for some solutions, I found the real mean of ohlcv_candle_limit and startup_candle_count.

Could happen that I'm in totally wrong direction.

Thank you

**Comment by xmatthias** [comment]
well there are some indicators that are not "rolling" - but will use all available data (`qtpylib.vwap` is one such example). Using `qtpylib.rolling_vwap` fixes this (but is still not the correct vwap).

That said - the same can also happen on other indicators (also from ta-lib) - the problem is, there it's difficult to discover as the C code there is ... quite complex.

If you're really suspecting this, then using batches of 500 units (or however many) would also be wrong. in reality, you'd have to use a rolling window of 500 candles (and move it by 1 candle each, calculating all indicators - and then using ONLY the last candle of this).

What's happening sometimes is that values leak (commonly in indicators where one value is based on the prior value) - so an EMA10 calculated on 100 candles would have a slightly different outcome than an EMA of 1000 candles (even if the last 100 candles are the same). The errors are "usually" very small (so pandas won't even print them by default as they're > 8th decimal place) - but it'll obviously depend on the volatility as well as on the starting values.

i've written a decorator for this once (not open source so far) - but it's dead slow, as you'll be calculating all indicators "candle count - 500" times.

**Comment by rongybika** [comment]
Thank you for answer, but unfortunately I have no idea how to start searching to implement this solution (a rolling window). Can you give some concrete points how I should start searching on google?

**Comment by xmatthias** [comment]
Don't jump to "i need to implement this" without being sure it's actually happening. 
Also, a usually much faster way is to search if this indicator is available someplace else - like in pandas_ta (which is well maintained and so far, has had every "common" indicator i've gone looking for in the "msot correct" way (see vwap)).


if you load a dataframe (real or fake) in an interactive environment (jupyter) - just try to calculate the same value on the full dataframe, and on the last 500 candles and compare results.

**Comment by rongybika** [comment]
Hi,

Probably your right.
I will try all what you have mentioned.

I think that we can close this ,,issue".
Thank you.
