### ISSUE TITLE
Expected behavior of startup_candle_count for multiple timeframe strategies?

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#6453]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version:  1.73.70 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have a strategy that uses 5m main timeframe and 1h informative timeframe. I'm trying to understand what length is the 1h dataframe as I can't find it in the documentation, so I'm printing the length of both dataframes. However, I'm finding strange results:

Most of the times, both dataframes have equal length, which is a number near but greater "startup_candle_count". However, I've also found that sometimes this only applies to the main timeframe (5m), while the informative (1h) timeframe has a number of samples so its temporal duration is equal (meaning that if I have 800 5m candles, then I have around 800/12=67 1h candles).

Which is the expected behavior for the 1hr informative dataframe length related to the startup_candle_count? 

Thanks

**Comment by xmatthias** [comment]
it'll depend a bit what mode you're talking about specifically.

For trade mode (live / dry run) - `startup_candle_count` has no real impact and is only there to warn if it's bigger than what the exchange can provide in one call.

For backtesting, we try to load "startup-candle-count in main timeframe more (so earlier than the original start date). This is obviously only possible if the data is also available, otherwise informative pairs will start when the available data starts.

for the calculation - assume you use 24 5m candles (2h) as startup candle count.
This means, the "starting-date" will be moved by 2 hours - so instead of at 00:00, your data will start at 22:00.
If possible, this is true for both 5m candles, as well as for all informative timeframes.

**Comment by dnuno89** [comment]
Sorry, I was referring to Live/Dry run mode. So, if I understand it correctly, in Live mode the bot gets all the candles that are provided in one call, for all dataframes, except if startup_candle is greater than the candles in one call, as then uses the required calls.

Right now I'm unable to replicate the weird results I was having some days ago, and all dataframes in Live mode are 999 candles long (I imagine it's 1 call) as would be expected.

Thanks.

**Comment by xmatthias** [comment]
You cannot rely on getting 999 candles all the time. If your logic somehow depends on that you're doing something fishy which will for sure be problematic.

Exchange downtimes can cause fewer candles in the exchange response - or if a pair was newly listed (or had a split or what have you - and didn't trade for a few hours).
relying on "i always get 999 candles, and fail if i don't" is for sure wrong.
