### ISSUE TITLE
Use freqtrade with outdated python version

### ISSUE THREAD

**Issue by harshadvekariya** [freqtrade/freqtrade#6462]
## Describe your environment

  * Operating system: Linux-Ubuntu
  * Python Version: 3.8, 3.6
  * CCXT version: ccxt==1.71.73 
  * Freqtrade Version: freqtrade -V
  * 
## Your question

I have two python versions installed in my system, Python3.8 and Python3.6. I want to install the freqtrade with Python version 3.6. Python3.8 comes by default, removing this version removes the gnome, hence the desktop. I also tried setting `alias python3='/usr/bin/python3.6'` in the `~/.bashrc`, and also commenting `check_installed_python`. However, it is not taking python3.6 to install the freqtrade when I run `setup.sh -i`

I am want to integrate the freqtrade with tf=1.15 library, which works only with Python3.6. Any help with this is highly appreciated, thank you.

Regards

**Comment by stash86** [comment]
I don't think FT support python 3.6, as can be seen here https://www.freqtrade.io/en/latest/installation/#requirements

And if you want official hack, don't think matthias would do it

**Comment by xmatthias** [comment]
Current versions of freqtrade will not work with python 3.6. 

This is not only because of freqtrade, but because of multiple dependencies. As such, we dropped support for 3.6 about a year ago, and for 3.7 roughly a month ago.
standard installation will therefore not support 3.6.

You can for sure give it a try by installing the package manually (this assumes you know your way around python) by manually downgrading necessary packages - but we can neither guarantee it will work (i think we use some 3.7 only features now so it would fail anyway), nor will we provide any support for this.

Best ask the library you're trying to use to upgrade to a modern, still supported version of python.

Assuming you mean Tensorflow with tf - then best upgrade to a new version - which will not only be supporting modern python versions - but will also have more features.
