### ISSUE TITLE
cancelled orders are processed as closed orders

### ISSUE THREAD

**Issue by mkavinkumar1** [freqtrade/freqtrade#6471]
https://github.com/freqtrade/freqtrade/blob/fdbd75501f1015218fc96fe5b390cf0aa323664b/freqtrade/constants.py#L59

https://github.com/freqtrade/freqtrade/blob/fdbd75501f1015218fc96fe5b390cf0aa323664b/freqtrade/persistence/models.py#L647-L651

https://github.com/freqtrade/freqtrade/blob/fdbd75501f1015218fc96fe5b390cf0aa323664b/freqtrade/persistence/models.py#L698-L707

How to differentiate canceled order and closed order?

**Comment by xmatthias** [comment]
A cancelled order will have filled = 0.
(it'll usually also have the status "canceled" - but you can't rely on that by 100%, as different exchanges report this differently).

The status itself is however irrelevant, as also a canceled order can be partially filled - so what you'll want to be looking at is if filled is <> 0 or not.

**Comment by mkavinkumar1** [comment]
isn't it a bug?

**Comment by xmatthias** [comment]
You will need to improve your communication skills (both in issues, as well as in the Pull request).
It's very difficult to try and collaborate with you at the moment - which can lead to missunderstandings, frustration, and in the end, closed PR's simply because you either don't respond, or don't listen.

The above is asking a question - which i assume is tied to #6424.

If it's a bug report, please
* fill out the issue template
* Provide logs of what's happening
* Provide a description of what's happening.

**Comment by mkavinkumar1** [comment]
Sorry. Cancelled orders are processed in recalculating open rate value and also in select filled orders as it will result in showing cancelled orders in /status trade.

**Comment by xmatthias** [comment]
That's correct if filled is > 0 - as you (or freqtrade) can cancel an order that half-filled - so instead of buying 100$ of a coin, you only bought 50$ (then it timed out). 

we cannot ignore these orders - therefore the status simply means "non-closed" - which has to include all 4 states as listed above.

**Comment by mkavinkumar1** [comment]
So the last condition is not needed?

**Comment by xmatthias** [comment]
Yes it is - it's excluding still open orders - we only want orders that are closed in the above case (all that are non-open, basically).

**Comment by mkavinkumar1** [comment]
ft_is_open  is also performing the same. Right?

**Comment by xmatthias** [comment]
Don't know that by memory - would need to check where / when exactly this can be set (i assume there could be other instances, too).
