### ISSUE TITLE
Trading at higher timeframes than data

### ISSUE THREAD

**Issue by TheDropZone** [freqtrade/freqtrade#6506]
## Describe your environment

  * Operating system: Windows 10 (Docker)
  * Freqtrade Version: freqtrade 2021.10 (Docker)
  
## Your question

I am attempting to implement a strategy that trades on a 5m timeframe using a few various indicators, but that uses information about the macd histogram taken from the 1m chart. I crafted the strategy on tradingview using their Multi-Timeframe functionality (https://www.tradingview.com/support/solutions/43000584445-how-to-use-multi-timeframe-mtf-functionality/). 
Based on experimentation with pinescript and TV, it seems that MTF simply calculates an average when using lower timeframe data (ex. if trading on 5 minute chart, but using 1 minute data, the past 5 data points are averaged together to present the 5 minute data point).

After reading docs, my first attempt was to use the below with a 5minute strategy 
```python
@informative('1m')
```
Which promptly told me that I can't use informative_pairs at a timeframe below the strategy timeframe.

Next, after searching docs and comments, my next attempt was to use a strategy at 1minute (for my macd data that I need) and then put the rest of the indicators on an @informative('5m',ffill=False). My catch is that I still do want to trade based on a 5 minute chart. My guess was to try something like this in the "populate_buy_trend"
```python
        dataframe.loc[
            (
                pd.isna(dataframe["rsi_5m"]) == False & #Only buy on 5 minute chart
                ...
            ),
            'buy'] = 1

        return dataframe
```
My thought is that with ffill turned off on the informative, and checking to see if rsi_5m is not empty, so only populate buy and sell on the 5 minute chart. Sadly, this isn't averaging the 1 minute macd data so still need to do some research/doc searching for that one.

Is this a valid assumption? Is this the proper way to trade on a 5minute chart with data from a 1minute chart? Is there a hard reason why informative_pairs could not use lower timeframe data?

Thanks

**Comment by xmatthias** [comment]
the automatic using the `@informative()` decorator will not allow you to use lower timeframes, nor will freqtrade automatic merging tools freqtrade provides.
This is because you'd try to merge 5 lines on to one line - which obviously will not work.

While you seem to have some logic in place (average the data) - that's not given - so we cannot safely assume that using the average (or any other function) is correct.

You can however use the "manual" [informative method](https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample) by calling `get-pair-dataframe`.

It's then your task to properly merge the 1m data to the 5m data (in a way that doesn't create new rows on the 5m chart).
This means, you'll either have to drop additional lines (why use 1m candles, then?) - or resample them first to at least 5m using the logic of your choice to get the proper data.

---

Where you're mistaking however:
since you're using 1m data (data which changes every 1 minute) - you'll effectively be trading at 1m, even if your "main" timeframe is 5m. 
The "open" candle values will change - causing "ghost" signals which may only be showing up from :02-:04 - but disappear at :05 (and have not been there yet at :00).
This means, when looking at a live chart - you may see trade entries (trades taken) - but there is no trade-signal showing.

Also, backtesting will not properly be able to capture this - so i think the choice to "don't go to 1m" will lead to a lot of workarounds - and do results you'll not really understand (the buy-signal is no longer showing).

**Comment by TheDropZone** [comment]
Thanks for all the great details and insight. Just for the sake of learning more, I'll definitely dive into the "manual" informative get-pair-dataframe method and try to get a better understanding there.

So, in your opinion, if the desire is to:
- Trade on the 5 minute chart
  - Respond to signals that present themselves on the 5 minute chart
- Use macd data from the 1 minute chart

I should:
- use the main strategy timeframe of 1 minute
- use informative pairs from 5 minute TF
- Average the macd data from the 1 minute chart and use that

Does that seem like the best option? And then if that is the way to go, How do I ensure that I am only trading on 5 minute intervals (where my 5 minute data is the most accurate)?

Thanks

**Comment by xmatthias** [comment]
the moment you use macd data from the 1m chart - you're no longer trading 5m.
your signal will be able to "flip" depending on 1m changes.
If that's not possible - then you're not using 1m data (it's not part of the signal).

Even with 5 conditions (1m macd being one of them) - you'll have situations where 4 are true - and the 5th (the 1m macd) is false - however flips mid-candle.

As such - also on 5m, there's little preventing you from getting trades 2-3 minutes into the 5m candle - so the "safety" you feel in when using 5m as main timeframe is not really there - as freqtrade will just act based on the strategy.
you can always use `ignore_buying_expired_candle_after` (a often overlooked setting) to prevent buys after X seconds (say - 1 minute).

**Comment by TheDropZone** [comment]
Ahh, great points. I think I was somewhat narrow minded thinking In terms of how my strategy worked in tradingview that I was missing the whole point. Thanks so much for the explanation.

I will also look into the mentioned setting to see if that could benefit me at all.

Thanks for your time!
