### ISSUE TITLE
buy_tag for forcebuys

### ISSUE THREAD

**Issue by thalro** [freqtrade/freqtrade#6544]
I have noticed that a forcebuy generated through telegram leaves the buy tag empty. I think it would be good if a buy tag could be applied.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

This is currently not possible. 
For the API, it could potentially be an option - although not one i see as particularly important, nor do i see much/any benefit on it - as it'll be a "user-invoked" buy - so the best way here might be to fill buy_tag as "forcebuy" automatically without providing it as part of the interface at all.

---

Telegram is mainly used on phones - so having multi-parameter commands is very bad from a  usability perspective.

The way i see the UX for telegram at the moment, this is something that will probably never be enabled for telegram.
telegram is also missing other parameters which the API provides (order type, ...) - simply because it'll be too complex/error prone to have to type multiple parameters in the correct sequence.

Assume the following command - `/forcebuy SOL/USDT 91 95 limit`
After looking up the price, you'll probably still be in doubt if I'd like to buy 95 SOL for 91$ - or 91SOL for 95$.

For a user, it'll be even more difficult to determine which parameter goes first, and having the sequence wrong can lead to disastrous results - with entry prices all over the place - potentially leading to missed other opportunities due to locked up trades.

**Comment by thalro** [comment]
ok, I understand. Thanks for the reply and sorry for not filling in the
template. I will do it next time. Thanks for the great work!

**Comment by xmatthias** [comment]
Doublechecking this - for the API - it's already available (called `entry_tag`).

It's not used by freqtrade - and no default is set.

it MAY make sense to set this to forcebuy if it's not set (also from telegram) - but i'm undecided on that so far.

**Comment by thalro** [comment]
Hey,  thanks for getting back to me. I'm no expert on this. I just noticed
that I don't see a buy tag in frequi for stuff that I force-bought through
telegram. I wanted to catch frocebuys in confirm_trade_exit and couldn't
find a way to identify them. I asked in the discord  and froggleston
suggested that this might be a ticket.

**Comment by xmatthias** [comment]
that's correct, you can't really filter for these at the moment.

Setting this explicitly would help to some degree - but if you start setting the tag manually through the API, this would have to change again (you're filtering on a free text field, basically).
