### ISSUE TITLE
status should not be passed in fake result

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6582]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: dev e7418cd (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

https://github.com/freqtrade/freqtrade/blob/e7418cdcdb9cf7916ff0a5464113c20817fe7486/freqtrade/exchange/exchange.py#L977-L987
If order could not cancel and could not fetched, passing `status` as `'cancelled` should be wrong.
So `status` should not be passed in `cancel_order_with_result` and `cancel_stoploss_order_with_result`

**Comment by xmatthias** [comment]
If you think we should investigate something - please provide corresponding logs that show the problem happening.

I'll not investigate theoretical problems you think you see from looking at the code - unless it's something that really caused a problem, as that is simply wasting time hunting for ghost problems.

If you feel something minor should be changed - best propose the change in a Pull request - where we can then determine if the proposed change provides benefits / enhanced behaviour - or has drawbacks.

Thanks for your understanding.

Feel free to reopen this issue IF you can provide logs that show this problem happening in reality.

**Comment by xmatthias** [comment]
Adding to the above for clarity:

The only situation i'm aware of where freqtrade will try to cancel an order, and subsequently fail to fetch the order:
* fetch_order works for this order id (otherwise we'd not try to cancel it)
* cancel_order works (but has an invalid result - which can happen for example on ftx and bittrex iirc).
* fetch_order no longer works - this means the order was "forgotten" and is no longer returned (bittrex)

As the order is "no longer available" - but we tried to cancel it - we can safely assume that it's not filled (then it'd be returned) - so the only conclusion is that it was cancelled successfully.
