### ISSUE TITLE
Could Kucoin 42900 be applied to `retrier`? 

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6583]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: e7418cdcdb9cf7916ff0a5464113c20817fe7486 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

#5847 is only applied for `retrier_async`.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

we could - but as mentioned in https://github.com/freqtrade/freqtrade/pull/6584#pullrequestreview-919207451 - i don't see why - as this problem is only affecting ohlcv endpoints as far as i know.
Blindly applying it to all endpoints can lead to permanent exchange bans (we're disrespecting their rate-limits), so if any, we'll have to be selective of the endpoints we KNOW it affects (there is none other than ohlcv i'm aware of - so for the moment, i see this as "won't fix".
