### ISSUE TITLE
Current dev backtesting  appears to crash, if one of the pairs has "no data left after adjusting for startup candles", with "ValueError: cannot set a frame with no defined index and a scalar".

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6629]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8.10
  * CCXT version: 1.77.45
  * Freqtrade Version: develop-6a622d26e
  
## Describe the problem:

```
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 1116, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 1053, in backtest_one_strategy
    results = self.backtest(
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 915, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 343, in _get_ohlcv_as_lists
    df_analyzed.loc[:, col] = 0 if not tag_col else None
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1615, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar
```
### Steps to reproduce:

  1. have a pair in the config that for the time range it will produce "no data left after adjusting for startup candles, skipping." edit: and at least one other 'normal' pair. edit: a high `startup_candle_count` might help to reproduce it
  2. backtest
  3. error

**Comment by epigramx** [comment]
~~This appears to be the cause~~, https://github.com/freqtrade/freqtrade/blob/0b40c37cc54dbf97ff8ed1b82330e9d158d91d6b/freqtrade/optimize/backtesting.py#L1054

I don't see why it would pass the untrimmed one there.

**Comment by epigramx** [comment]
~~Also I don't see why it would start happening now, since that code is there for a long time, unless I misunderstand how diffs show up on github.~~

It's most probably something in the latest backtesting edits, which I noticed they are extensive ~~, exposing this old bug~~.

**Comment by xmatthias** [comment]
6a622d26e is not really a version in this repository (otherwise it would turn into a link on the left) - which suggests there've been edits.
The bigger problem than any is however that it makes it impossible to determine the version you're using.

You're correct, there have been quite some edits - but as of now, i'm unable to determine if you're using a version prior to the "extensive changes" (which were caused by merging futures/short to develop), or one from afterwards, which would obviously change the approach.

**Comment by epigramx** [comment]
Yeah I had some edits but I had reverted them before retesting so I think it's irrelevant since this was on latest dev code I had downloaded today.  

~~I think that part of the code is wrong anyway; it passes to backtesting the unprocessed list; it appears it's meant to pass the trimmed list.~~

~~Passing it preprocessed_tmp instead (which should be probably renamed to 'processed') fixes the issue.~~

**Comment by xmatthias** [comment]
> I think that part of the code is wrong anyway; it passes to backtesting the unprocessed list; it appears it's meant to pass the trimmed list.

Trimming afterwards is actually the correct behaviour (this is not something that was changed recently).
By moving the trimmed part to "before" - you're getting the short dataframe to the `populate buy/sell` methods.
This means, if you use any `.rolling()` or `.shift()` there, then the first signal possible will be after the lookback you're using.

Worse than this - the dataframe will be trimmed again - so your `startup_candles` will actually be applied twice.

There's also a comment describing this ... ;) 

https://github.com/freqtrade/freqtrade/blob/0b40c37cc54dbf97ff8ed1b82330e9d158d91d6b/freqtrade/optimize/backtesting.py#L1047

**Comment by epigramx** [comment]
>Trimming afterwards

Where do you mean? The only usage of trim_dataframes() I see (for backtesting) is at that spot, which is before the only usage of backtest().

**Comment by epigramx** [comment]
Confirming that the line 1054 hack, does not even solve the issue for all time ranges. But what remains true is that if I remove from the config all the pairs which produce the ""no data left after adjusting for startup candles" info: the OP error goes away on default dev code.

**Comment by epigramx** [comment]
Wait a second. Why do we even backtest if there is no data at all? Can't we just return nothing?

**Comment by epigramx** [comment]
At line https://github.com/freqtrade/freqtrade/blob/7c5e7300076a3fd0443aa6743ce1d39dd3699f4e/freqtrade/optimize/backtesting.py#L325, it appears certain dataframes are returned empty while they were not empty before that assignment; it appears the reason is that the required_startup/`startup_candles` is big enough to cause that.

It's unclear to me if a check for `df_analyzed.empty` and a `continue` would solve it; it's probably not the right solution; that's because I don't see why the `required_startup` should empty a dataframe.

**Comment by epigramx** [comment]
The problem appears to be somewhere around the calls to `trim_dataframe()` which is called multiple times before the crash. Also the crash appears to require at least one "has no data left after adjusting for startup candles, skipping."-pair and another 'normal' pair otherwise if the no-data pair is on its own: backtesting exits normally with the "No data left after adjusting for startup candles." error (edit: it appears ~~to also need~~ a high `startup_candle_count` ~~for it to~~ helps to cause it ~~happen~~).

What difference between the codes I figured so far: `trim_dataframe()` used to be called 3 times in old code for the no-data pair; the first 2 calls returned a non-empty dataframe and the 3rd an empty one and the backtesting continued as normal; now it's called 4 times instead with the last call also returning an empty dataframe before the crash.

**Comment by xmatthias** [comment]
the number of calls is not the relevant part point for the exception
it's failing because of the assignment of None (which is a literal) to an empty dataframe (which pandas doesn't like).

prior assignments on a empty dataframe work as they're sourced from the same empty dataframe.
as such - it's a minor bug - occurring in rare circumstances (took me a while to get data prepared in a way to actually cause this behavior).

The amount of `startup_candle_count` is not relevant - what needs to play along is:

* you need data finishing "early" for one pair, in combination with a pair that got more data.
* the timerange /startup-candles needs to be configured in a way that:
  * both pairs initially load data
  * at least one pair has no data after removing the startup candle count
  * at least one pair still has data left after removing startup candle count.

Which is quite a specific scenario to get to ... obviously with higher startup-candles it's easier to archive, as the gap for this widens.
