### ISSUE TITLE
Can not combine last few RSI values

### ISSUE THREAD

**Issue by topcumustafa** [freqtrade/freqtrade#6674]
* Operating system: Windows 10
  * Python Version: 3.10.2
  * CCXT version: 1.77.98
  * Freqtrade Version: 2022.3
  
## Your question

I am trying to do buy/sell with last few RSI values, but when I try to combine last few RSI values it gives  "WARNING - Empty candle (OHLCV) data for pair" 

FOR EXAMPLE 

```python
def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
           (
               dataframe['rsi'].shift(1) < 89 &
               dataframe['rsi'].shift(2) < 89 &
               dataframe['rsi'].shift(3) > 89
           ),
           'sell'] = 1
        
        return dataframe
```
This is just an example. 

```python
# It works fine if I only use one value like this:
dataframe['rsi'].shift(1) > 89
```

What am I doing wrong?

**Comment by stash86** [comment]
Maybe you need some () ?

**Comment by topcumustafa** [comment]
> Maybe you need some () ?

I tried but still same. :(

**Comment by stash86** [comment]
have you set startup_candle_count?

**Comment by xmatthias** [comment]
> WARNING - Empty candle (OHLCV) data for pair

suggests that you're not returning the dataframe in one of the methods - which can also mean that there's a syntax-error in the pandas assignments (basically the `dataframe.loc[]` calls).

That said - the above is clearly invalid syntax - you MUST bracket each expression if you use `&` to combine the values, otherwise it'll be invalid pandas syntax.



> I tried but still same. :(

Maybe share how you tried this - maybe the brackets you set still contain some error?

**Comment by topcumustafa** [comment]
It was kinda complicated buy/sell conditions. I realized I missed some brackets. After I fix the brackets it works fine. It was a stupid mistake 😄 Thank you for ur help.
