### ISSUE TITLE
Using funding rates as indicator in a spot strategy?

### ISSUE THREAD

**Issue by Guillaume6606** [freqtrade/freqtrade#6684]
## Describe your environment

  * Operating system: ____ macOS Silicon
  * Python Version: _____ 3.8.6
  * Freqtrade Version: ____ freqtrade docker-cbbbe8a5
  
## Your question

I see multiple mentions of funding fees in the code and I guess it is in development. I would like to use it as an indicator to generate  signals in backtesting/dry run/live run. Is it possible at the moment? Any help/information would be much appreciated.

**Comment by xmatthias** [comment]
the use of other so-called "candle-types" is only possible within the defined trading-type (spot for spot, and futures/funding-rate / mark/index when trading futures).
As such - you can define and use funding-rates as informative indicator when using "futures" as trading mode - but not for spot trading (look for the candle_type argument in the informative decorator, or the 3rd tuple element in `informative_pairs`).

you may be able to get away with it for backtesting (as we don't explicitly check for this) - but it will not work in dry/live modes - and this is unlikely to change anytime soon due to the way ccxt  implements futures data (_will depend on the exchange, but assume it's not working in 90% of the cases_).

**Comment by Guillaume6606** [comment]
Thank you for your quick and thorough answer. I believe there is no documentation on futures mode as it is only in development, but based on the name I trust this mode will not allow me to make spot trades? (the idea being to reverse the problem and realise my strategy in futures mode, but in that case I would not have access to my spot-based indicators right?)

**Comment by xmatthias** [comment]
documentation for futures mode is available if you switch the documentation to "latest" (bottom right corner) - and will propagate to the default (stable) version once we release next time.

That's correct - see them as separate modes for now - unfortunately without access to the "other" mode for the moment. While that's something we may look into - that'll definitely not be for the initial release.
