### ISSUE TITLE
KuCoin: Known issue "to many requests"

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#6745]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.2.1____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I know about the "to many requests" issue on KuCoin, and this seems not to be an issue on the Freqtrade-side. Have you already got something like a workaround, which is more or less "waterproof", to use the exchange productively?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
As long as the issue is 429000 (which according to support is "retry immediately") - we're retrying immediately for several times.
While it may fill the log to some degree, logging here is also throttled, so you'll not see all failed requests.

In my experience, this only applies to the klines (candles) endpoint - as such it's only implemented there.
If you experience other "too many requests" calls (not 429000) - then it's something to do with rate-limits - but I've not heard about such a problem on kucoin.


I know a lot of users are using kucoin according to our discord server - so it is working fine.
Due to the instability of their api, we'll however not add it to the list of "supported" exchanges for the moment.

**Comment by myNextCoder** [comment]
I thank you for your answer. I have activated KuCoin due to its presence in the NostalgiaForInfinity project. I am glad to read in your text, that the error should not harm our work. But I test the exchange carefully on dryrunning it.

**Comment by xmatthias** [comment]
you should pick an exchange based on availability (what's available in your country) and features (low fees?)- not "because others use it".

That said - i think this answers your question.
