### ISSUE TITLE
Sending Custom Message to Telegram from Strategy

### ISSUE THREAD

**Issue by chriswck** [freqtrade/freqtrade#6772]
## Describe your environment

  * Operating system: Windows 10 Home Version 21H1
  * Python Version: Python 3.10.0
  * CCXT version: ccxt==1.79.94
  * Freqtrade Version: freqtrade 2022.3
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,

I would like send to Telegram my populated indicators. Is there any way to send custom messages to Telegram without having to modify the bot's source code?

I had a look at freqtradebot.py, rpc_manager.py and telegram.py and am an intermediate coder at best.

Thank you,
Chris

**Comment by xmatthias** [comment]
This is not possible, and it's also unlikely to be integrated.

If you just call this from within populate_indicators (for example) - then you'd get a message per pair every 5 seconds (default settings).
This has therefore a very real possibility of spamming you.

Also, strategies are often shared, so this bears a very real risk of misuse (people could place spam in the strategy message).

**Comment by chriswck** [comment]
Hi Matthias,

Thanks for your response.

I take it that it's technically not possible, even if assuming I'm okay with the spam and only for self use?

Newbie question - there is probably no way for me to reach the self.rpc from self.strategy in FreqtradeBot? Do you see any hack-y ways to send a message to telegram from strategy?

**Comment by xmatthias** [comment]
no, this is intentionally decoupled.

**Comment by chriswck** [comment]
Thanks

**Comment by Shade-** [comment]
Jumping in to say this would actually be a good way to complement automatic trading with supervised semi-auto trading.
My own strategy runs fine but sometimes misses good entries which I would want to enter earlier/later instead.

I would love to be able to send notifications from within my strategy to alert me a significant event has happened so I'm more alert on market conditions (eg.: EMA 50/200 crossover representing a potential buy).
I'm currently stuck with a separate dry run buying at every crossover (so that I receive a notification in a separate Telegram bot), but it feels kinda hacky.

I'm a programmer myself but I'm new to Python (have learnt some developing my strategy, but I'm mainly a JS/PHP coder).
Would love to know how to do this for myself if not possible to implement in the official release, thank you!

**Comment by xmatthias** [comment]
As mentioned above - RPC and strategies are intentionally decoupled.

There's no easy way to hack this into freqtrade.
