### ISSUE TITLE
hyperopt set ROI lower then trailing_stop_positive_offset

### ISSUE THREAD

**Issue by pr0vieh** [freqtrade/freqtrade#6813]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu
  * Python Version: Python 3.9.7
  * CCXT version: ccxt==1.81.81
  * Freqtrade Version: freqtrade develop-0f499469f

## Describe the enhancement

hyperopt ignores the tip from the documentation
and set ROI lower then trailing_stop_positive_offset
![image](https://user-images.githubusercontent.com/61424/167722549-8b9f42ed-b97e-4c95-9c48-9025abddacd8.png)

if hyperopt roi and trailing is active note this condition 
if trailing_stop_positive_offset = x  roi { 0 :  > x && !=0 }

**Comment by xmatthias** [comment]
In general, i'd suggest to not mix these 2 spaces, but optimize them one after the other.

That will usually yield better results as the space is smaller (so there's fewer local minima).

The spaces themselves are treated independently. That's in part due to limitations in how scikit-optimize works - and in part because combining via some hacky way them would most likely remove the possibility to hyperopt them independently.

We have long required users to transition parameters manually to the strategy so they are forced to look at the values, and consider if they make sense or not. While that's no longer necessary, that's still something i'd strongly recommend.

What a result like this really means is that your trailing stop could be deactivated. 
As scikit-optimize does not support hierarchical spaces - you'll also notice that it will change trailing stop around while actually having trailing stop disabled (so the changed values have no effect).

**Comment by pr0vieh** [comment]
oh ok that sounds very plausible 

it might make sense the point of view :monocle_face:
the trailing stoploss can deactivate/overwrite the roi...

then if trailing_stop_positive_offset is reached and set (an the exchange for example) is this the save point.
then you would have to prevent the ROI from being sold prematurely

maybe a switch
trailing_stop_positive_offset is reached and Set to prevent the ROI exit ?

sorry for the maybe pointless ideas but im new :grin:
if this is bullshit then feel free to close this ticket

**Comment by xmatthias** [comment]
considering how ROI works - this will make little sense.

It can "jump around" (it's time/step based - so you can want a profit of 5% in the first hour - or 3% after 1 hour. 
Deactivating this logic because we're "trailing now" will be highly unexpected - depending on the value you're trailing at it may even lead to losses (if you don't use offset).

If you want to rely on trailing stoploss alone - then this is perfectly fine and archivable by setting ROI to a very high number (200 or so).

if you use both - then both will (and should) be active.
Consider your ROI is at 10% - and you trail with 2% - so your trade reaches 9% - you'd expect the trade to be sold at 7% (2% below it's high point). 
Your strategy also explicitly said that "i'm happy with 10% - so sell at 10%".
Both are expected. if you don't want one or the other, then you can disable either functionality to rely solely on trailing stop (if that's what you're after).

**Comment by pr0vieh** [comment]
> Your strategy also explicitly said that "i'm happy with 10% - so sell at 10%".

but when the trail can reach maybe 20% then drop 2% i can't get 18% then i have sold at 10%... 😞
this is what i mean...

and yes i talking about if trailing_stop_positive_offset=x is reached

with this we can prevent ROI to leave an currently good growing Trail to fast

**Comment by xmatthias** [comment]
you still need to pick - either you want ROI at 10% (top-capping maximum profits at 10%) - OR you want to leave it trailing (potentially having more profits) - but also at the risk of a minor pullback throwing you out of a trade.

both ways are possible (either use ROI, or use trailing stop, with ROI disabled, or disabled for some time).
you can't however combine them - as ROI would fire before (you explicitly decided to top-cap profits at 10%).
