### ISSUE TITLE
Code Discussion

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6821]
https://github.com/freqtrade/freqtrade/blob/c299601ece12c388a20042fc508debbd89b3ca1d/freqtrade/freqtradebot.py#L521-L539

Why `current_rate` is not passed to `execute_entry`?

**Comment by xmatthias** [comment]
simply adding that will be a (undesired) change of behavior.

by not passing in the rate - the strategy get's a say in this via `custom_entry_price()` - which is the expected behavior.

there might be other/better approaches to this to avoid calling get_rate another time - but i'm not sure this creates a problem either.
