### ISSUE TITLE
Static Whitelist: Error when Coin is no more available on KuCoin spot

### ISSUE THREAD

**Issue by Pado1985** [freqtrade/freqtrade#6850]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS / GNU/Linux 5.13.0-1027
  * Python Version:
  * CCXT version:
  * Freqtrade Version: Docker Version 20.10.12
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

With a static Whitelist there is a fatal Error if a Coin is no more available on KuCoin spot.
For Example in my case it was the Coin "Luna".

### Steps to reproduce:

  1. Saw in Telegram 27 RNDR/USDT  1h nan%
  2. Show Logs and saw ERROR - Fatal exception!
  3. deleted "Luna" from the Whitelist and restarted the Bot
  4. The Bot runs again without error
  
### Observed Results:

The Problem was that a Trade was open in this Time and the Bot did not respond.
On Telegram it shows like that: 27 RNDR/USDT  1h nan%.
After I saw the error in the Logs i deleted the Coin from the Whitelist and restarted the docker-compose.
Then the Bot runs without Error and the Open Trade looked like that :27 RNDR/USDT  2d +20%.

It should only gives a Warning and not a Error.
So the Bot can handle the Trades like in the normal Case.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
2022-05-14 11:25:09,714 - freqtrade.commands.trade_commands - ERROR - Pair LUNA3S/USDT is not available on KuCoin spot. Please remove LUNA3S/USDT from your whitelist.
2022-05-14 11:25:09,714 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

**Comment by xmatthias** [comment]
This exception is only thrown at startup (when freqtrade is starting up).
It's intentionally there as an exception, as otherwise people tend to overlook important messages.

If freqtrade is running and the pair is removed, then this will not cause an error, but will cause either "Pair XXX is not compatible with exchange ..." - or "Pair XXX is not tradable with Freqtrade...".

Both of these messages will be logged as a warning logmessage, not as an exception.


---

In your case, it therefore seems like you either got another exception, or you were restarting (`/reload_config`) your bot before this exception happened. It's at any rate not the reason why freqtrade becomes unresponsive.

Maybe you can look further back in your logfiles to find the real exception.

If not, i'll close this issue within a few days - as the behavior experienced (based on the provided logs) is intentional (exception on startup with staticpairlist and invalid pairs).

**Comment by xmatthias** [comment]
Closing for lack of information.

Feel free to reopen / comment below should you be able / willing to provide the requested info.
