### ISSUE TITLE
lightly compress thyperopt_tickerdata.pkl file

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#6868]
## Describe the enhancement
(Sorry upfront if there is not everything right in my reasoning)
For every hyperopt - cycle with multiple jobs a hyperopt_tickerdata.pkl is saved and then read from the drive for each job to be calculated.
hyperopt_tickerdata.pkl is taking up humongous amounts of space and it is currently bottlenecked by the maximum speed of the vps's hard drive while the CPU is just in idle.

*Explain the enhancement you would like*
It would not have to be .7z on ultra or something mad like that. anything that is able to compress/decompress with multi threading (yeah python and multithreading don't go too well with each other) would suffice to speed up the drives' reading/saving process and keeping the cpu busy aswell.
In addition this would not tear down anyone using using his own drives since (at least for me) this is 5GB of data per each cycle.

The best solution would be to not have the hdd be busy and directly push that tickerdata over to the slave-jobs but don't know if that is possible.

The aim would be to reduce the cpu0% time while the drive is the only thing running at full tilt.

Picture1 shows the drive usage
![HDD_Hyperopt](https://user-images.githubusercontent.com/41228167/169643042-d7aca7f9-c3bd-4566-b8b5-fb797c2f02c2.png)
Picture2 shows the CPU usage
![CPU_Hyperopt](https://user-images.githubusercontent.com/41228167/169643041-446d6140-40a0-48d7-9ead-a9fe0f6a7c59.png)

**Comment by xmatthias** [comment]
The problem here is 2-fold. 
For performance reasons, the BEST would be to keep the results in memory, only saving them to disk at the end (or every few 100 epochs).
However, this causes memory spikes (it's technically a memory leak, although it's intentional), resulting in fewer data that can be used to hyperopt (you'll run out of memory quicker).
As such - the choice was made to persist every epoch independently (it could be batched in theory - but you'd cause spikes - which will be quite different depending on the hyperopt results).

Obviously persisting every epoch will cause disk usage - but with SSD's, i don't think that will be a problem (if it is, switch VPS providers).

While zipping itself sounds like a good idea at first - i'm not sure it is, as that'll put more pressure on the CPU.
I'm also not sure if appending to a zipped file is possible _without drawbacks_ - in the worst case, it would mean that we'd have to read/write the file each time (due to it being zipped). That'd have the opposite effect, causing more disk activity (reading the full file, writing the full file) as opposed to just appending to a file (where the size really doesn't matter).

**Comment by hippocritical** [comment]
writing it to zip files normally just generates a new dictionary which means compression would not be as good as if it would be written in one session, but well ... it would not be 7zip ultra either way.

Was just an idea to speed up the downtime for the cpu in between job cycles, if you think it would have drawbacks then it s no problem either way.

**Comment by xmatthias** [comment]
the "real" resource hog "between cycles" is the optimizer - trying to find the next values.

You can observe this in the CPU cycles - it'll spawn to "full multiprocess" - and then return to a "single process" approach for a bit, before spawning processes again.
This is expected behavior from scikit-learn (at least for the default algo - which is not parallelizable (or it's not implemented  in scikit-learn).

writing a file to disk will not significantly change this, as it's really just a minor time-component in this

**Comment by xmatthias** [comment]
Doing a small "timing" test (~100 epochs) with appending to a gzip file instead of a regular file (gzip allows file streaming - other zip options don't):

```
# With GZIP
t_ask=199344260393 - 199.344260393s                                                                                                 
t_back=36388747249 - 36.388747249s        
t_tell=9548104533 - 9.548104533s                                                                                                    
t_save=122084409 - 0.122084409s 

# Without gzip
t_ask=193545212696 - 193.545212696s
t_back=30956273775 - 30.956273775s
t_tell=9427832586 - 9.427832586s
t_save=71335374 - 0.071335374s 
```

You'll notice that the speed decreases (time increases) by almost 2x by using gzip - simply by using gzip.
The "other" options cover other areas of the "sync" loop - with "ask" being the prevalent (as explained above) - which is asking for new / next points.

Filesize decreased form 1.9M to 329k - so there might be a size benefit - but definitely not a speed benefit - but i'm not certain it's worth the effort - as my epochs also produced quite small results (only a few trades).
