### ISSUE TITLE
Fatal Exception - No module named 'pymysql' in Docker container

### ISSUE THREAD

**Issue by clutch70** [freqtrade/freqtrade#6945]
## Describe your environment

  * Operating system: Ubuntu Server 18.04
  * Freqtrade Version: freqtrade 2022.4.2
  

## Describe the problem:

When trying to leverage an SQLAlchemy string in the docker container, an error is thrown reporting that pymysql is missing. My peasantly Googling (https://stackoverflow.com/questions/50333650/install-python-package-in-docker-file) makes me think that the module is missing from the dockerfile. If I'm on to a thing here I'm happy to do up a PR to add to line 40 of the dockerfile.

### Relevant code exceptions or logs

docker-compose service when error is thrown

  ```
ft-400-NFI-static-eth-kucoin-buy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: ft-400-NFI-static-eth-kucoin-buy
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile user_data/logs/400-NFI-static-eth-kucoin-buy.log
      --logfile syslog:1.1.1.1:514
      --db-url mysql+pymysql://user:password@localhost:3306/400_NFI_static_eth_kucoin_buy
      --config user_data/configs/400-NFI-static-eth-kucoin-buy-config.json
      --strategy NostalgiaForInfinityX
  ```

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 2022-06-08 02:03:55,200 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kucoin'...
2022-06-08 02:03:55,218 - freqtrade.commands.trade_commands - ERROR - No module named 'pymysql'
2022-06-08 02:03:55,219 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 69, in __init__
    init_db(self.config.get('db_url', None), clean_open_orders=self.config['dry_run'])
  File "/freqtrade/freqtrade/persistence/models.py", line 56, in init_db
    engine = create_engine(db_url, future=True, **kwargs)
  File "<string>", line 2, in create_engine
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 68, in dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
  ```

**Comment by clutch70** [comment]
#6947 pending review

**Comment by xmatthias** [comment]
This is correct and intentional, keeping the docker images to a minimum size.

As the [SQL documentation](https://www.freqtrade.io/en/stable/sql_cheatsheet/#mariadb-mysql) describes - packages for additional sql databases need to be installed separately.
For docker, this can be easily accomplished by following [the docker segment about custom dependencies](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose).

While i do understand that you'd like to have this builtin, a majority of users are using sqlite, which is working perfectly fine.

If any, then Postgres would be the next choice - i've only seen very few people actually use mariadb with freqtrade. If any other DB is used, then it's almost in all cases i've seen so far postgres, so if any additional database support would be added, it'd surely not be mysql, but postgres.

It's an optional dependency - one that only edge-cases will require.
but where would this stop? 
we should install mariadb, postgres, maybe mssql and oracle as well, because someone may intend to use it at some point?

**Comment by clutch70** [comment]
This custom dockerfile is working well to import this dependency.

https://github.com/clutch70/freqtrade_public/blob/main/docker/dockerfile.custom
