### ISSUE TITLE
Freqtrade Amount is not equal to exchange's Amount

### ISSUE THREAD

**Issue by xxRockOnxx** [freqtrade/freqtrade#6948]
## Describe your environment

  * Operating system: Linux
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-b2968df5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I tried searching the docs and asking Discord but I didn't really get any answers.

I'm not sure if this is intended but the Amount in Freqtrade is not the same as in the Exchange.

Why? How is it being broken down in Freqtrade if it's intentional?

Example:

In exchange:
LIT Amount: 9.49050000

In Freqtrade:
LIT Amount: 9.34078323

**Comment by xmatthias** [comment]
with the provided information, there's little we can do to actually help or answer. This will revolve both here as well as on discord - as answers can only be as good as the question.

In general, freqtrade amounts will align to the amount on the exchange.

Freqtrade will however not "overconsume" - so if you had preexisting coins on the exchange, freqtrade will not touch these (allowing for HODL or separate trades in the same account) and make the trade "more than what it bought".

The one exception to this is fees - which can eat into existing coins in certain conditions.

---

The most likely case is that you had some pre-existing "dust" in LIT on the exchange (with the provided information, it's however all just guessing).

It's possible that this amount was "left over" unsellable dust from a prior trade (most likely due to 0 BNB, or BNB fees disabled).
Freqtrade would then eat into this dust (paying fees) - but it would not assume a higher balance than what was bought in the initial order for this trade.

If you look at the exchange - was the full amount bought in one order / trade - or in multiple orders?

My best guess for now is that the order freqtrdade placed (recently) was for 9.34078323 - and the remaining LIT is from a prior trade.

If the above is not the case (you should see that in the exchange order history), then to further look at this, we'll need:
* freqtrade logs from the time the trade was opened (both when the order was placed and when it was filled)
* the output of `freqtrade show-trades  --print-json --trade-ids <tradeID>`. (using the trade-id for the LIT trade).

**Comment by xmatthias** [comment]
Without the requested information, there's little we can do for you.

feel free to comment below / reopen if the above did not answer your question  and you're able to provide the additional requested info.
