### ISSUE TITLE
question on exiting an order

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#6950]
Dear friends. I have set the stoploss, roi and other configurations in some strategies here. the problem Im facing is that when the exit (sell) order is set in some cases it can not sell or exit and even when i apply force exit command again it can not exit. what is required to be considered to change? what parameter do i have to adjust more precise or change to avoid such cases?
thank you

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

It'll depend a bit - but from what you describe, i guess the problem is that your orders don't fill (there's noone on the other side to fill your order).
Best consult the [pricing documentation](https://www.freqtrade.io/en/stable/configuration/#exit-price) about this - it has some guidance on how to price orders - but assumes some basic understanding on how markets (and in particular orderbooks / order filling) work.
