### ISSUE TITLE
Behavior on large dry run trades

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#6963]
When testing with dry run with trades of hundreds or millions of USD₮, does it checks the deepness of the order book? I mean, if it simulates a completed buy and a completed sell, does it mean the order book had volume for such a big trade?

**Comment by xmatthias** [comment]
market liquidity itself is not taken into account fully (depending on the order type), although the prices themselves are checked.

This means - a limit order would fill if the price crosses that level. We're however not checking if the volume for it is sufficient.
In reality - the order would fill partially - consuming this level of the orderbook.

The problem is - our orders don't have any market impact - so the next iteration we try to fill the same order again - at the same price - most likely against the same "other side" seller/buyer.
This would mean to fill hundreds of millions of USDT - we'd simply take a few iterations - but it would fill eventually. 
As this simulation therefore doesn't make sense - it's not implemented, and orders are assumed as "filled" fully once price crosses.

Market orders "walk up" the orderbook up to a slippage of 5% - and are assumed to fill at 5% past spot. If your order is too big for that - we'd assume this 5% slippage.

This is also described in the [dry-run](https://www.freqtrade.io/en/stable/configuration/#considerations-for-dry-run) documentation
