### ISSUE TITLE
Allow Backtest/Hyperopting execution logic to be the same as Live/Dry run

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#6984]
Hello,

I wanted to train an incremental/online learning model using [river framework](https://riverml.xyz/0.11.1/).

To do so, I would need backtesting and hyperopting command to have a parameter in command line to change bot execution logic to be the same as Live/Dry run - meaning that `populate_indicators` would not be call once for all but once per candle, and everything else would be updated accordingly. 

I know it would be much slower, but it's the only way I can think of to implement accurate online training.

I have some experience with python, so if you give me some indications on how to do it the best way, I might be able to do it and propose a pull request if it can help others.

Thanks in advance for your help/reply

**Comment by xmatthias** [comment]
It'll not be slower - it'll be dead slow. 
To realistically simulate live mode - you'll have to move through the candles step by step - so for a backtest of 10.000 candles, you'll have `10000 - (lookback)` iterations (lookback is usually 500 or 1000).
you'll be slicing the dataframe 9000 times - and then combining it 9000 times (only using the very latest candle of each iteration).

I'm very hesitant to provide this as builtin option - simply because it'll become dead slow - and provides very little benefit (if you run this for more than a few days on 5m candles, you'll not have the patience for it ...).

You should be able to accomplish this from within the strategy (so no need to modify freqtrade for this).
You can either use the decorator I've posted in https://github.com/freqtrade/freqtrade/issues/6586#issuecomment-1077933526  (fixing the issues pointed out in comments below - as my decorator is old and not well tested) - or simply use the logic and run the iteration within yourself.

**Comment by robcaulk** [comment]
What type of functionality are you ultimately seeking from this "river framework?"  We do have the [feat/freqai](https://github.com/freqtrade/freqtrade/pull/6832) branch which allows you to take an adaptive machine learning approach to backtesting/hyperopt. But you can decide how much effort to put into it by deciding how frequently the machine learning model should self-update. This means you can avoid this problem associated with backtesting/hyperopt becoming "dead slow."

**Comment by popperwin** [comment]
@xmatthias thanks for your reply and explanation. I'll look at the decorator you posted and may be test it; but as you said if it's "dead slow" I won't probably be able to train something with it.

@robcaulk Thanks for your suggestion and interest. My goal is pretty simple; it's to do incremental training at every new data incoming. River is really adapted to it so it was my first choice. 
I looked about  [freqai](https://github.com/freqtrade/freqtrade/blob/feat/freqai/docs/freqai.md) and it looks very promising, thanks for your contribution to the ecocystem! I'll  look more deeply at it since it's not exactly what I was looking for but it can be useful. Thanks.

**Comment by robcaulk** [comment]
@popperwin 
>> simple; it's to do incremental training at every new data incoming. 

That’s precisely what freqai is designed to let you do.
