### ISSUE TITLE
DRYRUN: Buy price higher than market price 

### ISSUE THREAD

**Issue by FlockrushAdmin** [freqtrade/freqtrade#7004]
## Describe your environment

  * Operating system: macOS Big Sur 11.2.3
  * Python Version: 3.9.7 (`python -V`)
  * CCXT version: ccxt==1.88.15 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-53e5483 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

In DRYRUN the buy price is higher than what is shown as the price in the Binance charts for ARPA/USDT pair. 

### Steps to reproduce:

  1. Please the the database order below. I checked UTC time zones as well and they are the same. 
  2. PAIR: ARPA/USDT
  3. UTC Time of BUY: 2022-06-24 06:01:37.000000
  4. BUY PRICE SHOWN IN DB: 0.04621 
  5. Actual high of candle observed on Binance: 0.04431 
  6. Variation: +4.2% 
  
### Observed Results:

  * The price of the buy is higher than the price. The volume for the 
  * The buy price shown in the database to be the same as the market price at the time of order 

### Relevant code exceptions or logs

Order Table row:

511 | 97 | buy | ARPA/USDT | 0 | dry_run_buy_1656050497.648718 | closed | ARPA/USDT | limit | buy | 0.04621 | 0.04621 | 39346.0 | 39346.0 | 0.0 | 1818.17866 |   | 2022-06-24 06:01:37.000000 | 2022-06-24 06:01:58.086488 | 2022-06-24 06:01:58.086491

**Comment by xmatthias** [comment]
> Market orders fill based on orderbook volume the moment the order is placed.

[source](https://www.freqtrade.io/en/latest/configuration/#considerations-for-dry-run)

What you experienced is expected behavior (up to 5%), and simulates how a real market order works.
If the orderbook is thin (or your order size is big compared to the marked you're working in), then a market order will push the price.
while we can't simulate pushing the market - we can consume the orderbook until the full volume is filled - simulating the slippage that would incurr at that point.

What this means is that to fill a volume of 39346 ARPA - it took several steps in the orderbook at the time of filling - which resulted in slippage of 4% (most likely more - the price is averaged based on volume).
freqtrade will cap slippage at 5% to avoid completely insane results - but a real order with this volume would - based on the market conditions  / orderbook at that time - also fill with this price. 

That's also not unrealistic looking at the orderbook right now - where a 2000$ order will push the market 6 orderbook steps.

To circumvent that i would suggest to avoid market orders alltogether (especially starting with a certain order size) - as they become dangerous / uncontrollable on markets with thin orderbooks.
You can instead use limit orders - most likely with price side "other" - and maybe with `order_book_top` set to > 1 - which will define the worst price acceptable to you.
By using "other" - you're effectively simulating market orders - but you still control the worst possible price - as i'd assume you'd prefer to have the order partially filled - rather than having it push the market by 4%.

obviously the [custom price callbacks](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-order-price-rules)  give you even more control - maybe controlling the acceptable slippage based on the pair / pair volume.

**Comment by FlockrushAdmin** [comment]
Thank you for the detailed reply. 

The volume on the candle was 21million, so 39K should not be an issue. The bigger issue as you can see in the attached chart is that the fill price was never reached by the pair. 

(PS. apologize to attach the chart, it's to help visualize the issue)

![Screen Shot 2022-06-28 at 1 15 42 PM](https://user-images.githubusercontent.com/64109384/176244168-c06e1494-eed9-4ef5-8d17-10f81839d07e.png)




> > Market orders fill based on orderbook volume the moment the order is placed.
> 
> [source](https://www.freqtrade.io/en/latest/configuration/#considerations-for-dry-run)
> 
> What you experienced is expected behavior (up to 5%), and simulates how a real market order works. If the orderbook is thin (or your order size is big compared to the marked you're working in), then a market order will push the price. while we can't simulate pushing the market - we can consume the orderbook until the full volume is filled - simulating the slippage that would incurr at that point.
> 
> What this means is that to fill a volume of 39346 ARPA - it took several steps in the orderbook at the time of filling - which resulted in slippage of 4% (most likely more - the price is averaged based on volume). freqtrade will cap slippage at 5% to avoid completely insane results - but a real order with this volume would - based on the market conditions / orderbook at that time - also fill with this price.
> 
> That's also not unrealistic looking at the orderbook right now - where a 2000$ order will push the market 6 orderbook steps.
> 
> To circumvent that i would suggest to avoid market orders alltogether (especially starting with a certain order size) - as they become dangerous / uncontrollable on markets with thin orderbooks. You can instead use limit orders - most likely with price side "other" - and maybe with `order_book_top` set to > 1 - which will define the worst price acceptable to you. By using "other" - you're effectively simulating market orders - but you still control the worst possible price - as i'd assume you'd prefer to have the order partially filled - rather than having it push the market by 4%.
> 
> obviously the [custom price callbacks](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-order-price-rules) give you even more control - maybe controlling the acceptable slippage based on the pair / pair volume.

**Comment by xmatthias** [comment]
You're mistaking candle volume with orderbook depth.

There is nothing wrong with attaching a chart if it helps the cause. Your screenshot (assuming it was taken correctly, with the mouse above the relevant candle) shows 399k volume, not 21M.


That price may have never been reached, but your order would have pushed the (momentary) price there, based on available orderbook volumes at that second.

Live prices will never react to your dry orders, so the market obviously didn't know about your order, sobthat price was not reached.
Would live have moved candle high? Definitely.
Would live price have stayed there? Or risen even higher? Maybe, market impact of your orders is difficult to predict, especially if your order size is 10% of the 1m candle.
