### ISSUE TITLE
Configurable percentage between desired and possible Adjusted stake amount

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7028]
## Describe your environment
(if applicable)

  * Operating system: Docker
  * Python Version: Docker (`python -V`)
  * CCXT version: Docker (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.5.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

What about to make a Configurable percentage between desired and possible Adjusted stake amount?
Sometime I need a more then 30% difference.
Or be able to disable this check in config file.
wallets.py:
```
            if stake_amount * 1.3 < min_stake_amount:
                # Top-cap stake-amount adjustments to +30%.
                if self._log:
                    logger.info(
                        f"Adjusted stake amount for pair {pair} is more than 30% bigger than "
                        f"the desired stake amount of ({stake_amount:.8f} * 1.3 = "
                        f"{stake_amount * 1.3:.8f}) < {min_stake_amount}), ignoring trade."
                    )
                return 0
```

**Comment by xmatthias** [comment]
If you think carefully what this check does - then your request does not make sense, and it's actually in the users / strategies interest to have this check in place (maybe even stricter ...).


assuming the minimum stake amount for a pair is 20USDT
Calculations (or your strategy) determined a stake amount of 10USDT - so the order cannot be placed.

the 20$ sample is a standard one, but we've seen cases where prices rose heavily, and the minimum stake was suddenly 50$ or more (i've seen one case where it rose to 80$ at one point, from 15$ 2 days prior for the same pair).
(minimum stake is a combination of "minimum base" and "minimum quote" - so the price does play a heavy role in this). 
It's therefore a protection for your capital to avoid going "all in" on one trade due to minimum tradable amount being too high.


I can see no reason why the 30% should be adjusted or even configurable (see below). if any, it should be reduced to 20% or even lower.

you can easily use the [custom_stake_amount](https://www.freqtrade.io/en/latest/strategy-callbacks/#stake-size-management) callback to adjust stake yourself from within the strategy. 
it's then up to the strategy to use a stake amount that's between minimum and maximum stake amount. this factor will not be an issue if you respected the limits already.
