### ISSUE TITLE
Recalculate stoploss after adjustment (DCA) orders

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7067]
## Describe the enhancement

What about to make possible to recalculate stoploss after DCA orders?
For example (very simplistic):
I have open long trade, buy 100coins by rate 100.0 with initial stoploss 0.5 (stoploss rate <= 50.0)
Price down to 75.0 and I open 2nd buy order (DCA), buy additional 100coins by rate 75.0.
After second order summary buy rate is 87.5. But stoploss will remain the same rate (50.0).
I need to recalculate stoploss level to new rate (i.e. 87.5 * 0.5 = 43.75 instead of 50.0).
This is especially important for short positions.
custom_stoploss() callback not suitable for this, because it can only lower the distance to stop loss.

**Comment by xmatthias** [comment]
This is currently not possible (and also not planned).

It's also quite clearly documented in the [order adjustment documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) (red warning box).

One generic rule we have for freqtrade is that stoplosses never move down (for longs) - and i don't see why DCA should be able to validate this. 
Your initial order lost 25% already - adding more to this is a odd approach - you should've probably exited already quite some time ago.

assuming you use a logic to "always buy when position loses 25%" (no further rule) - you'd have effectively disabled stoploss - as you've allowed the pair to go down all the way - as stoploss cannot be reached (you always buy more before it's reached).

**Comment by medenlin** [comment]
@xmatthias, you are true. but sometimes I really want to move the stop loss further away on short positions. And it could save the whole 'Trade' )))
Give us such a dangerous opportunity, please ;)

**Comment by stash86** [comment]
Use custom_stoploss if you want a moving stoploss, and set the hard stoploss to -1

**Comment by aleeepp** [comment]
Hi, I'm just playing with the stops :)

I have a question @stash86 @xmatthias ,

From what I read the stoploss can never go down.

**Example**:

hard StopLoss: -0.1
Purchase price: 100
Current price: 150
Position: Long

1) custom StopLoss: -0.05
2) custom StopLoss: -0.09

**Stage 1**:
Hard StopLoss price: $90
Custom StopLoss Price: $142.5

$142.5 > $90 ->> StopLoss set to $142.5

**Stage 2**: The strategy modifies the custom to -0.09 and the current price remains at $150

Hard StopLoss price: $90
Custom StopLoss Price: $136.5
StopLoss set: $142.5

$136.5 < $142.5 -> StopLoss is still $142.5 since the new one is lower.

**_If this example is correct there is no way to use DCA and move the stop down._**

Link: [https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position](url)
> The stoploss price can only ever move upwards - if the stoploss value returned from custom_stoploss would result in a lower stoploss price than was previously set, it will be ignored. The traditional stoploss value serves as an absolute lower level and will be instated as the initial stoploss (before this method is called for the first time for a trade), and is still mandatory.

**Comment by xmatthias** [comment]
The documentation is pretty clear about this (see above link), and this is expected behavior.

A stoploss thats allowed to move down is not a stoploss, as it could never be hit, you could simply move it down in parallel with price, causing 100% loss.

If you assume youre going to dca at -10%, then your stoploss should never be at -5% in the first place, as thats not your strategy, and you'd not allow it to be hit anyway.

**Comment by aleeepp** [comment]
Thank you very much for your answer @xmatthias  :)

I understand and it seems perfect to me that the stop has a limit.

What I see is that the DCA model loses a lot of value by not having a soft stop for this case.

Maybe you are down -5% on the first buy, but the whole position maybe -0.3% real due to efficient buy management.

In my head it makes total sense to have a stoploss where it is dynamic to the purchases that I am making, for example a maximum of 4 purchases each time the position is -3%. If after 4 purchases the position (considering the average price) is -6%, the stop is executed. Where would be a stop to the entire position, not in relation to the first purchase.

**Comment by xmatthias** [comment]
Then its not a stoploss. You should br able to build what you desire with custom_exit. Your strategy decides when to exit, but youll still have the security of a hard stop below this, shuold your logic fail.
