### ISSUE TITLE
hyperopt command doesnt support --timeframe-detail 

### ISSUE THREAD

**Issue by abbaselmas** [freqtrade/freqtrade#7070]
## Describe the enhancement

In backtesting there exist --timeframe-detail parameter which is very usefull if you use trailing stop. Backtesting results become more realistic. However, hyperopt command doesnt support --timeframe-detail parameter.

Is it possible to add --timeframe-detail parameter to hyperopt also?

I know it will become more resource hungry but more realistic.

**Comment by xmatthias** [comment]
that's correct and intentional as is.
it would be possible to add it i guess - but memory will be killer (which is why it hasn't been added so far).

As memory is already a huge problem with hyperopt - using `--timeframe-detail` will only make this (a lot!) worse. Unfortunately, memory problems are very non-verbose by nature (it's the system that simply kills a process) - so these are already pretty difficult to debug.

it'll have to be very well weighted against the drawbacks this would have - especially for users not familiar with memory errors - which will require more support through that.

That said - you can obviously try to add the parameter to the configuration (`timeframe_detail`) and hyperopt with that - while i didn't test this, i think the loading-mechanics should be in place.

**Comment by abbaselmas** [comment]
Thank you for your quick and in detail response.
I have tested the ```timeframe_detail``` parameter in the config file with hyperopt command.
It worked as expected.
