### ISSUE TITLE
@informative - Duplicate column name date exists in dataframe

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#7095]
Trying to backtest some example strategies using `@informative` and this piece:

```python
@informative('1h', 'BTC/{stake}', '{column}')
def populate_indicators_btc_1h_2(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe['rsi_fast_upper'] = ta.RSI(dataframe, timeperiod=4)
    return dataframe
```

give the error:

`freqtrade - ERROR - Duplicate column name date exists in dataframe! Ensure column names are unique!` 

## Describe your environment

  * Operating system: MacOS Monterey
  * Python Version: 3.10.5 (`python -V`)
  * CCXT version: 1.90.41 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-6ef9029 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
How do I need to use that pice of code, is not clear from documentation?

Thanks.

**Comment by xmatthias** [comment]
The problem here is the usage of the 3rd argument, `'{column}'`.

By using this, you're saying "keep column names as is" - which means that the columns will be kept as "date", "open", "high", "low", "close", "volume", "rsi_fast_upper").

This is problematic, as each of the first 5 columns (date, open, high, low, close, volume) already exist in the main dataframe.

you could for example use `'BTC_{column}'` - which would rename these columns to "BTC_date", "BTC_open", ... - and would make them unique (obviously assuming you only use such a method once).

Alternatively, `'BTC_{column}_{timeframe}'` would name them as "BTC_date_1h", (1h is also dynamic and will depend on your selected timeframe for this informative pair) ... - again, making them unique.

using `'{column}'` alone is the problematic point - which will simply keep the name "as is". This is obviously also problematic for further use "down the road/strategy" - as you'd no longer be able to identify which column is which - as names are duplicated (pandas allows this iirc, but freqtrade does not, as you'll then no longer be able to reference them cleanly).

**Comment by botzill** [comment]
I see, I just found this example here: https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/multi_tf.py#L79, I guess we can change the example as well to not be confusing?

**Comment by botzill** [comment]
Here https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/multi_tf.py#L103 as well stake needs to be lower case.

**Comment by xmatthias** [comment]
Thanks for pointing this out - I've now updated this to make more sense.

**Comment by botzill** [comment]
thanks @xmatthias 

should be as well

`stake = self.config['stake_currency'].lower()`

**Comment by Finesse** [comment]
There is still a broken example [in the docs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative):

```python
    # Define BTC/STAKE informative pair. A custom formatter may be specified for formatting
    # column names. A callable `fmt(**kwargs) -> str` may be specified, to implement custom
    # formatting. Available in populate_indicators and other methods as 'rsi_upper'.
    @informative('1h', 'BTC/{stake}', '{column}')
    def populate_indicators_btc_1h_2(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi_upper'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe
```

**Comment by xmatthias** [comment]
@Finesse Great spot, thanks - fixed in develop (commit should be linked here, too).
