### ISSUE TITLE
plotting trades to Trading View

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7111]
Interesting feature to have in the future: the ability to export a script for TV so that the trades the bot took are displayed there. 
Sample strategy file: https://stackoverflow.com/questions/65203672/how-can-i-plot-my-historical-trades-executions-in-tradingview-the-same-way-as-in
Idea: https://kinfo.com/automatically-plot-any-trade-in-tradingview/

**Comment by xmatthias** [comment]
Using trading-view with other tools that are not trading-view based is a very dangerous approach.

We've had multiple occasions in the past where Tradingview indicators are calculated different to their ta-lib (or other indicator library) counterparts.
usually, the result was either that ta-lib implemented the indicator according to the original paper, and trading-view deviated from that slightly - or that we couldn't figure it out and most likely tradingview is using some different EMA calculation method internally. 
As it's not open source (for builtin indicators) - you can't really find out how it'll calculate things.

Now the big problem is - differences are often too small to spot immediately - but it can mean a missed indicator cross - or slightly different numbers.

You'll then wonder why some trades were made (or were not made) - while in reality looking at indicators that were calculated slightly differently.

FreqUI prevents this problem by using the indicators / indicator values calculated by the strategy - and therefore showing you the same thing the bot sees (which would not be possible with tradingview as far as i know).

---

I'm potentially willing to accept a very well PR for this if you're able to make an implementation (fully covered with tests) in 10-20 lines - including a clear and loud warning about the above potential misalignment of indicators - but otherwise this is not something we'll be adding to freqtrade for the above reasons.

**Comment by vaidab** [comment]
I understand the issue, I've confronted myself with fitting indicators to work identically on both sw. I think that the situation that you've so very well detailed would just continue even if we plot the trades (indicator differences, etc) and it's just better to use the webserver / plotting for now.
