### ISSUE TITLE
should_sell function should check buy signal first

### ISSUE THREAD

**Issue by timhilliard** [freqtrade/freqtrade#713]
https://github.com/gcarq/freqtrade/blob/b0536dba0b2265202851d264045e4679497d76cc/freqtrade/analyze.py#L174-L177

The comment mentions it should check but the code never does.

**Comment by xmatthias** [comment]
if i understand you correctly, you would propose to change the logic to prefer sell-signal over ROI(assuming point 2 really is "if use_sell_signal is false")?

* stoploss is the first to be checked (within min_roi).
* then comes min_roi
* then checking for `sell_only_profit` (which makes sense here - as you want stoploss to still apply
* last is `sell-signal`

The logic is not really that different than the above (assuming point 2 really is "if use_sell_signal is false" - as otherwise it does not make sense to me).

**Comment by yaotian** [comment]
misunderstood. Ignore my post. Sorry.

**Comment by xmatthias** [comment]
Closing this issue as i think it was a misunderstood comment.

**Comment by timhilliard** [comment]
Sorry for not responding earlier, github was being funny for me and not showing this thread before. Anyway the point I was trying to make is if the buy signal is still active we shouldn't sell which means the check for the buy signal should be the first conditional check in the function.

**Comment by xmatthias** [comment]
Interresting idea - 
you would like to ignore ROI if sell-signal is still present - i guess this could maximize profits given the right strategy...

i personally wouldn't ignore neither stop-loss or sell-signal - if both buy and sell-signal are present then the strategy is bad - and if it's at stop-loss - it's probably the same.

**Comment by timhilliard** [comment]
It's not so much that I want to maximize profits, although that is a good side effect, it's that I also want to make sure we do not end up buying the same stock again straight after we sell it because the buy signal is still active also avoiding extra unnecessary fees.

**Comment by timhilliard** [comment]
A better enhancement might be to sell on the sell signal and then settings a timeout before the same crypto can be bought again.

**Comment by xmatthias** [comment]
i think that can lead to lower profits - assuming there is a sell-signal - and 2 ticks after a buy-signal with a strong upwards trend ... which the strategy would have detected - but the timeout prevented it from buying...

**Comment by xmatthias** [comment]
i'll close this as #942 has been merged, which addresses the initial intent of this issue.
