### ISSUE TITLE
Is it possible to use freqtrade only for informational purposes

### ISSUE THREAD

**Issue by mihastele** [freqtrade/freqtrade#7152]
Is it possible to only use it for informational purposes, like for example that freqtrade notifies you when price goes up for certain percentage, or to store values and graphs for analytics? I could use it in dry-run though, but that is an overkill for what I want, because of the trading robot process.

So in general I want to know these 2 things:
- is it possible to only get notificiations rather than trading
- despite the first question being yes or no, is it at least possible to store telegram notifications into file and how to do that in a simple way, that would be useful for analytics

Thank you in advance for your time and effort in this project.

**Comment by xmatthias** [comment]
This is not a usecase we're supporting, or which we aim to support.
Freqtrade is a trading bot. 

While i guess you can code something in the strategy to send the messages (using develop you can now [send notifications from the strategy](https://www.freqtrade.io/en/latest/strategy-customization/#send-notification)) instead of providing signals - you'll still have the whole trading bot process in the background - which you don't  don't need. 

for 2: freqtrade will not allow you to store telegram notifications (this is again not something we aim to support, nor makes sense for freqtrade).
The notifications are not really relevant, it's the trades - where information is available.

**Comment by mihastele** [comment]
Thank you for the response, I appreciate it 😊
