### ISSUE TITLE
Installing numpy on raspbian buster

### ISSUE THREAD

**Issue by RoboTechy** [freqtrade/freqtrade#7153]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi there
I am having a problem with installing numpy on my raspberry pi 4. I really appreciate it if someone could help me to figure it out
while trying to install numpy on raspberry pi 4 (as a step of installing opencv) I face this error:
 ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

Thank you in advance

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
> as a step of installing opencv

If you're trying to install opencv and encounter problems with numpy, please use the corresponding support chanels for help.
we'll not provide generic installation help for random installation issues just because we happen to use one of the dependencies.

Usually - using a 3rd party package index like piwheels.org will help you with installation issues by providing pre-built wheels.
