### ISSUE TITLE
MaxDrawdown protection triggered on winning trade

### ISSUE THREAD

**Issue by andrijasinski** [freqtrade/freqtrade#7170]
## Describe your environment

  * Operating system: Docker
  * Python Version:  3.10.5
  * CCXT version: 1.89.14
  * Freqtrade Version: 2022.6
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi! I am using `MaxDrawdown` protection and I have noticed that if a winning trade closes **when** there is an active lock by protection, then the protection will get triggered again. Is this expected behavior? I will add screenshots for better visualization.

### Steps to reproduce:

  1. Setup a `MaxDrawdown` protection
  2. Protection triggered and lock is added
  3. Have a winning trade before lock is expired
  4. Protection should get triggered again.

  
### Observed Results:

  * What happened?
    * Protection got triggered after a winning trade
  * What did you expect to happen?
    * Protection not triggered

### Relevant code exceptions or logs
<img width="544" alt="Screenshot 2022-08-03 at 14 44 04" src="https://user-images.githubusercontent.com/32611353/182600573-5b0b1547-d579-430b-bf86-9e8053c30a26.png">

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by andrijasinski** [comment]
![IMG_5599](https://user-images.githubusercontent.com/32611353/182601668-0d7bf31e-d0fc-4b09-94b3-b7dfabf79059.jpg)
![IMG_5600](https://user-images.githubusercontent.com/32611353/182601688-df09230a-6e55-4251-b2e4-75ebc2e6582f.jpg)

**Comment by andrijasinski** [comment]
![IMG_5599](https://user-images.githubusercontent.com/32611353/182601782-5118183a-b04a-4077-8d6a-e61d551be1de.jpg)
![IMG_5600](https://user-images.githubusercontent.com/32611353/182601786-a4e845fb-778b-4eed-a4dc-7370c9cca6eb.jpg)

**Comment by stash86** [comment]
I assume you had a big loss before that rocket?

**Comment by andrijasinski** [comment]
Yes, here is the trigger moment after the loss

<img width="538" alt="Screenshot 2022-08-03 at 15 29 34" src="https://user-images.githubusercontent.com/32611353/182608064-bfa7c99f-6bb6-4408-b242-17054fdfdb81.png">

**Comment by xmatthias** [comment]
Well the protection doesn't really care about individual trades / individual trade results - but about the drawdown within the X (2789 in your case) minutes (which seems overly specific, and is most likely overfitted - but that's a different topic).


It'll trigger if the drawdown (within the defined period) is below the threshold - and if the "until" value is different (which it will usually be - as the new lock will have a longer duration).

Drawdown within a period will as such not only depend on a single trade - but also on prior trades. 
In unfortunate situations, this can mean that it'll retrigger on a winning trade - but that's not per se wrong - as the new lock time is different - and the drawdown is still below the defined threshold.

---

The real problem here is with your parameters - 0.039 (3.9%) drawdown with a stoploss of 8% will mean that you'll be down more than 2x the allowed drawdown with a single stoploss. 
It'll therefore act similar to a "stoploss" protection - with 1 stoploss locking all pairs for an extended period of time.

You may hit 2-3 stops in a row in crash situations - so "recovery" takes quite some winning trades (or waiting until trades age out).

Ideally - the drawdown should be > stoploss (most likely more than 2x stoploss) - allowing "a few" stoplosses before you trigger this protection.

**Comment by andrijasinski** [comment]
Thank you for the answer :)
