### ISSUE TITLE
Hyperopt search space constraints

### ISSUE THREAD

**Issue by taebow** [freqtrade/freqtrade#7189]
## Describe your environment
(if applicable)

  * Operating system: Archlinux
  * Python Version: 3.10.5
  * CCXT version: 1.91.29
  * Freqtrade Version: 2022.7

## Describe the enhancement

Hi there, I'm a bit new to using freqtrade, about 1 week now, running backtesting and hyperopt mostly, please be kind with me if this idea is not relevant and can be easily solved without changing some core features.

Here is the point, I think having a constraints mechanism on the search space, could improve and reduce the time of searching for the best combination of parameters. I know that the current implementation is using `skikit-optimize` and that a PR on this project is already ongoing ([https://github.com/scikit-optimize/scikit-optimize/pull/971](https://github.com/scikit-optimize/scikit-optimize/pull/971)) but for some months now... Also maybe this issue could serve as a reminder to integrate this feature once it has been implemented in the dependency. 

Here is a simple example, with 2 integer parameters:

```
fast = IntParameter(1, 100, default=50)
slow = IntParameter(2, 101, default=51)
```

If we say that the constraint `fast < slow` is needed for the space to be valid, with this mechanism we could reduce the space search considerably and reject the attempts that don't satisfy these constraints, and so this would end up for the optimizer to not run backtesting when `fast > slow`.

**Comment by xmatthias** [comment]
As you correctly point out - there's a PR on scikit-optimize to provide support for this available (although not yet merged).

Because of that, all work we'd be doing for this would be a waste of time - as it'd be duplicating their efforts - although in a definitely slower way - as the optimizer would still need to generate the points - which we then reject based on the condition.

Generating the next point is however a pretty slow process (it's single-core due to some scikit-learn limitations) - and usually takes the most time between backtesting runs).

Please understand that we'll not be implementing features based on impatience (to wait on a PR completion in an upstream project) unless it's fixing a crucial bug for freqtrade.
