### ISSUE TITLE
Limit orders fills 

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7191]
* Operating system: __Docker__
  * Python Version: ___3__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ___docker-4c68bec1_ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
===
I'm not sure which of the below is applicable in my case. I'd like to set a specific time for the entry limit order to be canceled if not filled. I've found in the documentation

**unfilledtimeout.entry

or 

order_time_in_force**

Do I need to change one or both of those settings for proper execution? 
Are those supported on all exchanges for both sides? I've seen there are some restrictions for the second parameter.

The second question is just to confirm if my understanding is correct 

According to this config

```
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 3,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
...
"unfilledtimeout.entry": 30
```

When the entry_long validates to 1 and price for example is 

...
103
102
101  # ask
-------------Current Spread
99   # bid
98
97
...

Then the limit buy order will be sent to exchange with the entry price of 97?

If the price will not reach 97 within 30 minutes the order will be canceled? 

Do I need to change order_time_in_force for this to take place?

**Comment by xmatthias** [comment]
`order_time_in_force` support will depend on the exchange - but has nothing to do with timeouts per se.
It's a type of order - which can for example force an order to be filled fully immediately (otherwise it'll be cancelled) (FOK) (default is GTC - or Good Til Canceled).


"unfilledtimeout" is exchange independent, and will depend on freqtrade to cancel the order actively if it didn't fill.
The proper way to configure `unfilledtimeout.entry` is as follows - and is the time from order placement, either in minutes (default) - or in seconds (if "unit" is defined and set to "seconds").

```
"unfilledtimeout": {
"entry": 30,
"exit": 1,
...
}
```

if you need more fain-grained control about order canceling, you can code your own logic as part of the [custom order timeout rules](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-timeout-rules).

**Comment by darioneto** [comment]
Thanks, this program is very versatile which is awesome. I was wondering if iceberg orders are supported out of the box ?

**Comment by darioneto** [comment]
I'm still not sure if this is working correctly. The bot just sent short limit order to the market however I was expecting to see the difference between the open and current price with this config 

```
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 25,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
```
I can see the order is reported via telegram as 
Open Rate: 22977.90000000
Current Rate: 22977.90000000

Shouldn't this be different with the  "order_book_top": 25," ?

**Comment by darioneto** [comment]
Ok maybe some cosmetic issues with the first telegram message. When I click on the "/status" the current rate is different indeed. The format of the second message looks slightly different but seems to show correct values more less 

Open Rate: 22977.90000000
Open Date: 2022-08-07 11:17:49
Current Rate: 22971.90000000

**Comment by xmatthias** [comment]
Well the "current rate" for entry notifications is determined the same way than the entry price for the order - so it'll have the same, 25 spot offset in the message.

the difference to /status is that this is using the exit variant - which will have a different configuration.
