### ISSUE TITLE
Dry Run mode. Order did not close on quick market change

### ISSUE THREAD

**Issue by farmage** [freqtrade/freqtrade#7255]
## Describe your environment

  * Operating system: Ubuntu 18.04.6 LTS
  * Python Version: 3.9.13 (`python -V`)
  * CCXT version: 1.91.93 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.8.dev-96cfe1471 

## Describe the problem:

The situation repeats over and over in such market conditions. If the price changes quickly in one long candle and closes far out of the "stop_loss" condition, the position will "hang" with the ** mark forever. Configuration was set to exit on limit price, but real exchange on futures works with the "price less than" condition. So it should just close the order after the price goes out of the scope. "stoploss_on_exchange" parameter doesn't make the difference. The only solution is to exit the order by "force_exit".
I know, the dry run mode is not very important, but during collecting trades statistics such a situation spoils all the data.
This happens only in dry run mode. Real trading with the same configuration works well.

### Steps to reproduce:

  1. Create any strategy
  2. Start it on dry run mode
  3. Wait for a "squeeze" on the market that crosses your stop loss price
  
### Observed Results:

  * What happened?
  Order will stay not closed and marked as ** 
 For example:
```
Trade ID: 758 (since 10 hours ago)
Current Pair: IMX/USDT
Direction: Long
Leverage: 25.0
Amount: 2608.0 (100.022016 USDT)
Enter Tag: long_cross_poc
Exit Reason: stop_loss
Open Rate: 0.95880000
Open Date: 2022-08-18 19:10:15
Current Rate: 0.88700000
Current Profit: -187.76%
Stoploss: 0.94154160 (-45.00%)
Stoploss distance: 0.05454160 (6.15%)
Open Order: (limit sell rem=2608.00000000)
  
Entry #1:
Entry Amount: 2608.0 (100.02201600 USDT)
```
So, as you see it's not filled at all

  * What did you expect to happen?
  
Real trade on the exchange closes the order on stop loss without any problem with the same configuration

### Config

```
{
  "max_open_trades": 3,
  "stake_currency": "USDT",
  "stake_amount": 60,
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "dry_run": false,
  "cancel_open_orders_on_exit": false,
  "trading_mode": "futures",
  "margin_mode": "isolated",
  "unfilledtimeout": {
    "entry": 10,
    "exit": 10,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },

  "order_types": {
    "entry": "market",
    "exit": "market",
    "emergency_exit": "market",
    "force_exit": "market",
    "force_entry": "market",
    "stoploss": "limit",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99
},

  "entry_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1,
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },

  "exit_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1
  },
  "exchange": {
    "log_responses": false,
    "name": "binance",
  }
}
```

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-08-19 04:49:11 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_cancel, 'trade_id': 758, 'exchange': 'Binance', 'pair': 'IMX/USDT', 'leverage': 25.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0, 'order_type': 'market', 'amount': 2608.0, 'open_rate': 0.9588, 'current_rate': 0.88, 'profit_amount': -2501.05051008, 'profit_ratio': -25.0, 'buy_tag': 'long_cross_poc', 'enter_tag': 'long_cross_poc', 'sell_reason': None, 'exit_reason': None, 'open_date': datetime.datetime(2022, 8, 18, 19, 10, 15, 857340), 'close_date': datetime.datetime(2022, 8, 19, 4, 49, 11, 811509, tzinfo=datetime.timezone.utc), 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'reason': 'cancelled due to timeout'}
2022-08-19 04:49:12 - freqtrade.freqtradebot - INFO - Exit for IMX/USDT detected. Reason: stop_loss
2022-08-19 04:49:13 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=758, pair=IMX/USDT, amount=2608.00000000, is_short=False, leverage=25.0, open_rate=0.95880000, open_since=2022-08-18 19:10:15)
2022-08-19 04:49:13 - freqtrade.wallets - INFO - Wallets synced.
2022-08-19 04:49:13 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 758, 'exchange': 'Binance', 'pair': 'IMX/USDT', 'leverage': 25.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.9415416, 'order_type': 'limit', 'amount': 2608.0, 'open_rate': 0.9588, 'close_rate': None, 'current_rate': 0.8812, 'profit_amount': -45.62618671, 'profit_ratio': -0.45607022, 'buy_tag': 'long_cross_poc', 'enter_tag': 'long_cross_poc', 'sell_reason': 'stop_loss', 'exit_reason': 'stop_loss', 'open_date': datetime.datetime(2022, 8, 18, 19, 10, 15, 857340), 'close_date': datetime.datetime(2022, 8, 19, 4, 49, 13, 416097), 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
  ```

**Comment by xmatthias** [comment]
> Configuration was set to exit on limit price, but real exchange on futures works with the "price less than" condition

You're miss-reading how real exchange stoploss works.
While the condition is "Price less than" - it's still a stop-limit order (which takes 2 prices).

Let's explain this via an example:
The first price (say 100$) defines after which point the stop triggers 
the 2nd price (by default placed 1% below the first price on freqtrade - can be controled via `stoploss_on_exchange_limit_ratio`) is then the limit order that's placed (in this example, at 99$).

If the market now moves from 101$ directly to 98$ (that's a 3$ gap) - what will happen is:
the stop order triggers, which creates a new limit order with a sell price of 99$ on the exchange.

As 99$ is above the current price of 98$, this order will not fill immediately - but will wait for price to come "back" to the 99$. (basically - your stoploss failed).
Binance does not support stop-market orders - so the only solution to this is to play with `stoploss_on_exchange_limit_ratio` - setting that lower (you're defining the maximum loss _on top of_ the stoploss you're willing to take to have the order fill).

This is not limited to freqtrade either, as the same behavior will apply when trading via the exchange website and using a stop-limit order there.

Because of the above - the behavior of freqtrade in dry-run is really aligned to how real exchanges behave - especially when using (or being forced to use) stop-limit orders.


For dry-run, one solution can be to configure "stoploss" as "market" order (leaving stoploss_on_exchange off) - which will guarantee a fill at whatever price it'll fill (obviously also at a greater loss than the real defined stop).

Your configuration is at any rate odd - as you're using market orders (you accept whatever price) for all order types except stoploss - where using market orders would probably be the most important point.

**Comment by farmage** [comment]
Thank you for the detailed explanation! I didn't spend much time learning the limit ratio parameter. It can be helpful.
I'll try to switch the stop_loss to "market" in the dry run mode. For the real exchange trades, I choose the limit stop, because I want to have some kind of guard on the exchange side to handle orders in emergency market conditions.

**Comment by xmatthias** [comment]
> For the real exchange trades, I choose the limit stop, because I want to have some kind of guard on the exchange side to handle orders in emergency market conditions.

That's not wrong - but a stop-limit (the only stop order type binance offers) is not a 100% guarantee of exit. 
It's an awareness topic more than anything - and if you're hunting in low-volume markets - something to potentially tune to higher values to increase the security you'll get from it.
