### ISSUE TITLE
Gathering out possible pairs, which causes the bot to stop

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7256]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8.dev (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

In ticket 7250 you gave me the information, that freqtrade.commands.trade_commands - ERROR - 'last' could have something to do with specific pairs. Many thanks for this. I think, you are right: Those bots which stopped have been on gate.io with stake currency USDT. Gate.io bots with stake BTC and ETH, as well as FTX tockenized stocks bots, didn't stop.

I have not really understood, how I can eliminate and even avoid this issue for the future entirely. Has it something to do with my constant incrementation of the AgeFilter? I increment it frequently, because I don't want new pairs, which behavior I don't know.
How can I gather out a possible pair, which causes the bot to stop? Over night I have put all pairs on the blacklist. And on VolumePairList: "number_assets": 0, I even pushed stopbuy (not really necessary). Like this none of the bots stopped until now.

A pair, which has had no trade within the last 24h, you told me. What exactly do you mean by this?
I thank you for your help. Tell me, if you need any further information.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
> A pair, which has had no trade within the last 24h, you told me. What exactly do you mean by this?

'last'  contains a price - usually the price of the last trade that happened on the exchange.
i've however seen on several exchanges that "0 volume pairs" (pairs without a trade in the last 24 hours) don't have "last" set / don't provide "last".
Now the duration after which this value times out is dependent on the exchange itself (could be 24h, could be 1h) - and should be in the respective API documentation (assuming they provide good / accurate documentation)

The problem of 'last' usage in the PrecisionFilter has been fixed in #7250 - so with the latest develop version this won't happen anymore.
It'll also contain a log message ("Removing because last is empty or similar") showing you which pair was causing this (it'll however also be removed by the PrecisionFilter). 

As this is not asking anything new over #7250 - i'll mark this as duplicate and will close this.

**Comment by myNextCoder** [comment]
I thank you :) and I also thank you for having fixed the PrecisionFilter issue after ticker #7250. I will update immediately. In fact I use PresionFilter, since I had some 'deep' SLs with very low pairs.
I hope I have understood correctly, that one of the concerned issue is (only?) with 0 volume pairs. If yes, this part of the problem should be eliminated, since I use quoteVolume in PairListFilters, and then I only take the top pairs. That's why I think, 0 volume pairs are eliminated early enough.

**Comment by xmatthias** [comment]
well - it's either limited to 0 volume pairs - or a bug in the exchange API where 'last' is not issued (or a bug in ccxt - which doesn't seem to be the case though, at least not in the current version).
