### ISSUE TITLE
Adding psycopg2-binary to the main image

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7281]
Any chance the psycopg2-binary==2.9.3 can be added to the list of dependencies with the main version of the Docker image?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Freqtrade's main sql driver is sqlite.
For the moment, we'll not be adding postgres, mariadb, or any other sql driver.
It'd bloat the image, where most people won't need it.

Also, since we're relying on sqlalchemy, freqtrade should also run fine on mariadb, mssql, oracle, ... - so in theroy, have to install all drivers to all images.
As such - this would know/have no limit.

Doing a custom image with custom dependencies [is easy ](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose) - and when it's built with `docker-compose build --pull` - it'll also always use an uptodate upstream image.

**Comment by darioneto** [comment]
Apologize for skipping the template. Assumed this was not related to the question as it's very generic. Since I moved to k8s it would be much easier to switch the tags in the manifest. 
I build those images locally and upload them to the repo which is a bit cumbersome. Just thought it would make more sense to include also psycopg2 while having already support for sql flavor db and sqlalchemy dependency.

**Comment by TheDon27** [comment]
I would also be very interested in this being added to the main image!
