### ISSUE TITLE
Dry Run test during LIVE to help decide when to enter real trade.

### ISSUE THREAD

**Issue by JhorAVi** [freqtrade/freqtrade#7300]
The idea is to always run a DRY test in the background along with the LIVE bot in order to get a better overview of the market safety before entering a LIVE trade.

a. DRY bot is preferably a simple buy signal volume trader just enough to get a better overview of the market safety.
b. If LIVE bot gets a buy signal, if first checks the DRY bot results. If there are too much blood from DRY then it cancels the LIVE trade entry.
c. On the other hand if DRY produces constant wins then LIVE can activate buy signals good for uptrend.
d. I used live trading as an example just to emphasize my point but the idea could also be applied in pure dry and backtesting.

* I got the above idea from observing very simple strats against more sophisticated strats. There are successive days where the simple strat is making impressive results while the sophisticated strat is half sleeping. If only there's a way for the simple strat to signal the sophisticated strat like, "Hey dude, weather is fine here. Join me fishing!"

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
This is also true even if you think it's not relevant - as it sparks good practice - otherwise you'll forget or delete it when it would be needed - leading to pointless back and forth.

---

Edge does something similar - running "in-line" backtests (or reduced backtests) to determine a pair's past performance, deciding if it should be kept in the pairlist or not.

That approach makes more sense than what you're suggesting - if a simple strategy is successful - why not run that strategy instead (if the complex strategy is sensitive to market regiment), or combine the 2 strategies into one.

Your problem is that once you know "today is a good day for trading, my last x simple trades were successful" - you're already late to the party.
obviously there's market situations where it's easier to make money, and other situations make it more difficult.
Once you know how a simple dry-run bot performed that day though - the situation could've changed already (it most likely did).

for a simple approach - this can be pretty easily implemented in a strategy - with a simple dry-run strategy running, and writing a "flag" to a file whenever "the weather is fine".
You can then have another strategy read that flag and use it as guard to see if you should be entering trades.

---

I don't see this as something that will be implemented into freqtrade though. 

The complexity this would bring for the codebase (and as such - the increased maintenance effort) will not be justified by the outcome.

**Comment by stash86** [comment]
or you can get case like "simple strat get 5 BLZ wins, then your live bot joined in, only to get the big red dump trade". Past is never future. When your dry bots won all those trades, there is chance that the good time for trade is over, and the rest will be red dump time.

As matthias said, edge does something like that, but in my experience, that just make you join the party too late.

**Comment by stash86** [comment]
what you can do is use API endpoint. When simple bot get x good trade, send /start signal to live bot, otherwise send /stop signal. Use custom dict to store the winning count maybe, and put the trigger inside confirm_trade_exit

**Comment by xmatthias** [comment]
> what you can do is use API endpoint. When simple bot get x good trade, send /start signal to live bot, otherwise send /stop signal. Use custom dict to store the winning count maybe, and put the trigger inside confirm_trade_exit

i'd personally rather use `/stopbuy` for this instead of `/stop` - as that will keep the bot running - still handling open trades (which `/stop` will not!).

**Comment by stash86** [comment]
I assume when the market goes bad, they would want to /forceexit all, hence /stop seems enough, and they won't need to reload the bot to start trading.

but your advise /stopbuy do works for all scenarios, /forceexit or not
