### ISSUE TITLE
Debugging Issue

### ISSUE THREAD

**Issue by williehk** [freqtrade/freqtrade#7316]
I have Telegram endpoint enabled in config, the bot runs on a tethered 4g connection for testing, it sometimes got disconnected and then the telegram endpoint seems to get stuck and becomes unresponsive; the telegram commands won't work but no errors in log or exceptions emitted. There are no errors in the log but constant heartbeats like below:
2022-08-29 10:05:23,758 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.7', state='RUNNING'

I notice the sqlite-shm and sqlite-wal filelocks keep flashing in and out and it looks like it is constantly retrying, how do I go by debugging issues like this? tks.

**Comment by xmatthias** [comment]
sqlite-* files are mostly irrelevant - that's just temporary, uncommited data from the database - not related to telegram. I assume the files will disappear once no transaction is in place - but never really verified.

Telegram itself is using long-polling - which means it attempts a request - and the server doesn't return the request until there's new data.
I think we're using something around 30s for this - but obviously network disconnects may cause this to either hang for longer.
It should however reconnect  (and show up in the logs iirc) - unless the error happens at startup, at which point telegram would not be loaded at all.

to debug this - you might consider changing the line in `loggers.py` for telegram to debug - which should enable debug-logs from the telegram library.
I'm not entirely sure if that will give you the info you expect (long time i had to debug telegram problems).

That said - IF it's a telegram problem - it'll most likely have to be fixed in the telegram library.
freqtrade has no info if telegram is still successfully connected - and i'm not sure that's even possible to get without some hackery.

**Comment by williehk** [comment]
Okay thanks for the tips. I had similar issue with a chatbot on telegram. Its bit time consuming to figure out since it's not persistently reproduceable and its only in dev environment, did some tests changed the backend to a Nodejs webhook and the problem went away. never bothered to rewrite the thing since the it's intended to be put in the cloud. Thanks anyways. :>
