### ISSUE TITLE
Another exit_reason for custom_stoploss() callback

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7320]
## Describe the enhancement

In my experience, stoploss setted in `custom_stoploss()` callback have a "trailing_stop_loss" value as `exit_reason`.
Is it possible to do something else (for example "custom_stoploss" value), or better yet a custom value (as in `custom_exit()` callback)?
This would be useful if the strategy has several different options for setting a custom stop loss.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

No, this is not possible.
you should not use trailing-stop in combination with custom_stoploss anyway (the two would compete with each other for the shorter distance to current price).
As such, whenever you use `custom_stoploss()` - you can rely on trailing_stop_loss to be caused by your custom stoploss.

as custom_stoploss does however only set the stop price (it's not an immediate sell reason) - it'll not be setting the exit reason - as the exit could come hours, days, or maybe never (not from this exit reason, anyway).

**Comment by medenlin** [comment]
Ok, thank you!
