### ISSUE TITLE
Setting enter_long/enter_short to 0 still enters trade

### ISSUE THREAD

**Issue by froggleston** [freqtrade/freqtrade#7336]
## Describe your environment

  * Operating system: Windows 10, WSL2, Ubuntu 20.04
  * Python Version: 3.8.10
  * CCXT version: 1.92.98
  * Freqtrade Version: freqtrade 2022.9.dev-b53791fef
  
## Describe the problem:

I have normal entry conditions that set enter_long / enter_short to 1, and then "cancellation conditions" that set the enter_long / enter_short to 0.

However, instead of seeing no buys using these rejected conditions, I see entries with the "rejected" tags which shouldn't be there at all as the enter_long/enter_short column is set to 0.

### Steps to reproduce:

```
def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
    df.loc[:, 'enter_long'] = 0
    df.loc[:, 'enter_short'] = 0

    df.loc[
        (
            (
                (df['bull'].shift(1) == False) &
                (df['bear'].shift(1) == False) &
                (df['bull'] == True) &
                (df['close'] < df['good_close']) &
                (df['rsi'] < 30)
            )
        ), ['enter_long', 'enter_tag']
    ] = 1, 'frogbuy1'

    df.loc[
        (
            (df['whatever'] < df['something_else'])
        ), ['enter_long', 'enter_tag']] = (0, "rejected_frogbuy1_l")

    return df
```

### Observed Results:

I then run backtesting, and still see opened trades with the "rejected" tag:

```
================================================================== ENTER TAG STATS ==================================================================
|                    TAG |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|------------------------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|    rejected_frogbuy1_l |    115 |           0.36 |          41.55 |            41.559 |           2.08 |        5:54:00 |    98     0    17  85.2 |
```

When printing out dataframes for each pair, they all come up empty, as expected, with the following print statement:

```
print(
    df.loc[
        (
            (df['enter_tag'] == "rejected_frogbuy1_s") & (df['enter_short'] == 1)
        ) | 
        (
            (df['enter_tag'] == "rejected_frogbuy1_l") & (df['enter_long'] == 1)
        )
    ])
```

**Comment by xmatthias** [comment]
enter_tag is a **shared column** between longs and shorts - it's just transmitting information of the tag.
If you've got colliding signals (both a long and a short signal) - that signal [won't be acted on](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) - so this is not a problem unless you try to be fancy - and in consequence use it wrong.

So your "rejected frog_l" will be a short - which get's it's tag overwritten.

to properly reject this and avoid both directions of the trade - you can use the following:

`), ['enter_long', 'enter_short', 'enter_tag']] = (0, 0, "rejected_frogbuy1_l")`

Alternatively - you'll also need to filter on `enter_short` - and only reset the long entry column (not the tag) if the enter_short column is still active.

**Comment by froggleston** [comment]
I haven't got colliding signals and I understand that it's a shared column. However, I don't understand why the enter_long is set to 0, but it still enters a long trade.

**Comment by xmatthias** [comment]
nothing in your output suggests the trade is a long trade (it's not stated).
but either you re-set the signal further down (but then without tag) - or it's a short trade (which is the more likely reason).

**edit** I'll gladly have a look at the problem in detail if you can provide me with a functional, minimal strategy (the above is not - it's partial and will require quite some work to get to a working state, including defining all indicators you're using).

**Comment by froggleston** [comment]
```
        ), ['enter_long', 'enter_tag']
    ] = 1, 'frogbuy1'
```
Setting enter_long to 1 makes it a long right?

edit: `), ['enter_long', 'enter_short', 'enter_tag']] = (0, 0, "rejected_frogbuy1_l")` this seems to work but this is not intuitive *at all*. This needs to be clearly documented.

**Comment by xmatthias** [comment]
there's no documentation part for resetting signals afterwards, either - and i don't think doing it that way is intuitive. It's better to define the condition upfront (eventually just as mask `protection_mask = (df['whatever'] < df['something_else'])` ) - and avoid setting the signal in the first place.

if you're not using shorts at all in your strategy - then the "enter_short" reset is not necessary.

Your signals may not be colliding - but you're not checking for "is enter_long > 0" either - so whenever your "reset" condition applies, you'll reset ALL tags (independently if the corresponding signal was a long or a short).
The "3 way" condition will reset all signals (both short and long) - which is why it's working now (it'll however also prevent short signals).

An alternative can be to ALSO check for `& (dataframe['enter_long'] > 0)` in your reset condition - if you expect it to apply only to long conditions.

---

I don't really see how / what can be documented (feel free to make a recommendation - but please do NOT use resetting signals in this way as an example, as i see this as an anti-pattern which should be avoided - and as you've seen, is pretty error-prone).

It's pretty clear from the docs that enter_long is used for long entries - enter_short for short entries - and "tag" for the tag that corresponds to that signal.

Colliding signals are rejected (also documented) - so there's no real need to have more than one "tag" column.

**Comment by froggleston** [comment]
Yeah I've done the `enter_long > 0` route for now, and I suppose yes I could front-load the protection in...

I'm just interested how this could be error prone when I'm simply changing the enter_long value in a column, much like I would set it to 1 to enter rather than setting it to 0 to not enter. I don't see any cases where that should result in differing functionality depending on which way round you do it...

**Comment by xmatthias** [comment]
it's error prone as you see above - you're resetting the tag from a signal you didn't want to touch. That's an error - an error made in the strategy. It's not the first time i see it either, which makes it error prone.



> I don't see any cases where that should result in differing functionality depending on which way round you do it...

Think about the dataframe as if it were a sheet in excel - and you do your conditions manually - one after the other.
you first do some long conditions - then some short conditions (you set both signal and tag)..
You also have some rejection conditions - so you go over these last (again, resetting the signal and tag).

The only difference here is - since you do it manually, you'll notice "oh, here is no long signal - but i'm resetting the tag column because i don't want a long here".
you'll notice (this is the difference) - and either change your approach by checking "is there an actual long signal?" - or by skipping this one (it's a manual task after all).

This is missing in a strategy / when populating a dataframe - as you basically get a dataframe in - and you return one.
If you don't think the course of action through (if i'm setting the same column 10 times with different conditions - then the last one will be the one that's actually active) - then you'll encounter such problems.

Recommending to "don't use guards, but "reset" signals afterwards" as part of the docs would therefore lead people down a dangerous path.
i'm not saying don't do it - i did it myself - and and if you're careful, it's not problematic - but you need to be aware of a few things.
