### ISSUE TITLE
Use pairlist directly in backtesting

### ISSUE THREAD

**Issue by quant5** [freqtrade/freqtrade#7377]
## Describe the enhancement

I'm using a command like the following to convert today's dynamic pairlist into a static pairlist.json file.
```
freqtrade test-pairlist --config ./configs/volume-pairlist.json --quote USDT --print-json > ./configs/pairlist.json
```
Having this pairlist.json file streamlines `freqtrade data-download`, but afaik I cannot directly reference this pairlist.json in `freqtrade backtesting` (e.g., as a config), without either (a) putting it into a space-separated list for the CLI or (b) putting it into the `pair_whitelist` of some existing config file.

Is there something I'm overlooking, if not may I suggest supporting using pairlist json files directly in backtesting (and edge, and hyperopt, and perhaps even `freqtrade trade`). I think such support would be aligned with the broader spirit of modularizing configs.

**Comment by xmatthias** [comment]
The problem here is expectations.

if we support `--pairs` in trade mode - you'd expect that to be used as pairs.
That's however ONLY true if you're using staticpairlist. in all other cases, this would be ignored.
As staticpairlist is enforced for backtesting, we can support that there - but it'd clearly be wrong for trade mode.

you can however create a (minimal, additional) configuration that looks as follows - which can be used as last `--config` argument

``` json
{
  "pairs": ["ETH/USDT", "..."]
}
```

**Comment by quant5** [comment]
Definitely makes sense, and also to your point the exchange-specificity of pairlists could be an issue if pairs.json were to be allowed (i.e. trying to run exchange A's pairlist on exchange B).

I will do some refactoring on my end to embed pairlists within configs.
