### ISSUE TITLE
hyperopt for future trading on both long/short

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7388]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.9.12
  * CCXT version: 1.92
  * Freqtrade Version: 2022.8
  
## Your question
I'm trying to use the `hyperopt` function to optimize some indicator parameters for my strategy.

### Q1:
For space assignment, since I'm working on future trading. The definition is quite confused at beginning. I then found this:

![image](https://user-images.githubusercontent.com/1921878/189425606-2109ecf2-46ef-4be9-8759-1fc15b0c44d5.png)

Does it mean `buy` is actually `entry` and `sell` is actually `exit` for trading with both long/short options?

### Q2:
In the [Optimizing an indicator parameter](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter) section, the manual didn't mention the assignment about `space`. 

But when running the hyperopt command, `freqtrade` will report error of not having `buy` space -- so should indicator optimization also need an assignment of `buy` / `sell`? Otherwise, what is the `space` that should be used in this case?

**Comment by xmatthias** [comment]
Freqtrade used to be a long only bot - so buy/sell separation automatically meant entry/exit.

While we aimed to rename most things from buy to entry/sell to exit - we didn't do this for hyperopt yet, both to avoid breaking peoples strategies - and because buy/sell can still make sense (if you consider "buy" as entry for long / exit for short).

In reality - the space naming (especially buy/sell) is arbitrary - simply there to allow you for a selection of a few parameters, while not optimizing the others.
You can also have all parameters in the buy space (for example) - switching optimization on and of manually via the `optimize` command line argument.

e.g.: `ema_long = IntParameter(15, 200, default=50, space='buy', optimize=False)`

If a parameter is then used for buy / sell - or something else - is really up to how the strategy decides to use this parameter.

---

If you read through the whole hyperopt page - you'll find [this section](https://www.freqtrade.io/en/stable/hyperopt/#hyperoptable-parameters) which explains how space assignment works.
the "space" argument is not needed if the variable starts with a space name (e.g. `buy_xxx`) - but it's needed if you pick custom names, which won't allow freqtrade to automatically determine the proper name.

The sample in the indicator section is using this - and for simplicity omits the parameter that's redundant in that case - keeping focus on the method it's aiming to show.
