### ISSUE TITLE
get_analyzed_dataframe does not provide history prior to the defined `--timerange`

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#7389]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: 3.10.4
  * CCXT version: 1.93.3
  * Freqtrade Version: 939fb7acb338202dfa2bf945ee51d95e37e14e97

## Describe the problem:

The first time you enter `custom_stoploss` in backtesting: you may get only a few rows of DataFrame from `get_analyzed_dataframe` and then it keeps increasing as you loop back to `custom_stoploss`. But you may need more rows  from the first time you enter `custom_stoploss` (in backtesting). It is not because of buy signals at the first few candles because the indicators tested need way more than that.

I think I might know how the quirk appears. It looks back before `--timerange` in order to populate indicators (possibly because of a long `startup_candle_count`) but it may then enter a trade the very first day of `--timerange` at the start of it (it does give a longer DataFrame on other trades later so it's only if you get "lucky" at the start of the first day of `--timerange` that may cause it). 

It appears the code should respect `startup_candle_count` and return a longer DataFrame with `get_analyzed_dataframe` in early buy signals. A user workaround might be to produce needed indicators before entering `custom_stoploss` (or similar functions that need `get_analyzed_dataframe` I guess), but that's counter-intuitive and it defies part of `get_analyzed_dataframe`'s purpose.

### Steps to reproduce:

  1. Have a strategy that will produce a trade signal at the very start of `--timerange`
  2. It needs indicators that may be populated from data before `--timerange`
  3. `get_analyzed_dataframe` returns very few rows  at the start

**Comment by xmatthias** [comment]
to be honest, I see this as intended behavior.

Let's assume a timerange of `--timerange 20220201-20220401` (end date is irrelevant ...), a timeframe of 1h - and you have 24 startup candles (so we have 1 day of additional data). The assumption also is that more data exists at the start.

Freqtrade will load data from 20220131-20220401 (an additional 24 candles) - and run analysis on this (calculating indicators - which may take up to 24 candles to actually produce values (e.g. an EMA24).

After the analysis - freqtrade will remove this additional 24 canldles from the start - leaving only the desired timerange (20220201-20220401).
Now it goes on and checks for entry/exit signals. Assuming your strategy produces a buy signal on the very first candle (2022-02-01 00:00) - so we enter the trade at 2022-02-01 01:00.
We'll now call `custom_stoploss()` (or any other callback, really) - and you call `get_analyzed_dataframe()` - which will give you data from the start of your timerange. 
In this case, that'll be 2-3 candles. 

---

Now you can assume "I need a lookback of 200 candles for my stoploss logic" (that'd bring us to roughly 2022-01-21) - but that's data that was never loaded, never analyzed, no indicators were calculated - so that's data freqtrade cannot provide to the strategy.

We must take the assumption that each callback will use any indicator (any column) in the strategy - so assuming the callback uses the EMA24 - but you use `df['ema24'].shift(200)` for your stoploss calculation - as you really care on the EMA from 200 candles ago.

That's data we never calculated, never loaded - so freqtrade cannot provide this data. It'll provide data from the start of the timerange - after the startup indicators are removed (otherwise the strategy would have the responsibility to check "has this already been analyzed, or is it NaN").

**Comment by epigramx** [comment]
>  that's data that was never loaded, never analyzed, no indicators were calculated 

They were (because of `startup_candle_count ` being > 0); e.g. the buy signal is based on indicators that look back for days before `--timerange`; `get_analyzed_dataframe()` drops them if they happen to be before `--timerange` which is counter-intuitive and it defies `get_analyzed_dataframe()` 's purpose in part.

It's also a practical advantage to `custom_stoploss()` to have that data. Currently it acts as if no data exists at all before `--timerange` which is technically wrong because it did use more data because `startup_candle_count` was > 0.

**Comment by xmatthias** [comment]
> They were (because of startup_candle_count being > 0); 

Your assumption and/or statement is wrong.
Based on the above sample - 24 additional candles were loaded (1 day). 
0 additional candle had ema24 calculated correctly - so EMA would come out as NaN (or whatever else the instable startup provides for the indicator used).

You can therefore not rely to that data in the strategy.

On top of that - i assumed to go back 200 candles (startup candle count was 24) - so that data (2022-01-20) has never been loaded.

> It's also a practical advantage to custom_stoploss() to have that data.

That's correct - but what's the limit (so what would you expect when supplying `--timerange 20220201-`) - should we load data for another month? 2 months? maybe years? 

we have no idea what the logic in the callback looks like - or what it's expecting - so it could go back 1 day - or 1 month - but that'd mean we always MUST load all available data - as you could want to go back all the way (which wont' work in live anyway)

**Comment by epigramx** [comment]
I understand your 2 arguments but the balanced solution is to return more data up to a limit (user-set or not) before `--timerange`, because if you claim you can't know how far back (before `--timerange`) you have to go: then how can anyone rely on `get_analyzed_dataframe()` returning _any_ data before the last candle?

It effectively makes the entire function of `get_analyzed_dataframe()` bugged for anything beyond the last candle (in backtesting).

**Comment by xmatthias** [comment]
> I understand your 2 arguments but the balanced solution is to return more data up to a limit (

The limit exists and is defined in the left border of `--timerange`.
to ensure buy signals starting from that time - you can set `startup_candle_count` - to ensure you only get "stable" signals (siganls calculated after an indicator's unstable period).

nobody forces a strategy to do that though - leaving `startup_candle_count=0`  works just as well - obviously you'll have to do "is my indicator now stable" checks yourself (probably by checking for `NaN` values).

We'll surely not load a random additional junk of data that will be analyzed - but then thrown away as "uups, still didn't need it".


your strategy must be able to handle non-available data (for example after a downtime you won't get a guaranteed dataframe length).
If your strategy can't handle such a situation, it'll fail in that event just as it will do in backtesting.

**Comment by epigramx** [comment]
Point is all strategies are effectively bugged if they use `get_analyzed_dataframe()` for more than the last candle if they look for signals that can happen before the last candle based on the data that it returns (even if they do a `len(df)` check to ignore a few dates: it's still an inaccurate backtest).

Though I was meaning to ask you if you can just detect how far back `populate_indicators()` used data in order to produce indicators (which is likely what `get_analyzed_dataframe()` needs for a "lookback length") **but then I realized**,

why don't you just return up to `startup_candle_count` number of candles in the past (before `--timerange`) since that's already defined and that's almost certainly up to what anyone needs both practically and intuitively?

**Comment by xmatthias** [comment]
> why don't you just return up to startup_candle_count number of candles in the past (before --timerange) since that's already defined and that's almost certainly up to what anyone needs both practically and intuitively?

That's the point i'm trying to make above - you can't rely on this data - even if we were providing this as part of `get_analyzed_dataframe()` - as that part of the dataframe is NOT analyzed properly.

in fake/conceptual code:

``` python
df = dp.get_analyzed_dataframe(pair)

if df.iloc[-5]['ema24'] > 20:
   return newStopLoss
```


The above code will (at least from a conceptual perspective) work perfectly fine if we were providing the analized dataframe as "timerange - startup_candle_count".

It'll work - UNLESS you get a buy on the first candle - since ema24 will be NaN - so you'll get a "can't compare NaN" error. The dataframe is not properly analyzed - but the content will be empty - so what exactly would we gain with this?

**Comment by epigramx** [comment]
Because in practice I may have a larger `startup_candle_count` than the length of any indicator's lookback, so I may know for certain that an indicator from the first candle of `--timerange` will be valid if I look back only up to a certain number of candles in the past.

Currently: it's certain that nothing is reliable before the last candle so you either have to choose to never rely on candles beyond that last one or: take the "accuracy hit" of using an `if len(df) > #` for the df returned to make sure you'll have a df row available.

**Comment by xmatthias** [comment]
letme repeat what i said above - you can't rely on the dataframe lenght in live either.
if an exchange was down for 500 candles - you'll only get the remainder of what that exchange provides (500 for binance).
You can say "we get enough to avoid that" - but you won't know how long an outage takes - (and okx only provides 300 candles by default ...) 

so having a `if len(df) > #` in is always good / necessary - also because you'll  get a completely empty dataframe at bot startup (before any candles are analyzed).

**Comment by epigramx** [comment]
Sure, but `if len(df) > #` will be most likely `True` on live (given no outages) when currently on backtesting `if len(df) > #` will be always `False` on the first few candles of the `--timerange`.

The `len(df)` check could always be there and still try to go as far back as `startup_candle_count` so that backtesting is closer to live.

**Comment by xmatthias** [comment]
i don't think you fully understood what i mean.

Even if `len(df) > #` passes for the first candle - it'll have to be replaced with `~df['someindicator'].isnan()` (or the equivalent for a single row) - as you have no guarantee the data is filled with what you expect (a number, most likely).

the assumption that `startup_candle_count` is way bigger than what i need is NOT an assumption freqtrade will base any code on - nor anything we'll recommend in the documentation.

**Comment by epigramx** [comment]
I understand your reasoning, which leaves the problem of non-last-candle data from `get_analyzed_dataframe()` not being guaranteed. It leads to either never using them (and staying only on using the last candle from it) or getting an accuracy hit with a `len(df)` check (and I'm closing this because we've already exhausted it I believe).

**Comment by xmatthias** [comment]
unfortunately, backtesting will always have tradeoffs - otherwise we'd all be rich already. 

i can see your point, too - at least to some degree, but i don't think we have many options which don't cause other, potentially worse problems.
we can't guarantee "you get the historic data you need" - because we simply don't know how much you're going to need.
we could apply startup-candles twice - and then provide "half of that" as additional `get_analyzed_dataframe()` - but in more cases than not, that will lead to backtesting loading quite some more data than necessary, which is then never needed/used.

simply providing "whatever we initially loaded before cutoff" is however the worst of all approaches - as that'll no longer give you ANY ensurance on the content of the dataframe (other than ohlcv columns) - as all indicators have a startup time of some sorts (either via NaN - or via incorrect values).

**Comment by xmatthias** [comment]
Let's leave this one open for now so i don't forget it (closed issues = forgotten issues).

Will have to have a good thought on how this could be approached (and it's consequences to different scenarios) - it's not a bug per se (it's currently intended) - but if behavior can be improved - that's always welcome.
