### ISSUE TITLE
Unable to open web address(127.0.0.1:8080) under the docker environment

### ISSUE THREAD

**Issue by dumengru** [freqtrade/freqtrade#7415]
## Describe your environment

  * Operating system: __windows10__
  * Python Version: __3.10___ (`python -V`)
  * CCXT version: __1.92.52___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.8.__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Under Windows environment, When I execute an order"freqtrade trade ...",  Web page(127.0.0.1:8080) opening is normal.
However, Under docker-compose environment, When I execute an order"docker-compose up ...",  Web page(127.0.0.1:8080) opening is abnormal, and the order "docker ps" shows that the ports is normal(127.0.0.1:8080->8080/tcp).

I'm not very familiar with Docker and what should I do?

**Comment by dumengru** [comment]
![image](https://user-images.githubusercontent.com/62230160/190101840-1f4c3721-44f0-4aa9-bdd7-7aab851e2b5c.png)


![image](https://user-images.githubusercontent.com/62230160/190100951-5bd16f26-76e3-4f3f-b327-f40ae8a86ad5.png)

![image](https://user-images.githubusercontent.com/62230160/190101045-23456eba-d4c6-4344-bb05-1f4f7104679e.png)

**Comment by xmatthias** [comment]
Your configuration must be adapted to be used from within docker to have `listen_ip_address` to 0.0.0.0.
Otherwise the port is not available for docker.

This is explained in the [docker segment of the API docs](https://www.freqtrade.io/en/latest/rest-api/#configuration-with-docker).

**Comment by dumengru** [comment]
Thank you very much. It was I who overlooked this detail.

**Comment by Bilal1422** [comment]
YesSent from my Samsung Galaxy smartphone.
-------- Original message --------From: 杜梦如 ***@***.***> Date: 14/09/2022  12:49 pm  (GMT+03:30) To: freqtrade/freqtrade ***@***.***> Cc: Subscribed ***@***.***> Subject: [freqtrade/freqtrade] Unable to open web address(127.0.0.1:8080) under the docker environment (Issue #7415) 

Describe your environment

Operating system: windows10
Python Version: 3.10_ (python -V)
CCXT version: 1.92.52_ (pip freeze | grep ccxt)
Freqtrade Version: 2022.8. (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

Your question
Ask the question you have not been able to find an answer in the Documentation
Under Windows environment, When I execute an order"freqtrade trade ...",  Web page(127.0.0.1:8080) opening is normal.
However, Under docker-compose environment, When I execute an order"docker-compose up ...",  Web page(127.0.0.1:8080) opening is abnormal, and the order "docker ps" shows that the ports is normal(127.0.0.1:8080->8080/tcp).
I'm not very familiar with Docker and what should I do?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freqtrade/freqtrade/issues/7415",
"url": "https://github.com/freqtrade/freqtrade/issues/7415",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
