### ISSUE TITLE
Please update the document about Using proxy with Freqtrade

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7445]
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8 stable

## Describe the problem

The document about [Using proxy with Freqtrade](https://www.freqtrade.io/en/stable/configuration/#using-proxy-with-freqtrade) needs to be updated

<img width="810" alt="image" src="https://user-images.githubusercontent.com/49523956/191189884-7c4bd86d-13b7-4010-9742-6e3892e5d4a0.png">

`"aiohttp_trust_env": true` only works for **ccxt 1.89.x** and older versions.

## Describe the enhancement

Here is the correct configure example for **latest ccxt and Freqtrade**.

```python
    "ccxt_config": {
      "aiohttp_proxy": "http://127.0.0.1:10808",
      "proxies": {
        "http": "http://127.0.0.1:10808",
        "https": "http://127.0.0.1:10808"
      },
      "enableRateLimit": true,
      "rateLimit": 25
    },
```
Make sure add `aiohttp_proxy` and `proxies`.

**Comment by xmatthias** [comment]
Since you seem to know how this needs to be configured - best open a Pull Request updating the documentation.

A guide for the github PR workflow can be found [here](https://guides.github.com/introduction/flow/) - in reality, especially for documentation changes, it's as easy as moving to the source file for the documentation, editing this on the github page - and then creating a Pull request out of this (which Github will guide you through).

**Comment by liaogx** [comment]
> Since you seem to know how this needs to be configured - best open a Pull Request updating the documentation.
> 
> A guide for the github PR workflow can be found [here](https://guides.github.com/introduction/flow/) - in reality, especially for documentation changes, it's as easy as moving to the source file for the documentation, editing this on the github page - and then creating a Pull request out of this (which Github will guide you through).

I'm lazy to do that. 😂 I gonna close this issue and leave it to you.
