### ISSUE TITLE
limit trade in trading time

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#7482]
Hi;

Due to how cryptocurrencies are, the bot can be without trading for hours and suddenly open 3 trades.

The problem is when it is an up-down market moment, and all your slots remain open for a long time, losing other market opportunities.

Could a method be created in Protections that avoids opening several trades in x space of time? Something like maximum x trades in 1 hour

thanks

**Comment by xmatthias** [comment]
In general, you'd not want to tie trades to other trades that opened X minutes prior - you might end up with the only loser (or very small profit) blocking entries to the profitable trades. 
Your approach would assume that "the trade entered first has the highest potential" - which is clearly wrong.

The only "real" limit should be available capital - which will prevent further trades due to lack of money.

Freqtrade itself won't be providing such functionality - but it should be pretty easy to combine something together with [confirmation callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#bot-order-confirmation), blocking further entries depending on whatever conditions you desire.
