### ISSUE TITLE
Martingale Strategy

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#7525]
* Operating system: Windows 10
  * Python Version: Python 3.10.4
  * CCXT version: ------
  * Freqtrade Version: 2022.9.1
  
I wounder if it is possible using martingale strategy with freqtrade bot ? 
"The Martingale Strategy involves doubling the trade size every time a loss is faced. By this way, when you win, you can compansate all of your loses and win additional gain."

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Also - please try to be a bit more descriptive. 
Without providing a link you assume everyone knows what the Martingale strategy is - or goes off to find a (reliable) source (which also aligns with your expectations).

Without further information - the answer is no, simply because i don't intend to do research to understand your question.

**Comment by bleriot14** [comment]
> 

I am sorry you are right. I am new in github I will be more cautios.

**Comment by xmatthias** [comment]
You can define the [stake size](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management) of trades.

Such strategies however usually assume unlimited capital - as you can/will run out of money on a losing streak very quickly.
