### ISSUE TITLE
Some historic data has 0 volume

### ISSUE THREAD

**Issue by Alex7Li** [freqtrade/freqtrade#7597]
## Describe your environment

  * Operating system:  Linux, Windows
  * Python Version: 3.8
  * CCXT version: 1.95.11
  * Freqtrade Version: 2022.9
  
## Your question

We have downloaded data for some popular coins from tfxus (BTC, LTC, ETC, SOL) and noticed that in some instances, the volume is 0. So, for BTC, after I download the data with
```
docker-compose run --rm freqtrade download-data --exchange ftxus --days 100 -t 5m
```
I noticed that of the entries, there are about 126 entries where the volume is 0, which seems impossible since BTC is so popular. (This happens even more in older time periods than the last 100 days). Also, even when the volume is 0, the open/close prices are not equal. How are we supposed to interpret the volume number, then?

**Comment by xmatthias** [comment]
tfxus - i assume you mean ftxus ... ? 

a 0 volume candle can have multiple reasons
* no trades happening
* exchange downtime

however in no case, would the open and close price in this instance be different.

---

Popularity has nothing to do with it, really - especially since it's ftxus (not ftx.com) - it's an exchange that's operating regionally (you can't access it from europe or asia, for example), you might have times of low activity, especially overnight.

On a quick check on ftx.com, i've found several occurrences in the last few weeks where volume was <100 in a 5 minute span - so the fact that there might be 0 trades within 5 minutes overnight seems quite realistic.
you should therefore be able to identify the exact dates from the data and go back in time on their chart (yes, involves quite some "scoll left") - to verify the data on exchange.

sample: 

![image](https://user-images.githubusercontent.com/5024695/196091524-01b4fa21-ebb1-4f70-a06b-5c79a3145b77.png)


---

Now the regional subsidiaries of exchanges (ftxus, binance.us) MIGHT be different, as they may couple the price to their international counterpart (not sure they do - check with their support).

This is however pure speculation.
You can use the following API endpoing (https://docs.ftx.com/#get-historical-prices) (update the URL for ftxus) to get the prices directly for the timeperiod you see these candles - and then (with the parameters filtered to affected candles) open an issue on ftx, asking their support for reasons of this.

Freqtrade is really only a consumer of their api - to receive reasons for the data - you'll have to ask the ones producing the data.

*edit* while i'm closing this issue - please rreport back on the answer support gave you on this topic.

**Comment by Alex7Li** [comment]
After some discussion with them, it seems that the 0 volume candles are because nobody bought crypto as you suspected, and the reason that the high is not equal to the low in these instances is because of the formula they use:

```
FTX.us engine is not building the candles from 'last trades' only. Market price = median (best bid, best ask, last trade)

That means that even if there are no last trades in the last second we still get a better market price if the best bid and ask price are being updated by traders/market makers. 

Thanks,
FTX
```
