### ISSUE TITLE
sync of manually cancelled/closed order

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7606]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10
  * CCXT version: 1.94.53
  * Freqtrade Version: 2022.09
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

1. I have been running `freqtrade` for a few days, and the terminal running freqtrade process suddenly crashed due to system reasons.
2. At that moment there was a open trade on the exchange -- as I don't have access to the computer at that moment, I manually close it through the exchange App.
3. When I restarted the `freqtrade` process, the system "think" the order was still there, and somehow I cannot use `\fx` to exit it (perhaps due to exiting condition).

The problem is, the system seems not sync with the exchange and keep thinking there was an "open order", and keep adding a "conditional stop order" to the exchange. If I cancelled it, it appeared on the exchange again.

In the end, I have to manually add the same order on exchange again, and `\fx` exit it through freqtrade. And the calculation of the PNL was incorrect, either.

I'm not sure if this is a bug or it is by design...
If it is not a bug, how should I manage the open order when `freqtrade` process died accidentally?

### Steps to reproduce:

  1. Open a position/order with `freqtrade`
  2. stop `freqtrade` process while leaving the position on exchange open
  3. manually stop/close the trade on exchange
  4. start `freqtrade` process again
  
### Observed Results:

  * What happened?
  `freqtrade` think there's still an open order 

  * What did you expect to happen?
  `freqtrade` sync with the exchange, and realize there's no open order anymore.

**Comment by stash86** [comment]
Sell it manually, then delete the trade from the database

**Comment by xmatthias** [comment]
This is by design - freqtrade will only touch orders / trades it opened itself.
This allows you to use the account for manual trades / holding other assets. The alternative would be to require the account to be exclusively be used by freqtrade - which is not feasible as many exchanges don't provide sub-accounts without entry barrier.


It'll not detect manually created orders (like a manual sell order) - as freqtrade will have no way to know if you're selling the Portion of COIN freqtrade bought - of if that's now a manual order that accidentally uses the same coin - but shouldn't be used to modify the freqtrade trade.

We have the [sql cheatsheet](https://www.freqtrade.io/en/stable/sql_cheatsheet/) for such situations - but the most likely better / simpler option here is to simply issue a `/delete <tradeid>` via telegram to remove the trade from the database.

We also assume that the system freqtrade is running on is stable (not causing issues on it's own). 
While you probably got the "process died" notification - that would not happen if (for example) the network disappears.
