### ISSUE TITLE
Allow post only orders on exchanges that allow it (GTX on ccxt)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#7706]
### Explain the enhancement you would like

As a trader i want to use post only orders so that i can do market maket using freqtrade and pay only maker fees.

#### How to do.

For far i have understand the post only order is reprensent in timeInForce = GTX.
I have make some test a few monthes ago with binance spot and GTX with freqtrade (just allow in binance exchange the GTX enum from far i remember) and it seems to work pretty well -> it handle the case where you place order and it is rejected because it be filled as taker (same way as FOK).

What to you think about it ?

Many tks, have a nice day.

**Comment by xmatthias** [comment]
The theory sounds good.

In practice we can't. 
CCXT does not provide information on which exchange supports which time in force.

Configuring a "wrong" time in force would make the bot start - but fail once it reaches the order creation step. This can be minutes, hours, or sometimes days into running the bot - and can also lead to losses (if you configure this for exit orders).
Therefore, we must ensure that the time in force configured is actually a valid Time in force setting for the exchange used (which is what we're doing now).
As ccxt does not provide this info - we must specify it on a  "per exchange" basis. I'd clearly like to get this info from ccxt - but we don't at this point.

Because of this, I'll close this for now as it's impossible to accomplish at this point in time.
You should however consider opening an issue against ccxt. 
We can gladly look at this (and remove the enum we have in freqtrade) once ccxt provides this information.
