### ISSUE TITLE
Getting Error with Freqtradeai Model 

### ISSUE THREAD

**Issue by HESSEBO** [freqtrade/freqtrade#7752]
First of I would like to thank the developer team for keeping this great piece of software up and running and in continuous development. 
I am playing around with FreqAi. all is going good and I want to bring it up using the docker-compose. Although when I hit the command: sudo docker-compose up I get the following error: 

Nostolgia    | 2022-11-14 20:43:05,660 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
Nostolgia    | 2022-11-14 20:43:05,952 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8088
Nostolgia    | 2022-11-14 20:43:05,952 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - Local Rest Server listening to external connections
Nostolgia    | 2022-11-14 20:43:05,953 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json
Nostolgia    | 2022-11-14 20:43:05,953 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
Nostolgia    | 2022-11-14 20:43:05,961 - uvicorn.error - INFO - Started server process [1]
Nostolgia    | 2022-11-14 20:43:05,961 - uvicorn.error - INFO - Waiting for application startup.
Nostolgia    | 2022-11-14 20:43:05,962 - uvicorn.error - INFO - Application startup complete.
Nostolgia    | 2022-11-14 20:43:05,962 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8088 (Press CTRL+C to quit)
Nostolgia    | 2022-11-14 20:43:05,966 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
Nostolgia    | 2022-11-14 20:43:05,967 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 1 pairs: ['BTC/USDT']
Nostolgia    | 2022-11-14 20:43:05,995 - freqtrade.commands.trade_commands - ERROR - No freqaimodel set. Please use `--freqaimodel` to specify the FreqaiModel class to use.
Nostolgia    |
Nostolgia    | 2022-11-14 20:43:05,995 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Nostolgia    | Traceback (most recent call last):
Nostolgia    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
Nostolgia    |     worker = Worker(args)
Nostolgia    |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
Nostolgia    |     self._init(False)
Nostolgia    |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
Nostolgia    |     self.freqtrade = FreqtradeBot(self._config)
Nostolgia    |   File "/freqtrade/freqtrade/freqtradebot.py", line 131, in __init__
Nostolgia    |     self.strategy.ft_bot_start()
Nostolgia    |   File "/freqtrade/freqtrade/strategy/interface.py", line 182, in ft_bot_start
Nostolgia    |     self.load_freqAI_model()
Nostolgia    |   File "/freqtrade/freqtrade/strategy/interface.py", line 153, in load_freqAI_model
Nostolgia    |     self.freqai = FreqaiModelResolver.load_freqaimodel(self.config)
Nostolgia    |   File "/freqtrade/freqtrade/resolvers/freqaimodel_resolver.py", line 41, in load_freqaimodel
Nostolgia    |     raise OperationalException(
Nostolgia    | freqtrade.exceptions.OperationalException: No freqaimodel set. Please use `--freqaimodel` to specify the FreqaiModel class to use.

From the debug info I can see that it can't find FreqaiModel during running process but when I use the command: 
sudo docker-compose run --rm freqtrade trade --strategy ai --freqaimodel LightGBMRegressor

It runs normally, the problem when using this command is that I can't access FreqUI via the web interface.

Any help will be appreciable.

**Comment by xmatthias** [comment]
First of all - please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt sometimes why we should chose to answer your questions.

----

First off - you shouldn't need to use `sudo` to run docker commands. That's bad practice from a security point of view - and suggests an installation error (or your user is not in the docker group). 
I'd suggest to use docker documentation to fix that - as to me, it points to an incomplete installation.

`docker-compose run` will not map any ports - which is why you can't access freqUI.

The solution is very simple - you know the comand you're trying to run already (` trade --strategy ai --freqaimodel LightGBMRegressor`) - so you simply take this command - and replace the command in the docker-compose file with the actually desired command.

**Comment by HESSEBO** [comment]
Thanks for your kind response and I apologize for my lack of following issue template.  
That did really solved the problem of bringing up docker-compose with FreqaiModel.
