### ISSUE TITLE
dataprovider.send_msg() doesn't send messages to discord

### ISSUE THREAD

**Issue by AlexBabescu** [freqtrade/freqtrade#7762]
## Describe your environment

  * Operating system: Windows/Linux/Docker image
  * Python Version: 3.9.12
  * CCXT version: 2.1.92
  * Freqtrade Version: 2022.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Trying to send a custom discord message using the dataprovider from the strategy doesn't work.

### Steps to reproduce:

  1. configure discord webhook and allow custom messages
  2. somewhere in populate_indicators or populate_entry_trend call self.dp.send_msg("test_msg")
  
### Observed Results:

If I do self.dp.send_msg("test_msg") and that will eventually call send_msg in freqtrade\rpc\discord.py with {'type': strategy_msg, 'msg': 'test_msg'} and then it will hit this if statement if msg['type'].value in self._config['discord']: where it expects to have strategy_msg under discord in the config.

**Comment by xmatthias** [comment]
As you correctly point out - it expects to have "strategy_msg" in the config (which apparently you don't have, otherwise it would works).

a config segment similar to this (within the discord section of the config) should work:

```
"strategy_msg": [
        {"MSG": "{msg}"}
      ]
```

sending "hello world" with `self.dp.send_msg('hello world')` from a strategy will then show up as follows:

![image](https://user-images.githubusercontent.com/5024695/202726799-5dc751e1-aeaa-47af-bea7-cadcfd573bfe.png)
