### ISSUE TITLE
Fetching backtest results for further analysis

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#7830]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: 3.10.4
  * CCXT version: 2.1.96
  * Freqtrade Version: freqtrade docker-9df10c6b
  
## Your question
How do I catch the key for "Max % of account underwater"?. For the "Absolute Drawdown (Account)" I got it this way:
```
  config = Configuration.from_files([f"{config}"])
  backtest_dir = config["user_data_dir"] / "backtest_results"
  stats = load_backtest_stats(backtest_dir) 
  max _draw_account = stats['strategy_comparison'][0]['max_drawdown_account']
```
So how do I do the same for max of account under water. What is the actual key? and where do I find it? I have been scouting for an hour plus :).

**Comment by xmatthias** [comment]
it's all in optimize_reports, really ...

https://github.com/freqtrade/freqtrade/blob/915524a1610265a1d94d5103692dbf6f2cece965/freqtrade/optimize/optimize_reports.py#L750-L752

a "probably" better option might be to use `stats['strategy']['YourStrategyClassName']['max_drawdown_account']` instead of the comparison stats...

**Comment by moinonin** [comment]
Thanks mate! :+1:
