### ISSUE TITLE
finta doesn't work

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7926]
## Describe your environment

  * Operating system: ____Ubuntu 22.04
  * Python Version: _____ (`python -V`) 3.10.4
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2022.12.dev-bc10bcaf6
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Finta throws an error calling vfi volumeflow. 

### Steps to reproduce:

  1. _____ start strategy
  2. _____
  3. _____
  
### Observed Results:

  * What happened? error
  * What did you expect to happen? no error - this is happening on a few strats, wondering if there is a workaround?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots.

  ```
dataframe['vfi'] = fta.VFI(dataframe, period=14)
Dec 21 05:34:16 instance-20220819-1716 freqtrade [2486]: AttributeError: type object 'TA' has no attribute 'VFI'
  ```

**Comment by xmatthias** [comment]
With the provided snippet it's impossible to say for sure what's the problem (what is fta? how is it imported??).
The most likely problem is that it's `fta` is not actually a finta import but "whatever" else - something that's not providing VFI at any rate.


That said - freqtrade does not depend on finta. While the dataframe will work with finta just fine - it's not something we can provide extensive support (Though we should be able to help with a "gone wrong" import...).

It also seems that it's no longer maintained (the [repo](https://github.com/peerchemist/finta) is in read-only state since November 9th) - so it's unlikely that there will be much support there either.

**Comment by tomjrtsmith** [comment]
from finta import TA as fta

talib.abstract is imported as ta

I can comment out VFI its annoying not being able to use it

**Comment by stash86** [comment]
Are you sure about the import? Why not `import finta as fta`?

**Comment by xmatthias** [comment]
The import itself seems to work fine as is - maybe check your version of finta? (`pip show finta`).

![screenshot](https://user-images.githubusercontent.com/5024695/208853908-2a53dd1c-6fa4-45f6-9f6e-5b4f7bcc519d.png)

I can't really tell you what version should or shouldn't have VFI ... 
you should be able to update it with `pip install -U finta` if you suspect it's not uptodate.
