### ISSUE TITLE
Add support for alpaca markets broker

### ISSUE THREAD

**Issue by dshetyo** [freqtrade/freqtrade#7953]
I want to add support for alpaca markets broker. How do i go about it?

https://alpaca.markets/

Am willing to contribute connector to this broker.

**Comment by xmatthias** [comment]
Freqtrade connects to exchanges / brokers through ccxt.
Assuming an exchange is suppored by [ccxt](https://github.com/ccxt/ccxt) (alpaca seems to be) - you can look at the [implement a new exchange](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) section.

The main point is that it's showing up in `freqtrade list-exchanges` - if it's supported by ccxt and doesn't show up - use `freqtrade list-exchanges --all`.
also make sure you're using the latest version of ccxt for this.
this will show you what's missing to have it supported - after which you can have a look at the API documentation if that's supported - and if / why ccxt didn't implement this.

Now having ccxt does not automatically guarantee success - but is the foundation you can build on.

Looking at the output of the above mentioned command 
```
alpaca              True     missing opt: fetchMyTrades, fetchL2OrderBook, fetchTicker, fetchTickers
```
we see that it's missing a few optional dependencies (using the lastest ccxt).

While it seems good in general - one of `fetchL2OrderBook`, `fetchTicker` MUST be implemented, otherwise we'll have no way to get an uptodate price for a pair.
your first stop will therefore have to be ccxt - adding at least one of these 2 methods.
