### ISSUE TITLE
How to entry newer signals after closing holding positions?

### ISSUE THREAD

**Issue by thanatchon36** [freqtrade/freqtrade#7957]
Assuming we have max-open-trades is 1, Let's say we have a traditional scenario here:

time | symbol | enter_short | exit_short | action
8:00 | BTCUSDT | 1 | 0 | Short BTCUSDT
8:00 | ETHUSDT | 0 | 0 | -
8:30 | BTCUSDT | 0 | 0 | Hold BTCUSDT
8:30 | ETHUSDT | 1 | 0 | Cannot Short ETHUSDT due to max-open-trades is 1

What I want to achieve is this scenario:

time | symbol | enter_short | exit_short | action
8:00 | BTCUSDT | 1 | 0 | Short BTCUSDT
8:00 | ETHUSDT | 0 | 0 | -
8:30 | BTCUSDT | 0 | 0 | Hold BTCUSDT
8:30 | ETHUSDT | 1 | 0 | Close BTCUSDT position, Short ETHUSDT

Please tell me how I can customize my strategy to fit the above scenario.

Thank you so much :D

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

it's also quite unclear what you're trying to do - so the below might not be 100% applicable to what you try to do (it's mostly based on guesswork from my side...).

You can close positions either through a `exit_<direction>` signal in the dataframe, or through the [`custom_exit()` callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-exit-signal).

the closing pair will be auto-locked until the end of this candle, but by default, all other signals will be acted on throughout the candle - obviously assuming the signal is still there.

**Comment by thanatchon36** [comment]
## Describe your environment

  * Operating system: MacOS 12.6
  * Python Version: Python 3.9.7
  * CCXT version: ccxt==2.4.60
  * Freqtrade Version: freqtrade 2023.1.dev
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

[custom_exit() callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-exit-signal) can access local variables only for holding positions which means I cannot get entry signals from other pairs that is not holding (populate_entry_trend enter_<direction>).

What I'm trying to do is that my strategy has the assumption that the newer entry signals would be a stronger indicator to entry than the older one. Therefore, my strategy would always hold a pair that has the youngest signal. I hope this might be solved in some ways.

Thank you so much for a prompt reply.

**Comment by xmatthias** [comment]
You can get dataframes for other pairs through the [dataprovider](https://www.freqtrade.io/en/latest/strategy-customization/#get_analyzed_dataframepair-timeframe).
You can also have a look at the [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs) section - where you can use data from X to trigger an entry (or in your case, exit) on another pair.

Freqtrade does however take the assumption that each trade is standalone - having signals from one pair influence another is probably not a good idea - you're most likely better off by splitting your capital into multiple trades, rather than having one trade cause a "forced exit" on other trades "just because".
That can very quickly result in accumulating fees (without real movements) - but it'll obviously depend on the scarcity of your signals.

**Comment by thanatchon36** [comment]
I will change my strategy assumption to be more suitable for Freqtrade. Thank you so much.
