### ISSUE TITLE
Comparing states of whitelisted pairs before making buy/hold/sell decisions in strategy

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#7985]
## Describe your environment

- Operating system: Ubuntu 18.04
- Python Version: 3.8.8 (python -V)
- CCXT version: 1.89.14 (pip freeze | grep ccxt)
- Freqtrade Version: freqtrade 2022.6 (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

  
## Your question

Hello

I am writing a strategy that assigns a "state" to each pair, and each state must be analyzed with the states of all whitelisted pairs to know what decision to make (buy/hold/sell).
For simplicity, let's consider that the state is a simple scalar, like a score, and let's consider 3  whielisted pairs BTC/USDT, ETH/USDT and DOGE/USDT. The state is updated at each candle.
Let's consider I have open position on ETH/USDT and DOGE/USDT. 
I want to be able to code the fact that if the score of DOGE/USDT becomes lower than that of BTC/USDT, then I sell the DOGE to buy USDT instead.
How can I do this as simply as possible, both in backtest and dryrun? My current idea is to use `confirm_trade_entry` and `confirm_trade_exit` but their use seems laborious and not very efficient; because I would have to mark all candles as signals, and at confirm_trade_entry check with `get_analyzed_dataframe` the scores of all whitelisted pairs and make a decision. I would have liked to know if there is a more elegant way to implement this strategy with my idea.

Thanks in advance for your help!

**Comment by xmatthias** [comment]
Freqtrade assumes positions to be independent - so whatever you are trying to do with this - it's not something freqtrade will support natively / in full.

while you can query the database and get positions - it's not "really" designed for it - and the way backtesting works (to be workable) - you can't assign signals to the dataframe based on prior trades.

For dry, you could just use this in one of the `populate_*` methods (otherwise it'll be quite verbose) - but for backtesting - you can't.
`confirm_trade_exit` might work (obviously with 100% "buy" signals) - but will slow backtesting down - especially if there's not "many" trades
You'll also be limited to not use any "native" exit signals - as that would cause signal collisions - which would mean that the signals are ignored.

**Comment by popperwin** [comment]
I see. I guess I will have to find another way to make it work then. Thanks for your help!
