### ISSUE TITLE
add option to select how many candles must contain start/continuous dataframe

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8002]
Hello,

I'am working on support/resistance levels indicator.
And i just got an essue - if I'am using bigger timeframe with function informative - it does not allows to use computed indicators if range of main tf dataframe does not contain at least 1 informative candle.

It means - when I use informative tf 1d (for example ta.ema(...)) and main tf 1m - the 1d timeframe does not returns computed indicator because in 1m timeframe not enough candles to cover at least one day(returnes NaN or NaT(what???)).
Using the same strategy but with main tf 5m returns 1d indicator for 1.4 candles(I have not checked if it computed fine, but i hope so).

So for this case will be great to add an option to change initial df length(if there are no additional restrictions from provider's side).
For backtesting is no such a problem(You know why).

Thank You for any responce and sorry if there was aswer for my question(I tried to find)

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Make sure to configure your "startup_candle_count" correctly (what your strategy REALLY needs to work.
Freqtrade allows you to get up to 5x (-1) the amount of candles an exchange provides (on binance, 4999 candles) - which should cover quite some more than full day at 1m candles.

Now on some other exchanges (okx in particular) - this may still limit you to fewer candles - but that's an edge-case that's due to how the exchange works.

**Comment by Arivadis** [comment]
Ah, ok, So «startup_candle_count directly influence on start dataframe length, does not it?

**Comment by xmatthias** [comment]
yes it does.
it's validated - and if you use 10_000 (or some other, insanely high number) - you'll get an error.

if you use something within 5x 1 request (as said, 4999 on binance) - you'll get this number "almost" guaranteed.
Technically, you can always get fewer candles, for example after an exchange outage / downtime - so  don't "hard-rely" on it - but that'll usually only account for 3-4 hours at maximum - which shouldn't be a real problem.

**Comment by Arivadis** [comment]
Great!

Thank You for help.

Have a nice weekend!
