### ISSUE TITLE
/stopentry related to adjust_trade_position method

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8030]
How is /stopentry behave related to adjust_trade_position method ?
If I activate /stopentry , will the bot continue or not to buy new DCA orders ?

**Comment by xmatthias** [comment]
`/stopentry` is technically simply setting `max_open_trades` to 0.

it'll therefore prevent new initial entries - but will not automatically prevent trade adjustments.

It's also questionable if that's actually desired (at least in all scenarios).

Just because i don't want any NEW Positions (effectively slowly winding out of all positions) doesn't necessarily mean a bot can't continue to manage existing positions - including increasing or decreasing that position depending on the strategy rules.

**Comment by dobremha** [comment]
I agree with you, that's how I imagined it too. 
However, I was not 100% sure because the documentation does not specify this aspect very clearly, regarded to orders generated by "adjust_trade_position".

Now that we know what it does, if we dont't want "adjust_trade_position" to buy when /stopentry (aka max_open_trades = 0) is enabled, simply check "max_open_trades" inside "adjust_trade_position" before buy, and if = 0 only sell (-decrease stake)  or do whatever you want.

**Comment by xmatthias** [comment]
yes that's correct.

make sure to check it with `self.config['max_open_trades']`.
