### ISSUE TITLE
Custom stoploss callback not updating the stoploss

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#8038]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: 3.10.7
  * CCXT version: 2.6.39
  * Freqtrade Version: freqtrade 2023.1.dev-81349c2a0
  
## Your question

I wanted to use a different stoploss for a certain enter_tag. So I wrote the following in the custom stoploss callback

```
        if trade.enter_tag == 'this_buy':
                return -0.087
```
Where "this_buy" is one of the enter_tags. Of course after declaring:

```
stoploss = -0.044
use_custom_stoploss = True
```
Unfortunately this didn't pan out. I checked the status of a just bought asset using telegram status it still showed initial stoploss as -0.044. Does anyone know how to go about setting custom stoploss for a particular enter tag?

I will be grateful.

**Comment by xmatthias** [comment]
if you carefully read the [custom_stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) documentation, it'll read:

> The traditional `stoploss` value serves as an **absolute lower level** and will be instated as the **initial stoploss** (before this method is called for the first time for a trade), and is still mandatory.

_Highlights added for clarity_

What you're seeing is therefore expected (and documented). 
Your stoploss will work - but since it's bigger than the initial stoploss - it'll only take effect once your trade is in profit "enough" to become a trailing stoploss (basically once "profit > -4.4% + 8.7%" (or > +4.3%). until then, it's ignored, and the absolute stoploss will take precedence, as it's higher than your new stoploss.

**Comment by stash86** [comment]
set the hard stoploss higher(or lower is better term?) than all your custom_stoploss values, for example -0.1.

stoploss in freqtrade can only be raised (in long position/spot) and can't be lowered. Once you set the initial stoploss at -4.4%, it can't go down to -8.7%

**Comment by moinonin** [comment]
thanks @stash86 this worked.
