### ISSUE TITLE
Some process questions

### ISSUE THREAD

**Issue by naujoks-stefan** [freqtrade/freqtrade#8039]
## Describe your environment

  * Operating system: macosx
  * Python Version: 3.10.7 64-bit (`python -V`)
  * CCXT version: 2.1.96 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Good morning dear Freqtrade team. I have two technical questions about the processing of freqtrade:
1.) When populate_indicators is called, are the 1000 dataframes recalculated with the indicators or only the new ones added?

2.) I want to use a confirm_trade_entry to set explicit values in my custom_trade_info{} at this point. If I call this in live/dry
dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
current_candle = dataframe.iloc[-1].squeeze()
I get the actual current_candle. What happens during backtesting? The background is that I want to get the current_candle at which the trade process should be triggered as in live/dry.

3.) Large time difference: I have a timeframe of 5 minutes in my strategy. Now I have noticed "frightening" things in live/dry.

        date                                           close
999 2023-01-21 09:10:00+00:00  0.7874 but the processing in populate starts at 2023-01-21 09:17:13

The last candle in the 5m timeframe should close at 2023-01-21 09:14:59+00:00. So I have a delay of about 2 minutes between populate_indicators and the last candle. This is an eternity/ a lot has already happened for a 5 minute chart. This also explains the "enormous" deviation between backtesting and dry live for me.

Best
stefan

**Comment by xmatthias** [comment]
> 1.) When populate_indicators is called, are the 1000 dataframes recalculated with the indicators or only the new ones added?

there's no 1000 dataframes, but 1000 rows.
Indicators are generally calculated across all rows. 
The dataframe you get in populate_indicators is a "fresh" one - with only ohlcv columns available.



> 2.) I want to use a confirm_trade_entry to set explicit values in my custom_trade_info{} at this point. If I call this in live/dry dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe) current_candle = dataframe.iloc[-1].squeeze() I get the actual current_candle. What happens during backtesting? The background is that I want to get the current_candle at which the trade process should be triggered as in live/dry.


You'll get the data up to the current candle - as long as you're using this in callbacks, and not in one of the `populate_*` methods.
you can however only use the data you produce there in other callbacks.
best familiarize yourself with the [backtesting execution logic](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic) to fully understand this.

> The last candle in the 5m timeframe should close at 2023-01-21 09:14:59+00:00.

This is a false assumption. A candle is assumed as "closed" the moment the next candle is available, which is earliest at 2023-01-21 09:15:00+00:00 - but more realistically, around 2023-01-21 09:15:01+00:00.

> 3.) Large time difference: I have a timeframe of 5 minutes in my strategy. Now I have noticed "frightening" things in live/dry.

You'll have to ignore startup - as we can't know when you start the bot - and will call populate_* "whenever" it's ready.

Assuming you take the time at the start of `populate_indicators()` (the very first populate call that's made) - then this is a sign of one (or both) of the following things
* insane (wrong) ratelimit settings) - causing your calls to be delayed (we recommend to NOT change rateLimit settings in the configuration).
* a huge pairlist (freqtrade needs to fetch all data - if you have 100 pairs, then that's 100 calls towards the exchange - obviously always respecting the ratelimit).

If you took the time at the end of `populate_indicators()` - then it can just as well be your strategy that's taking too long - again, reducing the pairlist (or filtering indicators you don't really need / are slow to calculate) can help.

Obviously ratelimits also depend on the exchange - so on kraken, your pairlist MUST be a lot smaller than on other exchanges, simply due to their rateLimits.

**Comment by naujoks-stefan** [comment]
Thank you very much for your answers. I apologize for my "unclear" formulation. You are of course right about dataframe. However, you have given me the correct answer in terms of content.

Now, again to my 3rd point:
I already get the time output when I call it and not at the end (right at the first line). That is, 2m pass between the receipt of the last closed candle and the call to populate_indicators. I have a manageable number of coins on the whitelist (20). My entry in the configuration is exchange : {...
"ccxt_config": {"enableRateLimit": true},
"ccxt_async_config": {
"enableRateLimit": true,
"rateLimit": 200
},
Your statement is dependent, I don't understand when I start the bot. Do you trigger the query on binance or do you get the data for the timeframe from binance-push and then process it?

**Comment by xmatthias** [comment]
i'd advise to remove the `"rateLimit": 200` clause. It's slower than what binance can go (by quite some) - and has not been in any recommended configuration for binance for at least a year (more likely longer).
I'd have to look at the commit log / ccxt updates to know for sure since when this changed - but it's not been recently for sure.

When the bot is started, freqtrade will initially fetch candle data for all pairs.
Depending on `startup_candle_count`, this can also be more than 1 request per pair.

Timing on the first iteration is not defined - and the strategy will be called whenever the data is ready (1s after the candle, or 4m after the candle).
After that, it's usually stable (assuming stable network, obviously).

You can use `ignore_buying_expired_candle_after` to avoid late entries if that's a concern - which i usually set to ~half a candle (at least on 5m candles) - and to something around 5m on 1h candles (but it's obviousy up to you to come up with numbers that make sense for you).
