### ISSUE TITLE
Entry strategy - price type change

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8043]
Describe your environment
Operating system: Ubuntu 22.04.1 LTS
Python Version: 3.10.6
Freqtrade 2022.11
CCXT 2.1.96
Freqtrade running in docker : docker-compose up -d
Echange: Binance

Is there is a possibility to use 'entry': 'limit' order type for first entry, and after that use 'entry': '**market**' order type for next DCA orders in the same trade ?
For first entry, price setup is through custom_entry_price; but for next DCA's I don't want to use custom_entry_price or adjust_entry_price anymore, only market.

**Comment by xmatthias** [comment]
no you can't.

But i'd advise against using market orders in general.
It's placing an order hoping there's enough volume at the other side - without any "maximum" slippage defined.

Instead, you can simply use a price on the opposite side of the orderbook for the limit order.
That is called a marketable limit order - which will usually be filled immediately.

You could for example place a buy order for BTC at 100_000$ today - since today's price is around 23_000$ - it'll fill at the best ask price (not at 100_000) - and as such - behave like a market order.

If you're not going for "insane" prices (like i did above), but instead 1-2% up (at maximum) - you'll also do a "safe" market order - which potentially won't fill - but if there's no volume on the other side - that's usually the desired behavior anyway.

**Comment by dobremha** [comment]
Initial order is fine, I get price from last candle, make some adjustments in custom_entry_price, all good.
My problem start's width my DCA, to put a correct price in DCA limit order's.
Because I don't know how to tell in custom_entry_price that it's an DCA order and has to be another logic for limit price (for ex. -1.5% from entry price or get current price). On DCA orders, custom_entry_price is doing same thing like on initial entry order.

So for DCA's I have to run adjust_entry_price after custom_entry_price to change limit price in my DCA order, and here I found some problems when I use more than 1 DCA and can't use trade.open_rate anymore (because I want 1.5% or 2% less from **last** filled order not from open_rate), and in some cases I get weird prices from trade.select_filled_orders('buy')[-1].price,
and my problem with rounding that I solved 99% but I still get one bad case in about 100 orders where the DCA never get filled.

So, how do I check in custom_entry_price if it's a DCA order, to get rid of adjust_entry_price call ?

**Comment by xmatthias** [comment]
i think pricing should be dependent on the market  / market situation - not on "Is it a dca order or not".

Since you're in a callback, you can simply use the [`Trade.get_trades_proxy()`](https://www.freqtrade.io/en/stable/trade-object/#get_trades_proxy) - filtering on the pair you're in, and for open trades only.

If you get a response, you're in a trade. If you get no response - it'll be the initial price.

---

From afar, it sounds like you're pricing your orders to be open for quite some time (pricing them off spot ...).   
You should be aware that having an open order pauses most other activity for a trade (namely exit checks like stoploss, roi, exit_signal, ...).
While an order is open - only the order-relevant callbacks (timeout, adjust-entry) are called.

**Comment by dobremha** [comment]
Thanks, i will try get_trades_proxy.
Regarding order placement, only first order is like you say. Next DCA's should be filled fast (ideal would be "market"), limit price will be current price, so I hope it fills fast.

**Comment by dobremha** [comment]
Hallo Matthias,

_While an order is open - only the order-relevant callbacks (timeout, adjust-entry) are called._

I hope what you wrote above is valid only for that pair/trade/order that have open order, not for all open trades.

For ex. if I have 5 open trades (filled) and 1 trade (unfilled) with 1 open order ; the 5 filled trades will get all the callback's and only the 1 unfilled trade get only order-relevant callbacks.
P.S. it's working, bot has closed other trades and TP even if I have some open orders .

**Comment by xmatthias** [comment]
of course it's per trade - but especially when using DCA orders - it can impact any of the "filled" trades - which are waiting for another fill (or partial exit) - and then "dump" into nirvana, missing their stop.

**Comment by dobremha** [comment]
I use check_entry_timeout and close after 2 min unfilled orders. 
Normally they fill instantly because I use your recommendation and my DCA limit orders act 95% like a market order, but you never know, therefore second protection is check_entry_timeout...
Many thanks for your input, information with not all calls active when we have open orders is very important ! It should be a big highlight somewhere in the DCA-Doku.
