### ISSUE TITLE
How to specify a custom config.json when using docker?

### ISSUE THREAD

**Issue by Seb90258** [freqtrade/freqtrade#8055]
Hi, my first question here. 
I use Docker & Docker Compose and created an additional config file (configFutures.json) in which I have whitelisted 1 pair (for testing). In the docker-compose.yml I changed the --config /freqtrade/user_data/config.json to --config /freqtrade/user_data/configFutures.json
I did my `docker-compose down` & `docker-compose up -d`
Ran the command `docker-compose run --rm freqtrade download-data --exchange binance -t 15m 30m 1h 4h 1d --timerange=20210101-20221231`

I can see it's trying to use the original config file in which no pairs are listed which then for obvious reasons is unable to find a pair
`Creating freqtrade_freqtrade_run ... done
2023-01-23 14:00:17,861 - freqtrade - INFO - freqtrade 2022.12
2023-01-23 14:00:17,862 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
...
2023-01-23 14:00:17,912 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2023-01-23 14:00:17,924 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-01-23 14:00:17,925 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-01-23 14:00:17,925 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2023-01-23 14:00:18,300 - freqtrade.commands.data_commands - INFO - About to download pairs: [], intervals: ['15m', '30m', '1h', '4h', '1d'] to /freqtrade/user_data/data/binance`

My question is... do I need to specify which config file to use somewhere else?
I only changed the docker-compose.yml and created a modified copy of the config.json called configFutures.json with 1 whitelisted pair.

I checked the log but it doesn't mention anything about the attempted download, only info related to the default unchanged SampleStrategy

Edit: My workaround was to just modify the original config file instead of creating a custom one so it's not a critical question or something.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template.
We're asking some very basic questions about the version - which will often help us identify why things are working differently than you expect.

---

all commands take a configuration flag (`--config`) - where you can specify an additional config.

If that's not specified, then Freqtrade will attempt to load the file `config.json` - either from the current working directory (`./config.json`) - or from `user_data/config.json` - unless a different command is specified (which is why you've seen freqtrade use the existing (but in your case wrong) file when using the "run" command.


In your case - you need to differentiate - what's specified as `command:` in the docker-compose file is used with `docker-compose up` - but NOT when using run (you're specifying a new command now - so you need to include "everything" that's in the command section of the compose file that appears relevant. 

you'll therefore have to adapt your "run" command to also include the configuration ...
```
docker-compose run --rm freqtrade download-data --exchange binance -t 15m 30m 1h 4h 1d --timerange=20210101-20221231 --config /freqtrade/user_data/configFutures.json
```

**Comment by Seb90258** [comment]
Ahhh... I guess that was the problem then as I didn't specify which config file to use. Thank you so much for pointing this out :-)
