### ISSUE TITLE
Is there a way to have 2 different roi or exit signal attched to specific buy signal

### ISSUE THREAD

**Issue by mathlabelle** [freqtrade/freqtrade#8135]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
If i use multiples dataframe.loc as entry signal is there a way to have different roi or exit signal . Ex; strategy buy when rsi < 30  or close<lowebbband.
Now if we buy based on the rsi signal, i want to sell when > 70 only. And if we bought base on bbband signal i want to sell when above bbupper . Is is a possibility or better run 2 different strategies on 2 sub account.

kinda : if entry reason = a , use exit signal a / if entry reason =b , use exit signal b
Thanks
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Assuming you're after backtesting support as well - you'll have to use the [`custom_exit()` callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal).

you'll get the [trade object](https://www.freqtrade.io/en/stable/trade-object/) - where you got `trade.enter_tag`to play along.

This obviously assumes that you're using entry tags - but i assume you are - otherwise please consult the documentation.
There's even an example that's almost identical to your requirement in the [documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#enter-tag).

**Comment by mathlabelle** [comment]
thanks a lot! completely missed that paragraph in the documentation.
works for custom exit but haven t found anything about if with the tag we can make specific roi and trailing per tag.
