### ISSUE TITLE
Please update pypi

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#8153]
2023.1 from pypi has known bugs that were fixed on dev. Would you please update pypi so who installs it that way can get rid of those bugs? It is currently very difficult for me to switch to git.

The bot tried to buy, created the order that was fulfilled but it crashed without tracking the transaction. I have 4 or 5 transactions with crashes like that on KuCoin, generating great losses.

Thank you in advance

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---


Kucoin is not a supported exchange. 
Investigating and fixing that bug is more time than i intended to invest on Kucoin at this point. 

The current develop version contains several features that i'm not ready to include in a release yet (they require more extended testing), so creating a bugfix release now would mean invest time again to test kucoin again on cherry-picked commits - which i'm simply not ready to do for an unsupported exchange (unsupported as it's known to have a very unreliable API).

The problem is known, and the release log warns users of kucoin to not update.

> It is currently very difficult for me to switch to git.

What you're really saying here "i'm too lazy to use develop".

If your system is setup to be installed from pypi, then installing through git is just a `git clone` away.
You can even use the "download" button on the homepage - and unzip the file you get from that - and run `pip install -r requirements.txt && pip install .` from within the unzipped freqtrade directory.
