### ISSUE TITLE
sdnotify should be an optional dependency

### ISSUE THREAD

**Issue by yurivict** [freqtrade/freqtrade#8167]
sdnotify is systemd's service notification protocol. systemd isn't required on Linux: there are distros without systemd, see [here](https://www.howtogeek.com/713847/the-best-linux-distributions-without-systemd/). systemd is also not and will never be adopted on BSDs.

sdnotify should be an optional dependency to accommodate systems which don't have systemd.

OS: FreeBSD 13.1

**Comment by xmatthias** [comment]
sdnotify is a very "unintrusive" dependency - which installs fine also on systems without systemd installed (including windows) - though obviously it'll be non-functional on such systems.

Unless the dependency is causing errors during install or runtime - i don't really see why we can't install it.

Is the dependency causing any problems on your install?

**Comment by yurivict** [comment]
> Is the dependency causing any problems on your install?

Yes.

On FreeBSD we don't have systemd, and we don't want to create a port/package for sdnotify that is not really needed.

**Comment by xmatthias** [comment]
sdnotify is a python package, installed via pip. why would you need to create a port for it?


Please provide logs of the problem you're encountering while installing sdnotify (most likely triggered by `pip install sdnotify`).

**Comment by yurivict** [comment]
> sdnotify is a python package, installed via pip. why would you need to create a port for it?

Because pip is only a python package manager. Other software often depends on Python packages, so we need to have system packages for python packages. Users also prefer to use system package manager to install software. This is a common practice, please see for example how numpy [is packaged on many distros](https://repology.org/project/python:numpy/versions).

**Comment by xmatthias** [comment]
Numpy is a package that requires a compile step - and is therefore considered a heavy dependency.

sdnotify is a pure python package - and can therefore be installed with pip on all systems.
there is no reason to create a system level package for it - and i doubt there will be any for any other distribution.

So is sdnotify creating a problem while installing on free-bsd (then please provide logs)?

**Comment by yurivict** [comment]
> Numpy is a package that requires a compile step - and is therefore considered a heavy dependency.

System packages are created regardless of the need to compile.



It doesn't cause problems when pip is used. It causes a problem that the sdnotify port shouldn't be created because it is defunct. I am patching it out currently.

**Comment by yurivict** [comment]
PIP is only known in the Python world. Regular OS users can't be bothered to know that Python packages are installed with PIP and not with 'pkg'. For this reason we provide system packages for all popular software.

**Comment by xmatthias** [comment]
> PIP is only known in the Python world

Freqtrade is written in python - so i don't see why using pip should be a problem.

> It doesn't cause problems when pip is used.

Thanks for confirming. this means this is a non-issue for freqtrade.
We assume installation through pip. 
If you can't or don't want to use pip, best install through [docker](https://www.freqtrade.io/en/stable/docker_quickstart/).

---


If you think this is a problem, best provide a Pull Request to the requirements and setup files making sdnotify optional for freeBSD only through a inline condition excluding freeBSD.

example:

https://github.com/freqtrade/freqtrade/blob/9a2f6d241678092c4b9e612f160f8492bcc3d285/requirements-freqai.txt#L8


I don't have a freeBSD system (so i cannot test this) , and have no interest in wasting my time researching how to do this on freeBSD on a theoretical basis (without the actual possibility to test) - there will be no further action from our side.

If you think this is important, we'll be receiving your PR - otherwise i'll consider this as closed - as you confirmed that it's working fine with all supported freqtrade install methods (docker, pip).

**Comment by yurivict** [comment]
@xmatthias Thanks for nothing.

**Comment by xmatthias** [comment]
@yurivict I've invited you to submit a fix - pointing you towards the direction of the fix for something that isn't really a problem - and that's not causing any problem to the user.

Not submitting that means it's not important - confirming my point above.

**Comment by yurivict** [comment]
I'll live with the local patch removing sdnotify, thanks.
