### ISSUE TITLE
ByBit : WARNING - fetch_order() returned exception: "Order not found (pair: BTC/USDT:USDT id: *). Message: Order * does not exist.".

### ISSUE THREAD

**Issue by clbenoit** [freqtrade/freqtrade#8175]
## Describe your environment

  * Operating system: Linux version 5.8.0-1019-raspi (buildd@bos02-arm64-072) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1)
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==2.7.80
  * Freqtrade Version: freqtrade 2023.2.dev-a3b4678ad
  
## Your question

When I run the bot on ByBit (live mode), I got these logs : 

```
2023-02-15 00:36:02,436 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 10
2023-02-15 00:36:12,616 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: BTC/USDT:USDT id: 8c26a9e7-0994-4a40-a411-db3c9e8dfdd1). Message: Order 8c26a9e7-0994-4a40-a411-db3c9e8dfdd1 does not exist.". Retrying still for 1 times.
```
 I tried to : 

- Set stoploss_on_exchange to false, and switched the stoplosses from limit to market orders. 
- Remove all the three files : tradesv3.sqlite*
- Checked that no orders and positions were opened on the exchange "USDT derivatives" when launching the bot

It looks like the bot open orders on the exchange at start (I can see the orders on ByBit UI). But then do not retrieve them...

[freqtrade.log](https://github.com/freqtrade/freqtrade/files/10744423/freqtrade.log)
[FastSupertrendHyperClean.py.txt](https://github.com/freqtrade/freqtrade/files/10744430/FastSupertrendHyperClean.py.txt)
[myConfig.json.txt](https://github.com/freqtrade/freqtrade/files/10744431/myConfig.json.txt)

Thanks a lot for your advice !

**Comment by clbenoit** [comment]
Tried multiple times and it reproduces the same behavior with different pairs

**Comment by xmatthias** [comment]
We've seen / heared this before - your best bet for now is to ignore these messages (even though it's not an ideal situation).

Whenever i've observed it, it's the bybit api that doesn't return a filled order for several minutes - like the order never existed.
in one case, i've had the order show up through the API 8 (!) minutes after it was filled.
This means, the above message continued for 8 minutes.

Freqtrade will recover after a few minutes (once the exchange API actually "refinds" the order).


from a freqtrade perspective, there's little to nothing we can do about this for now.
We hope that the new API version (v5) will help with this behavior once ccxt updates to that API version.

**Comment by clbenoit** [comment]
Thanks for your fast reply, 

It can last for hours in my case... It only happens on filled orders ? Seems to

So I guess we do not expect that this difficulty for the API to send order informations will conduct freqtrade to have not expected behaviors, like impossibility to move a trailing stop on exchange...

Despite it added this logs  : 

`freqtrade.exceptions.TemporaryError: Could not place stoploss order due to BadRequest. Message: bybit {"retCode":10001,"retMsg":"expect Failling, but trigger_price[44635000] \u003e= current[44500000]??1","result":{},"retExtInfo":{},"time":1676486636288}`

freqtrade seems to exit trades, and stoplosses are correctly handled. However even if they are filled, trades stay open for the bot, wich quicky reaches the max_open_trades limit. 

Do I post it on ccxt git ?

**Comment by gaugau3000** [comment]
Hi,

I make some test on limit orders on bybit using ccxt and fetch_order and fetchOpenOrders :

-> `await bybit.fetch_order('c3fbbf96-fcb3-44e1-a980-5a5c88c00dce','ASTR/USDT:USDT')`

` ccxt.base.errors.OrderNotFound: Order c3fbbf96-fcb3-44e1-a980-5a5c88c00dce does not exist.`

-> `await bybit.fetchOpenOrders('ASTR/USDT:USDT')`

`[{'info': {'symbol': 'ASTRUSDT', 'orderId': 'c3fbbf96-fcb3-44e1-a980-5a5c88c00dce', 'side': 'Buy', 'orderType': 'Limit', 'stopOrderType': 'UNKNOWN', 'price': '0.103500', 'qty': '2710', 'timeInForce': 'GoodTillCancel', 'orderStatus': 'New', 'triggerPrice': '0.000000', 'orderLinkId': '', 'createdTime': '1676676248880', 'updatedTime': '1676676248882', 'takeProfit': '0.000000', 'stopLoss': '0.000000', 'tpTriggerBy': 'UNKNOWN', 'slTriggerBy': 'UNKNOWN', 'triggerBy': 'UNKNOWN', 'reduceOnly': False, 'leavesQty': '2710', 'leavesValue': '280.485', 'cumExecQty': '0', 'cumExecValue': '0', 'cumExecFee': '0', 'triggerDirection': '0', 'cancelType': 'UNKNOWN', 'lastPriceOnCreated': '', 'iv': '', 'closeOnTrigger': False}, 'id': 'c3fbbf96-fcb3-44e1-a980-5a5c88c00dce', 'clientOrderId': None, 'timestamp': 1676676248880, 'datetime': '2023-02-17T23:24:08.880Z', 'lastTradeTimestamp': None, 'symbol': 'ASTR/USDT:USDT', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 0.1035, 'stopPrice': None, 'triggerPrice': None, 'amount': 2710.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 2710.0, 'status': 'open', 'fee': {'cost': 0.0, 'currency': 'USDT'}, 'trades': [], 'fees': [{'cost': 0.0, 'currency': 'USDT'}], 'reduceOnly': None}]`

Here we see that fetchOpenOrders work and fetch_order don't. And freqtrade use fetch_order.
I don't know why and if the responsibility is in ccxt or bybit ?

Have a nice day.

Edit  : link to https://github.com/ccxt/ccxt/issues/16880
(happens not all the time)

**Comment by xmatthias** [comment]
That's correct as long as the order is open. 
but the moment the order closes, it'll disappear from the "open_orders" endpoint - but it doesn't "show up" in the "closed orders" endpoint.

seen this delay before on binance (though that's been years ago - and i suspect they fixed it as i've not seen it in a while).
Bybit's V5 api has different endpoint layout - which i think / hope will simplify / straighten this.

**Comment by xmatthias** [comment]
There's little to nothing we can do about this - it's the exchange that (hopefully) improves their API.

It's not about open or closed orders either, but about the exchange not providing an order through the API endpoint.
they even mention this in the API docs, so i guess it's expected from their side.
the v5 endpoints WILL improve this somewhat (there's a "better" endpoint for that) - but so far it's not 100% clear if they are available for isolated futures or not.

**Comment by donmega** [comment]
Just had this issue. So even if this happens, the take profit/stoploss still happens, or do i have to manually monitor the orders on the exchange?

**Comment by stash86** [comment]
you would have to manually handle the trade

**Comment by donmega** [comment]
Thank you @stash86 .
For @xmatthias : It looks like v5 was merged in ccxt a few weeks ago: https://github.com/ccxt/ccxt/pull/16699

Anyway, thank you both work your great work!

**Comment by xmatthias** [comment]
we're using v5 since the ccxt update that happened a few days afterwards.
In my experience, you can "outwait" this message.  

It's an oddity in the bybit API that orders can "disappear" at a certain point.
They're visible / queryable while the order is open. The moment it fills, it can disappear for several minutes.

In my tests (using pre-v5 api), it once took 8 (!) minutes for the order to re-appear in the API (no api endpoint knew about this order, 8 minutes give you lots of time to try different endpoints).
Once the order re-appears though - freqtrade will continue operating as usual.
The delay is also highly volatile - and increased times will only happen in very high volume times.

Unfortunately - v5 is also not reliably used.
bybit built some very odd quirks - which means that depending on the account type (unified or not) and asset type (future, spot, ...) either v5 or v3 is used (depending on what bybit actually supports).
ccxt abstracts this away though - so it'll be a mix of v5 / v3 endpoints that will be used (also depending on the endpoint).

**Comment by donmega** [comment]
Hi @xmatthias ,

Thank you for your good explanation. I understand that this is something you can't do anything about at this moment. For documentation sake, mine also took about 8 minutes to update the orders. I've also attached the log. At around 20:00 about 5 orders came in. After about 8 minutes the orders we're updated in Freqtrade. It was still a mess after that, because some orders did close on the exchange, but they we're still shown in Freqtrade. At around 21:15 i did /delete the orders in Freqtrade (Because they we're already closed on the exchange, not by me, but probably by the bot?). The bot also didn't notify me about 2 closed orders: XCN/USDT:USDT and JST/USDT:USDT. Those are the 2 that i manually deleted.

Once again, i do fully understand that this is something you can't fix, and that it's probably on Bybit's side. For documentation sake i also attached the log, so that you can see what happened.

Thank you very much for your hard work!

[freqtrade.log](https://github.com/freqtrade/freqtrade/files/11047937/freqtrade.log)
