### ISSUE TITLE
HitBTC downloads only 1000 candles regardless of the days requested and timeframe

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#8214]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10 
  * CCXT version: 2.7.80 
  * Freqtrade Version: freqtrade 2023.2.dev-a3b4678ad
  

## Describe the problem:

When downloading the historic data for hitbtc, it only download 1000 candles, regardless of the timeframe or weather you requested a longer timerange.

Using CCXT I'm able to download data from December 2022 so there are available more than a 1000 candles.

### Steps to reproduce:

  1. freqtrade download-data --exchange hitbtc --pairs ETH/USDT -t 5m 1h --days 50
  2. Check downloaded files and the 5m file is too small, only a 1000 candles.

  
### Observed Results:

  * What happened?
  Insuficient data downloaded.
  * What did you expect to happen?
 Last 50 days of 5m candles.

### Relevant code exceptions or logs

```
import ccxt
import pandas as pd

pair = 'ETH/USDT'

exchange = ccxt.hitbtc()

# Set start and end times for data
start_time = exchange.parse8601('2022-12-20T00:00:00Z')
end_time = exchange.parse8601('2022-12-21T01:00:00Z')
 
timeframe = '5m' # 1 day candlesticks
limit = 400 # maximum number of candlesticks per request
ohlcv = exchange.fetch_ohlcv(pair, timeframe, since=last_timestamp, limit=limit)

print(pd.to_datetime(ohlcv[0][0], unit='ms'), pd.to_datetime(ohlcv[-1][0], unit='ms'), len(ohlcv))

```

**Comment by xmatthias** [comment]
it would appear like it's a (newly introduced) bug in the hitbtc API.

you can replicate this with manual calls quite easily:
https://api.hitbtc.com/api/2/public/candles/BTCUSD?period=H1&from=2022-02-11T16%3A00%3A00.000Z&limit=1000
https://api.hitbtc.com/api/2/public/candles/BTCUSD?period=H1&from=2022-02-11T16%3A00%3A00.000Z&limit=1000&sort=DESC

The [api documentation](https://api.hitbtc.com/#candles) does list both calls as valid (sort=DESC is a valid command) - and they don't list any further limitation when passing this command in.

I'm certain this worked before (otherwise we'd not have added this parameter).
Please open an issue against the exchange reporting this. 
If they don't fix it within a reasonable time (give them 1-2 weeks) let me know and we can take a look at this.

Please also keep in mind that hitbtc is not an exchange we actually, actively support. 
This can also mean that you're the first to use this exchange for actual live processing.
