### ISSUE TITLE
How to avoid new trade when conditions still are valid?

### ISSUE THREAD

**Issue by borgeskaiser** [freqtrade/freqtrade#8228]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.9.16  (`python -V`)
  * CCXT version: 2.7.12 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Suppose I have this simple strategy: 
buy when:

-     conditions.append(dataframe['ema5']>dataframe['ema9'])
-      conditions.append(dataframe['ema9']>dataframe['ema21']) 

        
sell when:
-       conditions.append(dataframe['ema5']<dataframe['ema9'])                 

roi: 
-      0: 0,01

The problem is: many times when I've got de 1% of profit and the buy conditions still are valid then another buy order will take place.

I want to "avoid" new trades until all condition become invalidate then validate again.

I've try callbacks (confirm_trade_entry,  confirm_trade_exit) in order to change enter_long and exit_long values but I could not find a solution.

How can I implement this solution? 
	
Appreciate your help.

**Comment by xmatthias** [comment]
Freqtrade has the concept of [protections](https://www.freqtrade.io/en/stable/plugins/#protections) for this.

In your case, `CooldownPeriod` will work, obviously assuming you know how long you wanna lock a pair after a trade.

Keep in mind that for backtesting, this needs to be explicitly enabled via command line flag, otherwise protections are ignored.

An alternative approach can be to use cross ... You usually only want a signal, not a period of signals (the last candle such a signal is active is usually the worst time to buy).
Qtpylib.crossed() might help (look at the sample strategy for actual code samples 😉

**Comment by borgeskaiser** [comment]
Great, it works. 

In addition, your alternative approach is useful in my approach.

Thank you very much @xmatthias.

**Comment by xmatthias** [comment]
well the "alternative approach" should be the default.

we used to call that the "signal" - while the > | < comparisons are more useful as "guards".
obviously there's no difference (the actual signal will be a combination of it all) - but it sometimes helps to think this way - as you want to buy "JUST THEN" - but only when "all these other things guard me" ... :laughing:
