### ISSUE TITLE
Freqtrade open trade with un-expected pair

### ISSUE THREAD

**Issue by BorixLin** [freqtrade/freqtrade#8251]
## Describe your environment

  * Operating system: local=win10+VScode, Remote=AWS EC2 Linux
  * Python Version: 2.7.18 (`python -V`)
  * CCXT version: 2.7.12 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
My whitelist only have ETH/USDT and BTC/USDT:
```
"exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT"
        ],
        "pair_blacklist": [
            "BNB/.*",
            "FET/.*"
        ]
    },
    "pairlists": [
        { "method": "StaticPairList" }
    ],
```

but when I dry run I see many pairs on freqUI that they are not in whitelist:
![image](https://user-images.githubusercontent.com/121042887/221761556-e050dbc2-93a4-4d35-8600-98d1ac854812.png)
I use sample_strategy 
Where I didn't set well ?
Appricate for your guidance

**Comment by xmatthias** [comment]
best check the "pairs combined" tab in the multi-pane view (next to this pairlist one).

The pairlist itself will only contain BTC/USDT and ETH/USDT (spot pairs) - but from the looks of it, you're running this with a non-empty database, which contains open positions for the other 4 pairs (which are therefore automatically added to the whitelist until the trade closes).

Now the problem is - these trades can't close - as they're invalid for the market you're running on.
When changing market - best start with a fresh database to avoid such issues.

**Comment by BorixLin** [comment]
Yes, solved!! I deleted the database and restart the bot.
Thank you very much!!
