### ISSUE TITLE
Is there any callback to exit the bot?

### ISSUE THREAD

**Issue by marcelo-o** [freqtrade/freqtrade#8265]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8
  * CCXT version: 2.7.69
  * Freqtrade Version: freqtrade 2023.1
  
## Your question

Since we have the [bot_start()](https://www.freqtrade.io/en/stable/strategy-callbacks/#bot-start) callback to start the bot execution, do we have any way to capture when the bot process was terminated?

My intention is to record that the bot was terminated either because the process was aborted or some failure occurred.

**Comment by xmatthias** [comment]
no there isn't - and (especially for the failure case) - it'd also not be a callback that could be guaranteed to be called - so whatever you aim to do with it - it'd not be reliable.

if you think about what can cause a bot to terminate, then that's
* unexpected python errors
* process kill signals
* process terminate signals

While we could (for the most part) capture the first 2 - the 3rd one can't be captured, as the system is killing the process forcefully (no further python line gets executed) - for example in case of  the system running out of memory.

Unfortunately, there can be other signals (other than OOM errors) that can cause this kill - so such a callback would not be reliable - and therefore mostly worthless.

That said - for errors that we CAN capture - we're sending a notification via telegram/webhooks/... - so that failure is recorded.
