### ISSUE TITLE
TP on Portfolio Level = Emergency Exit

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8269]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 22.10
  * Python Version: Python 3.10.7 (`python -V`)
  * CCXT version: ccxt==2.7.12 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.2.dev-1d6738778 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Well it has been discussed multiple times under different approaches, some would take emergency exit based on drawdown (which is exactly Take Profit with trailing for a trade) , some would run away from up or low spikes.

How about to create a function that will monitor (Closed trades / All Trades) ROI, and take actions based on trailing conditions, The data are already there when you use "Profit" button on Telegram:

`ROI: Closed trades
∙ 17.088 USDT (5.34%) (3.23 Σ%)
∙ 17.105 USD
ROI: All trades
∙ 22.234 USDT (3.20%) (4.2 Σ%)
∙ 22.257 USD
Total Trade Count: 13
First Trade opened: 4 hours ago
Latest Trade opened: 22 minutes ago
Win / Loss: 6 / 0
Avg. Duration: 1:17:53
Best Performing: CFX/USDT:USDT: 6.91%
Trading volume: 5087.291 USDT
Profit factor: inf
Max Drawdown: 0.00% (0 USDT)`

In the above example, All trades ROI is at 4.2%, maybe I would set Portfolio TP at 4.5% and if that hit i want to sell market, cool portfolio down for x min then start again.

Another parameter will be needed, might be called "ROI Baseline" where this is all trades ROI from last emergency exit, as regular all trades ROI is accumulating.

High level thoughts, something I see portfolio doing great but not to levels of TP per trade so was thinking how about a reset and a restart.

**Comment by xmatthias** [comment]
I'm not sure why you would want to take profit at "portfolio reached 4.5%".
Your trades are going well - so why would you "reset"? you could end up selling a trade that you entered 20 seconds ago - and that would end up spiking another 10% (assuming you have a good strategy).

in general, i think all trades should be treated independently. Sure, if "the market" drops - most coins will follow - but this approach will clearly not protect you from that.

also after the restart, you'd have reached the 4.5% profit already (the moment the next trade goes to 0.1% profit) - so you'd end up in an endless sell cycle.

It should be pretty simple to code something like this through `custom_exit()` - but i don't see freqtrade providing such functionality "builtin" - mainly because i think it's a bad idea, but then also because there's way too many variability in what logic people would ACTUALLY want to trigger their "inferno" scenario.
