### ISSUE TITLE
Please add validation for whitlist

### ISSUE THREAD

**Issue by eromoe** [freqtrade/freqtrade#8290]
## Describe your environment

  * Operating system:  win 10
  * Python Version: 3.8
  * CCXT version: ccxt==2.9.4
  * Freqtrade Version: freqtrade 2023.3.dev-5d9868b54
  

## Describe the enhancement

For this issue https://github.com/freqtrade/freqtrade/issues/8289

I made mistake on pair string. 
```

"exchange": {
        "name": "binance",
     ....
        "pair_whitelist": [
            "BTC/USDT"
        ],
    },

```

It would be much better to throw a warning  if   `downloaded_pair_number != len(pair_whitelist) `  .

**Comment by stash86** [comment]
Well, if you read the log, it gave warning that your whitelist is empty.

**Comment by xmatthias** [comment]
The log will contain warnings that the whitelist is empty.

also the `downloaded_pair_number != len(pair_whitelist)` point does not hold. I could download 200 pairs, but only run the bot on 20. There's 0 reason to prevent the bot from starting in such a situation.

You seem to be  only using `StaticPairlist` - but that's just one possibility.
Even with StaticPairlist - you can define dynamic, regex-based pairlists - which can expand to different pairlists depending on newly listed pairs on the exchange.

Freqtrade also supports multiple different, dynamic [pairlists](https://www.freqtrade.io/en/stable/plugins/#available-pairlist-handlers)  (some of them providers, generating a pairlist, some of them filters) - which - due to their dynamic nature, will provide different outputs depending on different circumstances.


To fully answer the title of the issue:
Freqtrade DOES validate the pairlist against available pairs on the exchange. It'll log which pairs have been removed - and if none is left, will warn with "no pair in whitelist".
As such - i'd think that we have this functionality already.
