### ISSUE TITLE
freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for FET/USDT:USDT is unavailable for Binance

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8308]
## Describe your environment

    Operating system: Ubuntu 22.10
    Python Version: Python 3.10.7 (python -V)
    CCXT version: ccxt==2.7.12 (pip freeze | grep ccxt)
    Freqtrade Version: freqtrade 2023.2 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Running on Futures (Binance)
  2. Certain pairs will stop bot and generate message: freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for FET/USDT:USDT is unavailable for Binance 

  
### Observed Results:

  * What happened?
  * freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for FET/USDT:USDT is unavailable for Binance
  * 
  * What did you expect to happen?
  * Bot to execute or to ignore trade

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

Reference issue:
https://github.com/freqtrade/freqtrade/issues/7485#issuecomment-1258987878

**Comment by xmatthias** [comment]
Depending if you're using live or dry-run, the answer will differ slightly.

For dry-run - newly listed (futures) pairs will depend on a manual refresh of the leverage tiers - as the binance endpoints require valid API credentials.

You can also run this yourself - as documented [here](https://www.freqtrade.io/en/latest/developer/#update-binance-cached-leverage-tiers) - and we're happy to get a pull request for this. Just make sure to do a "sanity check" over the diff - to make sure not "everything" changed.

For live - it would mean that the leverage tiers are outdated - which can be fixed with a simple restart of the bot (live will reload the tiers on startup).


---

for `FET/USDT:USDT` specifically - i don't really see your point. 
It's included in the cached file for 2023.2 - therefore i assume that your above stated version is not the one you're actually running
