### ISSUE TITLE
BTC/USDT:USDT

### ISSUE THREAD

**Issue by Goullies** [freqtrade/freqtrade#8314]
Hi Team,

I am running Freqtrade (Volume pairs) and it is searching for */USDT:USDT instead of */USDT. Has anyone come across this issue and how did you solve it?

Kind regards,

**Comment by Goullies** [comment]
![Screen Shot 2023-03-13 at 2 56 46 pm](https://user-images.githubusercontent.com/109409377/224604813-5f5f3870-81f1-44c2-8136-93dee8848dd0.png)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The pairs themselfs are valid [futures pairs](https://www.freqtrade.io/en/latest/leverage/#pair-namings) - so you've simply configured the bot to run on futures (intentional or not).
