### ISSUE TITLE
Different Leverage between Dev and Stable

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8329]
## Describe your environment

  * Operating system: Ubuntu 22.10
  * Python Version: Python 3.10.7 (python -V)
  * CCXT version: ccxt==2.8.17 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I have 2 bots, one running 2023.3.dev-5c280d564 and the other 2023.2.

2023.2 : Gives some pairs leverage X1 despite having leverage on 10
2023.3.dev-5c280d564: Gives always the right leverage X10

1- Why is that?
2- How can I switch 2023.2 to dev version to get the right leverage?

**Comment by xmatthias** [comment]
on live, freqtrade will always use the data provided from the exchange.
on dry-run (for binance) - we need to cache the data provided by the exchange, as it would require an authenticated call - and we assume dry-run doesn't have API key's available.

We therefore need to update this cached data from time to time.

We try to do this right before a new release - but we will not do new releases due to this.
If you require this data to be updated more frequently (as you're trading newly listed futures pairs), then you can update it yourself [as documented](https://www.freqtrade.io/en/latest/developer/#update-binance-cached-leverage-tiers).

**Comment by naif824** [comment]
Apologies for re-openning this again, I have created a file called Binance.py in the root folder with API key and secret, now sure how to update the tiers? tried multiple commands with no luck.

**Comment by xmatthias** [comment]
well whenever i'm doing this, i use the [documented way](https://www.freqtrade.io/en/latest/developer/#update-binance-cached-leverage-tiers) in an interactive shell, so this way is clearly working.
