### ISSUE TITLE
atr stoploss for short position help

### ISSUE THREAD

**Issue by mathlabelle** [freqtrade/freqtrade#8332]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
if i used the following does it make sense?
``` python
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
                        
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # Look up trade candle.
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        candle = dataframe.iloc[-1].squeeze()
        if trade.is_short==False:
            return stoploss_from_absolute((trade.open_rate - ((trade_candle['atr'] * 2))), current_rate, is_short=trade.is_short)*trade.leverage
        if trade.is_short==True:
            return stoploss_from_absolute((trade.open_rate + ((trade_candle['atr'] *2))), current_rate, is_short=trade.is_short)*trade.leverage
```
or i should use what is in the doccumentation and it ajust by itself when going short : 

``` python
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
                        
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        
        candle = dataframe.iloc[-1].squeeze()
        return stoploss_from_absolute((current_rate - ((candle['atr'] * 2)*trade.leverage)), current_rate, is_short=trade.is_short)
```
also, does my custom exit make sense:
``` python
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

        
        if trade.is_short==False:
            if current_rate > trade.open_rate+((trade.open_rate - trade.stop_loss)* self.riskrew.value):
                return 'takeprofitlong'

        if trade.is_short==True:
            if current_rate < trade.open_rate-((trade.stop_loss - trade.open_rate )* self.riskrewshort.value):
                return 'takeprofitlong'
```
thanks

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
whenever using `self.dp.get_analyzed_dataframe` (especially with a filter on trade date) - please ensure that you're checking that you actually got a candle. 
trade open date can age out of the available timerange if a trade is open for an extended period of time - causing unexpected errors.

---

i don't think your 2nd sample will work. 
your assumption is an absolute rate - so you MUST pass in something different for shorts (otherwise the stoploss will be at the wrong side of the entry - resulting in an invalid stoploss) - or the open rate (if you aim for break even after being in profit for a bit).


the "make sense" question is a more difficult one - is it valid python code? yes (at least i assume so).

will it make sense for the strategy you're using? maybe, maybe not. We don't know the strategy's aim, depending on the strategy's trading style, it may make sense, or it won't.

that's what we have backtesting for - if you start it from the UI, you can investigate the trades on a chart as they happened ... which will give you an idea if it behaved like you expected it to - or not.
