### ISSUE TITLE
no module named user_data

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8359]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

After the bot stops due to 'no module named user_data', running 'pip install user_data', seems not to be valid. What command do I need to run? (For your information: user_data of course is a folder, which is present in my system).
In case you need one of the strategies, which may fire this error:
https://github.com/nateemma/strategies/blob/master/archived/ADXDM.py 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
running pip install on random package names can be quite dangerous ... consider yourself lucky that it didn't ACTUALLY install something.

This is clearly caused by your strategy.

`from user_data.strategies import Config` is not an import freqtrade provides, nor will it be a valid import in standard setups.
It's also an import that can fail easily (freqtrade supports different user_data namings through `--userdir`, and should therefore clearly not be done this way.

**Comment by myNextCoder** [comment]
In that case, my post was to early. I was sure, that I have a lack of a certain module. But it is the programmer of the strategies in that GitHub folder, who is following a unusual way (I was not aware of that), is trying to read the values out of the config. After commenting out those parts, the strategy works fine.
