### ISSUE TITLE
How to disable pairlists, which limit max open trades?

### ISSUE THREAD

**Issue by elleszabo** [freqtrade/freqtrade#8362]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.10.9
  * CCXT version: ccxt==2.9.4
  * Freqtrade Version: freqtrade 2023.3.dev-5b2a29110
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
First of all, thank you so much for creating this platform. It is a massive help to many.

I read the wiki on pairlists and the wiki on configuration. However, I can't figure out how to disable pairlists. They're limiting the amount of open trades I can test (purportedly limiting #trades to #tokens in whitelist), and the pair trading strategy isn't even being used to my knowledge. Forgive me if I am misunderstanding the config params or constraints.

I tried deleting the pair trading key from the config file and then the lists themselves, but am getting "no Pairlist Handlers defined," as if I can only trade using pairlists. However, this doesn't make sense, because many of the strategies that I saw in the open source strategy repo don't involve pair trading, to my knowledge. So how do I disable them so that I can trade as many times as I want?

Thank you.
Best,
Elle Szabo

**Comment by Bloodhunter4rc** [comment]
The pairlist is not directly related to pair trading despite what you seem to assume. 

When trading you will have to select what assets you want to trade and this is your pair_whitelist, pair as its consists of 2 assets one being the quote currency BTC/USDT -> USDT for example.

So if your pairlist were empty you would have no assets to trade, and trades will never happen. You will need to tell freqtrade what assets to trade, by setting a static list or a dynamic list like a VolumePairlist.

You are limited to your pairlist, so if you have a pairlist of 50, a max of 50 trades can be opened, if you set your max_open_trades to 50 and have the available funds. There is no position stacking in a dry/live run so that is the limit.

**Comment by elleszabo** [comment]
edit: nvm

**Comment by xmatthias** [comment]
I'd strongly recommend to read through the full [documentation](https://www.freqtrade.io/) once to get a grasp on how things work.
simply copy/pasting a strategy, hoping it'll work the way you expect it without knowing how freqtrade actually works will probably not work.

For your particular problem - the [pairlist section](https://www.freqtrade.io/en/stable/plugins/#pairlists-and-pairlist-handlers) will be what you need.
No pairlist -> no pairs to trade -> the strategy has nothing to do.
having at least one pairlist defined is mandatory - otherwise your bot will simply do nothing.
