### ISSUE TITLE
any solution to use historical data and market data to have more candles available?

### ISSUE THREAD

**Issue by dademiller360** [freqtrade/freqtrade#8375]
## Describe your environment

  * Operating system: win 11
  * Freqtrade Version: freqtrade 2023.1
  * Docker Desktop: 4.17.1

## Describe the enhancement

Hi everyone. This question has already been made I would like just to be sure I didn't miss anything

The problem genesis is:
I'm building an indicator that needs more than 1 year of 1h candle data to work.
Live trading with this kind of data is impossible in this case, both for the time needed to create the indicator and the limit of the download candle from the exchange.

There is any currently any WIP solution?

I was thinking to build a service (maybe using directly a custom freqtrade) to download historical data from the date I need and populate the dataframe, the dataframe will stay in memory and I will feed the dataframe with 1h candle with market data
I will use than producer/consumer mode of freqtrade to receive the dataframe 
I'm probably missing a lot here, but I will work on it
Any tips? 
Thank you very much

**Comment by xmatthias** [comment]
freqtrade supports up to 5x the amount of candles an exchange - so if we assume binance (1000 candles per call)- that's 208 days.

If you need more data, then a higher timeframe is sufficient in all cases i've seen so far (think about an SMA - if you do an SMA of 6000 - it'll not really differ from an EMA of 3000 on 2h candles, which will give you >400 days).

Now in theory - the 5x limit is just a number that can be increased in theory - but depending on the rest of the configuration (e.g. volumepairlist) - can slow down the bot quite some as it'll need to do potentially 100ds of calls (in your case not, but people can (and will) configure the bot to use 1 year of 5m data ...).

Depending on the exchange - this can be problematic and delay one bot loop for minutes.

**Comment by dademiller360** [comment]
thank you very much matthias
your description is really clear but I have a problem with this type of implementation (as you mantioned)

my indicator, basically, has to calculate a time based pattern, so it has to iterate (loop into it, can't do it vectorialized, knowing that is really time consuming) through the entire number of candle, in this case around 10.000 candles

do it with the "standard method" will take around 10 minutes per pair, so it would not be feasible in live trade mode.

The only solution I can see is to download historic data, calculate the df and keep it in memory while it listens for market data and add into it, when it completes the new candle (in this case 1h), a new row, and process from there, so I don't have to recalculate the entire thing to every new candle.

I'm quite sure (hope it at least) I can create an independent module that expose via WS the df to FT that will works on the trades, just thinking if it can be useful if I try to implement it as a feature directly on FT, useful maybe as I mentioned, as a producer/consumer mode feature

**Comment by xmatthias** [comment]
to be honest - keeping the **analyzed** dataframe around is not supported - and that's intentional (i don't have plans on changing that).
While it may limit very specific usecases - it'll be problematic for most other users / usecases where this is clearly unexpected.

The thing i **can** imagine is to extend the historic timerange available to beyond 5x <exchange request length> - but this will surely not extend to the analyzed dataframe, which each candle will get a fresh dataframe.

---

I guess with a bit of imagination, you can do what you need in your strategy.
Load downloaded (historic) data - `dp.historic_ohlcv()` - and combine it with the live dataframe (maybe on startup, or based on some "dataframe is not in local custom data dict").

you can then save probably that in some [strategy-local custom dict](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information) - from where you retrieve it when a new candle arrives, append the new candle to that - and run your calculation on just that candle (obviously it's up to you to ensure this is neither a memory leak - and memory consumption for this strategy will be rather high).

if you take 10m per pair to analyze - you might wanna store the analyzed data (so the next restart won't take 2 hours) - but that's obviously up to you (and how you define your logic within your strategy).

**Comment by dademiller360** [comment]
perfect, thank you very much for your info matthias

since you said it's not planned for FT, I will build an external module, 
to have more freedom and avoid FT scheduler, and use produce/consumer mode to "link" them,

I will publish it , if anyone will ever need it

thanks again for your support
