### ISSUE TITLE
How to set up a strategy to long spot and short futures

### ISSUE THREAD

**Issue by yuanye72** [freqtrade/freqtrade#8414]
Hi folks,

New to freqtrade. I have a trategy that will take both long and short position. I'd like to enter long position in spot market and short position in futures. Is there a way to switch trade_mode from spot to futures in the configuration file automatically when switching from long to short?

Appreciate your help

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

trading-mode is per process - you can't dynamically switch between the two. so you'll either have a spot bot - or a futures bot - but not a combined spot/futures bot.

You can however run [multiple instances of freqtrade](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) - each with settings that correspond to what you'd like.

**Comment by escanoro** [comment]
> Hi folks,
> 
> New to freqtrade. I have a trategy that will take both long and short position. I'd like to enter long position in spot market and short position in futures. Is there a way to switch trade_mode from spot to futures in the configuration file automatically when switching from long to short?
> 
> Appreciate your help

adding to @xmatthias 

Since the configuration files accept either `Spot `or `Margin`, you cannot use the same config file to achieve your goal.
Instead you can clone the config file : One for **Spot** and one for **Margin**
1- `trading_mode : spot`
2- `trading_mode: margin`

You need also to clone your Strategy, and:

1- Comment/Remove the **Enter Short section** for the **Spot** scenario
@xmatthias : Is this necessary ? Or freqtrade wil ignore EnterShort when  `trading_mode : spot` ?

2- Comment/Remove the **Enter Long section** for the **Margin** scenario


Cheers,
Escanor

**Comment by xmatthias** [comment]
a spot bot will never go short - as the markets won't allow this.

[signal collision rules](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) will however still apply, even though the shorts would not be acted on.

**Comment by yuanye72** [comment]
appreciate your help @escanoro @xmatthias . I will most def. follow the issue template in the future. and sorry for the honest mistake from a first-timer

**Comment by xmatthias** [comment]
No worries at all - it's a template | friendly reminder - as we've seen this missing many times - where it's then causing unnecessary back and forth - where in the end it turns out that the version used is simply outdated.
