### ISSUE TITLE
How do I shift the RSI like in the example RL model?

### ISSUE THREAD

**Issue by BurningSpy** [freqtrade/freqtrade#8431]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.9.7 (`python -V`)
  * CCXT version:  3.0.43 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-2023.4.dev-19e112f3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, 
So I am trying to set up my RLModel and since this is my first time using freqtrade RL I thought I just copy paste the things from the documentation. However, in the calculate_reward function in the example MyRLEnv in from this [docu ](https://www.freqtrade.io/en/stable/freqai-reinforcement-learning/) it simply says 
"Assumes the shifted RSI indicator has been generated in the strategy."

The Problem is that in the example strategies that I could find the shifted RSI Indicator was not generated and I am not yet experienced with the indicator and how to shift it. 

I saw a user ask pretty much the same question a week ago with no result due to him not filling out the form. So I hope I'm not missnig any information and maybe you could point me in the right direction to look. I could not find any strategies using the shifted indicator, so I'd appreciate your help.

Thanks in advance

**Comment by xmatthias** [comment]
The answer in #8406 did actually include the answer - which is to point towards the [appropriate documentation part (feature engineering)](https://www.freqtrade.io/en/stable/freqai-feature-engineering/#feature-engineering), which describes how to generate features (look at `feature_engineering_expand_all` in detail ...)
It got no further comment for a week and was therefore closed, assuming the user was able to get it working based on the documentation.

it's the basis for all further freqAI strategies - and explains how indicators are created  (including how shifted indicators are created).

The sample strategy will also create the shifted RSI indicators (e.g. `'%-rsi-period_10_shift-1_XMR/USDT:USDT_1h'`) - but i think the docs contain a slight typo, where 

`rsi_now = self.raw_features[f"%-rsi-period_10_shift-1_{pair}_{self.config['timeframe']}"].iloc[self._current_tick]` would be the correct version (`_` instead of `-` after the period).

**Comment by BurningSpy** [comment]
First of all thanks for the quick reply. 
I think the sample strategies didnt generate the shifted indicator there, however I just found  that the strategy migration page does show how to shift all the indicators 

indicators = [col for col in informative if col.startswith("%")]

```
 if n == 0:
         continue
     informative_shift = informative[indicators].shift(n)
     informative_shift = informative_shift.add_suffix("_shift-" + str(n))
     informative = pd.concat((informative, informative_shift), axis=1)
```

where it adds the _shift + n bit as suffix
Just that the pair is at the start of the string. 

```
 t = int(t)
            informative[f"%-{pair}rsi-period_{t}"] = ta.RSI(informative, timeperiod=t)
```

Thanks for the help anyway

**Comment by BurningSpy** [comment]
I just realized I totally misunderstood your hint with the typo since the expand all should indeed expand this correctly. 
My bad, just got it. It's just a typo :D 
I'll close the ticket
