### ISSUE TITLE
Is there a way to realign the available capital for two different bots

### ISSUE THREAD

**Issue by yuanye72** [freqtrade/freqtrade#8449]
## Describe your environment

  * Operating system: _Amazon Linux___
  * Python Version: _3.9.16____ (`python -V`)
  * CCXT version: _3.0.48____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade 2023.3___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, I have developed a long/short strategy, in which the positions are either long 100% of the portfolio, or short 100%. To achieve that, I have split my strategy into two bots, one to trade the long positions in spot coin, and the other to trade the short positions in futures. 

The challenge I have is how to allign the trade size of the two bots. Assume I assign available_capital=50 to each bot . After a day, the long bot has profitted and capital grows to 60 (while the short bot does nothing with the assigned capital of 50). On the second day the strategy signals short, I'll have to close the long position with the long bot and enter a short position of 60 (that matches the newest available capital of the long bot) with the other bot. Is there a way to automatically allign the assigned capital of the two bots?

I have read through the guide twice and couldnt find a solution. Read the dynamic stake amount section multiple times. I intend to set up the strategy this way is to avoid entering long future positions and avoid paying interests. 

If you would kindly share some thoughts on how to solve this creatively, i'd greatly appreciate.

Thanks very much

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I'm not sure which exchange you're on - but as far as i can remember, all exchanges i used so far (for futures) do use different wallets for spot and futures markets - so you can't really use a "combined 50$" anyway - but you have to have 50$ in the spot wallet, and 50$ in the futures wallet for this to work.

As such - you also can't really assume that "spot bot made 10$ profit - now enter 60$ short on futures markets". That's not how it works - as the futures wallet will still only have 50$.

---


assuming you got an exchange with combined wallet (doubt we support one of these - but surprise me ...).

You definitely can't use `available_capital` - as that's the absolute starting point  for the bot (it will assume non-self gained capital as "not mine to touch").

You **might** be able to use something around `tradable_balance_ratio` - which would scale (more or less) dynamically based on the changing account outside of the bot. 
It'll however assume that the remainder of the account isn't changing in great ways - otherwise i think it'll be difficult to actually handle this.

---

assuming the 2 positions always contradict (you're only either long OR short) - then why not use one combined strategy, and use futures markets for both?
Futures fees are usually lower than spot fees (for whatever reason) ... so i don't really see a point in going long on spot, and short on futures (obviously you can't go short on spot ... but i don't really see a reason for this unnecessary complexity).

**Comment by xmatthias** [comment]
Closing this as i think/hope your question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Comment by yuanye72** [comment]
> I'm not sure which exchange you're on - but as far as i can remember, all exchanges i used so far (for futures) do use different wallets for spot and futures markets - so you can't really use a "combined 50$" anyway - but you have to have 50$ in the spot wallet, and 50$ in the futures wallet for this to work.
> 
> As such - you also can't really assume that "spot bot made 10$ profit - now enter 60$ short on futures markets". That's not how it works - as the futures wallet will still only have 50$.
> 
> assuming you got an exchange with combined wallet (doubt we support one of these - but surprise me ...).
> 
> You definitely can't use `available_capital` - as that's the absolute starting point for the bot (it will assume non-self gained capital as "not mine to touch").
> 
> You **might** be able to use something around `tradable_balance_ratio` - which would scale (more or less) dynamically based on the changing account outside of the bot. It'll however assume that the remainder of the account isn't changing in great ways - otherwise i think it'll be difficult to actually handle this.
> 
> assuming the 2 positions always contradict (you're only either long OR short) - then why not use one combined strategy, and use futures markets for both? Futures fees are usually lower than spot fees (for whatever reason) ... so i don't really see a point in going long on spot, and short on futures (obviously you can't go short on spot ... but i don't really see a reason for this unnecessary complexity).

Thanks for your reply earlier. It's helpful. 

Can you elaborate what do you mean by "Futures fees are usually lower than spot fees "?  Are you referring to the transaction fees? We're concern of implied interests for the futures as that number can get to quite rediculous levels sometimes.

**Comment by xmatthias** [comment]
> Are you referring to the transaction fees? We're concern of implied interests for the futures as that number can get to quite rediculous levels sometimes.

Yes i am. 
funding fees (which i assume is what you mean) can go both ways (in your favor or against you). While they do vary - the combination of them is (at least from what I've seen) way lower than what you get on margin markets (assuming you also borrow when going long).

**Comment by yuanye72** [comment]
Thanks Matt. This question is closed. appreciate it.
