### ISSUE TITLE
ERROR - StaticPairList requires

### ISSUE THREAD

**Issue by zukutoke** [freqtrade/freqtrade#8456]
## Describe your environment

  * Operating system: MacOS 12.6.1 
  * Python Version: Docker 4.17.0
  * CCXT version: can't get it from docker
  * Freqtrade Version: freqtrade docker-2023.4.dev-f03a9991
  
## Your question
Hey there! I got an error 
`2023-04-05 18:47:48,748 - freqtrade - ERROR - StaticPairList requires pair_whitelist to be set.`

`docker-compose run --rm freqtrade backtesting --strategy TrendIndicatorStrategy --config /freqtrade/user_data/config.json`
This is command what I use to run backtest

I'm trying use ChatGPT to fix it, but it's can't help. 

My config.json:

```
{
  "exchange": {
    "name": "binance",
    "key": "hidden",
    "secret": "hidden",
    "ccxt_config": {
      "enableRateLimit": true
    }
  },
  "pairlists": [
    {
      "method": "StaticPairList",
      "pair_whitelist": [
        "BTC/USDT"
      ]
    }
  ],
  "stake_currency": "USDT",
  "stake_amount": 100,
  "dry_run": true,
  "timeframe": "30m",
  "strategy": "Strategy",
  "bid_strategy": {
    "price_side": "bid",
    "ask_last_balance": 0.0
  },
  "ask_strategy": {
    "price_side": "ask",
    "use_order_book": false,
    "order_book_top": 1
  },
  "use_exit_signal": true,
  "sell_profit_only": false,
  "ignore_roi_if_buy_signal": false
}

```

I know, that this a frequently error, but I really don't understand what's the problem with Pair List in my config.

**Comment by xmatthias** [comment]
Instead of using chatgpt, please refer to our [documentation](https://freqtrade.io).
We try hard to keep it uptodate, and actually contain useful information.

ChatGPT is just guessing what the next word could be - but will not actually know how freqtrade works (even though it may seem like that - as it can get 80-90% of the things correct).

The config you're using is some mix of old and new syntax - so it'll fail at some point in the future (When we drop the compatibility shim).
Please follow the install documentation - and use `freqtrade new-config` to generate a proper configuration.

For a starter, `pair_whitelist` is in the wrong place and needs to go to the exchange subsection - but i'm not sure that's the only problem in your config.
