### ISSUE TITLE
Effect of Leverage on Backtesting Results: Total Profit % and Max % of Account Underwater

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#8457]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.10.7
  * CCXT version: 2.7.12
  * Freqtrade Version: 2023.1
  
## Your question

When I backtest a futures strategy with a leverage of 1x and 10x both the Total profit % and Max % of account underwater are very similar. Is the leverage taken into account when calculating these values?

**Comment by xmatthias** [comment]
Yes, leverage is taken into account.
As you'll have noticed, they're similar - but not identical.

the [backtesting docs](https://www.freqtrade.io/en/stable/backtesting/#backtesting-report-table) have an explanation on the calculation of each parameter.
Depending on the strategy - they might be very similar. especially for drawdown / underwater - this is most likely because the stoploss (in many cases the major losing reason) relates to the value at stake - not the price movement ([details](https://www.freqtrade.io/en/stable/stoploss/#stoploss-and-leverage)).

The same applies to ROI - so if your strategy depends heavily on these 2, the strategy may turn out to be quite similar.
