### ISSUE TITLE
No trades made

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8475]
I just run the demo. and run ETH with binance 

backtesting is empty, 
I just run the SampleStrategy, why???

it says.. 
No trades made. Your starting balance was 1000 USDT, and your stake was unlimited.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Apart from that, i'd encourage you to read through the [documentation](https://www.freqtrade.io/).

Results will always depend on the markets selected, exchange used and timerange.
with the provided info, it's impossible to actually help you - as the only thing we know is "i got no results with the sample strategy" - which simply means that the strategy didn't find a good entry point.
This could be because you only backtested 1 day  (where no good opportunities were present) - or because only pairs were selected which didn't show the required patterns for trades to happen.

While this is about backtesting - it's also fully covered by this [FAQ entry](https://www.freqtrade.io/en/stable/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet)
