### ISSUE TITLE
Strategy should control bid price

### ISSUE THREAD

**Issue by vertti** [freqtrade/freqtrade#848]
# Idea
Because it's our `Strategy` instance that calculates if the bot should buy or sell, it should be the same Strategy that decides the bid price for that sell/buy.

This would:
- Move another core logic to where the needed information is (ROI tables and buy/sell signals are already in the Strategy)
- Allow for easy extending to new buy/sell logic and techniques

# Implementation

- [ ] remove the current bid/ask balance calculation and related configuration
- [ ] make Strategy return a tuple instead of boolean for buy and sell signal, where the first value is the buy/sell decision boolean, and second is the buy/sell price
- [ ] implement base class for strategy so that old strategies that return just boolean can still be used and the base class will return tuple with default price

**Comment by xmatthias** [comment]
I agree that more logic should be (optionally) in the Strategy.
However, i think we should try to keep existing strategies compatible if possible - as traders (non-coders) may struggle to do the adjustments to their existing strategies.

In addition to the above, i would suggest to also move the following flags to the strategy - however evaluating if the strategy implements them - and otherwise falling back to the default:

- [ ] use_sell_signal 
- [ ] sell_profit_only

**Comment by jblestang** [comment]
How about passing ask/bid/last as  arguments of the populate_XXX functions?

**Comment by vertti** [comment]
@jblestang yep, the buy/sell signal functions will need that info along with the ticker history.

**Comment by iliecosmin** [comment]
Also the same strategy should check if the successful buy will trigger the stoploss sell imediately and not do it or whatever. I observed a loop where the bot buys and the sell imediately with stoploss set at -0.15 several times because of the big difference from the bid and ask prices.

**Comment by yazeed** [comment]
> How about passing ask/bid/last as arguments of the populate_XXX functions?

I was thinking of the missing functionality for buy/sell order pricing, to based on, e.g. current/last candle open/close/high/low.

Potentially I'd like something along the lines of, placing buys at candle open price, instead of orderbook-based price, to match real-time trading with backtesting.

I think it'd be best implemented as an interface method, with one job, buy/sell price calculation, an option when users want something different from bid/sell/last prices available today.

**Comment by yazeed** [comment]
BTW, this says strategy should control bid price, I think this applies for both buy orders and sell orders.

**Comment by yazeed** [comment]
@xmatthias This PR is so under-rated. In live-trading, freqtrade often ends up buying at candle highs, instead of open price due to market volatility, which is completely different from what you'd have backtested against (candle open price). Such a mechanism to control bid price based on candles combined with unfilledtimeout would allow live-trading to become strictly compliant with what one has backtested.

**Comment by xmatthias** [comment]
working on this makes no sense before #2872 is merged - as that introduces the possibility to easily and safely call user code (without risking the strategy callback code to bring the bot down).

Then - while using a custom price may seem tempting - what you're proposing will end up with orders that are stuck forever and won't get filled (your assumption is that price will get back to open - which it very often isn't. 
It's already problematic if you're using orderbook (configured as bids for buying) and you're using a slot higher than 2 or 3 (3 orderbook levels below the current price) - almost all of these orders do timeout after 10 minutes (i'm using 5m candles), since price moved away from the order - or if they get filled, it results in a stoploss soon after as price is dropping long and fast.
