### ISSUE TITLE
Hyperopt and backtesting are very different

### ISSUE THREAD

**Issue by donmega** [freqtrade/freqtrade#8488]
## Describe your environment

  * Operating system: Ubuntu 22.04 / Docker
  * Python Version: Docker (`python -V`)
  * CCXT version: 2.8.17 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

Sorry for the long post, but i am trying to be complete as possible :)

So i have a strategy, and when backtesting the hyperopt, i am getting strange results. The exchange is GateIO
This is the command i use to hyperopt:
sudo docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces buy --strategy multi_rsi_degen --timerange=20220901- --dry-run-wallet 1000 -c user_data/config.json --fee 0.0002 -e 1000 -j 2

Hyeropt results:
![hyperopt](https://i.imgur.com/2xXLdW5.png)
![hyperopt](https://i.imgur.com/Y432TBB.png)

Backtesting command:
sudo docker-compose run --rm freqtrade backtesting --timerange=20220901- --strategy multi_rsi_degen
Backtesting results:
![backtest](https://i.imgur.com/5IdUx5p.png)
![backtest](https://i.imgur.com/8PPvOft.png)
![backtest](https://i.imgur.com/CeyrVMR.png)

What am i doing wrong? Afaik i don't have any lookahead bias in the strategy.
Thank you for your time!

UPDATE: Like xmatthias and stash86 said, this was fixed because i was using the --fee command with hyperopt and not with backtest. Thank you both so much for your support!

**Comment by stash86** [comment]
Remove the fee setting from your hyperopt, or add the setting on backtest command, and try again?

**Comment by xmatthias** [comment]
Your hyperopt assumes a fee of VIP16 (--fee 0.0002, or 0.02%).
Unless you did 3 Billion in trading volume in the last 30 days [source](https://www.gate.io/fee), that's completely insane and unrealistic.
backtesting assumes the most basic fees, which usually correspond to using "non-vip" (or VIP0) fees, since you didn't explicitly specify fees.

The 2 commands will match given the circumstances are the same. You're hyperopting basically without fees - and are then hit by fees, which will result in a more realistic result.
