### ISSUE TITLE
MEXC 4h timeframe not available

### ISSUE THREAD

**Issue by Liapin** [freqtrade/freqtrade#8490]
Trying run freqtrade on MEXC but have following warning:
`freqtrade.exchange.exchange - WARNING - Cannot download (BTC/USDT, 4h) combination as this timeframe is not available on MEXC Global. Available timeframes are 1m, 5m, 15m, 30m, 1h, 1d, 1w, 1M.`

But based on docs they have 4h interval
https://mxcdevelop.github.io/apidocs/spot_v3_en/#enum-definitions

and inside ccxt 4h also present
https://github.com/ccxt/ccxt/blob/master/python/ccxt/mexc.py#L359

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by xmatthias** [comment]
Running `freqtrade list-timeframes --exchange mexc` on an uptodate develop instance shows that the timeframe is available.
The error also doesn't mention that 4h is not available - but that this combination ain't available - which is clearly a difference.

What's not available is BTC/USDT - which is in "maintenance" mode (apparently since [february](https://support.mexc.com/hc/en-001/articles/15149585234969-MEXC-Upgrade-and-Maintenance-of-API-for-BTC-USDT-FTM-USDT-OP-USDT-DOGE-USDT)).
If you're their customer, feel free to complain to their support - but based on some internet research, the usual answer is "it's in maintenance mode, we don't know when it'll be out of maintenance mode again" (or something along those lines).

This same applies to several usually high-volume pairs.

For me, this concluded the test i did with mexc last week - concluding that 
mexc is seemingly unable (or unwilling) to allow trading through the API of some major pairs (ETH/USDT is also inactive, among MANY others) - at least to non-VIP users.
As major pairs are unavailable - that's an exchange i'll not look at in detail - as there's clearly something phishy going on (either they intentionally keep the API disabled to favor internal trading against manual users, or their platform is unstable, where high volume would crash things).
