### ISSUE TITLE
Freqtrade selling on loss and not getting the data correctly from the exchanger

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#850]
## Step 2: Describe your environment

  * Python Version:  python 3.6
  * Branch: Develop
  * Last Commit ID: 7d3eefa97a80337ade8dc7047f15a9875392cf80
 
## Step 3: Describe the problem:

Freqtrade started selling lower than the price where it last bought losing money instead of making profit, before last commit it was selling correctly and making profit. On the same log you can see that the bot most of the time is not able to get the data from the exchanger correctly and it seems to be using old data all the time.

My Config File:  [Config.json](https://pastebin.com/WdSGj3AE)

### Relevant code exceptions or logs:

[Console output using verbose](https://pastebin.com/p15EQdRY)

**Comment by xmatthias** [comment]
the log only shows the `Outdated history for pair ` error - not the buy/sell lower.
would you happen ot have a log for that as well (even if it's not with Debug messages ?

**Comment by xmatthias** [comment]
sorry, but due to #845 i don't think hitbtc2 is ready to be added to supported exchanges.

i'm not certain if the upstream-bug mentioned affects live-trading as well - however i could see differences in the last candle depending on the coin used (ETH/BTC was uptodate, BANCA/USDT was outdated).

i'm going to close this issue for now (so we only keep one hitBTC ticket open). Once upstream resolves the hitbtc2 bug we can retest hitbtc.

Thanks for all your testing effort!
