### ISSUE TITLE
Future USDT: Force Setting Leverage No. to be 20 (on dry run)

### ISSUE THREAD

**Issue by thanatchon36** [freqtrade/freqtrade#8501]
## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: docker freqtradeorg/freqtrade:stable on 15 Apr 2023 (i'm not sure how to check python version inside docker)
  * CCXT version: ccxt==3.0.37 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Here is my code setting leverage at 20
<img width="709" alt="Screen Shot 2566-04-16 at 09 10 35" src="https://user-images.githubusercontent.com/10392423/232262389-4531239e-a20e-49fa-b265-2c5cc2dac9a0.png">

Sometime when taking a position, it uses leverage of 20.
<img width="310" alt="Screen Shot 2566-04-16 at 08 54 12" src="https://user-images.githubusercontent.com/10392423/232261955-ea042753-9785-43b7-be70-6f703fd965f8.png">

Sometimes when taking a position, it uses a leverage of 10 (or not 20).
<img width="295" alt="Screen Shot 2566-04-16 at 08 55 56" src="https://user-images.githubusercontent.com/10392423/232261994-502bd80f-718d-4e96-9b36-9e2c47f4f4d9.png">

Both of the above 2 position entry images use the same "def leverage" as the one mentioned above.

Would it be possible to kindly advise me on how to ensure that every entry uses a leverage of 20 on every symbol pair, as is possible during a dry run? Additionally, I would appreciate your input on how to prevent entry for certain symbol positions if a leverage of 20 cannot be used. If modifying the "def leverage" function is feasible, could you please let me know? Thank you very much for your help and assistance with investigating this matter.

**Comment by xmatthias** [comment]
maximum leverage is not guaranteed across pairs - but will vary depending on the exchange/pair used.

In general, high volume pairs (BTC, ETH) will have higher maximum leverage, while smaller pairs have smaller maximum leverage (also depending on the trade size, usually). This is to limit risk (for both the exchange and the user) - and the actual limits can be found in the corresponding exchange's doc pages.

Freqtrade will (and must) adhere to these limits.
the maximum leverage for that pair is provided as `max_leverage` argument - if your leverage is above that value, we'll adjust it to that (otherwise placing the order would fail).

**Comment by thanatchon36** [comment]
Thank you so much.

**Comment by xmatthias** [comment]
you're also overwriting the max_leverage line in your code - so make sure to not get confused by that (you should try to avoid overwriting incoming parameters).

**Comment by thanatchon36** [comment]
<img width="719" alt="Screen Shot 2566-04-16 at 13 50 22" src="https://user-images.githubusercontent.com/10392423/232278249-c3559fa9-6780-484d-983d-248ca1d7b5ff.png">
So this is correct one. Thank you.
