### ISSUE TITLE
Bitfinex ratelimit errors

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#8637]
## Describe your environment

  * Operating system: ``Linux  6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux``
  * Python Version: 3.10.11
  * CCXT version: ccxt==3.0.75
  * Freqtrade Version: freqtrade 2023.4

## Describe the enhancement

Currently when downloading data in the event of a `429` status code, the bot will use the following function to sleep and apply `DDosProtection`. (I guess for generic)

freqtrade/exchange/common.py

```python
def calculate_backoff(retrycount, max_retries):
    """
    Calculate backoff
    """
    return (max_retries - retrycount) ** 2 + 1


def retrier_async(f):
    async def wrapper(*args, **kwargs):
        count = kwargs.pop('count', API_RETRY_COUNT)
        kucoin = args[0].name == "KuCoin"  # Check if the exchange is KuCoin.
        try:
            return await f(*args, **kwargs)
        except TemporaryError as ex:
            msg = f'{f.__name__}() returned exception: "{ex}". '
            if count > 0:
                msg += f'Retrying still for {count} times.'
                count -= 1
                kwargs['count'] = count
                if isinstance(ex, DDosProtection):
                    if kucoin and "429000" in str(ex):
                        # Temporary fix for 429000 error on kucoin
                        # see https://github.com/freqtrade/freqtrade/issues/5700 for details.
                        _get_logging_mixin().log_once(
                            f"Kucoin 429 error, avoid triggering DDosProtection backoff delay. "
                            f"{count} tries left before giving up", logmethod=logger.warning)
                        # Reset msg to avoid logging too many times.
                        msg = ''
                    else:
                        backoff_delay = calculate_backoff(count + 1, API_RETRY_COUNT)
                        logger.info(f"Applying DDosProtection backoff delay: {backoff_delay}")
                        await asyncio.sleep(backoff_delay)
                if msg:
                    logger.warning(msg)
                return await wrapper(*args, **kwargs)
            else:
                logger.warning(msg + 'Giving up.')
                raise ex
    return wrapper

```

However, this `backoff` does not reflect the real-time waiting time before calling the exchange again.

Many exchanges include in their headers a `retry-after` field with an int to specify how much time must be waited.

![image](https://github.com/freqtrade/freqtrade/assets/53630064/77443dbb-7457-4423-bdd9-f3c16d2cfc22)

I suggest just using this value when sleeping

**Comment by xmatthias** [comment]
We use ccxt to connect to the exchange - which doesn't expose headers back to the caller (at least not directly).

I wonder what settings you're using though - i've downloaded data from many exchanges, and never encountered a 429 when using a supported exchange with freqtrade with ccxt (this assumes the recommended reconfiguration of "no rateLimit" setting).

Kucoin is different - but the error there is 429000 - which actually means something slightly different - and which we hande with "retry immediately".

**Comment by Corfucinas** [comment]
Bitfinex

```bash
freqtrade download-data --exchange bitfinex --pairs .*
/USDT --timerange 20170101-20230501 -t 1d 12h 6h 4h 1h 30m 15m  -v --prepend
```

**Comment by xmatthias** [comment]
well bitfinex is not a supported exchange.

most likely, it's limits are set incorrectly (we assume a default of 500 candles per response), which can either mean that freqtrade does too many requests, or too few requests (holes in the resulting data).
Nobody took the time to test that - so you might encounter other issues, too.

assuming this will load no config (depends if your user_data contains one), it'll use the rate-limits as configured by ccxt. 

If you get 429 from that, then these rate-limits in ccxt are set incorrectly - which can lead to other issues as well.
You should be able to easily reproduce that with ccxt (eliminating freqtrade from the mix), downloading candles in a loop (which will help you report this to ccxt).

Please report this to ccxt (feel free to link to this issue and let us know the result).

as bitfinex is not a supported exchange, i don't intend to do anything further for this issue for the moment (and the way it looks right now, it's something that should be fixed in ccxt).
