### ISSUE TITLE
Is there any way to turn off FreqUI, but turn on api?

### ISSUE THREAD

**Issue by webees** [freqtrade/freqtrade#8653]
It can save a little memory usage, right?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

No it won't.
FreqUI is a pure frontend application - the only thing the backend has to do is serve static files from a directory.

As long as you don't connect to it, there will be no load.
Even if you connect - there will only be load initially (when the static files are pulled into your browser).
The "actual" load will be caused by freqUI connecting to the API - but again, if you don't open it - there will be no load.
