### ISSUE TITLE
use async

### ISSUE THREAD

**Issue by owlswaper** [freqtrade/freqtrade#8656]
Hello, I have made an indicator that has a very heavy and long processing
To make it faster, I want it to be processed async.
Is there a way to use it in freqtrade?

**Comment by ThomasAnderson01** [comment]
I think you should use multiprocess rather than async, and this is not related to freqtrade, anyway, no matter how to  use async, you have to follow"get tick data -> calc signal->trade". So you need to think how to optimize your indicator, there is so many ways  such as multiprocess / cython  / jit / vectorize

**Comment by xmatthias** [comment]
it's unlikely that an indicator can be parallelized properly - as it assumes the indicator logic can actually be parallelized (which i've not seen so far).

A "heavy" indicator almost always means "it must loop, as value in row X depends on the same column in X-1".
With that, the only real optimization will be to go the cython / c / rust / ... route (or try to remove the loop by vectorizing).
