### ISSUE TITLE
WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json

### ISSUE THREAD

**Issue by 2morowMan** [freqtrade/freqtrade#8712]
So the documentation says if you are using Docker, change api server to 0.0.0.0
Yet when starting...    >docker-compose up
there are error messages about it being a bad idea...

and yes, 127.0.0.1 does not work with docker setup.

please advise...

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

It's a warning - if this were used outside of a docker context, it would be insecure.

If the docker-compose port is using 0.0.0.0 or the server IP (instead of localhost / 127.0.0.1) - that would be insecure (however it's not something the container content will see).

**Comment by 2morowMan** [comment]
Thank you for the reply and explanation
(dare i suggest your explanation/comment is included in the documentation?!)
