### ISSUE TITLE
Backtest result is not as same as hyperopt results

### ISSUE THREAD

**Issue by paycoiny** [freqtrade/freqtrade#8716]
It was my strategy bug.

**Comment by xmatthias** [comment]
what's the output of `freqtrade show-hyperopt -n 33` ? (make sure it's using the correct hyperopt file, the command will by default always use the very last file ...)

**Comment by paycoiny** [comment]
I found problem in my strategy file. I was using exit_params object to initialize my default values in protection space. Generated json file was generating protection_params object. In hyperopt it was OK because it was using IntParameter value but in Backtesting it was using default value of exit_params object.
By the way. When I was testing and searching problem I found a bug too. 
In hyperopt result files "*.fthypt" params_dict roi values are different than params_details roi values. Is this affecting hyperopt results or not?
Sample:   "params_dict": {
    "enter_buy": 70,
    "exit_duration_days": 13,
    "exit_duration_factor": 1,
    "exit_stoploss_factor": 9,
    "risk_reward_ratio": 4,
    "set_to_break_even_at_profit": 1,
    "roi_t1": 2866,
    "roi_t2": 1335,
    "roi_t3": 499,
    "roi_p1": 0.051,
    "roi_p2": 0.176,
    "roi_p3": 0.141
  },
  "params_details": {
    "buy": {
      "enter_buy": 70
    },
    "protection": {
      "exit_duration_days": 13,
      "exit_duration_factor": 1,
      "exit_stoploss_factor": 9,
      "risk_reward_ratio": 4,
      "set_to_break_even_at_profit": 1
    },
    "roi": {
      "0": 0.368,
      "499": 0.22699999999999998,
      "1834": 0.051,
      "4700": 0
    }
  },

**Comment by xmatthias** [comment]
Interestingly, this info is not really corresponding to the strategy shared, which does 
* not use any IntParameter
* not use protections
* does not optimize the protection space

At any rate - if you're optimizing protections, you'll have to run backtesting with `--enable-protections`, otherwise they'll be disabled (including the protection space will automatically enable this option for hyperopt).


the fthypt file is not intended to be viewed by users. ROI values are different, and need a translation for the strategy to work (they're added on top of each other). A sample of this can be found in the [advanced hyperopt docs](https://www.freqtrade.io/en/latest/advanced-hyperopt/#overriding-pre-defined-spaces) - but it's usually not necessary to change this, unless you want more/fewer roi steps.

**Comment by paycoiny** [comment]
Yes I tested with two separate strategy then reported as bug. But both of them had strategy bug and command line options bug. So I had problem with result of hyperopt and backtesting. Thank you for your support @xmatthias 
I closed the issue.
