### ISSUE TITLE
Output httpx about telegram in logs

### ISSUE THREAD

**Issue by superXR** [freqtrade/freqtrade#8717]
## Describe your environment

  * Operating system: linux
  * Python Version: Python 3.9.16
  * CCXT version: ccxt==3.1.5
  * Freqtrade Version: 2023.5
## Your question

In my dry-run logs,I notice there is httpx about api.telegram bot between two heartbeats.It seems that output once per 20 seconds.I did use telegram .Is this output and freqency normal ? I am worried that my config is incorrect or there is a bug in FT? Because I didn't see such output in FT-2023.4.
![image](https://github.com/freqtrade/freqtrade/assets/57396498/48f41af3-0e2c-4c89-a20e-9aca10394f69)

**Comment by xmatthias** [comment]
It's not a problem - but i'm not entirely sure why you'd get that, either.

This seems to be a change between httpx 0.24.0 and 0.24.1 - i've had 0.24.0 - and didn't get any such message - on 0.24.1 i get tons of info messages as well.
Seems like an intentional change (listed in their changelog) - should be a quick fix.

**Comment by drybx** [comment]
I have countless of these messages in my logs as well (about every 20 seconds). Makes the logs very hard to read. Is there a way to get rid of these?

**Comment by stash86** [comment]
I don't have such issue on latest dev. Not sure how some of you got it

**Comment by xmatthias** [comment]
jup, fixed / reduced on develop :)
