### ISSUE TITLE
Download Data: In prepend mode, some repetitive download are being done

### ISSUE THREAD

**Issue by DanielSayHello** [freqtrade/freqtrade#8718]
In prepend mode, if the start date of the timerange is set before the date when the coin was first listed on the exchange, the entire data set will be downloaded again.

For instance, when attempting to download data for APEUSDT:USDT from Binance Futures, the time range I set was from June 3, 2020 to June 2, 2022. However, the system indicated that it was downloading data from June 3, 2020 to March 17, 2022. Interestingly, APEUSDT was first listed on the exchange on March 17, 2022, meaning there's no data available within the time range it purports to be downloading. Despite this discrepancy, the downloaded data length still corresponds with the aforementioned time range.

I haven't yet verified whether the accuracy of the data has been impacted, for instance, if there are any false merges.
![4231685604726_ pic](https://github.com/freqtrade/freqtrade/assets/49643781/e81e4e37-38f6-4d19-b009-1672877a4986)

**Comment by DanielSayHello** [comment]
I'm currently unsure about how to resolve this issue. I suspect the problem lies in how Freqtrade calculates the number of times it needs to fetch data from ccxt, along with the usage of every timestamp from a list of start timestamps. However, in the aforementioned scenario, if a timestamp prior to the coin's listing is used, ccxt doesn't flag it as an incorrect input but instead provides data starting from the date the coin was first listed. As a result, Freqtrade may end up downloading the exact same data multiple times. Despite this, I believe the merging process isn't affected adversely.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Aside from that - i think this is based on a missunderstanding of how download-data works.

download-data is designed to download a huge chunk of historic data once, and then do small increments.

Assuming you have data available from 2022-01-01 to 2023-01-01 (1 full year, with the last 6 months missing).

If you run download-data with --days 5, then you'll get data downloaded from 2023-01-01 until today.
The same would happen with `--timerange 20230501-20230515` - where the start-date would simply be ignored, and data from 2023-01-01 - 2023-05-15 will be downloaded.
This protects the data from "holes" (gaps in the data due to downloading in odd chunks) - which you might think are acceptable when downloading (you'd NEVER backtest february, would you?) - but is dangerous, as it's not something we check, not something we aim to check, and something you'll have forgotten in a week.


If however, your starting date is BEFORE the available data, then freqtrade will drop all data and download it again.
therefore, running with `--timerange 20210101-20230501` - you'd get all data thrown away and redownloaded.

---

`--prepend` does allow prepending the data - but **must** be passed as an explicit argument to download-data. 
You'll also usually only do that once per pair - if you actually downloaded less data than what you would need in the future.

In that case, the logic is reversed - and `--timerange 20210101-20230501`  would download data from 20210101-20220101 - the first date data exists (it'll ignore the actual end date.

---

As for the pair listing date - that's not something that's available easily on most exchanges (not via the API, anyway).
As such, it's not information we can use to determine "this doesn't make sense".

If you think about a typical download scenario after an initial download, think about it as follows:

`freqtrade download-data  --new-pair-days 500 --config <whatever>.json`.

This will
* Download the data up to the current day for all pairs you already had data for
* Download the last 500 days for pairs that are new (where no prior data exists)

**Comment by DanielSayHello** [comment]
Thx! Really appreciate your reply! My bad. I dont use github a lot and didnt pay attention to the template. I really like this project, so i just wanna report what I think might be a problem.

**Comment by xmatthias** [comment]
Not a problem - just a standard text i post if it's missing - as it may be important and avoid some misunderstandings about the version used
