### ISSUE TITLE
Custom Stoploss & 

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#8732]
Hello, 

First of all thank you very much for this wonderful bot!

I am very new to Python, infact I just started using your script so apoligies if my question is too silly, however I would kindly like to remind you that I have been searching and doing my best since 1 week before posting here.

Below is my code:

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
                # only use .iat[-1] in callback methods, never in "populate_*" methods.
                # see: https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies
        candle = dataframe.iloc[-1].squeeze()
        stoploss = candle['ema200']
        relative_sl_long = candle['close'] - stoploss
        relative_sl_short = candle['close'] + stoploss
        stop_long = stoploss_from_absolute(relative_sl_long, current_rate)
        stop_short = stoploss_from_absolute(current_rate, relative_sl_short)
        if not trade.is_short :
            return stop_long
        return stop_short

As you can see, what I am trying to do is entering a long trade when ema200_3m crosses over ema200_30m and putting a custom stop on ema 200_3m (doesnt matter long or short since if short ema200_3m will be higher and if long vice versa).

If i do not use custom stop, the bot works very well with a normal trailing stop. However when I use custom stop it always exits with emergency exit saying : "Unable to place a stoploss order on exchange. In stoploss limit order, stop price should be more than limit price. Stop price: 0.0, Limit price: 0.0, Limit Price pct: 0.99".

To clear, if I do not use @informative and just use sar example (from https://www.freqtrade.io/en/stable/strategy-callbacks/) it works as usual.

I have been dying to find a solution on my own and I sincerely apoligize if it has been already explained.

I would sincerely appreciate if someone could assist me on this matter.

Kind regards,

Erhan

**Comment by xmatthias** [comment]
`relative_sl_long = candle['close'] - stoploss` doesn't really result in a relative stoploss.

assuming a roughly current BTC price of 27000$ - with the EMA slightly below at 26000$.

your calculation will result in a "relative_sl_long" of 1000$.
that can still be a valid exit - but the variable name makes you assume it's a relative stop - but it's not.

The consecutive call of `stop_long = stoploss_from_absolute(relative_sl_long, current_rate)` will not really help - as you're now trying to pace a stop at  a price of 1000$ - which is about -26000$ away from current price (you could also run without stop ...).
Now obviously the same happens on shorts - but i've ignored that for now (the problem is the same, just in the different direction).

i assume the confusion comes from usage of `stoploss_from_absolute` - which takes the final price (in your case, ema200 of the opening candle).

You might also wanna be careful as `custom_stoploss()` is called multiple times per candle.
while not per se a problem - your description makes me believe you'd want to place the stop at ema200 of the opening candle - not moving along EMA (if EMA raises, your stop raises, too).

**Comment by erhangunay** [comment]
Hello,

Many thanks for your swift reply!

Yes i would like to keep stoploss always on ema200 moving upwards and only upwards

Based on your feedback i have tried the following;

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

        # Use parabolic sar as absolute stoploss price
        stoploss_price = last_candle['ema200']

        # Convert absolute price to percentage relative to current_rate
        if stoploss_price < current_rate:
            return stoploss_from_absolute(stoploss_price, current_rate, is_short=trade.is_short)

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1

This code is exactly the same with the one given in "https://www.freqtrade.io/en/stable/strategy-callbacks/" the only difference is instead of sar i have written ema200 and i still get the error : Unable to place a stoploss order on exchange. In stoploss limit order, stop price should be more than limit price. Stop price: 0.0, Limit price: 0.0, Limit Price pct: 0.99

Could you please let me know how to put a stop on 3m 200 ema while using both 3min 200ema and 30min 200 ema (via informative)

**Comment by erhangunay** [comment]
I have found out that setting the initial stoploss at -1 was causing the issue.

Thanks for your reply.
