### ISSUE TITLE
Unusual Behavior with Very High 'max_open_trades' Parameter Value (STOPS TRADING!)

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#8742]
## Describe your environment

  * Operating system: MacOS Catalina 10.15.7
  * Python Version: Python 3.11.3 (`python -V`)
  * CCXT version: ccxt==3.1.13 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.6.dev-0b8ef1b88 (`freqtrade -V`)

## Describe the problem:

There seems to be a problem when setting the "max_open_trades" parameter to a very large number. In my case, I had it set to 1,000,000. It was working fine yesterday, but it stopped functioning correctly today after pulling some updates. The bot wasn't making any trades or hyper-optimizing, causing a hiatus in my bot's world domination plans (just kidding!). I was able to fix the problem by lowering "max_open_trades" to a more reasonable figure of 1000. But it's a significant issue if there's a hidden upper limit that isn't documented or an unintended bug that's creeping in when dealing with larger numbers.

### Steps to reproduce:

  1. Set "max_open_trades" in config.json to a very high number (like 1,000,000).
  2. Enable "dry_run" mode.
  3. Try to execute trades or run hyperoptimization.
  
### Observed Results:

  * The bot stopped making trades or running hyperoptimization after pulling some updates. No errors were thrown, it was as if my bot decided to take an unexpected vacation.
  * I expected the bot to continue trading or hyperoptimizing even with "max_open_trades" set to a very high number.

### Relevant code exceptions or logs

Unfortunately, there were no explicit exceptions or error logs related to this issue.

``` 
  // No related logs.
```

This bug behaved like a stealthy ninja, completely invisible but its effects were quite real. I hope the information above is useful and points towards a possible bug that can be exterminated, to make the bot unstoppable (again, just kidding!).

**Comment by stash86** [comment]
Because your stake amount become too low?

**Comment by keithorange** [comment]
> Because your stake amount become too low?

is this an issue with freqtrade? not allowing smaller than 1 stake amount? In real life you can stake a few cents at a time. It is actually a great training strategy because it forces the hyper-optimization to be super precise when combined with --`enable-position-stacking`

**Comment by stash86** [comment]
Depends on the exchange. On binance spot, $15 is the safe minimum stake amount. If you want to do a high max open trades, make sure to set a very high wallet size

**Comment by xmatthias** [comment]
> is this an issue with freqtrade? 

No, it's an issue with the minimum tradable limits on the exchange.

stakes of a few cents at a time is unreasonable on every exchange i've used so far (except FTX, but that's a different story from the past), anything below 15$ will most likely not work on most spot exchanges, at least not reliably across markets.

On some markets/exchanges, i've seen minimum limits of 50$ or higher - so "cent" stakes is clearly very far from reality.

In the end, it's most likely a simple miss-configuration - if you set max_open_trades to 1_000_000, your dry_run_wallet will have to match that - and be something around 50_000_000 (assuming USDT as stake) - then you'll see that you won't have a problem.

**Comment by keithorange** [comment]
Yes this is good advice. There should at **least** be a **warning** if the `max_open_trades >= dry_run_wallet`

**Comment by xmatthias** [comment]
Freqtrade gives you the flexibility to use it the way you want - if you're using BTC as stake-currency, the configuration settings are completely different, so simply because max_open_trades > dry_run_wallet, it's not per se a wrong configuration.

As user, you should **read** the documentation - which is quite clear on [the minimum trade stake](https://www.freqtrade.io/en/latest/configuration/#minimum-trade-stake) - and contains this information.

Clearly, you didn't - but the expectation that we'll have the bot read it to you is not going to happen.

This is an open source project - we spend our free time spread between helping people and improving bot functionality.
The base assumption from a user to get this for free is that they are able and willing to read the documentation.

Sure, we could spend the time having the bot explain every single facet for users who don't want to read the documentation - but that would mean less time to actually improve the bot, and is therefore in my eyes, a clear waste of time.
