### ISSUE TITLE
Static leverage

### ISSUE THREAD

**Issue by kasimovv** [freqtrade/freqtrade#8747]
## Describe your environment

Operating system: Debian 11
Python Version: Python 3.9.2
CCXT version: ccxt==3.1.5
Freqtrade Version: freqtrade 2023.5
  
## Your question

Hello. Tell me, please, how to establish a constant leverage? I tried to set constant values in this block: 

def leverage(self, pair: str, current_time: datetime, current_rate: float, proposed_leverage: 3.0, max_leverage: 3.0, entry_tag: Optional[str], side: str, **kwargs) -> float: 
return 3.0, 

but the leverage is 1 anyway.

**Comment by xmatthias** [comment]
Assuming this is your code, then most likely, it's because you're returning `3.0,` (notice the trailing comma).
This makes it a tuple - and as such, an invalid response - which will be ignored.
You're also using `:3.0` as type - which i'm not entirely sure is valid (though i suspect it'll run just fine).

Now obviously, with just this snippet, it could just as well be indented wrongly (not inside the class, therefore not considered part of the strategy) ... but again, with just this (mal-formatted) snippet, it's really impossible to say for sure.

You may just as well be running on non-leveraged markets (spot-markets).
