### ISSUE TITLE
BackTesting result is different with live result

### ISSUE THREAD

**Issue by yili1992** [freqtrade/freqtrade#8748]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.10.10 (python -V)
  * CCXT version: ccxt==3.1.5 (pip freeze | grep ccxt)
  * Freqtrade Version: freqtrade 2023.5 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  

## Describe the problem:
I compared the live trading results of a pair with the backtesting results, and I found that there is a difference in the exit signal 
BackTesing:
![WechatIMG598](https://github.com/freqtrade/freqtrade/assets/3176589/ed2b4554-c6fb-4f5d-a599-8b4002aa698b)
Live:
![WechatIMG600](https://github.com/freqtrade/freqtrade/assets/3176589/b1bd4748-c7ec-4250-967b-b0550e15e79f)

**Comment by xmatthias** [comment]
backtesting has to take [certain assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) - which, as the name already implies, are assumptions, which are a rough approximation of reality - but don't ACTUALLY reflect reality 100%.

---

If you look very carefully, you'll notice that the entries are slightly different. 

Where backtesting buys once (seemingly right at the buy signal) - live buys several candles later.
This can be "no open trade slot" (other trades that closed around the entry time impacted this trade) - or it can be caused by a very slow strategy, that's taking more than 1 candle to go through your whole pairlist (a VERY dangerous premise, which implies that your strategy is doing WAY too much work for the pairlist length / system power you're running this on, which will result in the bot to potentially buy several candles after the actual signal).

As a consequence, the remaining entry signals are also slightly off / later - most likely because they'll be profit/loss based - which is now obviously slightly different.


The chart shows that the exits are not regular, static exit signals (no exit signal on the chart), which most likely means that they're somewhat profit-based. Having slightly different entry prices will therefore automatically mean that your profit calculations will differ, causing different (later / earlier) exits.

**Comment by yili1992** [comment]
> 

Thx your reply , I have a other question , I using docker compose to run freqtrade. it only using 1 CPU . are there any way to improve cpu usage. my linux has 4 logic cpu

**Comment by yili1992** [comment]
> backtesting has to take [certain assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) - which, as the name already implies, are assumptions, which are a rough approximation of reality - but don't ACTUALLY reflect reality 100%.
> 
> If you look very carefully, you'll notice that the entries are slightly different.
> 
> Where backtesting buys once (seemingly right at the buy signal) - live buys several candles later. This can be "no open trade slot" (other trades that closed around the entry time impacted this trade) - or it can be caused by a very slow strategy, that's taking more than 1 candle to go through your whole pairlist (a VERY dangerous premise, which implies that your strategy is doing WAY too much work for the pairlist length / system power you're running this on, which will result in the bot to potentially buy several candles after the actual signal).
> 
> As a consequence, the remaining entry signals are also slightly off / later - most likely because they'll be profit/loss based - which is now obviously slightly different.
> 
> The chart shows that the exits are not regular, static exit signals (no exit signal on the chart), which most likely means that they're somewhat profit-based. Having slightly different entry prices will therefore automatically mean that your profit calculations will differ, causing different (later / earlier) exits.

Thx your reply , I have a other question , I using docker compose to run freqtrade. it only using 1 CPU . are there any way to improve cpu usage. my linux has 4 logic cpu

**Comment by xmatthias** [comment]
Python will by default only use 1 core (it's not a freqtrade limitation per se).

That's a core python limitation. While there are ways around this - we don't apply them as they have severe consequences and drawdowns, which would not make sense for freqtrade, and limit what the strategy can actually do - and would therefore hurt more than they'd help.
