### ISSUE TITLE
Change logic how stoploss_on_exchange orders are build

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8758]
Describe your environment
Operating system: Ubuntu 22.04.1 LTS
Python Version: 3.10.6
Freqtrade develop
CCXT 3.1.23
Freqtrade running in docker : docker-compose up -d
Exchange: Binance

Parameters from strategy:

    order_types = {
        'entry': 'limit',
        'force_entry': 'limit',
        'exit': 'limit',
        'emergency_exit': 'market',
        'force_exit': 'limit',
        'stoploss': 'limit',
        'stoploss_on_exchange': True,
        'stoploss_on_exchange_limit_ratio':0.998,
        'stoploss_price_type': "last"
    }

![tick_1](https://github.com/freqtrade/freqtrade/assets/108837852/85302261-b167-472b-bb2a-1367678ce58c)
![tick_2](https://github.com/freqtrade/freqtrade/assets/108837852/5ea8e53a-97e8-4599-8180-e72c8a909210)
![tick_3](https://github.com/freqtrade/freqtrade/assets/108837852/e8d06cdb-35b4-411b-b91e-499d23d9a124)
![tick_4](https://github.com/freqtrade/freqtrade/assets/108837852/09db7b6f-5f5b-48eb-a6f9-6627cd93be62)

At time in freqtrade "stoploss_on_exchange" setup has this requirement: 
-for shorts : limit price > stop price
-for longs : limit price < stop price

some log example:
2023-06-06 19:33:18,894 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. In stoploss limit order, stop price should be more than limit price. Stop price: 1.2206, Limit price: 1.2206, Limit Price pct: 1.0
2023-06-06 19:33:18,895 - freqtrade.freqtradebot - WARNING - Exiting the trade forcefully

But Binance allows to place stop-limit orders without this restriction (se attached examples), both examples are short positions. BTC - manual position, ALGO - fq_bot position.

Requirement is to be free to use positive or negative values in 'stoploss_on_exchange_limit_ratio' parameter , to be able to post limit orders less or equal stop for shorts, and bigger or equal stop for longs.

Reason for this request is: in the actual configuration, in >90% cases, limit orders are marked as "TAKER" which has 2x more fee than "MAKER" on Binance (last picture example).

Regarding risk management, users can use market or actual limit logic to avoid risk that stoploss limit order will not be filled. Everyone should choose a strategy that fit his needs; I personally will not use this setting in any strategy.

**Comment by xmatthias** [comment]
> 2023-06-06 19:33:18,894 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. In stoploss limit order, stop price should be more than limit price. Stop price: 1.2206, Limit price: 1.2206, Limit Price pct: 1.0

this seems fabricated (or a bug) - as i do think that identical stop and limit prices are allowed. If that's not - then that should be changed to be allowed.

---

I don't really see the remaining as a valid case though.
it's no longer a stoploss (tool for risk control) if you place a long exit it with the limit price > trigger price.

Just because the exchange allows it doesn't mean it's a good idea, not if you consider the consequences.

If you happen to have that case (stop order triggered but doesn't fill) - then freqtrade will stop processing this trade, waiting for the order to fill. 
obviously you can cancel the order manually on exchange, after which freqtrade will continue to work the trade further (replaceing the stoploss, most likely) - but freqtrade will not act on this further until the order is in either cancelled or filled state (also no timeouts will apply to this case).

Therefore, if you encounter a crash - then you'll no longer be able to use stoploss as "risk X amount of capital" - but as some random exit condition - which will potentially still cost you 90% of your actual position.

If you require custom pricing logics - then best use `custom_exit()` - which has appropriate handling and will eventually replace the order at a lower price (assuming proper timeouts are set) should the position go further against you.

**Comment by dobremha** [comment]
Hallo Matthias, what you said - same can happen also in the actual configuration in fast price movement condition.
If someone doesn't want this risk, they should use market parameter.
Has nothing to do with "custom pricing logics/custom_exit()" it's all about stoploss_on_exchange feature, and for shorts (where a crash is not a problem) it really make sense to pay 2x less fee.

If it's a good idea or not, every one has to decide for his strategy. You can't simply say it's a bad idea in all cases...

Maybe if you correct to work with :
'stoploss_on_exchange_limit_ratio': 1.00
to have limit = stop, it will be ok. I need to test some cases, but now it's not working with 1.00

**Comment by dobremha** [comment]
![tick_5](https://github.com/freqtrade/freqtrade/assets/108837852/e68abb4d-0364-4c04-b4d3-03a3092599df)

My example .. worked really fine

**Comment by xmatthias** [comment]
Seems like this is a bug with the edge-case of 1.0 - which didn't work before, but will shortly.

values > 1 are however not supported, and i don't see us support that either, really - for the reasons mentioned above.
