### ISSUE TITLE
Project needs to be Addon-able

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/freqtrade#8836]
I use this project and believe it's a great tool, but in some situation developers needs to implement special features that is specifically usable for owned strategies that must cover backend and also frontend, for example suppose my strategy needs changeable tags for open trades by moderator of Freqtrade panel, in current situation developer must put code in separate git branches in two projects(Freqtrade & Freq-UI), while it should be implement as a plugable package and developer must can share this package by others in  Freqtrade addons hub.

**Comment by froggleston** [comment]
Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

___

Some users (myself included) do not use FreqUI, so tightly coupling Freqtrade (the bot) to one of the interfaces for Freqtrade (of which there are multiple examples) doesn't make good development or usage sense.

Freqtrade is also not designed to be a library, but a software tool. Whilst you can import aspects of Freqtrade to create other solutions, e.g. jupyter notebooks, APIs, etc, it is not in the project's roadmap to make Freqtrade what you're asking.

In the end, Freqtrade is open source, so if you want to suggest specific changes to specific pieces of code to improve functionality then you are free to do so and we would encourage that. As this issue is not providing this, I'll close it and let you decide if you want to contribute specific changes. 👍
