### ISSUE TITLE
No option to short, Limits bot to 50% potential, increased risk during bear as counter trend trading 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#892]
Crypto markets experience both bull and bear periods mid / long term and up/down price movement intraday. 

A lack of capability to trade short during bear periods limits strategies to trading against the trend which is hard work and carries in increased risk. 

To be able to flip a position from long to short when day trading doubles to entry points opportunities. 

By way of examples: 

1. Longterm low risk trade:  A simple long term trend trade on hr4 would make 150% on 1 short/bear flip from Feb to April, and 60% on the following bull. 
2. Day trading example: Indicators flip to short at 7600, but no means to short BTC on the drop. 

1)
<img width="1081" alt="screen shot 2018-06-10 at 9 08 06 am" src="https://user-images.githubusercontent.com/34645187/41200119-3e0e94a8-6c8e-11e8-83b4-de545f9456be.png">
2)
<img width="1216" alt="screen shot 2018-06-10 at 9 10 36 am" src="https://user-images.githubusercontent.com/34645187/41200118-3de9489c-6c8e-11e8-8093-6edb1d6fd692.png">

**Comment by iguy0** [comment]
+1

**Comment by Gabri** [comment]
Can we have an update on development of this feature? And, if there is, a possible roadmap to have it to test.
Thanks!

**Comment by MichealReed** [comment]
@Gabri this is pending ccxt's issue https://github.com/ccxt/ccxt/issues/4834, feel free to add comments there.

**Comment by acrabb** [comment]
Just commented on https://github.com/ccxt/ccxt/issues/4834
Would love the ability to short.

**Comment by hroff-1902** [comment]
> Just commented on [ccxt/ccxt#4834](https://github.com/ccxt/ccxt/issues/4834)
> Would love the ability to short.

An ability to short does not depend on ccxt. That issue in the ccxt repo is about margin/leveraging.

**Comment by xmatthias** [comment]
> An ability to short does not depend on ccxt

yes it does (not exclusivly though), without having that unified in ccxt, supporting it in freqtrade will be almost impossible.

**Comment by hroff-1902** [comment]
It's not margin. You can now (manually, from a notebook, or something) call ccxt call to sell to create a negative (short) position. And then create a buy order to close the position. In my opinion, nothing in ccxt prevents short positions. However, many things should be redesigned in freqtrade to allow it, in almost every module.

**Comment by xmatthias** [comment]
the attached issue is wrong, yes.

i don't think you can short-sell using `ccxt.sell(<pairidontown>, ...)` ... i guess each exchange would require some specific parameters for this to work - but i've never used short positions,and i don't think the exchanges i'm registered at (and have some balance) offer that currently.

**Comment by acrabb** [comment]
> An ability to short does not depend on ccxt. That issue in the ccxt repo is about margin/leveraging.

thought it sounded off...

**Comment by qkum** [comment]
Amazing how overlooked shorting is. 

If you are not shorting you are missing out on 100-200% profit because you with a bot can lower your risk to like 0 if it is set up perfect. It will just always be long/short and then you got margin on top. It would be like printing money your self. 

Doing it manually is impossible to do perfectly because you can't react fast enough/need sleep - to flip side perfectly from short to long or long to short. 

This should have the highest priority. Everybody using the bot could easily 1x,2x,3x, 4x the profit they are doing now. As close to 0 risk as possible and maximum possible gains. (you profit when the market go up and down) This can be done with a 2x to 5x leverage even. Maybe even 10x with no risk of liquidation.  

This Enhancement should have the highest prioritization no doubt. 

Me telling you guys this secret is like giving you guys millions as thanks for your hard work @xmatthias @hroff-1902 and the rest of the hard-working people on this project. 

And it is many times more profitable to do on the 4h chart than 1-day chart btw. 100x in a year. Highly possible. 

PS: Margin/leverage short/long is on most big exchanges in 2020 - Binance, Kraken, Bitfinex, Bybit, and coming to all exchanges over the next years. 

Dont take my comment personally in any way or shape. Or negative. I just suck at puttings thoughts into words.

Thanks a lot for all your hard work already on this project. I'm so amazed over this great open source project that I'm in tears trying to describe how beautiful it is.

**Comment by hroff-1902** [comment]
leverage is completely different from support for shorts

**Comment by qkum** [comment]
> leverage is completely different from support for shorts

I'm sadly not a programmer yet so I dont know the coding difference. 

But on the exchange they are like bread & butter. But a 1x short is better than no short :) But when you with a bot can do a 10x short or long with same risk as a 1x short/long (1-2% stop loss example) it gives no sense to only use 1x :)

**Comment by xmatthias** [comment]
@qkum We will definitely not support shorting (nor leverage) before CCXT has this part unified. Otherwise we'd need repeated effort per exchange as it will be different per exchange, which we do not have the ressources for (remember, this is a free, open source Project, with everyone working on it donating their time in their free time).

That said, CCXT has both margin trading as well as leverage trading on their [Q2 roadmap](https://github.com/ccxt/ccxt/issues/6697) - so there might be light at the end of the tunnel.

Yet, even after that, don't expect either of these features to be implemented in freqtrade immediately after ccxt has it unified unless you're a coder (now talking to future readers) and feel you can contribute it to freqtrade yourself.

As noted above - freqtrade is a free, open source project with everyone spending/donating their free time to contribute and improve it. 
This also means that we cannot force people to implement feature X if that person is not interested in this functionality / feature.

Thanks for your understanding.

**Comment by drdux** [comment]
@qkum until ccxt and freqtrade support shorting you can experiment with the leverage tokens that pop up on all the exchanges. Instead of shorting you can buy the token that moves in the direction you want (on FTX their called BTCBEAR on Binance BTCDOWN). That should work with the current release of freqtrade and enable you to profit from falling prices even with leverage but without the need of margin trading.

**Comment by qkum** [comment]
Did I understand it correct that with the current version of Freqtrade you can log on to binance and pick 5x leverage/margin, and log out and start up the bot and run a strategy where it will trade the margin/leverage coins? Long only/buy only. Is that correct understood?

**Comment by xmatthias** [comment]
no, this is only possible via the margin pairs (which on binance require different api endpoints). ccxt does not unify this so far - so this is not possible.

The only way is to use BTCBEAR / BTCPULL (or however they're called on binance) pairs - which are leveraged spot pairs.

**Comment by qkum** [comment]
> no, this is only possible via the margin pairs (which on binance require different api endpoints). ccxt does not unify this so far - so this is not possible.
> 
> The only way is to use BTCBEAR / BTCPULL (or however they're called on binance) pairs - which are leveraged spot pairs.

Oki doki.

Thanks a lot for the fast reply as always! 

Never used Binance margin/leverage yet cause they required KYC in the start. Not anymore it seems. I have only used Bitmex/Bybit. Bitmex got hidden fees so I use bybit nowadays. (Bonus info about user habits)

**Comment by hroff-1902** [comment]
> Bitmex got hidden fees

what are "hidden fees"?

**Comment by xmatthias** [comment]
probably borrow fees (which is usually the case when using leverage) ... but binance has them too ...

**Comment by yohplala** [comment]
Hello guys, it is my understanding that differences between ccxt and ccxt pro are websockets and margin+leverages. I just asked what is meant by the term 'unification' in ccxt q2 roadmap thread. Let's see.

**Comment by yohplala** [comment]
Answer has been crystal clear and lightning fast! :)
Excellent,  there may be possibility to have it in ccxt open source!

**Comment by xmatthias** [comment]
yes - as usual... :laughing: 

The main benefit ccxt.pro offers is websockets. we may support that sometime in the future - but it'll always be optional, as it would exclude most of the userbase that's just "trying out the bot" if we'd require a ccxt.pro license.

**Comment by yohplala** [comment]
Yes, an alternative option may lie with cryptofeed that is an open source implementation for websocket support of most important exchanges, but this project is clearly not of the same scale than ccxt:
https://github.com/bmoscon/cryptofeed

Additionally, cryptofeed only 'fetches' data, and does not place orders. But it might be a start.

**Comment by xmatthias** [comment]
well - freqtrade works perfectly fine without websockets - so i don't see why it should use anything other than ccxt for comunication with the exchange.

**Comment by qkum** [comment]
> > Bitmex got hidden fees
> 
> what are "hidden fees"?

Only 10% of your profit if you happen to make money on a trade. So if you made 40% they will take 4% on top of the normal fees that are less than 1% in total. I checked every log/trade/stats I could and there was not official reason to why I lost 10% on winning trades. I also googled. 

And it got even worse during the last BTC crash/corona crash because that day during the most volatile hours they added even more fraudulent fees on top of the normal -10% profit fee one. During those hours you would end in like -8% - 12% profit the moment your limit order was filled lol. Even when the price clearly still after execution was at buyin price.... you were at a decent loss...even if the price moved 5% in the green you would still be in the red lol. I tested it a few times that day and it was like that on every order. Biggest legal fraud I have seen in crypto.  Even a mentor of mine, a top poster on tradingview ( alanmasters) confirmed to me that he knew all about the hidden fees and that you just had to live with them. I stopped on Bitmex after the - 8-12% fraud during the crash.  That was too much for me. And lucky me Bybit had just popped up shortly before. 

Bybit is as transparent as they come. And there is no hidden fees or anything shady about them. And 10x faster trading software. And by today 2020 Bybit also got more volume than Bitmex (scam-mex) on the BTC pair. 

Bybit has introduced options just recently called "insurance" so you can get insured from being liquidated. 

Scam-mex is the past.

**Comment by qkum** [comment]
> no, this is only possible via the margin pairs (which on binance require different api endpoints). ccxt does not unify this so far - so this is not possible.
> 
> The only way is to use BTCBEAR / BTCPULL (or however they're called on binance) pairs - which are leveraged spot pairs.

I have looked closer at the leveraged tokens you talk about. But how do I trade them with freqtrade? Just like I would trade any other crypto pair with freqtrade? I highly doubt that. Some guy on youtube made a video where he did leverage trade with freqtrade saying something about you had to know how to change "headers" to do what he did. I dont know if that was the leveraged tokens on Binance he used in that video. But it worked great for him. Huge profits.

**Comment by evka85** [comment]
Has there been any progress on this issue? I agree with @qkum that this is an essential feature (even though I do understand that there are a lot of complications involved with that)

**Comment by ghost** [comment]
This is one of the biggest features missing. It would be an excelent addition to be able to short on futures, margin or up/down spot tokens at least to take advantage of bearish markets.

**Comment by rokups** [comment]
> We will definitely not support shorting (nor leverage) before CCXT has this part unified. Otherwise we'd need repeated effort per exchange as it will be different per exchange

A way out could be pseudo-shorting, which is simply swapping buy and sell sides. So to short BTC/USDT bot would take a portion of BTC on the account and sell it and record it as a trade. To take profit bot would re-buy same amount of BTC. This is most likely not a trivial change as we would now be in a mode where we have two stake currencies. But at least it does not depend on ccxt having to support it.

**Comment by xmatthias** [comment]
on almost all exchanges, you'll have to have the amount of the "selling" currency available for this to work (binance spot markets won't allow you to place a sell-order for amounts you don't own).

As such - this will become rather difficult - and the easier bet is to use the "*BEAR/USDT" markets for this (if it's about allowing it "somehow").

**Comment by rokups** [comment]
> on almost all exchanges, you'll have to have the amount of the "selling" currency available for this to work (binance spot markets won't allow you to place a sell-order for amounts you don't own).

Of course! Why would that be a problem? Essentially we would have two balances, one for longs (USDT) and one for shorts (BTC). Ideal? Nope. Still better than nothing. I cant find any `*BEAR` pairs. There are `*DOWN` pairs, but they are leveraged, so not exactly a substitute.

**Comment by xmatthias** [comment]
the big problem - you limit yourself to BTC/USDT (fake) shorts - so honestly, that's not worth even investigating as it will be too limiting to be useful.

if itls *BEAR or *DOWN will depend on the exchange ... :laughing:

**Comment by dragos-janea** [comment]
I wanna look into this also, so any help to get me started is appreciated. Firstly, I found this for finding margin amount on binance(I care mostly about this) https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-margin-balance-with-params.py

**Comment by jackcobb** [comment]
> yes - as usual... 😆
> 
> The main benefit ccxt.pro offers is websockets. we may support that sometime in the future - but it'll always be optional, as it would exclude most of the userbase that's just "trying out the bot" if we'd require a ccxt.pro license.

What would prevent having the extensibility for a license? Instead of requiring a pro license to run the bot, you could still run things as normal, but if you want to user certain features (like margin trading/shorting), then a license is required

**Comment by dragos-janea** [comment]
@jackcobb Is this related to shorting? Is there a need for pro version aside from websockets? I see examples doing with open source version shorting and margin obtaining: https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-create-margin-order.py

If it's unrelated to the shorting option and only related to the websockets one, a new issue can be created for that.

**Comment by Ughuuu** [comment]
Rewritting from my account what I wrote before:

I wanna look into this also, so any help to get me started is appreciated. Firstly, I found this for finding margin amount on binance(I care mostly about this) https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-margin-balance-with-params.py

**Comment by Ughuuu** [comment]
Rewritting from my account what I wrote before:

@jackcobb Is this related to shorting? Is there a need for pro version aside from websockets? I see examples doing with open source version shorting and margin obtaining: https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-create-margin-order.py

If it's unrelated to the shorting option and only related to the websockets one, a new issue can be created for that.

**Comment by rokups** [comment]
Shorting support is underway: #5157, #5278. Contact @samgermain (@Samwow#2769 on discord) if you would like to help.

**Comment by Ughuuu** [comment]
Thanks for providing this info, this is great! Will for sure read the PR's and see if there is any way I can help.

**Comment by samgermain** [comment]
@Ughuuu margin-db is almost done, so don't look at that one, I'm going to make another PR called margin-exchange as soon as I can get all the tests to pass in it, which is filled with a lot of TODOs

**Comment by samgermain** [comment]
@Ughuuu 

One adjustment that needs to be made is

```
# TODO-mg: Need to add 'options': {'defaultType': 'margin'}, if exchange is binance (without futures I think)
        self.exchange = ExchangeResolver.load_exchange(
            self.config['exchange']['name'],
            self.config
        )
```

One solution that might work is just adding the option to the exchange config, but this seems like something extra the user would have to know about, which could be abstracted away in the code implementation(We know that by trading with leverage that this will have to be there, so why make the user do it?). But putting it in the code might make things messier

@xmatthias I'd like your opinion on this

```
"exchange": {
        "name": "binance",
        "key": "your_exchange_key",
        "secret": "your_exchange_secret",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "options": {
            "defaultType": "margin"
        },
```

**Comment by xmatthias** [comment]
you can put `"defaultType": "margin"` to `ccxt_config` - that way ccxt is started with it.

Your assumption (user uses leverage -> we need to use "defaultType Margin") will not work (it's even plain wrong in some instances).

It's binance-focused - this is not needed (nor will it work) for kraken, nor is it needed for ftx afaik.
Also on binance, it'll be needed for trading in margin accounts - but not for futures (for futures, you'll need to use a different defaulttype).

As such - i'd leave this open for the moment and for binance, configure it in "ccxt_config".

**Comment by samgermain** [comment]
> Your assumption (user uses leverage -> we need to use "defaultType Margin") will not work (it's even plain wrong in some instances).

Sorry, I meant when Binance is the exchange, i just didn't say anything

Also, [ccxt uses different names for binance, and binance futures,](https://github.com/ccxt/ccxt/wiki/Exchange-Markets) so checking for binance would be fine I think

**Comment by xmatthias** [comment]
From a code structure perspective - this part should not be outside of the exchange class - most likely in the binance class even.

**Comment by samgermain** [comment]
@Ughuuu One small update that would help would be merging `exchange.buy` and `exchange.sell` into one method, talked about here https://github.com/freqtrade/freqtrade/pull/5284#issuecomment-882721894

**Comment by samgermain** [comment]
> Thanks for providing this info, this is great! Will for sure read the PR's and see if there is any way I can help.

Don't read #5278

**Comment by FBosler** [comment]
@samgermain did you end up finishing the feature?

**Comment by xmatthias** [comment]
It's work in progress. 
Please understand that we're not providing any ETA, as it's all voluntary work, which means we cannot plan resources.

**Comment by samgermain** [comment]
> @samgermain did you end up finishing the feature?

There's a list of tasks that still need to be done https://trello.com/invite/b/zLDZxNhp/7c87ef32a81e053149d0c93697d77cd1/freqtrade-leverage
