### ISSUE TITLE
Using stoploss with leverage and adjust_trade_position()

### ISSUE THREAD

**Issue by tomashinM** [freqtrade/freqtrade#8976]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.11.4
  * CCXT version: 4.0.29
  * Freqtrade Version: freqtrade docker-2023.7.dev-9c1fea0e
  
## Your question

Hello, I have a question about the stoploss. Is it possible to set it below -1? As i understand if my strategy uses leverage 10 and i set stoploss to -1 then at -10% profit it will liqidate. But if i am increasing position with adjust_trade_position() callback then it can go below -10% without liqidation but stoploss triggers since it calculated from the first entry. And i don't understand how to set it below -1. Custom_stoploss callback not working because it can only move stoploss up but not down.

Example: 
Buying at 100$ price (50% of stake amount) -> stoploss at 90$ -> liqidation at 90$
Increase with adjust_trade_position() at 95$ price (100% of stake amount) -> stoploss at 90$ -> liqidation at 87,75$

Is there any way to achieve this or is it not possible in freqtrade? Or my understanding of how it works is not correct?

**Comment by xmatthias** [comment]
That's correct, it's currently not possible.

The change for that itself would be minor from a technical perspective - but it can't be done selectively (just for futures) - at least not without additional effort.

A more likely solution we'll pursue in the future is an additional call to the "custom_stoploss" callback which will allow you (once, after an adjustment fill) to re-define your stoploss - as effectively, the risk did change from the initial position (as your average entry may have changed).

it's dangerous to some degree, as it'll allow moving the stop lower - but it'd be an intentional action in that case.

**Comment by tomashinM** [comment]
Ok, thank you for clearing that up. I will try to change source code for now. But when can i expect this feature to be added? (just to know if its in priority list)

**Comment by xmatthias** [comment]
You're more than welcome to submit a PR adding this.

As for the feature itself - this project is developed by volunteers in their free time - as such, we'll not provide any timelines - as the acutal features being worked on depends on each contributors personal interest and priorities (i can't and won't force a specific task onto people they're not interested in, including myself).
