### ISSUE TITLE
Kraken: Add data convert ability for kraken OHLCVT csv format

### ISSUE THREAD

**Issue by 8de2fdb0** [freqtrade/freqtrade#8982]
## Describe your environment
(if applicable)

  * Operating system: ANY
  * Python Version: >3.7
  * CCXT version: 3.1.5
  * Freqtrade Version: 2023.5.1

## Describe the enhancement

As described in this support [article](https://support.kraken.com/hc/en-us/articles/360047124832-Downloadable-historical-OHLCVT-Open-High-Low-Close-Volume-Trades-data), kraken OHLCVT data can be downloaded as CSV files from a [GDrive share](https://drive.google.com/drive/folders/1aoA6SKgPbS_p3pYStXUXFvmjqShJ2jv9?usp=sharing).

The format is very similar to the freqtrader json/jsongz formats.

Below is a python script that I used for the conversion, I am not sure if I had to attach the 3 zeros to the timestamp or trim the Trades field from that data, I did it anyway to get the format as close as possible.

There are no 30 minute CSV files, I used  the 15 minute CSV file and merged every first and second row and used the timestamp from the first row. Should be pretty close to the real data.

Would be nice to add this conversion to to data convert command. The current option to download data takes forever.

If I get some hints on how to add that I be willing to open an PR.

```python
import sys

import csv
import json
import gzip

def convert_csv_to_json(in_filename, out_filename, combine=1):
    data = []
    sum_buf = []
    with open(in_filename) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        for row in csv_reader:
            line_count += 1
            row[0] = row[0] + '000'
            row.pop()
            if combine == 1:
                data.append(row)
            else:
                sum_buf.append(row)
                if len(sum_buf) == combine:
                    result = ['', '', '', '', '', '']
                    result[0] = sum_buf[0][0]
                    result[1] = str(float(sum(list(map(float, list(zip(*sum_buf))[1])))))
                    result[2] = str(float(sum(list(map(float, list(zip(*sum_buf))[2])))))
                    result[3] = str(float(sum(list(map(float, list(zip(*sum_buf))[3])))))
                    result[4] = str(float(sum(list(map(float, list(zip(*sum_buf))[4])))))
                    result[5] = str(float(sum(list(map(float, list(zip(*sum_buf))[5])))))
                    data.append(result)
                    sum_buf = []

    json_str = json.dumps(data) + "\n"
    json_bytes = json_str.encode('utf-8')

    with gzip.open(out_filename, 'w') as fout:
        fout.write(json_bytes)
    
def main():
    asset = sys.argv[1]
    file_in = f'./data/kraken_download/{asset}_OHLCVT/{asset}USD_%s.csv'
    file_out = f'./data/kraken/{asset}_USD-%sm.json.gz'
    convert_csv_to_json(file_in % 1, file_out % 1)
    convert_csv_to_json(file_in % 5, file_out % 5)
    convert_csv_to_json(file_in % 15, file_out % 15)
    convert_csv_to_json(file_in % 15, file_out % 30, 2)

if __name__ == "__main__":
    main()
```

**Comment by xmatthias** [comment]
well one thing upfront - you shouldn't use `csv.reader` - but [`pd.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).

You'll find that it'll make the whole "loop" mostly unnecessary, while automatically improving performance a TON.
That loop is really unnecessarily long, quite difficult to read and see what is being done immediately (and at first glance, converts the data from float to string to float again ... (or something in that regard)).

As for the "combine" - pandas has a `resample()` method - which will greatly assist in this.
Doing the sum of everything is wrong (e.g. low for 30m isn't 20 + 19 on 15m, but the minimum of the 2 values).

---

> The current option to download data takes forever.

This is correct and known (thank kraken for that) - however using the pre-built files limits you to what kraken provides via csv files - so currently, you'll be missing almost 3 months of data (data ends Q1 2023, according to the linked site).
if that's no problem, great (markets change all the time, so i think it's important to have uptodate data).

but by not having "native" trades data - you also can't really use the `download-data` command to get further data - as this combination assumes the "full" trades range is available and will do a complete conversion.

---

> If I get some hints on how to add that I be willing to open an PR.

That's great!
If i'm honest, i'm still a bit undecided as to where this should actually go (maybe a script, maybe a command)

If we go with command, then the "convert-data" command is (probably) the correct place - most likely by adding some additional command where you can pass it the "csv directory" (or the zip file??) - which will then trigger this alternative route - or a flag, and we have a pre-defined / documented place for the csv file(s).

Not sure what type of pointers exactly you'd need though. 
If you have specific questions - happy to help (a first pointer - the function should probably go to `converter.py`).

**Comment by 8de2fdb0** [comment]
> well one thing upfront - you shouldn't use csv.reader - but [pd.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).

yes I thought about using pd, it is just an example. will update that.

> but by not having "native" trades data - you also can't really use the download-data command to get further data - as this combination assumes the "full" trades range is available and will do a complete conversion.

This is the part I don't understand completely, I can see that you need `--dl-trades` for the kraken  API. 
I havn't really read through the source code of freqtrader,
So what I suspect is that the `download-data` command will download all trades for a specific range, generate the trades file `<PAIR>-trades.json.gz` and then generates each `<PAIR>-<INTERVAL>.json.gz` from that trades file.

Couldn't the `download-data` script do the following.

* download the trades range
* open the last ohlcv file and get the last timestamp
* append from the last +1 timestamp to the ohlcv file

I guess if that can't be fixed it makes little sense to add the custom conversion to `convert-data`, since you can't fill up the missing data.

One more question is there a way to tell `download-data` to download everything on top of what is currently downloaded without defining the  `timerange`?

I could imagine a `--append` switch to initiate that for example. The downside I can see is that probably complicated the current logic a bit. 

Alternatively there could be a `merge-data` command that allows to merge the result from `download-data` of course that would need to be run every time the `download-data` command had been run since that will delete the range that is not present in the  trades file.

**Comment by xmatthias** [comment]
The problem with "complicating" the logic for this is a combination maintainability and complexity, compared to the benefit it brings (only for one exchange, with a very limited/low usage) and the risk it incurs of having then non-aligned candles.

if with some random date logic, you start missing a few trades, you'll potentially have different candles than how they actually occurred. 
Effectively, you'll be comparing very high level data (say, 1m candle data) with very low level data (trades, where you have millisecond granularity) - which can be quite problematic.

The current approach is to require full trades data - and then converts the whole trades data in one go - replacing the ohlcv data completely.
This obviously doesn't have to be this way - but is a working solution - and honestly, there's only a handful of kraken users i know about - so that's "good enough" - and doesn't really justify much time invests.

#5578 would want to change that, as it's not unproblematic in regards to memory - but as you can see from time  / traction it gained (basically 0) - nobody found it interesting enough to work on this.

> One more question is there a way to tell download-data to download everything on top of what is currently downloaded without defining the timerange?

This is the default if you have existing data. Now for Kraken, the current assumption for "existing data" is obviously to have trades data (not ohlcv data).

---

there's many things that COULD be fixed - but personally, i don't intend to spend a great deal of time on kraken.
it's currently working (albeit slow).
 
Their ratelimits for public endpoints (you can verify as high as you want, public endpoints will ignore that) - combined with comparably low volume on most pairs makes it a pretty unattractive exchange i'm afraid.

They don't provide ohlcv historic data (max 1 request for 720 candles) - and have a 1 request/3s rate-limit on public endpoints.
Combining these points - it's pretty unattractive as an exchange (the ratelimit will also be potentially problematic for live runs, as you can't use very many pairs without waiting for minutes for all pairs to download).

Now I'm more than happy to get / review PR's (ideally smallish PR's, not one big PR changing 100 things at once, so they can be reviewed and tested quickly).
Obviously they can't / shouldn't break behavior for (other) exchanges - but i guess that should be clear ;)

**Comment by 8de2fdb0** [comment]
Yes that makes all sense.

I guess I will meditate a bit about that issue and come back. Could we keep the issue open for a couple of weeks?

>They don't provide ohlcv historic data (max 1 request for 720 candles) - and have a 1 request/3s rate-limit on public endpoints.

looking at #7510  using websockets would probably solve that issue.

**Comment by xmatthias** [comment]
You might wanna look at #8980, too - it's using a similar approach - but sticks to trades data - which will probably be a bit more flexible / less complex, as it doesn't try to reinvent everything.

**Comment by xmatthias** [comment]
Closing this in favor of #8980.

since kraken is only updating this data once every wuarter (and then not immediately) - it'll not provide uptodate data.
While the same is true for trades data - we can import this, and use it as base for further downloads - which is impossbile with ohlcv data.
