### ISSUE TITLE
Potential solution to "The objective has been evaluated at this point before"

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#9001]
## Describe your environment

  * freqtradeorg/freqtrade -> develop_plot docker image
  * Operating system: Ubuntu 5.4.0
  * Python Version: 3.11.4
  * CCXT version: 3.1.44
  * Freqtrade Version: freqtrade docker-2023.6.dev-a90b7c0b
  
## Describe the feature:

Let's take a situation where buy_ema_short space has 96 possible values (5, 6, ... 99, 100). If you now run hyperopt for the buy space, hyperopt will only have 96 values to try before running out of options. Your epochs should therefore be less then the toal amount of possible values - or you should be ready to interrupt a run if you notice a lot of "The objective has been evaluated at this point before. warnings."

Because the total possible values can be calculated from the start, a calculator function could decide to:
a) run hyperopt as before
b) switch from hyperopt to bruteforce and run through all possible values if epochs >= possible values
c) announce or predict from the start the potential for the objective has been evaluated before warning.

**Comment by xmatthias** [comment]
Freqtrade uses scikit-optimize under the hood - and bayesian search as search algorithm.
It's very well possible for bayesian search to reach a local minima it can't get out of again (so even with only 96 possible values, you get this message after 50 epochs).

the decision what the next point will be happens through scikit-optimize, so the algorithm decides what the next point is.
Early-stopping is dangerous due to the local minima - as it often can get out of the "was evaluated before" hole, too.

b) Scikit-optimize does not offer a Random search method as far as i know. You're free to implement that - but scikit-optimize had no commits merged in almost a year now.
c) the warning is thrown from scikit-optimize. We do have code around this already which tries to get further points (up to 5 times the size of the batch) if this warning is thrown. The warning itself comes from scikit-optimize - and i don't think we should attempt to disable it completely - as it CAN act as a warning sign if it happens too often.

**Comment by vaidab** [comment]
I understand..
Would a code that provides a warning or switches to a bruteforce before entering scikit-optimize work? In some cases you want just bruteforce the params space, no need for the bayesian search.

**Comment by xmatthias** [comment]
Estimators (the one that generates the next point) can be switched as [documented](https://www.freqtrade.io/en/latest/advanced-hyperopt/#overriding-base-estimator).

If you find a "bruteforce" implementation that implements the scikit-interface (`RegressorMixin`, iirc), that should work.

I'm more than happy to add your findings to the documentation (like, to bruteforce / random-search, use this estimator), but i have no plans in maintaining such an estimator as part of freqtrade.

**Comment by vaidab** [comment]
Thank you. Let's leave it open on low prio then.

**Comment by xmatthias** [comment]
> Let's leave it open on low prio then.

I'm not quite thrilled to leave issues open which will never be closed (i don't see any "needs to do X to close"). That'll lead to tons of open issues for no point, and where we have no intend to ever act on.

An addition to the docs can come at any point, and can also link to closed issues (or no issues).

I'll therefore be closing this unless you have some clear activity in mind for this issue.

**Comment by froggleston** [comment]
I agree. This is a scikit configuration option, and nothing to do with how freqtrade works. I'd recommend closing this issue.
