### ISSUE TITLE
Long Iterations 

### ISSUE THREAD

**Issue by tjoshi01** [freqtrade/freqtrade#9037]
Hi,

I am running a historical backtest for a strategy between September 2019 and August 2023. The process takes at least an hour to output all the results. The user has no idea how many months have been covered as they are waiting. 

How much time should we expect the program to take for a 3-year backtest? I have noticed that the issue also affects smaller backtests and Freqtrade's reporting service hangs up indefinitely. I'd appreciate any advice from you regarding this concern.

Thanks!

**Comment by stash86** [comment]
It's all depends on

* Timeframe you use
* Number of pairs you use
* Number of indicators you use

There is no definite number we can give you. If you think it took too long, try to use higher timeframes (hence lesser data) or reduce the pairs and/or indicators

**Comment by tjoshi01** [comment]
Hello, 

Thanks for the reminder. The time frame I am looking for is 1h. If I increase the timeframe in the dataset, I will lose access to the trades in between. The strategy can even execute across a span of minutes. I thought there are ways to catalyze the computation if we are testing 25000+ hours. Can we use distributed systems?

Thanks again for considering this question!

**Comment by stash86** [comment]
Freqtrade is single-thread only, so no you can't run parallel process. Honestly, I have been doing multiple backtests on 200+ pairs on 2+ years timerange on 15m timeframe, so I can't understand how you can get one plus hours on 1h timeframe. Maybe you should try better cpu?

**Comment by xmatthias** [comment]
backtesting timing depends on the points above (timeframe, timerange, number and type of indicator) - as well as on the amount of trades it actually has to simulate.

It's a loop through all candles (for all pairs) - with very little work to do while no trade is open - but with quite some complexity while trades are open - with even more complexity if you use callbacks and protections.


There's however no actual guideline we can give you on actual duration - as a strategy doing 5 trades a month will have a completely different duration than another strategy doing 10 trades per day.

it's correct that there's no feedback - but that's intentional to avoid useless log output (output will add another slowdown to a process).

**Comment by jackchalat** [comment]
What you could do to speed up back test is to limit about the amount of data to process.

1. Test in shorter time period first. Instead of testing 3 years, try testing 4 months first. If you strategy does not produce good results in 4 months, it will be worse in 3 years. However, if your strategy does well in 4 months, gradually increase the time period and adjust your strategy accordingly. This approach does not work for all strategies though.
2. Test only one trade entry logic at a time. Having too many entry points will slow down the back test. If you test one at a time, you can focus on one entry point and save time on other entry points. You still want to test all the entry points together though. But that should be the last thing to do to see the overall result of your strategy.
3. Make trade entry logic more selective. The more trades your strategy makes, the more time it takes. If you strategy filters out a lot of data, it will make less trade and save time. For example, you could filter out all dataframe that has RSI in the 1d timeframe  greater than 70 if you are looking to go long.

In my experience, the CPU does not affect the back test time much. I've used I5 6500t and Ryzen 9 3900x to run back tests and the Ryzen is faster by just an insignificant margin even though it is much more powerful than the I5. So optimizing your testing method will speed up your test more than upgrading the CPU.

**Comment by tjoshi01** [comment]
@xmatthias Thanks for sharing your thoughts. You have given us, I must say, an awesome trade manager in the form of Freqtrade. This is a game changer available for free and without hassle. Moreover, it reports numbers in classic digital fashion and it is one of the most comprehensive things I have seen. 

My two major worries were (1) time taken for backtesting, which I agree can get hampered if feedback is printed, but on the other hand, the cost of repairing a wrong strategy can be considerable without real-time feedback and (2) staking trades so that wealth can be multiplied because, in an inflationary environment, constant amounts of trade and good profits could mean lower returns than a moderately profitable reinvestment strategy. I am hoping to get Freqtrade to agree with my projections, and I am sure it will. Not to mention how good the download-data puller is...

@jackchalat, Agreed. The logic is well set up but since we do not have control over the program's flow, I am unsure how it evaluates (lazy or sudden or greedy) and how it can be potentially optimized.

**Comment by xmatthias** [comment]
> I am hoping to get Freqtrade to agree with my projections, and I am sure it will.

I'm ... not entirely sure what exactly you're looking for. the text before that is neither a question, nor is it really a "we'd want this changed" sentence ... so this feels kinda oddly placed.

**Comment by tjoshi01** [comment]
@xmatthias, if I want 8h timeframe, can each row store the prices for the 8 hours that we are skipping? Maybe set up a new column? But that will not work with the entry-exit conditions. I actually want 8h frame but I'll be trading 1h futures.

**Comment by xmatthias** [comment]
If you're trading at 1h, then your main timeframe will be 1h.

While you can use informative pairs with lower timeframe in theory - that'll cause exploding dataframes (the informative pair will have more data than the actual timeframe) - which will result in 
* the dataframe will expand
* if done wrong, cause lookahead biases

I don't see **any** reason why you'd want to trade on 8h timeframe if your indicators are actually calculated at 1h timeframes.
Trying to do this is being stubborn for no good reason - complicating your life by doing things backwards.

**Comment by tjoshi01** [comment]
Dear @xmatthias, thanks for sharing some advice! :)

Yes, I agree that the correct timeframe should be 1h. To satisfy all parties, it is best to backtest the full history of prices. The demands are steep. The market is very challenging to predict and makes a good example of chaos. I cannot see how we can tick every box but that is my goal anyway. 

End-to-end testing usually starts from 2018 for most crypto securities and the full backtest runs through 32000+ hours. When I use my Python IDE to simulate, it takes an awfully long time to compute hourly returns. That'd be the only reason to try 8h timeframe - as a sampling strategy which selects every 8th point and is hopefully robust when the frequency increases.

**Comment by xmatthias** [comment]
I'd strongly suggest to NOT run debug mode unless you'll actually need it.
that'll always add some overhead - even if you're not having it stop anytime.

That said - 1h data is pretty easy to backtest. 
If it takes a long time, you're probably using either a VERY heavy strategy - or indicators that are slow to calculate.

**Comment by tjoshi01** [comment]
Yup. Will do!
