### ISSUE TITLE
Lock pair duration override

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#9089]
## Describe your environment

  * Operating system: _Docker___
  * Python Version: ___Python 3.11.4
  * CCXT version: __ccxt==4.0.34
  * Freqtrade Version: __docker-2023.7.dev-52ec2324
  
## Your question
Is it possible to override default lock period after the trade is closed for something less then duration of the candle ?
I've tried this but it seem is not exactly the same function https://www.freqtrade.io/en/stable/plugins/#cooldown-period

```
    @property
    def protections(self):
        return  [
            {
                "method": "CooldownPeriod",
                "stop_duration": 1
            }
        ]
```
I'm running 5m strategy and sometimes the signals to exit short are overlapping with enter long and-vice versa. In such cases the second trade is missed due to this cooldown/lockdown period as the signal is being generated on one candle only.

**Comment by xmatthias** [comment]
depends how you use it.
the way you're using it, it'll be locking for 1 minute (not one candle).

[protections](https://www.freqtrade.io/en/stable/plugins/#common-settings-to-all-protections) have 2 ways to define the lock, either via `stop_duration` - or `stop_duration_candles`.

---

this does NOT apply to auto-lock protections - which are automatically applied until the end of the candle.
You can in theory [remove the lock](https://www.freqtrade.io/en/stable/strategy-customization/#locking-pairs-from-within-the-strategy) - but that'll only apply to live, and will not be backtestable (backtesting does not have this explicit lock, but will lock the pair due to it's execution logic until the end of the candle).

It's also a mode/method that we do not support (because it's not backtestable, and we've seen tons of cases where this caused a buy/sell loop, where a stop triggered within the opening candle, causing an immediate rebuy, followed by another stop).
I think the worst i've seen in this is 5-6 cycles within one candle - which is clearly not a position you'll want to find yourself in.

**Comment by darioneto** [comment]
Ok I see, if this is the case then probably best not to touch it.
