### ISSUE TITLE
Less features when using FreqAI with GateIO

### ISSUE THREAD

**Issue by donmega** [freqtrade/freqtrade#9096]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: Docker (`python -V`)
  * CCXT version: 4.0.50 (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-2023.8.dev-716b1cd0 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi!

When using FreqAI with ByBit and OKX i get 5138 features. When using the same strategy with GateIO i get 4098 features. I've also tried other strategies, and the same happens. I don't see any errors in the logging. Could it be that GateIO provides candles in a different format? 

PS: I am using futures (not spot)

Thank you fort your time and your great work!

**Comment by xmatthias** [comment]
candles are for sure in the same format, otherwise things would not work.

Without knowing your actual freqAI configuration / strategy, it's pretty difficult to determine the actual reason for sure, but most likely, it's due to using something unavailable on gate (either an `include_timeframe` or a `include_corr_pairlist` pair).

**Comment by donmega** [comment]
Stupid mistake on my part. There was a difference in the config with GateIO and the other exchanges. My bad!
