### ISSUE TITLE
My Windows Disk Used Space keeps growing forever

### ISSUE THREAD

**Issue by BlackDemonZyT** [freqtrade/freqtrade#9101]
Hey, my Windows Disk Used Space is growing forever...

I found out that this is because this 2 files are growing forever:

![image](https://github.com/freqtrade/freqtrade/assets/46494643/f51cf050-7f03-4cf8-8b56-39196f2a2be3)

How can i make freqtrade clean logs every X time or something?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I'm not entirely sure what makes you think that this is a freqtrade problem.
These are windows system level logs - i don't know what you've got running there - but it's VERY unlikely that it's anything from freqtrade (we do NOT log to windows eventlog).

Freqtrade writes it's logs to files (if specified via `--log-file`) - which are rotating by default, with 100MB as maximum size.

**Comment by froggleston** [comment]
This is almost certainly down to Windows System Insight logs (https://serverfault.com/questions/972272/what-is-the-purpose-of-the-system-data-archiver-feature), perhaps for Windows Server or an Azure instance, gradually getting larger over time and is not related to Freqtrade, so recommend that this issue is closed.
