### ISSUE TITLE
Quaestion abut what happens when you change your budget while running the bot

### ISSUE THREAD

**Issue by BlackDemonZyT** [freqtrade/freqtrade#9107]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.11.5 (`python -V`)
  * CCXT version: v4.0.75 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

If i have for exemple a total budget of 1000$, i tell the bot to open 5 trades at 200$. Now the bot have those 5 trades opened, but from now on, i want the bot to be able to open 10 trades at 100$, if i set up in the config and reload, i won't have enough balance, will the bot bug or the bot won't try to find and open orders until atleast 1 of those 200$ trades are closed?

**Comment by jackchalat** [comment]
In my experience, it will not open any new order unless there is enough fund for that order. If your stake_amount is higher than your wallet balance, it cannot open a trade.  But it should not crash. Anyone else correct me if I'm wrong.

However, I don't recommend changing bot configs when you have positions opened. Although highly unlikely, the market could go the wrong way and your bot won't be able to trigger stop loss (unless you have stop in exchange) or exit positions based on your strategy.

**Comment by BlackDemonZyT** [comment]
> In my experience, it will not open any new order unless there is enough fund for that order. If your stake_amount is higher than your wallet balance, it cannot open a trade. But it should not crash. Anyone else correct me if I'm wrong.
> 
> However, I don't recommend changing bot configs when you have positions opened. Although highly unlikely, the market could go the wrong way and your bot won't be able to trigger stop loss (unless you have stop in exchange) or exit positions based on your strategy.

Then, why nearly all strategies have "stoplossinexchange" set to false?? What is the reason? Isn't it always better to execute directly on exachange??

Also, does stoploss on exchange update also on exchange when the trailing stop loss hits?

**Comment by jackchalat** [comment]
It depends. Having stoploss on exchange also means the exchange knows your stoploss price. Some exchange will use this to their advantage to hunt for users' stoploss. Of course, there is no way to prove or disprove it. But the fact is you are giving away your stoploss price when using stoploss on exchange and you have to trust your exchange to not trade against you.

Stoploss on exchange updates periodically based on `stoploss_on_exchange_interval`

**Comment by xmatthias** [comment]
There's a whole section about configuring the [trade amount](https://www.freqtrade.io/en/stable/configuration/#configuring-amount-per-trade).

using a static 5x200 is fine - except i wouldn't recommend it (not without additional setups, anyway).
if your very first trade is a loss, you're left with a balance of <1000  - so your last trade won't have enough capital.

Freqtrade also (at least assuming a default config) doesn't use 1000$ - but 990$ (keeping the remainder as reserve for eventual fees) (which again, would cause the same problem on the last trade.

Now you can use `amend_last_stake_amount` - (maybe in combination with `last_stake_amount_min_ratio`) to counter this.


In general, i think i'd reocmmend [dynamic stake](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount) - where the bot will use `wallet balance / amount of trades`  - so if your first trade is a loser, the stake amount for new trades will be 190$ - instead of the statically configured amount.

---

Now the question of stoploss on exchange is a different one - and also one of "believe" (and tradeoffs).

I doubt the exchange will care about your 200$ position's stoploss - but if you trade bigger sizes, this CAN be a consideration (though the capital at risk will be higher, so you might want to make sure you get out of a losing trade).

Also, not all exchanges support stoploss on exchange (not in all configurations, anyway) - so a safe, almost always working configuration will be "limit orders / no stoploss".
That does however not say that this is the recommended or best way.
