### ISSUE TITLE
Pairlist keep_invalid missing filter symbols

### ISSUE THREAD

**Issue by santatic** [freqtrade/freqtrade#9127]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.12
  * CCXT version: 4.0.77
  * Freqtrade Version: 2023.7
  
## Describe the problem:

- I have a list of pairs of my own testing broker:
`
['FX:EUR/USD', 'FX:GBP/USD', 'FX:AUD/USD', 'FX:USD/JPY', 'FX:EUR/JPY', 'FX:GBP/JPY']
`

 - After I run `freqtrade trade ...` my parlist filtered to:
`
['FX:GBP/USD', 'FX:USD/JPY', 'FX:GBP/JPY']
` 

- My config:
```json
    "pairlists": [
        {
            "method": "StaticPairList",
            "allow_inactive": true
        }
    ],
```

I found a bug when filter in [expand_pairlist](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/plugins/pairlist/pairlist_helpers.py#L32-L34)

### Steps to reproduce:
```python
import re
result = ['FX:EUR/USD', 'FX:GBP/USD', 'FX:AUD/USD', 'FX:USD/JPY', 'FX:EUR/JPY', 'FX:GBP/JPY']

for element in result:
  if not re.fullmatch(r'^[A-Za-z0-9/-]+$', element):
    result.remove(element)

print(result)

# Result: ['FX:GBP/USD', 'FX:USD/JPY', 'FX:GBP/JPY']
# Expected: []
```
  
### Observed Results:

  * What happened?
  Should not remove original list when loop inside of it

  * What did you expect to happen?
  May be a filter could be work
```python
result = list(filter(lambda s: re.fullmatch(r'^[A-Za-z0-9/-]+$', s), result))
```
  * What did you expect to happen?
  I think Freqtrade should warning if pairlist is wrong format but lets user control the list, It's not clear when we have a flag `keep_invalid` but still filter pairlist.

**Comment by xmatthias** [comment]
In my opinion, it's a bug/problem in the naming of your custom broker.

Freqtrade uses the [ccxt pair naming](https://docs.ccxt.com/#/README?id=questions-on-naming-consistency) conventions- which "FX:EUR/USD" is not really a part of.
You can obviously create your own broker code - but the assumption throughout freqtrade is that it'll correspond to the ccxt conventions (not just in terms of naming, but also in terms of "what" individual endpoints return).

Aside from that - the code you linked (see below) does not intend to filter for valid pairs, but to filter wildcards (`.*/USD`) - which are not valid pairs.

https://github.com/freqtrade/freqtrade/blob/e0e0a258113184ec7d480207100685cb04a8da9c/freqtrade/plugins/pairlist/pairlist_helpers.py#L32-L34

---

As a fun fact - the ACTUAL bug is that the regex is wrong, and should include `:` to account for futures pairs (BTC/USDT:USDT) - after which all of your pairs above will be valid pairs (except they apparently ain't  - but as said above, that's a problem in your broker's code.
