### ISSUE TITLE
scikit-learn and scipy

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#914]
hi.... i had this problem when installing using setup.sh

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/scikit-learn/

**Comment by xmatthias** [comment]
can you please simply retry to run the installation?
from the error, it seems to be a problem with the connection to pypi.org - which is part of the Python infrastructure (and I experienced to be flucky myself since they changed to the new domain a few weeks ago).
I'm sure they will be improving that in the future.

**Comment by fachos** [comment]
ok...thats what im doing... another problem is when im run

source .env/bin/activate; python3.6 freqtrade/main.py
Traceback (most recent call last):
  File "freqtrade/main.py", line 11, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

why?

**Comment by xmatthias** [comment]
did you install freqtrade with the `setup.sh` script and get the final output `pip3 install completed`?

if not, please run `pip install -e .` to install the bot.

**Comment by fachos** [comment]
oh ok... i just pass setup.sh when scikit & scipy error.. i manualy sudo pip3 install -r requiments... theres a pip3 install -e . inside setup.sh... pip or pip3 should i use? ok i try again... thank you xmatthias
