### ISSUE TITLE
Small quirk or normal? use_exit_signal may be false and still warn of not enough currency to exit

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#9164]
## Describe your environment

  * Operating system: ubuntu server
  * Python Version: 3.10.12
  * CCXT version: 4.0.76
  * Freqtrade Version: 25f5dbfcbdaec2094c2e6a5808d03cc49d205d41
  
## Your question

I noticed that if `use_exit_signal` is set to `false`, the code at: https://github.com/freqtrade/freqtrade/blob/21859f79dbb766403ff293b64b019fe1342d9f2f/freqtrade/freqtradebot.py#L1080
may still repeat a warning if the currency is gone from the exchange (for external reasons like manual trading or another bot using it). 

This is probably normal but I wonder if I miss something so I just want to confirm this is intended behavior; I can conditionally ignore it locally so I don't ask for an upstream change if it's not required; it can be a bit spammy as it is because the user may not intend to sell with a bot that has `use_exit_signal` set to `false` and it also triggers a wallets `update()` every time.

**Comment by xmatthias** [comment]
`use_exit_signal` does exactly one thing - prevent the columns `exit_long`, `exit_short` and `sell` (for legacy purposes) from having any effect.

`use_exit_signal` does not mean the bot will not exit (it'll still exit on stoploss, roi, or any of the callbacks).
As such, it'll have no operational impact on the actual exit logic - as all checks (and so forth) are still necessary.

Quite honestly - if `check_exit_amount()` triggers, then it should find out what happened to this trade on exchange (manually sold, position closed, ...).
This means it can happen once per trade after you did "some" activity on exchange (usually independent of the action, but we currently mainly check for regular orders) - but should adjust itself after this (either by closing the trade, or by adjusting the trade to "what's still available to exit").

If it doesn't, then that may be a problem (either with your particular exchange, or with the "WHAT" that happened).
Logs should probably be able to tell us why.

The purpose of this logic is to have a bot state that's aligned to what's on exchange.
If another bot used the trade balance, or you sold it manually, then the bot should know and update accordingly. Otherwise what would the bot do should it actually encounter a sell signal? 
the balance is gone after all.

**Comment by epigramx** [comment]
I see. Yeah it makes sense to have the warning if it can still sell theoretically in the future. I wonder if the software could have a global "never sell" option for specialized uses of that sort but I guess it's unimportant in any case since it wouldn't be for actual strategies.

**Comment by xmatthias** [comment]
Freqtrade is a trading bot. 
there's no reason for a trading bot to have a "never exit" logic - as then you're no longer trading, but investing - and i don't think freqtrade is the right tool for that.

---

Aside from that - it's not a warning - but the subsequent logic will adjust the open position to the actual available amount  (at least that's what it should do).

**Comment by epigramx** [comment]
Yeah I more or less agree, on the basis that any relevant change would first need to consider FT as something aimed to more than regular trading. I guess this should be closed.
