### ISSUE TITLE
Reduce Pairlist when max_open_trades is reached

### ISSUE THREAD

**Issue by Bloodhunter4rc** [freqtrade/freqtrade#9175]
## Describe the enhancement

I would like a strategy option like: limit_pairs_with_max_trades
Which reduces the pairlist to only the active open trades, so if your max_open_trades = 5 and all trade slots are filled, the pairlist should be consisting only of those 5 pairs, which will reduce data usage, cpu usage, and increase the calculation speed for those 5 open trades by a bit. In what file should this be handled (reducing the pairlist)?

Or it could be just a pairlist which checks free_open_trades and returns nothing/open traded pairs if its full, which could be in the last position of the pairlist?

**Comment by xmatthias** [comment]
It sounds pretty simple initially (actually stupid that nobody thought about this before) - but i'm not sure it's that simple, as it'll drastically change some things (mainly around UX).
so before the "how" - i'm not sure about the IF.

For example:
we currently have the full pairlist available - which means people can readily browse charts for these pairs, looking at historic trades for these pairs, ...
sure, that's gone once the pair "moves out" of the pairlist now, too - but that's usually not a "common" case (assuming a dynamic pairlist of ~30-40 pairs or so).

Having the above limitation, you could browse all 30 pairs in the pairlist, unless there's all 5 trade-slots occupied, at which point you'll be limited to the 5 open pairs.

From a UX perspective, i find this pretty bad, actually (in both below scenarios):

If we assume the pairlist to be there (30 pairs) - but we don't reload and calculate the remaining 25 pairs, we'll still have the UI show all pairs - but the data will be outdated (for no good / apparent reason).
If we "empty" the whitelist directly - then the pairs won't even be selectable.

Neither option is good in my opinion, and both will drastically reduce the UX - but for what reason exactly?

**Comment by Bloodhunter4rc** [comment]
Think that depends on the user, for example it would be nice to have less requests on my dryruns to the exchange, but also generally reducing everything what is not needed atm to save resources. Why calculate 50 pairs indicators if nothing is going to happen anyway, its more of a QOL issue :D But yes downside would be you cant look at the other charts, till a trade exits, and the pairlist returns (then you will be able to look at historic trades again?), and it would need to recalculate indicators once that happens (which could be another performance decrease) The question is if this is worth it, atleast not as default setting.

I had pairs removed from the pairlist with open trades, you could still view them in the ui and indicators are calculated, so a empty pairlist would still make atleast the open trades selectable.

**Comment by xmatthias** [comment]
I'm not sure it's a QoL issue if you then lose the ability to look at a trade that just closed, just because a new one opened a minute later (filling the last trade spot again).

open trades will be selectable, yes - but others ones won't, even if a trade closed - say 2 minutes ago.

As mentioned above - _at first_ - it sounds like a great, very logical idea, but the more i think about it, i think it's actually not. 
it makes "what's available in the ui" (as well as how does the bot actually execute) a lot less predictable.

**Comment by stash86** [comment]
Personally I'm a fan of this feature. You can make this optional, so unless they activate it, users won't notice it.

regarding the frequi issue, I'm in the camp of "let the bot do their job" and don't check charts. If I'm using this feature and want to check the chart, I assume by turning this off and restarting the bot will bring the charts back to normal?

**Comment by xmatthias** [comment]
If you think it's a must (i don't), feel free to submit a pr (i'll keep this around for about a month - if we don't get a PR by then, i'll assume it's not as interesting as it sounded).

please make sure that it's 
* VERY well covered in tests (this touches very core functionality, so must be VERY well covered to avoid malfunctionings, as well as regressions).
* Has a short (but well explaining) documentation segment explaining what it's supposed to do, and what limitations it'll introduce.
* make it config only (there's too many "strategy too" settings already - this is not relevant for strategy execution  (it's not the strategy's business if i want to see all pairs in freqUI or not), so a config only option will be fine.

Please also make sure to tripple-check compatibility with different functionalities (mainly freqAI, where i fear this can have very bad side-effects).


__note__ to me this is still not a very good idea (for reasons outlined above), so i will remove this functionality without deprecation period should it introduce a lot of user confusion.

**Comment by stash86** [comment]
@Bloodhunter4rc can you try this and see whether it works as what you want?
Basically what it does is checking open trades every bot loop, then compare it to max_open_trades value. When the trade slots are full, it immediately clear the whitelist. When a trade closed, it immediately restore the pairlist.

https://github.com/stash86/freqtrade/tree/full-pairlist

To use this, just add `FullTradesFilter` to your config. Ignore the logging for now

**Comment by stash86** [comment]
Now, any idea on what needs to be measured to see whether what/how much improvement this filter brings?

**Comment by xmatthias** [comment]
I'm not entirely sure if i'd do this as an independent pairlist.

The idea is good - BUT you'll void all caching for other pairlists - unless it's forced to be last, otherwise otherwise pairlists could also add to the filtered pairlists again, which (while not common) is something that IS possible.

I'd also use `Trade.get_open_trade_count()` - that'll be a better / simpler result (by moving the work to the database) - and won't need the attributeerror handling (though this filter will be inactive in backtesting anyway), since pairlists are only evaluated initially, while trades will always be 0.

**Comment by stash86** [comment]
I'll test it as not-the-last filter

**Comment by stash86** [comment]
Any idea which caching filter might cause the cache issue? Because I tested the existing filters, and they all behave correctly when FullTradesFilter is placed in the middle.

In theory, if there an issue with cache of a specific filter in the future (maybe a new filter), then in my opinion that filter/pairlist is the one needed fixing, because pairlist can change at anytime even without this new proposed filter, for example if I put VolumePairlist's refresh period to 10 secs. And from existing filters, the only thing that can remove cache is when it expires, not even an empty pairlist can (and should) remove the cache.

And regarding the freqai compatibility, since freqai using static list, and even if it uses another filter, as tested above, cache works fine. And #9179 would fix the potential issue

**Comment by xmatthias** [comment]
> Any idea which caching filter might cause the cache issue? Because I tested the existing filters, and they all behave correctly when FullTradesFilter is placed in the middle.

Use Volumepairlist (maybe top 5 pairs), followed by FullTradesFilter, followed by StaticPairlist with a few more pairs (not the ones you have open trades for).

StaticPairlist will add all pairs that are not in the pairlist yet - but that's not a bug, but part of it's functionality (with this, you can use volumepairlist, but force a few selected pairs to be present at all times).


---

That's however NOT the point i was looking at, really.
if you use - say RangeFilter after this - then you'll no longer check for any pairs, and the cache will age out - and once pairs "return", cache is empty and must be filled.
that's not a problem per se, and will happen anyway at specified intervals - but this will force it.

**Comment by robcaulk** [comment]
I tried to scan the thread here. I’ll give a quick 2p:

freqAI’s main limitation is indeed the inability to handle dynamically changing pairlists. But it is also well known and documented. So if this is just another dynamic pairlist filter, then I see no real difference compared to existing dynamic filters.

If it is a config setting, then it should be easy enough to validate the conflict in the config validation and log a warning to freqai users telling them “don’t do that again ;), we’ve changed it back to static pairs.” And that solves the freqai conflict entirely.

**Comment by stash86** [comment]
for freqai use, look at this as dynamic within static list. So the base is still your static list, but when yout trade slots are full, it reduces your pairlist to only the pairs in trade. The issue will come when the trades are opened long enough that the bot will start to missing out on some new candles on those "being hidden" pairs, which I believe what your current PR try to fix

**Comment by stash86** [comment]
> > Any idea which caching filter might cause the cache issue? Because I tested the existing filters, and they all behave correctly when FullTradesFilter is placed in the middle.
> 
> Use Volumepairlist (maybe top 5 pairs), followed by FullTradesFilter, followed by StaticPairlist with a few more pairs (not the ones you have open trades for).
> 
> StaticPairlist will add all pairs that are not in the pairlist yet - but that's not a bug, but part of it's functionality (with this, you can use volumepairlist, but force a few selected pairs to be present at all times).
> 
> That's however NOT the point i was looking at, really. if you use - say RangeFilter after this - then you'll no longer check for any pairs, and the cache will age out - and once pairs "return", cache is empty and must be filled. that's not a problem per se, and will happen anyway at specified intervals - but this will force it.

based of my quick test using verbose mode, the cache seems to not aged out, maybe because the whitelist never really empty. When I bring back the hidden pairs, there is no "downloading 1d candles" log messages

**Comment by xmatthias** [comment]
depends on your setup.

> When I bring back the hidden pairs, there is no "downloading 1d candles" log messages

For this to appear, you'll need to have the pairlist full for > 1 day - until the cache invalidates. a 1d timeframe is unsuitable for this testing though, unless you have time forever.
You can't test this in 5 minutes - as it's a time-based problem.

try it with volumepairlist 1h candles, which refreshes every 1h (or pick any other lower timeframe for quicker testing - make sure to adjust refresh-timing as well) - at which point, the 1h messages will come every 1 hour (assuming volumepairlist is PRIOR to the Full filter. 
If it's after / later - you'll get the messages once trading resumes.

---

Thinking about it, both are potentially problematic 
either, the cache will be reloaded (which is unnecessary) - so assuming we'd reload this every 5m (on 5m candles) - we'd be loading ALL pairs every 5 minutes - but then this filter evicts all pairs - making the whole work done for pairlist generation unnecessary (which can be quite timeconsuming, depending on the exchange / settings).
Alternatively, we skip the whole pairlist generation, which avoids work we know we throw away later ... at the expense of "potential work to be done once a slot becomes available".


As said, i'm not entirely sure if "as a pairlist" is the correct approach, or if a "should be a config setting" would be better - as that would allow you to skip the pairlist generation in the first place, reducing traffic further (if that's our concern, anyway).

Both have downsides, and will depend on your expectation (trading on 1m data makes a slow restart way more severe than on 1h candles).

**Comment by stash86** [comment]
So my current test, I'm using DoesNothingStrategy on 1m timeframe, 3 max open trades. Entries and exits are all forced.

When the slot isn't full, there are `freqtrade.exchange.exchange - DEBUG - Using cached candle (OHLCV) data for SOL/USDT, 1m, spot ...` printed every bot loop for each pairs. When the slot is full, that message only printed for the pairs in open trade. When new candles arrives, the candles downloaded are only for those 3 pairs. When a slot open, then the bot will download the candles for the rest of the pairs.

So I believe that is the "slow restart" you mean? I don't think it's a slow restart, since when a trade opened, it just download the missing data that it should have download anyway. Instead of downloading (for example) candles for 50 pairs at xx:00:00, it download candles of 3 pairs at xx:00:00, and when a trade exit at xx:00:20 for example, it download the candles of 47 pairs at xx:00:21. I don't think there is any extra data traffic.

The only issue I can think of is late entry. We can put in the docs that if user want to use this, they might want to use the ignored expired candle config setting.

**Comment by stash86** [comment]
Regarding the volumepairlist, I don't see the issue. The pairlist will download the data and store it in the cache, whether user use this filter or not. Yes, most of those data won't be used when the slot is full, but it's still in the cache and not an extra steps/loads compared to not using this filter.

When a slot opened within the 1h window, the bot will use the cache to bring back the "full" pairlist without re-downloading the volume data. So yes the bot might download unused data, but it's not different than non-trimmed whitelist.

The saving will come from CPU usage since there is no need to calculate indicators on those extra pairs when the slot is full. Might make exit signals triggered slightly faster as well.

**Comment by xmatthias** [comment]
> So I believe that is the "slow restart" you mean?

no, this is normal and expected, but not what i'm talking about above (the impact "after" the pairlist is generated is pretty clear to me).

It's the Volumepairlist which is doing unnecessary work / downloads - downloading data for all pairs the exchange has to offer (for your quote currency).
This is where you either have unnecessary downloads (assuming a low timeframe with frequent refreshes)  - or a slow startup (needs to download data for several 100 pairs before continuing).
It obviously assumes the "advanced" volumepairlist config - and isn't really limited to volumepairlist, either (rangefilter, agefilter, ...).

I'm not sure if that's a problem (the unnecessary downloads) - but going the "pairlist" route for this will block the other option (we'll not have a config flag AND a pairlist setting for this).

**Comment by stash86** [comment]
* unnecessary downloads, yes.
* Slow startup, yes, but since we assume it's far past candle close time, we don't want to open any new trade anyway. We prefer waiting for next candle. So the slow startup shouldn't affect anything other than slightly delaying checks for exit of current open trades
* Yes I don't think any config flag is required

**Comment by stash86** [comment]
Maybe I should put a timer inside bot loop?

**Comment by xmatthias** [comment]
on debug, there is a timer in the bot loop (in the worker.py file).

As a side note: 
i'm just pointing out behaviors we can expect - which one we accept and won't is a different topic.

i do NOT consider "downloading data for pairs in pairlist" as slow startup - that's something that'll happen once per candle anyway.

**Comment by robcaulk** [comment]
> for freqai use, look at this as dynamic within static list. So the base is still your static list, but when yout trade slots are full, it reduces your pairlist to only the pairs in trade. The issue will come when the trades are opened long enough that the bot will start to missing out on some new candles on those "being hidden" pairs, which I believe what your current PR try to fix

It all depends on how it modifies the `strategy.dp.current_whitelist()` behavior. If your filter removes pairs from the returned list, then it will negatively affect both training and inferencing of FreqAI. It will stop training the removed pairs, and it will stop collecting data on the removed pairs. When the pairs "come back," the models will be outdated and the training data for subsequent models will have holes.

#9179 is unrelated, it is focused on helping reloads more accurately populate FreqUI visualizations.

**Comment by stash86** [comment]
So I guess I'll have to put lines to detect whether it's freqai or not, and throw error if it's freqai bot

**Comment by robcaulk** [comment]
> So I guess I'll have to put lines to detect whether it's freqai or not, and throw error if it's freqai bot

If it is a config option, we can do it all in the configuration validation. I can help with that part of your PR, just point me to your work and I will add it.

**Comment by stash86** [comment]
I'll tag you in the PR once it's ready

**Comment by Bloodhunter4rc** [comment]
Yes thats how i thought about it, i did spin up your branch.

I do not see the need to incorporate options for freqai, if its clear that freqai wont work with dynamic pairlists as stated in the docs? i find this more a users responsibility, i dont think that config validation check is there for most other dynamic filters/pairlist either or is this planned to be added? If needed it can be stated in the docs.

Looking at the much simpler pairlist/filter seems better in this case, also it fits in that category, i dont think a config option is needed after all.

For adding Pairlists after the FullTradesFilter in the order a simple check if its in last position on init and if not throw a exception would be enough for me (if that causes issues) + stating in the docs that its needs to be in the last position. Only issue i can think of if there will be any other pairlist/filter in the future with the same requirement, then they would need to be merged.

**Comment by xmatthias** [comment]
If it's not a config option, but a pairlist filter, then i think freqAI is covered by the "no dynamic pairlists" clause.

**Comment by stash86** [comment]
Gonna open a PR then.
