### ISSUE TITLE
Calculation of the cumulative profit and leverage seems off

### ISSUE THREAD

**Issue by mexxBf** [freqtrade/freqtrade#9184]
Hello,

In a recent trade notification, the reported cumulative profit was 2.00%, translating to a profit of 0.33200000 USDT. However, based on the trade details provided, I'm unable to reconcile how this profit value was derived.

Trade Details:
- Direction: Short
- Leverage: 10.0
- Amount: 166.00000000
- Open Rate: 1.00150000
- Exit Rate: 0.99850000
- Exit Reason: partial_exit (33.33% of the position)

✳ Okx (dry): Partially exiting BAND/USDT:USDT (#3)
Unrealized Sub Profit: 2.00% (profit: 0.33200000 USDT / 0.332 USD)
Cumulative Profit: (0.00000000 USDT / 0.000 USD)
Enter Tag: 1694620800000
Exit Reason: partial_exit
Direction: Short
Leverage: 10.0
Amount: 166.00000000
Open Rate: 1.00150000
Current Rate: 0.99850000
Exit Rate: 0.99850000
Remaining: (49.975 USDT, 49.966 USD)

✳ Okx (dry): Exited BAND/USDT:USDT (#3)
Cumulative Profit: 2.00% (profit: 0.33200000 USDT / 0.332 USD)
Enter Tag: 1694620800000
Exit Reason: partial_exit
Direction: Short
Leverage: 10.0
Amount: 166.00000000
Open Rate: 1.00150000
Exit Rate: 0.99850000
Remaining: (33.35 USDT, 33.344 USD)

Could you please clarify how the profit of 0.332 USDT was calculated for this trade?

Thank you!

  * Operating system: Ubuntu
  * Freqtrade Version: V: 0.9.7 docker-compose

**Comment by stash86** [comment]
(49.975-33.35) * 0.02?

**Comment by mexxBf** [comment]
That's true, but it's leveraged by 10. The Amount of 166 shows that the position is roughly 150 usdt of worth.

**Comment by stash86** [comment]
Open Rate: 1.00150000
Exit Rate: 0.99850000

If you calculate this, the actual profit is only around 0.2% after fees. 0.2% * 10 = 2%?

**Comment by mexxBf** [comment]
Okay so this means that the profit calculated with the adjust_trade_position in current_profit does not represent the leveraged position? My first tp was 0.02 percent. 


Thank you for your help!

**Comment by stash86** [comment]
0.02 or 0.02%? They are greatly different.

profit calculated in adjust_trade_position already include leverage

**Comment by mexxBf** [comment]
This is my adjust_trade_position:  

``` python
    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:
        """
        Custom trade adjustment logic, returning the stake amount that a trade should be
        increased or decreased.
        Positive values to increase position, Negative values to decrease position.
        Return None for no action.
        """
        # Sell one-third of the position at 2.5% profit
        if current_profit > 0.025 and trade.nr_of_successful_exits == 0:
            return -(trade.stake_amount / 3)

        # Sell one-third of the position at 5% profit
        if current_profit > 0.05 and trade.nr_of_successful_exits == 1:
            return -(trade.stake_amount / 3)

        # Sell one-third of the position at 150% profit
        #if current_profit > 1.50 and trade.nr_of_successful_exits == 2:
        #    return -(trade.stake_amount / 3)

        return None 
```

 

I thought it should mean sell at 2.5% (its compensating for the fees i guess, because if its set to 2 its about 1.76%) and sell the second 33.33% of the position at 5%.

**Comment by xmatthias** [comment]
`current_profit` for `adjust_trade_position()` is calculated using entry pricing.
Assuming your pricing configuration for entries says "other" - this will mean that your calculation (2.5%) is for the first ask price on a long.

Now as it's an exit, the actual rate it's selling is at the first bid price - so you're crossing the spread, which depending on the pair (not BTC necessarily), can be (or exceed 0.5% quite easily).

Fees are irrelevant to this - as they're included in the calculation - based on the assumption that entry-fees apply to both entry and exit (we don't actually know until an order is being placed - so this is the best effort assumption).


If you're looking for exit profits, you should rather use `current_exit_profit` in your calculations - which uses the exit-pricing logic (bids for a long) - and will therefore usually keep you in a trade "longer" (actual behavior will depend on pricing configured).

**Comment by mexxBf** [comment]
To be honest, I'm a little lost right now. I would like to recap my problem I guess there is something I am missing.

The bot is running in dry mode. It has 100 Usdt to work with, its allowed to buy two positions. It can go long and short. The buys are triggered via Freqtrade API. The leverage 10 it is set in the strategyfile. The position, when entered show: 49,364 (10x). Its allowed to use 0.99 of the balance.  The position shows STX/USDT:USDT | 1060 bought at 0,4657. So its about 493 Usdt. Thats quite close to the 500Usdt (50 Usdt * 10 leverage). 

The question now is, what does 2% gain mean in the adjust_trade_position?
current_profit is calculated by the entry price compared to the "other" ask price, as you correctly assumed. 
2% of the "movement" of the price is always the same, if its leveraged or not, so my adjust_trade_position should be correct, at least for a long? 

So the first question is, how would the function look like for long and short positions?

And the second question: why does it show Cumulative Profit: 2.00% (profit: 0.33200000 USDT / 0.332 USD) if the position is about 500 Usdt in size? Shouldnt 2% of 493 Usdt be more like 9 to 10 Usdt? 

I'm sorry if you already answered the question above but I didn't get it then :D 

Thank you!

**Comment by xmatthias** [comment]
Your last post is more confusing than anything - why are we suddenly in STX - while the exit messages were for BAND? 
If i were to use your last info, you'd have made >50% price profits (your buy was for 0.46 .. the exit you posted was for 0.998 . . . which (while possible) - is not what happened.

As such, i'll have to ignore all info in the last message, as it's unclear what belongs to which trade.

---

Keep in mind, we're working with the information provided here. if that information is then even confusing / conflicting, jumping between trades without warning - it becomes a mess pretty soon

To FULLY follow your calculations, that's not enough (we don't know how many entry/exit orders your trade did, nor much else). 
The calculations used when doing position adjustments are [in the documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#position-adjust-calculations).

---

> Shouldnt 2% of 493 Usdt be more like 9 to 10 Usdt?

if you look at relative profits - it's all a question of "against what"?
A partial exit won't show you the profit against the full position, but against the value you're exiting (otherwise values would become very low eventually).

For your math...
your exit is for 166 BAND - at 0.998$ - based on an entry of 1.0015$.

So absolute is quite easily calculated as (1.0015 * 166 - 0.998 * 166) (minus fees, which are not known at this point).
The above calculation gives about 0.5810$ of profit - subtracting fees, 0.332$ doesn't seem impossible or even far off (on futures it'll depends not just on order fees, but also funding fees eventually)  - as it'll depend on the original size (that'd be ~20c of fees, assuming your other message, assuming a full position of ~500$ - it's quite realistic).

the 2% it's showing you for the 0.332 are against the assumed partial entry (which probably didn't happen - calculated as exited amount * avg entry rate - or 1.0015 * 166. 
as i'm lazy now - 1.0015 * 166 * 0.002 (the relative profit) is exactly 0.332$ ... (in reality, the calculation happens the other direction, starting with 0.332$ against 1.0015 * 166 ).

**Comment by xmatthias** [comment]
On a different note - what's your actual freqtrade version? 0.9.7 is not a freqtrade version, but the freqUI version (you can see this version in the general tab on freqUI, or in the logs).

I'm asking this because `Cumulative Profit: 2.00% (profit: 0.33200000 USDT / 0.332 USD)` is NOT a message freqtrade will show (we don't show relative profit for the "cumulative " row of exit messages as the "relative against what" is unclear for these  - and did not do this in _at least_ 6 months - which is when the relevant line last changed).

This means you're either running a modified version of freqtrade - or a very outdated version of freqtrade - neither of which we'll be able to help you with much further.

**Comment by mexxBf** [comment]
I'm sorry, I had no intention to confuse you even more... For me it wasn't tied to the BAND/USDT trade, but I seem to have a more general problem of getting the numbers together.

The line "Cumulative Profit: 2.00% (profit: 0.33200000 USDT / 0.332 USD)" is part of the Telegram output. I checked the version of freqtrade I'm running and its 2023.8 with docker compose. 

> the 2% it's showing you for the 0.332 are against the assumed partial entry (which probably didn't happen - calculated as exited amount * avg entry rate - or 1.0015 * 166.
as i'm lazy now - 1.0015 * 166 * 0.002 (the relative profit) is exactly 0.332$ ... (in reality, the calculation happens the other direction, starting with 0.332$ against 1.0015 * 166 ).

This is the part I don't understand, really. The position was filled completely, as its bought "market". And why would it be * 0.002? The partial exit in the strategyfile is defined as 1/3 with 0.025. 

Maybe its helpful to say what I would expect to see.

my balance is 100 Usdt, I wan't to have two positions. The balance is split evenly, so the positions are bought with roughly 50 Usdt per position. With the 10x leverage the position will have sizes of around 500 Usdt. 1/3rd of the position (166Usdt) will be sold at 2% gain, so I would expect something around 3 Usdt as profit, because thats 2% of the initial 166 Usdt. 

Maybe its clearer now, where I get lost with the calculation.

Again, thank you for your efforts.

**Comment by stash86** [comment]
as I have answer above
`(49.975-33.35) * 0.02`

That partial exit only sold ~16 USDT, which means 2% of 16 USDT is around 0.3 USDT

My advice, add log print to your strategy so you know what is happening inside it, instead of just guessing

**Comment by mexxBf** [comment]
Thats a good idea, i will do that :)

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below if it's still unclear.
