### ISSUE TITLE
How to downgrade Python in freqtrade docker?

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#9234]
## Describe your environment

  * Operating system: Ubuntu 22.04.2 LTS(docker)
  * Python Version: python 3.11.4
  * CCXT version: 4.0.71
  * Freqtrade Version: freqtrade 2023.8
  
## Your question

Hello Team:)
I'm trying to implement UTbot strategy in freqtrade.

By the way, to implement utbot, vectorbt is required. 
(Actually vectorbt's Installation is only possible in Python 3.6 or higher but lower than 3.9.)
I attempted to downgrade python, but 'sudo' are required.

Is there any other way?

**Comment by xmatthias** [comment]
You can try to rebuild the freqtrade image from scratch, changing the base image to a different image (everything >=3.9 should work in theory - though the docker build process is only tested for the most recent python version).

Alternatively (and most likely more suitable for your usecase) - you can pick a native installation method, where you can directly control the python version (again >=3.9).

It should be noted howeer that freqtrade (and it's dependencies) do not support python versions prior to python 3.9.

That's not an artificial barrier, either, but due to some breaking syntax changes in python - and once a project starts using 3.9 only features, all prior versions automatically no longer work.

**Comment by thkwon9474** [comment]
Thank you so much!
