### ISSUE TITLE
about increase，please help me，thanks

### ISSUE THREAD

**Issue by xxmmxx** [freqtrade/freqtrade#9294]
Excuse me, Binance Perpetual Futures Contract, how to achieve the increase ranking of multiple contract pairs in a tick (within 24 hours)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Aside from that - i have no idea what you're actually asking.
We will need some further clarification of the actual question, otherwise we'll not be able to assist you.

**Comment by xmatthias** [comment]
As the question wasn't clarified, closing.

Feel free to comment below if it's still an issue and you'd like to elaborate this  a bit better.
You can also open a new issue - however make sure to include some more information of what you're actually trying to accomplish - giving us sufficient information to actually be able to help you.
