### ISSUE TITLE
Can freqtrade please consider implementing an exit mechanism based on the growth rate?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9299]
## Describe your environment
(if applicable)

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.8

## Describe the enhancement

*Explain the enhancement you would like*

Can we consider adding an exit mechanism based on the growth rate?

For example, when using `minimal_roi`, whenever the specified percentage increase is achieved within a specified time frame, the assets will be sold.

For instance, if we set it to sell if there is a 10% increase within 30 minutes.

During the active period of minimal_roi, there will be two scenarios:

1. If the cumulative increase reaches the value set by `minimal_roi`, the assets will be sold.
2. If the cumulative increase hasn't reached the value set by `minimal_roi`, but there has been a recent increase of more than 10% within the last 30 minutes, the assets will be sold.

I'm not sure if this suggestion is mature, but based on my real trading experience, I believe having this feature would be beneficial. I hope you can consider adding this functionality.

Thank you to the developers for creating such a great product like freqtrade, and I wish freqtrade continuous improvement.

**Comment by stash86** [comment]
You can use custom_stoploss or custom_exit for this. You can check percentage change and react accordingly

**Comment by xmatthias** [comment]
you'll probably want to use [`custom_exit`](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal) here, not custom stoploss (which would move your stop instead of selling immediately) - but i absolutely agree - this is your custom logic - so i don't see why it should be builtin.

everything builtin is will always be limiting to some degree (needs to be configurable by parameters, not all future ideas are immediately clear, ...) - `custom_exit()` callbacks on the other hand are only limited 
by your immagination (and ability to bring the imagination into working code).
