### ISSUE TITLE
show % in detail section in freqUI of closed trades between open rate and min rate. and open rate and max rate.

### ISSUE THREAD

**Issue by Deech123** [freqtrade/freqtrade#9324]
## Describe the enhancement
Hi, is it possible to add extra code in the freqUI interface?
When opening the details of a trade you can find the open rate, closed rate, min rate , max rate etc...
it would be nice to see that after the min rate we get the % in difference between the open rate and min rate.
Same as the % also between open rate and max rate.

*Explain the enhancement you would like*
If we have beside the min rate also the % in difference and also the % after max rate, we can have a quicker analyse if we want to use a SL how deep trades wend down or up before we get to our closed rated.
With a quick % between ( ) after the min rate and max rate value based ofcourse on open rate, this would be a nice extra value.

**Comment by xmatthias** [comment]
in theory - sure
in practice, i don't think it makes much sense, at least not if you're using trade adjustments.

the min/max rate doesn't tell you the position size at that point - so while it might've been the lowest point from a rate perspective, it's not really indicative of anything.
if that difference would show you 20% ... what's that mean? your trade could have sold 5% higher - but due to several further position adjustments, have been effectively a 25% loss.

**Comment by Deech123** [comment]
well, actually, if you have a % after min rate, that will tell you how deep the lowest point was in your trade.
And based on that, you can (even if you have a trailing SL) make a hard emercency SL based on those values.
If all trades max deepest point was like 6% ,then add hard SL at 8% for example in case market has sudden collaps.
it's a minor change in the code I think since the formule is not that complicate/
1. MIN rate - open rate = X1
2. (Min rate + open rate)/2 = X2
3. (X1/X2)*100 = value in % of deepest point compared to open rate.

**Comment by xmatthias** [comment]
as said above - the value of this will strongly depend on the method you're trading - which effectively means this won't scale without becoming wrong / useless depending on your strategy.

If you're using position adjustments, open_rate can and will change over time [documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).
With that premise, you also can't assume "my rate dropped by  6% - so a stop at -8% would work" - as a 6% price move does not equal to 6% loss if your position size changed anytime within the trade.


I therefore don't see us adding this - at least not in it's current form (min-rate is really a pointless measure on it's own since position adjustments have been introduced).

We _might_ introduce more valuable metrics which account for position size at that moment of the trade - but until then, this will be more confusing than what value it'll bring.
