### ISSUE TITLE
Freqtrade sometimes reports trades wrongly on kucoin

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#9346]
## Describe your environment
  * OS: Ubuntu 22.04.3 LTS
  * Freqtrade Version: 2023.9 stable (docker compose)

## Describe the problem:

on some trades the exit does not report properly. There it says it has more loss on spot with selling than it is having $ in the wallet for all trade slots

10 recent trades:
Close Date    Pair (ID)          Profit (USDT)
------------  -----------------  ------------------------
8 hours ago   IGU/USDT (#385)    1.85% (...)
12 hours ago  IGU/USDT (#384)    1.26% (...)
13 hours ago  IGU/USDT (#383)    12.93% (...)
13 hours ago  IGU/USDT (#382)    -36.45% (...)
14 hours ago  IGU/USDT (#381)    1.12% (...)
15 hours ago  IGU/USDT (#380)    3.79% (...)
21 hours ago  IGU/USDT (#379)    1.23% (...)
a day ago     UPO/USDT (#378)    1.84% (...)
a day ago     UPO/USDT (#377)    1.55% (...)
**2 days ago    FLOKI/USDT (#376)  -92.27% (-8270.49735089)**

### Steps to reproduce:
it happens every now and then on kucoin on live, the other trade right beside it had no issues at all. The behavior is there every now and then since a few months. 

The open rate is proper, but the close rate is not. it is 1/10th of what it should be, seems kucoin switched the rate-factorization around?
  
### Observed Results:

  * What happened?
a trade was done as usual, but one of the two almost parallel trades were reporting exits wrong.
Kucoin might have switched its' rate calculation up during the trade
  * What did you expect to happen?
report exits properly, as the orders are showing should be too
If the calculation of the pair switches, don't assume automatically that it stayed the same - get the value of the rate including its factorization so every value is properly caught

### Relevant code exceptions or logs
![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/225ac0a5-4ef8-4fa5-bccf-5e83db5f98b1)
![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/9674a363-7d69-4cfc-87ac-06e7c2e4bd60)
![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/eb94509c-8ceb-44d1-842b-d94f13114426)

![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/4592d1ed-2df5-46cf-969f-51c06f760c2c)

**Comment by xmatthias** [comment]
Well the problem is quite simple (although unfortunate, and actually known to be an issue for kucoin).

The precision values for FLOKI are `'amount': 1e-10, 'price': 1e-09`  - and adding these together actually results in leaving behind a 1e-8 amount.

(extracted from the following command):
``` python
import ccxt
exchange = ccxt.kucoin()
lm = exchange.load_markets()
print(lm['FLOKI/USDT'])
```

Loading this trade in an interactive environment (db was shared in private) - this can be quite easily seen:

![image](https://github.com/freqtrade/freqtrade/assets/5024695/309584fd-3a57-4ef4-b87c-eb3e6764db34)

![image](https://github.com/freqtrade/freqtrade/assets/5024695/a54123dd-9e52-424c-9733-76cf2b75218c)


The end-result does not even out evenly.

``` py
> print(f"{11511963.8634448908 + 11750101.7743937783:.15f}")
'23262065.637838669121265'
> print(f"{23262065.6378386617:.15f}")
'23262065.637838661670685'
```

Now i know that kucoin is returning these values via API (up to 16 digits iirc) - but IIRC the UI is applying some kind of rounding on top of it, so you might not see the 16 decimals.

---

Please check this trade (or rather, it's orders) in the UI - and get me some screenshots for the 3 orders that apply to this trade. 
I hope to gain some details on the actual rounding they apply. If we can round it the same way, it might be able to have it even out correctly.

It'd also be interesting / important to see if this trade has really left 1e-8 floki behind as the sum of the individual order amounts suggests.

**Comment by hippocritical** [comment]
> Please check this trade (or rather, it's orders) in the UI - and get me some screenshots for the 3 orders that apply to this trade.
> I hope to gain some details on the actual rounding they apply. If we can round it the same way, it might be able to have it even out correctly.

![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/7096c69f-72bf-46f7-ba23-3a7906c0a14a)
![grafik](https://github.com/freqtrade/freqtrade/assets/41228167/89754934-0a68-4b5b-9caa-1a12eb3d0061)
