### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by IMWurden** [freqtrade/freqtrade#9370]
Is there a method to auto-update in real time the repo on my PC folder?

**Comment by OlguD** [comment]
Git hooks will allow you to do extra things after issuing the git pull command, but not to periodically run a git pull.

**Comment by xmatthias** [comment]
Not that i know off.
You can always use a cron-job to schedule your git pulls eventually.

It's however neither something we'll be providing support for (it's a generic git topic, not related to freqtrade), nor is it something i'd recommend (for freqtrade specifically).

We will list breaking changes and behavioral changes in the Release Notes (we try to avoid this as much as possible, but that's no guarantee).

Should you run into one of these, you might be hit with a no longer running bot (or one that now behaves differently) - and it's then left to you to figure out 
* that the bot stopped (have good monitoring in place)
* why it stopped and what the fix is
* what the changed behavior is - which you may only notice after weeks of different behavior

As such, i'd clearly advise against this - and for "live" bots, the recommendation is to stick to stable versions - while carefully reviewing the highlighted changes in the release log before updating (which you should do for most important softwares anyway).
