### ISSUE TITLE
it is possible to run multiple bots use same chatID and different token?

### ISSUE THREAD

**Issue by csquan** [freqtrade/freqtrade#9403]
it is possible to run multiple bots use same chatID and different token?

**Comment by csquan** [comment]
only one account of telegaram ,so same chat ID but can get different token.

**Comment by xmatthias** [comment]
Yes you can (chatid identifies you, not the bot), but you'll have to configure multiple Bots, and press "start" in each of the conversations.

[multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) does cover this, too to some extend.

**Comment by csquan** [comment]
I mean use same chatID ,[multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) does not cover this,read many times,

**Comment by stash86** [comment]
why don't you just try it and see if it's working or not, instead of keep opening new issues?

**Comment by xmatthias** [comment]
You have been given the answer [here](https://github.com/freqtrade/freqtrade/issues/9403#issuecomment-1805976154).

don't just read the documentation, but also the actual answer - which includes the answer exactly to your question.

Please don't spam issues with the same question - otherwise we'll be forced to ban you from this repository (you have 3 identical issues opened within the last 24 hours. 
A closed issue doesn't mean you can't comment on it if it's still unclear (but give us time to actually answer, we're volunteers working on helping people, not a paid support)
