### ISSUE TITLE
Is it possible to define ROI, stoploss and trailing stop depending on the position direction?

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#9424]
## Describe your environment

  * Operating system: MacOS
  * Python Version: Python 3.11.5
  * CCXT version: ccxt==3.0.47
  * Freqtrade Version: freqtrade docker-2023.10-dev-8c633aab
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Is it possible to have different ROI settings, stop loss and trailing stop depending on whether the position is a long or a short position?

If not possible is it a planned feature?

**Comment by froggleston** [comment]
Yes, it's possible by using the custom callback functions, specifically, custom_exit and custom_stoploss: https://www.freqtrade.io/en/stable/strategy-callbacks/

**Comment by xmatthias** [comment]
> If not possible is it a planned feature?

it's not planned as part of the "configuration based" settings (`minimal_roi`, `stoploss`, `trailing_stop`).

whatever additional flexibility settings would provide, it'd most likely be always "slightly wrong" for whatever usecase you currently look at - which is why we have callbacks, giving you full flexibility as necessary.

you should consider / treat these as shorthands for what's possible through callbacks (the ones mentioned above).
