### ISSUE TITLE
Multiple Strategies on one pair in a single account

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#9434]
Hi all,

Is it possible to run multiple strategies in a single account? For example, I have 10 strategies for BTCUSDT and wish to run all of them in parallel. Let's say I have 10000USDT in my account, each strategy will only use 100 USDT as margin when opening a position. Will conflicts happen? My particular concern is that: when the first strategy open position of 0.1 BTC and the second strategy also open a position of 0.1 BTC, the total position value would become 0.2 BTC. When the first strategy hits exit condition would it reduce the position to 0.1 BTC or close the whole position?

**Comment by stash86** [comment]
Each bot will only sell what it bought. There is no issue there.

**Comment by xmatthias** [comment]
Since you're mentioning "margin" - it should be pointed out that for futures market - each bot assumes it's the only bot on this (sub-)account. We therefore recommend the use of subaccounts in such scenarios.

While it should work in theory - your liquidation levels may be off (as the calculation changes if the position is twice as big without the bot being aware of it), as well as the calculations of fees (funding fees in particular).

This info can also be found [in the futures docs](https://www.freqtrade.io/en/stable/leverage/).

Please note: 
on spot markets, this is NOT a problem, and the "available starting capital" for each bot can be configured via [assign available capital](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital).
