### ISSUE TITLE
stop trying to place a stoploss in a long if the price is below it.

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#9456]
## Describe your environment

  * Operating system: ubuntu 22.04
  * Python Version: 3.10
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.10

Sometimes 1-minute candles are larger than the trailing_stop_positive value, with the result that freqtrade tries to place a stoploss which is rejected by the exchange. This results in a lot of error messages and the stoploss considered by freqtrade is no longer consistent with the real price but is not updated because it is lower...
Is there any way to avoid this or to reset the stoploss?

I just saw this exemple now on ETH/USDT:USDT on Bybit where a candle have 1.35% offset and my trailing_stop_positive was at 1%
![Capture du 2023-11-21 19-08-25](https://github.com/freqtrade/freqtrade/assets/88237677/fdfce920-10fa-4fbe-a7e0-075dc70ff72c)

Thanks

**Comment by xmatthias** [comment]
if a stoploss is rejected by the exchange (due to price being lower) - then this should result in an emergency sell - which should default to a market sell - ensuring it's sold.

If that's not happening, then most likely the error-mapping in ccxt is wrong for that exchange  / error - or the error was a different one. 
Having logs for that would help for sure, without logs, there's nothing further to look at.

**Comment by macsim26** [comment]
Hi thanks for your answer.
The exchange is Bybit with a leverage of 10.
Here is a log of the error : 
[erreur.txt](https://github.com/freqtrade/freqtrade/files/13429854/erreur.txt)

**Comment by xmatthias** [comment]
well first off, your ccxt version is misaligned with the bot version - which makes it difficult to investigate further.
The Exception is not what we expect (anything around `InvalidOrderException` would trigger an emergency exit).

for 2023.10, you should have ccxt==4.1.22 - but you list 4.0.105 - which is over a month older than the expected version - which makes it quite likely that the issue has been solved since (it's unlikely nobody would've hit that on bybit so far).

When updating, please make sure to follow the [update guide ](https://www.freqtrade.io/en/stable/updating/) corresponding to your installation method to ensure dependencies are aligned.

---

Should it happen again with updated / corresponding dependencies, then let me know (with logs, obviously).
Otherwise, i'll assume it's been fixed with the alignment of dependenices.

**Comment by macsim26** [comment]
ok, but I had updated freqtrade with ./setup.sh --update ???? 
I've just updated ccxt manually and now I'm in version 4.1.22.
I'll try to put the stoploss back on the exchange and will see. 
Thanks

**Comment by xmatthias** [comment]
> ok, but I had updated freqtrade with ./setup.sh --update

that's interesting indeed - and suggests that the command may have failed somehow? (always check the output of the commands you run).

let me know how it goes with the new version :)

**Comment by xmatthias** [comment]
Please update to the latest develop (pushed just now, see above commit).
looking at the CCXt source, (https://github.com/ccxt/ccxt/blob/31d2d534b14853edce2aaa94b87949d9914322dd/ts/src/bybit.ts#L505, for those interested) - the error still maps to BadRequest.
There's however nothing wrong to handle BadRequest as "InvalidOrder" - as they essentially say the same thing in the context of a "place order" call.

**Comment by macsim26** [comment]
Ok thanks a lot!!!
Last question : is it safe to use the develop version in my bot in live or it's better for my case to wait for the 2023.11 stable update?

**Comment by xmatthias** [comment]
well "stable" is a monthly snapshot of develop. It's not "that" special, but something designed to give users some stability for some defined time.

we try to not include any "potentially problematic" features right before the release - but it's not THAT special, and right now, it's not very fluky, either.
