### ISSUE TITLE
Tried to merge a faster timeframe to a slower timeframe.This would create new rows, and can throw off your regular indicators.

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#9459]
I want my time frame to be 15m
But for my strategy, I also need 1m data

How can I access them?
I used informative, but it gives the error "Tried to merge a faster timeframe to a slower timeframe. This would create new rows, and can throw off your regular indicators".

please guide me

**Comment by stash86** [comment]
use 1m as the main timeframe, and 15m as the informative timeframe

**Comment by boyitnew** [comment]
> use 1m as the main timeframe, and 15m as the informative timeframe

What is the difference between the Timeframe in the strategy file and the Timeframe in the config file? Because I can’t change my Timeframe in the config file to less than 15.


In my config file, my Timeframe is set at 15m.

In the strategy file, I am working with a 5m Timeframe, but now I need 1m Timeframe data.

That’s why I used the informative, but it gives an error that “faster timeframe to a slower timeframe”. How can I avoid touching the Timeframe in the config file and use both 1-minute and 5m Timeframes in the strategy?

**Comment by xmatthias** [comment]
well the base assumption on a 15m timeframe is that there's a new candle every 15 minutes.

1m timeframe however would provide 15 rows for 1 15m candle - therefore would multiply the 15m rows. This can be problematic (in many aspects) - and we therefore don't provide helpers (nor support) for this.
This doesn't mean it's not possible (it's python code, so whatever you can come up with is possible) - but it's something we'd strongly discourage (also and not least because there's no reason to do this the wrong way around).

The **correct** approach is to invert your approach and use the 1m timeframe as your **main timeframe**.
you'll have the longerterm 15m candles as informative pairs - and the 1m timeframe as your base timeframe - giving you very detailed views.


---

Aside from that, you should be careful with your definitions of timeframe. 
there will be only one timeframe setting once everything is loaded / started- so if you've set it in the config, the strategy setting will be ignored (the prevalence here is cli argument > config > strategy - so config will always overwrite the strategy settings).

in general, i'd recommend to have the timeframe in the strategy - as it's usually strongly correlated with the performance of that strategy.

**Comment by boyitnew** [comment]
thanks
Well, this way you can get more diverse results.
I previously had excellent results with a 15m timeframe.
Now, I need to use lower timeframes like 5m and 1m for better results.
So, I removed the timeframe from the config file and transferred it to the strategy.
But now, the results are as follows:
`timeframe = ‘15m’`
with results:
`timeframe = ‘5m’`
`inf_tf = ‘15m’`
is different.
In the my strategy, I haven’t used timeframe = ‘5m’ anywhere, and I’m using inf_tf = ‘15m’ for everything.
For this reason, I need the main timeframe to be 15m, but I want to be able to retrieve some information from the 5m timeframe.

**Comment by froggleston** [comment]
You can't. Use the 5m main tf and 15m informative.

**Comment by xmatthias** [comment]
There's no reason to approach things the wrong way around.

The fastest/shortest timeframe has to be the "lowest" timeframe. Approaches for that are well documented.

**Comment by boyitnew** [comment]
thanks

My main timeframe is 15m, and I wanted to add a 30m timeframe as well by using informative.
So, I added the following code to the populate_indicators section:


```
inf_tf = '30m'
if self.dp:
    informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
    informative['trend_close_t3'] = ta.EMA(informative['close'], timeperiod=3)
    informative['trend_close_t6'] = ta.EMA(informative['close'], timeperiod=4)
    dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)
    return dataframe
```


Unfortunately, my candles are being returned empty, and I’m getting this error:
“WARNING - Empty candle (OHLCV) data for pair LTC/USDT”
