### ISSUE TITLE
TypeError: Strategy6short_mod.bot_loop_start() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#9464]
## Describe your environment

  * Operating system: Linux Mint Una
  * Python Version: 3.10.2
  * CCXT version: 4.1.52
  * Freqtrade Version: 2023.11-dev-736b583ff
  
## Your question

I get the above error when I run:
```
freqtrade plot-dataframe -s Strategy6short_mod

```
The last part of the logs look like this:

```
2023-11-24 19:52:45,575 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/plot/plotting.py", line 639, in load_and_plot_trades
    strategy.bot_loop_start(datetime.now(timezone.utc))
TypeError: Strategy6short_mod.bot_loop_start() takes 1 positional argument but 2 were given
```
The command worked when I plotted spot trading pairs. Is this something about futures trading?  I appreciate any help.

**Comment by xmatthias** [comment]
it's most likely an issue with your strategy missing the additional argument.

The signature should match `def bot_loop_start(self, current_time: datetime, **kwargs) -> None:` - and most likely, your's does not (otherwise it'd work).

I'll add some (default) error-handling around that so the error shows up slightly differently - but it's not changing the fact that the exchange implements the callback incorrectly.

The trade mode has nothing to do with this - but most likely, you were using a different strategy for spot pairs - which had this implemented correctly.

**Comment by moinonin** [comment]
You were right. Thanks
