### ISSUE TITLE
Question about MaxDrawdown Protection

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9545]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.8.10
  * CCXT version: 4.1.66
  * Freqtrade Version: 2023.11
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I have configured the following protective measures based on the tutorial from [here](https://www.freqtrade.io/en/stable/plugins/#full-example-of-protections):

My code:

```
    timeframe = "5m"

    @property
    def protections(self):
        return [
            {
                "method": "CooldownPeriod",
                "stop_duration_candles": 12
            },
            {
                "method": "MaxDrawdown",
                "lookback_period_candles": 288,
                "trade_limit": 10,
                "stop_duration_candles": 588,
                "max_allowed_drawdown": 0.1
            },
            {
                "method": "StoplossGuard",
                "lookback_period_candles": 288,
                "trade_limit": 10,
                "stop_duration_candles": 288,
                "only_per_pair": False,
                "required_profit": -0.02
            },
            {
                "method": "StoplossGuard",
                "lookback_period_candles": 288,
                "trade_limit": 1,
                "stop_duration_candles": 288,
                "only_per_pair": True,
                "required_profit": -0.04
            },
            {
                "method": "LowProfitPairs",
                "lookback_period_candles": 288,
                "trade_limit": 2,
                "stop_duration_candles": 288,
                "required_profit": -0.04
            }
        ]
```

In the case of `"method": "MaxDrawdown"`, my understanding is as follows:

**When within a period of 288 candles (24 hours), if the robot has made at least 10 trades and the maximum drawdown of the entire position exceeds 10%, the robot will freeze for 588 candles, during which no buying operations will be performed.**

However, during my virtual testing, I have encountered the following situation:

**When a trading pair is sold due to reaching the profit target ROI or when I manually force sell a profitable trading pair through Telegram, the robot also triggers the protective mechanism of freezing for 588 candles.**

Below is a screenshot of my trading activity on Telegram:

**Exit Reason: roi**

```
✳ Binance (dry): Exited RUNE/USDT (#208)
Profit: 3.07% (profit: 2.81793300 USDT / 2.818 USD)
Enter Tag: None
Exit Reason: roi
Direction: Long
Amount: 16.60000000
Open Rate: 5.53200000
Exit Rate: 5.71300000
Duration: 0:52:25 (52.4 min)

Protection triggered due to Cooldown period for 12 candles.. RUNE/USDT will be locked until 2023-12-13 14:30:00.

✳ Binance (dry): Exiting RUNE/USDT (#208)
Unrealized Profit: 3.03% (profit: 2.78476620 USDT / 2.785 USD)
Enter Tag: None
Exit Reason: roi
Direction: Long
Amount: 16.60000000
Open Rate: 5.53200000
Current Rate: 5.71100000
Exit Rate: 5.71100000
Duration: 0:52:25 (52.4 min)

Protection triggered due to 0.5477249175587007 passed 0.1 in 288 candles, locking for 588 candles.. All pairs will be locked until 2023-12-15 14:30:00.
```

**Exit Reason: force_exit**

```
Manually exiting Trade #209, UNFI/USDT

✳ Binance (dry): Exiting UNFI/USDT (#209)
Unrealized Profit: 1.90% (profit: 1.74089830 USDT / 1.741 USD)
Enter Tag: None
Exit Reason: force_exit
Direction: Long
Amount: 13.10000000
Open Rate: 6.98000000
Current Rate: 7.12700000
Exit Rate: 7.12700000
Duration: 1:04:46 (64.8 min)

✳ Binance (dry): Exited UNFI/USDT (#209)
Profit: 1.89% (profit: 1.72781140 USDT / 1.728 USD)
Enter Tag: None
Exit Reason: force_exit
Direction: Long
Amount: 13.10000000
Open Rate: 6.98000000
Exit Rate: 7.12600000
Duration: 1:04:46 (64.8 min)

Protection triggered due to Cooldown period for 12 candles.. UNFI/USDT will be locked until 2023-12-13 14:40:00.

Protection triggered due to 0.5477249175587007 passed -0.1 in 288 candles, locking for 588 candles.. All pairs will be locked until 2023-12-15 14:40:00.
```

I tested the two scenarios mentioned above with `"max_allowed_drawdown": 0.1` and `"max_allowed_drawdown": -0.1`, as I initially thought it needed to be set as a negative value.

**My question is:** 

Is this due to a bug, or did I make an error in my code configuration?

Please help me clarify this, thank you!

**Comment by xmatthias** [comment]
max-drawdown is a missleading filter unless you REALLY understand how it's meant to use - but from the information given - there's no way to derive if what you're seeing is correct or wrong (i assume is correct ...).
Logs would contain more information (please provide this) - but will still not contain the info about the previous trade states.

> Protection triggered due to 0.5477249175587007 passed

The message is slightly misleading (we could improve this i guess) - as drawdown is positive, while your configuration is negative. however, it implies a -0.54 drawdown.

It's therefore correct that it triggers.

> When within a period of 288 candles (24 hours), if the robot has made at least 10 trades and the maximum drawdown of the entire position exceeds 10%, the robot will freeze for 588 candles, during which no buying operations will be performed.

This is (slighltly) wrong - as it's not really "drawdown of entire position exceeds 10%" - but "combined drawdown of the last 10 positions/trades".
Now i **assume**  that's what you meant - but position is usually referring to one trade - not to multiple trades or similar.

---

**where the confusion comes from**

You see a winning trade and think "why would this trigger a max-drawdown protection".

Especially for this protection however, you can't really look at "this" trade, but must look at the sum of the last 10 trades.

If this winning trade (a win of 1.8%) is the 10th trade to close within the 288 candle window (it will have been, otherwise it wouldn't have triggered)  - and the previous 9 candles were 8 stoplosses for -10%, and another win of 2% - then this is (correctly) triggering the drawdown protection, as the overall drawdown for these 10 trades exceeds the set threshold.


You should see this in freqUI - where the dashboard will show you
* the last closed trades
* the last trades in a trade log (this is broken in one of the previous version - but can easily be replaced by the below)
* the cumulative profit - look at the change within last 1 day.
* the daily profit

All of the above will show you the state of the last 10 trades (eventually you'll by now have to go back slightly further) - but will give you the information if you start from the trade 209 backwards (sorted by close_date).

**Comment by WinPoss** [comment]
Today, the robot made 10 trades again, all of which were profitable. I have now executed the `/trades 15` and `/unlock` commands, and I have removed all the locked restrictions. Here are the results. I will observe until the next trigger of the protective mechanism. If I have any questions at that time, I will provide feedback on GitHub.

Freqtrade is an excellent algorithmic trading framework.

Good job!


```
/trades 15

15 recent trades:
Close Date    Pair (ID)         Profit (USDT)
------------  ----------------  ------------------
8 hours ago   DYDX/USDT (#218)  2.36% (2.204874)
8 hours ago   OP/USDT (#214)    3.54% (3.30544494)
8 hours ago   MEME/USDT (#213)  4.53% (4.2054388)
8 hours ago   DOGE/USDT (#205)  3.94% (3.62778343)
11 hours ago  IMX/USDT (#217)   3.06% (2.85875281)
11 hours ago  ARB/USDT (#216)   3.05% (2.85091458)
11 hours ago  JTO/USDT (#215)   5.00% (4.66941128)
14 hours ago  SOL/USDT (#211)   0.41% (0.3776679)
14 hours ago  XRP/USDT (#212)   0.72% (0.661078)
14 hours ago  LUNC/USDT (#207)  1.62% (1.49386774)
14 hours ago  PEPE/USDT (#206)  1.28% (1.17708352)
14 hours ago  TRX/USDT (#204)   0.27% (0.2440095)
14 hours ago  LTC/USDT (#203)   0.72% (0.66133252)
14 hours ago  SHIB/USDT (#202)  1.06% (0.97922948)
14 hours ago  LINK/USDT (#201)  1.49% (1.37076026)


/unlock
No active locks.
```

**Comment by xmatthias** [comment]
well that output seems to have happened after that trade `#209` closed.

As mentioned above - the critical part is what closed prior to that trade ... :)

**Comment by WinPoss** [comment]
> well that output seems to have happened after that trade `#209` closed.
> 
> As mentioned above - the critical part is what closed prior to that trade ... :)

Yes, it was the previous trades that caused the locking of all positions, and no new trading pairs were entered within the 588 candlesticks. I'm sorry for not replying in a timely manner, I've been busy these days.
