### ISSUE TITLE
Failed building wheel for TA-Lib

### ISSUE THREAD

**Issue by ashutoshmondal** [freqtrade/freqtrade#9554]
`Building wheel for TA-Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for TA-Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/talib
      copying talib/abstract.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/__init__.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/stream.py -> build/lib.linux-x86_64-cpython-39/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/talib
      gcc -pthread -B /root/anaconda3/envs/freqtrade/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/freqtrade/include -I/root/anaconda3/envs/freqtrade/include -fPIC -O2 -isystem /root/anaconda3/envs/freqtrade/include -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-build-env-zwgtbxfo/normal/lib/python3.9/site-packages/numpy/core/include -I/root/anaconda3/envs/freqtrade/include/python3.9 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-39/talib/_ta_lib.o
      talib/_ta_lib.c:1082:10: fatal error: ta-lib/ta_defs.h: No such file or directory
       1082 | #include "ta-lib/ta_defs.h"
            |          ^~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects`

**Comment by ashutoshmondal** [comment]
Found a solution to this : 


Build an anaconda environment with python3.9. 

Install Ta-Lib separately by running the following commands :  


1.1 Download
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

tar -xzf ta-lib-0.4.0-src.tar.gz

cd ta-lib/

1.2 Install TA-LIB
If the next command fails, then gcc is missing, install it by doing “apt-get install build-essential”)

sudo ./configure

sudo make

sudo make install

1.3 Install Ta-Lib (after activating the conda env of python3.9)

pip install ta-lib

//in case this encounters error : run  pip install ta-lib--break-system-packages

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

well following the [installation guide](https://www.freqtrade.io/en/latest/installation/#install-guide) - or more specifically the [talib section](https://www.freqtrade.io/en/stable/installation/#install-ta-lib) will tell you that you need to first install the ta-lib binaries, otherwise the wheel will fail (as well as other things if you somehow manage to get past the wheel step).

For freqtrade, we also recommend a small patch (see doc page) to ensure calculations remain correct on very small numbers (speak, cheap coins).

In the end, the solution you found does work, but the freqtrade test-suite will not pass due to the missing ta-lib patch.
