### ISSUE TITLE
ProfitDrawDownHyperOptLoss max_drawdown_abs out of bounds

### ISSUE THREAD

**Issue by serpent213** [freqtrade/freqtrade#9563]
## Describe your environment

  * Operating system: NixOS
  * Python Version: 3.11.5
  * CCXT version: 4.1.57
  * Freqtrade Version: 2023.11
  
## Describe the problem:

In *ProfitDrawDownHyperOptLoss* [`max_drawdown_abs`](https://github.com/freqtrade/freqtrade/blob/6404bd8b2b980dc6b7535ff5042cc85bcf85cc4b/freqtrade/optimize/hyperopt_loss/hyperopt_loss_profit_drawdown.py#L30) is expected to [be between 0 and 1](https://github.com/freqtrade/freqtrade/issues/8685#issuecomment-1561763877) but in one of my runs it reaches from around -760 to 1200, so HyperOpt runs in the wrong direction.

As a workaround I clamped it between 0 and 1. I'm not aware of doing something funny in my strategy.  🤷🏼‍♂️

### Steps to reproduce:

  1. `freqtrade hyperopt --strategy MassiveDropDCA --hyperopt-loss ProfitDrawDownHyperOptLoss -e 1000 --spaces buy stoploss trailing roi --timeframe 1m --config user_data/config_download.json --timerange 20231117-`
  
### Observed Results:

```
+--------+-----------+----------+--------------------------+--------------+-------------------------------+-----------------+-------------+-------------------------------+
|   Best |     Epoch |   Trades |    Win  Draw  Loss  Win% |   Avg profit |                        Profit |    Avg duration |   Objective |           Max Drawdown (Acct) |
|--------+-----------+----------+--------------------------+--------------+-------------------------------+-----------------+-------------+-------------------------------|
| * Best |    1/1000 |       87 |     78     8     1  89.7 |        1.41% |       304.468 USDT   (12.18%) | 0 days 00:23:00 |    -111.061 |        68.137 USDT    (2.72%) |
| * Best |    2/1000 |       60 |     55     5     0   100 |        1.17% |       176.130 USDT    (7.05%) | 0 days 00:06:00 |     -176.13 |                            -- |
| * Best |    4/1000 |      141 |     94    46     1  66.7 |        0.99% |       341.492 USDT   (13.66%) | 0 days 00:14:00 |    -340.238 |        17.584 USDT    (0.62%) |
| * Best |    7/1000 |      293 |    155   135     3  52.9 |        0.83% |       609.307 USDT   (24.37%) | 0 days 02:01:00 |    -607.369 |        26.985 USDT    (0.86%) |
| * Best |   17/1000 |      355 |    189   163     3  53.2 |        0.74% |       621.550 USDT   (24.86%) | 0 days 01:38:00 |    -616.154 |        81.365 USDT    (2.54%) |
/home/self/freqtrade/.venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. 
This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
| * Best |   19/1000 |      485 |    285   194     6  58.8 |        0.64% |       650.640 USDT   (26.03%) | 0 days 01:06:00 |    -640.404 |       172.712 USDT    (5.20%) |
| * Best |   21/1000 |      261 |    207    51     3  79.3 |        1.16% |       741.281 USDT   (29.65%) | 0 days 01:17:00 |    -735.546 |        85.261 USDT    (2.56%) |
|   Best |   31/1000 |      563 |    315   242     6  56.0 |        0.67% |       806.324 USDT   (32.25%) | 0 days 01:27:00 |    -795.839 |       169.134 USDT    (4.87%) |
|   Best |   71/1000 |      546 |    376   162     8  68.9 |        0.72% |       814.509 USDT   (32.58%) | 0 days 01:06:00 |    -803.918 |       170.828 USDT    (4.90%) |
|   Best |   75/1000 |      549 |    310   232     7  56.5 |        0.80% |       919.376 USDT   (36.78%) | 0 days 01:22:00 |    -905.541 |       230.768 USDT    (6.32%) |
|   Best |  116/1000 |      733 |    508   220     5  69.3 |        0.64% |      1098.267 USDT   (43.93%) | 0 days 01:14:00 | -1,084.34439 |       223.389 USDT    (5.85%) |
|   Best |  126/1000 |     2847 |   1361   121  1365  47.8 |       -0.20% |     -1421.269 USDT  (-56.85%) | 0 days 00:09:00 | -9,142.00453 |      1437.851 USDT   (57.18%) |
|   Best |  151/1000 |     3258 |   1681   961   616  51.6 |       -0.20% |     -1619.559 USDT  (-64.78%) | 0 days 00:38:00 | -26,021.22828 |      1626.708 USDT   (64.88%) |
|   Best |  182/1000 |     3000 |   1349   966   685  45.0 |       -0.20% |     -1481.408 USDT  (-59.26%) | 0 days 00:28:00 | -59,043.85691 |      1484.132 USDT   (59.30%) |
|   Best |  331/1000 |     2499 |   1173   958   368  46.9 |       -0.18% |     -1131.414 USDT  (-45.26%) | 0 days 00:59:00 | -1,033,390.21205 |      1131.507 USDT   (45.26%) |
```

  * What did you expect to happen?

Optimisation towards lower drawdowns.

Any idea about that in-between warning?

**Comment by stash86** [comment]
No, max_drawdown_abs is never expected to be between 0 and 1. The name already says it, it's the absolute value.

**Comment by stash86** [comment]
The name of the variable is misleading, because what you get at [5] is `max_drawdown_rel`. Whether `max_drawdown_rel` varies between 0 to 1, I'm not sure. You know that you can just do manual calculation and work back from the objective values and see the values of `max_drawdown_rel`?

**Comment by serpent213** [comment]
In *ProfitDrawDownHyperOptLoss* it apparently is expected to fall between 0 and 1, please see the two links.

Could you elaborate on your last question?

**Comment by stash86** [comment]
Yes, the formula might expect it, but do it really only range between 0 to 1? You can easily debug it by printing the value

**Comment by xmatthias** [comment]
Is your strategy using leverage?

independent of that - the problem here seems to be that the strategy ends at it's absolute low point (at the end of the timerange).
I can see that because the total_profit and the max_drawdown is (near) identical.


the formula used ...
`-1 * (total_profit * (1 - max_drawdown_abs * DRAWDOWN_MULT))`

Using the below values (these are NOT necessarily the values used for the calculation above) in the formula above already yields a very high negative objective.

```
DRAWDOWN_MULT = 0.075
total_profit = -1131.414
max_drawdown_abs =  1131.414
```

The "actual" value used for this particular objective is not immediately visible, as it'd require the total high point of the epoch (backtest session), as well as the cumulative sum up to that point.

playing with the values above you can already see that a higher drawdown (increase max_drawdown_abs) will also increase the value (though into the negative range).

The way the calculation is set for this loss function - there's no starting balance - hence we don't have an actual "account drawdown" to tear from - but instead will have to fall back to the cumulative gains up to the account high point - and use that as "relative drawdown anchor".

---

I don't immediately see why you think it's out of bounds - as i don't think it is (at least not with the details given).
You might be able to get a bit more details with `freqtrade hyperopt-show -n <epochnumber>` - which will probably give you the actual drawdown / account max number (most in this comment are assumptions based on the details provided).


it's an edge-case, sure (your strategy is losing straight, it seems - or never really reaches anything much above 0) - but as the documentation says - loss function experience may vary - and the "best" loss function doesn't really exist.


The only thing one can argue is that the function is in general not well balanced / behaves oddly depending on the sign of total_profit - where positive profits create positive numbers, while negative profit causes negative numbers - which then obviously means that the negative number will be prefered - as it's lower than the positive number.

**Comment by xmatthias** [comment]
Closing this as we got no further feedback.
