### ISSUE TITLE
Converting Unfulfilled Limit Orders to Market Orders After a Set Time

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#9586]
## Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: 3.10.13 (`python -V`)
  * CCXT version: 4.1.31 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.11-dev-8c2920eb1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

Can I change a limit order to a market order if it hasn't been executed after a certain period? I specifically want the limit order to switch to a market order if it's not filled within 5 minutes. The idea is to automatically cancel the limit order and place a market one if the limit order has not been filled.
Currently, I'm using unfilledtimeout.exit_timeout_count = 1 like this : 
```
"unfilledtimeout": {
        "entry": 10,
        "exit": 5,
        "unit": "minutes",
        "exit_timeout_count": 1
    }
```
 to force an emergency exit for unfilled limit orders, but this method isn't consistently effective. Sometimes it works, but often it doesn't. I suppose that when it fails it's because the exit condition is not valid anymore after the timeout. 

Looking for any advice to achieve this.

Thanks.

**Comment by popperwin** [comment]
Just had an idea to do it, but I'm not sure it will works as expected. My main concern is to be sure that once a custom_exit is triggered,  it would not be executed every `internals.process_throttle_secs`  ; but would be executed again only after unfilledtimeout.exit .

The idea is to have a cache and keep the number of attempt of exit for a specific trade. If the trade have already been attempted for exit, then we choose a very low custom_exit_price = proposed_rate*0.98 , in order to "force" the exit.

Here is the pseudo code:
```
class Strat(IStrategy):
    
    order_types = {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": True,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    }
   
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.exit_cache_count = defaultdict(int) #Dict with pair as key and value the number of exit attempt 
        
    
    def custom_exit_price(self, pair: str, trade: Trade,
                          current_time: datetime, proposed_rate: float,
                          current_profit: float, **kwargs) -> float:
    	
    	if self.exit_cache_count[trade.id] > 1:
        	return proposed_rate*0.98 #Pseudo market sell if limit sell have failed one time
    
    
    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        
        if exit_condition or self.exit_cache_count[trade.id] > 0:
        	self.exit_cache_count[trade.id] +=1

        	return f"exit_condition_{self.exit_cache_count}"
        
```

**Comment by xmatthias** [comment]
i think your main misconception is the difference between a market and limit order.

A market order can be pretty reliably emulated with limit orders by simply placing the order with a price "way" across the spread (say 1-2%).
Unless you use some non-default time_in_force, the exchange will auto-convert the order to a marketable limit order, and execute it at the best price available (just as a market order would).

The only thing the price defines in that case is the WORST price you're willing to accept (1-2% slippage) - which is out of your control on market orders, and on thin markets, can also exceed 5% or more (i've seen / had these in the past, they're not fun).

---

You're making your own life more difficult by using unnecessary state (which will be gone once the bot is restarted) - instead of simply looking at what's available (all canceled exit orders will be part of `trade.orders`).

As such - assuming the exit-signal is still there when the timeout expires - simply add some logic to [custom_exit_price](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-order-price-rules) - which does "whatever" depending on the count of `trade.get_canceled_exit_order_count()` (a helper method counting canceled exit methods).

**Comment by popperwin** [comment]
Thanks for your reply, I wasn't aware of the helper method `get_canceled_exit_order_count` . May be the documentation should add all the property and methods avalable ? It would be really great.

Also thanks for your explanation, what you explained was pretty clear in my mind , may be I didn't used the right words but yes I know that placing a limit order at 2% of the current price will result to a market order with the limit of 2% of slippage. That's why I had the idea to use `proposed_rate*0.98` for have a "pseudo" market order, which is doing what I need.

Thanks for your help again!
