### ISSUE TITLE
Pandas Alert: fillna ‘method’ No Longer Supported After Version 2.1.0

### ISSUE THREAD

**Issue by ASGDLO** [freqtrade/freqtrade#9610]
Traders and developers using freqtrade, take note of a significant update in the pandas library that may affect your trading strategies and data analysis! As of version 2.1.0, the 'method' parameter in the fillna function is deprecated. This is crucial for those who rely on pandas for data cleaning and preparation in freqtrade.

this is blog : https://medium.com/@hoon33710/pandas-alert-fillna-method-no-longer-supported-after-version-2-1-0-9b32c742e893

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I'm not sure how you think this impacts freqtrade directly (it obviously can through strategies).

All our code removed the usage of this weeks ago, so if you're still encountering this from freqtrade's internal methods, you're most likely on an older version.

The fix is pretty much the replacement of `dataframe = dataframe.fillna(method='ffill')` with `dataframe = dataframe.ffill()`.
