### ISSUE TITLE
freqtrade installs a common file tests/__init__.py that can conflict with other packages

### ISSUE THREAD

**Issue by yurivict** [freqtrade/freqtrade#9612]
We have this conflict:
```
Installing freqtrade-2023.11...
pkg-static: freqtrade-2023.11 conflicts with py39-technical-1.4.1 (installs files into the same place).  Problematic file: /usr/local/lib/python3.9/site-packages/tests/__init__.py
```

No package should install the ```tests``` directory. Both technical and freqtrade should be corrected.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Accidentally, this has been fixed in the last freqtrade release (2023.12) - which was released just today.
let me know if you encounter something similar with the 2023.12 release. 

Your technical version is also outdated. best Report it there if you still encounter this in that version - or better yet - submit a fix.

from a freqtrade perspective - i'll assume this as fixed.

**edit** for technical, tests are no longer included in the wheel as of this afternoon - and will therefore no longer be included in the next release.
