### ISSUE TITLE
Freqai cannot be cleanly stopped (happens on ctrl + c once)

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#9625]
@robcaulk this might be one for u :) this thing keeps happening on every reboot for a random producer, the others reboot fine. Have to delete the broken models in ft_userdata/user_data/models which kind of sucks since it takes another week to properly continue with those higher timeframes.

This issue is not a one time thing, it was an issue since freqai rebooted for the 1st time.

## Describe your environment

  * Operating system: Ubuntu 22.04.3 LTS
  * Python Version: Docker stable-version (2023.11)
  * CCXT version: Docker stable-version (2023.11)
  * Freqtrade Version: Docker stable-version (2023.11)
 

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:
  1. Start freqai with tmux, docker compose up 
  2. Let it run
  3. docker compose down or ctrl+c to gently have freqtrade itself shut down
  4. one of 6 instances usually have broken models (it s the same freqai strategy  model, just different timeframes and exchanges)
  
### Observed Results:
  * Solution will be to delete the model that is broken (which is not clearly stated, so I just usually delete all models ...) 

  What did you expect to happen?
  * I would like to be able to reboot containers properly once a month without one blowing up the calculated models

### Relevant code exceptions or logs

[freqtrade2producer.log](https://github.com/freqtrade/freqtrade/files/13804645/freqtrade2producer.log)

**Comment by robcaulk** [comment]
Hey,

I don't see anything to do with FreqAI models here in the provided logs (but please correct me if I missed an important part of the log). I did find the following errors:

```
2024-01-01 12:53:07,055 - freqtrade.rpc.fiat_convert - ERROR - Could not load FIAT Cryptocurrency map for the following problem: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
```

```
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
```

```
2024-01-01 12:46:53,221 - freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "SOL/USDT:USDT", timeframe: 30m.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 269, in _download_pair_history
    data_handler.ohlcv_store(pair, timeframe, data=data, candle_type=candle_type)
  File "/freqtrade/freqtrade/data/history/hdf5datahandler.py", line 37, in ohlcv_store
    _data.loc[:, self._columns].to_hdf(
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 2779, in to_hdf
    pytables.to_hdf(
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 307, in to_hdf
    with HDFStore(
         ^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 584, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 744, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/tables/file.py", line 294, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/tables/file.py", line 744, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 515, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 836, in H5Fopen
    unable to synchronously open file
  File "H5F.c", line 796, in H5F__open_api_common
    unable to open file
  File "H5VLcallback.c", line 3863, in H5VL_file_open
    open failed
  File "H5VLcallback.c", line 3675, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 128, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 1911, in H5F_open
    unable to lock the file
  File "H5FD.c", line 2412, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD__sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace
```

Which suggest to me some issues with downloading data due to rate-limits, and also a sqlite DB connection issue.

Let me know if I missed some part of the log!!

Cheers,

Robert

**Comment by hippocritical** [comment]
After deleting the models it works again without issue
And there is only one producer per exchange per IP and the consumers start respectively 120s and 240s later by that time the download of the main bot is already long done with only 30 ish pairs.
The issues only happen when restarting bots, never at the first boot.
Those rate limits happen when the bot tries + fails over and over to my understanding, that causes these issues - not the bootup of the bot itself, but continuous restarting of the bot over and over.

Or am I wrong?
Not really as into freqai as you are

You didnt miss any part of the logs, this literally was from gently shutting down the docker compose containers with a single ctl+c then deleting the previous logs, then a restart via docker compose up until the end of the logs. 

The sqlite files are not an issue, the models are that were generated via freqai ... once those files are deleted everything worked fine again - and that s only 1 of 6 instances over 3 different VPSes (2 producers per IP, 2 different exchanges per IP and the consumers start at 120s and 240s for consumer1 and consumer2 respectively) so there shouldnt be any issues at all with rate limits from a load perspective

**Comment by xmatthias** [comment]
```
2024-01-01 12:46:53,221 - freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "SOL/USDT:USDT", timeframe: 30m.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 269, in _download_pair_history
    data_handler.ohlcv_store(pair, timeframe, data=data, candle_type=candle_type)
  File "/freqtrade/freqtrade/data/history/hdf5datahandler.py", line 37, in ohlcv_store
    _data.loc[:, self._columns].to_hdf(
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 2779, in to_hdf
    pytables.to_hdf(
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 307, in to_hdf
    with HDFStore(
         ^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 584, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 744, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/tables/file.py", line 294, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/tables/file.py", line 744, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 515, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 836, in H5Fopen
    unable to synchronously open file
  File "H5F.c", line 796, in H5F__open_api_common
    unable to open file
  File "H5VLcallback.c", line 3863, in H5VL_file_open
    open failed
  File "H5VLcallback.c", line 3675, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 128, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 1911, in H5F_open
    unable to lock the file
  File "H5FD.c", line 2412, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD__sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace
Unable to open/create file '/freqtrade/user_data/data/bybit/futures/ETH_USDT_USDT-1h-futures.h5'
```

I think this error was missinterpreted above.
this has nothing to do with ratelimits - but is a file system error, where the bot fails to create the file.

The error is repeated several times - and since this appears to be a bot run through docker, it's slightly more difficult to actually interpret the error - however it can only be a limited number of options

* File system is full
* the system is overloaded as a whole - causing the file system driver to get no resources
* The filesystem permissions are wrong (unlikely that it would affect only a few files, but not impossible)
* the system provider has some problem with it's filesystem
* Resource contention - with 2 bots trying to write the same file at the same time


combining this error with all the other errors in the file (including the coingecko ratelimit errors, and knowledge that it's running multiple freqAI bots) - i'd bet on the "system is overloaded" part.

Now independent of the cause - the logs show the problem when downloading data (these files will simply not be stored, and the data will not be available for freqAI).
Now knowing that freqAI also _stores_ models - it's pretty safe to assume that the same exact error can (and will) also happen when storing models - leading to either missing or corrupted models (depending on the exact error at that moment).

---

Please keep in mind - freqAI can consume quite some resources as it's spawning several processes (depending on config and models used) - so it's not necessarily a "light" approach - but rather one that can max out a system / CPU quite easily.

From the logs - i agree with Rob though - there's nothing suggesting a problem with freqAI itself - everything i've seen points to a problem with the system. 
if that's now a plainly overloaded system, a VPS with bad neighbors maxing out all available IOPS, or a provider with a bad storage unit is beyond what freqtrae logs can provide.

**Comment by hippocritical** [comment]
freqtrade itself worked perfectly and produced signals upon the very moment the container had to be restarted, I dont believe it would be a VPS issue since it was not maxed out in any way

**Comment by xmatthias** [comment]
well the log contains 3 types of errors as far as i can see, none of which is directly related to freqAI (other than freqAI causing tons of load eventually).

* rate limit errors from fiat-convert (which are irrelevant unless your problem is that fiat display doesn't work).
* sqlalchemy queue pool errors (which are not related to freqAI - but have something to do with the UI, i'd assume)
* hdf5 errors (see above)

The fiat errors are clearly irrelevant.

The hdf5 errors are not - and **are** a problem with file access. These are clearly a problem, and the pairs it appeared on will not have been saved - so either the subsequent data is old, missing completely, or errors happen on next read (unlikely).

sqlalchemy errors _might_ be caused by problems with disk-access as well - as they suggest that the database is responding very slowly, which bumps up the pool size (as sessions can't be reused until they complete their current query).

The combined log therefore suggest a problem with the disk of the VPS.

---

If you have other logs, which don't show these errors - but have similar behavior, then it might be something we can look at.
However the way the logs look like, it's several restarts - which are caused by disk-related issues (the hdf5 ones are for sure, the sqlalchemy ones most likely).

**Comment by hippocritical** [comment]
I have a suggestion then ...
If this issue happens again, the models will be saved completely and routed to you (not on github since they are kind of big).

I make sure that the logs previous to the error are complete and after
And that the containers were allowed to ctrl + c gracefully ( no accidental double tapping )

this seems to happen every now and then  and is not reproducible but will happen again (Hopefully not but hey ...)

The CPU goes round and cound with freqai but the single pair is done in about 10-15s and there are only 26~ pairs and the timeframe is either 15m, 30m or 1h so the calculations for the models are not possible to clog up the whole pipeline. They have ample time to calculate (At least to my understanding, this cant be the issue)

Will close this issue now, if it happens again we can then pick up from here again. Deal? :)

**Comment by xmatthias** [comment]
> The CPU goes round and cound with freqai but the single pair is done in about 10-15s and there are only 26~ pairs and the timeframe is either 15m, 30m or 1h so the calculations for the models are not possible to clog up the whole pipeline.

That's not what i'm suggesting - the error points to a disk based failure - which COULD be caused by high CPU - but since we're talking VPS - could just as well be caused by a "bad neighbor" symptom - where someone on a VPS next to you (on the same physical host) consumes all resources (either CPU, or IO).

> Will close this issue now, if it happens again we can then pick up from here again. Deal? :)

sure, works fine for me :)
i'm also not saying there couldn't be a different issue - but we need to work from logs - which don't contain any freqAI based errors, only errors pointing to "potential problem with disk" ...

**Comment by hippocritical** [comment]
> That's not what i'm suggesting - the error points to a disk based failure - which COULD be caused by high CPU - but since we're talking VPS - could just as well be caused by a "bad neighbor" symptom - where someone on a VPS next to you (on the same physical host) consumes all resources (either CPU, or IO).

this might be yes, but I doubt ... it can on demand hit 100MB/s from disk and the CPU isnt shared since it s ARM which cannot be shared due to architecture (unlike x86)

The funny part is just that the 30m strategy failed while the issue points to data corruption or CPU usage as you stated - but a model can be done in TOPS 20s (usual 10s) and there s only less than 30 (26~) pairs meaning by doing a rough worst-case estimation then it would be 30*20 = 600s which is far below the 30minutes mark
And on the same machine with the same configuration (timeframe) but another exchange the other instance is just fine - which is weird.
