### ISSUE TITLE
Dependency conflict due to pydantic 1.x vs. 2.x conflict

### ISSUE THREAD

**Issue by yurivict** [freqtrade/freqtrade#9627]
## Describe your environment

  * Operating system: FreeBSD 14.0
  * Python Version: 3.9
  * Freqtrade Version: 2023.12
  

## Describe the problem:

You require pydantic>=2.2.0, but your other dependency fastapi requires pydantic-1.x and not 2.x.

2 versions of the same package can't exist simultaneously in the same environment.

It shouldn't be possible to install FreqTrade if version requirements of all dependencies are checked pedantically.

How are you able to install FreqTrade?

### Steps to reproduce:

regular install using PEP517 compiant tools.
  
### Observed Results:

version conflict related to pydantic.

**Comment by stash86** [comment]
Fastapi now support pydantic v2
https://github.com/tiangolo/fastapi/discussions/9709

Maybe that version hasn't been released for FreeBSD? You will need to ask the Fastapi team instead for that

**Comment by xmatthias** [comment]
Considering your numerous issues with installation on freeBSD, i can only recommend to switch to a supported system (for example ubuntu or debian) - and use regular / documented installation methods.

While we don't resetrict freqtrade from being used on exotic systems like freeBSD, we also don't provide support for such systems.
The assumption is therefore that people are able to investigate issues for themselfs.

Freqtrade installation works fine since years, using either a regular `pip install` (which is also what our `setup.sh` script uses) with freqtrade works fine on all systems we test against (linux, macos, windows) - hence this is clearly yet another freeBSD issue.
You can also use docker - which i assume should be available on freeBSD, and will get you started easily.

> regular install using PEP517 compiant tools.

I assume that the latest pip will be a PEP517 compliant tool - where our CI confirms (on multiple different systems) that installation works fine.

---

We'd like our users to enjoy using freqtrade - not waste their time with installation issues (on unsupported, apparently badly maintained systems).

Therefore please use a supported system (i'd recommend ubuntu for beginner users - as it's rather user friendly).

**Comment by yurivict** [comment]
@xmatthias 

I created 3 issues:

1. The use of sdnotify on systems where systemd isn't used: this is a real bug in the Python infrastructure that sdnotify is called anyway and it sometimes does nothing. I wouldn't allow such thing in software that I write. This practice is confusing and causes redundant code.
2. The ```tests``` directory was installed: this was a real bug in freqtrade that was later fixed.
3. Pydantic 1.x vs. 2.x problem - which isn't currently a problem for freqtrade - is also a real problem in the Python infrustructure. A number of packages (not freqtrade) insist on using Pydantic 1.x and such packages conflict with Pydantic 2.x.

None of these problems are FreeBSD-specific. They were only exposed on FreeBSD due to the pedantic nature of the FreeBSD porting/packaging system.

> [...] on unsupported, apparently badly maintained systems [...]

This is a baseless conclusion. FreeBSD has the industry-best packaging system and is an extremely well designed and clean system.

Please do not cast judgements about matters which you don't know about.

----------------------------

```freqtrade``` is now ported to FreeBSD without any known problems.

**Comment by xmatthias** [comment]
> The use of sdnotify on systems where systemd isn't used: this is a real bug in the Python infrastructure that sdnotify is called anyway and it sometimes does nothing. I wouldn't allow such thing in software that I write. This practice is confusing and causes redundant code.

you've been invited twice to submit a pull request fixing this if it bothers you.
By not doing that, my conclusion is that it's simply a "i want others to waste their time" request - otherwise YOU would invest YOUR time to fix something that bothers you (that's how open source works, after all).

For the freqtrade userbase, this is a none-issue, so the only one bothered by this is you. I'm happy to **review your** Pull request - but i don't intend to spend my time on it.

> This is a baseless conclusion. FreeBSD has the industry-best packaging system and is an extremely well designed and clean system.
> Please do not cast judgements about matters which you don't know about.

Glad to hear FreeBSD has a good packaging system. 

My interactions with freeBSD have been mainly through you, which were mainly negative so far, so apparently it's just you who lacks understanding of such.

As such please do _your own_ investigations instead of wasting other project's time.

* opening pointless issues without doing investigation beforehand (see this issue).
* having identical issues opened again by the same user, with the same conclusion (see sd_notify duplicate issue)
* Having us investigate failures in **YOUR CI** (see https://github.com/freqtrade/technical/issues/390)

Have a good day.

**Comment by yurivict** [comment]
@xmatthias 

There are no pointless issues that I opened. Each one was for some reason. This one is because Pydantic has a legit problem with conflicts between versions, which happens to be already resolved.

You are just one toxic individual with zero social skills and an abundance of false confidence.

-1 to FreqTrade for having to talk to you here.

**Comment by stash86** [comment]
If you have issues on non-freqtrade repo (no matter how important you think it is), please ask the question in the respective repo. We are not here to be your personal problem solver. Thanks.
