### ISSUE TITLE
Enable 1s for timeframe-detail in backtesting and hyperopt

### ISSUE THREAD

**Issue by engzizo79** [freqtrade/freqtrade#9635]
I have noticed that backtesting produced much more realistic results when using a timeframe-detail of 1m in a strategy with a 5m timeframe. As binance has 1s data available and I have 96GB of RAM, I wanted to try a 1m strategy with 1s timeframe-detail data. This is however currently unsupported.
I don't think it would be hard to add this support. I know it's a lot of data but it might make a huge difference to get realistic results, even a resampling to 5 or 15s would do much.

**Comment by stash86** [comment]
We are open for someone to add 1s timeframe to freqtrade. Personally, we won't pursue it for 2 simple reasons
1. Amount of memory needed
2. Amount of storage needed to store the historical data. Since you are using 1m timeframe, just multiply the sizes of the 1m data by 60. That's only for 1 pair. See how big the storage you need

Just want to add, 96GB is nothing in the world of backtest/hyperopt. I once had 128GB ram VPS and I managed to use all the memory on 5m timeframe. To have a good hyperopt (no overfitting), it's advisable to use a wide timerange. In such scenario, 96GB isn't enough imo.

**Comment by froggleston** [comment]
`I don't think it would be hard to add this support.` - Freqtrade is open source. By all means try to add in such support if it's not that hard and see what results you get.

**Comment by xmatthias** [comment]
Doing a very rudamentary backtest (single pair, single trade for the full timerange of 15 days) with 1h main timeframe (this is actually irrelevant), and different detail timerames, i don't think it'll make sense.



```
5m:
real    0m11.094s
user    0m5.712s
sys     0m1.231s

1m:
real    0m12.637s
user    0m8.055s
sys     0m1.425s

1s:
real    3m41.322s
user    3m36.187s
sys     0m1.544s
```

the slowdown is 60x over a 1m backtest - applicable to every candle with either a signal, or while a trade is open.
That makes it next to unusable - so i don't think it'll make sense to introduce this (Memory is important - but it's not the only problem when dealing with this topic).


I'm not aware of any exchange supporting other "sub-minute" timeframes (binance seems to be the only one that even supports 1s as far as i could find) - and there's no plans on supporting emulated timeframes.

unless you have some very compelling argumens why you think this would be worth it, i don't think we'll be adding support for this - not least because of the insane amounts of data necessary (see screenshot below) - but mainly because of the very questionable and doubtful "improvements" you'd be expecting.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/d53e6d01-850e-48ef-85cf-e6b640191cdf)
