### ISSUE TITLE
custom tags for position adjustment trades?

### ISSUE THREAD

**Issue by abdozoon** [freqtrade/freqtrade#9642]
## Describe your environment
(if applicable)

  * Operating system: Docker
  * Python Version: Docker
  * CCXT version: using latest Docker image
  * Freqtrade Version: latest one

## Describe the enhancement

My suggestion is that, similar to what's done with entry/exit signals, I would like to have each trade from a trade's filled entries to have its own tag.

So, if I have multiple conditions within the adjust_trade_position, each condition met needs to have its own tag, so that we know which condition was met, and also it will help create more conditions in the same function or in other functions to act on previous filled_entries that have specific tags.
So, one condition might have this tag adjust_tag: "RSI_low", another has adjust_tag: "BB_mid", etc.
Same idea for filled exits.

Also, if I force adjust position manually in FreqUI for example, I need this filled entry to have its own tag, like adjust_tag: "force_entry".

I asked if it's already possible in the Discord channel but got an answer of NO, that's why I'm submitting feature request.

Thank you for reading.

**Comment by xmatthias** [comment]
This is not possible - and i don't think we'll be adding this, either, so for now, i'll treat this as question (convince me otherwise ...).

First off - tags are stored at the trade level (not at the order level) - so you can only have one entry tag, and one exit tag.
While this could be changed - i don't see how this would scale from a representation perspective.

We could store it at the order level - but what should a call to `/status` show? 
* the initial entry tag? 
* the last partial order tag? 
* . . . 

Same for the UI ... 

While a `/orders` call might show these - i don't think that call is used frequently.

As such - it would be information that's obscure / hidden - and only really available within the strategy.
while breaking everyone's strategy - as suddenly, the callback is expected to be a tuple, no longer a simple number (or None).

**Comment by abdozoon** [comment]
Thank you so much for your feedback.

I'm not a dev, but if you think about implementing this in the future, would it be as simple as if you check if the return is a simple number, then process it normally, but if it's a tuple, then apply the new way?

For the reporting, maybe it's more helpful in FreqUI when examining filled entries/exits of a specific trade and look at their custom tag?
(BTW, the coloring of the Buy / Sell strings in the snapshots is how I wish it would look like as well for my old eyes, but you can disregard this, indeed)

Example1:
![image](https://github.com/freqtrade/freqtrade/assets/25867871/992f869f-f81c-4ac3-a2cb-3496e62e8fc0)

Example2:
![image](https://github.com/freqtrade/freqtrade/assets/25867871/9e89b21b-50ee-4c48-a577-141f58aafd50)

Regarding /status, I think it should return the initial tag.

**Comment by xmatthias** [comment]
> (BTW, the coloring of the Buy / Sell strings in the snapshots is how I wish it would look like as well for my old eyes, but you can disregard this, indeed)

i really don't see why a sell should be red, while a buy is green.
that's a very confusing color-scheme - using colors used for profit / loss - while in reality, it's simply an order (the order on it's own is neither profit nor loss).

If you have other, neutral color ideas, i'm not against it per se - but red / green suggests something this view is not.

**Comment by abdozoon** [comment]
yes, you can use colors derived from the entry / exits markers from the chart depending on the FreqUI light/dark theme, or any neutral colors from your choice ;)

like this:
![image](https://github.com/freqtrade/freqtrade/assets/25867871/28c81189-d8c8-4176-b896-2ccaf7419873)

or this, you may use any unicode symbol of your choice, indeed :)
![image](https://github.com/freqtrade/freqtrade/assets/25867871/faa00b5a-a288-413b-b222-8d6c59d887bb)

Many thanks again for your continuous efforts on the development of the bot. ♥
