### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known'))

### ISSUE THREAD

**Issue by le8888e** [freqtrade/freqtrade#9672]
## Describe your environment

  * Operating system: _Linux_
  * Python Version: __3.9.16___ 
  * CCXT version: __4.0.71___ 
  * Freqtrade Version: __2023.8__ 
## Your question

Hi, my bot was running regularly then crushed:

  ```
File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /sapi/v1/capital/config/getall?timestamp=1704620902924&recvWindow=10000&signature=2ccb768753cee749cf6436dc878aee4eb552cc5b5ea012fe4053a3f9f27beab4 (Causedby NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b67caddf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/freqtrade_test/freqtrade/exchange/exchange.py", line 497, in reload_markets
    self._markets = self._api.load_markets(reload=True, params={})
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/base/exchange.py", line 1433, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/binance.py", line 1783, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/binance.py", line 7493, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ec2-user/freqtrade_test/.venv/lib64/python3.9/site-packages/ccxt/base/exchange.py", line 627, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance G
```

I was using Freqtrade 2023.3 and never met this problem. Could you please tell me what caused this and what is the possible solution? Thank you.

**Comment by xmatthias** [comment]
well the error points to a generic network error ... more specifically, most likely to a dns resolution error.

That's however not something that freqtrade can (or will) influence, but is usually a generic problem of the host / network you're on.
It might be a temporary problem - but it's not a version problem - at least i wouldn't know how that's possible.

**Comment by stash86** [comment]
In which country is this computer located?

**Comment by xmatthias** [comment]
Well your version is half a year old (2023.8) ... so it's also possible that it's simply an incompatibility in an endpoint that's not often queried (unlikely, but possible).
exchange endpoints change - and so do (sometimes) actual endpoints - as well as error handling (both in freqtrade, as well as in ccxt).


---

Country restrictions might be an issue - though it's unlikely (considering it's a dns resolving issue), as that'd prevent an initial startup with the assumption that your IP doesn't change - and the exchange won't add random, temporary restrictions for countries.

Please double/tripple check your network configuration (specifically the DNS resolving topics - but also from an overall perspective, including potentially involed proxies or VPN's).



Due to resource constraints, we're however unable to provide support for old versions, thanks for your understanding.

to get further help: please also update to the latest version (2023.12 at the point of writing) - following the [update](https://www.freqtrade.io/en/stable/updating/) procedure for your current installation method (or do a fresh install ...).


For now, i'll close this with the assumption that the update will fix this.
If it doesn't - please provide us with logs (logs including AT LEAST 10 lines before and after the actual problem) of the updated bot below - so we can reopen and try and assist getting your network in order (it's not something freqtrade will or can actively assist you with).

**Comment by le8888e** [comment]
> In which country is this computer located?

I am using an AWS EC2 server and it's in Hong Kong region.
