### ISSUE TITLE
calculating indicator on live tick price untill the candle closes

### ISSUE THREAD

**Issue by keerthankumar** [freqtrade/freqtrade#9682]
## Describe your environment

Operating system: Ubuntu 22.04.2 LTS
Python Version: Python3
CCXT version: 4.1.22
Freqtrade Version: freqtrade 2023.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

#9380 extension from this - 

Is there anyway to use the tickdata on indicator calculation before the candle closes?

say moving avg calculated till bar-10, now bar 11 is forming but untill the current bar is closed moving average indicator wont be able to reflect on that data. is there anyway the moving average will continously use the bar11 tick data untill its closed? Just like MT5 or Amibroker.

this helps in live trading, to avoid the wide spread or price movement.

**Comment by froggleston** [comment]
No. Indicators are calculated on candle close in the main dataframe, because most (all?) indicator libraries need complete candles for calculation.

(MT5 etc "repaint" candles, which means they give you a fake representation of an incomplete "candle" - there is no such thing as an incomplete candle, only open rate and current rate). You can use ticker price and orderbook data and set process_only_new_candles to False, but be aware this won't change the fact that you'll have the same OHLCV data within a candle).

**Comment by keerthankumar** [comment]
@froggleston Thank you for commenting. 

Can this be considered for enhancement? creating a switch to enable this behaviour?

Its important the indicators actively updated with live data for many reasons -  if you are relying on the indicators for entry or exit, (moving avg crossover etc) waiting for the canndles to complete will cost you the price of entry or exit. this becomes more important when you start playing with lower timeframes like 1m/5m.

please consider this for enhacement, I dont im alone in this regard.

Thanks

**Comment by stash86** [comment]
We won’t add that for the simple reason that it makes the strategy can’t be backtested.

There are few hacks you can do to achieve what you want. In the end, it’s all just python programming. I won’t give the hacks because I don’t believe such thing would really benefit you. You can learn how FT works first, then you should know what are the required hacks needed.

**Comment by xmatthias** [comment]
> Can this be considered for enhancement? creating a switch to enable this behaviour?

No, sorry.
Aside from not being backtestable (you'll be aware of this i assume), Repainting will also lead to ghost signals in live - which are trades that enter (or exit) - but once you look at a chart 1 candle later, there's no signal there anymore.


This will lead to tons of confusion - and will severely increase both the support effort (rarely anyone reads the documentation to understand what settings they change ...), as well as the complexity for both the user, and people trying to assist with such problems.

**Comment by froggleston** [comment]
Not to mention that you'd also need to convince the developers of talib and other libraries to fundamentally change the whole way those libraries work, which is .... unlikely.
