### ISSUE TITLE
Get informative pairs from a different trading market

### ISSUE THREAD

**Issue by win-lobo** [freqtrade/freqtrade#9746]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.11
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9

## Describe your enhancement

Hello, I'm looking for a way to use informative pairs trading in a different market (Futures).
My strategy runs on Spot market and uses BTC as stake currency but for some circumstances like trading volume (which differs in both market) I feel more comfortable using futures pairs to get insights into what's happening there before entering a trade.

I have looked into the documentation and similar request but unfortunately I could not find an answer.
The only parameters that `get_pair_dataframe(pair='{BASE}/USDT', timeframe='1h')` allows are pair and timeframe. 

It would be great to have something like below but not sure if that's technically efficient or possible. Anyway just wanted to give it a try.
```
    def informative_pairs(self):
        informative_pairs = [("BTC/USDT", "1h", "futures")]
        return informative_pairs
```

Note: Not sure if there is a config parameter that can help with that instead.

Thanks.

**Comment by xmatthias** [comment]
you can in theory do this since quite some time - though success will depend on the actual exchange used (ccxt (or rather, the underlying exchanges) don't always allow querying futures data when the exchange was initialized for spot trading and viceversa for all exchanges).


`informative_pairs()` (as well as the corresponding `@informative` decorator) do have a little documented 3rd argument with candle type (as part of the tuple in the regular function - and as kwarg `candle_type` in the decorator).
the "full documentation"  in the [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) documentation does include this as optional parameter.




this parameter normally defaults to whatever your trading mode is (spot for spot trading, futures for futures tradingmode) - but can in theory be set to either `''` (or None - empty for default - see above), `spot`, `mark`, `index`, `premiumIndex` or `funding_rate`. 
Not all exchanges will have all price types ... so do your research first (and be aware that such a  strategy won't tranfer to other exchanges without eventual modifications).

Also, the pair given **must**  match the correct [pair naming scheme](https://www.freqtrade.io/en/stable/bot-basics/#pair-naming).

the same parameter is also available on `get_pair_dataframe` - and obviously assumes that the corresponding pair was configured for informative (or is used directly via `@informative`).

**Comment by xmatthias** [comment]
While looking at the docs for something else, i realized that also the [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) section does include a "alternative candle types" documentatoin section (collapsed note box), with that, describing both methods in the docs.
