### ISSUE TITLE
Bug Backtesting: failing to properly exit trades when having open entry order

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9760]
## Describe your environment

  * Operating system: linux
  * Python Version: Python 3.9.2
  * CCXT version: ccxt==4.2.25
  * Freqtrade Version: freqtrade 2024.2-dev-35e1421d5
 
## Describe the problem:
During backtesting on 1m timeframe, I'm not able to exit trades properly, by exit signals or custom trailing stoploss.

*Explain the problem you have encountered*
During backtesting on 1m timeframe and without timeframe details, trade exits are not properly triggered, trades are not closed at expected time.

### Steps to reproduce:
1. Create a simple strategy using 1m timeframe
2. Create a custom stoploss that will trail
3. Backtest

### Observed Results:

  * What happened?
  trailing stop is triggered multiple candle late, 
  * What did you expect to happen?
  Trailing stop should be triggered once price touch it

To test, I tried to force stoploss exit using it as signal doing this:
```
        close_under_trailing_stop_long = df['close'] < df['trsl_long']
        close_over_trailing_stop_short = df['close'] > df['trsl_short']

        df.loc[
            (   
                close_under_trailing_stop_long
            ),
            'exit_long'] = 1

        df.loc[
            (
                close_over_trailing_stop_short
            ),
            'exit_short'] = 1
```
But got the same result with exit triggered more than 10 candles late.

Note:
I saw in test.backtesting that **test_backtest__check_trade_exit** is using a "5m" timeframe with a "1m" timeframe detail.
Maybe we could add a "1m" test case scenario.

**Comment by xmatthias** [comment]
technically, there's no real difference between timeframes (at least anything <1 week) - so it's quite unlikely - and it's more likely related to some oddity in your strategy.


happy to look at this, but i'll need you to provide an actual, proper reproduction (full strategy, including timerange this should be tested on to show this behavior).
As it is now - it's really only a tale - nothing more.

**Comment by Axel-CH** [comment]
Thank you for your response, I will create a simple strategy to reproduce the issue, will come back to you after that.

**Comment by Axel-CH** [comment]
I was able to reproduce the issue, for some reason, when I'm using a "custom_entry_price" callback with a price that won't be filled immediately (keeping an entry order open) the trade won't close properly.

In fact, there is a has_open_order condition in backtesting.py that prevent "_check_trade_exit" call if "trade.has_open_orders"
You can check backtest_loop, step "# 4. Create exit orders (if any)"

I think we must remove or replace the "if not trade.has_open_orders" condition before calling "_check_trade_exit"

**Comment by xmatthias** [comment]
so far, i don't really see anything that justifies a change. It's more a lack of understanding that leads you down this path.

The `custom_entry_price()` correlation is something i suspected here - but was curious for a reproduction (can never exclude a bug, can you) - as "fill" times WILL change with lower timeframes (candles are smaller - hence a 1% offset (or whatever value used) can lead to a fill X candles down the road, which might not happen on longer candles (they're longer, both in time, as well as in "high/low" wicks.

Once a candle touches your price (custom price is within high / low) - it'll fill (fully). Backtesting doesn't know the concept of "filled partially" - simply because we lack information to properly simulate this (you can determine volume, but not how the orderbook actually looked like at the spot you've placed your order at).

Until this is the case (the order is filled), there is no position to "check for exit" (you don't own anything) - it's just an open order waiting for filling.

All you can do at that point is "check for cancellation" - either through regular (configured) timeouts, or through custom-timeout.
Once that order is canceled (or filled) - then the trade will either be deleted (nothing filled - so you don't have a trade) - or your trade is filled - and regular exit-processing will commence.

**Comment by Axel-CH** [comment]
Test Strategy to reproduce the issue: 
[CustomStoplossWithLow.zip](https://github.com/freqtrade/freqtrade/files/14171322/CustomStoplossWithLow.zip)

**Comment by Axel-CH** [comment]
From what I understand, in that case the issue is coming from the fact that there is no distinction between `entry` and `exit` orders with  `has_open_orders`

`if not trade.has_open_orders`
should be at least replaced by
`if not trade.has_open_exit_orders`

Unless i really don't get it... wich is a possibility 😀

**Comment by xmatthias** [comment]
> Unless i really don't get it... wich is a possibility 😀

Didn't say (nor imply) this at all. :)

---

I do understand what you mean - however - the main goal of backtesting is to emulate behavior of dry/live _as best as possible_ (will probably never be perfect for reasons we don't control).

If you have an open order (other than stoploss) in trade mode (dry/live) - there will be no "exit" processing at this moment - as such - there's no bug or problem in backtesting - as it's following trade mode behavior in this regard.

It's another discussion if this handling should happen (maybe, someday in the future) - but this move has to start on live - not with backtesting for sure (backtesting is an easy adjustment - live is not).

The problem with this is - there's a ton of edge-cases to consider in such a scenario - most of which you can't simulate / force to happen easily - letalone to simulate them or even think about these.
Missing a single one may lead to an open order the bot would simply "forget" - which is rather risky from a user perspective (it may fill at any later point) - especially if you don't regularily (and carefully) look at your open orders and trades **on exchange**.

**Comment by Axel-CH** [comment]
Now I understand, thank you for the clarification. With this behavior i'm not able to execute my strategy, as I am scaling in.
For example, in a long position I always have a lower limit entry order, so if the price move lower to have a better entry price.
If the price do not move lower it is not an issue because I'm already in, if it goes lower I'm in with a better price.

**Comment by xmatthias** [comment]
it's a limitation - sure - but as said - backtesting is working as intended.

You can still perform the required checks in custom_cancel callbacks, once the order is canceled, processing of regular exit functionality will progress immediately.
