### ISSUE TITLE
WebUI, 2 strategies are mixing?

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#9782]
* Operating system: Linux
  * Python Version: 3
  * Freqtrade Version: freqtrade 2024.1
  
Running two strategies in the WebUI, they are mixing. The stock buys ordered by 1 strategy is being sold by the second strategy.

freqtrade trade --config user_data/config_1.json --strategy Strategy1
freqtrade trade --config user_data/config_2.json --strategy Strategy2

only the port is different in the 2 configs

    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "same",
        "ws_token": "same",
        "CORS_origins": ["http://127.0.0.1:8080"],
        "username": "same",
        "password": "same"

    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "same",
        "ws_token": "same",
        "CORS_origins": ["http://127.0.0.1:8080"],
        "username": "same",
        "password": "same" 

The strategy should only be buying and selling their own trades.
The screenshot shows that adding the second strategy inherits the trades of the first bot and I have witnessed the second strategy closing trades opened by the first strategy.
![Screenshot from 2024-02-08 21-12-31](https://github.com/freqtrade/freqtrade/assets/94738562/36cd89a5-a59e-420d-a1c2-3c7d81e91933)

**Comment by xmatthias** [comment]
When running more than one bot on the same machine, please make sure to follow the [according documentation](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade).

From your description (and based on the commands given) - it seems like you're using the same database (the first point in the above linked documentation page).
You'll also usually want to use a different telegram bot (if you're using telegram) - otherwise only one of the 2 bots will be able to work at the same time and will also listen to interactive commands sent.

**Comment by Immortality-IMT** [comment]
Great. Seems to be working now. I shall monitor over the next few tries.
