### ISSUE TITLE
Python 3.12 compatibility / TA-Lib

### ISSUE THREAD

**Issue by mczero80** [freqtrade/freqtrade#9795]
Hi,

I want to make a Freqtrade package for Void Linux. There are some hurdles, first, Python on Void is on version 3.12.2.

The Freqtrade installer expects Python 3.9 - 3.11 as highest compatible version. Could Python 3.12 be supported in the near future?

I did hack setup.sh to support Python 3.12 and so far it did work (I did not complete the setup process fully because of missing dependencies though).

And then I have a question regarding TA-Lib.  The build_helpers/install_ta-lib script does some modifications to the TA-Lib source, are they really necessary for Freqtrade? Because there is no TA-Lib in the Void Linux package repository and I have to provide a TA-Lib package as well. And I don't know if the modifications that install_ta-lib does are bad for other packages that may depend on TA-Lib in the future.

Thank you very much and have a great weekend.

**Comment by perkmeister** [comment]
You'll be installing in virtual environment with setup.sh, so I don't think any of that matters, you can have different versions to what is installed in your native environment.

**Comment by xmatthias** [comment]
3.12 is supported for parts of the bot (we also run ci against 3.12) - but we'll not be adding it to the setup script until all dependencies support python 3.12 (which is a problem with scientific / machine learning projects).

Tests for 3.12 we know are not working are disabled (it's basically all of the freqAI module except for lightgbm and xgboost).
We'll gradually re-enable the tests as 3.12 support for the relevant packages (catboost, torch, stable-baselines3) rolls out - but it's not up to us to move this forward - but with these projects.

Hence while you can make a basic freqtrade installation for 3.12 - it'll be limited to "no freqAI".

---

the modifications to ta-lib are rather simple precision modifications (you can run the `sed` command on the ta-lib codebase manually to see the actal changed line).
These are necessary for some xxx/BTC pairs - which can show a very low price - and where the result without these modifications will simply be a flat 0 line (Bollinger Bands on a pair priced at 0.000005 BTC, for example) - which is wrong.
That's due to intermediate results that go below the floating point thresholt - hence this thresholt has to be increased to work correctly.

Installing ta-lib without these modifications will make (exactly one) test fail - and will break (some) people's /BTC strategies - assuming they do use affeted methods (shouldn't have an impact to bots on USDT markets).

It's slightly slower (due to the increased precision) - however - there are newer ta-lib versions than 4.x (not supported by the python wrapper at the moment as far as i know) - which do have this fix included.

---

To be quite frank - from a user perspective (think - user of a linux distro that provides a package for a particular software) - i expect a fully functional installation.

for freqtrade, that'll _currently_ mean 
* python 3.11 
* installing the full dependencies (including freqAI) - if possible optional - but that's not always an option for system package managers
* properly installed (patched ta-lib).

**Comment by mczero80** [comment]
Ahh thank you very much.

I will try out installing python 3.11 through pyenv, if that fails for whatever reason, I'll go with python 3.12 and Freqtrade without FreqAI.
