### ISSUE TITLE
Disabling "Auto Lock"

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9808]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: docker 2024.1(`python -V`)
  * CCXT version:docker 2024.1 (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker 2024.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello,

Is it possible to disable the autolock which the bot uses whenever a trade closes?

I tried manually entering the below code however it did not help although it recognized what i have written by giving me a headsup on telegram. I want to completely disable it, is it possible?

    @property
    def protections(self):
        return [
            {
                "method": "CooldownPeriod",
                "stop_duration": 0
            }]

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
No, disabling auto-lock is not possible, though you can delete the protections entry if you think that's a must ([unlock pairs](https://www.freqtrade.io/en/stable/strategy-customization/#locking-pairs-from-within-the-strategy).

It's also a lock that doesn't apply during backtesting explicitly - but is there implicitly due to the operations of the bot (if a pair closed on a candle, there can't be a new entry until the next candle).
As such - a strategy disabling auto-lock cannot be accurately backtested.

**Comment by erhangunay** [comment]
thank you for the answer
