### ISSUE TITLE
Backtesting - Close and open on same candle not possible?

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#9817]
## Describe your environment

  * Operating system: Mac OSX
  * Python Version: 3.9.7
  * CCXT version: 4.1.76
  * Freqtrade Version: freqtrade docker-2023.12-dev-0f82ea87
  

Hi, firstly, thank you for all your work on this fantastic program!

## Describe the problem:

I've spotted that the backtest will close a trade on a candle at the open price, but then will not allow any of the further coins to be purchased in the same candle. This isn't what would happen in Live. I cannot see any reference to this behaviour in the documentation.

I am using a custom_exit to avoid signal collision but I am not sure if this only happens using that.

As far as I understand, if we had this setup with the order being Coin A then Coin B in the whitelist and with max_trades = 1, then this would happen:

_**EDITED TABLE**_
| Candle  | Signals | Backtest | Live |
| ------------- | ------------- | ------------- | ------------- |
| 1  | Buy Coin A and Buy Coin B  |   |  |
| 2 | Sell Coin A and Buy Coin B  | Buy Coin A  | Buy Coin A |
| 3  | Buy Coin A and Buy Coin B | Sell Coin A   | Sell Coin A and Buy Coin B  |
| 4  |   | Buy Coin A  | Nothing |

In backtest this doesn't buy Coin B on Day 2, but in live it would, and instead buys coin A again on Day 3.

### Steps to reproduce:

  1. Use strategy below.
  2. Run backtest script below
  
### Observed Results:

  * What happened? See below. Just repeatedly buys and sells Coin A, every other day. But in Live they would alternate.
In backtest, Coin B is never bought.
  * What did you expect to happen? Allowed to buy another coin on the same candle as the sale as that is what would happen in live. This may be by design, that the bot backtest locks itself for a candle, but I cannot see any reference to it in the Backtesting assumptions.

In the below, although we are using both BTC and ETH (see execution script), only BTC is ever bought. As a BTC close locks the buying of ETH in the same candle. So Bot moves to next candle, BTC is first, and so it buys BTC.

<img width="1146" alt="image" src="https://github.com/freqtrade/freqtrade/assets/7068759/a7aae3ad-d341-4b3c-bf69-c7e25b70c79c">

### Relevant code exceptions or logs

Super simple strategy to demonstrate. Just closes the trade the next day. I have a much more complicated actual strategy where I first spotted this difference between Live and Backtest, so this is just an example.

`docker compose run --rm freqtrade backtesting --config user_data/config-backtest.json --pairs BTC/USDT ETH/USDT --strategy SimpleStrategy --timerange 20240101- -i 1d --fee 0.000 --breakdown month --cache none    
`

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        return dataframe

    # always buy everytime
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # populate the entry longs
        dataframe['enter_long'] = 1;
        dataframe['enter_tag'] = 'Buy';
       
        return dataframe
    
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        return dataframe
    
    # using this to avoid signal collision
    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
       
        # force a close on the next candle
        if (current_time.date() > trade.open_date_utc.date()):
            return 'Sell';
```

Note: Please copy/paste text of the messages, no screenshots of logs please.

**Comment by alisalama** [comment]
I checked a strategy without the custom_exit and the same thing happens. I assume this is by design then?

```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # get the pair
        pair = metadata['pair'].replace(f'/{self.config["stake_currency"]}', "");
        
        # populate the entry longs
        if pair == "BTC":
            dataframe['enter_long'] = dataframe.index % 2; # tag the odd rows for BTC (so we get buy on different days)
        else:
            dataframe['enter_long'] = abs(dataframe.index % 2 - 1); # tag the even rows for ETH (so we on different days)
               
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # flip the enter_long over so we sell on the same day as the alternate coin (and avoid collision signals)
        dataframe['exit_long'] = abs(dataframe['enter_long'] - 1); 

        return dataframe

```

**Comment by froggleston** [comment]
Yes this is by design. See rationale why:

https://github.com/freqtrade/freqtrade/issues/8966
https://github.com/freqtrade/freqtrade/issues/6666
https://github.com/freqtrade/freqtrade/issues/5680

Plus others if you search.

**Comment by alisalama** [comment]
Hi, thanks for your response, but they are not the same issue/question.  They all refer to the same pair being locked for the candle when there is a close. I am aware of that feature and makes sense.

This is about in the backtest, all other pairs appear to be locked for the same candle, when a different pair has closed. Which is not what happens in Live.

**Comment by stash86** [comment]
It's similar concept. Backtest won't care about intra-candle actions, except roi and stoploss.

Why do you use 1d timeframe if you expects the trades to be closed before day change? You can just use 1h timeframe for example

**Comment by alisalama** [comment]
I accept the idea is "similar" but it is not the same. There is no intra-candle action needed here. I don't expect the trades to be closed before the day changes. Perhaps my labelling on the table was not clear enough - I have relabelled it below.

Simple question is why could you not buy a coin because you sold another coin in the same candle? That is what happens in the backtest, but in Live the bot will loop round again and buy the other coin on the 2nd bot loop.

| Candle  | Signals | Backtest | Live |
| ------------- | ------------- | ------------- | ------------- |
| 1  | Buy Coin A and Buy Coin B  |   |  |
| 2 | Sell Coin A and Buy Coin B  | Buy Coin A  | Buy Coin A |
| 3  | Buy Coin A and Buy Coin B | Sell Coin A   | Sell Coin A and Buy Coin B  |
| 4  |   | Buy Coin A  | Nothing |


I could accept the answer to that being the order of the coins in the whitelist/backtest being a limitation of the backtest, but that doesn't appear to be the reason.

**Comment by stash86** [comment]
https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic

Entry is checked before exit, which means in backtest, you won't be able to buy B since your trade slot still full with A.

In live, the checks are done on every bot loop, hence you will buy B after you sell A and still within the same candle

**Comment by alisalama** [comment]
I see the backtest loop logic now. I guess then the question is why? That just doesn't match what happens in reality.

We are saying that when there is a buy signal and an exit in the same candle on any two coins in the backtest, the buy signal is **always** ignored. This means the backtest can theoretically "ignore" up to half the trades in a strategy that would actually execute in Live / or just take a completely different path of trades.


---- 

I thought `--timeframe-detail` might come to the rescue, but it doesn't make any difference. I think due to this _"Entry orders will only be placed at the main timeframe, however Order fills and exit signals will be evaluated at the 5m candle, simulating intra-candle movements."_ So again, the exit happen after the entry is tried, and so the entry that would happen in Live is ignored.

**Comment by alisalama** [comment]
In a more extended theoretical example, just repeating the same alternating signals. These are fundamentally different outcomes.

| Candle  | Signals | Backtest | Live |
| ------------- | ------------- | ------------- | ------------- |
| 1  | Buy Coin A and Buy Coin B  |   |  |
| 2 | Sell Coin A and Buy Coin B  | Buy Coin A  | Buy Coin A |
| 3  | Buy Coin A and Buy Coin B | Sell Coin A   | Sell Coin A and Buy Coin B  |
| 4 | Sell Coin A and Buy Coin B  | Buy Coin A  | Hold Coin B |
| 5  | Buy Coin A and Buy Coin B | Sell Coin A   | Hold Coin B  |
| 6 | Sell Coin A and Buy Coin B  | Buy Coin A  | Hold Coin B |
| 7  | Buy Coin A and Buy Coin B | Sell Coin A   | Hold Coin B  |
| 8 | Sell Coin A and Buy Coin B  | Buy Coin A  | Hold Coin B |
| 9  | Buy Coin A and Buy Coin B | Sell Coin A   | Hold Coin B  |
| 10 | Sell Coin A and Buy Coin B  | Buy Coin A  | Hold Coin B |
| Outcome |   | 9 Trades  | 3 Trades |

**Comment by alisalama** [comment]
If we did a similar thing, but alternated the sale of Coin B too (as per my example above). In backtest we would miss half the trades, and totally ignore Coin B.

Candle | Signals | Backtest | Live
-- | -- | -- | --
1 | Buy   Coin A and Sell Coin B |   |  
2 | Sell   Coin A and Buy Coin B | Buy   Coin A | Buy   Coin A
3 | Buy   Coin A and Sell Coin B | Sell Coin A | Sell   Coin A and Buy Coin B
4 | Sell   Coin A and Buy Coin B | Buy   Coin A | Sell   Coin B and Buy Coin A
5 | Buy   Coin A and Sell Coin B | Sell Coin A | Sell   Coin A and Buy Coin B
6 | Sell   Coin A and Buy Coin B | Buy   Coin A | Sell   Coin B and Buy Coin A
7 | Buy   Coin A and Sell Coin B | Buy   Coin A | Sell   Coin A and Buy Coin B
8 | Sell   Coin A and Buy Coin B | Buy   Coin A | Sell   Coin B and Buy Coin A
9 | Buy   Coin A and Sell Coin B | Sell Coin A | Sell   Coin A and Buy Coin B
10 | Sell   Coin A and Buy Coin B | Buy   Coin A | Sell   Coin B and Buy Coin A
11 | Buy   Coin A and Sell Coin B | Sell Coin A | Sell   Coin A and Buy Coin B
Buys |   | Coin A = 5 | Coin A = 5, Coin B = 5
Sells |   | Coin A = 5 | Coin A = 5, Coin B = 5
Trades |   | 10 | 20

**Comment by alisalama** [comment]
Hi @froggleston, I believe this has been incorrectly closed. The questions you mention as being related are not the same as this. Could you please reopen?

**Comment by stash86** [comment]
This is correctly closed since this isn't a bug. If you think you can improve the backtest without adding more time, please do open a PR.

**Comment by froggleston** [comment]
This is intentional and well understood behaviour, so the issue will remain closed. It *is* related as you could simply enter into a buy/sell spiral across multiple pairs, not just the same pair. As stash says, please consider any improvements in a PR.

**Comment by alisalama** [comment]
It is a logical / calculation bug. Basic logic tells you in Live you can exit and enter different coins within the same candle, in backtest you can't. Ultimately this will hurt the profitability of a profitable strategy in the backtest vs if you actually ran it in Live.

But I know sometimes in software things are the way they are for a reason, so I accept there may be a reason for the order being this way, so we can call it a question. If there is a reason for it then that's fine, but I haven't seen one yet, so it is at the very least an "open question".

I don't quite follow the spiral comment. AFAIU in the same candle, once a pair is exited it is locked for that candle, so we would buy the next pair with a buy trigger and we hit the max trades, as happens in live, and there is no spiral.

----- 

A fix looks like it could simply be a swap around of these 4 function calls, but I don't know if there are any dependency issues or downstream implications of that.

https://github.com/freqtrade/freqtrade/blob/60b12c1d9ecd19e8ed7ae6e559021c810c068c8c/freqtrade/optimize/backtesting.py#L1142-L1190

**Comment by alisalama** [comment]
I also just spotted the comment in the middle of those backtest functions, which sounds very related to my question.

https://github.com/freqtrade/freqtrade/blob/60b12c1d9ecd19e8ed7ae6e559021c810c068c8c/freqtrade/optimize/backtesting.py#L1157-L1159

**Comment by xmatthias** [comment]
> I also just spotted the comment in the middle of those backtest functions, which sounds very related to my question.

No it's not (at least not really).
Your "issue" is caused by your configuration - which i'm sure is using 1 max_open_trade.

If you're using "max_open_trades=2" - (essentially, if you're not maxing out your trade limit) then what you're claiming is NOT true - and trades on other pairs can be opened just fine within the prior, closing candle.
The provided strategy sample (on 1h data, as i don't have 1d data) shows that the bot closes at 2:00 - and opens the next pair at 2:00.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/a9aef384-2dc4-4ae1-a8cd-61d8f341f277)

Comparing this to one maximum parallel open trade:
![image](https://github.com/freqtrade/freqtrade/assets/5024695/55d70ae2-eab2-478d-9f63-d4b7848aafa8)

The "hacky workaround" linked above is exactly this. it "pins" the current_open_trades value to what it was before the candle starting.

---

Now removing this might _partially_ fix this issue (depending on the case) - but would in reality - make this issue worse as it's no longer deterministic how behavior will be.


you're working with 2 pairs - which is a very much simplified approach.
Assume a pairlist of 5 pairs (A,B,C,D,E) - with max_open_trades = 1.

Backtesting will process each pair in this sequence - for every candle - in a simplified format:
* check for entries
* check for exists
* Rinse / repeat

Assuming pair A has the open trade and closes, we'd be in a position to check for every other pair's entries (like, B,C,D and E - as we have the trade-slot open again.).
This is what you're thinking / hinting at above - and removing this "hacky workaround" would do just that.

But what if pair D had the open trade and closes?
we'd now ONLY check this for pair E - which may or may not have an entry signal.
It's however in position 5 of the pairlist - so why would this be preferred on an entry over pair A? 

The worst place would be if the very last pair (E) has the open trade - after which there'd be no entry checks - as it's the last pair in the pairlist.

As such - the "does it enter after an exit" would become totally random. It's now determined how backtesting will behave - which is way better than have results totally random.



You can't reverse the order of calls - if you check for exits first, then you cannot have a trade that enters, and exits on the same candle (be that via ROI, stoploss, or something other).
So while fixing "your" particular edge-case - you've caused problems for a much more common case of "entry and exit on the same candle".

The only fix i can think of for this is to loop the pairlist twice - which would however also potentially _double execution time_ (eventually worse, depending on the complexity of the strategy) - which is something i don't feel acceptable for an edge-case like this.


There's however no bug - it's intentional and understood behavior - as such, i don't see this issue as being a case to be reopened.
At maximum - we might improve the wording in the comment - though i do feel it's justified to call it a hacky workaround - as that's what it is - a workaround to a much worse problem.

**Comment by alisalama** [comment]
Thanks Matthias. I totally get Backtest doesn't have the advantage of the multiple bot loops during 1h/1d candle. I totally get that the order of the pairs in the pairlist would make a difference to the execution in the BT. So you're left with forcing another loop, which is too slow. That is fair enough.

I am using max_open_trades=1 with stake_amount="unlimited", which is what I need it to be for Live, but if I switch that to 2 for only backtest purposes then the stake is halved. I think your stake_amount is static at 140? So I think that causes another issue, perhaps that can be "hacked" away in custom_stake_amount, but I guess will hit the same no 2nd loop idea.

In my real strategy (not the example one above) I am using 10+ coins, 1d and over a 2 yr backtest it knocks out ~40% of the trades. So not really an edge case. I think two coins "swapping" over in the same candle could happen a lot in reality. This two coin example is just arbitrary to demonstrate what happens.

**Comment by xmatthias** [comment]
i don't think `custom_stake_amount` should care for this - it's updating as the trade closes.

It does remain an edge-case though - limited to your particular strategy - which might be impacted more than others - but that won't change the fact of it being an edge-case - neither will it change the fact that the changed logic will be just as wrong - as now only half of the pairs will be eligible for a new entry.
