### ISSUE TITLE
Prerequisite to process exit while having open order

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9828]
## Your question

It is not currently possible to process exits while having an open order, as discussed here #9760 
It a limitation that also affect backtesting and can give an unrealistic result, as even liquidations are not properly triggered in case of left open order.
As this limitation is voluntary implemented to prevent odd cases, I would like to know what modifications are needed to allow us to remove it.

**Comment by xmatthias** [comment]
Well you need to be 100% certain that you're not "forgetting" open orders (especially important in live, obviously) - and that all orders are properly handled (partial fills, ...).

That's the only requirement, really. 
That essentially involves all cases of closing or deleting a trade - as well as most cases where new orders would be placed.
This becomes more complex as every order might actually be partially filled (which is something rather difficult to test reliably).


you also need to ensure all open orders are cancelled before placing a new "non-stop" order (otherwise the placement will most likely fail, as you'd tie up the same capital twice) - again with the same requirement above.

Effectively, it's also a reminder of "old days" - where it didn't really matter (you didn't have the possibility to place orders at random prices, nor to replace orders) - so it's something that should be addressed for sure - but is probably not something easy / quick.

There's however no explicit list of "these cases need to be covered" - but feel free to list them if you intend to look at this (i don't, at least not in the foreseeable future).

**Comment by Axel-CH** [comment]
Thank you for your answer,
I will definitly work on this, I will start by testing in live what is hapening when I disable the "has_open_order" check to see what kind of issue that could create.

_you also need to ensure all open orders are cancelled before placing a new "non-stop" order (otherwise the placement will most likely fail, as you'd tie up the same capital twice)_

On this part I would like to give the possibility to split an entry in multiple orders in order to scale in the position.
So you could have two or tree patial entry or exit orders on exchange at the same time. In fact the same capital won't be allocated multiple times but just shared beween multiple orders.
What do you think about that?

**Comment by xmatthias** [comment]
> On this part I would like to give the possibility to split an entry in multiple orders in order to scale in the position.
So you could have two or tree patial entry or exit orders on exchange at the same time. In fact the same capital won't be allocated multiple times but just shared beween multiple orders.

Well what you talk above is the prerequisite - though i don't really see a need for this.
You can simply use the position-adjust callback to scale into the position - don't really see why we'd need a 2nd way.
if the orders are at the same price level - you gain nothing.
if the orders are not - you can place the 2nd order once the first filled.
That's anyway a completely different topic - please don't mix it with what this issue is about.

Also - you seem to focus on "entering" a position - but assume you got an exit order "above price" on binance spot ... your "XRP" (or whatever other coin) will be tied up - and you cannot place a 2nd order for this.

**Comment by Axel-CH** [comment]
Of course that will be seperated features and PR's.
About exiting it is the same principle, if I have 10 (contracts/coins) I can have and exit order of
5 contract at price 103.5
5 contract at price 103.7

Here I am not trying to sell two times the same coins.

**Comment by xmatthias** [comment]
yes - but you can just as well place the 2nd order for 103.7 once price reaches 103.5.
Don't see this as a "must have" feature. It'll complicate code for no good reason - but as said - i see that as off-topic to this issue (and hence, will hide comments about this now).

**Comment by Axel-CH** [comment]
_You can simply use the position-adjust callback to scale into the position - don't really see why we'd need a 2nd way._

There is two reasons:
- Market can moove quikly so it is always better to have the order already on exchange, sometime the bot will not have time to react to be filled (same as why it is better to have stoploss on exchange)
- If your limit order is already on exchange and is not filled imediatly, you will pay market  "maker" trading fees, hugely lower that market "taker" fees.

**Comment by xmatthias** [comment]
Closing this as i do think that the question was ansered (what's the prerequisite) - and there's nothing actually actionable in this issue anymore.

It's in the rarest of cases that you'll get a full checklist of "did i check these parts ...". 

As mentioned above - in general, i don't see this as "hard requirement" - most logics are in place - though there'll be edge-cases that need proper handling.

**Comment by Axel-CH** [comment]
Thant you @xmatthias , I've removed the "has_open_order" limitation for both live and backtest. Tested live for one week, It's working fine for most cases.
I managed to fall in an edge case with a bug in my strategy: My on exchange long entry order was near and under my stoploss on exchange.
Ended up with a remaining position that the bot was not aware of. Beside that it is fine 👍🏾

**Comment by xmatthias** [comment]
Happy to get a PR - in this case (as it's changing some fundamentals quite drastically) please make sure to include a dedicated test (something similar to what we have in `test_integration.py` already) for the new / changed functionality (same for backtesting, obviously).
