### ISSUE TITLE
Setting an item of incompatible dtype is deprecated

### ISSUE THREAD

**Issue by MrHumanRebel** [freqtrade/freqtrade#9852]
def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        strategy_xyz= (
            rules here
        )

        df.loc[
            strategy_xyz,
            ['enter_long', 'enter_tag']
        ] = (1, 'strategy_xyz')

        return df

I get the following warning:
/freqtrade/user_data/strategies/Strat.py:494: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'strategy_xyz' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  ['enter_long', 'enter_tag']

The code is working fine but this warning annoys me so much. How can I get rid of it?

Thanks in advance!
Have a nice day.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by perkmeister** [comment]
> I get the following warning:
> /freqtrade/user_data/strategies/Strat.py:494: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'strategy_xyz' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
> ['enter_long', 'enter_tag']

Add the following lines to the top of `populate_entry_trend()`:
```
dataframe['enter_tag']=''
dataframe['exit_tag']=''
```

**Comment by xmatthias** [comment]
well knowing the version, we could tell him to update to a newer version - where we're doing this for the user already  as a temporary workaround - which is why the version is important, and i stopped answering questions which fail to provide that.

At any rate - the underlying pandas bug in this regards (this message is false) has been fixed (https://github.com/pandas-dev/pandas/issues/56503), and will as such also disappear with the next pandas release.
