### ISSUE TITLE
Fetch curren open trades during live mode (and backtesting), presumably using the dataprovider

### ISSUE THREAD

**Issue by atomcracker** [freqtrade/freqtrade#9860]
I am using the very latest freqtrade version.

When I open a trade for let's say BTC. I would like to know if, for example, the bot is in an ETH position simultaneously. Or at the very least see the amount of currently open long/short positions.

In confirm_trade_entry I have access to the trade object, I have tried to find the other currently open trade objects with the self.dp methods too but I can't seem to work it out.

What I used before is keeping track in a separate dict of what positions are open. But I would very much like to fact-check the information reliably in live mode.

Is there any way to get this kind of information? Thanks in advance!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---

in callbacks, you can use [get_trades_proxy](https://www.freqtrade.io/en/stable/trade-object/#get_trades_proxy) - with appropriate filters.
In live, this might work in `populate_*` methods, too - but in backtesting, you'll only get empty results due to the execution sequence (populate_* methods are only executed once per pair).
