### ISSUE TITLE
Be even more than just a crypto trading bot!

### ISSUE THREAD

**Issue by prononext** [freqtrade/freqtrade#9886]
I know that Freqtrade is advertised as a crypto trading bot as stated before in similar request. 

But - its clear that trading crypto via API is not really a big difference than trading stocks, or options via API apart from fees and that with non crypto assets there mostly are market hours. 

It would be really nice to see some difference in trading non-crypto assets with good open source tools like Freqtrade and Freqtrade will also gain a lot of interest when doing so. 

### Here a rough plan how that could work: 

- [ ] Insert explicit setting for respecting Market Hours (https://github.com/freqtrade/freqtrade/issues/7138)
- [ ] Create API Setting for IBKR (https://github.com/freqtrade/freqtrade/issues/5608)

### **Hey, Freqtrade is made to be "THE TOOL" for trading "ANY" API-tradable Asset!**

Lets go that way and show that Open Source with Freqtrade/FreqAI can really rule the market on API Trading.

**Comment by stash86** [comment]
We will wait for your PR to achieve this. Thanks.

**Comment by prononext** [comment]
@stash86 what should be the problem here? 

**PR not the problem here:** 

- [x] "crypto trading bot open source" - Google 1st Place
- [x] "options trading bot open source" - Google 1st Page
- [x] "stocks trading bot open source" - Google 1st Page

I guess that topic is really attractive and will greately extend the codebase and knowledge of the freqtrade project.

**Comment by froggleston** [comment]
Someone has to code it, is the point, and freqtrade is specifically a crypto bot. So, unless someone outside the core dev contributors wants and has the time to look at it, then it's up to the community to provide the code in the form of PRs demonstrating a route to a working product.

**Comment by xmatthias** [comment]
What @stash86  means with "PR" is that you're welcome to implement and contribute that feature.

that's not "PR" in the sense of advertising - but PR in the sense of "Pull Request".

---

@prononext 
Thanks for the proposal - and as you've already found - others have asked the same.

Freqtrade is a free, open source project, maintained in people's free time. 
The current scope is already filling my available free time rather nicely, so i'd rather not extend the scope to other areas.
It's also not a topic i'm personally interested in - which would mean it wouldn't be fun.

As such, I don't see freqtrade move in that direction at this point.

If ccxt (the library we use for exchange connections) were to implement traditional exchanges, we might have a look at this again - but your initial point of contact will be there - as i don't plan on maintaining exchange API compatibility as part of freqtrade.

**Comment by prononext** [comment]
Thank you @xmatthias, 

I am using freqtrade and freqai for quite some time now but I am not 100% familiar with the details of the codebase and how the exchange is connected.

Could you maybe provide a checklist of what needs to be done to get ccxt working with IBKR and freqtrade? 🙏 

For sure as CCXT is the base of the Exchange connector we need to somehow create a API Translator to get the IBKR API working with the CCXT protocol that Freqtrade uses. 

First to connect it here I suppose: https://github.com/freqtrade/freqtrade/tree/develop/freqtrade/exchange

Also found a old post on CCXT directly https://github.com/ccxt/ccxt/issues/6508

**Comment by froggleston** [comment]
As xmatthias pointed out, it's not a priority and you'd need to see if CCXT would support trad exchanges before it would be considered within FT.

**Comment by xmatthias** [comment]
> Could you maybe provide a checklist of what needs to be done to get ccxt working with IBKR and freqtrade? 🙏

Quite simply - no.
It's a decision first of all, if a library known to connect to crypto exchanges also wants to integrate with regular exchanges.
It's one i do not know the opinion on - nor do i particularily care. 

---

However, as mentioned above - it'd extend the scope for freqtrade - which i currently don't see us having the capacity for (and don't have a personal interest in, either).
This means that even if it were integrated in ccxt, we'd probably not move to support it "just because" - not unless someone steps in and volunteers to maintain this part longer term. 

This will however not be someone unknown doing a so-called "drive-by contribution" - just to get things working - but someone who's been doing quality contributions to the community over a longer period of time, someone we know will not disappear 2 days after (everyone will say otherwise - it's actions over time that count here).
This is quite important for contributions that extend the scope of a project - as that extended scope will also need an extended maintainer team (more capacity) to maintain things going forward.

I don't see any point in further discussing this here - as we've explained our standpoint on this topic as "not planned".

**Comment by roozich** [comment]
@xmatthias I believe the future of freqtrade should include an API gateway or adopt an API Federation architecture, instead of solely relying on the CCXT Unified API, which currently limits the freqtrade capabilities. By integrating a Federation architecture, Freqtrade could seamlessly support a wider range of exchange API features, including those from centralized exchanges, decentralized exchanges (DEXes), and other market exchanges.

This approach would allow for the implementation of diverse trading scenarios with minimal effort, maintaining CCXT as an independent gateway option within this broader framework. Such a strategy ensures that Freqtrade remains adaptable and powerful, capable of accommodating any trading requirement.

![2d61fbac-traditional-api-vs-graphql-federation-architectures](https://github.com/freqtrade/freqtrade/assets/1100023/34b142ca-7710-47cd-b445-ec712a21b43a)

https://github.com/ccxt/ccxt/issues/6508
https://github.com/roozich/ibkr_web_api
https://the-guild.dev/graphql/mesh
https://github.com/fibo/graphql-ccxt
https://hummingbot.org/gateway/
https://github.com/hummingbot/gateway

**Comment by roozich** [comment]
If we have a solid architecture and proposal I can start to contribute for this feature with the team

**Comment by froggleston** [comment]
I'm afraid throwing around phrases like "minimal effort", "the team", etc are misguided. "The team" is the community of open source developers. It's up to "the team", i.e. everyone including yourselves, to produce proposals. Developing a feature is one thing and the maintenance of that feature is another. There's a big gap between saying "just implement GraphQL" and producing a working, tested, dependable, updated, maintained piece of code.

Xmatthias has been *very* clear. It's not in scope, so it'll be up to you to produce initial developments, tests, docs before it would be considered for inclusion.

**Comment by xmatthias** [comment]
> It's not in scope, so it'll be up to you to produce initial developments, tests, docs before it would be considered for inclusion.

On top of that - this is not a proposal I'll consider if it comes from a new/unknown contributor - as then it's almost certainly a drive-by contribution - which will dump the further maintenance onto existing people.
Built our trust with consistent, quality contributions (code, comments, ...) over months (which also kindof serves as a "i won't go away soon" proof) and we can discuss bigger ranging changes.

If your **first** interaction with a project is "let's rewrite everything, this is limiting" - please accept that your opinion will not be considered.

**Comment by roozich** [comment]
frog, by "the team," I mean a group of people in the community who share the same purpose and are willing to participate. When I mention "minimal effort," I'm comparing it to the comprehensive implementation of exchange features.

We are here to discuss, brainstorm, and talk about possibilities. We need to assess whether it's worth pursuing certain implementations. Fully implementing every feature requires time, energy, and volunteers to develop and maintain it.

@xmatthias, this feature isn't about rewriting everything. It's all about strategizing how to fetch data, without altering the core logic of freqtrade.
