### ISSUE TITLE
static stoploss from 'OpenPrice' per pair

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#9950]
## Describe your environment

Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.7
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2024.01

## Your question

Hello Team:)

I'm writing to you today to inquire about an issue I'm experiencing with the custom stoploss function.

my goal is set a static stoploss based on the opening price for each pair.
For instance, 
 1. BTC/USDT:USDT set to -13.2% 
 2. ETH:USDT/USDT set to -21.3 % 
from open price.

To implement this, 

ⓐ use_custom_stoploss = True
ⓑ As following the code is for stoploss code in def custom_stoploss function. 

    if pair in ('BTC/USDT:USDT'):
        result = stoploss_from_open(-0.131, 0, is_short=False, leverage=trade.leverage)

ⓒ
    if pair in ('BTC/USDT:USDT') :
        stoploss_price = trade.open_rate * (1 - self.BTC_Long_SL / trade.leverage)
        
        # self.BTC_Long_SL = 0.131
                    
The problem is that backtesting results of applying static stoploss(regular stoploss)  without using custom stoploss on a single pair are different from the results when setting static stoploss using the customstoploss function.

Could you please help me understand why this is happening and how I can fix it?

**Comment by xmatthias** [comment]
i'm ... not entirely sure what you're asking - it's quite clear that a static stoploss (same for all pairs) will yield different results than when setting a stoploss per pair.

Also - custom-stop is trailing by definition - so whenever a value is returned - this value is assumed to be "from current price". 
it's called `stoploss_from_open()` - but it assumes to get current_profit as 2nd value to do it's calculations correctly.
if it doesn't - then values will be incorrect - as the assumption of "trade starts at 0% profit" is wrong - you usually start at ~-0.02% profit (due to fees).
I also don't think we've got any examples using 0 in this position ... as i don't see when this would make sense.

Also - you should keep in mind that the original, static stoploss will serve as the default - so if your "-21%" is below that static stoploss - the static stop will win.

What (c) is trying to say is beyond me - it's a simple, commented assignment - so as is - will be ignored.

**Comment by thkwon9474** [comment]
@xmatthias 

I would like to express my sincere gratitude for your continuous and kind assistance.

To clarify my previous inquiry,,,

1. Objective : Set stoploss at -13% for BTC / -21% for ETH
 - corrected the current_profit = 0 error mentioned in the previous inquiry

2. Issue :
 - Backtesting results show a discrepancy between regular stoploss set at -0.13 and stoploss_from_open(-0.13, current_profit, is_short= False, leverage=trade.leverage)
 - Backtesting for each pair was conducted using the -p option

Regarding this, Could you give me a advice?

**Comment by xmatthias** [comment]
regular stoploss can "cheat" when it comes to exit price within a candle (we know the sequence prices within a candle are evaluated).
A stop set via custom_stoploss is however always treated as trailing stop - which uses slighlty different logic to determine the final exit price within the exiting candle.

**Comment by thkwon9474** [comment]
Thanks for reply.

Regarding this, I have a one more Question.

I am aware that fees are added to/subtracted from the open/close price in dry/live runs. However, I noticed that the profit in the log does not change even when using the --fee option with Custom Stoploss() or Custom Exit() functions.

I would appreciate it if you could clarify how fees are applied when using these functions.

Best regards,

**Comment by xmatthias** [comment]
not sure what you mean with "profit in the log".
profit is usually relative - and fee is applied to the trade object - and hence to all profit calculations freqtrade does internally.

If you're doing profit calculations as part of your custom callbacks, then it's up to you to correctly implement this.

**Comment by thkwon9474** [comment]
There was uncertainty in conveying meaning.
what i would like to say, the mean of profit in the log is backtest results.

As you said, I calculated the "Open/Close Price + Cumission" inversion results from the backtest log match.

Thank you for always responding!!
