### ISSUE TITLE
default config path ignore env USERDIR

### ISSUE THREAD

**Issue by castorinop** [freqtrade/freqtrade#9991]
## Describe your environment

  * Operating system: docker
  * Freqtrade Version: freqtrade 2024.1 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

i have defined FREQTRADE__USERDIR but keeps load default path config
```
2024-03-22 22:45:04,029 - freqtrade - INFO - freqtrade 2024.1
2024-03-22 22:45:04,042 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2024-03-22 22:45:04,043 - freqtrade - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.
```

*Explain the problem you have encountered*

### Steps to reproduce:

  1. define service STRAT into docker compose with FREQTRADE__USERDIR custom path for config / strategies
```
    STRAT:
    profiles:
      - staging
    environment:
    - FREQTRADE__STRATEGY=STRAT_V3
    - FREQTRADE__USERDIR=/freqtrade/user_data/STRAT
     env_file:
    - .env
    image: freqtradeorg/freqtrade:${IMAGE_TAG:-2024.1}
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
```
  3. run docker compose service for backtesting `docker-compose run --rm STRAT backtesting --timerange 20230701-20240401` 
  4. `2024-03-23 00:01:59,500 - freqtrade - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.`
  5. if i override userdir throw command line works well. 
  6.  if create a empty config.json load this file and then load envs.
```
2024-03-23 00:02:25,082 - freqtrade - INFO - freqtrade 2024.1
2024-03-23 00:02:25,097 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2024-03-23 00:02:25,098 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__USERDIR'

```
### Observed Results:

  * What happened?
 dont load config from defined USERDIR env 
  * What did you expect to happen?
  load environment vars and then load default config using USERDIR if defined

**Comment by xmatthias** [comment]
That's only partially correct. 
USERDIR will be loaded correctly if an explicit config is provided - but it'll not work if you expect the configuration to be loaded from that location (providing config as environment variable will also not work).
That's because environment variables are read after the configuration - as you expect them to override the configuration, not viceversa.

You can however pretty easily work around this by providing the configuration explicitly (`--config ...`). the remaining userdir can then be set via environment variables.

I'll be updating the documentation to reflect this - but there's no intend to change behavior - hence i'll treat this as a question - with a documentation fix that'll close this.
